### ISSUE TITLE
Adding valid_principals to an ssh sign operation causes signing error

### ISSUE THREAD

**Issue by lhw** [hashicorp/vault#10068]
**Describe the bug**
Adding the `valid_principals` config value to a ssh engine role causes an client error.

**To Reproduce**
```
1. vault secrets enable ssh
2. ssh-keygen -C ca -t ed25519 -f ca -N '' 
3. vault write ssh/config/ca private_key=@ca public_key=@ca.pub
4. vault write ssh/roles/role allow_user_certificates="true" key_type="ca"
5. ssh-keygen -C user -f user -N ''
6. vault write ssh/sign/role public_key=@user.pub valid_principals="test" > FAILURE

Code: 400. Errors: role is not configured to allow any principles
```

**Expected behavior**
It signs the cert.
There is no documentation on any option for the ssh backend role to allow principals. But in case thats just a missing feature it would be great if we could limit the principals of certain roles by specifying a list on a per role basis.

**Environment:**
* Vault Server Version (retrieve with `vault status`): 1.5.4
* Vault CLI Version (retrieve with `vault version`): 1.5.4 (1a730771ec70149293efe91e1d283b10d255c6d1)
* Server Operating System/Architecture: Ubuntu 20.04.1

Vault server configuration file(s):
`vault server -dev`

**Additional context**

**Comment by pippo** [comment]
I wanted to contribute by digging into this, however it appears to be working as intended. Unless I'm missing something.

I'm guessing this might be caused by how a role is being created at step 4 of the steps provided.
```
# vault write ssh/roles/role allow_user_certificates="true" key_type="ca"
```
If I inspect the role, I see, e.g. that "allowed_users" property is undefined.
```
# vault read ssh/roles/role
Key                         Value
---                         -----
[...]
allowed_users               n/a
[...]
```
Eventually it fails to validate the "test" as principal name because, list of allowed user names is empty.
Changing the step 4 to the command below resolves the issue.
```
# vault write ssh/roles/role allow_user_certificates="true" key_type="ca" allowed_users="test"
```
(test could be a `*` too)

Looking at the examples in the [doc](https://www.vaultproject.io/docs/secrets/ssh/signed-ssh-certificates) I see that `"allowed_users": "*"` is explicitly specified when a role is created. Perhaps, documentation could be clearer on this aspect though.

Am I missing anything?

**Comment by lhw** [comment]
I think that's a misconception. Allowed users and principals are disjointed concepts.

A principal does not have to be a user, it's more of a role. For example if we have two different sets of nodes. Some for a Ceph Cluster and some for Kubernetes, all automatically deployed. Now the `allowed_user` root has a list of `user_principals` that allow connection for ssh certificates. i.e. `node-ceph01,superadmin,ceph` and `node-kube01,superadmin,kube`. So you can assign someone temporary permissions for one node, a set of nodes or to everything.

This allows you to have the option to assign people different roles based on their ssh certificate without managing users on the respective servers.

**Comment by lhw** [comment]
I think after some further testing that this is just an issue with naming. The UI actually shows the key as `valid principals` which maps to the role key `allowed_users`. If used with the replaced name as suggested by @pippo this feature works just fine. I don't know how much of an issue this is in the end. One one side its definitely the wrong name in the vault api but on the other hand its not much of an issue when the documentation would point it out as said by @pippo.

**Comment by lhw** [comment]
Im honestly fine with the solution for now. This might warrant a documentation entry but aside from that this does not seem like a "bug".
