### ISSUE TITLE
Unable to seal the vault in HA mode

### ISSUE THREAD

**Issue by georgerobinson** [hashicorp/vault#1006]
I'm running a small Vault cluster of 5 server nodes in HA mode. All 5 nodes are in the unsealed state. 

However, I'm currently unable to seal the vault. When I run `vault seal`, I get the following error message:

```
Error sealing: Error making API request.

URL: PUT http://127.0.0.1:8200/v1/sys/seal
Code: 500. Errors:

* internal error
```

and see the following log line in syslog:

```
Feb  1 15:50:52 vault[4820]: 2016/02/01 15:50:52 [ERR] core: token store is unavailable
```

I have no issue authenticating with Vault, reading, writing or deleting secrets, nor accessing the Consul key value store via the HTTP API.

**Comment by jefferai** [comment]
Hi @georgerobinson,

How are you running your other commands? I ask because although this is a strange state for Vault to be in, the same code path that prints that error is hit by every single authenticated command.

However, unlike many other commands, a seal command doesn't forward to the active node from a standby, and that forwarding happens before any authentication checks. So my guess is that the node you're trying to seal has been in a bad state for a bit but you didn't notice it because other commands were forwarding.

Do you have anything else of interest in the log? This is a very strange state for Vault to be in (where it's unsealed but has no token store in the core) so I would guess other parts of the log should have relevant information.

**Comment by georgerobinson** [comment]
Hi @jefferai,

I see no other errors in syslog apart from that single line. I ran commands via the CLI client (e.g. `vault write`) and via the HTTP API with `curl`. However, having played around with Vault over the last 10 minutes it appears to be directly related the high availability mode in Vault.

For example, I stopped Vault on all other nodes to force this node to become active. As the sole node in the cluster I can seal the vault.

In addition, if I boot up and unseal the other Vault servers, I am able to seal the vault only from the `active` server. Any attempt to seal the vault from a standby yields the same error.

I've pasted a log trace of a node below. I start will the vault service stopped in all nodes. I start Vault in this node first followed by the other four nodes. I then unseal Vault in the same order such that this node becomes the `active` server.

I then seal the vault from this node successfully, restart the Vault service with systemd, and then unlock it such that this node becomes a standby server. I then finally attempt to seal the vault from this node as a standby, but hit the same error.

```
Feb  1 16:41:48 node-1 vault[24597]: 2016/02/01 16:41:48 [INFO] core: vault is unsealed
Feb  1 16:41:48 node-1 vault[24597]: 2016/02/01 16:41:48 [INFO] core: entering standby mode
Feb  1 16:41:48 node-1 vault[24597]: 2016/02/01 16:41:48 [INFO] core: acquired lock, enabling active operation
Feb  1 16:41:48 node-1 vault[24597]: 2016/02/01 16:41:48 [INFO] core: post-unseal setup starting
Feb  1 16:41:48 node-1 vault[24597]: 2016/02/01 16:41:48 [INFO] core: mounted backend of type generic at logical/8d796d6a-eddd-d203-1a26-5ebab0059915/
Feb  1 16:41:48 node-1 vault[24597]: 2016/02/01 16:41:48 [INFO] core: mounted backend of type cubbyhole at logical/283c7dfe-179a-0ba7-5ca1-e8c307a82bfa/
Feb  1 16:41:48 node-1 vault[24597]: 2016/02/01 16:41:48 [INFO] core: mounted backend of type system at sys/
Feb  1 16:41:48 node-1 vault[24597]: 2016/02/01 16:41:48 [INFO] rollback: starting rollback manager
Feb  1 16:41:48 node-1 vault[24597]: 2016/02/01 16:41:48 [INFO] core: post-unseal setup complete
Feb  1 16:41:57 node-1 env[19088]: 2016/02/01 16:41:57 [INFO] agent: Synced check 'service:vault'
Feb  1 16:41:57 node-1 consul[19088]: agent: Synced check 'service:vault'
Feb  1 16:42:45 node-1 vault[24597]: 2016/02/01 16:42:45 [WARN] core: stopping active operation
Feb  1 16:42:45 node-1 vault[24597]: 2016/02/01 16:42:45 [INFO] core: pre-seal teardown starting
Feb  1 16:42:45 node-1 vault[24597]: 2016/02/01 16:42:45 [INFO] rollback: stopping rollback manager
Feb  1 16:42:45 node-1 vault[24597]: 2016/02/01 16:42:45 [INFO] core: pre-seal teardown complete
Feb  1 16:42:45 node-1 vault[24597]: 2016/02/01 16:42:45 [INFO] core: pre-seal teardown starting
Feb  1 16:42:45 node-1 vault[24597]: 2016/02/01 16:42:45 [INFO] core: pre-seal teardown complete
Feb  1 16:42:45 node-1 vault[24597]: 2016/02/01 16:42:45 [INFO] core: vault is sealed
Feb  1 16:42:47 node-1 env[19088]: 2016/02/01 16:42:47 [WARN] agent: check 'service:vault' is now critical
Feb  1 16:42:47 node-1 consul[19088]: agent: check 'service:vault' is now critical
Feb  1 16:42:47 node-1 env[19088]: 2016/02/01 16:42:47 [INFO] agent: Synced check 'service:vault'
Feb  1 16:42:47 node-1 consul[19088]: agent: Synced check 'service:vault'
Feb  1 16:42:57 node-1 env[19088]: 2016/02/01 16:42:57 [WARN] agent: check 'service:vault' is now critical
Feb  1 16:42:57 node-1 consul[19088]: agent: check 'service:vault' is now critical
Feb  1 16:43:07 node-1 env[19088]: 2016/02/01 16:43:07 [WARN] agent: check 'service:vault' is now critical
Feb  1 16:43:07 node-1 consul[19088]: agent: check 'service:vault' is now critical
Feb  1 16:43:17 node-1 env[19088]: 2016/02/01 16:43:17 [WARN] agent: check 'service:vault' is now critical
Feb  1 16:43:17 node-1 consul[19088]: agent: check 'service:vault' is now critical
Feb  1 16:43:26 node-1 vault[24597]: 2016/02/01 16:43:26 [INFO] core: vault is unsealed
Feb  1 16:43:26 node-1 vault[24597]: 2016/02/01 16:43:26 [INFO] core: entering standby mode
Feb  1 16:43:27 node-1 env[19088]: 2016/02/01 16:43:27 [INFO] agent: Synced check 'service:vault'
Feb  1 16:43:27 node-1 consul[19088]: agent: Synced check 'service:vault'
Feb  1 16:43:31 node-1 vault[24597]: 2016/02/01 16:43:31 [ERR] core: token store is unavailable
```

**Comment by jefferai** [comment]
What version of Vault is this? I'm running some tests against `master` and can't reproduce it.

**Comment by georgerobinson** [comment]
Vault 0.4.0.

**Comment by georgerobinson** [comment]
I can confirm that this also affects Vault 0.4.1.

**Comment by jefferai** [comment]
0.4.1 is exactly the same as 0.4 in terms of the Vault codebase so that's expected. It was simply built against a different Go version.

I'll be able to dig into this more on Wed. In the mean time, we released 1.5rc1 last night and did make some changes to the seal function so it's not impossible that it might fix your issue if you want/are able to test it.

**Comment by jefferai** [comment]
@georgerobinson OK, so this is known behavior but the error message has changed due to some logic changes, which is why I didn't think of the issue right away.

Basically, standby nodes have never really supported sealing, because sealing requires a token with appropriate privileges, and standby nodes do not have the token store available to them to check whether the token being provided is valid.

At the least I think I will ensure that the error message returned from this call is helpful (for instance, explaining that re-sealing a standby currently requires a restart of the Vault service).

**Comment by georgerobinson** [comment]
@jefferai O.K, just to make sure that the correct procedure for sealing the Vault in HA mode is to seal the master, wait for re-election, and the repeat until all Vault servers have been sealed. Please comment whether sealing the master (active server) is supposed to seal the standbys, because I can't replicate that behaviour on my cluster.

**Comment by jefferai** [comment]
Sealing is per-node, just like unsealing is per-node. It just can't be done right now on standbys.

Can I ask what your use-case is? Generally there isn't much use for sealing since Vault becomes inaccessible, and shutting down Vault performs the same sealing procedure. Usually we only see people having a sealed Vault when restarting it, and there's no need to manually seal prior to that.

**Comment by georgerobinson** [comment]
On the docs page https://www.vaultproject.io/docs/concepts/seal.html:

> There is also an API to seal the Vault. This will throw away the encryption key and require another unseal process to restore it. Sealing only requires a single operator with root privileges.

> This way, if there is a detected intrusion, the Vault data can be locked quickly to try to minimize damages. It can't be accessed again without access to the master key shards.

I was just thinking about how to easily lock down the Vault in the possible event of a security breach. It appears to be a much harder process when running in HA mode?

**Comment by jefferai** [comment]
I guess it kind of depends what you intend to do about it:

- If you want Vault to stay up and running while you investigate, there isn't much point in sealing it
- If you want client access to stop, since sealing Vault makes its store inaccessible, and thus it cannot respond to any requests other than for status and unsealing, there's not really any difference between shutting it down and sealing it
 - As a corollary, if you have running standbys and you seal the active node, one of the standbys will pick it up, which will allow client access

The only practical application I can think of for that API endpoint is if you want to enable users to seal Vault that do not have access to stopping the process itself, which could be used to force an active node switch, or to allow a security team to seal Vault without waiting for ops. In this specific kind of break glass scenario, I suppose the best you can do with the current capabilities would be to seal each node as it takes over active duty until there are no nodes left. Not ideal, but certainly something that can be codified into such an emergency process.
