### ISSUE TITLE
Enhancement to add headers into root path

### ISSUE THREAD

**Issue by naveensetty1** [hashicorp/vault#10206]
**Is your feature request related to a problem? Please describe.**

We have requirement to add security headers to root path of the vault. Able to add below headers into UI, however also need same to be added into Root/base URL as well.

Current Vault version: Vault 1.5.4+ent
Headers to be added: Strict-Transport-Security header = max-age=31536000; includeSubDomains on the 307 redirect response page 

**Describe the solution you'd like**
Provide api's at root path to add http headers at root page (where redirection to UI occurs)

**Describe alternatives you've considered**

Layer 7 load balancer is considered to define headers on LB, however layer 7 load balancer will not work , since load balancer does not pass the client certificate to Vault  in turn, Vault issues a "client certificate must be supplied" error

**Explain any additional use-cases**

This is best practice issue and when websites are open to internet, ,since a number of external posture vendors will still flag this URL with a control failure because the 307 Temporary Redirect response page is missing the Strict-Transport-Security header

**Additional context**

**Comment by aphorise** [comment]
Hey @naveensetty1 do you agree that this issue can be closed since [the `custom_response_headers` parameter](https://www.vaultproject.io/docs/configuration/listener/tcp#custom_response_headers-parameters) has been added as detailed in the documentation of tcp listener stanza:

 - [Configuring custom http response headers](https://www.vaultproject.io/docs/configuration/listener/tcp#configuring-custom-http-response-headers)

**Comment by aphorise** [comment]
Closing due to no follow-up. Kindly re-open if relevant again.
