### ISSUE TITLE
Windows 10 Error checking seal status: Get "https://127.0.0.1:8200/v1/sys/seal-status": http: server gave HTTP response to HTTPS client

### ISSUE THREAD

**Issue by KamranShahid** [hashicorp/vault#10304]
I am getting following error when trying to get status

![image](https://user-images.githubusercontent.com/2170442/97872904-9d568800-1d38-11eb-8dae-b74888ac42fc.png)

though my server seems to be running 

![image](https://user-images.githubusercontent.com/2170442/97872990-c37c2800-1d38-11eb-941b-ee66fd99f945.png)

**Comment by allthingsclowd** [comment]
Hi Kamaran,

I think there may be some confusion here between powershell in windows 10 with a typical linux shell found on non windows systems.

The `export` statement above in the example is not being recognised as it's for a linux shell like bash. Also the `set` command in powershell does not appear to work with environment variables.

There are a few options :
1. Install a linux like `bash` shell on windows and the examples should work
2. Use powershell's native `$env` command to set the correct address for Vault, possible something like `$env:VAULT_ADDR='http://172.0.0.1:8200'`
3. Use windows `cmd` shell rather than powershell

Apologies but I don't have access to a windows system to validate these suggestions.

**Comment by KamranShahid** [comment]
thanks
