### ISSUE TITLE
Web UI allows to enter comma-separated token policies

### ISSUE THREAD

**Issue by manderson-it** [hashicorp/vault#10346]
**Describe the bug**
When creating a new role for an Auth Method (e.g., Kubernetes) through the Web UI the Web UI EditField named **Generated Token's Policies** allows to enter comma-separated policies. This leads to a consistent Web UI display, but results in invalid referenced Vault policies.

**To Reproduce**
1. Web UI: Navigate to Access > Auth Method (e.g., Kubernetes)
2. Web UI: Click "..." > View Configuration > Tab Roles > Create Role
3. Web UI: Enter Name, Bound service account names, Bound service namespaces
4. Web UI: Expand Tokens to reveal EditField **Generated Token's Policies**
5. Web UI: Enter a comma-separated value referencing two different Vault policies 'default,helloworld' 

This results in a consistent display after the role has been created (see screenshot).
![vault-webui-bug-policies1](https://user-images.githubusercontent.com/8469956/98423982-5204e800-205e-11eb-9545-d86192424666.png)

EditField when comma-separating two different Vault policies in the field:
![vault-webui-bug-EditField-wrong](https://user-images.githubusercontent.com/8469956/98424033-7a8ce200-205e-11eb-97d2-ae03cb72ac02.png)

EditField when using the Add Button to the right:
![vault-webui-bug-EditField-correct](https://user-images.githubusercontent.com/8469956/98424049-84aee080-205e-11eb-9456-a33b33fa48bd.png)

**Expected behavior**
1. The Vault Web UI rejects any comma-separated input in the EditField **Generated Token's Policies**, or
2. the Web UI splits the comma-separated policies into two different entries, meaning one entry for each policy.

**Environment:**
* Vault Server Version (retrieve with `vault status`): 1.5.5
* Vault CLI Version (retrieve with `vault version`): 1.5.5
* Server Operating System/Architecture: Alpine

Vault server configuration file(s):

```hcl
# Paste your Vault config here.
# Be sure to scrub any sensitive values
```

**Additional context**
After enabling audit log with raw output, you can see what Vault consumed.
`vault audit enable file file_path=stdout log_raw=true`

"token_policies":["default,helloworld"] <---- this is invalid
versus
"token_policies":["default","helloworld"] <---- correct, notice the double-quotes before and after comma

**Comment by Monkeychip** [comment]
Hi @manderson-it, thank you for the issue.  This is a little confusing because we _do_ let you add commas in your policy names.  And then to make it more confusing, when the CLI encounters a comma in the string name it splits the values to make them more clear.  However, if you were to run a curl command, with a comma you would see that it accepts a string with commas in it.  So in the UI, when you enter a string with commas in it, it sends that as the payload in the POST and it's accepted.

1. Here is a gif of the UI making an API request with a policy that has commas in the name. 
<img width=400 src="https://user-images.githubusercontent.com/6618863/102386952-057dc800-3f8d-11eb-8a86-3bca2632eb77.gif">

2. Here is a gif of the curl command and the command itself.
<img width=400 src="https://user-images.githubusercontent.com/6618863/102388093-825d7180-3f8e-11eb-8b50-07f6717d51fa.gif">

I think we could make this more clear in the API documentation. Because as it reads now it says, [under `token_policies` ](https://www.vaultproject.io/api-docs/auth/kubernetes#token_policies) `(array: [] or comma-delimited string: "")`. If you want to test the API call, the documentation lists the curl command and payload I used.

Hope that helps!

**Comment by manderson-it** [comment]
@Monkeychip yes it is confusing, which is precisely why I opened this ticket.
Not sure we agree on what the issue is. The issue is that the Web UI in 1.5.5 doesn't sanitize the input in the EditField and allows the comma character as part of a Vault policy name, which to me seems like a bug. A Vault policy name "ImA,policy" should be rejected.
The impression the user gets from the Web UI though is that it correctly splits the string containing a comma into two different attached policies, which it doesn't in 1.5.5. This is why I opened the ticket.

So are you saying with your tested 1.6.0 version that the Web UI EditField does string sanitization now?

If it doesn't, then this is not resolved and should not be closed.
I am also open to a quick video or audio chat. Might be easier to express.

**Comment by Monkeychip** [comment]
Agreed, it's strange that we allow commas in policy names, but it's accepted.  I've confirmed with other devs that this is indeed intended behavior.  I have however generated a ticket to make will make the tooltip language on that specific field more helpful, clarifying that we _do_ allow commas in the name.  

So,  yes, you're correct. The web ui and the api does not sanitize a string when it contains a comma.  But it is not a bug, but intended behavior.  

Thank you for the feedback, and the ticket!

**Comment by manderson-it** [comment]
@Monkeychip appreciate the clarification! Thanks a lot! Have a nice weekend and hopefully some time off at the end of the year! 👍

**Comment by con-f-use** [comment]
> So, yes, you're correct. The web ui and the api does not sanitize a string when it contains a comma. But it is not a bug, but intended behavior.

But then this tooltip (which you said was incorrect) **is** the bug:

![image](https://user-images.githubusercontent.com/11145016/153263430-b8115c69-9738-4946-9a89-35bdc483d494.png)

> Comma-separated list of policies associated with the user.

Because that says, it is a list of policy names of which each items is separated with a comma character. So according to this "pol1,pol2,pol3" in this field should result in associating three policies, not a single one with commas. This is so confusing and sever, that once fixed, if a comma was entered, the user should be prompted, that will be in the policy name and not result in an additional associated policy.

**Comment by con-f-use** [comment]
@manderson-it please reopen this until it's fixed.

**Comment by hsimon-hashicorp** [comment]
@con-f-use we are discussing this now - re-opening, thank you for bringing this up again!

**Comment by hellobontempo** [comment]
Related to https://github.com/hashicorp/vault/issues/19451
