### ISSUE TITLE
Inconsistencies in Transit engine for keys read & export operations

### ISSUE THREAD

**Issue by ppiotr3k** [hashicorp/vault#10352]
**Describe the bug**
Depending on key type (RSA vs _other supported types_) [public key is either presented](https://github.com/hashicorp/vault/blob/master/builtin/logical/transit/path_keys.go#L266-L343) as base64-encoded raw key bytes or PKIX container. Same goes with [private key presented](https://github.com/hashicorp/vault/blob/master/builtin/logical/transit/path_export.go#L152-L192) either as base64-encoded raw key bytes or PKCS#1 container. While exporting a symmetric key in b64-encoded raw bytes is common practice, having for example RSA and ED25519 key-pairs handled inconsistently appears to me as an unwanted behavior.

**To Reproduce**
1. Run `vault secrets enable transit`
2. Run `vault write transit/keys/ed25519 exportable=true type=ed25519`
3. Run `vault write transit/keys/rsa2048 exportable=true type=rsa-2048`
4. Run `vault read transit/keys/ed25519`
5. See public key in base64-encoded raw bytes form
6. Run `vault read transit/keys/rsa2048`
7. See public key in PKIX, ASN.1 DER form

Similar inconsistency goes with export operations, for example with `vault read transit/export/signing-key/...`

**Expected behavior**
All asymmetric key types to be presented in a consistent manner when read/exported.
Ideally with the ability to select either a b64-encoded raw bytes form, or PKIX/PKCS#1/PKCS#8 form.

**Environment:**
* Vault Server Version (retrieve with `vault status`): **1.6.0-dev** (building from master, `make dev`)
* Vault CLI Version (retrieve with `vault version`): **v1.6.0-dev** ('3e803c2a571f414950b03416160aa8d90f93ade0+CHANGES')
* Server Operating System/Architecture: 5.4.0-52-generic SMP x86_64 GNU/Linux

Vault server configuration file(s): none, directly using `make dev && vault server -dev -dev-root-token-id="root"`

**Additional context**
Observed initially in `vault 1.5.4` while developing a system where Vault is used for signing operations, but signature verifications have to be performed elsewhere, requiring public keys to be made available outside of Vault itself.
Led to digging in Vault's source code and testing against latest `master` branch, discovering at the same time [this comment](https://github.com/hashicorp/vault/blob/master/builtin/logical/transit/path_export.go#L195-L196); this code has been introduced 3 years ago, and the [used Go module does since have support for PKCS#8](https://golang.org/pkg/crypto/x509/#MarshalPKCS8PrivateKey) indeed :smiley:

**Comment by ppiotr3k** [comment]
While not (yet?) a Go developer myself, I started tinkering with code from `master` branch to by default export ED25519 public keys in PKIX form, to be consistent with default for RSA public keys; and experimenting at the same time with exporting private keys not only in PKCS#1 but also PKCS#8 - thus the `CHANGES` visible in the Vault version I'm running.

However, I totally realize such changes can break integrations/assumptions with Vault that have been made so far.
For example if people expect RSA private keys to be exported as PKCS#1, while ED25519 private signing-keys to be exported as b64-encode raw key bytes :thinking:... 
Hopefully, `backup` and `restore` operations doesn't seem to be affected as they seem to always use b64-encode raw key bytes.

Thus me turning here for guidance and discussion, before even proposing any kind of PR, as IMHO these inconsistencies and the way to handle them required some prior thinking :pray:

**Comment by cipherboy** [comment]
\o hey @ppiotr3k

I don't think we're going to implement this as, as you said, this would be a breaking change without additional API work that wouldn't be very discoverable (e.g., a `encode_ed25519_in_pkix=true` option or some such).

I think here you're running into what's an interesting observation of historical quirks, protocol design choices, and the intersection between many, many different systems. Certainly, when Ed25519 keys are used in X.509 certificates, they are PKIX marshalled. And NIST P-curve keys _generally_ tend to be PKIX marshalled as well, outside of a few protocols where they're explicitly identified for. However, outside of X.509, a lot of people and protocols prefer direct wire encodings (i.e., byte arrays) to PKIX-wrapped wire encodings _for Ed25519 keys_ and so I think the choice in Transit was made to conform to that. And, you can always PKIX-encode your Ed25519 key yourself, if you desire.

Indeed, our plaintext backup uses the native storage format, where `key` is a byte array, not a complex PKIX encoded variant (the 64 bytes come about because the 32-byte private key is concatenated with the 32-byte public key, not some PKIX ASN.1 wrapper object).

So I don't think we'll be likely to implement this. 

...That said... :-)

The new [BYOK export API](https://github.com/hashicorp/vault/blob/main/website/content/api-docs/secret/transit.mdx#securely-export-key) ([live docs site when up](https://developer.hashicorp.com/vault/api-docs/secret/transit#securely-export-key)) does use the BYOK format, which does require Ed25519 keys to be PKIX encoded. It does require a public key to encrypt to as it is not a plaintext export, but an encrypted export. In general though, for most users I'd recommend an encrypted key portability option over a plaintext export or backup. 

So give that a shot and let us know if it works out for you!
