### ISSUE TITLE
Vault 1.6 breaks mysql-legacy-plugin

### ISSUE THREAD

**Issue by james-atwill-hs** [hashicorp/vault#10476]
**Describe the bug**

The username that gets created for mysql legacy database plugin now follows the format "v-<authmethod>-<identifier>-<maybesomethingelse>", but it's truncated at 16 characters, so it's often "v-<authmethod>-<ide", which prevents the same Vault consumer (service/user) from having multiple simultaneous logins.

**Comment by pcman312** [comment]
Thanks for reporting this @james-atwill-hs ! Could you provide details about your setup? Specifically: what version of MySQL you are using, the database configuration, and the role configuration. Thanks!

**Comment by james-atwill-hs** [comment]
The two old versions we've got are MySQL 5.1, and 5.6. 

The DB is configured as:
```
$ vault read mysql-bastion/config/mysql
Key                                   Value
---                                   -----
allowed_roles                         [*]
connection_details                    map[connection_url:{{username}}:{{password}}@tcp(mysql-staging.cluster-nopenopenope.us-east-1.rds.amazonaws.com:3306)/ username:xxxxxxxxxxxxxxx]
password_policy                       n/a
plugin_name                           mysql-legacy-database-plugin
root_credentials_rotate_statements    []
```

The role I'm testing against is pretty generic. I'm auth'd via an ldap authn backend, so the error I get when I run **vault read .../creds/..**. a _second_ time is:

```
* 1 error occurred:
	* Error 1062: Duplicate entry 'v_ldap-james.atw' for key 'user'
```

**Comment by james-atwill-hs** [comment]
Are there mount-point/database/role flags to control how usernames are generated or should I rollback to 1.4.7?

**Comment by james-atwill-hs** [comment]
AFAICT, usernames are configured here: https://github.com/hashicorp/vault/blob/master/plugins/database/mysql/mysql.go#L123

and ultimately generated on L133. 

I can't see a way of using the old-style username generation (just a random ~b64 string) for usernames.

This prevents multiple services of the same name from creating credentials. This also prevents, in some cases, any two services authenticated by a longer backend (`v_kubernetes_staging_c1_service_name` becomes `v_kubernetes_sta`) from getting credentials.

**Comment by pcman312** [comment]
Thanks for the details! I'm looking into it now. I suspect this is a bug that is fixed with https://github.com/hashicorp/vault/pull/10433

Re: controlling how a username is generated:
We are looking into adding the ability to customize how usernames are generated in a near-future release, however there are no controls over this at the moment. Each username uses the display name of the token making the query against Vault as well as the name of the database role, but the only way of controlling any part of the username is to change the name of the role in Vault. That role name is truncated to a different length depending on which database you are using (in this instance it's truncated to 4 characters because older versions of MySQL limit usernames to very small number of characters).

**Comment by pcman312** [comment]
Based on your comment about `v_kubernetes_staging_c1_service_name` becoming `v_kubernetes_sta I'm confident that the PR I linked (#10433) is a fix for this issue.

For legacy MySQL, usernames are generated as follows:

`v-{role name}-{20 random characters}-{current timestamp}` (and truncated to 16 characters)
The role name is truncated to 4 characters in order to keep some part of the randomly generated characters intact. The bug here is the display name associated with the token used to query Vault should be getting stripped out but isn't. This results in a username like `v-kubernetes_staging_c1_service_name-my_vault_role_name-h8owigtjuVSja9sfvSVD-1234567890` which is then truncated to 16 characters: `v-kubernetes_sta`

Apologies for breaking this in 1.6! The fix for this should be in an upcoming release. At this time I recommend rolling back from 1.6. Vault 1.5.x does not have this bug if you wish to roll back to this point.

**Comment by james-atwill-hs** [comment]
Perfect. Thanks for the speedy responses! It'd be great to have an explicit test for this scenario in #10433 - just in case there's a refactoring in the future.

I'll look into rolling back.

**Comment by pcman312** [comment]
I was just thinking the same thing! As a part of the username customization I was thinking about how we could go about protecting against this scenario.

If you have a moment, I'd love to hear if you have any particular desires for custom username generation. Have you had the need for this (other than this issue)? If so, what was the problem with the current username generation?

**Comment by james-atwill-hs** [comment]
@pcman312 Until today I hadn't given it much thought - but I do see this as something that bubbles up in various places (the name displayed (which i'm guessing is from the associated lease) in the aws console to users who get aws creds through sts:assumerole, etc, etc). 

My use case today was to work around this bug without having to rollback. My only feedback would be that most systems truncate long usernames in the UI, so "v-james.atwill-aws-assume-role-abcabcabca" is better than "v-aws-assume-role-james-atwill-abcabca" (or even "v-aws--james-atwill-abcabc").
