### ISSUE TITLE
Large mount of view keys, causing unmount issues

### ISSUE THREAD

**Issue by waiariki-koia** [hashicorp/vault#10481]
**Describe the bug**
We tried to disable/remove a pki secret engine, first using Terraform and then manually using `vault secrets disable pki/<identifier>`. When we tried to do this, we received the error `context deadline exceeded`.

When looking in the logs, we noticed;
```
{"@level":"debug","@message":"clearing view","@module":"core.secrets.deletion","@timestamp":"2020-12-01T11:36:04.756294Z","namespace":"root","path":"pki/<identifier/","total_keys":1461754}

{"@level":"error","@message":"failed to clear view for path being unmounted","@module":"core","@timestamp":"2020-12-01T11:37:32.709597Z","error":"http://<IP_ADDRESS:PORT>/v1/kv/HIDDEN/logical/1234-abcd-56ef-gh78-12345abcde/certs/1a-2b-3c-4d-5e-6f-7g-8h-9i-0j-1k-2l-3m-4n-5o-6p-7q-8r-9s-0t: context canceled","path":"pki/<IDENTIFIER>/"}

{"@level":"error","@message":"unmount failed","@module":"secrets.system.system_63b37468","@timestamp":"2020-12-01T11:37:32.709641Z","error":"Delete http://<IP_ADDRESS:PORT>/v1/kv/HIDDEN/logical/1234-abcd-56ef-gh78-12345abcde/certs/1a-2b-3c-4d-5e-6f-7g-8h-9i-0j-1k-2l-3m-4n-5o-6p-7q-8r-9s-0t: context canceled","path":"pki/<IDENTIFIER>/"}
```

**To Reproduce**
1. Create PKI backend with 1.4 million keys
2. Run `vault secrets disable pki/<IDENTIFIER>`
3. See error

**Expected behavior**
Not get to 1.4 million keys
Successfully clean up/disable secret engine.

**Environment:**
* Vault Server Version (retrieve with `vault status`): v1.4.2
* Vault CLI Version (retrieve with `vault version`): Vault v1.3.0
* Server Operating System/Architecture: Flatcar Container Linux by Kinvolk 2512.4.0 (Oklo)

Vault server configuration file(s):

```hcl
api_addr = "https://VAULT_ADDR"
cluster_addr = "https://<IP_ADDRESS:PORT>"
storage "consul" {
  address = "<IP_ADDRESS:PORT>"
  path    = "vault-name"
  service = "vault-name"
}

telemetry {
  statsd_address = "statsd:9125"
  disable_hostname = true

}

listener "tcp" {
  address = "0.0.0.0:8200"
  tls_key_file = "/etc/ssl/key-path"
  tls_cert_file = "/etc/ssl/cert-path"
  tls_disable_client_certs = true
}

seal "awskms" {
  region     = "<AWS_REGION>"
  kms_key_id = "<KMS_KEY_ID>"
}

log_level = "Debug"
log_format = "json"
```

**Additional context**
- Why would our total_keys value would be so large and is there anyway to minimize this, as this could cause issues for other unmounting attempts.
- What is a view?
- What are these keys?
- Is there any documentation around this that I may have missed?

**Comment by HridoyRoy** [comment]
Hi @waiariki-koia , this is a very interesting issue. I will raise it with the team. Thanks!

**Comment by HridoyRoy** [comment]
Hi @waiariki-koia , after discussing with the team, I've learned that unmounting includes a storage wipe, which takes time due to the number of keys for this mount. To resolve this issue one would need to increase the request timeouts for the unmount request: https://learn.hashicorp.com/tutorials/vault/performance-tuning?in=vault/operations#maximum-request-duration and  https://www.vaultproject.io/docs/commands#vault_client_timeout. 

Please let us know if that resolved the issue. Thanks!

**Comment by vishalnayak** [comment]
Issues that are not reproducible and/or not had any interaction for a long time are stale issues. Sometimes even the valid issues remain stale lacking traction either by the maintainers or the community. In order to provide faster responses and better engagement with the community, we strive to keep the issue tracker clean and the issue count low. In this regard, our current policy is to close stale issues after 30 days. Closed issues will still be indexed and available for future viewers. If users feel that the issue is still relevant but is wrongly closed, we encourage reopening them.

Please refer to our [contributing guidelines](https://github.com/hashicorp/vault/blob/main/CONTRIBUTING.md) for details on issue lifecycle.
