### ISSUE TITLE
Website download section still refer to 0.4.1

### ISSUE THREAD

**Issue by jhaals** [hashicorp/vault#1051]
Can't wait to get my hands on 0.5.0 :ship: :+1:

**Comment by OWSM** [comment]
:+1:

**Comment by jefferai** [comment]
@jhaals It wasn't released 3 hours ago  :-)

**Comment by OWSM** [comment]
@jhaals it's listed in the releases page on GitHub as 4 hours ago...

**Comment by jefferai** [comment]
FYI, GitHub is just listing tags; we do not use GitHub for releases. Until we announce the release via the mailing list/blog post, it isn't final. In particular, we have rebuilt the tag/packages a few times over the last couple of days for various reasons. It is final now, though, and the download links are updated  :ship:

**Comment by jhaals** [comment]
Upgraded today and people are super happy with the new list feature :)

**Comment by OWSM** [comment]
Reading the changelog now. Also looking for that mailing list

**Comment by jefferai** [comment]
@jhaals Cool! Please do note for the future though that even if you see a tag on the GitHub page, that tag may float until we arrive on a final build. So a tag is indicative that a release is coming up, but not necessarily indicative of the final commit/packages.

**Comment by jhaals** [comment]
Sure! I will keep that in mind. Does that go for the fastly packages as
well?

**Comment by jefferai** [comment]
@jhaals Yeah -- when we make packages they go up on releases.hashicorp.com after the tag goes up, but they may be replaced with newer versions as well. Once we announce the release through official channels, you're golden.

**Comment by mikemcquaid** [comment]
@jefferai Note that generally repushing tags is a bad idea when using Git. If I've fetched a repository (and thus the tags) and then fetch it again then tags won't be updated locally. This also messes with projects like Homebrew that try to use tags for stable downloads from GitHub.

**Comment by jefferai** [comment]
Hi @mikemcquaid,

We try to refrain but sometimes after our initial packaging when we're prepping for release we find something that we don't want to wait until the next release, so we re-roll. Note that we use annotated tags which AFAIK should be properly re-fetched when using `git fetch --tags`.

I looked at the linked issue. The commit message is half right; it seems Homebrew jumped the gun rather than waiting for our official release announcement. However, we _do_ use GitHub for official release tags.

**Comment by DomT4** [comment]
Thanks @jhaals.

>  it seems Homebrew jumped the gun rather than waiting for our official release announcement.

The problem on our side is that we rely on external contributors to handle most of our package updates, because there's only ~10 of us (who aren't all active) and 3000+ packages, so we more or less have to trust people and on GitHub many users are used to taking tags as cut releases. I added some package notes on our side here so people do that less, hopefully.

> However, we do use GitHub for official release tags.

That's what I get for only glancing through the Issue, apologies.

**Comment by jefferai** [comment]
@DomT4 No problem!  (And as a user of Homebrew and a long time Linux user I understand the hassles and time sink of being a packager and handling proposed package updates -- your work is much appreciated!).

It's unfortunate when we have to reroll releases, but in this case we had a non-final tag and non-final binaries up for a couple of days (whereas normally if we have to reroll the package it will be immediate) because of a hard deadline for engaging auditors -- something we did for 0.2 and again for 0.5 (will officially be announced with 0.5.1). We found some documentation errors after the initial tag that affected compiled-in help that we wanted to fix, since they related to changed behavior and we got actual reports from RC testers of confusion.

We do provide official builds on our release site, and we do provide official announcements via our blog and our mailing list, so if we haven't announced it yet, any indications of release should be considered unofficial. Upstreams are humans too and we do make mistakes, so it's very nice to us if people give us a chance to fix our mistakes before packaging. At the same time, we're very grateful to both our packagers and our users for their enthusiasm! :100:

**Comment by mikemcquaid** [comment]
> Note that we use annotated tags which AFAIK should be properly re-fetched when using git fetch --tags.

@jefferai There's an important point here (that I tested again locally to reconfirm): if I `git fetch`: all the tags are fetched. If I `git fetch` again: all tags are fetched but there's no sign that you have updated upstream tags unless I `git fetch --tags` (which I wouldn't know to do without knowing that you've changed a tag). It's also for this reason that updating a tag requires you to use `git push --force` (or equivalent): changing tags in Git should be considered similarly to other types of history rewriting.

It'd be great for projects like Homebrew if you could use a `.GM1` (gold master) for a tag that you expect might be the release tag but isn't ready for full release. Otherwise, I suspect people will continue to submit tags that aren't considered ready (but semver makes them look ready) and we'll end up accidentally including them.

**Comment by jefferai** [comment]
Hi @mikemcquaid 

As I said, I'll try to ensure on our end that tags aren't pushed before final packages are ready.

That said, we're not the only project that has had to reroll a release. When you're packaging a project you want to ensure that your code state matches the upstream's. If the upstream releases source tarballs, that's easy (unless you jump the gun before the release is official, of course); if the upstream is in Git, I would expect that one of the following would be the norm:

1) `git fetch --tags; git checkout v0.5.0` if you want to use a tag
2) Directly checking out the actual revision denoting the release (we always have an empty commit indicating the release)
3) Performing a fresh clone before checking out the tag

Any of these three would ensure sane code state, and that's a basic packaging essential. I don't know what method the packager for Vault was using, but it clearly wasn't one of those, *and* they jumped the gun and packaged ahead of our release announcement. We can try to be nicer about when we push tags, but this shouldn't have been a problem in the first place.

**Comment by mikemcquaid** [comment]
> As I said, I'll try to ensure on our end that tags aren't pushed before final packages are ready.

Thanks!

> That said, we're not the only project that has had to reroll a release.

Sure; I've created similar issues with them before :wink: 

> We can try to be nicer about when we push tags, but this shouldn't have been a problem in the first place.

If you're on GitHub generally https://github.com/hashicorp/vault/releases is taken as being at least somewhat authoritative and indicative of the current releases. We use the tarballs that are generated by the tags for packaging.

**Comment by jefferai** [comment]
> If you're on GitHub generally https://github.com/hashicorp/vault/releases is taken as being at least somewhat authoritative and indicative of the current releases. We use the tarballs that are generated by the tags for packaging.

If we could turn this feature off, we would, but I have never seen a way to do so. It is not and has never been indicative for us, and should not be used by packagers. We officially announce releases on several channels when they are final. Whoever is responsible for packaging Vault should be aware of this, just as they would familiarize themselves with the release process for projects that do not have their code bases hosted on GitHub.

**Comment by DomT4** [comment]
A lot of people don't understand the nuance, to be fair. The logic broadly is that if people see it on the upstream website or git repo they presume the tag to be stable unless labelled otherwise. I understand this is frustrating from a package manager and upstream perspective, but by and large people don't want to and don't spend a lot of effort investigating versions available.

Nonetheless, hopefully this won't happen again with the explicit warning in our vault package file.

**Comment by jefferai** [comment]
@DomT4 I don't have much experience with Homebrew packaging compared to Linux distro packaging, but the logic you mentioned is very much not the broad case there. A packager responsible for a particular piece of software is also responsible for understanding the upstream release process for that software.

I just took a look at the formula. Can I ask, is there a reason that the formula doesn't simply pull down our official binary, verify the PGP signature and the SHA256, unzip, and put the file into the right place? This would both make it easy to upgrade to new versions -- upon (official! :-) ) release, simply update the version number used in the download URL; and, it would make it easier for us to support, since right now we don't actually know what's going into the bottle builds. If we know someone is using the binary we built, it removes one possible difference when trying to reproduce reported behavior.

**Comment by DomT4** [comment]
OS X packaging is a different beast to Linux packaging, to be honest. People who use Linux _tend_ to be _generally_ more tech savvy and familiar with pre-GitHub ways of operating.

In regards to formal Linux distros, such as Debian, they often have semi-formal maintainers who oversee an individual or small group of software; Homebrew is considerably more casual in terms of contributor regularity and consequently doesn't have a strict system of Bob is responsible for OpenSSL and Alice is responsible for LibreSSL, etc. We just don't have the same regular resources as even some of the smaller Linux distros.

I'd wildly guess that at least 30% of the version updates we handle are just people interested in `vault`, for example, and see there's a new tag on the repo/site and submit it to us as their first or second contribution.

> Can I ask, is there a reason that the formula doesn't simply pull down our official binary, verify the PGP signature and the SHA256, unzip, and put the file into the right place?

We don't do upstream binaries because we have no control over them.

We're not beholden on upstream to push new releases to fix problems, which is useful when a big chunk of upstreams aren't as active as you folks and if there's a security fix committed for example we can pull the diff, apply it and force the rebuild and we can do that pretty quickly because all we have to be concerned about is one platform.

We can't do anything with upstream binaries beside shrug and tell people to wait for upstream to fix the problem, and that's fairly bad UX in terms of package management.

**Comment by jefferai** [comment]
@DomT4 I see...Homebrew is pretty big so I thought it was more formalized in terms of packager responsibilities. I figured that the more casual parts were relegated to Cask  :-)

> We can't do anything with upstream binaries beside shrug and tell people to wait for upstream to fix the problem, and that's fairly bad UX in terms of package management.

It's true -- I was thinking more specifically for Vault (rather than in a general sense) as we are quite active. Since it's a single binary, we can pretty easily ask people to try out the official builds if they are hitting some problem we are having trouble reproducing, but often we don't know if they are using a non-official build in the first place.

**Comment by mikemcquaid** [comment]
Without boring you too much as to the reasons why: we prefer to build our own binaries from source.

**Comment by DomT4** [comment]
> Homebrew is pretty big so I thought it was more formalized in terms of packager responsibilities. 

We are largely where we are because of community enthusiasm; in terms of resources we have ~10 core maintainers and a small CI infrastructure. In an ideal world we'd have the funding to expand our resources significantly, but such is FOSS :smiley:.

> but often we don't know if they are using a non-official build in the first place.

Some formulae support passing a tag to the tool's version output to deal with this, so we can tag things `vault 0.5.0 (Homebrew)` or such. I'm not that intimate with Go but I believe it requires upstream cooperation to support.

**Comment by petems** [comment]
I made a quick custom brew formula that allows you to "build" by downloading the prebuilt binaries and moving them to the Homebrew bin.

https://github.com/petems/homebrew-vault-prebuilt

Right now the Vault UI won't work with a brew installed vault as it's not built with the flags, and that process to build with the UI manually isn't fully documented yet (https://github.com/hashicorp/vault/issues/4295)
