### ISSUE TITLE
HTTP rekey/init API does not return nonce

### ISSUE THREAD

**Issue by mwielgoszewski** [hashicorp/vault#1054]
The rekey/init HTTP API in Vault 0.5.0 does not return a nonce.

~~~
$ curl -i http://127.0.0.1:8200/v1/sys/rekey/init -XPUT --data '{"secret_shares": 1, "secret_threshold": 1}'
HTTP/1.1 204 No Content
Content-Type: application/json
Date: Wed, 10 Feb 2016 20:55:41 GMT
~~~

Note, to get the current nonce, you have to make a second (GET) request to the API:

~~~
$ curl -i http://127.0.0.1:8200/v1/sys/rekey/init
HTTP/1.1 200 OK
Content-Type: application/json
Date: Wed, 10 Feb 2016 20:56:32 GMT
Content-Length: 141

{"nonce":"1646890b-ede8-26b3-84b5-d96e62bfabf7","started":true,"t":1,"n":1,"progress":0,"required":3,"pgp_fingerprints":null,"backup":false}
~~~

It is still possible for an attacker to reset the rekey process when initiated using the HTTP API.

**Comment by jefferai** [comment]
Good point. Fortunately, as this would happen before the process had started (rather than an attacker performing a switch in the middle) I don't think it's anything to worry much about; the original issue had a limited scope to begin with, and this is only useful if an attacker resets the process between the initiator doing a put and a get. But we'll definitely fix this for 0.5.1.
