### ISSUE TITLE
"vault status" help is incorrect

### ISSUE THREAD

**Issue by blalor** [hashicorp/vault#1056]
In 0.5.0, the `vault status` help output is incorrect:

```
vault status -h
Usage: vault status [options]

  Outputs the state of the Vault, sealed or unsealed and if HA is enabled.

  This command outputs whether or not the Vault is sealed. The exit
  code also reflects the seal status (0 unsealed, 1 sealed, 2+ error).
```

In practice:
```
[ec2-user@vault-server-dbf7885b ~]$ VAULT_ADDR=https://$(hostname -f):8200/ vault status
Sealed: true
Key Shares: 5
Key Threshold: 3
Unseal Progress: 0

High-Availability Enabled: true
	Mode: sealed
[ec2-user@vault-server-dbf7885b ~]$ echo $?
2
```

#1040 helped me figure this out, because I find the changelog to be confusing.

**Comment by jefferai** [comment]
What does `vault version` say for `ec2-user@vault-server-dbf7885b`?

**Comment by blalor** [comment]
```
[ec2-user@vault-server-dbf7885b ~]$ vault version
Vault v0.5.0
```

**Comment by jefferai** [comment]
When did you download it?

**Comment by blalor** [comment]
at 12:16:26 UTC today.

**Comment by jefferai** [comment]
That is...very strange.

**Comment by jefferai** [comment]
Let me look into it.

**Comment by blalor** [comment]
I even validated the GPG signature of the hash. :-) The output includes when the signature was made.

```
    gpg: WARNING: standard input reopened
    gpg: Signature made Mon 08 Feb 2016 12:59:47 AM UTC using RSA key ID 348FFC4C
    gpg: Good signature from "HashiCorp Security <security@hashicorp.com>"
    gpg: WARNING: This key is not certified with a trusted signature!
    gpg:          There is no indication that the signature belongs to the owner.
    Primary key fingerprint: 91A6 E7F8 5D05 C656 30BE  F189 5185 2D87 348F FC4C
```

**Comment by jefferai** [comment]
Chalk this up to a big "doh".

What happened is we had a couple of unreleased builds of 0.5 -- not uncommon as we prep for a release and as we figure out last minute website fixes, changelog entries, etc. The release process does the signed commit/tag, package building, package signing, and package uploading. Once we're happy with everything, we announce the release, and it's official.

What I didn't know at the time (but do now) is that the process will purge our Fastly index cache but not the cache for the binaries themselves. Normally this isn't a problem, because we don't have these last minute changes to the actual code. In this particular case, there was one singular code change that was made between binary builds: updating the help text of `vault status`. So, not knowing about not purging the binaries, I thought the final build reflected the final state of the code.

I've purged this cache; I don't at all like changing the binaries after the fact, but there was a chance it would be purged at some point anyways, and better to have them switch over now than at some future random time.

Very sorry about this. If you re-download 0.5 you'll see the fixed status help text. Thanks so much for bringing this to our attention!
