### ISSUE TITLE
In OIDC auth, if user has more than one roles, the group_claim is not matching with 2 group-aliases.

### ISSUE THREAD

**Issue by josedev-union** [hashicorp/vault#10667]
I am realizing OIDC authentication using keycloak.
When the user has only one role in keycloak and the group & group-alias are configured with the same name with role, the authorization and authentication seems good.
But when the user has 2 roles in keycloak, the user has no permission.
Of course, the group and group-aliases for 2 roles are created in vault side. None of 2 policies are not granted to the user.

**Comment by HridoyRoy** [comment]
Hi @josedev-union , could you paste the two outputs when running vault login with the oidc method (first output for the user with only 1 role, and the second output for the user with 2 roles)? 

A runbook of the commands used with keycloak and vault would also be helpful so we can replicate this exact behavior on our end. 

Thanks so much!

**Comment by josedev-union** [comment]
Let me make a test again and upload it.

**Comment by vishalnayak** [comment]
Closing the issue due to staleness.

Closing stale issues helps us keep the issue count down and the project healthy. Keeping the issue count under a manageable number helps us provide faster responses and better engagement with the community.

If you feel that the issue is still relevant, or if it is wrongly closed, please leave a comment and we'd be happy to reopen it.

**Comment by NagenderPulluri** [comment]
+1
