### ISSUE TITLE
Vault Agent Not Respecting Certificate Expiry Date and Renews Certs while renewing Token

### ISSUE THREAD

**Issue by venky999** [hashicorp/vault#10676]
**Describe the bug**

Vault Agent Not Respecting Certificate Expirty and Renews Certs as before Token Expiry.

1. Created a aws auth method with token TTL 1hour
2. Certs are configured with TTL of 30 days.

The vault agent is updating certs every 1 hour instead of may be before 7 days of cert expiry.

**To Reproduce**

1. Created a aws auth method with token TTL 1hour
2. Certs are configured with TTL of 30 days.

Followed the example Here.
https://github.com/hashicorp/consul-template/blob/master/examples/vault-pki.md

**Expected behavior**
The vault agent should update cert before 7 days of cert expiry. A new token should be generated before it expired but 
the cert should be generated 7 days before cert expiry.

**Environment:**
* Vault Server Version: 1.5.4
* Vault CLI Version : 1.3.0
* Server Operating System/Architecture: Centos

**Comment by HridoyRoy** [comment]
Hi @venky999 , thanks for raising this issue. It looks like a bug to me: from https://github.com/hashicorp/consul-template , it seems like "Consul Template will renew the secret with Vault's Renewer API. The Renew API tries to use most of the time the secret is good, renewing at around 90% of the lease time (as set by Vault).", which means that Vault should not be renewing certificates every hour. 

I will see if I can repro the issue, and keep the Issue updated. 

Thanks!

**Comment by venky999** [comment]
Hi @HridoyRoy 

Thank you for looking into it

I am using config like below

`auto_auth {
    method "aws" {
        mount_path = "auth/aws"
        config = {
            type = "iam"
            role = "dev-role-iam"
        }
    }

    sink "file" {
        wrap_ttl = "5m"
        config = {
            path = "/home/ubuntu/vault-token-via-agent"
        }
    }
}

vault {
  address = "http://10.0.101.53:8200"
}`

and pki example here https://github.com/hashicorp/consul-template/blob/15e145a77fa4b4ffcec9892843543cfed8c70410/examples/vault-pki.md

and my PKI role doesn't have generate_lease field set

**Comment by d-honeybadger** [comment]
Hi @HridoyRoy!

Experiencing the same problem with AppRole auth. Relevant config:
```
auto_auth {
  method "approle" {
    mount_path = "auth/approle"
    config = {
      role_id_file_path = "/opt/vault_agent_credentials/data_member/role_id"
      secret_id_file_path = "/opt/vault_agent_credentials/data_member/secret_id"
      remove_secret_id_file_after_reading = false
    }
  }
  sink "file" {
    config = {
      path = "/opt/vault_agent_credentials/data_member/token"
    }
  }
}
```
The certs are valid fro 30 days. The token generated from AppRole auth is a batch token with 4h ttl though. So, instead of renewing the cert ~7 days before expiry, vault agent renews it every time it re-authenticates with approle.

**Comment by ncabatoff** [comment]
I think @d-honeybadger was correct and this is basically the same as #11030.  @venky999, if your token isn't renewable, Agent will have to re-authenticate when the token expires.  When it does so, it restarts its internal template service, which is probably why your certificates are getting re-issued.  I suggest as a workaround you modify your aws auth role to use renewable tokens.  I'm going to close this issue, because the work to improve the Agent behaviour will be done as part of #11030.
