### ISSUE TITLE
Cannot specify a fixed database password

### ISSUE THREAD

**Issue by q1979635364** [hashicorp/vault#10680]
**Describe the bug**
When I use the Database secret engine, I cannot specify a fixed Database password in the 'creation_statements' parameter.

**To Reproduce**
Environment to prepare
1. Create user of mysql. Run `create user 'vault' identified by '123456';grant select,create user on *.* to 'vault'@'%' with grant option;`
2. Start Vault by `config.hcl`file. Run `vault server -config=config.hcl && vault operator init`.
```
storage "raft" {
  path    = "./vault/data"
  node_id = "node1"
}

listener "tcp" {
  address     = "127.0.0.1:8200"
  tls_disable = 1
}

api_addr = "https://127.0.0.1:8200"
cluster_addr = "https://127.0.0.1:8201"
ui = true
```
3、unseal Vault , Run `vault operator unseal`

1. Run `vault secrets enable database`
2. Run `vault write database/config/my-mysql-database plugin_name=mysql-database-plugin connection_url="{{username}}:{{password}}@tcp(127.0.0.1:3306)/" allowed_roles="my-role" username="vault" password="123456"`
3. Run `vault write database/roles/my-role db_name=my-mysql-database creation_statements="CREATE USER '{{name}}'@'%' IDENTIFIED BY 'pwd123456';GRANT SELECT ON *.* TO '{{name}}'@'%';" default_ttl="1h" max_ttl="24h"
Success! Data written to: database/roles/my-role`
4. Run `vault read database/creds/my-role`. The password I get is a random password instead of a fixed password '123456'. I can use the password '123456' to log in to MySQL instead of using a random password, that is the problem.

**Expected behavior**

**Environment:**
* Vault Server Version (retrieve with `vault status`):
```
Key                     Value
---                     -----
Seal Type               shamir
Initialized             true
Sealed                  false
Total Shares            5
Threshold               3
Version                 1.6.1
Storage Type            raft
Cluster Name            vault-cluster-5816945e
Cluster ID              4a229188-a454-aebd-e4a1-06c9c24930b8
HA Enabled              true
HA Cluster              https://127.0.0.1:8201
HA Mode                 active
Raft Committed Index    215
Raft Applied Index      215
```
* Vault CLI Version (retrieve with `vault version`):
```
Vault v1.6.1 (6d2db3f033e02e70202bef9ec896360062b88b03)
```
* Server Operating System/Architecture:

Vault server configuration file(s):

```hcl
storage "raft" {
  path    = "./vault/data"
  node_id = "node1"
}

listener "tcp" {
  address     = "127.0.0.1:8200"
  tls_disable = 1
}

api_addr = "https://127.0.0.1:8200"
cluster_addr = "https://127.0.0.1:8201"
ui = true
```

**Additional context**

**Comment by HridoyRoy** [comment]
Hi @q1979635364 , I wanted to follow up on this with a quick question: do the dynamic credentials that you get back also allow you to log in, in addition to the pre-created vault user? 

I'll circle back to see if this is a bug, but my initial thoughts are that dynamic credential creation doesn't remove pre-created credentials. It only generates credentials, and so the old credentials would still be valid.

**Comment by q1979635364** [comment]
> Hi @q1979635364 , I wanted to follow up on this with a quick question: do the dynamic credentials that you get back also allow you to log in, in addition to the pre-created vault user?
> 
> I'll circle back to see if this is a bug, but my initial thoughts are that dynamic credential creation doesn't remove pre-created credentials. It only generates credentials, and so the old credentials would still be valid.
> 
> Thanks!

I'm pretty sure the generated dynamic credentials won't log in, but I can log in with a fixed password. Could you please look at this problem again?. My operation is shown in the figure below.
![image](https://user-images.githubusercontent.com/25050128/104419624-ad4ddc00-55b3-11eb-82cc-28fc68b459e9.png)

**Comment by rs-sliske** [comment]
I think this is because the dynamic db credentials isnt designed to be used in this way, i dont believe vault does any kind of parsing of the creation statements you pass, it just replaces the {{name}} and {{password}} with the credentials it generated. and trusts that the statement will use them.

if you want to control the credentials yourself then i dont think you need to use the database plugin, you can just use the key/value store

**Comment by pcman312** [comment]
Hi @q1979635364 ! @rs-sliske is correct in this. Dynamic database roles are not intended to reference existing users within the database. They are intended to create a randomized user within the database and then manage its lifecycle by extending how long it lives in the database (based on the `default_ttl` and `max_ttl` values) and removing the user once the TTL passes.

Here is the full lifecycle (assuming no errors along the way):
1. User sets up a dynamic database role
2. User calls `/creds/:name` to retrieve a short-lived username & password in the database. The lifetime of that user is governed by the configuration set up in step 1.
3. Vault generates a randomized username and password
4. Vault applies the username & password to the `creation_statements` by replacing `{{username}}` and `{{password}}` within the statements with the username and password generated from step 3
5. Vault executes the `creation_statements` within the database
6. Vault saves the username and password from step 3 to its data store (Consul, integrated storage, etc.)
7. Vault returns the username and password from step 3 to the calling user
8. User can then use the username and password returned from step 7 to log into the database
9. User may extend the lifetime of that user by calling `vault lease renew <lease_id>` to a maximum of the `max_ttl` specified in step 1
10. After the TTL passes, Vault will automatically remove the user from the database by using the `revocation_statements` (most/all of the DBs have a reasonable default value for these statements) in the same way as in steps 4 and 5

If the username and/or password are not specified as templated fields within the `creation_statements`, Vault will not recognize what user & password was used. This is also antithetical to the purpose of dynamic roles.

Additionally, a fixed database password is also antithetical to static roles as the purpose of static roles is for Vault to take ownership of an existing user and to rotate that user's password on a regular cadence. If you need to store a static username & password within Vault, the K/V store is the place to do that however I do not recommend it as the credentials for a database user should be short lived otherwise there is significantly more danger in those credentials being leaked and compromised.

I hope this was helpful!

**Comment by sgmiller** [comment]
@pcman312 's summary is correct.  The database secrets engine expects the creation statement to assign the random password generated by Vault.  It cannot be used to set a static password.  Closing for now, reopen if you have additional trouble.

**Comment by q1979635364** [comment]
Ok~
