### ISSUE TITLE
possible to rebuild vault server with intact secret backend?

### ISSUE THREAD

**Issue by ezeeetm** [hashicorp/vault#1071]
we are vetting vault for production use.  One question that came up was is it possible to re-provision a new vault server on top of an otherwise intact secret backend, assuming we have access to the master keys and initial root token created when init'ing the original vault server?

If this is not possible, is it possible to export and manually decrypt the data (again, assuming we have master keys/root token) in an orphaned secret backend, so that we can then recreate those secrets in a new vault server?

**Comment by chrishoffman** [comment]
Unsealing is the process that constructs the master key whether you are provisioning a new server or rebooting the server.  By pointing the new server at the secret backend and unsealing, it will become a fully functional vault server.

Check out https://www.vaultproject.io/docs/concepts/seal.html

**Comment by ezeeetm** [comment]
@chrishoffman thanks, that's very helpful.

Just curious, by what means is the backend secret data encrypted that a new server can access it with a master key constructed from a new set of unseal keys?

**Comment by jefferai** [comment]
The master key is stored with the Vault data, but is itself encrypted. So the unseal keys together form the description key that the new Vault server applies to the stored master key.

**Comment by narayan8291** [comment]
@jefferai When a new vault server is spanned and configured to use the same secret backend, then the unseal keys that are used to construct the decryption key should be the same right ?

**Comment by jefferai** [comment]
That's correct!

**Comment by geek876** [comment]
@jefferai. What @narayan8291 commented is it actually possible ? When you create new vault server (presumably you lost all your vault nodes but your 'consul' backend is intact), you can't use your old unseal keys as this new vault server(s) will have its own set of unseal keys correct ? so effectively you can't recover in this scenario ?

**Comment by vishalnayak** [comment]
@geek876 When you say 'lost all the vault nodes', if you mean that all the nodes went down and they can all be brought up, then data can be recovered since the vault instances can be unsealed again (with the same set of unseal keys).

If you mean that the nodes are permanently down, then I am afraid data cannot be recovered. The encryption key used on the data, will in turn be encrypted by a master key. This master key is not stored anywhere and can only be recovered by a specific set of unseal keys generated during vault initialization. If all the vault instances that can regenerate the master key are lost, then recovery is not possible.

**Comment by geek876** [comment]
@vishalnayak Thanks. I meant the later case.

**Comment by ezeeetm** [comment]
@vishalnayak @geek876 , I also meant the latter case...but perhaps my OP example needs to be clarified that it refers to a single server deployment, not one server of an HA configuration.  Wondering why @chrishoffman and @jefferai are giving a different answer?  Just to clarify, the OP question is:

- given a single vault server (no HA) node A, pointed at secret backend A
- the unseal/root keys for server A are known (but sounds like they may not be needed)
- server A dies, completely, but backend A is still intact
- a new vault server, B, is provisioned configured and pointed at backend A
- server B is initialized

Can server B read the  /secrets data previously stored in backend A?

**Comment by ezeeetm** [comment]
@vishalnayak it would be great if we could keep this open until we have a consensus answer.

**Comment by chrishoffman** [comment]
I don't think I gave a different answer but I am just a user of vault.  I would trust @jefferai, as he may give a clearer answer to the question.

**Comment by ezeeetm** [comment]
here are the comments that seem conflicting:

> @chrishoffman : By pointing the new server at the secret backend and unsealing, it will become a fully functional vault server.

> @jefferai : The master key is stored with the Vault data, but is itself encrypted. So the unseal keys together form the description key that the new Vault server applies to the stored master key.

> @vishalnayak : If you mean that the nodes are permanently down, then I am afraid data cannot be recovered.

**Comment by vishalnayak** [comment]
@ezeeetm @chrishoffman: My bad. @jefferai was right in telling that the data can be recovered.

I am sorry for the confusion. I tested it out and it works just fine. As Jeff said, the master key is stored with Vault data and not tied to the Vault instance. So if you have the unseal keys and root token, everything is good.

**Comment by ezeeetm** [comment]
@vishalnayak that's great!  just to clarify:

>So if you have the unseal keys and root token, everything is good.

you mean the unseal keys/root token of the *new* vault server.  Nothing is needed of the old (dead) vault server other than the intact backend.

**Comment by geek876** [comment]
@vishalnayak Sorry, so does it mean, I can un-seal vault instance(s) 'Y' using keys from another valut instance(s) 'X'  ?

**Comment by geek876** [comment]
@vishalnayak @ezeeetm : Its confusing now
 If you only need unseal keys/root token of the new vault server then how can the new server decrypt old data ? ( As per @jefferai , data is encrypted using unseal keys, so unseal keys of the old vault instance in this context).

**Comment by ezeeetm** [comment]
@geek876  see third comment in this thread (which is the same as the question you are asking now, just different words).  I had the same curiosity, but it sounds like the subsequent responses to that comment are correct.

**Comment by vishalnayak** [comment]
@ezeeetm Confusion here is because you asked 2 different questions.

> is it possible to re-provision a new vault server on top of an otherwise intact secret backend, assuming we have access to the master keys and initial root token created when init'ing the original vault server?

The answer to this is **yes**. This is what Jeff referred to.

>by what means is the backend secret data encrypted that a new server can access it with a master key constructed from a new set of unseal keys?

The answer to this is **no**. This case is not possible. When you attach an intact backend to a new Vault instance, it will already be initialized (since master key is stored with backend data) and a new set of unseal keys cannot be generated. You will have to use the unseal-keys/root-token generated while initiating the (intact) backend/old-vault.

>you mean the unseal keys/root token of the new vault server. Nothing is needed of the old (dead) vault server other than the intact backend.

This is incorrect for the reason I explained above.
You cannot use unseal-keys of one backend to decrypt data belonging to a different backend.

@geek876 

>does it mean, I can un-seal vault instance(s) 'Y' using keys from another valut instance(s) 'X' ?

Yes. If both X and Y were pointing to the same backend, and if you have the unseal-keys/root-token of the same when you first initialized the backend with X.

**Comment by ezeeetm** [comment]
@vishalnayak thanks! this is very helpful.

By way of explanation, I assumed incorrectly that the second part of the OP (left out of your quote) helped to clarify what was being asked:

>If this is not possible, is it possible to export and manually decrypt the data (again, assuming we have master keys/root token) in an orphaned secret backend, so that we can then recreate those secrets in a new vault server?

At the end of the day, this is the answer I was looking for, and am happy with the answer:

>does it mean, I can un-seal vault instance(s) 'Y' using keys from another valut instance(s) 'X' ?

Yes. If both X and Y were pointing to the same backend, and if you have the unseal-keys/root-token of the same when you first initialized the backend with X.

**Comment by vishalnayak** [comment]
@ezeeetm Good to know that it was helpful. I am closing this issue. Feel free to reopen it if you still have questions.

**Comment by kiran2956** [comment]
the vault which provisioned using dynamo DB as part of disaster recovery process in HA mode . is not allowing to uneal, 

I see vault is initiated automatically when i use the old dynamo DB table in order to restore.

[ec2-user@ip-<**Redacted**>]$ vault operator unseal -tls-skip-verify
Unseal Key (will be hidden):
Error unsealing: Error making API request.

URL: PUT https://1<redacted>:8200/v1/sys/unseal
Code: 500. Errors:

* failed to decrypt encrypted stored keys: error decrypting data encryption key: AccessDeniedException: The ciphertext refers to a customer master key that does not exist, does not exist in this region, or you are not allowed to access.
	status code: 400, request id: a52b27d3-e603-4bb8-b926-c8f6215aed81
