### ISSUE TITLE
vault key value pair, policies migration from oss vault to enterprise vault

### ISSUE THREAD

**Issue by sangamgo** [hashicorp/vault#10744]
Hi Guys,

we have a situation where we need to copy all secret data(key value pairs) and policies from oss vault to enterprise vault.

we only to transfer key value pairs and policies and nothing more, is there any script available so that we only migrate key value pairs to new vault server?

**Comment by HridoyRoy** [comment]
Hi @sangamgo, are you migrating storage backends or changing the vault binaries from OSS to Ent?

**Comment by vishalnayak** [comment]
Issues that are not reproducible and/or not had any interaction for a long time are stale issues. Sometimes even the valid issues remain stale lacking traction either by the maintainers or the community. In order to provide faster responses and better engagement with the community, we strive to keep the issue tracker clean and the issue count low. In this regard, our current policy is to close stale issues after 30 days. Closed issues will still be indexed and available for future viewers. If users feel that the issue is still relevant but is wrongly closed, we encourage reopening them.

Please refer to our [contributing guidelines](https://github.com/hashicorp/vault/blob/main/CONTRIBUTING.md) for details on issue lifecycle.
