### ISSUE TITLE
The search box is very slow and resets while typing

### ISSUE THREAD

**Issue by xelhark** [hashicorp/vault#10754]
**Describe the bug**
I'm talking about the ui in the path `/ui/vault/secrets` of a KV v2 secret mount
It often happens that while searching for some vault, the search box is slow, unresponsive, or overwrites the user's input, resulting in a frustrating experience. 

**To Reproduce**
1. Login to your vault
2. Navigate to the page `/ui/vault/secrets/`
3. Type something in the search box (typing quickly makes this more apparent)
4. Notice the search box being unresponsive or cutting pieces of your search

**Expected behavior**
The search box should search for whatever you typed and be more responsive.

**Environment:**
* Vault Server Version 1.6.0

**Comment by ifurs** [comment]
I am facing this issue, too, in the production and dev environment.
Looks like it can be request `/v1/secret/metadata/?list=true` which generate list of available secrets.

If you put name of specific secret `/ui/vault/secrets/your_secret` it will return list of all included secrets, than you can trigger new `?list=true` if you will put `/ui/vault/secrets/another_secret` 

But it quite strange that the attribute `?list=true` refreshes the page.

**Comment by Monkeychip** [comment]
@xelhark Thank you for the issue. To help me reproduce, can you tell me:

1. Approximately how many secrets you have (e.g 100+ or 500+)? 
2. Do you see pagination at the bottom of the screen? 
3. We have made some improvements to this view since 1.6, so if you've upgraded and this is still and issue, can you tell me what version of Vault you are now on?

**Comment by hsimon-hashicorp** [comment]
As it has been some time since @Monkeychip asked for an update, I will consider this issue "stale" and go ahead and close it. If the issue is recurring in a recent version of Vault, please create a new issue with the issue template filled out to the best of your ability and we can look at it. Thanks!
