### ISSUE TITLE
Mysql backend

### ISSUE THREAD

**Issue by gambol99** [hashicorp/vault#1076]
When added a mysql backend and adding the config/connection option it appears to try and connect to the database. Is there any particular reason why this check has to be performed inline? I was writing a quick provisioner (https://github.com/gambol99/vaultctl) and wanted to provision the backend before the db might even exist.

```shell
INFO[0000] [backend:platform/db/config/connection] skipping the config, as it's a oneshot setting 
INFO[0000] [backend->config: platform/db/roles/readonly] applying configuration for backend 
[error] Error making API request.

URL: PUT http://127.0.0.1:8200/v1/platform/db/roles/readonly
Code: 500. Errors:
```

**Comment by vishalnayak** [comment]
@gambol99 
Connecting to database is the only way to ensure that the connection string provided during configuration is valid. Vault does it for the same purpose to ensure that there are no problems while issuing credentials.

**Comment by jefferai** [comment]
I do think we should consider whether this behavior is correct. Obviously there are pros and cons. I believe this behavior was put into some of the backends initially because of the opposite problem, where people were complaining that they had entered something invalid but didn't know until they had tried issuing credentials and failed.

I'm going to mark this as something for us to consider going forward; maybe we can just put in a 'notest' boolean or something of that sort.
