### ISSUE TITLE
KV Secret disappear after "Cannot read property 'notifyBelongsToChange' of undefined" on GUI

### ISSUE THREAD

**Issue by Grazulex** [hashicorp/vault#10789]
Hello,

I have just install Vault 1.6.1 on a Ubuntu 20 server.

On the GUI I have 2 times the same error.

I have enable the KV engine and create secrets...
If I click again on the "enable new engine" I have this error : 
"**Cannot read property 'notifyBelongsToChange' of undefined**" and the KV engine desappear for the screen but is still there..
Where I don't know but I have check with API and I can always find the secrets but I have nothing anymore in the GUI.

Can somebody help me ?

Thanks

JMS

**Comment by Grazulex** [comment]
MY kv engine is showing again after 5min and a logout/login !! strange no ?

**Comment by Monkeychip** [comment]
@Grazulex Thank you for the question. There has been a lot of updates and internal changes to the UI since 1.6.1. Is this still an issue on Vault UI 1.11+?

**Comment by hsimon-hashicorp** [comment]
@Grazulex As this issue is appearing for you on 1.6.0, please update to a newer version as we only accept bug reports for versions that are `n-2` (ie, the latest Vault version we have released is 1.14, so we accept bug reports and enhancement requests for versions 1.12 or newer). If this issue continues in Vault 1.12+, please open a new issue with the template filled out (ie configuration, precise errors, etc). Thanks!
