### ISSUE TITLE
audit backend dependency and failover

### ISSUE THREAD

**Issue by horsehay** [hashicorp/vault#1083]
Looks like vault has a dependency on the audit backend, which is understandable. Is there any mechanism for failover if the audit backend isn't available? It would be nice if Vault would change leadership if such failures occur.

log output:

`2016/02/15 17:21:11 [ERR] audit: backend 'syslog/' failed to log request: Unix syslog delivery error
2016/02/15 17:21:11 [ERR] core: failed to audit request with path (transit/decrypt/XXXXXX): no audit backend succeeded in logging the request
2016/02/15 17:21:11 [ERR] audit: backend 'syslog/' failed to log response: Unix syslog delivery error
2016/02/15 17:21:11 [ERR] core: failed to audit response (request path: transit/decrypt/XXXXXX): no audit backend succeeded in logging the response`

**Comment by jefferai** [comment]
Changing leadership if audit logs cannot be written to is an interesting idea, although I'm not sure it's feasible, since the local Vault instance still needs to write out the value to the audit log in order to fulfill its contract to ensure all requests and responses are logged.

One thing you can do is configure the file backend as well. The audit log only requires that *one* audit backend writes an entry successfully.

**Comment by horsehay** [comment]
In this instance, the Transit module was unable to decrypt a value because of the dependency. :frowning:

**Comment by jefferai** [comment]
It's not a dependency; it's a contract. If you have chosen to enable audit logging, Vault ensures that all transactions are sent through the audit log. If it cannot, it stops handling requests until the audit log is fixed. Vault does not consider it acceptable to simply fail to log this information; otherwise this would be a great way for an attacker to cover their tracks.

**Comment by horsehay** [comment]
That makes sense, that it wouldn't be considered a dependency. So to clarify the issue, auditing is an option, but one that is pretty integral to security (supported by the fact that Vault won't service requests if it isn't available). File and local syslog auditing are a system service, so ideally any failure of a system service that would prevent Vault from servicing requests should be addressed in HA.

I understand that doing it at the HA layer would be difficult, so there would have to be some type of failover based on the audit config. My suggestion would be to add a timeout option to the audit backend config so that after a number of tries or period of time where requests fail, appoint a new leader in the cluster.

**Comment by jefferai** [comment]
Appointing a new active node has the same problem -- Vault operations continue while an operation (on the now-standby node) continues to be unable to be audit logged.

**Comment by shomron** [comment]
@jefferai this seems to be a potentially crippling scenario:

Syslog auditing is enabled, something happens to the syslog daemon.

*Can't disable syslog auditing:*

```
$ vault audit-disable syslog
Error disabling audit backend: Error making API request.

URL: DELETE https://127.0.0.1:8200/v1/sys/audit/syslog
Code: 500. Errors:

* internal error

<snip>

2016/05/25 21:15:59 [ERR] audit: backend 'syslog/' failed to log response: Unix syslog delivery error
2016/05/25 21:15:59 [ERR] core: failed to audit response (request path: sys/audit/syslog): no audit backend succeeded in logging the response
```
*Can't enable file auditing as a backup:*

```
$ vault audit-enable file path=/var/log/vault.log
Error enabling audit backend: Error making API request.

URL: PUT https://172.16.1.16:8200/v1/sys/audit/file
Code: 500. Errors:

* internal error

<snip>

2016/05/25 21:28:57 [ERR] audit: backend 'syslog/' failed to log request: Unix syslog delivery error
2016/05/25 21:28:57 [ERR] core: failed to audit request with path (sys/audit/file): no audit backend succeeded in logging the request
2016/05/25 21:28:57 [ERR] audit: backend 'syslog/' failed to log response: Unix syslog delivery error
2016/05/25 21:28:57 [ERR] core: failed to audit response (request path: sys/audit/file): no audit backend succeeded in logging the response
```

What would one do in this scenario?

**Comment by jefferai** [comment]
Right now the only thing you can do is fix syslog.

Avoiding this scenario requires enabling two forms of audit *before* bad things happen :-/

The active node remains active because it has pending audit values to write and we don't want to discard them by losing active status. Vault tries at all costs to ensure that audit logs succeed being written, as that's a key part of its security model.

**Comment by shomron** [comment]
@jefferai that was my understanding as well. This operational risk has led us to deprecate the syslog backend internally and manage file -> syslog outside of Vault. Where would a good place to document this issue for others to understand the tradeoffs?

Also a little extra context: we are running Vault in Docker and to enable the syslog backend were mapping the host's `/dev/log` socket into the container. Whenever the syslog service on the host was restarted, the container would be unable to write to its mapped socket until it was restarted as well.

**Comment by jefferai** [comment]
@shomron It's documented at https://www.vaultproject.io/docs/audit/index.html (see the section "Blocked Audit Backends").
