### ISSUE TITLE
Improve generic secret backend documentation

### ISSUE THREAD

**Issue by pdbogen** [hashicorp/vault#1091]
Doc in question: https://www.vaultproject.io/docs/secrets/generic/

This page causes some confusion because it uses "key" and "value" to describe multiple elements. It may be the case that new terminology should be introduced.

I'd recommend referring to the key-value pairs that are the value of a key as subkey-subvalue pairs. In the metasyntax of the document, secret/foo would be the "foo" key and the value of "foo" would be a list of subkey-subvalues, for example "zip=zap;" "zip" would be a subkey and "zap" would be a subvalue.

**Comment by vanhalt** [comment]
I would address it like this:

```bash
secret/foo is a path
zip=value is the key-pair(s)
```

Considering `foo` to be a key seems wrong to me since it is really a path. Example:

```bash
vault write secret/passwords/aws_account user=rafa password=123456
```

In this case pay particular attention to `passwords/aws_account` being the path where I am going to write my key-pairs. That said, the sentence that I would like to see rewritten would be this one:

`Writing to a key in the generic backend will replace the old value; sub-fields are not merged together.`

Unless I haven't read enough and haven't learn how to do it,  there is no way to update a key, every time you write to a path its a replace operation.

```bash
$ vault write secret/foo zip=zap
Success! Data written to: secret/foo

$ vault read secret/foo
Key           	Value
lease_duration	2592000
zip           	zap

$ vault write secret/foo zip=zap zop=zep
Success! Data written to: secret/foo

$ vault read secret/foo
Key           	Value
lease_duration	2592000
zip           	zap
zop          zep

$ vault write secret/foo zam=zoom
Success! Data written to: secret/foo

$ vault read secret/foo
Key           	Value
lease_duration	2592000
zam           	zoom
```

And I would not include the definition of sub-keys at all. What do you think?

**Comment by jefferai** [comment]
Hi @vanhalt ,

I think some of the confusion here, which bleeds into the documentation (as you saw), is that paths in filesystem-like key-value stores are usually called keys (rather than files), although these live in directories. So the "key" in that context is really the "file" part of the path. The "value" is then whatever value lives at that key. In our case, however, we are storing a JSON document there, which itself has keys and values.

**Comment by pdbogen** [comment]
@jefferai understandable, but the docs are still *very* confusing as a result. I'm not _very_ highly opinionated about what names are used, but something definitely needs to change. There are several statements in this doc that are very unclear:

> Writing to a key in the generic backend will replace the old value; sub-fields are not merged together.

(nowhere is "sub-field" defined; why is it a sub-field? Is it a sub-field of a field? What's a field?; "key" has all of the confusion described previously; is it referring fo "foo" in secret/foo or "zip" in "secret/foo zip=zap")

> The generic backend allows for writing keys with arbitrary values. A `ttl` value can be provided ...

..except a "key" as in "foo" in "secret/foo" _can't_ have arbitrary values, it can only have be a map/dict/associative array of strings to strings; unless this is referring to "key" as in "zip" in "zip=zap", in which case yes, a key can have arbitrary values. But "ttl" is a value and not a key? Or a sub-field? Or a field?

> Path and key names are not obfuscated or encrypted; only the values set on keys are.

I don't know what "key" means here. In "secret/foo" I gather that both "secret" and "foo" are unencrypted, but in "zip=zap" is "zip" encrypted? Is it a key, or is part of the value set on a key?

**Comment by vanhalt** [comment]
@jefferai now I see... I got it wrong then. Thanks for the clarification!

**Comment by jefferai** [comment]
> ..except a "key" as in "foo" in "secret/foo" can't have arbitrary values, it can only have be a map/dict/associative array of strings to strings

To clarify: On the CLI this is half true, but that's purely a limitation of the CLI. In the JSON API you can set it to be any JSON, and this will be passed through to the backend. (I said it's half true because you can also use `bar=@baz.json` syntax to do this on the CLI.) It's also possible to simply serialize your data and base64 encode it and pass that in.

**Comment by thatarchguy** [comment]
Can someone define a best practice? Should we be writing our generic secrets like this:
```
vault write secret/passwords/aws_account user=rafa password=123456
```
or:
```
vault write secret/passwords/aws_account/user value=rafa
vault write secret/passwords/aws_account/password value=123456
```

I understand that both can be used. I like the simplicity and organization of the first, but I am leaning towards the latter example because of:
>Writing to a key in the generic backend will replace the old value; sub-fields are not merged together.

**Comment by jefferai** [comment]
Honestly, I don't think there is a best practice. People like the different styles for different reasons and I see both out in the wild.
