### ISSUE TITLE
Vault agent re-authenticates on Vault server outages

### ISSUE THREAD

**Issue by andrejvanderzee** [hashicorp/vault#10918]
We are on Vault 1.6.2 and are experiencing problems with vault agent in production environments. When Vault is down for longer than 1 minute, it seems that vault agent re-authenticates and eventually revokes the old token and secrets. Preferably, vault agent would at least retry renewing the lease of the vault token until its TTL expires, instead of restating the lifetime watcher and consul template manager.

It seems that this logic could be tuned so that vault agent can cope with Vault outages longer than one minute, without revoking token and secrets:
https://github.com/hashicorp/vault/blob/master/api/lifetime_watcher.go#L263

We have tried VAULT_MAX_RETRIES but it bails out after 1 minute.

**Comment by ncabatoff** [comment]
I think the problematic behaviour is here:

```
		// We keep evaluating a new grace period so long as the lease is
		// extending. Once it stops extending, we've hit the max and need to
		// rely on the grace duration.
		if leaseDuration > priorDuration {
			r.calculateGrace(leaseDuration)
		}
```

When we get there due to a renew failure, this condition will be false, so we don't recalculate grace.  Grace remains what it was at the outset, something like 10-20% of the original lease TTL.  So let's say the auth method TTL is configured at 3m, as it looks to be the case in your agent example in #10898.  That would make the grace be something like 30s, and the sleep duration a bit over 2m.

We immediately attempt a renew when the LifetimeWatcher starts running, then sleep for about 2m.  We try to renew then, and suppose we fail.  So now leaseDuration is about 1m (time remaining), grace remains 30s, and sleep duration is 

```
		// The sleep duration is set to 2/3 of the current lease duration plus
		// 1/3 of the current grace period, which adds jitter.
		sleepDuration := time.Duration(float64(leaseDuration.Nanoseconds())*2/3 + float64(r.grace.Nanoseconds())/3)
```

so about 40s + 10s.  This means that we will indeed return nil here as you saw, because leaseDuration-sleepDuration is about 10s, smaller than grace of 30s:

```
		if leaseDuration <= r.grace || leaseDuration-sleepDuration <= r.grace {
			return nil
		}
```

If the numbers had been bigger the situation is similar.  With a 300m TTL, grace would be about 45m, sleep duration becomes 215m.  So we sleep for 215m, get a renew failure, set the new lease duration to 85m and the new sleep duration to 2/3 of 85m + 1/3 of 45m or about 70m, and now see that leaseDuration-sleepDuration is 15m which is smaller than r.grace so we again give up immediately on renewing.

I'm not sure what the thinking behind the current behaviour is, i.e. why do we only recalculate grace when leaseDuration increased.  Another area to explore: should we use a smaller sleepDuration after a previous renew failure?

**Comment by andrejvanderzee** [comment]
Pull request here: https://github.com/hashicorp/vault/pull/11008

**Comment by ncabatoff** [comment]
Fixed in https://github.com/hashicorp/vault/pull/11445
