### ISSUE TITLE
Feature request: Customer Master Keys

### ISSUE THREAD

**Issue by therandomsecurityguy** [hashicorp/vault#1101]
Add the ability to create customer master keys (CMK) similar to [AWS KMS](http://docs.aws.amazon.com/kms/latest/developerguide/concepts.html).

**Comment by jefferai** [comment]
Hi there,

Take a look at the transit backend at https://www.vaultproject.io/docs/secrets/transit/index.html -- this is the same concept, including datakeys!

**Comment by therandomsecurityguy** [comment]
Thanks Jeff!

**Comment by jefferai** [comment]
@therandomsecurityguy Sure -- if that doesn't meet your needs, please report back and we'll figure out what you're looking for that's lacking.

**Comment by therandomsecurityguy** [comment]
Hi Jeff,

The Vault implementation for the transit backend is for data in transit. AWS KMS implementation is using a master key per customer (more SaaS friendly). Data at rest within Vault is using the same Vault master key.

Thanks,
Derek

**Comment by jefferai** [comment]
Hi Derek,

I don't think I really follow what you're asking for, because the offerings are nearly identical. AWS KMS uses a default master key per customer, plus optional extras, which can then be used to encrypt/decrypt data or encrypt/decrypt datakeys for offline encryption and decryption. `transit` in Vault uses an unlimited number of named keys, which can then be used to encrypt/decrypt data or encrypt/decrypt datakeys for offline encryption and decryption.

The named keys themselves are encrypted at rest with the Vault master key, but this is no different than AWS, which in (some? all?) cases encrypts the customer keys at rest using an HSM, but that in itself is using a master key (they don't provision an HSM per customer).

AWS KMS provides a policy engine that controls access to the customer keys. Vault provides a policy engine that controls access to its named keys.

Vault also supports context for its keys, requiring that a given ciphertext/plaintext value not only name the same key but provide the same context in order to successfully encrypt or decrypt data. Between the separate named keys and the contexts, there are essentially infinite possible keys that can be used, each one distinct from the other. I'm not sure if KMS provides this or not.
