### ISSUE TITLE
VAULT - List Tokens

### ISSUE THREAD

**Issue by narayan8291** [hashicorp/vault#1115]
Is there a feature where vault can list all the tokens that has been created ? I am currently using vault list secret/ to display all the secrets. I tried to use vault list auth/token to display all the tokens but didn't work. Is there a way to get the list of created tokens ?

I created a number of tokens and I would like to revoke everything one by one or I would like to revoke all tokens except the root token.

**Comment by jefferai** [comment]
Hi @narayan8291 ,

Can you please post questions on the mailing list (https://groups.google.com/forum/m/#!forum/vault-tool) rather than in GitHub issues? This gets a lot more eyes on any particular question or idea.

It also prevents problematic issue workflows for questions where either the issue is closed immediately but then discussion continues on a closed issue; or, the issue is not closed, discussion dies down, and the issue remains open indefinitely waiting for further potential replies.

Thanks!

**Comment by andrewhowdencom** [comment]
#savedyouaclick 

https://groups.google.com/forum/#!searchin/vault-tool/list$20tokens%7Csort:relevance/vault-tool/gv1_B4knO6Q/ajkIh0sVEwAJ

**Comment by ahmadalli** [comment]
if anyone still looking for an answer, you can list accessors, not tokens: `vault list auth/token/accessors` and if you want to revoke them, you can revoke by accessor: `vault token revoke -accessor <accessor>`

**Comment by abdennour** [comment]
still `vault list auth/token/accessors` will do the trick

**Comment by awnumar** [comment]
`auth/token/accessors` includes all tokens. How can I list only root tokens?

**Comment by vaygr** [comment]
I guess it will be very hard without iterating over them, in which case this might work:

```shell
$ vault list -format json auth/token/accessors | jq -r .[] | xargs -I '{}' vault token lookup -format json -accessor '{}' | jq -r 'select(.data.policies | any(. == "root"))'
```
