### ISSUE TITLE
Unseal Vault with Recovery Key ( Lost AWS KMS used for Auto unseal )

### ISSUE THREAD

**Issue by sandeep0701** [hashicorp/vault#11244]
Hi,

We Are you using AWS KMS for auto unsealing the vault in our environment.

But we have a question.

What if we lost the AWS KMS key ? do we have any other way to unseal the vault ?

I tried the recovery keys but it only works to unseal vault if the vault is manually sealed.

**Comment by carnei-ro** [comment]
@sandeep0701 I had this concern too. We are using AWS KMS with an uploaded key https://docs.aws.amazon.com/kms/latest/developerguide/importing-keys.html.

**Comment by squaricdot** [comment]
You can download and decrypt those unseal keys from aws and store them encrypted (on separated ) usb stick(s) and store it in an actual (offsite) vault/secure location

**Comment by sgmiller** [comment]
You are correct that the recovery keys are used to authorize certain operations but cannot recover the master key (that is stored in KMS).  Using a customer managed key would allow you to keep your own backup, but of course you would need to secure that backup very well.

**Comment by g-psantos** [comment]
See #9421. It seems they're aware of this issue and considering having two copies of the encryption key, one wrapped by AWS KMS and the other wrapped by the Recovery Key. But there appears to be no momentum to implement it, unfortunately.

**Comment by vishalnayak** [comment]
Issues that are not reproducible and/or not had any interaction for a long time are stale issues. Sometimes even the valid issues remain stale lacking traction either by the maintainers or the community. In order to provide faster responses and better engagement with the community, we strive to keep the issue tracker clean and the issue count low. In this regard, our current policy is to close stale issues after 30 days. Closed issues will still be indexed and available for future viewers. If users feel that the issue is still relevant but is wrongly closed, we encourage reopening them.

Please refer to our [contributing guidelines](https://github.com/hashicorp/vault/blob/main/CONTRIBUTING.md) for details on issue lifecycle.
