### ISSUE TITLE
Update google OAUTH2 to support Workload Identity Federation

### ISSUE THREAD

**Issue by prashantkul** [hashicorp/vault#11255]
Please update google OAUTH2 library to support [Workload Identity Federation.](https://cloud.google.com/iam/docs/workload-identity-federation)

GO v0.0.0-20210218202405-ba52d332ba99 or later of the golang.org/x/oauth2 module

**Comment by calvn** [comment]
Hello, thanks for opening a GH issue on this request! There's an ongoing dependency issue where both the `golang.org/x/oauth2` package and the `github.com/etcd-io/etcd` package depends on `google.golang.org/grpc`, and upgrading the former breaks the latter due to package incompatibility issues, thus breaking the Vault build.

We're looking into updating the `etcd` depending to be at etcd v3.5.0-alpha.0 or newer which might unblock us from this dependency problem, but we'll have to make additional code changes to get the imports and references updated throughout the codebase.

Related to https://github.com/etcd-io/etcd/issues/12124
Similar to https://github.com/hashicorp/cap/pull/14

**Comment by MXfive** [comment]
Seems this is unblocked now, would be really great for cloud portable workloads to run on both clouds simultaneously using Vault to provision credentials.

**Comment by austingebauer** [comment]
@prashantkul - We've recently upgraded our [golang.org/x/oauth2](https://github.com/hashicorp/vault/blob/main/go.mod#L179) dependency beyond the version you've suggested in this issue. Are you able to provide any additional information as to how this specific dependency upgrade would help us support Workload Identity Federation? Thank you!

**Comment by sofixa** [comment]
I can confirm that Vault now supports GCP Workload Identity Federation and can successfully auth into GCP from other trusted identity providers.
