### ISSUE TITLE
does vault provide array of IP address in its config file?

### ISSUE THREAD

**Issue by ruchi15** [hashicorp/vault#1130]
Hi,
I am running 3 vault instance with 3 consul instance as storage backend. All consul instances are in a cluster. Right now, my configuration is, i am giving one-to-one mapping with each vault to each consul. data is consistent and everything is working fine. but if i down one of my consul instance, it's corresponding vault instance also goes down. this is not i want. I want to pass the array of IPs or something like that so that i can pass the IP addresses of all my consul instance in each of the vault config file. so that if i down one of the consul, my vault doesn't go down.

can anyone tell me the reason or solution?

**Comment by jefferai** [comment]
Hi @ruchi15 ,

The approach you have is not recommended because two of the Consul instances will simply be forwarding requests to the leader anyways, so you're introducing unnecessary latency.

The recommended approach is to point Vault at a local Consul agent. The agent is aware of the Consul leader at all times and will send requests to the appropriate server.

If you don't want to run a local Consul agent, my suggestion is to use the [only_passing](https://www.consul.io/docs/agent/options.html#only_passing) in the Consul configuration file, then point your Vault servers at the address of the Consul service in DNS. This address will always return the leader.
