### ISSUE TITLE
TLS & integrated storage: Vault validates an incomplete CA chain

### ISSUE THREAD

**Issue by ahamez** [hashicorp/vault#11318]
**Describe the bug**
To enable end-to-end encryption, I set up a two-tier private CA:
`Root CA -> Intermediate CA -> Vault certificate`.

However, even though I didn't install the `Root CA` and just added the `Intermediate CA` as a K8S secret, raft nodes can join each other, which should not be the case as they don't have access to `Root CA`.

For instance, `openssl s_client` correctly states that it has not been able to verify the certificate:
```
$ openssl s_client -connect vault-0.vault-internal:8200 -CAfile dev-ca.crt
CONNECTED(00000003)

[snip]

    Verify return code: 2 (unable to get issuer certificate)
```

**To Reproduce**
1. Setup a two-tier private PKI
2. Sign a certificate for Vault with the intermediate CA
3. Install Vault on Kubernetes using the [kubernetes raft deployment guide](https://learn.hashicorp.com/tutorials/vault/kubernetes-raft-deployment-guide?in=vault/kubernetes) altogether with the certificate for the Vault server and the intermediate CA as K8S secrets
4. Init and unseal a few nodes
5. List peers (`kubectl exec --namespace=vault --stdin=true --tty=true vault-1  -- vault operator raft list-peers`) to show that nodes could join even though they should not:
    ```
    Node       Address                        State       Voter
    ----       -------                        -----       -----
    vault-0    vault-0.vault-internal:8201    leader      true
    vault-1    vault-1.vault-internal:8201    follower    true
    ```

**Expected behavior**
Vault should fail if it cannot validate the whole CA chain.

**Environment:**
* Vault Server Version (retrieve with `vault status`): `1.7.0`
* Vault CLI Version (retrieve with `vault version`): `Vault v1.7.0 (4e222b85c40a810b74400ee3c54449479e32bb9f)`
* Server Operating System/Architecture: K8S / Alpine / Installation via [Vault helm chart](https://learn.hashicorp.com/tutorials/vault/kubernetes-raft-deployment-guide?in=vault/kubernetes)

**Vault server configuration file(s):**

The same as the one in the [kubernetes raft deployment guide](https://learn.hashicorp.com/tutorials/vault/kubernetes-raft-deployment-guide?in=vault/kubernetes) .

```hcl
storage "raft" {
          path = "/vault/data"
            retry_join {
            leader_api_addr = "https://vault-0.vault-internal:8200"
            leader_ca_cert_file = "/vault/userconfig/tls-ca/ca.crt"
            leader_client_cert_file = "/vault/userconfig/tls-server/tls.crt"
            leader_client_key_file = "/vault/userconfig/tls-server/tls.key"
          }
          [...]
        }
```

**Comment by viralpoetry** [comment]
Hi @ahamez, I am not sure what you exactly mean by adding `Intermediate CA` as a K8S secret, but if you set `VAULT_CACERT`, from the PKI perspective you provided issuer certificate for the vault SSL cert, so during the verification, other Vaults have an issuer certificate and are able to verify the endpoint certificates.

Generally, applications verifying chain only care about the signature path building and if any CA certificate from a chain is trusted (in this case trusted is what is in the VAULT_CACERT) then verification should end. If the provided CA certificate is self-signed or signed by yet another authority is not checked to my knowledge

**Comment by ahamez** [comment]
In this case, as I followed the vault/helm guide, `VAULT_CACERT` is set to the intermediate CA with
```
extraEnvironmentVars:
    VAULT_CACERT: /vault/userconfig/tls-ca/ca.crt
```
The intermediate CA is mounted to `/vault/userconfig/tls-ca/ca.crt` as a K8S secret as explained in the guide.

The intermediate CA is, to the best of my knowledge, not self signed, as it's signed with the Root CA  (which the test with `openssl s_client` tends to prove, because it fails if the root CA is not provided).

The point here is that, even without the root CA, raft node validates the vault server certificate (which has been signed by the intermediate CA, not the root CA).

I hope it makes sense 😬

**Comment by viralpoetry** [comment]
Hi, so I think I understand you correctly. the problem is that once you set VAULT_CACERT you basically say that this CA cert is an actual trust anchor - the CA you are validating against. So the Vault handle it correctly and once it validates that node is using certificate issued by this CA it accepts it as valid.

On the contrary, if you put your root to the VAULT_CACERT, then your `leader_client_cert_file` in configuration has to be an actual chain of the intermediate (issuer) CA and the server certificate.
I have not tested adding chain there though

**Comment by ahamez** [comment]
> then your leader_client_cert_file in configuration has to be an actual chain of the intermediate (issuer) CA and the server certificate.
Do you mean I should make a bundle with the intermediate CA and the server certificate and reference it in `leader_client_cert_file `?

Even though, unless I'm mistaken, the validation should fail in the absence of the Root CA, isn't it? Otherwise it seems to me it completely defeats the purpose of having a certificate chain of trust 🤔. Which should mean that `VAULT_CACERT` is not automatically a trust anchor I guess.

**Comment by viralpoetry** [comment]
@ahamez it should not fail, it basically just verify up to a cert you provided. In `VAULT_CACERT` you state that this is the "final cert I am checking against" so the vault in a client role will act like that. You don't have to use an actual root CA, but as you said, it won't make sense, because with the current setup, you can't revoke intermediate CA.

Correct server setup is to serve whole chain / bundle except the root and clients should have root preinstalled and set in VAULT_CACERT. then it will work in any hypotetical scenario, like:
you have a Let's Encrypt certbot and it will renew a cert and put the `fullchain` bundle somewhere in `/etc/letsencrypt`. Certbot will trigger `post hook` that do a Vault reload without need to unseal it. And then if Lets Encrypt reissue some of their issuing CA, which they do often, your code will continue to work if you have set VAULT_CACERT to an ISRG Root cert which is long term trust anchor. The `fullchain` file that certbot receive will always contain issuer CA cert and server cert. That way you don't have to track changes on the intermediate CAs at all.

But back to your question, I think it's confusing that you don't have to use only Root but it works like that everywhere. if you install intermediate CA using `update-ca-certificates` on linux it won't complain and curl would work OK. but again, you won't be able to revoke intermedate so it's basically trust anchor and new root now, even when it does not sign itself.

**Comment by ahamez** [comment]
@viralpoetry Thank you for your explanation! I thought implementations were required to "go up" the chain until a self-signed certificate is found. But basically, what you're saying is that if any certificate in this chain is somehow considered to be a trust anchor, then the verification ends here. It makes sense in a way!

While it's not an issue in itself, maybe it could be part of the documentation: the fact that a bundle should be created is not straightforward, at least for me. What do you think?

**Comment by ahamez** [comment]
I tried with a bundle that contains both the server certificate and the intermediate CA and set `leader_client_cert_file` to this bundle. Vault fails with:
```
Error initializing listener of type tcp: error loading TLS cert: tls: private key does not match public key
```
Which makes sense 😬.
I'm quite lost here, I don't see how I can have an intermediate CA if one hand I cannot provide the Root CA and on the other hand I can't have a matching private key with the bundle that contains the whole chain except the root. Maybe there's a third way?

**Comment by viralpoetry** [comment]
yeah, actually that order differs between the software, I think there is no standard ¯\_(ツ)_/¯

**Comment by ahamez** [comment]
I'll close this issue as it's not a bug, I'll try to contribute to the documentation to help clarify this topic.
Anyway, @viralpoetry , thank you for your answers 🙂
