### ISSUE TITLE
[Feature Request] Root Token Generation should have a TTL option

### ISSUE THREAD

**Issue by Lasering** [hashicorp/vault#11376]
**Is your feature request related to a problem? Please describe.**
If for some reason a root token is lost it is computationally heavy to revoke it (it envolves listing all accessors, and for each accessor checking if it was the root policy associated with it).

**Describe the solution you'd like**
When generating a new root token an optional TTL argument should exist. When set it would automatically revoke the root token after the TTL expires. The default value for this argument would be 0.

It would also help if an endpoint which lists all accessors with the root policy existed. This endpoint would be restricted to be used by root tokens. This would help making sure no dangling root tokens exist.

**Additional context**
Not the first person hitting this problem:
  - [Identifying Active HashiCorp Vault Root Tokens](https://www.greenreedtech.com/identifying-active-hashicorp-vault-root-tokens/)
  - https://groups.google.com/g/vault-tool/c/-9FijFVaR8k

**Comment by sgmiller** [comment]
Root tokens are discouraged for real world use.   If you need admin-level tokens with ttls, consider creating an admin specific policy and child tokens with ttls with that policy, rather than root tokens.

Ideally once one has configured access for administrators this way, all root tokens are destroyed.
