### ISSUE TITLE
How to properly delete kv2 secret version

### ISSUE THREAD

**Issue by kotyara85** [hashicorp/vault#11435]
Hey there,
Trying to delete the latest secret version which results into all version being lost and this return from vault api:

```
        "data": null,
        "metadata": {
            "created_time": "2021-04-21T19:17:37.798497339Z",
            "deletion_time": "",
            "destroyed": true,
            "version": 14
        }
```

code itself:
```
secretName := "secret"
const version = 14
if _, err := s.VaultClient.Logical().Write(fmt.Sprintf("/secret/destroy/%s", secretName),
	map[string]interface{}{
		"versions": []int64{version},
	},
);
```

Thanks

**Comment by sgmiller** [comment]
You'll want to use the Delete() function on "/secret/data/:path", not the "/secret/destroy" path which as you found deletes everything.  Have a look [here](https://www.vaultproject.io/api/secret/kv/kv-v2#delete-latest-version-of-secret).

**Comment by vishalnayak** [comment]
Issues that are not reproducible and/or not had any interaction for a long time are stale issues. Sometimes even the valid issues remain stale lacking traction either by the maintainers or the community. In order to provide faster responses and better engagement with the community, we strive to keep the issue tracker clean and the issue count low. In this regard, our current policy is to close stale issues after 30 days. Closed issues will still be indexed and available for future viewers. If users feel that the issue is still relevant but is wrongly closed, we encourage reopening them.

Please refer to our [contributing guidelines](https://github.com/hashicorp/vault/blob/main/CONTRIBUTING.md) for details on issue lifecycle.
