### ISSUE TITLE
Input validation for invalid data

### ISSUE THREAD

**Issue by clstokes** [hashicorp/vault#1149]
When working with Vault recently, I typo'd a couple commands, but didn't notice because the commands completely successfully without indicating that my input was invalid.

Is it possible to validate the _data_ that is provided on commands - for invalid keys and values?

###### `policieeeeeeeees` is invalid.
```
$ vault write auth/userpass/users/contractor password=training policieeeeeeeees=contractor
Success! Data written to: auth/userpass/users/contractor
```

###### The policy does not exist.
```
$ vault write auth/userpass/users/contractor password=training policies=policy-does-not-exist
Success! Data written to: auth/userpass/users/contractor
```

**Comment by jefferai** [comment]
```
$ vault write auth/userpass/users/contractor password=training policieeeeeeeees=contractor
Success! Data written to: auth/userpass/users/contractor
```
Backends usually validate input data, but only for the fields they're actually looking for. They don't actually check anything else, and generally don't want to because other pieces of Vault may want that data (for instance, `ttl` in generic).

```
$ vault write auth/userpass/users/contractor password=training policies=policy-does-not-exist
Success! Data written to: auth/userpass/users/contractor
```
It's actually totally valid in Vault to assign a policy to a token that does not yet exist, because policy contents can be changed on-the-fly but which policies are attached to any particular token cannot. At actual token issue time, the user would get a warning about the policies that don't exist.
