### ISSUE TITLE
SSH accounts as a secret backend

### ISSUE THREAD

**Issue by myspotontheweb** [hashicorp/vault#115]
A "ssh" secret backend that generates SSH accessible user accounts on production servers. When coupled with Issue #94  (LDAP authentication) one would have an account management solution that would satisfy any corporate audit. 

Concept could be extended to control when a user is allowed access. For example only during business hours or perhaps a requirement to submit a valid change request ticket. How far can you take this idea?

Create some vault managed servers
----------------------------------------------
 
    $ vault mount ssh -path "server000123"
    $ vault write ssh/config/connection/server000123 host="server000123" user="root" pass="ZZZZZZZZ"

    $ vault mount ssh -path "server000124"
    $ vault write ssh/config/connection/server000124 host="server000124" user="root" pass="ZZZZZZZZ"

Set a lease period on credentials
---------------------------------------------
 
    $ vault write ssh/config/lease lease=1h lease_max=24h

Configure some user roles
----------------------------------

    $ vault write ssh/roles/admin value="useradd -G admins {{name}}"
    $ vault write ssh/roles/user value="useradd -G users {{name}}"

Usage
-----------
Request "admin" access on the first server:

    $ vault read server000123/creds/admin
    ..
    username admin-12345XYZ
    password 132ae3ef-5a64-7499-351e-bfe59f3a2a21

Request "user" access on the second server

    $ vault read server000124/creds/user
    ..
    username user-XYZ1234
    password 132ae3ef-34567-7499-351e-xhsgdooedjkd

A tool like the Consul template could be used to keep configure files up to date for automated SSH processes.

**Comment by phinze** [comment]
Thank you for kicking off this discussion. This is something I've been picturing since Vault was only a glimmer in @mitchellh and @armon's eye.

There are a lot of workflow and implementation details to work out here, but first I just wanted to mention how excited I am for a future in which the base state for a production server is to have a single `vault` user account, with operator access happening via ephemeral accounts created from centrally controlled policies with securely audited lifecycles.

:rocket: :grinning:

Initial high-level thoughts:

 * It'd be nice to work key-based SSH auth into this somehow, perhaps the provider can be given access to metadata about the vault-authenticated user, which includes the contents of the user's public key?
 * Is there a way for Vault to rotate its own root SSH key periodically?

(Also worth keeping on the table in this early stage that some of this may end up falling into external tools as well - all the functionality doesn't necessarily have to live within Vault.)

**Comment by myspotontheweb** [comment]
@phinze You described this nicely: "Single vault/root user account, with operator access happening via ephemeral accounts".

**Comment by apparentlymart** [comment]
OpenSSH supports an authentication scheme based on certificate authorities as well as the more common approach of explicitly generating and authorizing a key for each user.

Given that there's already support in Vault for acting as a CA, could this instead be built as a thin layer around that that issues OpenSSH-compatible certificates? Then the target servers can be configured to trust the CA cert and it's no longer necessary to explicitly install the generated certificates on each target server.

I've been considering setting up such a CA for an environment I work on, with a central system issuing a short-lived certificate to a user in response to authenticating in some other way (OAuth on a web server, in our case). In my use-case there would only be a single "real" user account on each machine and it would trust all certs from the CA, with the certs themselves identifying the human users. I realize this is slightly different than what this ticket was originally requesting, but I do think it's pretty close.

**Comment by jefferai** [comment]
Backends are purposefully separate from each other. In order to have backends access each other, you'd have to set a Vault token into one and give it the location of the other, and it would act as a normal HTTP client.

What you suggest could be a future enhancement to the SSH backend, but there are good use-cases for both the dynamic key backends and OTP backends, so we're not going to strip those out to build up a CA-based approach instead.

**Comment by myspotontheweb** [comment]
Since this enhancement was raised the [SSH backend][1] was added, introducing the alternative approach of using One Time Passwords.

I noticed also a possible duplicate issue here asking for [Dynamic user creation][2]

[1]: http://vaultproject.io/docs/secrets/ssh/index.html
[2]: https://github.com/hashicorp/vault/issues/571
