### ISSUE TITLE
Vault leader with consul backend

### ISSUE THREAD

**Issue by kaelumania** [hashicorp/vault#1161]
I wondered why is it required that vault redirects its traffic to its leader when using a HA backend like consul. Instead every vault instance could just ask consul by itsself, because consul takes care of consistency etc. The only reason I can imagine is the vault cache, that would make consistency more difficult otherwise. But again with an HA backend like consul I don't forcibly need a cache, because consul is made for stuff like this. Am I missing some important points?

**Comment by jefferai** [comment]
Hi @kaelumania ,

Can you please post questions on the mailing list (https://groups.google.com/forum/m/#!forum/vault-tool) rather than in GitHub issues? This gets a lot more eyes on any particular question or idea.

It also prevents problematic issue workflows for questions where either the issue is closed immediately but then discussion continues on a closed issue; or, the issue is not closed, discussion dies down, and the issue remains open indefinitely waiting for further potential replies.

Thanks!
