### ISSUE TITLE
Github auth: Token still working even after validity check fails

### ISSUE THREAD

**Issue by bkrodgers** [hashicorp/vault#1164]
I was very excited to see https://github.com/hashicorp/vault/pull/1047 from @vishalnayak in 0.5.1.  However, I'm not seeing what I would have expected here.  My test:

1. I'm in a github team that allows me access to stuff.
2. I do `vault auth -github ...`, and can `vault list /secret` or whatever else I should have access to.
3. I remove myself from said Github team.  I should now have no access to vault via github teams.
4. Just as a note, yes, I understand that after removing from github but prior to attempting to renew, it will still give me access (and it does).
5. I do `vault token-renew ...` and the output is simply the `Key	Value` header.  So it does detect that something has changed.
6. At this point, I've done a token renew, so I would expect future calls to things (`vault list /secret` or whatever) should fail.  It does not.  Everything still behaves as if my token was valid.

Is there a step missing (or not working) to revoke the token if the validity check fails?

**Comment by vishalnayak** [comment]
@bkrodgers 
Failure of renewal does not mean that the token gets revoked.
`vault token-revoke` would make the token invalid.

**Comment by bkrodgers** [comment]
I don't see why you wouldn't want that to happen automatically.  We've checked the token and found it to now be invalid.  Why should the token still allow them access?

**Comment by vishalnayak** [comment]
@bkrodgers You are right. I'll get back to you on this!

**Comment by bkrodgers** [comment]
Thanks!

**Comment by jefferai** [comment]
@bkrodgers The reason is that there is an important difference between "the token is invalid" and "the token is no longer allowed to be renewed".

When you authorize someone, you are authorizing them for a certain amount of time. The fact that you don't want them to continue to be able to use the system after that amount of time has expired is a separate concern from the fact that you authorized them for the initial period. And, importantly, Vault has no control over *when* the user renews. If the user is authorized for six hours and immediately an administrator changes the initial conditions under which that authorization was given, the user could choose to renew in one minute, or they could choose to renew in six hours. That's why lifetimes should be chosen such that they are the maximum amount of time you are comfortable with the user having access before re-authenticating.

Vault tries to be deterministic. Random revocation times based on when tokens are renewed are both non-determinstic and simply encourage users and applications to wait as long as possible to attempt renewal, which defeats the purpose in the first place. In addition, there are legitimate reasons why an administrator may want to change configurations around but not disrupt existing behavior (for instance, migration to new policies). Revoking tokens because the configuration has changed means not only that token but all of its leases (dynamic credentials, etc.) will be revoked instantly, which could be catastrophic for legitimate applications. Better to give them a chance to deal with the situation properly, by re-authenticating, getting a new token, using that to get new credentials, and switching over to those new credentials for e.g. new database connections, after the old ones are finished.

If you need to lock someone out immediately, revoke their token. This may mean revoking other tokens as well, e.g. if you `revoke-prefix` the entire GitHub mount (keep in mind that you can have multiple mounts of each auth backend, and this is one of the reasons why), but everyone else will be able to immediately re-authenticate. Revocation is the only way to ensure that the user is locked out _at a time of your choosing_, rather than at some random time if and when they decide to renew, which very well may not be until the entire initial TTL of their issued token.

**Comment by bkrodgers** [comment]
@jefferai -- Thanks for the detailed response.  I do set my max github token lifetime to the length we're comfortable with (a day for now, we may lower that). My concern prior to Vishal's change was that since the token was renewable and didn't get re-checked, they could set up a script to renew it forever and never time out.  Now that it is checking it on renew, is the empty 'Key Value' response on a token renew an indication that the token has not been renewed and will time out based on its original TTL?  It wasn't returning an explicit error saying the lease can't be extended and the TTL is still the original.  I'll test that to make sure.

I do agree that revoking a token explicitly when their access changes would be the best option.  However, since (to my knowledge) there's no way as an admin to find the token based on the Github user that it belongs to, there's no way to do this.  Revoking all github tokens is not a good solution.  In fact, it's an infinitely more egregious violation of the principle in your comments on being deterministic.  

Would it be possible to create such an endpoint?  Maybe not to return the token itself, as that seems somewhat problematic, but one that will search for tokens with certain metadata and revoke them.

**Comment by jefferai** [comment]
Renewing, if it hits a max TTL, simply caps the renew operation to that max TTL. Therefore, renew will always succeed unless the token has been revoked. It just may not actually return a lease duration longer than the current value, so the caller can check it.

> In fact, it's an infinitely more egregious violation of the principle in your comments on being deterministic.

It's not, though: you as the administrator know exactly what tokens will be revoked when. And this can be communicated to your users. That's perfectly deterministic. I think what you mean to say is it's not _friendly_.  :-)

> Would it be possible to create such an endpoint? Maybe not to return the token itself, as that seems somewhat problematic, but one that will search for tokens with certain metadata and revoke them.

Yes, it's certainly possible, although it would be very slow. We don't index by metadata and I don't think we will, so this would require crawling through all tokens and searching. As a break-glass procedure, that's not too bad.

**Comment by bkrodgers** [comment]
Well, with the change #1047, renew doesn't succeed if it fails the validation checks, right?  The return from vault CLI is just an empty `Key Value` header, but I'm not sure what that actually means on the back-end.  I would hope that it would not extend the lease in that case.

**Comment by jefferai** [comment]
Yes, sorry -- if it fails validation it doesn't succeed; however, if validation works, it attempts to extend the lease. At this time, the extended time will be capped if it's passed the max allowed TTL.

BTW, if you're seeing empty key/value output, are you using `vault renew` or `vault token-renew`? I believe that both would work but the latter is the best way to do it.

**Comment by bkrodgers** [comment]
I'm seeing the empty key/value output when I do `vault token-renew` (when I no longer have the same github memberships)

**Comment by jefferai** [comment]
Hmm. @vishalnayak can you look into that and make sure that's the new expected behavior?

**Comment by vishalnayak** [comment]
@bkrodgers  

The actual return value from Vault API is a JSON object.
The CLI tries to print it out in a default format (`table`) and the `Key/Value` you see are the column names in this format.

If you use `vault token-renew -format=json <token>`, you should see the result of renewal in the `auth` subsection of the JSON result.

**Comment by jefferai** [comment]
@bkrodgers @vishalnayak reproduced the empty response. We're digging into it.
