### ISSUE TITLE
Allow configurable values for RetryWaitMin and RetryWaitMax field in Vault client

### ISSUE THREAD

**Issue by developer-guy** [hashicorp/vault#11675]
**Describe the bug**

We can't configure the values of RetryWaitMin and RetryWaitMax in Vault Client [here](https://github.com/hashicorp/vault/blob/master/api/client.go#L922-L923).  is it a bug, or was it done on purpose?

It had better make those fields dynamic configurable since we can not override the values.

**Comment by mahalrs** [comment]
Hey @vishalnayak, I am new to open source, and I would like to contribute to this project. Can you guide me on what needs to be done. I have read the [CONTRIBUTING.md](https://github.com/hashicorp/vault/blob/master/CONTRIBUTING.md) and I have everything setup for local dev.

**Comment by vishalnayak** [comment]
@mahalrs Thanks for showing interest in contributing!

The goal is to make the RetryWaitMin and RetryWaitMax as configurable values. Each of these should have a corresponding fields in the [config](https://github.com/hashicorp/vault/blob/master/api/client.go#L62). Then the values from config should be put to use.

You will need to move the current hard coded values that we are using into the DefaultConfig() function.
And add support for corresponding env vars in the ReadEnvironment() function.

Let us know if you have more questions along the way and we'll be happy to help.

**Comment by ncabatoff** [comment]
I have a little concern re backwards compatibility.  We expect that when calling NewClient, people will either provide a nil config, or a config that they created starting from DefaultConfig.  If they do either of those, @vishalnayak's proposal above will work fine.

But suppose instead of using DefaultConfig, they are just creating a Config from scratch, and they didn't look closely at the change history when adopting the new version of the client that introduces these min/max options?  In that case RetryWaitMin and RetryWaitMax will be zero and retrying will be broken.

To protect against that, I suggest that NewClient treat a zero value for RetryWaitMin and RetryWaitMax in the config to be equivalent to the default value.  This means it won't be possible to configure them to be zero, but I think that's okay: the backoff funcs I've seen would generally break or behave very badly if either were zero anyway.

**Comment by mahalrs** [comment]
@vishalnayak When reading RetryWaitMin and RetryWaitMax in [ReadEnvironment()](https://github.com/hashicorp/vault/blob/master/api/client.go#L248), should it be in milliseconds or in seconds (like ClientTimeout).

If in milliseconds, there is no ParseDurationMillisecond function in [parseutil](https://github.com/hashicorp/vault/blob/master/sdk/helper/parseutil/parseutil.go). So, should I submit an issue and work on that first.

**Comment by mahalrs** [comment]
> @vishalnayak When reading RetryWaitMin and RetryWaitMax in [ReadEnvironment()](https://github.com/hashicorp/vault/blob/master/api/client.go#L248), should it be in milliseconds or in seconds (like ClientTimeout).
> 
> If in milliseconds, there is no ParseDurationMillisecond function in [parseutil](https://github.com/hashicorp/vault/blob/master/sdk/helper/parseutil/parseutil.go). So, should I submit an issue and work on that first.

Because the current hardcoded value uses milliseconds, I think it is good idea to take env values for RetryWaitMin and RetryWaitMax as msecs. @vishalnayak Let me know what you think and I will submit a issue for adding ParseDurationMillisecond() in [parseutil](https://github.com/hashicorp/vault/blob/master/sdk/helper/parseutil/parseutil.go).

**Comment by mahalrs** [comment]
> @vishalnayak When reading RetryWaitMin and RetryWaitMax in [ReadEnvironment()](https://github.com/hashicorp/vault/blob/master/api/client.go#L248), should it be in milliseconds or in seconds (like ClientTimeout).

I think it would be a good idea to take env values for RetryWaitMin and RetryWaitMax as millisecond.

Also, there are two ways to make RetryWaitMin and RetryWaitMax configurable:
- read values through [ReadEnvironment()](https://github.com/hashicorp/vault/blob/master/api/client.go#L248)
- add SetMinRetryWait() and SetMaxRetryWait() like [SetMaxRetries()](https://github.com/hashicorp/vault/blob/master/api/client.go#L544)

@vishalnayak I think it would be better to implement both ways. Let me know what you think.

**Comment by vishalnayak** [comment]
@mahalrs I think the unit of seconds should be easier for users to understand and operate on. A lot of other APIs in Vault also consume input in seconds. Making this a unit of seconds will retain that consistency. (In this regard, I might close the issue/pr that you have created for supporting millisecond). Sorry for not getting back to you sooner.

Regarding the ReadEnvironment(), we discussed it internally, and we intentionally omitted that part in our guidance for this task. The rationale was to add it in future only if warranted by many users. So, kindly not add the env var support for these knobs.

**Comment by mahalrs** [comment]
@vishalnayak Thanks for the reply. I am about to submit a PR.
