### ISSUE TITLE
Proposal: set renewable to false when a lease has reached its maximum duration if the lease cannot be extended

### ISSUE THREAD

**Issue by alistanis** [hashicorp/vault#1173]
I'd like to have a way to easily determine whether or not a current lease can actually be extended in the case that it is renewable but has been leased for its maximum duration. Currently, it seems that if I have a lease, I can renew it up until the maximum lease duration, but my application does not have an easy way to tell what that duration is. I could check to see if the lease duration is actually extended, but it seems that this could be handled a little more elegantly. 

I'd like to either: 
1) set renewable to false when a lease reaches maximum duration, or
2) provide the maximum lease time in the json response

If this is something that is already easily done and I'm just missing it, please let me know, but if not, and either of these approaches seem reasonable, I have no problem implementing this myself and submitting a pull request back to you.

Thanks!

**Comment by jefferai** [comment]
Hi @alistanis ,

There isn't a way to set renewable to false when it's reached maximum duration because a renew operation can specify an increment -- which can be ignored, although it tries to be satisfied -- which can be for less time than the current maximum. So if I have a lease for 60 minutes max, and at 30 minutes I attempt to renew for 60 minutes, it will get capped to another 30 minutes. However, it's valid for me to renew for 2 minutes, at which point my current lease TTL is now 2 minutes, but with the ability to extend 28 minutes beyond that. The reason for this is so that services or users can reduce the lifetime of their lease if they don't actually need the full possible extent.

We also can't provide the maximum lease time in the JSON response because it's not necessarily fixed. An administrator could change this at any time, and renew operations check the current maximum value against the issue time of the lease to determine whether it's allowed. So any information given at lease issue time is subject to change.

Renewable instead literally means whether a renew operation can be run, period. Not all leases support renew operations, and so those are not renewable.

Given that the requested increment may not be granted, you should always check the value of the lease duration returned from a renew call. If it's less than the requested time, it's a good indicator that the max has been hit. In addition, our best practice (for example, what Consul Template does) is to simply use the halfway point of the lease duration as the renewal time, which in most cases will give plenty of warning if you're close to hitting the max.

**Comment by alistanis** [comment]
@jefferai ,

Thanks for the speedy response. That actually makes a lot of sense. I'll suck it up and write a smarter application,

Chris

**Comment by jefferai** [comment]
@alistanis Yeah, a lot of things about Vault can make you scratch your head until you understand the rationale behind the way things are. *Usually* at this point there is a good explanation. :-)
