### ISSUE TITLE
Feature: Add "environment" sink to Vault Agent

### ISSUE THREAD

**Issue by nhlushak** [hashicorp/vault#11745]
**Is your feature request related to a problem? Please describe.**
Currently I am integrating Vault to my infrastructure to replace AWS SSM Parameters Store. And I have encountered with a difficulty of providing a proper way of authenticating my secret injection tool against Vault. My current setup is an ECS service which has IAM role attached and eligible to read from AWS SSM Parameter Store. And I am very into keeping this way of authentication with Vault. The problem is that currently `vault agent` support AWS Auth, but sinks resulting token in a plain file. That is very frustrating since the whole idea of IAM roles was to eliminate any credentials to be stored on host system.

**Describe the solution you'd like**

It would be awesome if vault agent could sink resulting auto-auth token not just to file, but also to environment. E.g.:
```
auto_auth {
  method "aws" {
      mount_path = "auth/aws"
      config = {
          type = "iam"
          role = "dev-role-iam"
      }
  }

  sink "environment" {
      key: "VAULT_TOKEN"
      }
  }
}
```

**Describe alternatives you've considered**

For now I am stuck with running vault agent on container startup, grab file containing resulting token, export it as `VAULT_TOKEN`, remove file and then run secret injection tool with application.

**Explain any additional use-cases**

Most of open-source secret-injection tools that support Vault use token for authentication. Even Hashicorp's own [envconsul](https://github.com/hashicorp/envconsul#vault) This feature could expand usage of this tools by far by allowing to use more than a standard auth flow.

**Comment by vishalnayak** [comment]
Thanks for submitting this! For those others who are also interested in this, please hit the thumbs up emoji on the issue.

**Comment by slemme1** [comment]
I am just exploring the use of the agent and auto-auth and that was one of my first questions -- can I sink to an environment variable!  @NikitaGl Note that you can set an environment variable aad_env_var with a "seed" value to encrypt the file that is created so that it cannot be easily unencrypted without that value, but this would still require some extra processing (at startup or when the client needs to use the token) to unencrypt the file.

**Comment by liad5h** [comment]
this would be really nice, especially if the token can be injected as an environment variable to other containers in the same pod.

**Comment by MattBathgate** [comment]
Would be a very useful feature to avoid extra code in applications that have no interest in reading from files to get tokens that could be easily pulled from the environment.

**Comment by VioletHynes** [comment]
Thanks for this suggestion! This has been implemented as a Process Supervisor mode, and supports rendering everything a file template can as environment variable (including tokens) 

https://developer.hashicorp.com/vault/docs/agent-and-proxy/agent/process-supervisor

**Comment by nhlushak** [comment]
@VioletHynes Nice, thanks for pointing that out!
I see that it requests providing an `env_template`. Does it able to just expand whole object as set of environment variables?
For instance, I have such secret in my Vault:
```
vault kv get -format json -field data /secret/prod/myservice
{
  "API_KEYS": "xxxxxxxx",
  "DB_TSYS_RW_URL": "postgres://user:pass@postgresdb.aws.amazon.com:5432/mydb",
  "SECRET_SAUSE": "xxxxxxxx"
}
```
And I want Vault agent to load it into running process as set of variables and do it dynamicaly for any object content. 
According to documentation you provided I just don't seem this as doable for now and leaving us to continue to use envconsul.

**Comment by VioletHynes** [comment]
Hmm, I'm not sure it's able to 'automatically' expand a set of KV pairs into a set of environment variables, but usually it's useful to be able to define which environment variable names the secrets go to. Furthermore, it's possible to massage any of the keys as part of the process if they need a different format of any kind.

Since the `env_templates` are built to work the same as file templates, all of the template functionality is built-in (i.e. `secret`, `pkiCert`, and all the other helpers), and you can vary stuff like renewal rates and refresh rates. The only difference is that it goes to an environment variable, not a file.

**Comment by nhlushak** [comment]
You’re absolutely right.

However, if you’re someone who values keeping things organized from the start, and your secret’s context already aligns with the correct naming and structure for the variables you want to pass into your running application, this step can feel more frustrating than flexible.

In such cases, you’d expect to simply add a new field to your Vault secret and have it automatically show up as a new environment variable after a process restart or similar action. Instead, you’re forced to manually update and resubmit your Vault Agent configuration, effectively doubling your workload.
