### ISSUE TITLE
Run vault server command in detach mode.

### ISSUE THREAD

**Issue by HarshMultani** [hashicorp/vault#11770]
I am trying to run vault in a docker container.

Like This :- 

    vault-server:
      image: vault
      restart: always
      container_name: vault-server
      ports:
        - 8400:8400
      volumes:
        - ./config:/var/lib/postgresql/vault
      environment:
        - VAULT_ADDR=http://0.0.0.0:8400
      command: >
                      sh -c "vault server -config=/var/lib/postgresql/vault/vault-config.hcl && 
                                vault operator init"
      cap_add:
        - IPC_LOCK

Now, as I want to initialize and unseal the vault automatically using commands, how I can do this.

If I am using the above script, the server command is not running in detach mode and so the command after that is not able to execute.

Is there any way I can achieve this @vishalnayak 
Thanks

**Comment by vishalnayak** [comment]
@HarshMultani 
Initialization uses a concept called [Seal/Unseal](https://www.vaultproject.io/docs/concepts/seal) which should be done using one of the [supported seals](https://www.vaultproject.io/docs/configuration/seal).
Since I don't know the contents of the vault-contif.hcl file, I am assuming that you are trying to use Shamir seal.

For which the command should go something like the following:
```
vault operator init -key-shares 1 -key-threshold 1
```

Besides, take a look at the official Vault docker images available at https://hub.docker.com/_/vault
You can do a `docker run` on it.

Hope this helps!
