### ISSUE TITLE
Hover tooltip wrong for CA role domain handling

### ISSUE THREAD

**Issue by HiranChaudhuri** [hashicorp/vault#12226]
Having configured vault as CA and intermediate CA I tried to add another domain to the setup.
When expanding the "Domain Handling" section on the role configuration screen I see the tooltip on allowed domains saying

    This parameter accepts a comma separated string or list of domains

This is not true. You have to put one domain name per input field and press add.

**Comment by hsimon-hashicorp** [comment]
Hi @HiranChaudhuri - please check out the reply from @aphorise and let us know if you have more details for us. Thanks!

**Comment by HiranChaudhuri** [comment]
I am referring to this tooltip:
![Screenshot from 2021-09-22 22-43-51](https://user-images.githubusercontent.com/6866487/134419273-0f04a794-5b9c-4e4c-a392-c461df617343.png)


I took this from Vault 1.8.2.

**Comment by arnav28** [comment]
Hi @HiranChaudhuri 
In UI either you can enter domain names per input or provide a comma separated string in the input box, both ways are supported that's why the tooltip says `parameter accepts a comma separated string or list of domains`.
We will consider this as a feedback and will review with design team to check if more users are getting confused with this UI component. Thanks :)
