### ISSUE TITLE
(Re)initializing vault

### ISSUE THREAD

**Issue by waghanza** [hashicorp/vault#1224]
Hi,

I'm playing with `vault`
* creating **deb** package
* installing / removing
* create `systemd` script
* ....

I have built and `linux/amd64` version and packed it into a **deb** package (backend => file).

After removing / (re)installing my package, I have an error on initialization
`VAULT_ADDR='http://127.0.0.1:8200' vault init` 
Vault says :
```
Error initializing Vault: Error making API request.

URL: PUT http://127.0.0.1:8200/v1/sys/init
Code: 400. Errors:

* Vault is already initialized
```
What does it mean ?
Regards,

**Comment by jefferai** [comment]
Hi @waghanza,

Can you please post questions on the mailing list (https://groups.google.com/forum/m/#!forum/vault-tool) rather than in GitHub issues? This gets a lot more eyes on any particular question or idea.

It also prevents problematic issue workflows for questions where either the issue is closed immediately but then discussion continues on a closed issue; or, the issue is not closed, discussion dies down, and the issue remains open indefinitely waiting for further potential replies.

Thanks!
