### ISSUE TITLE
"Server" header

### ISSUE THREAD

**Issue by msabramo** [hashicorp/vault#1225]
Should Vault HTTP responses have a "Server:" header?

Or is that considered too sensitive for a security-related product?

Personally, I would like to know what Vault version I am talking to and what IP address I am talking to.
The reason for the IP address is that I am currently dealing with a misconfigured advertise address problem, so when I hit Vault and I do not happen to get the master node, it responds with an HTTP 307 redirect to an HTTPS URL with an IP address in it and most versions of Python do not know how to verify certificates for URLs with IP addresses in them (this was fixed only recently in Python 3.5 -- See https://bugs.python.org/issue23239) so everything barfs. It would be handy for know which server is sending this HTTP 307 so that I could try changing the advertise address on one and then be able to verify that the node I modified is fixed.

But would it be bad, security-wise for Vault to respond with a "Server:" header? I guess if it responds and says "Vault version ??.??.??" then that could help an attacker to know to try certain exploits? In that case, maybe just the IP address?

**Comment by jefferai** [comment]
Hi @msabramo ,

Non-active nodes redirect to the `advertise_addr` of the leader. It will try to detect this address, which will be detection of an IP address, but if you manually configure it you can use a full host name, e.g. `advertise_addr = "https://vault1.myorg.com"`.

**Comment by msabramo** [comment]
Oh. I think you just made me realized that what I was about to do is not ideal. I was going to set the `advertise_addr` to a URL with a DNS name that is resolved by Consul. That is probably not a good idea as then it will redirect to the pool and it could go to the wrong node again and redirect several times. I probably should use the hostname of the specific machine so that the redirect will work the first time.

What do you think of Vault having a "Server:" response header with the hostname or IP address? I guess it could be a configuration option that defaults to false so that it doesn't expose any additional info by default.

**Comment by jefferai** [comment]
I guess I don't really understand the use-case, given that your initial use-case is fixed by configuration :-) It also seems unnecessary to give out what could be a private IP purposefully kept under wraps by a load balancer or reverse proxy in front, or to give out a Vault version in case someday there are known exploits.

**Comment by msabramo** [comment]
Yeah the use case is fixed by configuration, I think (still trying to verify that).

I guess what I didn't mention is that I wanted to adjust the configuration on only one node and then test to see that one node was sending the right hostname in the 307 redirect.

The reason for wanting to test only a single node is every time I restart Vault, it becomes sealed again. So if I run an ansible playbook that reconfigures and restarts all 3 of my Vault servers, then I have to go and unseal 3 Vault servers, which is kind of a pain.

I was hoping to get a bit more info so I could be a little more targeted in my testing and not have to restart and unseal quite as much. But that could just be me being lazy.

**Comment by jefferai** [comment]
> I wanted to adjust the configuration on only one node and then test to see that one node was sending the right hostname in the 307 redirect.

Keep in mind that the `advertise_addr` will never be given out by the node you configured it on. It's the address given out by standby nodes when the node you set it on is the active node. So in order to test it out, you'll need to configure it on a node, then restart that node, then force the other nodes to give up leadership (for instance via step-down in 0.5.2) until the node you restarted is the active node again, then hit up your standby nodes for the redirects. If you are able to unseal your Vault servers on your own, that sounds easier to me :-)

**Comment by msabramo** [comment]
Yeah unsealing wasn't *that* hard once I got into a good copy/paste rhythm :smile: 

and I guess I could write an ansible playbook to unseal the servers as long as I keep the unseal keys local and don't commit the unseal keys to version control.

Going to close this.

Thanks, @jefferai!
