### ISSUE TITLE
Unable to copy inline text from vault secret

### ISSUE THREAD

**Issue by trutled3** [hashicorp/vault#12350]
**Describe the bug**
After creating a json secret in vault, I am unable to copy inline text from the secret. I am only able to copy inline text after hitting "Edit" on the secret. It may be related to https://github.com/hashicorp/vault/pull/11500

**To Reproduce**
1. Create json secret in kv secrets engine
2. Attempt to highlight text and right click to copy and unable to do so.
3. See error

![image](https://user-images.githubusercontent.com/89163186/129967917-83573156-4a9d-4827-af65-329a53027c45.png)

**Expected behavior**
To be able to highlight inline comment and able to copy without having to click "Edit"

**Environment:**
* Vault Server Version (retrieve with `vault status`): v1.8.1
* Vault CLI Version (retrieve with `vault version`): N/A, was able to replicate with docker.
* Server Operating System/Architecture: N/A, was able to replicate with docker.

Vault server configuration file(s):
Can replicate with 
docker run -it --rm -p 8200:8200 vault:1.8.1

**Comment by timonych** [comment]
> @timonych thank you for posting this issue. We're looking into it. It should be an easy fix, but there might be a little more to it, involving the removal of a deprecated plugin. I created a ticket and will hopefully tackle this soon.

Thanks for information, waiting for fix this trouble.

To be honest, @trutled3 has opened this issue. I've only add additional info about version and problem.

**Comment by Monkeychip** [comment]
This has been fixed and backported to 1.8.x -1.10.x. The fix for 1.8 -1.10 will show a blinking cursor when in readOnly mode but you will now be able to copy/paste. The fix for 1.11 will not show a blinking cursor and will allow you to copy/paste. The fix for 1.11 was a complete refactor which gave us more control over the css and removed a deprecated wrapper. Thanks @trutled3 for opening the issue and everyone for upvoting or commenting on it.
