### ISSUE TITLE
Postgres Storage Backend Connection Failure

### ISSUE THREAD

**Issue by mdgreenfield** [hashicorp/vault#12415]
**Describe the bug**

We've encountered an issue when using TLS enabled postgres connections using `Azure Database for PostgreSQL` w/ golang 1.15 or newer and lib/pq versions prior to v1.9.0. When this issue occurs, connections will fail, but not be purged from the lib/pq pool and will continue to be used by the Vault unsuccessfully until Vault is restarted.

```
1 error occurred:
	* failed to persist lease entry: write tcp <vaultLeaderNode>:58492-><postgresNode>:5432: write: connection reset by peer
```

When this error occures we're able to SSH into the `vaultLeaderNode` and successfully establish connections to the `postgresNode:5432` showing that new connections can be established without issue.

```
$ nc -zvw3 <postgresNode> 5432
Connection to <postgresNode> 5432 port [tcp/postgresql] succeeded!
```

**Expected behavior**

The connection pool should recover from failed connections.

**Environment:**
* Vault Server Version (retrieve with `vault status`): 1.7.2

Vault server configuration file(s):

```hcl
backend "postgresql" {

  connection_url = "host=<%= @postgres_host %> user=<%= @postgres_user %> password=<%= @postgres_password %> dbname=<%= @postgres_dbname %> sslmode=<%= @sslmode -%>"
}
```

**Additional context**
It may be prudent to also allow operators to configure the Postgres `SetConnMaxLifetime` similar to how `SetMaxOpenConns` and `SetMaxIdleConns` can be configured.

**Comment by doctork9999** [comment]
I ran into the same issue here quite strange that it happens everytime when the Azure Postgres Database is restarted, the broken connections are lingering around and not evicted. I ended up testing the same scenario locally as well as other cloud providers, i.e. AWS and don't see this symptom. The PR seems to explained the part that the new TLS error was introduced and the additional error handling in the lib/pq but why the symptom did not happen everywhere else?

**Comment by doctork9999** [comment]
Running some tests and now I can see why it only occurs in Azure, it looks like when the connections are closed in Azure, they are closed in quite an odd way, there was no FIN message to notify client to close the connections.

![Screenshot from 2021-09-24 19-25-50](https://user-images.githubusercontent.com/91298592/134652344-d6a24e5c-b2f7-4028-ac6e-18bf9815d795.png)
![Screenshot from 2021-09-24 19-26-22](https://user-images.githubusercontent.com/91298592/134652350-5ede879c-fa84-4f4a-93df-5a961f7ff7c0.png)

I see that this commit still serves its purpose to introduce the `permamentError` type to the error handling in the `tls` module. Dig deeper and find that when the connections are closed normally with the **FIN** message notifying back to the clients over the network sockets, they appear to be closed off normally and when tls.conn attempts to write data to those connections that are already closed, the error it gets is not of the type `net.Error`, instead, it is `io.EOF`, so it falls into the `else` condition of function `setErrorLocked` and returns back to the `lib/pq` with error type `io.EOF` instead of the wrapper `permamentError`.

https://github.com/golang/go/commit/614a713be560ca86dcca570a8b872614d822eb9

In the scenario where FIN message is received and the write function returns with the error type of `io.EOF`, the `lib/pq` in the latest version of Vault, which is still at 1.8.0, is able to handle the error OK and the closed connection is marked as bad for eviction.

https://github.com/lib/pq/blob/v1.8.0/error.go#L498-L503

It is odd when I see Azure Postgres keeps closing the connections this way, hope that someone will let them know where the underlying cause of this odd symptom is from exactly and get it fixed but the update to the newer version of `lib/pq` should be able to cover this flaw from the lower level as well so hope it comes out soon.
