### ISSUE TITLE
FTBFS w/ Go1.17

### ISSUE THREAD

**Issue by the-maldridge** [hashicorp/vault#12456]
**Describe the bug**
Fails to build from source.

**To Reproduce**
Download a recent source tarball.
Try to build it with Go1.17.  Observe build fail due to go-limiter importing private resources that are protected in Go version 1.17.

**Expected behavior**
I expected Vault to build.

**Environment:**
Build environment is a Void Linux build server.  The complete environment is specified as part of [xbps-src](https://github.com/void-linux/void-packages/), but for practical purposes its a Linux environment with Go, 1.17 available.

**Additional context**
Looks like someone on the forum has already root caused this: https://discuss.hashicorp.com/t/basic-build-error/28526, and the issue has already been resolved upstream: https://github.com/sethvargo/go-limiter/issues/23.

**Comment by pmmukh** [comment]
Thanks for submitting the issue! Just dropping a note that there's an open PR https://github.com/hashicorp/vault/pull/12358 that is being worked on, that will fix this.

**Comment by AbbyDeng** [comment]
nicely reported issue! thanks a lot, we're also having it

**Comment by the-maldridge** [comment]
Fantastic.  Any idea of the timeline on this one?  I am trying to decide if I should import the patch from #12358 into Void to get the build un-stuck.

**Comment by pmmukh** [comment]
@the-maldridge i don't really have a timeline for you, sorry! you are def welcome to directly use the patch on the PR in the interim, but fair warning that it is currently failing tests and so might have issues down the line, so I would recommend waiting until the PR is merged in, tbh.

**Comment by the-maldridge** [comment]
Hmm, that is unfortunate.  I can flag the package as upstream_broken until the fix rolls out then.  Do you know if Vault will be adding any kind of CI gate to avoid this in the future (this being that Vault doesn't appear to do CI against the stable matrix for the Go language)?  Having a dependency that linked an internal implementation of the language runtime is a liability that surprised me in production software like Vault.

**Comment by pmmukh** [comment]
Oh yeah, so this issue is only happening cause here you're trying to build Vault with go 1.17, which we don't actually support yet. You'll notice that both the `main` and `1.8.x` release branches are using go 1.16. We do have CI gates that would catch this, had we been trying to release a version of Vault built with go1.17 this would've been caught earlier, i promise 🙂

**Comment by pmmukh** [comment]
So the PR to update the go-limiter version has been merged in now, and I just verified that the binary does get built on darwin/amd64 with go.1.17. Although that's a different environment than specified here, I think the issue wasn't platform specific so that shouldn't be a problem. I'm going to go ahead and close out this issue, but if the problem persists feel free to reopen it!
