### ISSUE TITLE
Can auth & secret backends be integrated more closely?

### ISSUE THREAD

**Issue by radeksimko** [hashicorp/vault#1247]
There are cases, specifically in AWS where it would be valuable to integrate Auth Backends and Secret Backends.

AWS currently provides multiple ways of generating temp credentials:

1. IAM User can have MFA device attached w/ policy enforcing use of MFA
   - `sts:AssumeRole(roleARN, mfaDeviceArn, mfaTokenCode)`
2. SAML can be used to assume IAM Roles - `sts:AssumeRoleWithSAML(roleARN, SAMLresponse)`
3. OpenID Connect-compatible IdPs (OAuth) can be used to assume IAM Roles - [`sts:AssumeRoleWithWebIdentity(roleARN, token)`](http://docs.aws.amazon.com/cli/latest/reference/sts/assume-role-with-web-identity.html)

-----------

1. Since Vault currently makes auth & secret backends separate, there doesn't seem to be any way for an AWS Secret Backend to get SAML response from a (hypothetical) SAML Auth Backend.
2. There isn't a way to manage MFA devices for an AWS account (yet there are APIs available for all this) via Vault.
3. There doesn't seem to be an easy way to pass a token from (hypothetical) OAuth/OpenID-based Auth Backend to AWS Secret Backend.

Admittedly this might not fit into the current concept of policies which are at the very centre of Vault since the SAML response / OpenID token would usually carry a certain level of permissions already.

Also you may argue that this may potentially allow leakage of some data between backends and Vault should be there as a strict proxy, not just an observer.

There would be a value for users that already use a "secure setup" in AWS with federated logins or MFA.

If there is no interest in making this possible, I'm :ok_hand: with that, but I'd like to see the reasons behind such decision. If you think it's worth separating this issue into more, I'm also :ok_hand: with that.

**Comment by jefferai** [comment]
Hi @radeksimko ,

Vault doesn't just make auth and secret backends separate, it makes *all* backends, and all mounts of each backend, separate. They have no mechanism for crosstalk, and they don't share data storage areas. This is by design, in order to enforce separation of data and ensure that data can't leak from one backend to another.

I think maybe you're a bit confused on the role of an auth backend; it's not to give Vault credentials to be used by another backend...it's to give a user a Vault token by relying on an external party for authentication/authorization information. You'd never get a SAML response from a hypothetical SAML auth backend and pass it into an AWS secret backend, because the only role of a SAML auth backend (or any auth backend) is to provide the client with a Vault token. After that, what can be done with the AWS secret backend depends on the client's Vault token.

MFA is a bit of a separate matter: The current mechanism, implemented as a pseduo-backend, will be changed at some point to a mechanism that has it entirely separate from backends, so that it can easily be layered onto any of them.

Hope that clears things up!

**Comment by radeksimko** [comment]
Understood! Thanks for detailed explanation. :+1:
