### ISSUE TITLE
Allow configuration of ~/.vault-token path using an environment variable.

### ISSUE THREAD

**Issue by W1M0R** [hashicorp/vault#12494]
**Is your feature request related to a problem? Please describe.**
For 12-factor projects, it is common to set project-specific environment variables. If two 12-factor projects both use the vault cli to login to project-specific vault dev server instances, then they will each overwrite the ~/.vault-token of the other project.

**Describe the solution you'd like**
Having the vault cli respect a VAULT_CLI_TOKEN_HELPER_FILE environment variable (or similar), will enable two different projects to support simultaneous login to two different vault instances.

**Describe alternatives you've considered**
An alternative is to always use the VAULT_TOKEN environment variable and -no-store when using the vault cli. Another alternative is to implement a custom [token helper](https://www.vaultproject.io/docs/commands/token-helper#example-token-helper).

**Explain any additional use-cases**
None.

**Additional context**
None.

**Comment by systemmonkey42** [comment]
I would like to have the option for the TOKEN be in to $XDG_CONFIG_HOME or in the current directory or any parent.

Having only a single tokens per account is a nightmare when you want a cron job or systemd task to run. but have its own specific credentials.

**Comment by hsimon-hashicorp** [comment]
Hi folks! Since `vault login` is intended to be utilized by an interactive user process, and since there's the token helper already, we've decided this is not a direction we'd like to take the product due to concerns about adding insecurity. Thanks for understanding.

**Comment by ieugen** [comment]
I believe this should be re-opened. 

I use vault client as an interactive user and I do believe it should store it's data under XDG directories instead of directly under my home. 

Please see XDG spec here https://specifications.freedesktop.org/basedir-spec/basedir-spec-latest.html 
and a list of nice behaving apps here: https://wiki.archlinux.org/title/XDG_Base_Directory .

Since token is supposed to expire, it might be treated as runtime or cache data and use: XDG_CACHE_HOME or XDG_RUNTIME_DIR should be considered.

IMO the wild wild west era of linux/unix programs is over and applications should behave and follow the specs and standards.

**Comment by peikk0** [comment]
IMO the token should go in `$XDG_STATE_HOME` if set.

**Comment by ieugen** [comment]
I believe $XDG_STATE_HOME has a default value if NOT set. 
All XDG env variables have defaults if not set. 
This way the spec is OPT IN.
