### ISSUE TITLE
How to backup data periodically without any vault downtime?

### ISSUE THREAD

**Issue by ShubhamDX** [hashicorp/vault#1273]
I am using consul as my backend. Is there some way in which I can take periodic backup/snapshot of my data without having any data-inconsistency and without having any downtime for vault/consul?

**Comment by jefferai** [comment]
I can't give you a definitive answer because everyone's abilities are a bit different. Some people use https://github.com/kailunshi/consul-backup but I don't know if it's guaranteed to be consistent. My favorite method is to put Consul's data on ZFS and use ZFS snapshots to ensure a consistent state of the underlying data. If I need to do disaster recovery I can use that instance to bootstrap new ones.

Generally, think of Consul as a database, and use your favorite consistent database backup mechanism!

**Comment by BSick7** [comment]
@jefferai I know this topic is closed; however, the included repo seems unmaintained as it has multiple PRs that are untouched for months.

I have created an new version of this idea with support for piping and dumping the consul k/v store to a tar.gz file.  I also have an automated process to deploy linux, darwin, and windows binaries to github releases. See [https://github.com/BSick7/envoy](https://github.com/BSick7/envoy).

**Comment by jefferai** [comment]
@BSick7 I would suggest posting that on the Consul mailing list and asking for feedback there, as this is really more of a Consul question than a Vault question and you'll get better feedback!

**Comment by BSick7** [comment]
Thanks @jefferai, will do
