### ISSUE TITLE
Vault behind ELB using HA

### ISSUE THREAD

**Issue by DanHoerst** [hashicorp/vault#1315]
Hi - I'm running two Vault servers on AWS behind an ELB using etcd as the backend. The ELB is listening for HTTPS traffic, terminating SSL, and forwarding to 8200 on the nodes. This ELB is using a healthcheck to the `/v1/sys/leader` endpoint to avoid redirect loops to the non-leader. So essentially the leader shows as `Available` and the other node shows as `Unavailable`.

When I first spin up the cluster, I hit one node directly to unseal the vault (this isn't ideal) and it becomes master. It then becomes `Available` in the ELB and I can hit the node and set/get secrets as expected. For `/v1/sys/leader`, the node responds with:

    {
      "ha_enabled": true,
      "is_self": true,
      "leader_address": "https://vault.domain.net"
    }

The `leader_address` being the CNAME to the ELB. This seems fine. However, when I hit the Unavailable node directly at `/v1/sys/leader` I get:

    {
      "errors": [
        "Vault is sealed"
      ]
    }

This doesn't seem right. Shouldn't this node redirect back to the `leader_address`, essentially having the `Available` node serve the request?

Needless to say, if I terminate the leader node I have to start the process from the start and unseal the vault from either the original `Unavailable` node or the new `Unavailable` node that spins up in place of the terminated instance.

Here is my Vault config:

    backend "etcd" {
      advertise_addr = "https://vault.domain.net"
      address = "http://vault-etcd.domain.net:2379"
    }

    listener "tcp" {
      address = "0.0.0.0:8200"
      tls_disable = 1
    }

Please let me know if there are any more details I can provide or if there is a better way to run HA vault in AWS. Thanks in advance.

**Comment by jefferai** [comment]
Unsealed nodes don't redirect because they can't decrypt the storage with active node information. Standbys are meant to be installed; otherwise they can't take over if the active node goes down.

**Comment by DanHoerst** [comment]
@jefferai Thanks for the quick response. Can you elaborate a bit? If I understand you correctly you are saying that I need to individually unseal each node that I intend to have in the ELB? If this is the case, I can assume that autoscaling is not a good solution for having an HA front end of Vault?

**Comment by DanHoerst** [comment]
So I assume I understood you correctly as unsealing each node individually works. I can instead use `/v1/sys/health` as a healthcheck endpoint and the failover works correctly. I definitely see the upside of the way this works, with the downside being convenience for the typical cloud based infrastructure. If you have any suggestions for streamlining this process they would be greatly appreciated. Otherwise you can close the issue. Thanks!

**Comment by jefferai** [comment]
Hi Dan,

I think the distinction here is around what typical cloud based architecture is...not all process types are suitable for auto scaling groups. For instance, HTTP front end servers generally are, databases generally aren't, with some specific exceptions. Part of Vault's security model means it doesn't handle auto scaling well.

It's up to you if you want to have Vault be unsealed via an automatic process...it's not hard to devise a mechanism that works for you...but you will give up a lot of security by doing so, both because there will not be oversight of the process around who restarted Vault and when and why, and because verifying an unmodified binary also becomes difficult to trust. Not to mention having to securely store the unseal key (s) somewhere.

This question comes up quite a lot, but most people, considering the alternatives, choose to simply not put Vault in an ASG and instead run as many instances as they need to feel comfortable :-)

**Comment by DanHoerst** [comment]
Thanks @jefferai. I totally agree is far as the security concerns go. Thanks for the help.
