### ISSUE TITLE
Cert list operation not working

### ISSUE THREAD

**Issue by bkrodgers** [hashicorp/vault#1325]
The docs suggest you can list certs that have been registered in the cert auth backend.  See https://www.vaultproject.io/docs/auth/cert.html

However, `vault read /auth/cert/certs` (or the equivalent curl) return `unsupported operation`.

**Comment by jefferai** [comment]
I think you meant `vault list`...and for `curl`, either `-X LIST` or adding `?list=true` to the URL.

**Comment by bkrodgers** [comment]
@jefferai -- that worked, but that's not what the API docs say.  Can you reopen this for a documentation fix?

**Comment by jefferai** [comment]
It's what the API docs say, but I've added some more info to clarify it.

**Comment by bkrodgers** [comment]
The API docs say the method is GET, not LIST.

**Comment by vishalnayak** [comment]
@bkrodgers 

See latest doc update commit from @jefferai 
https://github.com/hashicorp/vault/commit/110c483ffc3827f582a85e2cbc4dbd58b5d520a7

You can use the API in the following manner.

`curl -X GET -H "x-vault-token:bbb" "http://127.0.0.1:8200/v1/auth/cert/certs?list=true"`
OR
`curl -X LIST -H "x-vault-token:bbb" "http://127.0.0.1:8200/v1/auth/cert/certs?list=true"`

**Comment by jefferai** [comment]
The docs said it was LIST (in the section heading) with the given endpoint. It also specified GET since listing can be done with GET using ?list=true. That's normal behavior for Vault listing but I have clarified it in this particular document.

In either case, the CLI command for listing is 'vault list', not 'vault read'.
