### ISSUE TITLE
Feature request: Enable extensible physical layer (plugin)

### ISSUE THREAD

**Issue by shaj13** [hashicorp/vault#13269]
**Is your feature request related to a problem? Please describe.**
vault physical package only support a limited number of databases drivers, different applications may have different architecture when it comes to persisting the data, 

**Describe the solution you'd like**
extend vault plugin to support physical Backend & HABackend 

**Describe alternatives you've considered**
n/a

**Explain any additional use-cases**
1. assume the site setup consists of three replicated sites where one of the sites is active and the other is in standby mode for ha purposes, 
each site consists of a vault and database with another bunch of containers. 
indeed to put the vault on active, standby mode, the vault is required to connect into one single database to acquire the lock which interferes with the system architecture. 
right now the only solution is to connect all vaults from all sites into the same active database and when the failover takes place, reconfigure the vault followed by a restart.  

2. On-premise object storage 

3. kv database

**Additional context**

**Comment by hsimon-hashicorp** [comment]
Hi @shaj13 - can you provide more information about what you're looking for? By "database", do you mean storage backend? There's some good documentation about the storage backend options here: https://www.vaultproject.io/docs/configuration/storage

**Comment by shaj13** [comment]
@hsimon-hashicorp 
I would like to be able to extend the storage itself (https://github.com/hashicorp/vault/tree/main/physical). 
right now vault only offer the above list of storage backend's (Postgres, etcd, etc..)
I would like to make this extendable via plugins.
where i can write my own implementation and vault can call my "plugin" instead of communicating directly with the storage 
i.e Postgres. 

IIRC, after taking a deep look at the vault code base, it seems this required a bunch of refactors. 
so i was thinking of adding webhook(gRPC or http) pkg under physical that 
implementing [physical.Backend](https://github.com/hashicorp/vault/blob/main/sdk/physical/physical.go#L33) 
and [physical.HABackend](https://github.com/hashicorp/vault/blob/main/sdk/physical/physical.go#L52). 
once one of the webhook methods is invoked the backend itself run http/grpc request to the target origin server to persist 
the data on the desired storage. 

**flow**:
vault -> webhook -> server that serve webhooks -> save/get data from storage.

obviously the users can configure the webhook in  the HCL config file as following
```txt
storage "webhook" { 
 connection_url = "http://127.0.0.1:9092"
 [OTHER-PARAMETERS...] 
}
```

**Comment by hsimon-hashicorp** [comment]
Due to the level of complexity, as well as the potential for serious performance implications and the potential for data loss, I think this might be something that we would choose not to implement. For the OSS version, only raft, Consul, and filesystem are supported / maintained by HashiCorp for storage backends. Other storage backends often are "community supported", meaning that a member of the community (often the maintainer of the storage backend) contributed the PR and helps with further maintenance. While HashiCorp will accept PRs for review that allow for specific new storage backends, I don't think there will be an effort for an abstraction layer such as what you're requesting here.
Please let me know if you have any other questions. Thanks! :)

**Comment by shaj13** [comment]
closing, will reopen if necessary
