### ISSUE TITLE
Allow configuration for TLS session reset when reloading certificates

### ISSUE THREAD

**Issue by orshlom** [hashicorp/vault#13518]
**Is your feature request related to a problem? Please describe.**
When reloading certifications for Vault using `SIGHUP`, Vault keeps the certificate sessions and does not allow any configuration for it. The current implementation uses the Go TLS defaults which is [7 days](https://cs.opensource.google/go/go/+/refs/tags/go1.16.12:src/crypto/tls/common.go;l=743).

**Describe the solution you'd like**
On TLS load (can be done [here](https://github.com/hashicorp/vault/blob/main/internalshared/listenerutil/listener.go#L75)), enable configuration for session reset. Implementation can use [SetSessionTicketKeys](https://pkg.go.dev/crypto/tls#Config.SetSessionTicketKeys) in order to reset existing saved sessions. 

**Describe alternatives you've considered**
The only option we have found that resets sessions is restarting Vault.

**Explain any additional use-cases**
- A good example is doing certificate rotation on an extremely short time (sub 15 minutes) and needing to reset existing saved sessions.
- When certificates become compromised and required to be replaced, Vault keeps the sessions for the compromised ones.

**Additional context**
None.

**Comment by cipherboy** [comment]
\o Hello @orshlom 

We don't agree with this, for two main reasons: 

 1. In the case of a compromise of Vault's API certificates, the reasonable scenario here is to seal Vault and investigate the compromise. This more effectively prevents reuse of existing session resumption tickets two ways, one by preventing any sensitive data from being returned over the compromised API, and two, because after compromise you'll likely want to restart Vault completely, clearing the cache. 
 2. On large scale deployments, if rotating the certificates (via SIGHUP) caused session resumption ticket invalidation, you'd run into a thundering herd problem as all clients were forced to fully re-handshake (potentially with mTLS as well). Except in limited scenarios where certificates are 15 minutes (most short-lived certs are around 30-90 days), sessions tokens live much shorter than cert lifetime and the extension isn't much of a concern. And organic expiration would prevent a thundering herd. 

I think the best compromise for your deployment would be to lengthen certificate lifecycle and if sessions must be cleared, restart Vault. I'm also not aware of any literature on resetting session caches on traditional certificate rotation (barring compromise of course). 

Let us know if you disagree or have a reference for truncating session length. In the case of the latter, the best course would probably be to file a bug against Go's TLS library.
