### ISSUE TITLE
pki documentation unclear about interactions between glob_domains and wildcards

### ISSUE THREAD

**Issue by drawks** [hashicorp/vault#13530]
**Describe the bug**
pki documentation is not clear as to what the expected behavior is when combining `allow_glob_domains` and requests for literal wildcard domains. Behavior has changed at some point between 1.5.4 and 1.9.1, but no mention of changed behavior is present in any of the release notes/changelogs

**To Reproduce**
1. configure a pki role with `allow_glob_domains` and a domain allowed entry like `*.*.foo` on 1.5.4 and 1.9.1 
2. observe that 1.5.4 will allow cert issuance for wildcards like `*.bar.foo`
3. observe that 1.9.1 will not allow cert issuance for the same request

**Expected behavior**
Expectations are unclear because documentation doesn't describe what should be expected.

**Comment by chongyangshi** [comment]
The use of `glob.Glob` is a much older line of code, but [the change in its input as described above for v1.9.3](https://github.com/hashicorp/vault/commit/5e016cd7c94051dd47ee972db6715b22ddccd534#diff-4ddfb6cce8278968d34e839e8c8989c06fb1514b53d824267fbf2d54306b28cbL348) started passing `sanitizedName` rather than `name` to `glob.Glob` . And this the `sanitizedName` with the leading `.*` already trimmed away would no longer be accepted by `glob.Glob`.

**Comment by cipherboy** [comment]
Hello @dovys and @drawks -- we agree on the assessment here and we're working a fix internally.

**Comment by drawks** [comment]
The change that restores the previous behavior is greatly appreciated, it would still be good if the documentation is clear about what the expected behavior should be. Part of the reason that this took a while to identify as a bug/regression is because the intended behavior is not clearly spelled out anywhere. Since the root problem of this issue is the lack of documentation, I'd appreciate if it could be re-opened until such time as the documentation is updated.

**Comment by cipherboy** [comment]
That's in #14236 which also documents the stuff in #14238. :-) Let me know if you have suggestions for either of those PRs (or the one that landed fixing this issue).
