### ISSUE TITLE
SSH: add not_before_duration feature, like what pki has

### ISSUE THREAD

**Issue by dhbaird** [hashicorp/vault#13608]
**Is your feature request related to a problem? Please describe.**
Would like to backdate SSH certificates as is already possible in PKI, see:
* https://github.com/hashicorp/vault/issues/4639 PKI: new certificates valid ahead of time
* https://github.com/hashicorp/vault/pull/5325 Add ability to configure the NotBefore property of certificates in role api

**Describe the solution you'd like**
See same issue as above.

**Describe alternatives you've considered**
See same issue as above.

**Explain any additional use-cases**
See same issue as above.

**Additional context**
Would be nice to have an option to specify exact valid date/time in the past or future, as well as relative, but in a pinch just relative will dates in the past work (as in issue above).

Thanks!

**Comment by cipherboy** [comment]
Hey @dhbaird -- this makes to me. If you happen to get around to it before we do (likely will be a bit), happy to review a PR for it.

Do note that we've recently modified the API structure of the PKI fields (for `NotAfter` at any rate) to allow both a numeric duration and an absolute timestamp... For _eventual_ consistency, it might be nice support both? My 2c. :-)

**Comment by Gabrielopesantos** [comment]
Hello, I have never used vault but seems seems an interesting issue. Can I take it? Not sure If I will be able to produce any kind of solution but I will try. Thanks

**Comment by cipherboy** [comment]
@Gabrielopesantos Sure! There's a similar PR on the PKI side right now: https://github.com/hashicorp/vault/pull/14178

You could likely model the SSH changes (design wise) off of that. :-) Let us know if you have any questions.

**Comment by Gabrielopesantos** [comment]
Hello, I already made some changes based on the PR you linked but I am now having a few problems.

Before trying to implement the support of both numeric duration and absolute timestamp I would like to test if numeric is working as expected, however, I am having some issues running these tests. They take too much time and seem to fail to running out of memory.

**Comment by cipherboy** [comment]
Hi @Gabrielopesantos,

If I understand you correctly, yeah, `not_before_duration` would simply take a numeric duration (in seconds). I don't (personally) see the value here in _both_ a numeric value and an absolute timestamp. Unlike NotAfter (where the Y10K date is a good reason to specify the exact NotAfter value -- because as an offset in seconds, it'd overflow a 64-bit numeric type), I don't really see the value in backdating by that much? 

I.e., a Y8K-BC value doesn't really make sense, and the time since the Unix Epoch is ~2^30 and definitely fits in a 64-bit value -- backdating certs any further than that again also doesn't really make sense.

For people with a specific back-date in mind, it is a bit of work, but I'm going to imagine it isn't that common of a problem (whereas, clock skew of say, 5 minutes is more common of a problem).


Regarding your second question, I do agree they're a touch slow. These tests can take longer or shorter to run depending on your network connection; they query DockerHub to pull down some testing container images for validating our SSH cert signatures against various implementations.

On my fast connection on a fast system, it takes 1m57s to execute the tests, with the containers pre-fetched. Three minutes or so sounds reasonable on slower systems.

**Comment by Gabrielopesantos** [comment]
Hello, I have opened a draft pull request it the proposed solution. It is not open because I would like to get feedback on what I have done, and how/where to test them.

Let me know if its better to make it ready to be reviewed. Thanks

**Comment by Gabrielopesantos** [comment]
Hello, I have created test to validate differing `not_before_duration` values in `backend_test.go` but could not figure out the other.

I will make the PR ready to review and you can give me feedback.

**Comment by cipherboy** [comment]
@dhbaird Thanks to @Gabrielopesantos's contribution, this should be addressed in the next release of Vault!

**Comment by Gabrielopesantos** [comment]
No problem, thank you for everything as well.
Do you know if there are other "easier" open issues that I could try to tackle? I took a look in the ones labeled as "good-first-issue" but none of the most recent seems to be available.

Thanks in advance.
