### ISSUE TITLE
False positive when deleting secret parent path

### ISSUE THREAD

**Issue by frodopwns** [hashicorp/vault#1369]
Not sure if this is really an issue but I wondered if maybe the output should be different.

If I have secrets in a path like:

secret/dir/s1
secret/dir/s2
secret/dir/s3

and I run the command:

```
/ # vault delete secret/dir
Success! Deleted 'secret/dir'
```

It says success but nothing really gets deleted.

Should the cli tool try to determine if the path is in fact a secret and then respond accordingly?  I'd be willing to take a stab at making this change if it is in fact a good idea.

**Comment by jefferai** [comment]
This is because most delete operations result in a `204` code, so from the client perspective it is successful. Specifically to the generic backend, it's this way because most of the physical backends don't consider it an error to delete a value that isn't there; the "success" means that there is no value there, and that's what Vault sees.

**Comment by frodopwns** [comment]
IT looks like you can also have both a path and a secret in th esame place

```
test
test/
```

**Comment by jefferai** [comment]
That is correct.

**Comment by frodopwns** [comment]
fair enough, thanks
