### ISSUE TITLE
Enhancement: Version Vault storage database to support detection of rollbacks

### ISSUE THREAD

**Issue by justenwalker** [hashicorp/vault#1396]
Vault should support a progressive database version to detect if the vault storage was rolled back. It can use the Audit log to write this version. An external log aggregation/alerting service can use the audit logs to see if the version of the database ever rolls back - which would indicate restoring an older version of the database.

See [Mailing List Discussion](https://groups.google.com/forum/#!topic/vault-tool/bk3M1_oy_ew)

> Consider the following scenario:
> 
> I'm using the File backend (Although it really could be any storage backend). 
> - I take a backup of the data directory.
> - Some time in the future, I stop Vault, restore this backup and start it up again.
> - OR perhaps there was an online restore of old data where the storage engine rolled back.
> 
> Either way, I'm not sure what mechanisms vault has for detecting or preventing this from happening.  Is there a concept of a "database version" in the audit backend?
> 
> A progressive database version number of some kind would be helpful. Lets say every time a vault starts up it spits out a the version of the database. I'm capturing these audit logs in a log aggregation tool. In my external logging/alerting system, I can record these events into a DB, then if I ever see an event with a version number that is less than ones I’ve already seen - I know there was a rollback.

**Comment by justenwalker** [comment]
I'm no cryptographer, but just to elaborate on some of the threat models I'm trying to mitigate:

## Case I. Attacker repudiates master key rotation

- An attacker has access to the storage backend for Vault but does not know the unseal key(s).
- The attacker backs up the vault (still encrypted).
- At some time later, the key is rotated.
- The attacker, eventually figures out the old unseal key(s). We aren't using it anymore, so it is currently useless.
- The attacker is able to use their access to restore their old backup, and use the old unseal keys to re-initialize the old vault backup.

**Result**: The master key rotation is repudiated.

## Case II. Attacker repudiates arbitrary secret key rotation

- An attacker has access to the storage backend for Vault but does not know the unseal key(s).
- The attacker backs up the vault (still encrypted).
- At some time later, a secret is changed
- The attacker is able to use their access to restore their old backup without a restart.

**Result**: Secret key change is repudiated.


## Possible Mitigation

Although a progressive database version might work for Case II, it may not work for Case I where the attacker is able to get the old secret key.  Perhaps the audit logs must always have both pieces of information: A database version AND the current master key hash. That way we can check if the database rolled back (Case II) and also if the master key was repudiated (Case I) by comparing it to our historical database of key hashes.

**Comment by jefferai** [comment]
I've been thinking about this more and I don't think Case I at least is something Vault can/should handle.

It's really not in Vault's security model to ensure that someone with a) valid unseal keys and b) a valid copy of all Vault data is unable to unseal an old Vault. In fact, it can't, because this is completely normal/valid behavior. In this scenario, the attacker is surely going to ignore or bypass audit logs, so having any kind of version information in audit logs is not going to make a difference, especially given that with a copy of the data and the master key, the attacker doesn't even need Vault; they could simply write something to decrypt the entire data store.

On to Case II: it's not clear what you mean by "arbitrary secret key". Do you mean the encryption keys Vault uses (that are decrypted by the master key)? Do you mean an arbitrary secret within Vault?

In the first case, any information about versioning would only apply to the key versions. If an attacker is able to replace key versions, you'll start seeing errors where items encrypted with a later key version will be unable to be decrypted, which is certainly an issue. However, in the scenario you describe (where there is no restart of Vault) without writing the key version into every single audit log entry, which I don't think we want to do, this is not something that is really detectable -- and even then there is a cache of the keys (since looking up the key from storage for every operation would be very slow) so any such change wouldn't take effect until after a restart anyways. It's not a great situation, but this starts to feel like the best answer is simply to protect your storage.

In the second case, where an arbitrary value is overwritten, right now Vault does not version entries. It's possible that at some point it will gain versioning support, but even then, it would mean versioning *all* entries (as opposed to merely versioning the `generic` backend, for instance). Writing an audit log entry for every version of every storage object that is touched in storage as a request/response move through Vault would be prohibitive -- not to mention the fact that all such entries would have to be examined location-by-location constantly as they come up in the logs.

So I think Case I is not a Vault problem and Case II is something that Vault can't really mitigate without adding very onerous/slow burdens on top. The only thing I can think of that might be a good idea would be to output the keyring version in the Vault log on startup, but that's not much of a balm as that only solves looking at one specific entry.

I'm going to close this for now as I don't really see a way forward. Thanks for bringing up the concerns, but I think these mostly need to be mitigated operationally.

**Comment by justenwalker** [comment]
@jefferai One way this can be somewhat mitigated operationally is to provide a CAS operation that I can perform by some sentinel process to detect roll-backs during a write.

In pseudo-code it would do something like this may work:

```go
var previousKey SecretValue
for {
	key := vault.readSecret("secret/sentinel/version")
	if key.Less(previousKey) {
		panic("Key Roll-back detected")
	}
	if !vault.casSecret("secret/sentinel/version", key, key.Increment()) {
		panic("Atomic write failed: possible roll-back detected")
	}
	previousKey = key
}
```

**Comment by jefferai** [comment]
As per the mailing list discussion, this won't actually mitigate anything, and Vault is unlikely to provide CAS in any near future.
