### ISSUE TITLE
Github Auth: Set TTL on Token

### ISSUE THREAD

**Issue by nemothekid** [hashicorp/vault#1400]
Currently there doesn't seem to be a way to set a TTL on a token when its created using a GitHub Personal token (which makes the `ttl` and `max_ttl` options in the config redundant). Is this intended?

**Comment by jefferai** [comment]
I'm afraid I don't really understand what you mean about the ttl/max_ttl being redundant. Those control the default and max ttl of the issued token respectively.

**Comment by nemothekid** [comment]
Right, I get what they do, however there is no way to actually override the default once its set (hence your default is essentially your max).

**Comment by jefferai** [comment]
What do you mean by your default being your max? The max is the max :-)

These options are meant to be set administratively. Some auth backends support different roles with different sets of configured ttl/max ttl, but GitHub doesn't currently. You can mount the auth backend in multiple places though.

**Comment by nemothekid** [comment]
Ah, I guess my naiveté with how Vault works could be why I'm not explaining this right.

What I'd like to do is something like (in order to make a scoped token)

```bash
$ curl $VAULT_ADDR/v1/auth/github/login \
    -d '{ "token": "your_github_personal_access_token", "ttl":3600 }'
```

But that has no affect. I also looked into seeing if I could set a `ttl` at the team level (ex. `vault write auth/github/map/teams/owners value=root`) but I couldn't find any options to do so. Hence my question, why does the GitHub Auth backend offer both a default `ttl` and `max_ttl` if there is no what to override the default? If there is no way to override the default, the `max_ttl` seems kind of useless.

In anycase, my original ask is it possible for me to set my own `ttl` when I create a vault token while authorizing with GitHub?

**Comment by jefferai** [comment]
Hi @nemothekid ,

Let me go over some TTL concepts and it will hopefully be more clear.

Each token (and this applies to leased secrets as well) has a current TTL before it expires. This is the amount of time remaining before the token must be renewed. Renewing a token is a check against tokens being lost/ignored, to help prevent a found token from still being active.

There is also a limit on the maximum amount of time a token can live, which is the max TTL. So often you'll see configurations like a `ttl` of `24h` and a `max_ttl` of `720h`. This means that a token only remains valid for 24 hours at a time before requiring to be renewed, but after 30 days a new token must be obtained by reauthenticating.

These values cannot be set at login time because they are security-sensitive values; they are meant to be set by an administrator/operator according to organizational policy.

Unlike some other authentication backends, the GitHub auth backend doesn't support a notion of roles, so you cannot map different teams to different TTLs; however, you can mount multiple copies of the backend in different paths (e.g. `auth/github-team1` and `auth/github-team2`) to have different configurations.

**Comment by nemothekid** [comment]
>There is also a limit on the maximum amount of time a token can live, which is the max TTL. So often you'll see configurations like a ttl of 24h and a max_ttl of 720h. This means that a token only remains valid for 24 hours at a time before requiring to be renewed, but after 30 days a new token must be obtained by reauthenticating.

That makes far more sense. I thought tokens could be renewed potentially indefinitely (if you had set `max_ttl` to be infinitely long). My thoughts were *someone* could set a ttl on their own token before they had to renew, only as long as that ttl was less than the `max_ttl`.
