### ISSUE TITLE
Vault UI: Configure 'Mount path' values for auth methods

### ISSUE THREAD

**Issue by me0x847206** [hashicorp/vault#14034]
**Is your feature request related to a problem? Please describe.**
It is a bit 'hard' to do auth actions from UI page when an auth method is mounted to one or more non default paths.

**Describe the solution you'd like**
For the LDAP auth method for example,
if there are 2 different mount paths,
then I would like to have the 'Mount path' input field (located into the 'More options' space) as a select HTML field,
so I would be able to check under which exactly LDAP path I want to do auth operation.

**Explain any additional use-cases**
Similar to LDAP case,
all other auth methods may be considered,
like 'Username', 'Github' and so on

**Additional context**

![Screenshot from 2022-02-13 03-39-12](https://user-images.githubusercontent.com/85886119/153734829-4406401d-fddc-4601-ae34-ff0ede20af42.png)

**Comment by hashishaw** [comment]
Hi @me0x847206! 

In order to populate a select dropdown for the mount path, the UI would need to know (unauthenticated) all the mounts the cluster has available for that auth type. 

There is a auth method config attribute called [listing visibility](https://www.vaultproject.io/docs/commands/auth/enable#listing-visibility) ("List method when unauthenticated" in the UI) which when set to `unauth` will allow the method mount to show up on an unauthenticated call, and allows the UI to present as tabs in the UI for easy access. 

<img width="629" alt="Check List method when unauthenticated when enabling auth mount in the UI" src="https://user-images.githubusercontent.com/82459713/163204721-cab1588c-b0bf-43d5-9ace-02f9c18afc48.png">

<img width="520" alt="Auth mounts with listing_visibility=unauth will show up on the login screen as tabs" src="https://user-images.githubusercontent.com/82459713/163204722-e22e00ce-1396-4df8-a453-94c2a060c2be.png">

I hope that helps your use case. Please feel free to re-open this ticket if you feel it was not addressed.
