### ISSUE TITLE
Kubernetes access method must be updated credentials after Vault's pods restarted

### ISSUE THREAD

**Issue by vietanhduong** [hashicorp/vault#14072]
**Describe the bug**
Kubernetes access method must be updated CA cert and JWT token after Vault's pods restarted.

**To Reproduce**
1. Run `kubectl -n vault delete pod --all`
2. Restart your service pod (using vault) and your service pod cannot auth (permission denied).

**Expected behavior**
No need to update credentials after restart pod

**Environment:**
* Vault Server Version (retrieve with `vault status`): Vault 1.9.0, Helm chart version 0.18.0
* Server Operating System/Architecture: Kuberentes v1.21

Vault server configuration file(s): 

```hcl
 ui = true

listener "tcp" {
  tls_disable = true
  address = "[::]:8200"
  cluster_address = "[::]:8201"
}

storage "gcs" {
  bucket     = "${ vault_bucket }" 
  ha_enabled = "true"
}

seal "gcpckms" {
  project     = "${ project_id }"
  region      = "${ region }"
  key_ring    = "${ vault_kr }"
  crypto_key  =  "${ vault_key }"
}
```

**Additional context**

**Comment by RemcoBuddelmeijer** [comment]
This seems to be an issue with your service account token rather than your CA certificate.
With the new Kubernetes 1.21 the service account token's are expired per pod deletion or after a certain amount of time. I do not know of any such change when it comes to the CA cert.

Please have a look over at the [wiki](https://www.vaultproject.io/docs/auth/kubernetes#kubernetes-1-21) and follow the section that covers your use case

**Comment by vietanhduong** [comment]
@RemcoBuddelmeijer Thank you, that is the answer for me. Maybe I miss the document.

**Comment by matthiashaasesourceforge** [comment]
same problem also this moment with vault pods deployed per helm
/ $ vault version
Vault v1.9.2 (f4c6d873e2767c0d6853b5d9ffc77b0d297bfbdf)
.
any suggest howto work with ?
is there any workaround
