### ISSUE TITLE
Vault: is switching storage backend possible

### ISSUE THREAD

**Issue by Niks-JJ** [hashicorp/vault#1412]
Hi, 
I want to use Vault for encryption without storing data, i.e transit backend.

Right now I am not sure if I will need consul, just need vault running and encrypting decrypting.

Can I switch from file system as storage backed to consul as storage backend in future? Or backend has to be consistent? If yes, how is data from one backend is moved to another type of backend?

Niks

**Comment by BRMatt** [comment]
Vault hides most of the details about storage backends [behind a simple interface](https://github.com/hashicorp/vault/blob/master/physical/physical.go#L13) - the only things it can do are lookup the value associated with a "key", and change the value associated with the "key". In theory (not tried this myself) you should be able to copy all keys/values from one backend into another and it should work fine, though you might need to take Vault down while doing this.

**Comment by Niks-JJ** [comment]
Thanks Matt for quick response. 
By copy, do you mean read all keys using vault from 1 backend and write those keys to other backend using vault?

Niks

**Comment by jefferai** [comment]
Hi @Niks-JJ ,

Can you please post questions on the mailing list (https://groups.google.com/forum/m/#!forum/vault-tool) rather than in GitHub issues? This gets a lot more eyes on any particular question or idea.

It also prevents problematic issue workflows for questions where either the issue is closed immediately but then discussion continues on a closed issue; or, the issue is not closed, discussion dies down, and the issue remains open indefinitely waiting for further potential replies.

Thanks!
