### ISSUE TITLE
Auth, Secret and Audit Plugins

### ISSUE THREAD

**Issue by sherzberg** [hashicorp/vault#142]
I just wanted to start a public conversation about a plugin system for vault. So thoughts on a plugin system? We (think) we want a custom auth backend and are going down the path of keeping a fork of vault with said backend and would obviously rather have a plugin system.

I see there is some documentation with some overview stuff on plugins, but this looks like more of a preview of where vault may go. Also, we already use the terraform style plugin system, so this would be great :)

**Comment by sherzberg** [comment]
At second look, was the provider folder just a copy and find-and-replace of the docs for terraform? Maybe I jumped the gun... But still want plugins!

**Comment by adrianbn** [comment]
I was expecting that all backends were "pluggable" really. Most organisations will want to develop backends for their existing products/infrastructure.

**Comment by armon** [comment]
The current thinking was to making it very simple to maintain plugins in a fork of Vault. Because of the pretty clean separation, there should be very little effort in maintaining a fork (since the plugins should not touch any core code). A multi-process plugin model introduces a lot of new challenges and security considerations that are currently avoided by just having everything compiled in.

**Comment by jefferai** [comment]
I'm going to close this -- just to explain, we do intend to have a plugin system at some point, but we have a number of things we're figuring out first, including how to do this with good security. So this will appear when it does, but it's on our radar.

**Comment by sandstrom** [comment]
Perhaps plugins could be added at build-time (i.e. compiled in). A few popular ones could be bundled, with extras separate (possibly added later, if they become really popular).

**Comment by mytototo** [comment]
Hi there,

I'm looking to build a custom audit device for Vault. I'm aware we can build our own backend engines thanks to plugins but I can't find such a thing for audit devices.

Am I missing something ?

Thanks.

**Comment by mytototo** [comment]
Ok, thank you for your quick answer @jefferai.
Just out of curiosity, is there any plan to support this or not?

**Comment by jefferai** [comment]
We don't currently have plans to build a plugin system for audit, although that's largely because there's been no demand (until your query).

**Comment by mytototo** [comment]
Oh, I see... I just want to keep logs in a time-series database instead of file. Am I understanding audit features correctly ?

Thanks for your support.

**Comment by jefferai** [comment]
Sure. I think generally people have used the `socket` interface to send the logs elsewhere for ingest into a database.

**Comment by mytototo** [comment]
I understand. Thank you for your answers @jefferai I appreciate.

**Comment by lrstanley** [comment]
I was thinking about creating custom audit backends as well, but I see this functionality does not yet exist. The plan was to not necessarily use it for logs perse, but more for alerting and separated statistical analysis on a per-token level for internal needs. For example, one way as a corporation to give people piece of mind when moving to a renewable/expirable token-based system, is to have some sort of way to alert (if requested), when a token is nearing it's expiration time (i.e. the auto renewal process fails).

Example: a metadata field `alert:some-email@domain.com` or `alert:https://some-domain.com/some-webhook-endpoint`.

I guess for now I will use the socket method, since this seems sufficient enough.

**Comment by lrstanley** [comment]
I guess another thing to note with using the socket audit device, is that it's considered a 'successful' write to an audit device. I.e. if for some reason it cannot write to a different audit device (i.e you have file and socket), it will still let requests go through, even if your socket audit device doesn't have the same intent as a normal file audit device, for example.

If used for purposes other than solely logging audit logs, this sounds like it would violate the "one audit device has to be online or requests won't go through" rule.

I don't think there is a way to do the following, but this may be worth an additional feature request:

1. if there are two audit devices enabled, it must still be able to send a log to **X** device (i.e. device A and B, but A is required before requests are fulfilled, even if B is online).
2. OR: the ability to tell a given audit device (via param) that it is considered "non-primary" in a sense. I.e. even if a log is sent to it, don't consider it as one of the audit devices that is required.

I'm sure this is kind of an unpopular need, but I feel that through the audit device system, lots of cool projects could be created. I.e. **Vault Advisor** could ingest directly as an audit device, rather than having to rely on a file. Maybe some kind of monitoring/analysis system hooked directly as an audit device that watch suspicious/malicious traffic and alert on it. Maybe some clustered alerting system as well. Yes, you could throw everything into a central logging system, and iterate over it that way -- the problem with that method is it will then change the integration points drastically depending on what system others are using to store those logs.

With the options above, I think it would make it easier to do both standard logging, for compliance requirements, but hook directly into Vault for other tooling, without having to compromise when a audit device goes offline. With a plugin system, I feel it would be easier for others to better integrate without having to have so much knowledge about the cluster. E.g. if I setup a socket device, read in the logs, I have to do an external API call to vault, which means I need to have a token, hostname, port, and other protocol information -- I feel with a plugin, less of this information is required, and the integration point is easier. Thoughts?

Sorry, lots of text 🏄
