### ISSUE TITLE
A way to forcibly unmount a secret engine

### ISSUE THREAD

**Issue by benvanstaveren** [hashicorp/vault#14351]
A long, long time ago we ran vault with the Consul KV backend. Somewhere along the lines, Consul crapped itself. In the end we ended up with a PKI secrets engine that has no data, no configuration, no nothing except showing up in secrets list. Doing a secrets disable on it either results in a 500 error, or a timeout.

**Describe the solution you'd like**
I'd like to be able to forcibly disable a secret engine, no questions asked, no errors returned, just nuked completely. 

**Explain any additional use-cases**
I've not encountered any other issues that would require the "nuclear" option, but...

**Comment by swayne275** [comment]
thanks for the suggestion! I'll raise it for discussion.

**Comment by swayne275** [comment]
I'm going to close this based on the following (but please re-open if it doesn't resolve your issue):

When a secrets engine is revoked, Vault will [revoke secrets associated with this engine](https://www.vaultproject.io/docs/commands/secrets/disable). You are likely seeing the error during this process.

Since you mentioned a timeout, the best course of action is likely to increase that timeout such that there is enough time for the secrets to be revoked.

Failing this, you can "forcibly unmount" a secrets engine by doing a [force prefix revoke](https://www.vaultproject.io/docs/commands/lease/revoke) for the secrets mount in question (something of the form `vault lease revoke -force -prefix <secrets prefix>`
