### ISSUE TITLE
Getting 'no handler for route' error for app-id and Policy association

### ISSUE THREAD

**Issue by suhaspan** [hashicorp/vault#1436]
Hi,

I am trying to associate app-id with Policy, but getting below error,

```
NYCMAC2YYGB8WP:vault user$ curl -X POST -H "X-Vault-Token:$VAULT-TOKEN" -d '{"value":"my_policy", "display_name":"myName"}' http://localhost:8200/v1/auth/app-id/map/app-id/1290
{"errors":["no handler for route 'auth/app-id/map/app-id/1290//'"]}
```
I also tried below command, but getting same error,

```
NYCMAC2YYGB8WP:vault user$ ./vault write /auth/app-id/map/app-id/1290 value=my_policy display_name=myName
Error writing data to auth/app-id/map/app-id/1290: Error making API request.

URL: PUT http://127.0.0.1:8200/v1/auth/app-id/map/app-id/1290
Code: 404. Errors:

* no handler for route 'auth/app-id/map/app-id/1290//'
```

Any idea why this is happening ? 
Any help is appreciated!

Thanks
Suhas

**Comment by jefferai** [comment]
Hi @suhaspan ,

It is likely that you did not first run 'vault auth-enable app-id' or run the equivalent API call (see https://www.vaultproject.io/docs/http/sys-auth.html).

In the future, can you please post questions on the mailing list (https://groups.google.com/forum/m/#!forum/vault-tool) rather than in GitHub issues? This gets a lot more eyes on any particular question or idea.

It also prevents problematic issue workflows for questions where either the issue is closed immediately but then discussion continues on a closed issue; or, the issue is not closed, discussion dies down, and the issue remains open indefinitely waiting for further potential replies.

Thanks!

**Comment by suhaspan** [comment]
Hi @jefferai ,
Thanks, it worked!

Thanks,
Suhas

**Comment by akashpearsystem** [comment]
URL: PUT http://9.128.134.150:8200/v1/vault/secrets/aws-vault-admin
Code: 404. Errors:

no handler for route 'vault/secrets/aws-vault-admin'


How to handle this error in vault using terraform??
Please help me out to resolve this issue ASAP.

**Comment by zanilgupta** [comment]
@akashpearsystem  are you able to resolve the above issue ?
I am facing the same issue ?
