### ISSUE TITLE
Ember Data Request GET returned a 400 Payload (application/json) [object Object] 1 error occurred: * invalid ciphertext: wrong number of fields

### ISSUE THREAD

**Issue by HenryAndry** [hashicorp/vault#14510]
hi guys have an error during open "kv", how i acn fix it, help pls
Ember Data Request GET /vault/path/ returned a 400 Payload (application/json) [object Object]
1 error occurred: * invalid ciphertext: wrong number of fields
try this solution didnt help infortunatly - https://github.com/hashicorp/vault/issues/6805#issuecomment-498125487; 
vault 1.8.0 version (not enterprise), mysql v8

**Comment by HenryAndry** [comment]
> Hi, thanks!
> 
> Can you give us more details about steps to set up and reproduce?

hi, thanks for answering; 
my step was next, i create engine and then write wrong path (dublicate engine in yourself)

**Comment by kitography** [comment]
Hey, this still isn't enough information for us to replicate this issue.

I'm pretty sure from the error, that unless you've modified the ciphertext manually elsewhere, that you are hitting a backend issue - it's unlikely to have anything to do with Ember.

What happens when you run `mysql> describe vault;` as described in ( https://github.com/hashicorp/vault/issues/6805#issuecomment-498125487 )?

**Comment by raskchanky** [comment]
This hasn't had a response in awhile now, so I'm going to close it due to inactivity. Please feel free to reopen if you feel this was a mistake, or if there is additional information to add. Thanks!
