### ISSUE TITLE
Vault with DynamoDB

### ISSUE THREAD

**Issue by hridyeshpant** [hashicorp/vault#1454]
HI,
We are using vault with dynamodb combination and working fine ,when using one vault server behind the ELB. i come to know that we cant have mutiple vault server in single ELB due to limitation as It doesn't have locks tied to an expiring session. and we need start new server with  recovery_mode=1  flag .

So if that means “it supports HA if you manually restart a down/failed/crashed service with an argument to force stealing the lock back”

we are thinking if we can deployed vault server in multiple regions with the same dynamodb backend (as it is PaaS) and use Route53 to do latency based routing and also use failover capabilities of Route53 to fail between regions. since 99.9% of all our calls are going to be secret read calls without write.
That would also potentially provide a solution to enable reads even in the event that the read/write leader crashes and by that time we launch the leader with recovery_mode=1  flag.

Could you please suggest?

**Comment by vishalnayak** [comment]
Can you please post questions on the mailing list (https://groups.google.com/forum/m/#!forum/vault-tool) rather than in GitHub issues? This gets a lot more eyes on any particular question or idea.

It also prevents problematic issue workflows for questions where either the issue is closed immediately but then discussion continues on a closed issue; or, the issue is not closed, discussion dies down, and the issue remains open indefinitely waiting for further potential replies.

Thanks!
