### ISSUE TITLE
migration data from Dynamodb to Consul

### ISSUE THREAD

**Issue by hridyeshpant** [hashicorp/vault#1455]
we have setup Vault server with dynamodb HA backend,now if we want to use consul ,
Is there any way we can migrate all the Vault data which are stored in Dynamdb to consul ?

**Comment by vishalnayak** [comment]
Hi @hridyeshpant,

Please refer to this earlier response in the mailing group: https://groups.google.com/forum/#!msg/vault-tool/zfabfkuHPIY/x4i53dxhAAAJ

Also, can you please post questions on the mailing list (https://groups.google.com/forum/m/#!forum/vault-tool) rather than in GitHub issues? This gets a lot more eyes on any particular question or idea.

It also prevents problematic issue workflows for questions where either the issue is closed immediately but then discussion continues on a closed issue; or, the issue is not closed, discussion dies down, and the issue remains open indefinitely waiting for further potential replies.

Thanks!
