### ISSUE TITLE
Identity Backend Audit HMAC Request/Response Cannot Be Configured

### ISSUE THREAD

**Issue by ianferguson** [hashicorp/vault#14696]
**Describe the bug**

It does not appear possible to allowlist fields to be printed in cleartext in the audit logs for requests/responses from the Identity backend.

Based on the Identity backend docs and poking around at a local Vault dev server, it appears that the `tune` option used to allow fields to be printed in plaintext rather than HMAC'd values in audit logs in secret/auth backends is not available for the Identity backend.

It would be useful to our operations and use of the Identity backend if we were able to allow specific fields (ex. `policies` or `member_entity_ids`) from the request or response of Identity backend request to be printed in plaintext in our audit logs 

**To Reproduce**
Run `vault server -dev` and configure VAULT_ADDR/VAULT_TOKEN to work with that:
```
> vault secrets tune -audit-non-hmac-request-keys=member_entity_ids -audit-non-hmac-request-keys=member_entity_ids identity
Error tuning secrets engine identity/: Error making API request.

URL: POST http://127.0.0.1:8200/v1/sys/mounts/identity/tune
Code: 400. Errors:

* cannot tune "identity/"

> vault write sys/mounts/identity/tune audit-non-hmac-request-keys=member_entity_ids
Error writing data to sys/mounts/identity/tune: Error making API request.

URL: PUT http://127.0.0.1:8200/v1/sys/mounts/identity/tune
Code: 400. Errors:

* cannot tune "identity/"
```

On the server logs, running the above client commands will result in:
```
2022-03-24T11:25:17.201-0400 [ERROR] secrets.system.system_fafb1c8d: cannot tune this mount: path=identity/
```

**Expected behavior**

The Identity mount can be tuned to allow specific fields to be printed in audit logs in plaintext

**Environment:**
* Vault Server Version (retrieve with `vault status`): v1.9.3
* Vault CLI Version (retrieve with `vault version`): v1.9.3
* Server Operating System/Architecture: OS X, Linux

Vault server configuration file(s): n/a, reproduces on a `vault server -dev` instance

**Additional context**
None

**Comment by HridoyRoy** [comment]
Hi @ianferguson thanks for submitting this issue and corresponding pull request! I submitted the same comment on the pull request, but I'd like to capture those thoughts here as well. The use-case you presented regarding auditing and the identity mount makes sense, but I'm worried about the repercussions of allowing the other tunable parameters to be modified for the identity mount (as it is such an integral part of vault, allowing variability in it would increase the complexity of bugs that may arise as a result of tuning). Can we change the functionality so that only a subset of audit-related parameters can be tuned for this mount?

**Comment by gonda-datadog** [comment]
@hsimon-hashicorp can we get some eyes on the above?
