### ISSUE TITLE
Support generating certificates for OpenVPN Servers and Clients

### ISSUE THREAD

**Issue by grahamc** [hashicorp/vault#1476]
OpenVPN requires certain features to be enabled on the certificates for the VPN clients and servers. As far as I can tell, the current PKI backend doesn't support a rich enough set of key usage options for servers and clients.

From the [OpenVPN HowTo](https://openvpn.net/index.php/open-source/documentation/howto.html): 

[OpenVPN 2.1 and above]Build your server certificates with specific key usage and extended key usage. The RFC3280 determine that the following attributes should be provided for TLS connections:
 
# Client Mode
## Key Usage
 - digitalSignature
 - keyAgreement
 - digitalSignature, keyAgreement

## Extended Key Usage
 - TLS Web Client Authentication

# Server Mode
## Key Usage
 - digitalSignature, keyEncipherment
 - digitalSignature, keyAgreement

## Extended Key Usage
 - TLS Web Server Authentication

**Comment by jefferai** [comment]
@grahamc The PKI backend *used* to support these sets of options but they were causing problems with various crypto stacks (see e.g. #987), many of which explicitly deviate from the spec. At this point, taking a cue from Google and other very large web sites, only extended usages are added to certs except for CA certs. This seems to be broadly compatible, and being broadly compatible is a nice thing.

We could maybe add a mode to generate OpenVPN-compatible certificates, but they do specify five different ways that this behavior can be worked around. Ideally, they'd stop requiring specific key usage restrictions and instead allow simply the extended key usage since that's what's broadly done.

**Comment by jefferai** [comment]
@grahamc Any chance you can try that out and let me know how it goes for you?

**Comment by jefferai** [comment]
I think this should be supported now; in new roles it will be supported by default, or existing roles can be rewritten. Please let me know if you get a chance to try it!

**Comment by dnascimento** [comment]
@grahamc What about using a PAM module for 2FA with Openvpn? I'm considering Vault to manage our VPN infrastructure too.
