### ISSUE TITLE
mysql backend - how do i revoke a lease / user

### ISSUE THREAD

**Issue by jippi** [hashicorp/vault#1485]
Hi,

Can't find any API way of revoking a specific mysql secret lease by its username

Is this intended or me missing something obvious?

I've tried `vault revoke` with all kind of weird combinations, but the mysql user seem to stick in the `mysql.User` table

**Comment by jefferai** [comment]
Hi @jippi,

Please post questions on the mailing list (https://groups.google.com/forum/m/#!forum/vault-tool) rather than in GitHub issues. This gets a lot more eyes on any particular question or idea.

It also prevents problematic issue workflows for questions where either the issue is closed immediately but then discussion continues on a closed issue; or, the issue is not closed, discussion dies down, and the issue remains open indefinitely waiting for further potential replies.

Thanks!
