### ISSUE TITLE
A way to avoid writing auth token to ~/.vault-token

### ISSUE THREAD

**Issue by stvdilln** [hashicorp/vault#1492]
Problem:

Scenario1- I would like to use vault in our Jenkins build jobs.  Using App-ID auth, different build jobs may use different vault credentials.  As the jobs run as the same OS user we have overwrite issues for ~/.vault-token. When a job terminates it has left it's token exposed without an explicit token-revoke.  I'd rather just have a per-process VAULT_TOKEN environment set.

Scenario2- Logged into my machine as Vault root/admin with a token.  I want to test a permission with a different user.  I open another shell prompt and 'vault auth'.  My admin token is now lost.   

Both of these have work arounds of running a shell wrapper to "vault auth", read the ./vault-token, set VAULT_TOKEN, and delete ~/.vault-token.  

I saw TokenHelper and ExternalTokenHelper and that looked promising but I don't see a way to use a config file with the client.

**Comment by jefferai** [comment]
Hi @stvdilln ,

Please post questions on the mailing list (https://groups.google.com/forum/m/#!forum/vault-tool) rather than in GitHub issues. This gets a lot more eyes on any particular question or idea.

It also prevents problematic issue workflows for questions where either the issue is closed immediately but then discussion continues on a closed issue; or, the issue is not closed, discussion dies down, and the issue remains open indefinitely waiting for further potential replies.

Thanks!

**Comment by tmaher** [comment]
@stvdilln - I went down the path of using ExternalTokenHelper and ran into an bug. Patch is in https://github.com/hashicorp/vault/pull/1550 . As to the config, for the token helper Vault uses separate config files for running as server (e.g. where you set `backend`) and for CLI commands.  `$HOME/.vault` is used for the CLI stuff, which at the moment appears to **only** be the token handler.  Once the bug is fixed, syntax looks like...
```
tmaher@shulgin:~$ cat .vault
token_helper = "/Users/tmaher/bin/trivial-token-helper"
```
The double-quotes are mandatory. Here's my example trivial helper, which isn't any more secure than using `~/.vault-token`. Ultimately I'm planning on using this to wrap [calls to the git credential helpers](https://help.github.com/articles/caching-your-github-password-in-git/), which use OS-provided encrypted local storage.
```
#!/bin/sh

TOKEN_FILE="${HOME}/.helper-token"

if [ "x$1" = "xget" ]; then
  cat "${TOKEN_FILE}"
elif [ "x$1" = "xstore" ]; then
  cat > "${TOKEN_FILE}"
elif [ "x$1" = "erase" ]; then
  cat /dev/null > "${TOKEN_FILE}"
else
  exit 1
fi
exit 0
```

**Comment by stvdilln** [comment]
Thanks for the Help with how to use this, I couldn't find much info on how to use the token helper.  Would be nice to get a way to get the vault binary to just put this to the screen.

We are going to mostly be using AppID authentication for our automation work, and the vault login there is done with a "vault read" and the token comes back to the screen.  We just specify json formatted output and this works great for scripting.

**Comment by tomdottom** [comment]
An full Ruby example of a token helper can now be found at https://www.vaultproject.io/docs/commands/token-helper.html

The example above only needs a small modification to be able to determine the token location with a  `VAULT_TOKEN_PATH` env var:

```
#!/bin/sh

DEFAULT_TOKEN_PATH="${HOME}/.vault-token"
TOKEN_PATH=${VAULT_TOKEN_PATH:-$DEFAULT_TOKEN_PATH}

if [ "x$1" = "xget" ]; then
  cat "${TOKEN_PATH}"
elif [ "x$1" = "xstore" ]; then
  cat > "${TOKEN_PATH}"
elif [ "x$1" = "erase" ]; then
  cat /dev/null > "${TOKEN_PATH}"
else
  exit 1
fi
exit 0
```
