### ISSUE TITLE
 [ERR] Error connecting to statsite! Err: dial tcp 127.0.0.1: 8125: connectex: No connection could be made because the target machine actively  refused it.

### ISSUE THREAD

**Issue by waliul-cse** [hashicorp/vault#1496]
I have written a configuration file(example.hcl) and after executing the file in vault I got an error and can't initialize vault.

backend "file" {
  path = "C:\\Vault Server\\Keymanager"
}

listener "tcp" {
 address = "127.0.0.1:8200"
 tls_disable = 1
}
telemetry {
  statsite_address = "127.0.0.1:8125"
  disable_hostname = true
}
showing error  **No connection could be made because the target machine actively  refused it.** 
can anyone help that issue.Thanks in advance.

**Comment by jefferai** [comment]
@waliul-cse Unfortunately this is nothing we can help with -- the error message says that statsite is not properly accepting connections. You should verify connectivity to statsite; once it's working, Vault should work.

**Comment by waliul-cse** [comment]
Hello @jefferai 
Can you give me the proper process to set up vault in production mode? I 'm trying to configure vault server from few days.please help me out.My steps is given below.

I have tried to configure vault server in production mode.I have read vault server documentation from here. https://www.vaultproject.io/docs/index.html

According to documentation At first install vault server and  then write a configure file(example.hcl) and then execute the command in vault server but got some errors please help me out.

My configuration file:

backend "file" {
  path = "C:\\Vault Server\\Keymanager"
}

listener "tcp" {
 address = "127.0.0.1:8200"
 tls_disable = 1
}
telemetry {
  statsite_address = "127.0.0.1:8125"
  disable_hostname = true
}

When I run this file through command:
 vault server -config=example.hcl
Then got a warning that mlock not supported on that system but showing logging info.
 and when I try to initialize the vault then can't do that event if I can't show the vault status.

LogInfo:
2016/06/08 05:12:04 [ERR] Error connecting to statsite! Err: dial tcp 127.0.0.1:
8125: connectex: No connection could be made because the target machine actively refused it.

Please give me some suggestion what I have to do now ? Thanks in advance

**Comment by vishalnayak** [comment]
@waliul-cse 

To verify if Vault is working fine, you could try removing the telemetry block from the configuration file and running Vault. If that works, you can deal with the connectivity issue later on.

Also, please post questions on the mailing list (https://groups.google.com/forum/m/#!forum/vault-tool) rather than in GitHub issues. This gets a lot more eyes on any particular question or idea.

It also prevents problematic issue workflows for questions where either the issue is closed immediately but then discussion continues on a closed issue; or, the issue is not closed, discussion dies down, and the issue remains open indefinitely waiting for further potential replies.

Thanks!

**Comment by waliul-cse** [comment]
Thanks @vishalnayak  for your information.
