### ISSUE TITLE
 interface conversion: interface {} is json.Number, not string in sdk/framework/field_data.go

### ISSUE THREAD

**Issue by Nikita1821** [hashicorp/vault#15057]
I use framework.TypeCommaIntSlice for get emloyeeID and add it in group AD in my engine.

Send: curl -X POST -H "X-Vault-Request:..." -H "X-Vault-Token: $(vault print token)" -d '{"param":  213}' http://127.0.0.1:8200/v1/<engine path>

In vault system log: interface conversion: interface {} is json.Number, not string

You use StringToSliceHookFunc() in DecodeHook();

if reflect1.Kind != reflect.String || reflect2.Kind != reflect.Slice {return data, nil} 
you do it : raw := data.(string)
reflect.ValueOf(json.Number), reflect.Kind() => string, reflect.Type() => json.Number

sdk/framework/field_data.go, maybe remove function  mapstructure.StringToSliceHookFunc(",") from DecodeHook

commit: Brian Kassouf, 4 years ago   (March 3rd, 2018 2:01 AM) logical/framework: add a field data type for parsing integer arrays, [83a7d20]

**Comment by VinnyHC** [comment]
Hello, @Nikita1821 thanks for opening this issue. Could you please let us know what version of Vault (found using `vault status`) you're experiencing this with?

**Comment by Nikita1821** [comment]
hi, the last version

**Comment by Nikita1821** [comment]
ok, v1.10.0

**Comment by Nikita1821** [comment]
you can add to any engine parameter with type framework.TypeCommaIntSlice
send just int and get this error

**Comment by ccapurso** [comment]
As @Nikita1821 noted, this occurs due to the type `string` assertion performed in `mapstructure.StringToSliceHookFunc` when the input is of type `json.Number`. A similar issue used to occur with `framework.TypeCommaStringSlice`. The parsing for that type is handled by `ParseCommaStringSlice` in `github.com/hashicorp/go-secure-stdlib/parseutil`. The issue was fixed in https://github.com/hashicorp/vault/pull/14522. If the type of the input is `json.Number` then we simply call `String()`. We can likely add the same conversion for `framework.TypeCommaIntSlice`.
