### ISSUE TITLE
Unable to revoke postgres role with sequence privileges

### ISSUE THREAD

**Issue by mickhansen** [hashicorp/vault#1535]
If you have a postgres role with something like:

```
CREATE ROLE "{{name}}" WITH LOGIN PASSWORD '{{password}}' VALID UNTIL '{{expiration}}';
GRANT SELECT, INSERT, UPDATE, DELETE ON ALL TABLES IN SCHEMA public TO "{{name}}";
GRANT USAGE ON ALL SEQUENCES IN SCHEMA public TO "{{name}}"
```

Which allows the role to actually use a sequence in the insert (which the default mentioned in vault/postgresql docs apparently does not) on 9.4.

However vault is no longer able to revoke the role which causes some issues.

Vault uses `REVOKE USAGE ON SCHEMA public FROM %s` which would ideally be enough but it appears postgres also requires a `REVOKE ALL ON ALL SEQUENCES IN SCHEMA public FROM %s` to properly drop the role.

Edit: `REVOKE ALL` rather than `REVOKE USAGE` since `REVOKE USAGE` does not remove cases where `GRANT SELECT ON ALL SEQUENCES` has been used.

**Comment by jefferai** [comment]
@mickhansen I think we can put this in for the next release if we can verify that there won't be any detrimental effects (like an error coming back) for when sequences aren't used. Then if you can wait on those leases until 0.6.1 (or until you build from master) then that would work.

Eventually (as part of a series of much larger changes we're working on with respect to the SQL backends) revocation SQL will be supported so that the user can specify exactly what they want, similar to the creation SQL.

**Comment by mickhansen** [comment]
@jefferai I only did a few tests but their didnt appear to be any issue with revoking on existing sequence permissons (as long as it's that high a revokation level).

That was my thought aswell, having users potentially supply the revokation SQL would save vault from having to know every possible combination out there.

For now i manually removed all roles with a script, only found this because our postgres backend stopped working and i couldn't unmount because of revokations not happening.

**Comment by jefferai** [comment]
Glad you're sorted for now. You probably were not aware of https://www.vaultproject.io/docs/http/sys-revoke-force.html -- this is for exactly this kind of thing, where you can't unmount because of failed revocations. Hopefully next time that will make things easier!

**Comment by mickhansen** [comment]
@jefferai On a related note, the postgres backend generally stops issuing new postgres creds when it gets too many roles it can revoke.

Not sure if this is intended or not (i'm guessing not since it times out and doesn't provide an acutal error)

**Comment by mickhansen** [comment]
https://github.com/hashicorp/vault/pull/1573

**Comment by jefferai** [comment]
Hi @mickhansen ,

The creds issue may be something that we identified with another user and just fixed -- I literally merged the fix for that into `master` right before replying here. If you're up for giving that a try it'd be great.

**Comment by mickhansen** [comment]
@jefferai Looks like you've changed so failed revocations will no longer keep a connection alive?
That will likely help, odd thing was that the backend would still lock up after a restart of vault, i had to drop all roles in the db, force revoke, unmount and remount to get it to work again.

But i think your PR + my recent PR will likely help a lot in keeping PG secrets running in production :)

**Comment by jefferai** [comment]
No -- what changed is that instead of grabbing a single database connection (when the transaction began), each concurrent goroutine was grabbing two, since it wasn't using the transaction object.

As the default number of connections is two, this meant that any two concurrent requests that began a transaction and then attempted the next statement would exhaust the number of concurrent connections to the database, leading to deadlock. There were also a number of places where statement objects being created were never actually closed.

A workaround to see if this was the root of your problem would have been to increase the number of concurrent connections and see if that made a difference, but hopefully the changes fix that issue for good.

**Comment by mickhansen** [comment]
@jefferai I see transaction usage related changes for mysql in https://github.com/hashicorp/vault/pull/1572/files - but not for postgres (for postgres i see some logging and a `Close`.

I'm obviously not too familiar with the codebase though.

**Comment by jefferai** [comment]
See https://github.com/hashicorp/vault/pull/1572/files#diff-924f3094d95d55ed6071e32ff06bfb0cL95

**Comment by mickhansen** [comment]
Ah, sorry @jefferai - Not sure how i missed that.

**Comment by jefferai** [comment]
I'm going to close this in favor of your PR...as you noted between that and the changes that already went in this issue is probably set!
