### ISSUE TITLE
Authentication via HTTP API

### ISSUE THREAD

**Issue by MadsRC** [hashicorp/vault#155]
The docs mention "Otherwise, a client token can be retrieved via authentication backends.

Each authentication backend will have one or more unauthenticated login endpoints. These endpoints can be reached without any authentication, and are used for authentication itself."

I can't seem to do that via the API. The docs also state "For example, the GitHub login endpoint is located at auth/github/login" but I keep getting an error:

Is authentication via HTTP API not supported yet? The docs aren't quiet clear. Ideally I'd like to generate a token using a username and password and have that token send back to me in a cookie (Actually, exactly what the docs mention).

**Comment by sethvargo** [comment]
Hi @MadsRC 

The GitHub auth backend requires you first configure and setup the backend. In order to do this, you will need to use a root token or a token obtained from another source. Once you [configure the GitHub backend](https://www.vaultproject.io/docs/auth/github.html), you also need to configure it. This is a bit unclear in the docs, so I have pushed up #160 to explain the steps in more detail with copy-pastable commands.

Does that help? I was able to get GitHub authentication working successfully following those steps.

**Comment by MadsRC** [comment]
Hi @sethvargo 

What I'm trying to do is authenticate a user using `userpass` over HTTPS. It's working fine using the terminal/vault. The docs just state that "Each authentication backend will have one or more unauthenticated login endpoints." but does not mention what said endpoint is or how the login details should be presented to the HTTP API.

**Comment by MadsRC** [comment]
I figured out how to do it by remembering that the vault client uses the interface. Tailing the log while authenticating using the app allowed me to find the correct path and how the data should be represented.

**Comment by sethvargo** [comment]
Fixed in #155
