### ISSUE TITLE
Standardize namespace across different vault commands (where possible)

### ISSUE THREAD

**Issue by I-B-CC** [hashicorp/vault#15501]
It was frustrating to discover that when running the command: `vault login ....` the namespace for the token is "token" however when running the command `vault token lookup` the namespace for the token is "id". I think this is a minor nit, and perhaps I'm just not aware of why this would be desirable, however from my point of view it seems like the namespace for a 'token' should be universal, either "token" or "id" (or something else), but _there can be only one_.

**Comment by VinnyHC** [comment]
It might help to see that the responses are coming from two different subsystems within Vault, therefore the perspective is different.
When issuing the command `vault login` you are being presented with authentication details related to your login; if you inspect the response with the flag `-format=json` you’ll notice the details are part of an `auth` response. Using a field name like `id` here would be confusing as it’s not very specific (i.e. id of what?).
When looking up a token using `vault token lookup` you are requesting a particular record from the system; again if you toggle `-format=json`, you’ll notice that the response is in the `data` field; so in this case, `id` can reasonably be assumed as the unique identifier of the record, in this case, a token.
It's also worth noting that in order to maintain backward compatibility changing these fields would require a fair bit of effort without much gain.
I'm going to close this issue but if you feel that I did not address your concerns please don't hesitate to reopen!
