### ISSUE TITLE
How best to watch for changes?

### ISSUE THREAD

**Issue by cressie176** [hashicorp/vault#1558]
I'm writing a Vault loader for [Confabulous](https://github.com/guidesmiths/confabulous), and would like to notify clients when data stored in vault changes.

1. Is there anything etcd like on the roadmap for this
2. What do you think about setting etag headers on the HTTP read responses and supporting HEAD requests?

**Comment by jefferai** [comment]
> Is there anything etcd like on the roadmap for this

Not currently, but if you have access to your underlying storage system, at least Consul and etcd both support notification.

> What do you think about setting etag headers on the HTTP read responses and supporting HEAD requests?

This is a poll model, not a notification model. Additionally, because Vault would need to perform normal processing of the request (authn/authz check, lookup of data), there is not much efficiency to gain.

You didn't say, but I assume that you are using the `generic` backend. Our generally recommended approach is to take advantage of the ability to set the returned refresh interval to have writers clue readers into how often they should check for new data.

**Comment by cressie176** [comment]
Thanks for the response. The idea behind setting headers on the vault response was so that confabulous could poll vault on an interval and emit a "changed" event when the etag (or potentially last modified) header changed. By listening to the "changed" events the application can re-initialise itself automatically if the configuration if updated. Since this might involve dropping and reconnecting to databases etc, I'm interested in detecting when the data in vault has actually changed, rather than purely relying on a refresh interval.

There are other ways to solve the problem though. Just thought I'd ask.

**Comment by anhldbk** [comment]
@cressie176 Another solution may be using [Consul Events](https://www.consul.io/docs/commands/event.html). But be careful of [event duplications](https://github.com/hashicorp/consul/issues/3742).
