### ISSUE TITLE
boolean string options in configuration file should have consistent documentation 

### ISSUE THREAD

**Issue by siddharthist** [hashicorp/vault#1559]
I'm using Vault 0.6, and attempting to disable the Consul service auto-registration. 

With this configuration:

```
[centos@lb0-control-02 ~]$ sudo cat /etc/vault/vault.hcl         
backend "consul" {
    address = "127.0.0.1:8500"
    path = "vault"
    scheme = "http"
    token = "[redacted]"
    advertise_addr = "https://lb0-control-02.node.consul:8200"
    disable_registration = true
}

listener "tcp" {
    address = "0.0.0.0:8200"
    tls_cert_file = "/etc/pki/tls/certs/host.cert"
    tls_key_file = "/etc/pki/tls/private/host.key"
}
```

I get the following error:

```
Jun 24 13:13:34 lb0-control-02 vault[4604]: Error loading configuration from /etc/vault: Error loading /etc/vault/vault.hcl: error parsing 'backend': backend.consul: At 7:25: root.disable_registration: unknown type for string *ast.LiteralType
```

However, after changing `disable_registration` to a string, I don't:

```
[centos@lb0-control-02 ~]$ sudo cat /etc/vault/vault.hcl         
backend "consul" {
    address = "127.0.0.1:8500"
    path = "vault"
    scheme = "http"
    token = "[redacted]"
    advertise_addr = "https://lb0-control-02.node.consul:8200"
    disable_registration = "true"
}

listener "tcp" {
    address = "0.0.0.0:8200"
    tls_cert_file = "/etc/pki/tls/certs/host.cert"
    tls_key_file = "/etc/pki/tls/private/host.key"
}
```

This distinction is also upheld in the documentation, where defaults for boolean variables (see `tls_skip_verify`) are unquoted, whereas the default for disable_registration is a quoted string. 

Am I crazy, or should this variable be a boolean? 

Thank you for your great work!

**Comment by jefferai** [comment]
It's an unfortunate artifact of the way things are parsed, mostly to allow variations of true/false (for instance, see the text of https://www.vaultproject.io/docs/config/index.html#tls_disable). This is especially important because of how environment variables are handled, which are strings. The default for that option is listed as `"false"`, with quotes, for a reason :-/

Some of the boolean values have more documentation than others about acceptable values; I'll take this as a documentation TODO to make that more consistent.

**Comment by siddharthist** [comment]
@jefferai Thanks for clarifying!

**Comment by jefferai** [comment]
Our documentation continually undergoes refactoring and is hopefully much more consistent in this regard now.
