### ISSUE TITLE
Support for listing ldap group members

### ISSUE THREAD

**Issue by sigmunau** [hashicorp/vault#1563]
Currently the only way to find out which (additional) users are part of a group when using the ldap backend is to list all users and iterate over each user and list that users memberships. Having a separate path to get this information would be a nice convenience. This could also be useful in designing policies even for setting. Eg. user1 should be allowed to view/modify members of group A. 

I suggest `auth/ldap/groups/<name>/members

**Comment by jefferai** [comment]
Unfortunately the design of the LDAP backend means we don't have an efficient way to do this -- internally it'd be the same thing as you describe. We can plan to add this functionality at some point but in the mean time doing a query on group membership via Identity (https://www.vaultproject.io/api/secret/identity/lookup.html#lookup-a-group) may help.

**Comment by mitchellmaler** [comment]
@jefferai This is something we just ran into today as well. We are leveraging creating multiple ldap groups and adding ldap users to them but it's difficult to list what users are related to each group.
Guess we will have to loop through each ldap user and compile a list for now.

**Comment by vishalnayak** [comment]
Issues that are not reproducible and/or not had any interaction for a long time are stale issues. In order to provide faster responses and better engagement with the community, we strive to keep the issue tracker clean and the issue count low. In this regard, our current policy is to close stale issues after 30 days. Closed issues will still be indexed and available for future viewers. If users feel that the issue is still relevant, we encourage reopening them.
   
Please refer to our [contributing guidelines](https://github.com/hashicorp/vault/blob/main/CONTRIBUTING.md) for details on issue lifecycle.
