### ISSUE TITLE
APT repository missing latest versions

### ISSUE THREAD

**Issue by rbayerl** [hashicorp/vault#15641]
The APT repository seems to be missing `1.10.1`, `1.10.2`, and `1.10.3` for both `arm64` and `amd64`.

**Comment by kpenfound** [comment]
Hi @rbayerl ,

Are you specifying the version using a method like `apt install vault=1.10.3`?

Starting with the `1.10.1` release, we've begun setting the `debian_revision` to 1 rather than unset/0, which means you'd want to install with `apt install vault=1.10.3-1` or `apt install vault=1.10.1-*`.

Using the `*` means that if we make an update to the package between vault version releases, you'll get the latest package for that vault version.

**Comment by rbayerl** [comment]
🤦 that works. Thanks!
