### ISSUE TITLE
How To?

### ISSUE THREAD

**Issue by gvenka008c** [hashicorp/vault#1614]
Hi,

Where can i find documentation for setting up Vault in Production? 

Also how can clients access Vault server? 

```
$ export VAULT_TOKEN=<token>
$ export VAULT_ADDR='http://xx.xxx.xx.xx:8200'
$ curl http://xx.xxx.xx.xx:8200/v1/sys/init
curl: (7) Failed to connect to xx.xxx.xx.xx port 8200: Connection refused
```

When I run the below command on where the vault is running, i was able to initialize it.

```
# curl http://127.0.0.1:8200/v1/sys/init
{"initialized":true}
```

Thanks,
Govind

**Comment by jefferai** [comment]
Hi Govind,

Please post questions on the mailing list (https://groups.google.com/forum/m/#!forum/vault-tool) rather than in GitHub issues. This gets a lot more eyes on any particular question or idea.

It also prevents problematic issue workflows for questions where either the issue is closed immediately but then discussion continues on a closed issue; or, the issue is not closed, discussion dies down, and the issue remains open indefinitely waiting for further potential replies.

Thanks!
