### ISSUE TITLE
setPolicyInternal function and define policy type

### ISSUE THREAD

**Issue by valli0x** [hashicorp/vault#16258]
![Screenshot from 2022-07-08 17-17-49](https://user-images.githubusercontent.com/65861300/178010946-e6a868c5-6031-4d85-8632-c5407217c86d.png)
Why do you use getRGPView() function for policy Type == PolicyTypeACL and getACLView for policy Type == PolicyTypeRGP ?
file vault/policy_store.go  setPolicyInternal function

**Comment by Imomoi** [comment]
OK. It looks like this code here https://github.com/hashicorp/vault/blob/v1.11.0/vault/policy_store.go#L387 has copy-paste error.

Looks like this case is working with ACL policy, but it is using RGP policy view.

But in the next case we are processing RGP policy, but are using ACL policy view.

May be it is bad constant naming.

**Comment by calvn** [comment]
I believe that this is intentional. As @ncabatoff  pointed out, we are getting the RGP policy view on the ACL case to ensure that there's no existing policy with the same name under that view. The check for the ACL case against a possible collision on the RGP view occurs here:

https://github.com/hashicorp/vault/blob/ea296ccf58507b25051bc0597379c467046eb2f1/vault/policy_store.go#L393-L395

After this validation step, we actually store the policy in the proper `view`. For ACL policies, it happens here:

https://github.com/hashicorp/vault/blob/ea296ccf58507b25051bc0597379c467046eb2f1/vault/policy_store.go#L397-L399

Note that we're using `view` here, which is the right one that's fetched based on the policy type:

https://github.com/hashicorp/vault/blob/ea296ccf58507b25051bc0597379c467046eb2f1/vault/policy_store.go#L362

Hope this clarifies things a bit more!

**Comment by Nikita1821** [comment]
i'm sorry, i don't see it(
thank you
