### ISSUE TITLE
"// Ensure that the default policy exists, and if not, create it" loadACLPolicy() in setupPolicyStore()

### ISSUE THREAD

**Issue by Nikita1821** [hashicorp/vault#16376]
Why do you load 3 default policy in setupPolicyStore() function in unseal?
it's a waste of time, if we use many default policies, do you get everyone from storage?

// Ensure that the default policy exists, and if not, create it
	if err := c.policyStore.loadACLPolicy(ctx, defaultPolicyName, defaultPolicy); err != nil {
		return err
	}
	// Ensure that the response wrapping policy exists
	if err := c.policyStore.loadACLPolicy(ctx, responseWrappingPolicyName, responseWrappingPolicy); err != nil {
		return err
	}
	// Ensure that the control group policy exists
	if err := c.policyStore.loadACLPolicy(ctx, controlGroupPolicyName, controlGroupPolicy); err != nil {
		return err
	}

**Comment by ncabatoff** [comment]
loadACLPolicy, despite the name, doesn't just read the policies from storage, it's also creating them when they don't already exist.  We put the policies in storage rather than hardcoding them so that people can modify those policies if they want.

I'm not sure what you mean by "many default policies"?

As to it being a waste of time - there's a lot of stuff that happens during unseal, reading a couple of storage entries is pretty insignificant in terms of the total time.

**Comment by Nikita1821** [comment]
"I'm not sure what you mean by "many default policies"?" - I mean everything policies what you get from storage in unseal(sorry)
you init vault - vault putted policy in storage

why do you get policy from storage in unseal every time?

**Comment by Nikita1821** [comment]
generate rsa keys in identity store - it's really long - 100-200 ms
and every time geting 3 policy from storage

**Comment by Nikita1821** [comment]
if somebody deleted these 3 policies from physical storage, maybe I get a message from vault about this critical error?

**Comment by ncabatoff** [comment]
When vault is unsealed, it's like it's rebooting.  Any state it had in memory prior to being sealed is lost.  We have to read those policies from storage because we want to allow users to modify them, and because we don't know what their contents is due to us having been in a sealed state.

You're right however that we could do this differently, writing the policies once at init time, and only reading them on demand like we do other policies.  I don't think the potential speed improvement is worth the disruption though.

Why is unseal speed such a concern for you?

**Comment by Nikita1821** [comment]
I want to add more policies during init
