### ISSUE TITLE
Expiration manager revoked tokens despite them having TTL remaining

### ISSUE THREAD

**Issue by BRMatt** [hashicorp/vault#1640]
Earlier this morning Vault revoked several of our tokens, even though they had several days left on their TTLs. I've restored a backup of vault's database from yesterday, and by adjusting the system clock I can reliably recreate a situation where the tokens are valid, then get revoked, even though there are > 400 hours remaining on the TTL. My repro environment is using a copy of 0.6.0 from the website.

I'm still trying to track down how this happened, but I thought I'd start an issue to see if you have any pointers as the behaviour seems unusual.

Relevant information:

- 20 days ago (1st July ~ 13:00 UTC) we upgraded from 0.5.2 -> 0.6.0 (from the website)
- We provision "long-lived" tokens for each of our apps (vault config file contains `"max_lease_ttl": "438000h"`)
- We have a cron job that runs every morning, "incrementing" the TTL of these tokens to 20 days

Here's a graph showing the TTL of these tokens over the past 7 days (taken from the `ttl` field of the `lookup-self` endpoint):

![](https://cl.ly/1F0Y1G463Y1e/Image%202016-07-21%20at%202.41.52%20pm.png)

And here's the graph focussed on the time of the incident:

![](https://cl.ly/1W143W1L3A2i/Image%202016-07-21%20at%202.44.11%20pm.png)

Here are the logs from vault's STDOUT at that moment (graphs are in BST, logs are in UTC):

```
2016/07/21 09:00:02 [INFO] expire: revoked 'auth/token/renew-self/8b09de498befe70177a8f3dde71a7bd85897fbeb'
2016/07/21 09:00:02 [INFO] expire: revoked 'auth/token/renew-self/b05d09df958d7e371ec93a3629f8baaa9a955c7f'
2016/07/21 09:00:02 [INFO] expire: revoked 'auth/token/renew-self/d6b884ebf5c330f533e5ae1f3779d0aff98f01b5'
2016/07/21 09:00:02 [INFO] expire: revoked 'auth/token/renew-self/518ae40efed9affc4e431af012824af6c5f1fa95'
2016/07/21 09:00:02 [INFO] expire: revoked 'auth/token/renew-self/9e651ab0fa08f013ff374a4a03c8c2e2030044d5'
```

The backups have allowed us to investigate the state of vault prior to the incident. I'm not sure which keys are relevant, but these keys seem to be associated with the `auth/token/renew-self/518ae40efed9affc4e431af012824af6c5f1fa95` entry:

```
# sys/token/id/518ae40efed9affc4e431af012824af6c5f1fa95
{
  "Meta": null,
  "Parent": "",
  "DisplayName": "token-management-api-worker",
  "ID": "REDACTED",
  "TTL": 2592000000000000,
  "Policies": [
    "default",
    "polling-keys-full-access",
    "service-account-credentials-full-access",
    "service-objects-full-access"
  ],
  "NumUses": 0,
  "CreationTime": 1466158288,
  "Path": "auth/token/create"
}
```

```
# sys/expire/id/auth/token/create/518ae40efed9affc4e431af012824af6c5f1fa95
{
  "client_token": "REDACTED",
  "path": "auth/token/create",
  "issue_time": "2016-06-17T10:11:28.98035926Z",
  "auth": {
    "Accessor": "",
    "DisplayName": "token-management-api-worker",
    "renewable": true,
    "lease": 1728000000000000,
    "Metadata": null,
    "InternalData": null,
    "Policies": [
      "default",
      "polling-keys-full-access",
      "service-account-credentials-full-access",
      "service-objects-full-access"
    ],
    "ClientToken": "REDACTED"
  },
  "lease_id": "auth/token/create/518ae40efed9affc4e431af012824af6c5f1fa95",
  "expire_time": "2016-08-09T09:00:01.981961319Z",
  "data": null,
  "last_renewal_time": "2016-07-20T09:00:01.981962355Z",
  "secret": null
}
```

```
# sys/expire/id/auth/token/renew-self/518ae40efed9affc4e431af012824af6c5f1fa95
{
  "last_renewal_time": "0001-01-01T00:00:00Z",
  "client_token": "REDACTED",
  "issue_time": "2016-07-01T09:00:02.478241522Z",
  "data": null,
  "secret": null,
  "lease_id": "auth/token/renew-self/518ae40efed9affc4e431af012824af6c5f1fa95",
  "expire_time": "2016-07-21T09:00:02.478242359Z",
  "path": "auth/token/renew-self",
  "auth": {
    "InternalData": null,
    "ClientToken": "REDACTED",
    "Metadata": null,
    "renewable": true,
    "DisplayName": "token-management-api-worker",
    "lease": 1728000000000000,
    "Policies": [
      "default",
      "polling-keys-full-access",
      "service-account-credentials-full-access",
      "service-objects-full-access"
    ]
  }
}
```

```
# sys/token/parent/29a876ccd9206d415b54293473f8d1cfc93b69b8/518ae40efed9affc4e431af012824af6c5f1fa95

empty value
```

The last payload references 09:00 this morning as the expiration time, but others reference `2016-08-09T09:00:01.981961319Z` as the expiration time.

One interesting thing I noticed is that the log<sub>2</sub>(2592000000000000) (the TTL field) is ~51 bits long and some languages impose a limit of 52 bits of precision on json numbers. That said, I'm not sure if this is relevant as type `time.Duration` seems to be an `int64` and `encoding/json` appears to be able to [encode](https://golang.org/src/encoding/json/encode.go#L486)/[decode](https://golang.org/src/encoding/json/decode.go#L877) 64bit integers.

**Comment by jefferai** [comment]
Hi @BRMatt ,

It's really hard to understand what's going on with the redacted client tokens. Can you update the pastes above with obfuscated values (perhaps hmac'd shas) so that I can understand the correlation between the entries?

Thanks,
Jeff

**Comment by BRMatt** [comment]
@jefferai All occurrences of REDACTED in these payloads represent the same token ID. i.e.

```
$ ./vault token-lookup REDACTED
Key              	Value
---              	-----
accessor
creation_time    	1466158288
creation_ttl     	2592000
display_name     	token-management-api-worker
explicit_max_ttl 	0
id               	REDACTED
last_renewal_time	1469005201
meta             	<nil>
num_uses         	0
orphan           	true
path             	auth/token/create
policies         	[default polling-keys-full-access service-account-credentials-full-access service-objects-full-access]
renewable        	true
role
ttl              	1647634
```

**Comment by BRMatt** [comment]
Would you still prefer me to use hmac'd shas?

**Comment by jefferai** [comment]
@BRMatt It's OK. I think I know the underlying cause, just trying to verify exact behavior.

**Comment by jefferai** [comment]
OK -- this was one of a few bugs fixed partly in fd0edf26 and partly in 8056bf0, which means the underlying cause is already fixed since 0.6.

The underlying cause -- which probably existed since the introduction of `renew-self` -- was that there was a hardcoded expected path during request handling that any renewal requests would have a request path of `auth/token/renew/`, because at the time that code was written it was the only way to actually renew a token. When `renew-self` -- at path `auth/token/renew-self` -- was introduced, this check no longer worked, causing the request flow to hit the function that generates a new lease. This particular case was fixed in fd0edf26.

This wouldn't have been a problem except for another issue -- when renewing, the value being passed to the expiration manager for the token path was the request path rather than the actual path of the token entry being renewed. Since the token's creation path was `auth/token/create` but the request path was `auth/token/renew-self`, rather than the expiration manager simply overwriting the existing entry with the new TTL info, it actually created a new entry, leaving the old timer in place and starting a new one. This was fixed in 8056bf0.

What you saw was the effect of the old timer timing out. Unfortunately, you basically have two options at this point:

1) Change your renewal logic so that it renews leases with both `auth/token/create/<ID>` and `auth/token/renew-self/<ID>`. The ID is the same. Renewing both should ensure that they don't time out again.

2) Issue new tokens.

Option 2 isn't necessarily a bad idea, because based on the above information, you're using super long token lifetimes rather than rotate them. The problem with doing this is that *all* tokens issued directly from the token store are subject to the same max TTL. The recommended way to have very long lived tokens that are renewed in an automatic fashion is via periodic tokens. These can be created using token store roles (and in 0.6.1, via the new AppRole backend). Periodic tokens have a fixed period, so for every renewal the TTL will be reset to the defined period (rather than the normal behavior where any renewal of a token can potentially set the TTL to the system or token-store-mount-set max), but so long as they are renewed successfully they never expire.

Happy to answer any further questions...

**Comment by BRMatt** [comment]
Thank you so much for the in-depth explanation/advice! ❤️  I owe you a beer/beverage! 🍻 

So if I understand this correctly, 0.5.2 was creating lease entries under `sys/expire/id/auth/token/create/...` at token creation time, then creating new ones under `sys/expire/id/auth/token/renew-self/...` at renewal time? I'm a little confused as to why the lease at `sys/expire/id/auth/token/create/...` didn't expire before we upgraded... I don't suppose you have any insight into this?

For posterity, here's what our leases looked like before we upgraded:

```
# sys/expire/id/auth/token/renew-self/518ae40efed9affc4e431af012824af6c5f1fa95
{
  "last_renewal_time": "0001-01-01T00:00:00Z",
  "secret": null,
  "data": null,
  "auth": {
    "renewable": true,
    "DisplayName": "token-management-api-worker",
    "InternalData": null,
    "lease": 1728000000000000,
    "Metadata": null,
    "ClientToken": "REDACTED",
    "Policies": [
      "default",
      "polling-keys-full-access",
      "service-account-credentials-full-access",
      "service-objects-full-access"
    ]
  },
  "issue_time": "2016-07-01T09:00:02.478241522Z",
  "expire_time": "2016-07-21T09:00:02.478242359Z",
  "path": "auth/token/renew-self",
  "lease_id": "auth/token/renew-self/518ae40efed9affc4e431af012824af6c5f1fa95",
  "client_token": "REDACTED"
}
```

```
# sys/expire/id/auth/token/create/518ae40efed9affc4e431af012824af6c5f1fa95
{
  "auth": {
    "ClientToken": "REDACTED",
    "InternalData": null,
    "Metadata": null,
    "lease": 1728000000000000,
    "Policies": [
      "default",
      "polling-keys-full-access",
      "service-account-credentials-full-access",
      "service-objects-full-access"
    ],
    "renewable": true,
    "DisplayName": "token-management-api-worker"
  },
  "lease_id": "auth/token/create/518ae40efed9affc4e431af012824af6c5f1fa95",
  "last_renewal_time": "2016-07-01T09:00:02.456140033Z",
  "data": null,
  "path": "auth/token/create",
  "client_token": "REDACTED",
  "secret": null,
  "issue_time": "2016-06-17T10:11:28.98035926Z",
  "expire_time": "2016-07-21T09:00:02.456139238Z"
}
```

> 2) Issue new tokens.

Thanks for the suggestions. In the short-term we'll probably create new tokens. Long-term we'll have to look at moving to periodic tokens/approle. The current approach is definitely less than ideal, we're only doing it this way because it was the easiest way to migrate our systems to vault.

As an aside we've now fully migrated over to vault - all encryption/decryption of credentials we store for third party services (e.g. oauth tokens, api keys etc) is done through the vault transit backend! It's currently chugging along at 11,000+ requests per minute.

**Comment by jefferai** [comment]
> I'm a little confused as to why the lease at sys/expire/id/auth/token/create/... didn't expire before we upgraded

If you look at the `create` entry in your last post you'll see that the `expire_time` is `"expire_time": "2016-07-21T09:00:02.456139238Z"` which seems to exactly match the behavior you saw.

I think the key here is that depending on which `lease_id` you ended up renewing you'd see different behavior. From the previous values you posted it appears like sometimes the `.../create/...` lease was being renewed and sometimes `.../renew-self/...` was being renewed.

You can see the current docs for AppRole at https://github.com/hashicorp/vault/blob/f8a1b0dd9f7fb2031deea7c81f1bf24b4063f8f5/website/source/docs/auth/approle.html.md -- this is likely going to be merged in today, but the docs will potentially get some love between now and release. Note that you don't *need* to use AppRole to get periodic tokens, you can also use token store roles to get them as well. They're not exposed for user operations because they're really not meant as a user feature.

> As an aside we've now fully migrated over to vault - all encryption/decryption of credentials we store for third party services (e.g. oauth tokens, api keys etc) is done through the vault transit backend! It's currently chugging along at 11,000+ requests per minute.
A++++++!!!!! :heart: :heart: :heart:

**Comment by jefferai** [comment]
@BRMatt I'm going to close this, but if you have further questions/comments I'll still watch for them.

**Comment by BRMatt** [comment]
> I think the key here is that depending on which lease_id you ended up renewing you'd see different behavior. From the previous values you posted it appears like sometimes the `.../create/...` lease was being renewed and sometimes `.../renew-self/...` was being renewed.

Yeah I noticed the expire time was the same, but I think our tokens had been around for a while at the point we upgraded so wasn't sure why both leases were being renewed. At one point we were using the `renew` endpoint, but then we moved everything over to `renew-self`. `¯\_(ツ)_/¯`

> Note that you don't need to use AppRole to get periodic tokens, you can also use token store roles to get them as well. They're not exposed for user operations because they're really not meant as a user feature.

Gotcha, cheers. Have a great weekend!
