### ISSUE TITLE
Error on parsing pem_bundle parameter

### ISSUE THREAD

**Issue by mmauro-ez** [hashicorp/vault#16667]
**Describe the bug**

Hello there,

We are trying to upgrade from Vault 1.9.6 to 1.11.2 and we are encountering an issue when importing intermediate CA PEM files through endpoint /config/ca :

**To Reproduce**

Request
`
curl --header "X-Vault-Token: ..." --request POST --data "@payload.json" http://127.0.0.1:8200/v1/pki/config/ca
`

PEM file:

```
-----BEGIN CERTIFICATE----- 
...
-----END CERTIFICATE-----
-----BEGIN EC PARAMETERS-----
...
-----END EC PARAMETERS-----
-----BEGIN EC PRIVATE KEY-----
...
-----END EC PRIVATE KEY-----
```

Result :
`
"Error parsing key 0: failed to parse PEM block: asn1: structure error: tags don't match (16 vs {class:0 tag:6 length:8 isCompound:false}) {optional:false explicit:false application:false private:false defaultValue:<nil> tag:<nil> stringType:0 timeType:0 set:false omitEmpty:false} pkcs8 @2"
`

**Expected behavior**

Return success code with CA correctly imported

**Environment:**

The issue seems to appear since version 1.11.0 

_(It works fine from 1.9.6 to 1.10.5)_

**Additional context**

Similar issue there: https://github.com/hashicorp/vault/issues/16203, but we still couldn't figure out a solution.

Validating PEM file content with openssl reports no explicit error.
Parsing PEM file content with crypto/x509 and encoding/pem Golang libraries reports no explicit error.

**Comment by schultz-is** [comment]
Howdy @mmauro-ez, does this work when you remove the curve parameters from the PEM bundle?

e.g.
```
-----BEGIN CERTIFICATE-----
...
-----END CERTIFICATE-----
-----BEGIN PRIVATE KEY-----
...
-----END PRIVATE KEY-----
```

**Comment by mmauro-ez** [comment]
Hi @schultz-is, removing the curve parameters gives now the error:

`"1 error occurred:\n\t* error building CRLs: unable to build CRL for issuer (9f6e97c5-7456-8b42-c1e2-27c05bc1dcc8): error fetching CA certificate: Error getting key type from pkcs#8: Failed to parse pkcs#8 key: x509: failed to parse private key (use ParseECPrivateKey instead for this key format)\n\n"`

**Comment by schultz-is** [comment]
Ah, that sounds like the curve the key uses is one that's not supported by Go. Would you happen to know which curve the key is using?

**Comment by mmauro-ez** [comment]
Here is the result of: `openssl ec -in file.pem -text -noout`
```
read EC key
Private-Key: (256 bit)
priv:
    ...
pub:
    ...
ASN1 OID: prime256v1
NIST CURVE: P-256
```

The NIST P-256 seems to be implemented by crypto/elliptic library : https://pkg.go.dev/crypto/elliptic@go1.17.12

And we have no issue when importing this PEM file on Vault 1.10.5, which has the same Go version as Vault 1.11.2 from
(Go version: 1.17.12)

**Comment by dosfslib** [comment]
We had a similar issue with Vault 1.11.2 in the sense that importing with a POST of cert/ca with a pem bundle with another certificate such as the submit CA information in 1.10.5 and the certificate does not seem to be overwritten. I had to delete the whole root section in order to replace it. It used to be working in 1.10.5.

**Comment by cipherboy** [comment]
@dosfslib I believe that is a separate issue. If you read the upgrade notes around PKI, we're explicitly allowing multiple issuers. So yes, this is the expected behavior on 1.11+. You'll want to call `DELETE /root` prior to import (if you want the old behavior) -- or manually delete them as you've done (`LIST /issuers + DELETE /issuer/:unwanted_ref`) afterwards.

Note that the new semantics allow for safer/incremental rotation (in that multiple issuers can exist temporarily until they're propagated everywhere and then the old ones can be removed) so this is working as intended. :-)

**Comment by dosfslib** [comment]
thanks that makes sense i will make modifications for automation.
