### ISSUE TITLE
Vault active node should become standby when SIGTERM is received

### ISSUE THREAD

**Issue by jacob-koren** [hashicorp/vault#1705]
If the active node knows that it's about to die, then a step-down action should be triggered immediately. Otherwise, unnecessary downtime occurs.

**Comment by jacob-koren** [comment]
I tested it on docker container using "docker stop" which send SIGTERM and after 10 seconds SIGKILL

**Comment by jefferai** [comment]
This sounds like a Docker problem. Vault correctly responds to SIGTERM outside of a Docker container.

**Comment by jacob-koren** [comment]
But it should respond also inside? Do you have an official docker image?

**Comment by jefferai** [comment]
There are a lot of non-official Docker containers out there that may or may not work properly. There is an official image -- it's simply "vault" as it's part of the Docker standard library. I just tested and `docker stop` works correctly with it.

**Comment by jacob-koren** [comment]
Did you test on mesos? coreos?

**Comment by jefferai** [comment]
We test on a normal Linux environment using the current version of Docker.

**Comment by jacob-koren** [comment]
Then you didn't cover large portion of the use cases

**Comment by jefferai** [comment]
That is correct.

**Comment by jacob-koren** [comment]
If vault hasn't been tested on Mesos than it does not support docker. 
Mesos is one of the primary ways to run containers, not a corner case.
How is it closed?

**Comment by jefferai** [comment]
It's closed because there's nothing more that I can provide. Vault supports Docker. Mesos is not Docker; Mesos optionally *uses* Docker as a client. If you are seeing this problem, but it is not reproducible in a Docker-only setup (which it isn't, in my testing), then it's likely caused by your Docker image (if not using the official library image), Docker version, your OS, your OS version, your Mesos version, some combination of the above, or none of them. None of these are related to Vault specifically.
