### ISSUE TITLE
HA question

### ISSUE THREAD

**Issue by jacob-koren** [hashicorp/vault#1742]
Is vault completely HA (zero downtime)? 
I tested with two nodes firing requests to the standby node and follow redirects. At some point, I sent an SIGTERM to the active node, and it took few seconds for the standby node to act as active.
For a few seconds, I was still getting redirects to the dead node.

Details: 
- There was 3 seconds delay between SIGTERM and SIGKILL
- throughput ~10 Req/sec 

Maybe 3 seconds is not enough?

**Comment by jefferai** [comment]
It is not zero downtime, although in practice it is often less than a second...it depends strongly on the number of mk mounts, leases, and other objects in the data store. Generally speaking a SIGKILL will cause things to take longer, not shorter, because you run the risk of having to wait for the lock in the data store to time out rather than being given up gracefully.
