### ISSUE TITLE
OIDC login fails when using Firefox in fullscreen on macOS

### ISSUE THREAD

**Issue by MattIPv4** [hashicorp/vault#17584]
**Describe the bug**

When using OIDC to sign in while accessing Vault through Firefox on macOS with the app running in fullscreen, OIDC fails to complete on the original tab.

The login screen for the OIDC provider opens in a new tab and completes, returning back to Vault with the success message. The tab then closes shortly after, taking you back to the original tab where an error message shows stating that the tab was closed early (even though it closed itself after the success message automatically).

![image](https://user-images.githubusercontent.com/12371363/196488868-94a155e5-ea96-471c-ab69-ba5c53984a2c.png)

**To Reproduce**

1. Have Vault configured with an OIDC sign-in option
2. Acess Vault via Firefox on macOS, with Firefox running as a fullscreen application
3. Attempt to sign into Vault
4. Observe failure

**Expected behavior**

Login should complete as it does when Firefox is running windowed, rather than fullscreen.

**Environment:**

* Vault Server Version (retrieve with `vault status`): `Version 1.10.1+ent`
* Vault CLI Version (retrieve with `vault version`): `Vault v1.10.1 (e452e9b30a9c2c8adfa1611c26eb472090adc767)`
* Server Operating System/Architecture: `Linux [REDACTED] 5.0.0-36-generic #39~18.04.1-Ubuntu SMP Tue Nov 12 11:09:50 UTC 2019 x86_64 x86_64 x86_64 GNU/Linux`

**Additional context**

Given that this works just fine when Firefox is running in windowed mode, I suspect this has to do with some oddity in opening a popup window vs. opening a tab (when Firefox is windowed, the OIDC login appears in a popup window, but when Firefox is fullscreen a popup window isn't possible and so it opens a new tab).

**Comment by ausfestivus** [comment]
These are the steps ive been using to repro the problem.
Only seeing the issue on MacOS.
Some additional info from efforts to further isolate the issue are included at the bottom.

**Repro**
* Start new incognito browser window, ensure the browser window is opened in full-screen
* Open your Vault browser UI in the incognito window
* Click the **Sign in with OIDC Provider** button
* A new tab will appear for https://login.microsoft.com
* Enter your Azure Active Directory credentials and complete the sign in
* The new tab for the Azure Active Directory sign in will update and then close
* The Vault sign in page will display an error that says
<img width="602" alt="Screen Shot 2023-01-16 at 10 02 39 am" src="https://user-images.githubusercontent.com/40222285/212795017-b8316bd3-8071-49fb-9590-90891efb4095.png">

* Now, exit full screen view in the incognito browser window
* Click the **Sign in with OIDC Provider** button
* The Vault sign in will be successful
* Sign out of Vault

**Additional info**
* havent been able to reproduce on a Windows machine using Chrome(v108.0.5359.125) or Edge(v109.0.1518.55)
* If performed using Safari, the problem is intermitent. Safari also displays a JS error in the popup window.
<img width="1146" alt="Screen Shot 2023-01-17 at 1 23 44 pm" src="https://user-images.githubusercontent.com/40222285/212795997-92028383-529f-46b2-8989-bcf3d528c107.png">

* Chrome on MacOS also has the same problem (v109.0.5414.87)
* Problem persists when Firefox is in Troubleshooting Mode
* Problem persists if external monitors are connected or not

**Comment by greedybro** [comment]
I have the same behaviour using Vault, OIDC and Firefox on MacOS.

Tested on:
- MacOS 12 and 13
- Vault 1.11.x and 1.12.x
- Firefox 105, 106, 107, 108, 109

In order to get it work, I have to get Firefox out its ["space"](https://support.apple.com/en-gb/guide/mac-help/mh14112/mac) and then it pops a new window instead of a new tab for OIDC sign-in.

**Comment by candlerb** [comment]
I also see this problem when authenticating against an upstream OIDC provider. For me it is consistent rather than intermittent, and does not require fullscreen mode.  The problem is definitely with pop-ups; I have not redirected pop-ups to their own tabs.

It works with Chrome (under macOS).

When using Safari, the user sees this:
![image](https://user-images.githubusercontent.com/44789/216762928-2b35dd2a-e7b6-42d5-af15-1f61f0cf827c.png)
The user has to go to Preferences... > Websites > (scroll down to) Pop-up Windows, and change "Block and Notify" to "Allow", then try again.

In Firefox, pop-ups are also disabled by default, although there's a small button you can click to enable them (if you notice it):
![image](https://user-images.githubusercontent.com/44789/216763013-66a08089-54fc-470d-89cb-8adfdd046090.png)

Personally, I think this gives a very poor user experience, and requires a lot of user hand-holding to resolve. I would rather that the authorization took place using a regular redirect (as is normal for OpenIDC), instead of inside a pop-up.

**Comment by aphorise** [comment]
We've had the following message update regarding pop-ups on: #18787 - pending release in the next Vault **1.12.3**

I suspect this issue may also be resolved when that's released?

**Comment by MattIPv4** [comment]
For me, this was never about the browser blocking popups. I have popups enabled, and the popup does appear (not a popup though, just as a new tab, because Firefox is running as a fullscreen app). Vault freaks out at that and fails to authenticate with the error I shared.

**Comment by candlerb** [comment]
> We've had the following message update regarding pop-ups on: #18787 - pending release in the next Vault **1.12.3**
> 
> I suspect this issue may also be resolved when that's released?

All that #18787 does is change the wording of the error message, from:

_"The provider window was closed before authentication was complete.  Please click Sign In to try again."_

to:

_"The provider window was closed before authentication was complete. Your web browser may have blocked or closed a pop-up window. Please check your settings and click Sign In to try again."_

**Comment by shivshav** [comment]
Can confirm. I'm getting the same issue **only in Firefox, and only when fullscreen** (Chrome seems to work fine, though I didn't try any other browsers)

Details:
- macOS Monterey 12.6.2
- Firefox 109 in fullscreen mode
- Vault 1.12.1
- Popups are allowed for my Vault instance in Firefox settings

Upgraded from 1.8, where it was not an issue previously

**Comment by aphorise** [comment]
Hey @shivshav - thank you for the clarity and comparative notes that also included Firefox versions.

I'm just curious if has any ideas what may have changed since 1.8 and if there are any current workarounds in the case of full-screen Firefox in the current versions.

**Comment by shivshav** [comment]
Hey @aphorise, my apologies, I should've stated in the previous message; the workaround of exiting out of fullscreen for login does indeed work for me in Firefox.

I have not tried any other OSes personally so I couldn't say whether it's OS-specific or not.
