### ISSUE TITLE
Reading Versioned Plugin Doesn't work

### ISSUE THREAD

**Issue by davidcorrigan714** [hashicorp/vault#17738]
**Describe the bug**
When using a vault read command on a plugin with a version as shown [in the docs](https://developer.hashicorp.com/vault/api-docs/system/plugins-catalog#read-plugin), no data is returned.

```
root@ip-10-236-99-32:/var/snap/amazon-ssm-agent/6312# vault plugin info -version=0.1.2  secret artifactory
Key                   Value
---                   -----
args                  []
builtin               false
command               artifactory-secrets-plugin_v0.1.2
deprecation_status    n/a
name                  artifactory
sha256                0ca7f4ad38be7fd790ae39aed96dc1961eeccf0f991632c82ffbd544658162eb
version               v0.1.2
root@ip-10-236-99-32:/var/snap/amazon-ssm-agent/6312# curl --header "X-Vault-Token: ...." --request GET https://.....:8200/v1/sys/plugins/catalog/secret/artifactory
{"errors":[]}

```

**Comment by ccapurso** [comment]
Hi, @davidcorrigan714. In order to attempt to identify the root cause of the issue that you have provided it would be beneficial to have a bit more information. Would you be able to provide the version of Vault that you are running and a full output of the request using `curl -v ...`. Thanks!

**Comment by davidcorrigan714** [comment]
@ccapurso I'm using v1.12.0, which I believe is the only version that supports plugin versioning. Querying a versioned plugin needs a version query parameter so I think the docs are just a bit misleading in this case. The "Sample Request" really needs a "?version=v1.0.0" tacked on. It'd be nice if it would actually return all versions or something useful when it's not included but that doesn't seem to be the case. Maybe some note that the version query is required for versioned plugins in the "Parameters" section would be helpful.

**Comment by tomhjp** [comment]
Hi @davidcorrigan714, thanks for reporting this, you're right that the documentation is misleading, as the request doesn't match the response. It sounds like you've got this, but just to confirm, does `curl --header "X-Vault-Token: ...." --request GET https://.....:8200/v1/sys/plugins/catalog/secret/artifactory?version=0.1.2` work for you?

To complete the context, the 404 on your `curl` command is because it's querying for the "unversioned" plugin of that name and type (i.e. if you previously ran `vault plugin register -sha256=... -command=... secret artifactory`, without a `-version` flag), which presumably hasn't been registered.

We'll get the request updated in the documentation.

**Comment by davidcorrigan714** [comment]
@tomhjp confirming that adding the version query parameter works.
