### ISSUE TITLE
Allow user to set Consul health status on standby

### ISSUE THREAD

**Issue by mfischer-zd** [hashicorp/vault#1775]
With 0.6.0's builtin Consul health provider, both the active and standby nodes are published as healthy.  Clients that look up Vault using Consul DNS could then try to connect to either address (as the agent may return one or the other).  

If HTTP redirection isn't working for whatever reason (No IP SAN in Vault's TLS certificate, accessing Vault through an SSH tunnel, etc.), clients may be unable to connect to Vault reliably if they receive the address from Consul for the standby node instead of the active one.

To handle situations like this, allow the user to optionally configure Vault to set the Consul health status on the standby node to "warning" or "critical", so that the standby node won't get published in Consul DNS.

(There are admittedly workarounds like using Consul prepared queries, but they're more difficult at some sites to implement, or may force a DNS name change, forcing a TLS certificate reissuance...)

**Comment by jefferai** [comment]
I believe this was already changed in 0.6.1? @vishalnayak do you know?

**Comment by mgilbir** [comment]
On vault 0.6.1 I have consul health end-points as: `https://URL/v1/sys/health?standbycode=503` and it's working like a charm.

On a somehow unrelated note, but just in case you also stumble with it, I had problems because vault>0.6.0 will register automatically a service called `vault` in consul unless explicetly told not to. If you happen to have a consul service with the same name things get ugly.

**Comment by jefferai** [comment]
@mgilbir You're talking about external health checks; @mfischer-zd is talking about internal health checks.

I looked at the 0.6.1 code and I don't think you can actually specify what you want Consul's status to be for standbys.

Still, any reason just changing your query to `active.vault.service.consul` instead of `vault.service.consul` isn't working for you?

**Comment by mfischer-zd** [comment]
With Consul DNS you can only specify one tag in the query name, unless you're using prepared queries.  In our case, we've got a functional scope tag (e.g., `master`, `staging`) that we're using to address our Vault.  We can't specify both `master` and `active` in the current Consul DNS implementation.  (Also, it's so rare that we'd want to address the `standby` directly that it's not worth publishing IMO.)

**Comment by jefferai** [comment]
It seems like prepared queries (after all, this kind of thing is what they're there for) are a good option, but you could also turn on request forwarding in Vault. Then you don't need to rely on redirection.

**Comment by mfischer-zd** [comment]
That's what we're doing now, but it seems unnecessary IMO.
