### ISSUE TITLE
vault unseal doesn't error out, and exits 0 when given an incorrect hex or base64 string

### ISSUE THREAD

**Issue by SarahKowalik** [hashicorp/vault#1777]
Using vault v0.6.1 (released version)

When giving an incorrect string for the unseal key (such as 'asdf'), there is no obvious visual output that an incorrect string has been entered, beyond the `Unseal Progress` staying at 0.  

This also exits 0, while other invalid keys given (such as `'key' must be a valid hex or base64 string`) exit non-zero.

```
-- sarah@vault:~ $ vault unseal
Key (will be hidden): <asdf>
Sealed: true
Key Shares: 6
Key Threshold: 2
Unseal Progress: 0
-- sarah@vault:~ $ echo $?
0
```

**Comment by jefferai** [comment]
@SarahKowalik Originally it didn't error on invalid key to avoid leaking any kind of sensitive state, but in the end the only errors returning a `200`/`204` are invalid key errors anyways, so we'll just make them `BadRequest` errors.

BTW: `asdf` doesn't throw give an invalid key error because it's valid base64!

**Comment by SarahKowalik** [comment]
That makes sense, thanks! :)
