### ISSUE TITLE
panic: runtime error: invalid memory address or nil pointer dereference when register custom secret plugin

### ISSUE THREAD

**Issue by evitch** [hashicorp/vault#17878]
I'm writing a custom secret plugin based on built-in pki plugin and another based on transit built-in plugin.
Register plugins is ok with Vault 1.11.3. But now with Vault 1.12 and 1.12.1 I have errors:
```sh
panic: runtime error: invalid memory address or nil pointer dereference
vault    | [signal SIGSEGV: segmentation violation code=0x1 addr=0x88 pc=0x12e5e5b]
vault    |
vault    | goroutine 813 [running]:
vault    | github.com/hashicorp/vault/sdk/plugin.(*gRPCSystemViewServer).ReplicationState(0x505dea0?, {0xc00114a420?, 0x4bd306?}, 0x0?)
vault    |      /home/runner/work/vault/vault/sdk/plugin/grpc_system.go:224 +0x1b
vault    | github.com/hashicorp/vault/sdk/plugin/pb._SystemView_ReplicationState_Handler({0x5514040?, 0xc000f40260}, {0x6b5aff8, 0xc00114a3f0}, 0xc00114c1e0, 0x0)
vault    |      /home/runner/work/vault/vault/sdk/plugin/pb/backend_grpc.pb.go:939 +0x170
vault    | google.golang.org/grpc.(*Server).processUnaryRPC(0xc0011ae000, {0x6b702c0, 0xc0011aa340}, 0xc000cb7440, 0xc001190480, 0x9943880, 0x0)
vault    |      /home/runner/go/pkg/mod/google.golang.org/grpc@v1.47.0/server.go:1283 +0xcfe
vault    | google.golang.org/grpc.(*Server).handleStream(0xc0011ae000, {0x6b702c0, 0xc0011aa340}, 0xc000cb7440, 0x0)
vault    |      /home/runner/go/pkg/mod/google.golang.org/grpc@v1.47.0/server.go:1620 +0xa2f
vault    | google.golang.org/grpc.(*Server).serveStreams.func1.2()
vault    |      /home/runner/go/pkg/mod/google.golang.org/grpc@v1.47.0/server.go:922 +0x98
vault    | created by google.golang.org/grpc.(*Server).serveStreams.func1
vault    |      /home/runner/go/pkg/mod/google.golang.org/grpc@v1.47.0/server.go:920 +0x28a
vault    | Error registering plugin pki: Put "http://0.0.0.0:8200/v1/sys/plugins/catalog/secret/pki": EOFvault exited with code 2
```

**Comment by paxwell92** [comment]
We had a very similar issue. We were crashing vault when trying to register a plugin under v1.12.1.  I think the issue is around changes to the plugin life-cycle in v12. As of v12 plugins are started and killed to check what version they are v4 or v5 during the registration process.

 During this process func Factory is used to create a new Backend and provided  *logical.BackendConfig

we were (improperly) using c.StorageView.Put to initialize a config variable and save it in the Storage Backend

When using v1.12.1 and v0.6.1 of the sdk, vault not just the plugin, would crash after “core: successfully dispensed v5 backend plugin:” with
SIGSEGV github.com/hashicorp/vault/sdk/plugin.(*GRPCStorageServer).Put.

I would assume calling c.System.ReplicationState() during Factory would cause the same issue.

Interestingly this issue only exists for specific versions of the plugin sdk including v0.6.1 downgrading to v0.5.3 the plugin functions without crashing the application.

In our case the fix was to move any use of Storage to an InitializeFunc: b.initialize, and using request.Storage.

Assuming its the same issue b.System().ReplicationState() should work in your case from within initialize


This can be easily replicated with any plugin I used 

https://github.com/sethvargo/vault-secrets-gen/tree/main

Just add 

	entry, err := logical.StorageEntryJSON("config", "test")
	if err != nil {
		return nil, err
	}
	_ = c.StorageView.Put(ctx, entry)

Above the return in Factory in gen/backend.go

Because it is build using github.com/hashicorp/vault/sdk v0.5.3 there will be no errors and the plugin will load.

Run go get -u to update to v0.6.2 and rebuild and this should crash vault on v1.12.1

as I said above I assume adding 

_ = c.System.ReplicationState() will also trigger a crash but I did not test.

I did not check if as stated in the original issue downgrading to v1.11.3 would also not crash.

**Comment by tomhjp** [comment]
Thanks for the report. I think you're right @paxwell92, although we should definitely guard against panics and return a helpful error message/document this requirement. @evitch would you be able to link to your plugin source code to help confirm these are both the same issue please? Or otherwise confirm that moving sys/storage usage to the `Initialize` function fixes the issue?
