### ISSUE TITLE
Unable to read ssh key from ssh mount

### ISSUE THREAD

**Issue by ekristen** [hashicorp/vault#1787]
In 0.3.1 you could write a key to `ssh/keys/<key-name>` and then read it back out if you needed it for something.

In 0.6.0 it gives unsupported operation when trying to read.

I have read all changelog entries and upgrade notes and cannot find any not that this behavior was changed or removed. Is this a bug? Or was this done on purpose.

**Comment by jefferai** [comment]
If a feature is purposefully removed or changed in a breaking way, we document it in the changelog and (since 0.5.0) the version-specific upgrade notes.

In this case, I can find no evidence that a read operation on the keys path was *ever* supported in either [0.3.0](https://github.com/hashicorp/vault/blob/v0.3.0/builtin/logical/ssh/path_keys.go#L29) where SSH first appeared or in [0.3.1](https://github.com/hashicorp/vault/blob/v0.3.1/builtin/logical/ssh/path_keys.go#L29)

**Comment by ekristen** [comment]
Hey @jefferai so I did some digging, I was an early user of vault, and it I built my one vault that supports this still a few commits before v0.3.0-rc and it did support this behavior.

Looks like you removed the reading of keys in commit https://github.com/hashicorp/vault/commit/fa53293b7b7794469355730c14e98c4cf2ba4c6c so that solves that mystery. :)

Thanks.
