### ISSUE TITLE
Vault unresponsive after becoming leader

### ISSUE THREAD

**Issue by iljaweis** [hashicorp/vault#1788]
Vault 0.5.2 (but reproducible with Vault 0.6.1)
Consul 0.6.4
RHEL 7.2 VMs, 4 cores, 4GB RAM

HA setup with consul backend (3 server nodes) and 3 loadbalanced vaults; this generally works.

When one of the vault becomes the leader (after restarts, or another one stepping down), the API is unresponsive to the point that the whole service is unavailable, with the local consul and vault processes consuming CPU.

After, in our case, 10 minutes, vault becomes available and works without any further problems. This is reproducible with Vault 0.6.1 and the same data.

Here's the logfile:

```
Aug 23 20:35:30 vault-develop03 vault: 2016/08/23 20:35:30 [INFO] core: acquired lock, enabling active operation
Aug 23 20:35:30 vault-develop03 vault: 2016/08/23 20:35:30 [INFO] core: post-unseal setup starting
Aug 23 20:35:30 vault-develop03 vault: 2016/08/23 20:35:30 [INFO] core: mounted backend of type generic at secret/
Aug 23 20:35:30 vault-develop03 vault: 2016/08/23 20:35:30 [INFO] core: mounted backend of type cubbyhole at cubbyhole/
Aug 23 20:35:30 vault-develop03 vault: 2016/08/23 20:35:30 [INFO] core: mounted backend of type system at sys/
Aug 23 20:35:30 vault-develop03 vault: 2016/08/23 20:35:30 [INFO] core: mounted backend of type generic at <PATH>
Aug 23 20:35:30 vault-develop03 vault: 2016/08/23 20:35:30 [INFO] core: mounted backend of type generic at <PATH>
Aug 23 20:35:30 vault-develop03 vault: 2016/08/23 20:35:30 [INFO] core: mounted backend of type generic at <PATH>
Aug 23 20:35:30 vault-develop03 vault: 2016/08/23 20:35:30 [INFO] core: mounted backend of type generic at <PATH>
Aug 23 20:35:30 vault-develop03 vault: 2016/08/23 20:35:30 [INFO] core: mounted backend of type generic at <PATH>
Aug 23 20:35:30 vault-develop03 vault: 2016/08/23 20:35:30 [INFO] core: mounted backend of type generic at <PATH>
Aug 23 20:35:30 vault-develop03 vault: 2016/08/23 20:35:30 [INFO] core: mounted backend of type generic at <PATH>
Aug 23 20:35:30 vault-develop03 vault: 2016/08/23 20:35:30 [INFO] core: mounted backend of type generic at <PATH>
Aug 23 20:35:30 vault-develop03 vault: 2016/08/23 20:35:30 [INFO] rollback: starting rollback manager
Aug 23 20:45:30 vault-develop03 vault: 2016/08/23 20:45:30 [INFO] expire: restored 222567 leases
Aug 23 20:45:30 vault-develop03 vault: 2016/08/23 20:45:30 [INFO] core: post-unseal setup complete
```

I sniffed the consul request vault performs during the time it's unavailable and it's all requests like
```
GET /v1/kv/vault/sys/expire/id/auth/token/create/<TOKEN> HTTP/1.1
...
GET /v1/kv/vault/sys/expire/id/auth/cert/login/<TOKEN> HTTP/1.1
...
```

We're indeed storing many tokens. This is a rough count of the key/values stored in consul:
```
1145141      vault/sys
749703      vault/sys/token
394925      vault/sys/expire/id
394925      vault/sys/expire/id/auth
394925      vault/sys/expire
341227      vault/sys/token/accessor
341035      vault/sys/token/id
202985      vault/sys/expire/id/auth/cert
202985      vault/sys/expire/id/auth/cert/login
97513      vault/sys/expire/id/auth/ldap/login
97513      vault/sys/expire/id/auth/ldap
96280      vault/sys/expire/id/auth/ldap/login/vmp
94427      vault/sys/expire/id/auth/token
94424      vault/sys/expire/id/auth/token/create
67440      vault/sys/token/parent
```

We only have very few actual secrets compared to that.

**Comment by jefferai** [comment]
When a Vault node transitions to active state it needs to read all of the existing leases (for dynamically generated secrets and tokens -- the values under `sys/expire`) out of Consul before it can begin serving. You have a very large number of tokens that have been issued, so you're seeing Vault wait while it makes 222567 requests to Consul to load up the expiration information.

Usually when we see this it's due to a combination of two things:

1) Clients reauthenticating rather then reusing existing tokens, creating another expiration entry. This is often because a developer simply coded in an "auth to Vault; fetch secret" routine into their application rather than authenticating and storing the given token for reuse.
2) Long token expiration times compared to the actual lifetimes of the clients

There are a couple of ways to avoid this. First -- have clients reuse tokens instead of reauthenticating; if for some reason this isn't possible, if a client is shutting down, they should revoke their token so that the entry isn't kept around.

Second, analyze your actual needed TTLs for tokens and adjust them accordingly. The default is 30 days; if your clients are reauthenticating every two minutes, you're going to have a lot of leases sitting around which must be tracked even though they'll be unused for the vast majority of their lifetime.

You can use the `sys/revoke-prefix` endpoint to expire things early, but it's a bit of a heavy hammer. You could also use the new accessor listing functionality in 0.6.1 (see the token auth backend docs) to get information about the tokens and revoke them one by one based on some logic that makes sense for you (e.g. time since creation, if you know that they're not being reused).

**Comment by iljaweis** [comment]
Thank you for your help! We will reconsider how we create and use tokens to avoid storing so many.
