### ISSUE TITLE
Behavior of userfilter in ldap authtype

### ISSUE THREAD

**Issue by enspritz** [hashicorp/vault#17898]
**Describe the bug**
Our use-case with the `ldap` authtype is to allow only those LDAP accounts that are members of the admin group to authenticate with Vault, and the `userfilter` config setting seems like the perfect place to encode enforcement. However, we have found that `userfilter` seems inert in our workflow.

The [documentation](https://developer.hashicorp.com/vault/docs/auth/ldap#userfilter) clearly states:
```
The user search filter can be used to restrict what user can attempt to log in.
```
Great, sounds perfect for our use case, and is fully aligned with the analogous setting in a vast array of other popular tooling. We are compelled to take this description at face value. Here is our actual config setting, confirmed as working properly in other LDAP tooling (substituting `UserAttr` and `Username` as appropriate):
```
vault write auth/ldap/config \
  userfilter="(&(objectClass=person)({{.UserAttr}}={{.Username}})(memberOf=cn=admin,ou=groups,dc=acme,dc=com))" \
  ...
```

Yet when we moved to produce a negative test case in an attempt to confirm proper operation, we discovered that `userfilter` seems to have no observable impact on who can authenticate. Even an LDAP search filter as utterly scandalous as the following doesn't hinder authentication:
```
vault write auth/ldap/config \
  userfilter="(objectClass=tortoise)" \
  ...
```
So we're not sure what `userfilter` is meant to do and what it actually does! Have we overlooked something?

(Note that the tortoise example above produces a warning from Vault but otherwise makes no difference)

**Environment:**
* Vault Server Version (retrieve with `vault status`): Vault v1.12.1
* Vault CLI Version (retrieve with `vault version`): Vault v1.12.1
* Server Operating System/Architecture: Linux, OpenLDAP 2.4

**Comment by bradjoss** [comment]
Any progress on this, I am having the exact same symptoms!

USER_FILTER1="(&(objectCategory=Person)({{.UserAttr}}={{.Username}})(memberOf=CN=**NO_ACCSES_GROUP**,OU=...com))"
USER_FILTER2="(&(objectCategory=Person)({{.UserAttr}}={{.Username}})(memberOf=CN=**GOOD_GROUP**,OU=...com))"

vault write auth/ldap/config \
    userfilter="${USER_FILTER#}" \
    userattr="sAMAccountName" \
    ...

Both of those allow me in, even though I am not in NO_ACCSES_GROUP.
To ensure the filter expressions were correct, I tested in powershell with:
Get-ADUser -LDAPFilter "..."

Sub'ing out the {{.UserAttr}}={{.Username}} for sAMAccountName=MY_LOGIN.
In the good case, I get the correct record back, in the bad case, no record, which is correct.
I agree, it seems like Vault is ignoring this property. :(

Environment:
OS = Red Hat Enterprise Linux Server 7.9 (Maipo)
Vault Version                 1.13.1
Vault Build Date              2023-03-23T12:51:35Z

**Comment by raymonstah** [comment]
I'm curious if @bradjoss and @enspritz, are you able to run an `ldapsearch` command with the same filter and have it return the expected results?

For example:
```
ldapsearch -x -b "dc=example,dc=org" -H ldap://localhost:1389 "<YOUR_FILTER_HERE>"
```

**Comment by enspritz** [comment]
@raymonstah  yes, `ldapsearch` returns the expected results, as does a wide variety of other tooling we have around here. Moreover, this query is copied from / patterned after the configurations of many the other software configs.

**Comment by bradjoss** [comment]
@raymonstah - I was unable to perform the test with ldapsearch on the linux server hosting vault for technical reasons.  However, I do believe the powershell commands I noted do the exact same thing of testing the filter expression, no?

**Comment by raymonstah** [comment]
Unfortunately I'm having a difficult time reproducing the issue you're seeing. I have a LDAP server running in a docker container with 'Alice' being a part of the 'group01' group.

```
vault write auth/ldap/config \
...
userfilter="(&(objectClass=inetOrgPerson)({{.UserAttr}}={{.Username}})(!(memberOf=cn=group02,ou=users,dc=example,dc=org)))"
Success! Data written to: auth/ldap/config
```

Since they're _not_ part of the 'group02' group, I am able to successfully log in.

```
vault login -method=ldap username=alice
Password (will be hidden):
Success! You are now authenticated.
```

When I write the same userfilter, but negate the last condition, I get the expected login failure response:

```
vault write auth/ldap/config \
...
userfilter="(&(objectClass=inetOrgPerson)({{.UserAttr}}={{.Username}})((memberOf=cn=group02,ou=users,dc=example,dc=org)))"
Success! Data written to: auth/ldap/config
```

```
vault login -method=ldap username=alice
Password (will be hidden):
Error authenticating: Error making API request.

URL: PUT http://127.0.0.1:8200/v1/auth/ldap/login/alice
Code: 400. Errors:

* ldap operation failed: failed to bind as user
```

This is on Vault v1.13.1

@enspritz I've also tried the userfilter you specified in the original post, and it correctly prevents me from logging in as well.

I'm also curious if your server debug logs show anything helpful. If you enable debug logging, the search filter should be logged. That search filter is just passed along to the library, which performs the [search](https://github.com/hashicorp/vault/blob/cc570c11bbc63bd3810a56d8b2ec9e09902ca654/sdk/helper/ldaputil/client.go#L121-L131).

**Comment by bradjoss** [comment]
Tried a few things...
1) I tried an Active Directory group that was of group type "Security".  The previous groups I was trying were "Distribution".  Same effect, the security group I used (that I am not a part of) still allowed me in.

2) @enspritz, is your LDAP instance Active Directory? Or other?, Same question to @raymonstah?  If @enspritz and I are AD, and @raymonstah is not -- could it be an issue with Vaults LDAP relationship/schema in regards to Active Directory?

3) @raymonstah, I have (tried to) enable debug logging as below:
log_level = "debug"
log_format = "standard"
log_file = ".../logs/vault.out.log"

I do see [DEBUG] entries in the log, but I don't seem to find that log entry (or any meaningful LDAP entries):

cat vault.out.log | grep -i 'discovering' <== No mathces
cat vault.out.log | grep -i 'ldap'
2023-08-03T13:02:48.152-0700 [INFO]  core: successfully mounted: type=ldap version="v1.13.1+builtin.vault" path=ldap/ namespace="ID: root. Path: "
2023-08-03T13:02:48.154-0700 [INFO]  core: successfully mounted: type=ldap version="v1.13.1+builtin.vault" path=ldap/ namespace="ID: root. Path: "

Is there another log setting I can enable to toggle on better logging in this matter?

**Comment by raymonstah** [comment]
For question 2, I'm using the [bitnami/openldap](https://hub.docker.com/r/bitnami/openldap/) container to run my LDAP server.

For 3, that appears correct. There's more information [here](https://developer.hashicorp.com/vault/tutorials/monitoring/troubleshooting-vault#vault-server-logs) on how to enable it.

Once enabled, you should see logs like this when making performing a login.
```
2023-08-03T11:37:45.514-0700 [DEBUG] auth.ldap.auth_ldap_5f924248: discovering user: userdn="ou=users,dc=example,dc=org" filter="(&(objectClass=inetOrgPerson)(uid=alice)(memberOf=cn=group01,ou=users,dc=example,dc=org))"
2023-08-03T11:37:45.516-0700 [DEBUG] identity: refreshing external group memberships: entity_id=409054d5-a460-dbf5-80b9-8e9fad68b1a9 group_aliases=["mount_accessor:\"auth_ldap_5f924248\" name:\"group01\""]
2023-08-03T11:38:19.670-0700 [DEBUG] auth.ldap.auth_ldap_5f924248: compiling search filter: search_filter="(&(objectClass=inetOrgPersonx)({{.UserAttr}}={{.Username}})(memberOf=cn=group01,ou=users,dc=example,dc=org))"
2023-08-03T11:38:19.671-0700 [DEBUG] auth.ldap.auth_ldap_5f924248: discovering user: userdn="ou=users,dc=example,dc=org" filter="(&(objectClass=inetOrgPersonx)(uid=alice)(memberOf=cn=group01,ou=users,dc=example,dc=org))"
2023-08-03T11:38:19.679-0700 [DEBUG] auth.ldap.auth_ldap_5f924248: error getting user bind DN: error="LDAP search for binddn 0 or not unique"
```

**Comment by bradjoss** [comment]
@raymonstah - Thanks for all your help on this!

Yah, I enabled it correctly as best I can tell, and still see no login details in the logs.  I went so far as to nuke the logging folder to ensure I was not getting files mixed up!  I set it to trace this time around, and in the startup output, that seems set correctly:

              Go Version: go1.20.1
...
               Log Level: trace
                   Mlock: supported: true, enabled: true
           Recovery Mode: false
                 Storage: raft (HA available)
                 Version: Vault v1.13.1, built 2023-03-23T12:51:35Z
             Version Sha: 4472e4a3fbcc984b7e3dc48f5a8283f3efe6f282

Is there a reason we can think of that I would not be seeing any LDAP logging with these settings as they are?

If it helps, here is an edited version of this output:
vault read  auth/ldap/config

Key                             Value
---                             -----
anonymous_group_search          false
binddn                          CN=svc-vault,...,DC=com
case_sensitive_names            false
deny_null_bind                  true
discoverdn                      false
groupattr                       cn
groupdn                         OU=Users,...,DC=com
groupfilter                     (|(memberUid={{.Username}})(member={{.UserDN}})(uniqueMember={{.UserDN}}))
insecure_tls                    false
request_timeout                 90
starttls                        false
tls_max_version                 tls12
tls_min_version                 tls12
token_bound_cidrs               []
token_explicit_max_ttl          0s
token_max_ttl                   8h
token_no_default_policy         false
token_num_uses                  0
token_period                    0s
token_policies                  []
token_ttl                       8h
token_type                      default
upndomain                       ....com
url                             ldaps://....com
use_pre111_group_cn_behavior    false
use_token_groups                false
userattr                        samaccountname
userdn                          OU=...,DC=com
userfilter                      (&(objectClass=Person)({{.UserAttr}}={{.Username}})(memberOf=DENY_GROUP,...,DC=com))
username_as_alias               false

**Comment by raymonstah** [comment]
@bradjoss I'm not sure if this is what you're running into, but it might be worth a try: https://developer.hashicorp.com/vault/tutorials/monitoring/troubleshooting-vault#not-finding-the-server-logs

**Comment by bradjoss** [comment]
Humm...

I do see logs in the expected location based on the configuration in the server config .hcl file.  I just don't see the debugging entries related to LDAP, but I do see other debug entries, e.g.

2023-08-03T13:36:34.235-0700 [TRACE] core: adding write forwarded paths: paths=[]
2023-08-03T13:36:34.235-0700 [INFO]  core: successfully mounted: type=ldap version="v1.13.1+builtin.vault" path=ldap/ namespace="ID: root. Path: "
2023-08-03T13:36:34.236-0700 [INFO]  core: restoring leases
2023-08-03T13:36:34.295-0700 [TRACE] mfa: loading login MFA configurations
2023-08-03T13:36:34.295-0700 [TRACE] mfa: methods collected: num_existing=0
2023-08-03T13:36:34.295-0700 [TRACE] mfa: configurations restored: namespace="" prefix=login-mfa/method/
2023-08-03T13:36:34.295-0700 [TRACE] mfa: loading login MFA enforcement configurations
2023-08-03T13:36:34.295-0700 [TRACE] mfa: enforcements configs collected: num_existing=0
2023-08-03T13:36:34.295-0700 [TRACE] mfa: enforcement configurations restored: namespace="" prefix=login-mfa/enforcement/
2023-08-03T13:36:34.295-0700 [INFO]  core: starting raft active node
2023-08-03T13:36:34.295-0700 [INFO]  storage.raft: starting autopilot: config="&{false 0 10s 24h0m0s 1000 0 10s false redundancy_zone upgrade_version}" reconcile_interval=0s
2023-08-03T13:36:34.295-0700 [DEBUG] core.undo-log-watcher: starting undo log watcher
2023-08-03T13:36:34.295-0700 [DEBUG] core: request forwarding setup function
2023-08-03T13:36:34.295-0700 [DEBUG] core: clearing forwarding clients
2023-08-03T13:36:34.295-0700 [DEBUG] core: done clearing forwarding clients
2023-08-03T13:36:34.295-0700 [DEBUG] core: leaving request forwarding setup function
2023-08-03T13:36:34.296-0700 [DEBUG] storage.raft.autopilot: autopilot is now running
2023-08-03T13:36:34.296-0700 [DEBUG] storage.raft.autopilot: state update routine is now running

Our instance is not started via systemd service (I double checked to make sure).

I do have a /var/logs/messages file with some vault entries in them, but all are written by ansible, which we use to deploy and configure our vault instance(s).

Maybe the elephant in the room...  We are not using Vault Enterprise in this instance.  While I did not see in the docs that user-filtering is only available at that level, could that be a root cause?

I am happy to dig in other directions as you see fit! :-)

**Comment by raymonstah** [comment]
I don't think it's related to not using Vault Enterprise, since I'm testing from Vault OSS. However, I'm running in dev mode, and receive my logs through the console. Are you using a multi-node setup?

**Comment by bradjoss** [comment]
In all other environments, yes, but this one we are currently working in, no (it's our pre-dev env).  Here is a redacted config from that server.  We 

listener "tcp" {
  address          = "127.0.0.1:8200"
  cluster_address  = "OUR_SERVER:8201"
  tls_disable      = "true"
}

cluster_addr  = "https://OUR_SERVER:8201"
api_addr = "https://OUR_SERVER:8200"

listener "tcp" {
  address          = "OUR_SERVER:8200"
  tls_disable      = "false"
  tls_cert_file = "/folder/OUR_SERVER-cert.pem"
  tls_key_file = "/folder/OUR_SERVER-key.pem"
  tls_client_ca_file = "/folder/CERT.pem"
  tls_require_and_verify_client_cert = "false"
  tls_disable_client_certs = "true"
}

storage "raft" {
  node_id = "OUR_SERVER"
  path    = "/vault/data"
}

disable_mlock = "false"
ui = "true"
log_level = "info"
log_format = "standard"
log_file = "/vault/logs/vault.out.log"
log_rotate_max_files = "5"
log_rotate_bytes = "10485760"

default_lease_ttl = "1d"
max_lease_ttl = "7d"

default_lease_ttl = "1d"
max_lease_ttl = "7d"

Our startup line is:

nohup vault server -config=${VAULT_HOME}/config/vault_server.hcl 2>/dev/null >${VAULT_HOME}/logs/nohup_stdout.out &

We are not using exported system variables to configure our server at this time.

**Comment by raymonstah** [comment]
Anything interesting in the `nohup_stdout.out` logs?

Aside from that, two things that stood out:
1. the log_level is reverted back to "info" instead of "debug"
2. Could some logs be lost due to being redirected to `/dev/null`? Could you try running it without `nohup`? `vault server -config=${VAULT_HOME}/config/vault_server.hcl`

**Comment by bradjoss** [comment]
BINGO!  We were missing a LOT of logging with that /dev/null (the dev who put it in there had a long comment as to why, but meh, removed, we have details!)

vault server -config=${VAULT_HOME}/config/vault_server.hcl > ${VAULT_HOME}/logs/nohup_stdout.out 2> ${VAULT_HOME}/logs/nohup_stderr.out &

cat nohup_stderr.out
...
# Me logging out...
2023-08-03T15:50:36.113-0700 [INFO]  expiration: revoked lease: lease_id=auth/ldap/login/ME/h7ea50c859ea3e5e2f2b23b0581bc1d7d059073efe0284c11f54d00481f800fc8

2023-08-03T15:50:38.803-0700 [DEBUG] auth.ldap.auth_ldap_0ce77b88: user binddn fetched: username=ME binddn=ME@CO
# This seemed like a normal GET USER ldap query.  It was a little odd that it didn't use my userattr of sAMAccountName, but it found the correct user so I won't sweat it.
2023-08-03T15:50:38.810-0700 [DEBUG] auth.ldap.auth_ldap_0ce77b88: searching upn: userdn="OU=...DC=com" filter="(userPrincipalName=ME@CO)"
# This is our current group filter, and it did seem to resolve correclty to expected groups.
2023-08-03T15:50:38.812-0700 [DEBUG] auth.ldap.auth_ldap_0ce77b88: compiling group filter: group_filter="(|(memberUid={{.Username}})(member={{.UserDN}})(uniqueMember={{.UserDN}}))"
2023-08-03T15:50:38.812-0700 [DEBUG] auth.ldap.auth_ldap_0ce77b88: searching: groupdn="OU=..."
2023-08-03T15:50:39.125-0700 [DEBUG] auth.ldap.auth_ldap_0ce77b88: groups fetched from server: num_server_groups=36 ...
2023-08-03T15:50:39.125-0700 [DEBUG] auth.ldap.auth_ldap_0ce77b88: adding local groups: num_local_groups=0 local_groups=[]

**# However, no where did I see it try to apply the userfilter?**

2023-08-03T15:50:39.126-0700 [DEBUG] identity: refreshing external group memberships: entity_id=...

Our config like looks as follows:

local MEMBER_OF="CN=A_VALID_GROUP_DN,...,${BASE_DN}"
local USER_FILTER="(&(objectClass=Person)({{.UserAttr}}={{.Username}})(memberOf=${MEMBER_OF}))"

 vault write auth/ldap/config \
    url="${LDAP_ADDR}" \
    upndomain="${UPN_DOMAIN}" \
    **userfilter="${USER_FILTER}" \**
    userattr="sAMAccountName" \
    userdn="${USER_DN}" \
    binddn="${BIND_DN}" \
    bindpw="${BIND_PW}" \
    groupdn="${GROUP_DN}" \
    groupfilter="${GROUP_FILTER}" \
    groupattr="cn" \
    token_ttl="${LDAP_AUTH_TOKEN_TTL}" \
    token_max_ttl="${LDAP_AUTH_TOKEN_TTL}" \
    certificate=@${CERTIFICATE};

Is there something we are doing wrong in setting our user filter?

**Comment by raymonstah** [comment]
Ah interesting! Based on the [code here](https://github.com/hashicorp/vault/blob/cc570c11bbc63bd3810a56d8b2ec9e09902ca654/sdk/helper/ldaputil/client.go#L156) it seems like we only render the usersearch filter when both `binddn` and `bindpass` are non empty, or when `discoverdn` is set.
In your last comment, it appears that you're using `bindpw` instead of `bindpass`. That might be an issue. And if that doesn't work, can you try setting `discoverdn=true`?

**Comment by bradjoss** [comment]
JOY! RAPTURE!

Error
Authentication failed: ldap operation failed: failed to bind as user

I think the trick was just changing to **bindpass**="${BIND_PW}"!

Unfortunately, I have locked myself out! :-)  (which is a good problem to have right now!)
I will try with the positive pass testing and let you know tomorrow.
Thanks a TON for all your help!

**Comment by enspritz** [comment]
Thanks for looking into this @bradjoss @raymonstah 

Here is the Vault config:
```
vault write auth/ldap/config \
  url="ldap://1.2.3.4" \
  groupattr="memberOf" \
  groupdn="ou=groups,dc=acme,dc=com" \
  groupfilter="(objectClass=groupOfUniqueNames)" \
  userattr="uid" \
  userdn="ou=accounts,dc=acme,dc=com" \
  userfilter="(&(objectClass=person)({{.UserAttr}}={{.Username}})(memberOf=cn=admin,ou=groups,dc=acme,dc=com))" \
  insecure_tls=true
```

Perhaps I need to be disabused of a faulty interpretation of the [docs](https://developer.hashicorp.com/vault/docs/auth/ldap), but I am expecting that (with the below config) Vault will first attempt to authenticate to LDAP by assembling the binding principal from the supplied config params + the given CLI username arg. For example:

```
vault login -method=ldap username=me-of-course
```

Here the binding DN would be `uid=me-of-course,ou=accounts,dc=acme,dc=com`. Then, with the correct password provided and authentication established, that user then has permission to do the group search, and Vault will conduct that search as the newly-bound principal to determine whether the principal is welcome in Vault or not, based on the supplied `groupattr` et. al. Vault config params above.

**Comment by raymonstah** [comment]
@enspritz since you didn't specify a `binddn/bindpass` or `discoverdn` in your config, Vault skips over the `userfilter` search. Here's a rough outline of what the code does today, based on my understanding:

1. Dial LDAP to establish a connection
2. Get the user bind DN given the username, in your case `me-of-course`. The [code](https://github.com/hashicorp/vault/blob/cc570c11bbc63bd3810a56d8b2ec9e09902ca654/sdk/helper/ldaputil/client.go#L168-L173) assumes the bind DN can be derived immediately, without performing a user search request to the LDAP server, which means that the `userfilter` is completely ignored.
3. Once the bind DN is established, perform a bind request against the LDAP server (the actual authentication).
4. Once authenticated, fetch groups.
5. Retrieve policies based on groups.

**Comment by enspritz** [comment]
Thanks @raymonstah @bradjoss , looks like we are going with the `binddn/bindpass` approach. And yes, the clarify docs ;)
