### ISSUE TITLE
Vault agent is not passing errors to vault clinet

### ISSUE THREAD

**Issue by matusb** [hashicorp/vault#17900]
**Describe the bug**
I'm not sure if this is an issue is related to #17792 and HTTP 500 are not passed to client via agent, but here is what I'm experiencing 

Background: We are using multiple Vault clusters in our environment, often switching between Vault servers, connecting to each vi   multiple Vault agent installed on separate server (bastion host). We authenticate to vault using LDAP.

When I authenticate to First Vault Server my token is written in .vault-token and everything works as expected. However, whenever I connect to Second Vault Server in different environment, every operation will timeout with `context deadline exceeded` instead of getting `invalid token` or similar error. Deleting .vault-token and re-authenticating  against Second Vault Server works, but is not intuitive for users. Expecting the error to be passed from Vault server <> Vault agent <>  Client. 

**To Reproduce**
1. Authenticate to Vault Server (obtain ~/.vault-token) 
2. Connect to different Vault Server via Vault Agent and execute any operation   (example: `vault token lookup`)
3. command will hang and eventually times out with `Error looking up token: context deadline exceeded`

**Expected behavior**
expected error to be returned to client.
Error I get with the same token directly connecting to Vault Server (not using agent)
```
Error looking up token: Error making API request.

URL: GET https://vault.server/v1/auth/token/lookup-self
Code: 500. Errors:

* token mac for token_version:1  hmac:"xxxxxx"  token:"xxxx" is incorrect: err %!w(<nil>)
```

**Environment:**
* Vault Server Version (retrieve with `vault status`): 1.10.3
* Vault CLI Version (retrieve with `vault version`): Vault v1.10.3 (af866591ee60485f05d6e32dd63dde93df686dfb)
* Server Operating System/Architecture: Linux

**Comment by hghaf099** [comment]
Thanks for filing this ticket. I cannot reproduce the issue as described. Would you please provide more details of your setup? For instance, it is mentioned that `However, whenever I connect to Second Vault Server in different environment, every operation will timeout with context deadline exceeded instead of getting invalid token or similar error. ` So, is this the same Vault agent which connects to the second Vault server? If so, how do you do that? Or is it the case that a new vault agent with the old config is started but pointing to the second Vault server? And, is the second Vault server in the same cluster or in a separate cluster? Would you be able to provide vault logs from the server that `context deadline exceeded ` is returned? Thanks for you patience with the above questions.

**Comment by matusb** [comment]
already fixed in latest version
