### ISSUE TITLE
cannot revoke blank token

### ISSUE THREAD

**Issue by bkrodgers** [hashicorp/vault#1790]
I've noticed these messages in my logs every time a node takes over as active.  I get more than 50 of them for both github and cert (those are the only two auth backends I use right now)

[ERR] expire: failed to revoke lease lease_id=auth/cert/login/f3c355ab367324de78bea8d4b6e77d6bf8a13c9e error=failed to revoke token: cannot revoke blank token

Is this something Vault can clean up on its own in a future version?  In the meantime, is there something I can or should do in consul to manually take care of them?

**Comment by jefferai** [comment]
Hi @bkrodgers ,

One thing I'm curious on, because I know you've been running Vault for a long while -- is the number of these *increasing*?

Basically, I'm wondering if this is something left over from some bug a while back, or an active bug. Unfortunately, even if they are increasing that doesn't mean it's an active bug, because it could just be a previous token that is only now expiring. But still.

Either way there isn't anything Vault can do alone because we don't want to code in paths where a revocation failure is acceptable, *but* you should be able to do one of the following as an administrator:

* Use the `sys/revoke-force` endpoint. I'm not sure that this will work in this particular situation, but I think it will. You can use the entire lease as the "prefix" to force-revoke and it will only act on that single lease.

* Simply manually delete those entries from Consul

I'd also be interested in knowing if these leases have ever been renewed or not.

**Comment by bkrodgers** [comment]
So I'm not sure if they're growing or how old they are.  However, tell me if I'm inferring this right:

`curl <consul>/v1/kv/vault/?recurse | jq '.[].CreateIndex' | sort -n` tells me that my max `CreateIndex` is `5321369`.

Spot checking consul with `curl localhost:8500/v1/kv/vault/?recurse | jq . | grep -A 5 -B 2 <one-of-the-ids>`, I find each of them has both a `vault/sys/expire/id/auth/cert/login/<id>` and `<vault/sys/token/id/<id>` key.  

Create indexes I've found on these bad records in my spot checking are 4247970, 4247672, 4247905, 4247533.  I can parse the logs to check them all, but am I right to assume that this create index is a number that starts at 1 and is incremented sequentially?  If so, then it would seem to indicate that these are both fairly old (essentially > a million records ago) and were grouped together roughly in a common time period (since they all are in the 4247XXX range).  Does that sound right?

I don't know if the leases would have been renewed, but I would suspect some were.

**Comment by bkrodgers** [comment]
I parsed everything, and it looks like there are a few ranges.  The lowest is 4243998, and the highest is 5257706.  So with my overall highest CreateIndex at 5321369, it looks like it has happened within the last ~63K records.

**Comment by jefferai** [comment]
I honestly don't know whether those assumptions are true in Consul, although I can bring someone in to look at them if needed.

You're on 0.6.1 right? Maybe at this point it's worth simply removing those entries and seeing if the problem recurs. I know you're a long time user and it's not impossible this is related to a fixed bug from a while back.

**Comment by bkrodgers** [comment]
Yeah, I'm on 0.6.1. And you're right, this install started on 0.2, I think.  I can try taking them out and seeing if we get any new ones. 

I tried `curl -XPUT -H "X-Vault-Token: $(cat ~/.vault-token)" https://<vault-server>/v1/sys/revoke-force/auth/cert/login/<key>` and got a 204, but I still see the entries in consul.  Is that what you had in mind?

 Or I can just do it in consul, that's no big deal too.  I assume I should delete both `vault/sys/expire/id/auth/<auth-method>/login/<key>` and `vault/sys/token/id/<key>` for each key it's complaining about in the logs?

**Comment by jefferai** [comment]
The revoke-force command should delete the lease (under `vault/sys/expire...`) but won't touch the token, since the problem appears to basically be the lease information not corresponding to the token anymore. So the tokens at least you'll have to delete manually. Sorry...

**Comment by bkrodgers** [comment]
It doesn't appear to have deleted either, but no worries.  I already wrote the logic to find them all in consul for the research above last night, so it's no big deal to change it to delete the two entries for each.

**Comment by jefferai** [comment]
Blegh. Well...it's designed for a different problem. :-)

**Comment by bkrodgers** [comment]
OK, cleared things out and I don't see that message anymore when a new node takes over.  I'll keep an eye on it over the next days/weeks and report back if it returns.

In case anyone else comes across this ticket and needs to do this, here's more or less what I did.  Because I was experimenting as I go, I did more intermediate steps...you could combine much of this, obviously.

```
# Change to whatever you need to do to get to your vault logs
journalctl -ru vault | grep blank > blank
cat blank | sed -n 's/.*login\/\([0-9a-z]*\).*/\1/p' > blank1
sort blank1 > blank2
uniq blank2 > blank3

for item in $(cat blank3) ; do 
consulKeys=$(curl <consul-addr>/v1/kv/vault/?recurse -s | jq -r ".[] | select(.Key | contains(\"$item\")) | .Key"); 
  for consulKey in $consulKeys ; do
    curl -XDELETE <consul-addr>/v1/kv/$consulKey
  done
done
```

**Comment by jefferai** [comment]
Going to close this for now -- but let me know and/or reopen if more of these pop up!

**Comment by rikwasmus** [comment]
FWIW: I'm currently seeing this issue with Consul 0.6.3, with Vault versions deployed being: 0.3.1, 0.5.2, 0.6.0, 0.5.2, 0.6.1 (in that order if memory serves right, there was indeed a downgrade in there). As Consul dies horribly if we query it with vault?recurse due to how full it is, but querying it with `?keys` instead (which resulted in an a  61MB json file) and walking through that we can clear it. Now, still to figure out why there are 300k items under `vault/sys/expire/id/auth/app-id/login/*`, but that might be an application issue rather than a Vault or Consul issue.

**Comment by jefferai** [comment]
The 300k entries are because you have 300k active tokens issued via the app-id backend. Probably you are constantly reauthenticating rather than reusing tokens, and/or you need to change the TTL of the tokens you are issuing via app-id.

**Comment by rikwasmus** [comment]
Yup, in a dynamic Dockers-in-Marathon environment it's silly to let the AppID TTL stay at 30 days (especially in a very dynamic staging or dev environment which understandably has a lot more start ups & exits compared to production), I'm currently testing there with an AppID TTL with 30 minutes instead of the default max TTL of 30 days which should be OK.  

But, this issue was about the empty token thingamajig: I'm happy to report I haven't seen any reappearance of those running 0.6.1 since the manual purge from Consul yet, and as stated, if others run into trouble downloading / rescursing an entire Consul KV store, just fetching the keys and searching in those what to delete should suffice.
