### ISSUE TITLE
[Req] Implement GET on /pki/issue/:name/latest and /pki/issuer/:issuer_ref/issue/:name/latest

### ISSUE THREAD

**Issue by boeboe** [hashicorp/vault#18060]
**Is your feature request related to a problem? Please describe.**

Istio users that want to leverage Vault PKI, will typically use the `vault-agent-init` sidecar to bootstrap the istio control plane (istiod pods) with the necessary key material:
 - private intermediate CA key
 - public intermediate CA cert
 - root CA cert
 - cert chain (from intermediate CA cert all the way to root cert, all appended)
 
This process is documented [here](https://istio.io/latest/docs/tasks/security/cert-management/plugin-ca-cert/#plug-in-certificates-and-key-into-the-cluster).

When we want to use the Vault pki API, we can leverage the `/pki/issue/:name` and `/pki/issuer/:issuer_ref/issue/:name` endpoints that provide a POST method to generate new intermediate certificates.

The problem however, is that we do not want to generate a new certificate for every `istiod` pod restart or scale-up. Furthermore, the CA private key generated is not persisted within the API.

As a work-around, we use the secret kv backend to store this data.

**Describe the solution you'd like**

Implement HTTP GET on `/pki/issue/:name/latest` and `/pki/issuer/:issuer_ref/issue/:name/latest` which would return the latest the private CA key, public CA cert, root cert and cert chain. When a intermediate certificate rotation is needed, an out-of-band process (cicd pipeline or service portal) can leverage the POST method to issue a new cert/key pair. The latest issued certificate should be easily retrievable by certificate consumers (istio control plane pods as just one example).

**Describe alternatives you've considered**

Right now we issue the cert/key and store them in vault secret kv, which seems like double work/storage.

**Explain any additional use-cases**

An system where multiple certificate consumers need to sync on a common intermediate certificate. Kubernetes pods that require an intermediate certificate is a typical use case.

**Additional context**

Also posted this question [here](https://discuss.hashicorp.com/t/vault-as-pki-for-istio-intermediate-certs/47095?u=boeboe).

**Comment by cipherboy** [comment]
Curious, have y'all further considered simply reissuing the intermediates? Unless you're pinning to them, using an ECDSA intermediate and root cert would allow it to be reissued almost as fast as reading it from storage. In general, we suggest treating leaf certificates (which, from the root's perspective, an intermediate is) as just another resource that gets refreshed and rotated. Whenever the pod gets restarted, or a new node need the cert, or whatever, you could issue a new intermediate and not worry about it. Ideally, these CI/CD or service portal processes shouldn't be necessary, because nothing really cares about the contents of the intermediate being exactly the same: only that it chains up to the root.

The only case where this would be problematic is if you expect people to be able to get new leaves _under the same intermediate_, i.e., you're pinning intermediates. In this type of infra, I don't expect that to work well, and so I'd consider taking out the K/V step entirely. However, even if you're doing code signing, as long as the intermediate is still valid and can be distributed by the server nodes (missing chain components is a much bigger problem and out-of-band socialization of intermediates is not a good idea in general)... it should all work out (and the same leaf code signing cert could be re-signed under new intermediates if necessary). For a TLS traffic API, issuing new intermediates should really be a non-issue. When the (TLS server or client) gets a new leaf cert, it should get the new intermediate as well and send that along to its peer for validating the chain.

Fundamentally though, I think there's a misunderstanding here of how Vault's PKI works. The PKI engine isn't a generic secrets engine for certificates. It doesn't do anything with leaves. It really is an X509 Certificate Authority engine only.

Roles (which `/sign/:role` and `/issue/:role` use) are for leaf non-CA issuance only, and don't support signing intermediate CAs. One role is (generally) meant to be able to sign a multitude of non-identical certificates. This means the concept of a "latest" isn't useful, as sometimes you'd get e.g., a cert for `example.com` vs `www.example.com` vs `Steve Jobs` or whatever, _and you wouldn't have control over which name would be requested/returned.

I _think_ the correct feature request here would be for a path like `/pki/*/sign-intermediate/latest`, but again, you run into parallel paths problem: some people _do_ run multiple parallel, active intermediates under their root, so you'd want some name query capabilities, which is a bit hard to do well (performance-wise) in a simple K/V store. In X.509, there's no _real_ concept of a renewal that'd make this feasible: reissuance is indistinguishable from first issuance, given only one cert. Its only from an operational perspective that renewal and reissuance make sense, but then mostly boils down to issuance in the first place. In other words, its hard to tell (objectively, from a x509/code perspective) whether a given CSR to this endpoint is meant to be a replacement of an existing path (refreshing/renewing it) or a separate path altogether.

Furthermore, Vault presently doesn't persist (leaf) private key material at all! This would be Key Recovery and Archival (KRA) functionality, and we'd have fundamental safety issues of just... returning private key material to whoever asks. This is less than ideal, and we'd ideally want these operations to be approved by an admin (requiring another out-of-band process).

At the end of the day, considering the GET request to Vault K/V isn't much less involved than a POST request to PKI intermediate, I'd consider taking out the much more involved CI/CD pipelines and similar dashboards to _rotate_ the intermediate, and simply reissue it every time a node needs to fetch it again. This is safer from a key material distribution problem as well, as you'd know which node got a particular copy of the intermediate and thus (if private key material did leak) which node was compromised.

My 2c.

**Comment by cipherboy** [comment]
\o cool, glad to hear @boeboe! I'm going to go ahead and close this, but let me know in the future if this doesn't end up working out. 

I think the only tricky thing here is that some clients need more encouragement than others to send intermediate CAs, but generally it should be possible with all I've tried.
