### ISSUE TITLE
Improve documentation for ssh signed certificate based login

### ISSUE THREAD

**Issue by soumyadeep-paul-ibm** [hashicorp/vault#18119]
Hi Team, we are using HashiCorp vault to sign ssh certificate with vault CA and logging in to target. 
We are following the documentation https://developer.hashicorp.com/vault/docs/secrets/ssh/signed-ssh-certificates#client-ssh-authentication

In the documentation, point number 5 in the client-ssh-authentication section, the command for ssh is given as 
`ssh -i signed-cert.pub -i ~/.ssh/id_rsa username@10.0.23.5`
However, we realised this doesn't work in certain version of ssh, for example "openssh-server-8.0p1-6.el8_4.2.x86_64"

We had to explicitly provide `-o CertificateFile=signed_key` 

Also, in our opinion "CertificateFile" is more explicit and better way of providing the signed key. 
Request you to enhance the doc for the same.

**Comment by maxb** [comment]
I compiled OpenSSH 8.0p1 from source, curious if the CLI behaviour had in fact changed since that version. It accepts the form of the command in the Vault documentation as is, and works for me.

Therefore I suggest the proposed change not be applied, as it would make the command a user is told to type a fair bit longer and less memorable, and the reason for it not working in this particular report is not yet understood.

**Comment by soumyadeep-paul-ibm** [comment]
In our working and not working scenario: Both cases, the ssh client version is same 
openssh-clients-8.0p1-13.el8.x86_64 (RHEL 8.6) 

It is the opens server version that differs, 
- It works for server version openssh-server-8.0p1-13.el8.x86_64 (On RHEL 8.6)
- It doesn't work for server version openssh-server-8.0p1-6.el8_4.2.x86_64 (On RHEL 8.4)

From the logs, we see when a certificate is passed with "-i" flag, it treats as a key and not certificate. We get the error 
`debug3: mm_answer_keyallowed: publickey authentication test: RSA key is not allowed`
`debug3: mm_answer_keyallowed: publickey authentication test: ED25519 key is not allowed`

It works only when we pass "-o CertificateFile=signed_key"

**Comment by cipherboy** [comment]
Could this be a RHEL-only change fixed by a patch since?

**Comment by maxb** [comment]
It doesn't really sound right to me that what is effectively client-side behaviour, is varying with server-side version.

I wonder if the different server versions are in fact not the actual cause, and there is other configuration present in this client environment that causes different behaviour with different server names being connected to.

**Comment by cipherboy** [comment]
Yeah I agree, @maxb.

@soumyadeep-paul-ibm can you share complete debug logs both client and server side on both version pairs, along with their relevant execution parameters? The partial logs shared above don't point to any concrete issue and why passing `CertificateFile` option actually fixes it.

**Comment by maxb** [comment]
I built a CentOS 8.4 VM, which had the same package version of openssh-server as reported above. I tested the command as written in the current Vault docs with two `-i` options. It worked.

I'm pretty sure this is a local configuration issue in @soumyadeep-paul-ibm 's environment, rather than something linked to software versions, at this point.

**Comment by soumyadeep-paul-ibm** [comment]
Well, this is embarrassing. 
I too am unable to reproduce the problem on the same set of server/client VMs. 
It is working with two -i option as well as -o CertificateFile. Its a mystery to me why it didn't work earlier.  
My apologies and thanks a ton for your support.

**Comment by cipherboy** [comment]
Thanks all! I'll go ahead and close this with no changes to docs.
