### ISSUE TITLE
Inconsistent output for lists

### ISSUE THREAD

**Issue by sethvargo** [hashicorp/vault#1837]
Sometimes lists have commas, sometimes they do not. Example:

```
training@hashicorp > vault token-create -policy=base
Key             Value
---             -----
# ...
token_policies  [base default] # <-- no comma

training@hashicorp > vault auth 0b82c139-c54d-6234-52d9-67c6cd1b2152
Successfully authenticated! You are now logged in.
# ...
token_policies: [base, default] # <-- comma
```

I would personally vote for commas, since it just makes it clearer that this is, in fact, a list 😄

**Comment by jefferai** [comment]
The second `token_policies` output there is the inconsistent case -- instead of printing `%v` it's doing a `strings.Join`. In terms of consistency, the easy/fast thing to do would be to remove that, and have everything not use commas. Adding commas everywhere requires putting in type switches and special casing things.

**Comment by jefferai** [comment]
👍 on #1839; I think we can revisit overall formatting in another ticket or just in future conversations, but let's get this consistent for the moment.
