### ISSUE TITLE
mssql backend cannot connect when named instance of server is used, 500 Server Error.

### ISSUE THREAD

**Issue by rajanadar** [hashicorp/vault#1851]
Vault Version: 0.6.1
OS Version: Windows 10

Repro Steps:

1. have a MS SQL Server running on a named instance. (localhost\sqlexpress)
SQL Version is 2012
all TCP protocols etc. opened up in Client Protocols for MS SQL Server

2. have the connection string as: 

server=localhost\sqlexpress;port=1433;user id=sa;password=raja;database=master;app name=vault;

3. invoke the API to configure the connection: /mssql/config/connection
provide connection_string and also verify_connection as true.

Observed Error:

500 InternalServerError. {"errors":["1 error(s) occurred:\n\n* Unable to open tcp connection with host 'localhost:1433': dial tcp 127.0.0.1:1433: connectex: No connection could be made because the target machine actively refused it."]}

the weird thing is changing the connection string's server value to any random value (laala\sqlexpress), still gives the same error (cannot connect to 127.0.0.1:1433), when the API is invoked. it is almost like the provided server name is ignored. the issue doesn't happen if a normal instance is used. i.e. a default SQL server instance.. 

let me know if more information is needed.

**Comment by jefferai** [comment]
You can check with the authors of the go mssql library but from my perspective this is not a bug in Vault. It's not Vault's responsibility to resolve a database-specific connection string, the library does that.

FWIW the error makes it sound like you have a firewall or database configuration issue, since it says the connection was actively refused.
