### ISSUE TITLE
Unable to unseal vault

### ISSUE THREAD

**Issue by ilbarone87** [hashicorp/vault#18577]
**Describe the bug**
My vault instance is running in a kubernetes cluster (rke2) after a reboot I'm not able anymore to unseal the vault with error:

`Code: 500. Errors: * failed to check for keyring: invalid character '\x00' looking for beginning of value`

I've tried to unseal the vault from web gui (same devices and different), or even exec into the pod but I'm getting always the same error

I've found that this issue was submitted in the past [https://github.com/hashicorp/vault/issues/9398](url)
but the solution is not valid anymore since the request counters are not written in current version.

**To Reproduce**
Not able to reproduce

**Expected behavior**
Unseal the vault

**Environment:**

```
Key                Value
---                -----
Seal Type          shamir
Initialized        true
Sealed             true
Total Shares       5
Threshold          3
Unseal Progress    0/3
Unseal Nonce       n/a
Version            1.12.0
Build Date         2022-10-10T18:14:33Z
Storage Type       file
HA Enabled         false

```

Vault server configuration file(s):
Vault Helm chart without any edit

**Additional context**
the kubernetes cluster is running on VMs in proxmox.
The VMs are Ubuntu Server 20.04 kernel 5.15

**Comment by maxb** [comment]
This error message suggests that internal Vault files on disk have been corrupted by the underlying filesystem, perhaps related to a power outage, and now contain null bytes in something which is supposed to be JSON.

It is not possible to say for certain from this level of detail, but it is very possible that it will be necessary to restore from a backup, if one exists - or if no backup exists, this Vault may irrecoverably lost.

**Comment by ilbarone87** [comment]
Is there any other way I can try before going for full restore? 
A workaround to fix this issue was possible last  time this issue was posted.

**Comment by maxb** [comment]
The workaround last time (#9398) was to delete the corrupted data. That worked then, because the corrupted data was non-essential usage tracking counters. This time, the corrupted data is the critical encryption keys needed to decrypt the rest of the Vault.

You could check the contents of the `core/_keyring` file, which is the one which is apparently corrupted. The correct contents is a small JSON document:
```
{"Value":"some base64-encoded data here"}
```

If somehow, the only corruption is in the first few characters of the file, which should be exactly `{"Value":"`, it might be possible to fix - but if any of the base64-encoded data is lost, that's it - critical encryption keys have been destroyed.

**Comment by hsimon-hashicorp** [comment]
I'll go ahead and close this issue now, but please feel free to re-open if you need. Thanks!

**Comment by ilbarone87** [comment]
Yeah. Fine with it. I’ll restore from a backup.
