### ISSUE TITLE
Remove instance from peerlist when shutting down

### ISSUE THREAD

**Issue by wim-de-groot** [hashicorp/vault#18725]
**Problem**
When vault is shutting down (e.g. for restart or upgrade) other peers are still trying to reach out to the instance. This is the cause for the error: "failed to appendEntries to", "dial tcp: lookup <hostname of instance> on <ip address>:53: no such host". Vault should not try to 'append Entries' to an instance that (temporary) down.

**Possible solution**
I would like a solution where Vault does remove itself from the list of peers.

**Context**
I am running Vault HA with 5 instances on a Kubernetes cluster using the integrated storage back-end.

**Comment by maxb** [comment]
I don't think this is the right approach. From my experience working with Consul clusters, I know that removing and re-adding a Raft peer is a fairly slow operation, which is unnecessary when a node is just being restarted, and introduces extra complexity in understanding and managing the cluster quorum, since the cluster size is now changing as nodes join and leave.

I have a feeling there would be extra complexity in translating this generic Raft knowledge to Vault, since IIUC Vault actually requires the unseal keys to be available to complete a Raft join. I think that Vault also deliberately doesn't support joining a cluster once a node has any local data stored, to safeguard against overwrites - so that's another thing in the way of this proposal.

Perhaps there is a way to better mitigate the volume of noisy log messaging, without modifying the Raft peer set when nodes are temporarily down.
