### ISSUE TITLE
ec2-auth failing instance under certain conditions

### ISSUE THREAD

**Issue by gregdurham** [hashicorp/vault#1884]
I am spinning up instances in EC2 and have run into an issue affecting 10% of my force where we get an error from vault regarding the instance state:

> failed to verify instance ID: instance is not in 'running' state

After troubleshooting, I found that 'running' can be one of two states:
16) all healthy
272) underlying host reported problems

Should we assume that the '16' state is the only good state. It seems the wrong place to dictate that we will not allow vault to auth due to the underlying host reporting failures, rather than that being handled by the user's provisioning tool. 

Here is the line that likely would require 
https://github.com/hashicorp/vault/blob/e3cd98dae0acf0dafa473d9fb43359eeee1b1460/builtin/credential/aws-ec2/path_login.go#L86-L88

Thanks!

**Comment by jefferai** [comment]
This is most likely simply an oversight not realizing that 272 can be a valid state. Really we just want to make sure the host is powered on, not that it's fully healthy.

**Comment by gregdurham** [comment]
Excellent, would you be okay if I put a PR in for this fix?

**Comment by jefferai** [comment]
I'm already on it :-)

**Comment by jefferai** [comment]
For completeness, the issue here is that the AWS docs say to ignore the high byte as it's an internal value, but we're comparing on the full value rather than only looking at the full byte. In both cases the state name will be `"running"` so I'm actually thinking the right approach is to remove the check on the code entirely and only use the state name.

**Comment by gregdurham** [comment]
Makes sense and thank you for getting right on it!
