### ISSUE TITLE
hashicorp/vault:1.12

### ISSUE THREAD

**Issue by ankursrivastva** [hashicorp/vault#18891]
running jfrog x ray scan will reporoduce the issue

[Docker_rmrsp-hashicorp-vault-1.12_Security_Export.csv](https://github.com/hashicorp/vault/files/10532187/Docker_rmrsp-hashicorp-vault-1.12_Security_Export.csv)

please fix the issue or let us know in which release the fix will come

**Comment by mickael-hc** [comment]
Hello @ankursrivastva thank you for opening this issue.

We take a risk-based approach to adopting dependency updates including security fixes as part of our ongoing product development lifecycle. You'll generally see these addressed in future releases. For the two specific vulnerabilities mentioned in your report:

* `github.com/mholt/archiver/v3` dependency does not have a fixed version. `github.com/mholt/archiver/v3` is used by the debug command for archive _compression_ only, and does not extract any files. Vault should therefore not be affected by this issue.

* It appears you are using Docker, therefore it is unaffected by this vulnerability since the Docker images use Linux (Alpine) as a base. However, the version of Golang will be updated in Vault 1.12.3, scheduled for release in the upcoming days.

For any future security related inquiries, please contact security@hashicorp.com. I will close this issue for now, but please let us know if you disagree or if you think we misunderstood your request.
