### ISSUE TITLE
AZURE_CLIENT_ID takes precedence over provisioned secret in azure secret engine

### ISSUE THREAD

**Issue by dguihal** [hashicorp/vault#18915]
**Describe the bug**
While deploying vault on an AKS (Azure) kubernetes cluster, I stumbled on an strange behavior (IMHO)

on vault chart (0.23.0) I provide 2 envs vars
* AZURE_CLIENT_ID
* AZURE_CLIENT_SECRET

for vault service to be able to connect to Azure key vault service (for unseal) and Azure blob storage (for data backend)

outside of this I provision (using terraform & terraform vault provider) an azure secret engine with also providing some service principal credentials (different from above one), which have enough permissions to manage (create/delete/...) service principals.

But using this setup looks like vault completely ignore terraform provided SPN for azure secret engine and directly uses AZURE related env vars (which in my case don't have enough permissions to be used for azure secret engine)

**To Reproduce**
1. Configure vault with AZURE_CLIENT_ID / AZURE_CLIENT_SECRET env vars
2. Configure an Azure secret backend using another SPN (https://registry.terraform.io/providers/hashicorp/vault/latest/docs/resources/azure_secret_backend) provided through client_id / client_secret vars

**Expected behavior**
I would expect vault to use terraform provided vars and not vault service env vars

**Environment:**
* Vault Server Version (retrieve with `vault status`): 1.11.6
* Vault CLI Version (retrieve with `vault version`): 1.11.6
* Server Operating System/Architecture: Vault on AKS (using vault-k8s helm-chart)

Vault server configuration file(s):

```hcl
            default_lease_ttl = "168h"
            max_lease_ttl = "87600h"
            ui = true

            listener "tcp" {
              address = "[::]:8200"
              cluster_address = "[::]:8201"
              tls_cert_file = "/vault/certs/tls.crt"
              tls_key_file = "/vault/certs/tls.key"
              tls_min_version = "tls12"
              telemetry {
                unauthenticated_metrics_access = true
              }
            }

            service_registration "kubernetes" {}

            seal "azurekeyvault" {}

            storage "azure" {}

            ha_storage "raft" {
              path = "/vault/ha"
            }

            telemetry {
              prometheus_retention_time = "30s"
              disable_hostname = true
            }
```

**Additional context**

```terraform
resource "vault_azure_secret_backend" "azure" {
  use_microsoft_graph_api = true
  tenant_id               = var.vault_azure_secrets_engine_config_tenant_id
  subscription_id         = var.vault_azure_secrets_engine_config_subscription_id
  client_id               = var.vault_azure_secrets_engine_config_client_id
  client_secret           = var.vault_azure_secrets_engine_config_client_secret
  environment             = "AzurePublicCloud"
  path                    = "azure"
}
```

removing AZURE_CLIENT_ID / AZURE_CLIENT_SECRET from pod env vars and providing them through hcl file "fixes" the issue but then requires to provide an init script to generate the hcl file with appropriate secrets.

**Comment by austingebauer** [comment]
@dguihal - Thanks for opening this. I see that both the Azure secrets engine and Azure Key Vault seal use the same environment variables. It's documented that the environment variables [take precedence](https://developer.hashicorp.com/vault/docs/secrets/azure#authentication) in the Azure secrets engine. I agree that it makes more sense for direct API-provided values to take precedence. Unfortunately, I don't think we can change the behavior without surprising users or introducing some configuration to opt in changing the precedence. 

I see that you found a workaround that involves unsetting the environment variables. That is what I was going to suggest. Instead of generating the HCL file, could you pass the SP credentials via [Terraform variables](https://developer.hashicorp.com/terraform/language/values/variables)?

**Comment by dguihal** [comment]
@austingebauer thanks for your answer which confirmed my guess.

I totally understand that it would be hard for you to change this behavior although it would make more sense to me either.

For SP creds as tf variables I don't see how it could be used as a workaround. That one is used for data backend and unsealing.


So for now we'll decide on the most graceful way to manage this. Maybe we'll have to run with only one SP. I really hate those init managed config file personnally.

**Comment by austingebauer** [comment]
> removing AZURE_CLIENT_ID / AZURE_CLIENT_SECRET from pod env vars and providing them through hcl file "fixes" the issue but then requires to provide an init script to generate the hcl file with appropriate secrets.

I was mostly wondering if you can use TF variables to avoid the need to generate the HCL file from your comment above. In any case, it doesn't solve the core issue. I was mostly trying to help reduce the pain if possible 🙂 

I'm going to close this issue since there isn't a clear action we can take here. It's a good reminder for future development on how to set the config precedence and the potential for collision. Again, thanks for opening this!
