### ISSUE TITLE
Consistency mode in Cassandra

### ISSUE THREAD

**Issue by jefferai** [hashicorp/vault#1894]
@mp911de as someone who is using Cassandra, looking for some input:

Is there a reason not to use consistency mode ALL when performing Vault operations? Some users are seeing issues in a multi-zone setup where queries are going to different members that do not yet have new users propagated. But perhaps QUORUM would actually be the better option here?

https://docs.datastax.com/en/cassandra/3.0/cassandra/dml/dmlConfigConsistency.html

**Comment by mp911de** [comment]
Usually users want to start using credentials independently from where data is located. Everything else than that introduces eventual consistency to the generated users. `ALL` provides the highest consistency and usually takes the most time until all replicas acknowledged their writes. I think that's a sane default since user creation _should not_ be something that happens multiple times a second on a regular basis. 

There are also good reasons why one would like to use `EACH_QUORUM` or `LOCAL_QUORUM` especially for applications that care about data locality. There's a wide spectrum of Cassandra users so I'd keep that setting configurable.

**Comment by jefferai** [comment]
As a default, from the descriptions, I'm thinking QUORUM, if set on *both* write and read, will ensure correct ordering but allow some tolerance. I agree that being able to configure would be ideal.
