### ISSUE TITLE
policy creation requires management token

### ISSUE THREAD

**Issue by ygersie** [hashicorp/vault#1926]
We are working on an implementation of Vault. We're using the num_uses principle to provision an initial token to a VM safely. The problem we're facing is that we rely on "role" based secrets as follows:

Machine token (`f135effd-f6ef-4c04-a2eb-8e5184f0ef8e`) has access to path:
`secret/$role/$cluster`

We'd like to rely on the machine (token) to provision a new Child token for the specific application. Unfortunately Vault doesn't allow to create a new policy based on a subpath using a non-management token. I understand where this is coming from but this leads to a lot of manual operations to create policies and map child tokens correctly. I'd like to have the ability to provision a new token based on the parent token so we end up with:

`f135effd-f6ef-4c04-a2eb-8e5184f0ef8e` -> `9818b576-f8c9-417f-b321-a96cbb110e03` -> new_policy for path `secret/$role/$cluster/$appname`

Is this something you would consider? Or do you have suggestions on how to deal with this problem?

**Comment by jefferai** [comment]
This fits into our overall ideas around delegation, but those are a bit out time-wise. I'm not sure I totally understand your constraints but I recommend looking at response wrapping (https://www.vaultproject.io/docs/concepts/response-wrapping.html). Since the machine has a superset of access, the machine could fetch the value on behalf of the app and send it in for the app to unwrap.

**Comment by dropje86** [comment]
Let me explain the situation with a different example. I have an API which is responsible for the lifecycle of SSL certificates. This API is internally available for different platforms. You send a POST request to it with some parameters (like domain and platform) and the API will generate a CSR based on user input and send it off for signing. Once it's signed and ready the same POST call will return the cert, chain and private_key. This solves the issue of manually maintaining SSL certs (and distribution) which is quite cumbersome to say the least.

At this stage I'd like to be able to think of a solution to store all data in Vault in a secure manner. Ideally the client will be passing a Vault token (with a policy attached) to the API so it can only write to a specific path based on the node ${role}/ssl/${whatever}. The reason I want to store it that way is because this data will need to be accessible by other nodes that share the same role (distribute the same private_key, cert and chain).

If I were to use the initially generated Machine token I will have access to all secrets living within the ${role} path which is not desirable. If I want to create a Child token with a subset of the parents policy I'll always have to manually pre-create that specific policy which requires more (manual) configuration.

I will have to share a token with the API as there wouldn't be a way to read data in Vault which is required to verify certificate validity and renewals, so I can't just use response wrapping to prevent the API from accessing values, I actually need that.

This would be solvable (Low Trust) if I could create a Child Token with it's own policy. In that case I could limit the scope of the API's access to just the SSL path which it needs to manage. The "Authentication" part of the API would also be handled by Vault simply because of only having access to a specific path in Vault. The API could just try to write to the path and if that fails it doesn't have access.

Hope this explains the situation a bit better and maybe you guys have a suggestion on how to solve this. I'm currently drawing blanks.

**Comment by jefferai** [comment]
Unfortunately i think the answer is the same: we want to support this workflow but we're just not there yet.

**Comment by meirish** [comment]
Going to close this as I believe this is possible now with the Identity secret engine and ACL templating. See the docs here: https://www.vaultproject.io/docs/concepts/policies.html#templated-policies or an in-depth guide here: https://learn.hashicorp.com/vault/identity-access-management/policy-templating.

Thanks!
