### ISSUE TITLE
`vault kv put` ignores `-cas=n`

### ISSUE THREAD

**Issue by otto-dev** [hashicorp/vault#19368]
`vault kv put -help` states

```
Common Options:

  -cas=<int>
      ... If set to 0 a write will only be allowed if the key doesn’t
      exist.  ....
```

But that simply does not work.

```sh
root@dev-2:~# vault kv put -cas=0 secrets/example/auth password=foo
Success! Data written to: secrets/example/auth
root@dev-2:~# vault kv get secrets/example/auth
====== Data ======
Key         Value
---         -----
password    foo
root@dev-2:~# vault kv put -cas=0 secrets/example/auth password=bar
Success! Data written to: secrets/example/auth
root@dev-2:~# vault kv get secrets/example/auth
====== Data ======
Key         Value
---         -----
password    bar
```
The value is written no matter what I set `-cas` to.

```
root@dev-2:~# vault --version
Vault v1.5.5 (f5d1ddb3750e7c28e25036e1ef26a4c02379fc01)
```

**Comment by otto-dev** [comment]
Turns out it works if you set `-version=2` during kv store creation

**Comment by akshya96** [comment]
Hi @otto-dev. According to kv put documentation https://developer.hashicorp.com/vault/docs/commands/kv/put, “If working with K/V v2, this command creates a new version of a secret at the specified location. If working with K/V v1, this command stores the given secret at the specified location”. When the “-cas” (Check and set) flag is specified, the current version of the secret is verified before updating it. Since K/V v1 does not have versions for secrets, this will succeed.

**Comment by otto-dev** [comment]
Thanks for the response, I'm just going to close this :slightly_smiling_face:
