### ISSUE TITLE
Support module vault token locations instead of $HOME/.vault-token

### ISSUE THREAD

**Issue by sstarcher** [hashicorp/vault#1937]
For people dealing with multiple vault servers it would be useful to be able to authenticate with multiple servers without clobbering the $HOME/.vault-token or needing to wrap the command and store the token manually.

Preferably an environment variable.  $VAULT_TOKEN_HOME or $VAULT_PROFILE

**Comment by vishalnayak** [comment]
When multiple Vault instances are being dealt with, the combination of `VAULT_ADDR` and `VAULT_TOKEN` environment variables come in handy to operate on specific servers. I don't see how storing tokens at different locations would solve the problem.

**Comment by sstarcher** [comment]
True with the lack of support for the token being assocsiated with an address.  The request in and of itself is insufficient.

The original request would be functional if the vault server address was stored along with the token.

With the current CLI a user wants to persist the token between vault servers the user must
1. VAULT_ADDR='dev'
2. vault auth
3. mv ~/.vault-token ~/.vault-token-${VAULT_ADDR}
4. Either cat the token into VAULT_TOKEN or just copy the value instead of moving the value

After authing and storing the token
1. VAULT_ADDR='dev'
2. cp or cat ~/.vault-token-${VAULT_ADDR}

**Comment by jefferai** [comment]
Hi @sstarcher ,

Vault's token-helper is also modular; the built-in one simply sets a token in a file, but another could be provided that does more fancy things. That capability is probably not well-documented, but that's mainly because nobody has yet (as far as we've heard) actually wanted to take advantage of it and write their own, especially because a lot of people use `envchain` (https://github.com/sorah/envchain) for exactly this purpose!

**Comment by sstarcher** [comment]
@jefferai Perfect, I'll look into seeing if that resolves my issues
