### ISSUE TITLE
vault kv secret with special chars ('$#') changes

### ISSUE THREAD

**Issue by wibram** [hashicorp/vault#19393]
**Bug Description**
When the secret value contains the characters '$#' it changes to '0'.

**To Reproduce**
1. Run: vault kv put secret/test mypwd="$#"
2. Run: vault kv get secret/test
3. You will get: 0
4. The value can contain more charactes, but if there is '$#' in the value, it will change to '0', e.g. 'demo$#demo' will be 'demo0demo'.

**Expected behavior**
It should return the same input: '$#'. The problem seems to be a base64 conversion problem.

**Environment:**
Vault Version: 1.12.1 (Seal Type: shamir)
Runs in kubernetes pod/container.
OS:
NAME="Alpine Linux"
VERSION_ID=3.15.6
PRETTY_NAME="Alpine Linux v3.15"
4.18.0-147.5.1.6.h541.eulerosv2r9.x86_64

**Comment by wibram** [comment]
When I run following in the shell:
`echo $# | base64`
Result: MAo=
Then:
`echo MAo= | base64 -d`
Result: 0

So this seems to be a bug in the OS. The EulerOS system is made by Huawei and based on CentOS.

**Comment by wibram** [comment]
I found a workaround:

`vault kv put secret/test mypwd='$#'`

Values with single quotes instead of double quotes works fine.

**Comment by maxb** [comment]
All of the symptoms you describe here are part of the normal intentional behaviours of common shell (i.e. command prompt) programs on Linux. You may find it useful to spend some time reading the documentation at https://www.gnu.org/software/bash/manual/bash.html or Google for related tutorials, if you prefer a different style of learning material.
