### ISSUE TITLE
Please provide a systemd unit for Vault Agent

### ISSUE THREAD

**Issue by patrakov** [hashicorp/vault#19511]
Vault git repository contains an official systemd unit file for Vault Server: https://github.com/hashicorp/vault/blob/main/.release/linux/package/usr/lib/systemd/system/vault.service

However, there is no unit file for Vault Agent, which is another type of daemon that can be started using the "vault" binary.

**Comment by martinfojtik** [comment]
This would help tremendously as I run the Agent on Linux systems most of the time.

**Comment by VioletHynes** [comment]
Hi there! I'm going to close this as a won't do. I put a more detailed explanation here: https://github.com/hashicorp/vault/pull/19722#issuecomment-2152927607

But in short, we talked about this internally and we don't feel like this makes sense. Ultimately, for Vault itself, it's possible to have a service and config that 'makes sense' and starts up and works with a sane configuration, but that's simply not possible for Agent. 

Making the systemd unit file is the 'easy' part, so the value of providing something that seems like it might work but will always fail since you will always need to update the config file, at least to me, seems questionable.

That being said, I don't think we have things perfect here, and it's why this was something we had to talk about internally. I'll continue thinking about this and how we can improve the experience here for both of our daemons.
