### ISSUE TITLE
Vault Agent Cache Kv2 Secrets

### ISSUE THREAD

**Issue by M1Gd0nPG** [hashicorp/vault#19879]
**Is your feature request related to a problem? Please describe.**
We use the Kv2 Secret engine to provide secrets during runtime.  We've noticed that this means our applications are hammering the server for secrets endlessly since the vault agent doesn't currently allow for caching of non-renewable secrets.  It would be really helpful to have a caching option for static secrets like this that the agent could handle. 

**Describe the solution you'd like**
The vault agent can be configured to cache static secrets for a user-specified amount of time.  Maybe something like adding an option to the cache block of the config file
```
cache {
    persist = {
        type = "kubernetes"
        path = "/vault/agent-cache/"
        keep_after_import = true
        cache_static_secret = "10m"
```

**Describe alternatives you've considered**

**Explain any additional use-cases**
If there are any use-cases that would help us understand the use/need/value please share them as they can help us decide on acceptance and prioritization.
I saw [this issue](https://github.com/hashicorp/vault/issues/10920) and it seems pretty related.  We could use this method as well;  but we don't always use templates so it wouldn't be a full solution.  

**Additional context**

**Comment by VioletHynes** [comment]
Hey there! We've been talking a lot recently about the potential of adding static secret caching to Vault Agent. It sounds like you're in particular looking for this for Agent's API Proxy use case? i.e. caching secrets that are sent to Vault Agent's API Proxy listener so that upon the second request for the same secret, it wouldn't need to send the request to Vault at all.

In particular, you also pointed out, `static_secret_render_interval` supports the template use case, and you "don't always use templates", so I think that it's the case that the API proxy is what you're hoping for for cache support, but making sure I'm right about this and fully understand your use-case will help!

Thanks for the request, and thanks in advance for the info!

cc @finnstech

**Comment by M1Gd0nPG** [comment]
@VioletHynes yes, exactly!  ` caching secrets that are sent to Vault Agent's API Proxy listener so that upon the second request for the same secret, it wouldn't need to send the request to Vault at all.`  is exactly what we want.  Hopefully my write up wasn't too confusing 😄 .  Very excited to hear y'all are discussing the idea of adding static secret caching to the agent!

**Comment by VioletHynes** [comment]
Hey there! I wanted to report back with the good news that this has been implemented and should release in 1.16! Specifically, we implemented this into Vault Proxy, which is a new subcommand for the Vault CLI that's similar to Agent, but is where the API Proxy functionality now lives. The API Proxy functionality may be deprecated from Agent at a later date, but Proxy's functionality is entirely compatible to an Agent config that was doing API Proxying and no templating, and its API Proxy functionality is a superset of Agent's.

The tentative pre-release documentation can be found here: https://vault-r1xrfcpnr-hashicorp.vercel.app/vault/docs/agent-and-proxy/proxy/caching/static-secret-caching

Feel free to let me know if you have any questions! Thanks for the FR!

**Comment by adrianlzt** [comment]
I was playing with this new cache and there is a little catch with the CLI.

Executing `vault kv get kv/foo` will [always send](/v1/sys/internal/ui/mounts/kv/foo3) first a call to `/v1/sys/internal/ui/mounts/kv/foo`.

This call could not be cached, so the client will always need to make a request to the Vault server and then use the cached value in the proxy.

If that call could be skipped, the CLI could get cached data from a proxy while the server is offline (somehow addressing #150).

**Comment by VioletHynes** [comment]
Hey @adrianlzt ! Thanks for the feedback, and thanks for checking this out already!

Some background about the kv 'preflight' check: This is implemented to make `kv get` work as expected with KVv1 and KVv2, and will add the 'data' required for KVv2 secret mounts if it's not already present. I suspect you already know this, but I'm adding this for prosperity.

If you'd like to avoid the preflight check today via the CLI, you could use `vault read my-kv-v2-mount/data/foo`, as this will perform a direct read on the path, and this will allow the CLI invocation to use the cache entirely. That being said, the preflight check is just a `kv get` CLI convenience, since we expect the majority of production calls to be going through the API directly, for example.

I noticed your PR, and I'll try and make sure it gets looked at. Thanks!

Thanks,
Violet

**Comment by adrianlzt** [comment]
Uops, I didn't know about `vault read my-kv-v2-mount/data/foo` :sweat:.
I think that fixes the problem and the PR is not needed.
Thanks!

**Comment by adrianlzt** [comment]
Could be possible to also add caching to the "list" operations?
```v1/kvmountpoint/metadata/vestas?list=true```

If those calls could be cached, will be possible to have an offline proxy that could the _navigated_.
