### ISSUE TITLE
Best practice for Multi-master Consul backend?

### ISSUE THREAD

**Issue by igormoochnick** [hashicorp/vault#2003]
From the server configuration doc (https://www.vaultproject.io/docs/config/index.html) I can't figure out how to tell Vault that there is a cluster of Consul servers. The "address" field can be specified only once, but I have 3 consul masters and I'd like Vault to be full HA.

Should Vault use Consul DNS to resolve the Consul masters?  Or Vault servers have to have Consul agent running locally and everyone of them should have "address" field pointing to "localhost"?

DNS: address = "consul.service.consul:8500"
vs.
Agent: address = "localhost:8500" or address = "unix:///tmp/.consul.http.sock"

  What's is the best practice?  Pros. and Cons.?

```
Thank you
```

**Comment by mgar** [comment]
I would say that having a Consul agent running in every single Vaul node is the way to go. Doing it this way you will also have Vault's health checks set up in Consul.

**Comment by ekristen** [comment]
@igormoochnick @mgar is correct at least in my opinion.

I've been running vault since pre 0.3.0 using Consul as my backend.

You should run vault either on the same 3 servers that your consul servers are on, or run them on servers that have their own consul agent running that is tied into your consul cluster.

Then when running vault, point each local vault to the local consul server/agent. This will make sure everything runs in HA mode.

**Comment by chrishoffman** [comment]
Running a local consul agent is the recommended workflow and required in some case.
