### ISSUE TITLE
How to distribute token?

### ISSUE THREAD

**Issue by WangFenjin** [hashicorp/vault#2068]
Hi all,

I'd like to use vault manage MySQL username/password. I read through the docs, but still in doubt how to distribute token to clients. Let's say:
1. I have a MySQL server, and had config vault with readonly role (follow the guide https://www.vaultproject.io/docs/secrets/mysql/index.html)
2. I can create a role_ip and secret_id, and give them to service developers, so they can login to fetch a token (follow the guide https://www.vaultproject.io/docs/auth/approle.html)
2.1 Or I can use the role_ip and secret_id to generate a token and give the token to service developers.
3. Developers will commit the token in source code or config files and use that token to retrieve password. (like this blog https://spring.io/blog/2016/06/24/managing-secrets-with-vault)

But in either case, secret_id or token will expose to all developers, and they can use this token to do anything they want, such as retrieve the password.
I can't see the difference with give them password directly... What I mean is, as long as the token is committed to git, anyone who has permission access to the code can use that token to read/modify your database.

Could you please help clarify where am I wrong? Thanks.

**Comment by jefferai** [comment]
Hi @WangFenjin ,

Can you please post questions on the mailing list (https://groups.google.com/forum/m/#!forum/vault-tool) rather than in GitHub issues? This gets a lot more eyes on any particular question or idea.

It also prevents problematic issue workflows for questions where either the issue is closed immediately but then discussion continues on a closed issue; or, the issue is not closed, discussion dies down, and the issue remains open indefinitely waiting for further potential replies.

Thanks!
