### ISSUE TITLE
null password allowed with ldap authentication

### ISSUE THREAD

**Issue by camill8** [hashicorp/vault#2086]
If you pass an empty password to authenticate to vault using LDAP, and the LDAP server is configured to accept null bindings, the authentication will succeed without knowing the user's password.  Vault should check that a non-empy password is submitted before trying to authenticate to the server.

Here is what such a post looks like:

`POST /v1/auth/ldap/login/charlie  HTTP/1.1`
`{“password":""}`

**Comment by jefferai** [comment]
If Vault were to make such a check, workflows that rely on null bindings would no longer work.

**Comment by broamski** [comment]
Would a string length of zero check at [backend.go#L114](https://github.com/hashicorp/vault/blob/master/builtin/credential/ldap/backend.go#L114) be sufficient to prevent this? Perhaps this check combined with a flag that toggles null binding capabilities?

**Comment by camill8** [comment]
@jefferai: Its seems like if something is being advertised as "authentication", it should probably require a password.

**Comment by ChrisLundquist** [comment]
> @jefferai: Its seems like if something is being advertised as "authentication", it should probably require a password.

I can see that perspective. I think there is more to it than that though.

Vault is using LDAP as a trusted third party, right?
It seems like if we specify some constraints in Vault, and other ones in LDAP, we'll have a bad time.

It seems that the constraint should be added in LDAP, in that case.
Otherwise, an ldap user could exist with an empty password, and Vault wouldn't let them log in because it had differing constraints. (Maybe I had a narrowly scoped read only LDAP user, but disallowed anonymous binds, say for SSH Public Keys)

To reframe the above,
If you're using LDAP for auth, shouldn't *it* require a non-empty password?
Vault is just the go-between here.

**Comment by broamski** [comment]
Referencing [builtin/credential/userpass/path_login.go#L42-L45](https://github.com/hashicorp/vault/blob/master/builtin/credential/userpass/path_login.go#L42-L45), is it acceptable to replicate this same check with the addition of a flag that allows password-less null binds? It seems like not allowing a user to auth via LDAP without a password by default is a nice, safe thing to do in the interest of involuntarily exposing secrets.

**Comment by jefferai** [comment]
I'm totally fine with making this a flag to control this behavior (and disallowing black passwords by default).
