### ISSUE TITLE
vault.service too strict for Integrated Storage (Raft) Backend. Read only access for service.

### ISSUE THREAD

**Issue by ipaqmaster** [hashicorp/vault#21096]
**Describe the bug**

Trying to start a Vault cluster with a vault.hcl which specifies to use Raft - fails. This is a result of the strict vault.service file currently in the main branch preventing write access to /var/lib/vault even when following current deployment steps on the website.

**To Reproduce**
1. Install Vault
2. Make a vault.hcl which uses a relative Raft storage path as per the documentation.
3. Service fails to start as it cannot write its vault.db file.

**Expected behavior**
The service to start.

This is possible with `su - vault -s /bin/bash -c 'vault server -config=/etc/vault.hcl'` which works around the vault.service strictness.

**Environment:**
* Vault Server Version (retrieve with `vault status`): <During initial setup>
* Vault CLI Version (retrieve with `vault version`): Vault v1.13.2 (cgo)
* Server Operating System/Architecture: Archlinux

Vault server configuration file(s):

```
storage "raft" {
  path    = "./data"
  node_id = "vault01"
}
```

**Additional context**

Before this issue I also submitted a downstream bug report https://bugs.archlinux.org/task/78742 where it were confirmed the package uses the provided vault.service file from vault.

**Comment by maxb** [comment]
This is not an upstream issue, but an error in the Arch packaging.

The HashiCorp package uses different directories for the `vault` user home directory, and the data directory. In this configuration, `ProtectHome=read-only` is valid.

The Arch package assigns `/var/lib/vault` as both the home directory and the data directory, making `ProtectHome=read-only` now a problem - but only because of Arch's decision to use the same directory for both roles.

**Comment by ipaqmaster** [comment]
Thanks for the clarification Max

**Comment by maxb** [comment]
Also, a factual correction:

> https://bugs.archlinux.org/task/78742 where it were confirmed the package uses the provided vault.service file from vault.

No, what they actually said (emphasis mine) was:

> the upstream provided .service file [1] (which we are **not** using...yet)

**Comment by maxb** [comment]
Also, a couple of suggestions about your Vault configuration, which are not related to the problem you experienced, just things I noticed in reading it:



> path    = "./data"

I would discourage using a relative path here. It is better to use an absolute path, to insulate yourself from an unplanned change to the current directory of the Vault server process.



> node_id = "vault01"

I would discourage manually specifying Raft node IDs. Let the Vault process generate a random UUID and store it on disk, and that way you'll never have to worry about accidentally configuring a conflict, which could seriously impact cluster operations.

**Comment by ipaqmaster** [comment]
Personally the setup I'm using right now is using full paths. My example above was trying to follow the documentation on the hashicorp developers subdomain as closely as possible (Which also exhibits the issue). I understand relative complicates things especially in this situation.

> https://bugs.archlinux.org/task/78742 where it were confirmed the package uses the provided vault.service file from vault.

My bad. Busy day.

**Comment by hashworks** [comment]
> The Arch package assigns /var/lib/vault as both the home directory and the data directory, making ProtectHome=read-only now a problem - but only because of Arch's decision to use the same directory for both roles.

This is not correct - see the [systemd documentation](https://www.freedesktop.org/software/systemd/man/systemd.exec.html#ProtectSystem=) on ProtectSystem=full and ProtectHome=read-only:
> ProtectSystem=
> Takes a boolean argument or the special values "full" or "strict". If true, mounts the /usr/ and the boot loader directories (/boot and /efi) read-only for processes invoked by this unit. If set to "full", the /etc/ directory is mounted read-only, too.

> ProtectHome=
> Takes a boolean argument or the special values "read-only" or "tmpfs". If true, the directories /home/, /root, and /run/user are made inaccessible and empty for processes invoked by this unit. If set to "read-only", the three directories are made read-only instead.

This means the only directories the Arch Linux vault systemd unit can't write to are /usr, /boot, /efi, /etc, /home, /root and /run/user. The vault home directory /var/lib/vault is still writable. ProtectHome is NOT specific to the user home directory.

> Service fails to start as it cannot write its vault.db file.

My guess is that the service fails because the directory does not exist, vault will not create it:
```
Error initializing storage of type raft: open /var/lib/vault/data/node-id: no such file or directory
```

If you create `/var/lib/vault/data` it might complain about permissions, so make sure it is owned by the vault user.
```
Error initializing storage of type raft: open /var/lib/vault/data/node-id: permission denied
```

With the current Arch Package and the following config and an existing directory with correct permissions the raft database is created correctly:
```
ui = true

backend "file" {
	path = "/var/lib/vault"
}

cluster_addr = "http://127.0.0.1:8201"
api_addr     = "http://127.0.0.1:8200"
storage "raft" {
  path    = "/var/lib/vault/data"
}

listener "tcp" {
	tls_disable = 1
}
```

![image](https://github.com/hashicorp/vault/assets/2362091/dbf3b66c-eb27-48aa-bb23-042afabb1037)


```
$ tree /var/lib/vault
/var/lib/vault
└── data
    ├── node-id
    ├── raft
    │   ├── raft.db
    │   └── snapshots
    └── vault.db

4 directories, 3 files
```

**Comment by hashworks** [comment]
> the upstream provided .service file [1] (which we are not using...yet)

I've [adjusted the package](https://gitlab.archlinux.org/archlinux/packaging/packages/vault/-/commit/5007691691d6fb722aa8e78e89e067956fc8cee4) to use the systemd unit file provided by vault, so we can avoid future confusion about this.

**Comment by ipaqmaster** [comment]
Much appreciated. I understand your above comment clearly too.

**Comment by maxb** [comment]
> This is not correct - see the [systemd documentation](https://www.freedesktop.org/software/systemd/man/systemd.exec.html#ProtectSystem=) on ProtectSystem=full and ProtectHome=read-only:
> 
> >

Oops. That's my bad for assuming `ProtectHome` would apply to the actual home directory, and trusting that the original report of this being a permissions problem was true. I guess I should be more sceptical and demand actual error messages be copy/pasted, as a matter of course.

A separate matter: In the example configuration shown above:

> backend "file" {
> 	path = "/var/lib/vault"
> }

This part is not valid Vault configuration, being ignored since `backend` is not a known block name for Vault server configuration.

**Comment by hashworks** [comment]
> This part is not valid Vault configuration, being ignored since backend is not a known block name for Vault server configuration.

Correct, my bad. Not sure where it came from.

**Comment by hsimon-hashicorp** [comment]
Hi folks, with @hashworks's comments here, is this issue okay to be closed? Let me know if there's anything else I can do to help. Thanks!

**Comment by hsimon-hashicorp** [comment]
It's been a little while, so I'm going to go ahead and close this issue now. Please feel free to re-open it or open a new one as needed. Thanks!
