### ISSUE TITLE
gomaxprocs question

### ISSUE THREAD

**Issue by pantocrator27** [hashicorp/vault#2123]
is setting gomaxprocs still recommended for vault & consul?

**Comment by jefferai** [comment]
Hi @pantocrator27 ,

Can you please post questions on the mailing list (https://groups.google.com/forum/m/#!forum/vault-tool) rather than in GitHub issues? This gets a lot more eyes on any particular question or idea.

It also prevents problematic issue workflows for questions where either the issue is closed immediately but then discussion continues on a closed issue; or, the issue is not closed, discussion dies down, and the issue remains open indefinitely waiting for further potential replies.

Thanks!
