### ISSUE TITLE
Provide a custom logger to testutil server

### ISSUE THREAD

**Issue by sethvargo** [hashicorp/vault#2132]
Right now, the testutil server automatically dumps logs to stderr. It looks like there's a way to specify a custom logger interface to the server itself, but this is not exposed in the test server. It would be awesome if I could send log output to any io.Writer.

**Comment by jefferai** [comment]
Which function specifically are you referring to here?

**Comment by sethvargo** [comment]
Hey @jefferai 

Basically I have this function now which I've hacked around a bit:

```go
func testVaultServer(t *testing.T) (*ClientSet, *vaultServer) {
	t.Parallel()

	core, err := vault.NewCore(&vault.CoreConfig{
		DisableMlock:    true,
		DisableCache:    true,
		DefaultLeaseTTL: 2 * time.Second,
		MaxLeaseTTL:     3 * time.Second,
		Logger:          logxi.NullLog,
		Physical:        physical.NewInmem(logxi.NullLog),
		LogicalBackends: map[string]logical.Factory{
			"pki":     pki.Factory,
			"transit": transit.Factory,
		},
	})
	if err != nil {
		t.Fatal(err)
	}

	key, token := vault.TestCoreInit(t, core)
	if _, err := vault.TestCoreUnseal(core, vault.TestKeyCopy(key)); err != nil {
		t.Fatal(err)
	}

	ln, addr := http.TestServer(t, core)
	clients := NewClientSet()
	if err := clients.CreateVaultClient(&CreateVaultClientInput{
		Address: addr,
		Token:   token,
	}); err != nil {
		ln.Close()
		t.Fatal(err)
	}

	server := &vaultServer{
		Address: addr,
		Token:   token,
		core:    core,
		ln:      ln,
	}

	return clients, server
}
```

It'd be nice if there was a better-er way to do that, without actually starting a vault server as a subprocess or something.

**Comment by jefferai** [comment]
Hi @sethvargo ,

I generally recommend using the TestCluster function going forwards. This sets up a three-node Vault cluster with real HTTP servers, listeners, HA, and request forwarding; you can use the Vault Go API with it natively. Outside of the bits done by command/server.go, this gives real end-to-end testing rather than simply instantiating a core. (You can see examples of using it in http/forwarding_test.go)

I've just added code that will be in 0.6.3 that will use a Logger passed in to the base config given to that function for the cores the function creates.
