### ISSUE TITLE
Docs relating to starting in prod mode

### ISSUE THREAD

**Issue by illogicalextend** [hashicorp/vault#215]
https://www.vaultproject.io/intro/getting-started/deploy.html

Why does the 'getting started' example use consul (file store would be simpler, I assume?) to set up vault? Why does it use a third party consul instance? Why not include basic instructions of how to connect to your own consul instance if you start one locally with (./consul agent -server -bootstrap-expect 1 -data-dir /tmp/consul)?

edit: just found docs on how to use file system: https://www.vaultproject.io/docs/config/index.html , although my previous comments relate to the quick start guide.

If it's possible to write to a file rather than consul, why isn't this defined anywhere? Not sure how to get info on what arguments to add to hcl file for this.

**Comment by armon** [comment]
@illogicalextend All of the docs for the `file` backend are on that page you've linked, it only has a single "path" argument to configure.

We use Consul in the quick start guide because it is the recommended backend for production, but running Consul is outside the scope of that guide, so we use the publicly hosted instance instead.

**Comment by sheldonh** [comment]
@armon Could you please clarify how you'd like us to fix the Getting Started guide? Were you saying you would prefer that the Getting Started guide use the `file` backend instead of the `consul` backend?

**Comment by armon** [comment]
@sheldonh We should probably just put the one liner in for starting Consul. The file backend is just not generally recommended.
