### ISSUE TITLE
Problems with diacritic symbols in path to resource

### ISSUE THREAD

**Issue by mr-tron** [hashicorp/vault#2150]
For example,  if I put some data to `/v1/secret/russian/й` (where `й` is U+0439) I can also get it by this key. But if i do listining request to parent record `/v1/secret/russian/?list=true`, I get `data": {  "keys": ["й"] }` (where `й` is  `и` U+0438 combined with ` ̆` U+0306).
And when I try this text as a key I get 404.

I think this problems also exists with over languages with diacrtitic symbols like german or vietnamese.

**Comment by jefferai** [comment]
This appears to be OS or platform specific. I just tried on a dev instance on macOS 10.12:

```
$ vault write secret/russian/й foo=bar
Success! Data written to: secret/russian/й

$ vault read secret/russian/й
Key             	Value
---             	-----
refresh_interval	768h0m0s
foo             	bar

$ vault list secret/russian
Keys
----
й
```
According to an online unicode decoder I found (http://www.online-toolz.com/tools/text-unicode-entities-convertor.php) these are the same characters.

**Comment by jefferai** [comment]
What OS, storage backend, version of Vault?

**Comment by mr-tron** [comment]
macos el captain, vault from github master, file backend. I checked - on dev in-memory backend on same host works without problems.

**Comment by jefferai** [comment]
That's a filesystem normalization problem then, which is well known as a pain point in mac OS. The filesystem is normalizing the character such that lookups return the expected value (because during file open the normalization will always translate the symbol to the same value), but when you do a listing, you're getting the normalized value. There's unfortunately absolutely nothing we can do; this is not a bug in Vault, but a feature of macOS.
