### ISSUE TITLE
Require "sudo" capability for reading backend configuration

### ISSUE THREAD

**Issue by lethalpaga** [hashicorp/vault#2166]
Most backends (both auth and secret) require some kind of "root user" configuration to access the underlying system. For example, the AWS secret backend requires an access key and a secret key in aws/config/root, the ldap auth backend requires a password in auth/ldap/config, etc.

IMHO theses paths should require a stricter permission to read them, otherwise it makes it quite difficult to write policies to empower users to do the config they require without giving them access to read thoses critical secrets, e.g. I want my users to be able read and write on aws/roles, aws/creds and aws/sts but not aws/config. This gets hairier when mounting the backend several times (when having several aws accounts for example). At the moment my policy will look like
```hcl
path "aws/account1/roles" {
  capabilities = ["read", "create", "update", "list"]
}

path "aws/account1/creds" {
  capabilities = ["read", "create", "update", "list"]
}

path "aws/account1/sts" {
  capabilities = ["read", "create", "update", "list"]
}

path "aws/account2/roles" {
  capabilities = ["read", "create", "update", "list"]
}

path "aws/account2/creds" {
  capabilities = ["read", "create", "update", "list"]
}

path "aws/account2/sts" {
  capabilities = ["read", "create", "update", "list"]
}
```

Unless I'm mistaken, wildcarding can't help here as you can only have a * at the end of the path (so no `aws/*/roles`) and it's not a full-blown regexp.

A neat solution would be to require the `sudo` capability (or a new capability) to access theses paths. That would have the additional advantage of not requiring to be explicitly defined in the policies (most of them don't have sudo)

**Comment by lethalpaga** [comment]
mm I retried reading from the aws backend and it looks like reading config/root isn't supported, even with a root token, so that's a good thing I guess.
On the other hand the problem exists at least for `ldap` and `postgresql` (reading `config/connection` gives you your db password), so maybe there should be a guideline consistent across all backends?

**Comment by jefferai** [comment]
We've actually been doing the opposite -- removing the requirement for "sudo" across most endpoints because it was a general source of confusion.

The problem with adding it to arbitrary endpoints is that if people rely on requiring sudo + something else to access, it's easy to end up in a situation where if we decide to remove sudo from that endpoint at some future time, suddenly access is granted on upgrade to much more than administrators were intending.

As a result we're limiting sudo to very dangerous paths. It's really just a message to the administrator: beware, dragons.
