### ISSUE TITLE
orphaned users with Cassandra as a secret backend 

### ISSUE THREAD

**Issue by cscetbon** [hashicorp/vault#2171]
Hi guys,

having made some tests with Vault using Cassandra as a secret backend, I have twice seen surviving users after the lease has expired (is supposed to have expired as it's set to 10 mn). **The good news**, is that I see that it doesn't have permissions. I can't tell if it has lost its permission or if it has been created without any permission but it survives : 

```
cassandra@cqlsh> select * from system_auth.users ;

 name                                                                   | super
------------------------------------------------------------------------+-------
                                                              cassandra |  True
 vault_t1_readonly_root_1ff9affc_eade_b8f0_94a7_b38d798d25b0_1481303347 | False

cassandra@cqlsh> LIST ALL PERMISSIONS OF vault_t1_readonly_root_1ff9affc_eade_b8f0_94a7_b38d798d25b0_1481303347;

 username | resource | permissions
----------+----------+-------------
```

Here is the command used to create the role : 

```
$ vault write cassandra/roles/t1_readonly creation_cql="CREATE USER '{{username}}' WITH PASSWORD '{{password}}' NOSUPERUSER; GRANT SELECT ON demo.t1 TO {{username}};" consistency=LOCAL_ONE lease=10m
Success! Data written to: cassandra/roles/t1_readonly
```

FYI, the tests to generate accounts have been done using consul-template

**Comment by jefferai** [comment]
@cscetbon Any chance you can share the C-T file? Also, can you share your Vault logs? Would be good to see if there were errors on revocation.

**Comment by cscetbon** [comment]
@jefferai what do you mean by C-T file ? 
http://pastebin.com/855583XZ is the vault log. The error you see is not related. I've stopped the vault server to check if a standby was elected and then made this vault be re-elected so I think I lost some logs. It seems logs are overwritten when we restart the server, can you confirm ?

**Comment by jefferai** [comment]
@cscetbon I meant the template file you're using. Logs are not written by Vault, they are just put out to stdout/stderr so if it's overwritten it's your startup/init script doing it. What's the config of your Cassandra backend?

**Comment by cscetbon** [comment]
@jefferai The consul template file is http://pastebin.com/76CiHrp3
The configuration of the Cassandra backend has been set with this command :
```
$ vault write cassandra/roles/t1_readonly creation_cql="CREATE USER '{{username}}' WITH PASSWORD '{{password}}' NOSUPERUSER; GRANT SELECT ON demo.t1 TO {{username}};" consistency=LOCAL_ONE lease=10m
Success! Data written to: cassandra/roles/t1_readonly
```
I may have run it twice with different parameter, to update the lease duration for instance, but I suppose that token created with the first configuration were not impacted ?

**Comment by jefferai** [comment]
What version of Cassandra?

**Comment by cscetbon** [comment]
2.1.14

**Comment by jefferai** [comment]
So far I'm not seeing anything damning. The revocation logic is super duper simple: it fetches the username from the stored data, connects to the database, and issues a `DROP USER '<user>'`. At all points along the way errors are checked and if an error occurs the lease will not be revoked but rather scheduled to be retried later.

I will keep my eyes out but it's not impossible that this is some Cassandra bug. For instance, see http://stackoverflow.com/questions/32687675/cassandra-can-not-delete-role-or-user-which-in-the-role-or-user-list -- a poster complaining of a role showing up in the role list which actually doesn't exist, which sounds very close to your behavior, if we can assume that the reason the role has no privileges is because it is in fact "deleted".

Most systems aren't using dynamic Cassandra users, so it's not impossible that Vault is triggering a little-seen error condition. You may also want to try posting on the Cassandra list and/or bug tracker as well and see if this rings any bells for anyone. What Vault does is pretty simple, it just does it a lot...

**Comment by cscetbon** [comment]
@jefferai it's not deleted cause I can connect using the account. I looked at your code and I agree it looks super simple, that's why I was thinking that maybe there was an edge case not handled somewhere ... I'm not aware of a Cassandra error when executing a `DROP USER` that removes only permissions. I'm gonna ask the question on their ML.

> What Vault does is pretty simple, it just does it a lot...

That's why I like it :)

Thank you, and if I can reproduce it and nail it, I'll tell you.

**Comment by cscetbon** [comment]
I close the issue for now and will reopen it in case

**Comment by jefferai** [comment]
OK. Please do let us know if you can figure out what's going on and/or how to reproduce!
