### ISSUE TITLE
Utilize Linux Kernel Keystore to protect in-memory secrets

### ISSUE THREAD

**Issue by jhmartin** [hashicorp/vault#21801]
As a Vault operator, I want vault to make maximal use of all available protections to prevent secrets it protects from being exposed. 

**Describe the solution you'd like**
Evaluate the Linux Key Retention Service per
* https://blog.cloudflare.com/the-linux-kernel-key-retention-service-and-why-you-should-use-it-in-your-next-application/
* https://kernel.org/doc/html/v6.0/security/keys/core.html#key-overview
* https://youtu.be/7djRRjxaCKk

for suitability in storing sensitive data outside of the Vault memory space.

**Additional context**

https://developer.hashicorp.com/vault/docs/internals/security indicates that memory safety of Vault is not one of the threats addressed by Vault, so I can see this might be considered 'out of scope'.

**Comment by cipherboy** [comment]
Fundamentally, as an approach to protect Vault server's managed secrets, this is not suitable as it won't solve the problem. There are many equivalent secrets that leak in memory that cannot be stored in the kernel keyring due to design restrictions of both the keyring and of the Go toolchain. Consider:

1. TLS session keys. Go does not understand placing them in the kernel keyring and further, simply storing them in the keyring would necessitate moving them back to memory (for actual encryption operations). A better kernel keyring design so that encryption operations can occur within it seems impractical, given it competes with things like e.g., TPMs, PKCS#11 tokens, &c. With these keys, an attacker can decrypt any and all traffic coming to/from Vault, stealing high-privileged tokens, or even just passively reading session traffic.
2. (inner) HTTP traffic, including auth tokens, login info, and transited secrets. Skipping breaking TLS, secrets are transmitted within the inner HTTP stream, and these could be read from memory. Here, unless Go updates to support decrypting _into_ kernel keyring space (which again, seems unlikely -- and bodies can be somewhat large, I think our default is 30MB), the TLS decrypt operation would (temporarily) leak any in-flight decryption requests at memory snapshot time.
3. Other similar approaches to the above apply _many_ places within Vault (Transit keys, PKI CAs, reading/writing from KV, database creds, at token creation time, ...) &c. 

Then there's the scalability aspect: based on https://man7.org/linux/man-pages/man7/keyrings.7.html , there's only (by default) 200x 20KB secrets for non-root users (which we don't recommend running Vault as root!). With root, that's 20,000x 20MB, which is much better suited for running Vault at scale. But this means that operators would need to tune their Kernel instance at scale, to support reading/writing more secrets. (Thanks to @swenson, we believe https://www.kernel.org/doc/html/v5.8/security/keys/core.html could help with some of the e.g., TLS termination concerns, but without deep Go enablement, would still likely result in HTTP request being in memory when Go parses the HTTP body). 

Instead, I think the technology that would be best suited here would be full memory encryption: e.g., [one of our partners](https://www.hashicorp.com/partners/tech/anjuna): https://www.anjuna.io/blog/runtime-protection-for-secrets-management 

---

However, what _is_ a good use of this technology, and one I've personally been wanting to see, is a protocol for reading secrets from keyring instead of envvars.

E.g., to [parse path](https://github.com/hashicorp/go-secure-stdlib/blob/1a4b95565d57828244cbb7879b8d3a8f3d20522a/parseutil/parsepath.go#L20-L39) so that a `keyring://` schema could be used to transparently fetch secrets out of kernel keyring (mostly used server-side I believe). Or, further, to enhance our server config to directly read sensitive values from kernel keyring.

Or, via vault agent's [templating functionality](https://developer.hashicorp.com/vault/docs/agent-and-proxy/agent/template), to allow Agent to place fetched secrets into keyring on the client, where available. 

Here, I think we'd welcome pull requests in this direction! 

My 2c. :-)

**Comment by jhmartin** [comment]
Thank you for the detailed analysis!

**Comment by cipherboy** [comment]
Hmm, I can't find the diagram quickly here, but I think this is good enough: https://developer.hashicorp.com/vault/docs/internals/architecture

Essentially, with manual shamir's unseal, there's the following key hierarchy:

```
shamir splits
  =combines-to-form=>
    shamir protected unseal key
      =encrypts=>
        root key
          =encrypts=>
            barrier key ring
              =encrypts=>
                secrets on disk
```

Here, the root key is purged from memory as soon as it is done being used, leaving only the barrier keyring in memory. Secrets that are actively being read/written are accessible of course, but the ability to unseal Vault again (from a memory dump, +/- root key actually being purged from memory/overwritten by the OS) is prohibited. 

I think to protect the barrier keyring, you'd need to have Kernel support for encrypting/decrypting data. Again, a TPM/PKCS#11/... might be more relevant here, and using Seal Wrapping provides the same protection (for critical security parameters/CSPs). 

My 2c., obviously there's defense in depth, but at some point, running on compromised hosts provides limited utility. To be able to read memory, you'd need to have root level access, at which point, how do you even know it is Vault running and not some other compromised software?

**Comment by victorr** [comment]
I am closing this issue since there is no specific feature to implement.

Thank you @jhmartin for your well documented request.

**Comment by rwb-truelime** [comment]
Its May '26 and this thread could not be more important imho @victorr @jhmartin @cipherboy @evanphx 

With all the latest supply chain attacks this should become a global standard (fast): 

> However, what is a good use of this technology, and one I've personally been wanting to see, is a protocol for reading secrets from keyring instead of envvars. E.g., to [parse path](https://github.com/hashicorp/go-secure-stdlib/blob/1a4b95565d57828244cbb7879b8d3a8f3d20522a/parseutil/parsepath.go#L20-L39) so that a keyring:// schema could be used to transparently fetch secrets out of kernel keyring (mostly used server-side I believe). Or, further, to enhance our server config to directly read sensitive values from kernel keyring. Or, via vault agent's [templating functionality](https://developer.hashicorp.com/vault/docs/agent-and-proxy/agent/template), to allow Agent to place fetched secrets into keyring on the client, where available.
