### ISSUE TITLE
docs: Clarify scenarios where allow_bare_domains is considered a security risk.

### ISSUE THREAD

**Issue by c4milo** [hashicorp/vault#2209]
When creating roles in order to generate certificates, `allow_bare_domains` risks are not completely clear to me: 

> allow_bare_domains optional If set, clients can request certificates matching the value of the actual domains themselves; e.g. if a configured domain set with allowed_domains is example.com, this allows clients to actually request a certificate containing the name example.com as one of the DNS values on the final certificate. In some scenarios, this can be considered a security risk. Defaults to false.

I would appreciate expanding a bit more on the risk scenarios, if possible.

**Comment by jefferai** [comment]
Honestly, it's totally up to a given organization! There are some CAs out there that *always* add the bare domain to certificates -- e.g. if you have authenticated `foo.org` and request `x.foo.org` they will always also add `foo.org` to the `x.foo.org` certificate. But, suppose you are using these for internal services where `foo.company` is your intranet but you have many other internal services `hr.foo.company` and `eng.foo.company`. As a security precaution -- not due to an inherent issue, but defense-in-depth -- you may may want to ensure that `eng.foo.company`, which may be managed by a different team than `foo.company`, can never respond to requests for `foo.company` in the case of some internal DNS cache poisoning or some such thing (or simple misconfiguration).

Hope that helps!

**Comment by c4milo** [comment]
That makes sense @jefferai, thanks for clarifying. I didn't have those scenarios in my mind when I was reading the docs.
