### ISSUE TITLE
Service and path question when running against a Consul backend

### ISSUE THREAD

**Issue by dudyk** [hashicorp/vault#2210]
I wanted to ask, if we have two instances of Vault running against the same Consul backend and path but with different service names (or one with service registration disabled), could unsealing both cause data corruption?  
No commands apart from unseal will be sent to the instance with a different service name.

**Comment by jefferai** [comment]
Hi @dudyk ,

Can you please post questions on the mailing list (https://groups.google.com/forum/m/#!forum/vault-tool) rather than in GitHub issues? This gets a lot more eyes on any particular question or idea.

It also prevents problematic issue workflows for questions where either the issue is closed immediately but then discussion continues on a closed issue; or, the issue is not closed, discussion dies down, and the issue remains open indefinitely waiting for further potential replies.

Thanks!
