### ISSUE TITLE
Recycle bin for deleted secrets

### ISSUE THREAD

**Issue by patrickdung** [hashicorp/vault#22211]
**Is your feature request related to a problem? Please describe.**

There are many situations that the secrets are being accidentally deleted.
eg. KV2: keys (the item not the versioned secrets), database secrets, etc.
Users are not aware, new to Vault, etc.
This could happen daily.

**Describe the solution you'd like**

Create feature like recycle bin for deleted secrets.
Maybe users with root token can access it.
Maybe set default retention period for 14 days.

**Describe alternatives you've considered**

I saw the YT video https://www.hashicorp.com/resources/oh-no-i-deleted-my-vault-secret
It is cumbersome to create another instance when we need to restore deleted secrets.

**Explain any additional use-cases**
If there are any use-cases that would help us understand the use/need/value please share them as they can help us decide on acceptance and prioritization.
N/A

**Additional context**
N/A

**Comment by hsimon-hashicorp** [comment]
Is this a feature request for the CLI, UI, or both? Thanks!

**Comment by patrickdung** [comment]
@hsimon-hashicorp 
I think the feature request is for both, thanks.

As a side note, Oracle database has implemented the recycle bin for deleted objects since their version 10g (ten+ years ago). I think there may be some demand from their customers.

**Comment by maxb** [comment]
It is not realistically possible to implement a common recycle bin in Vault, because the nature of secrets is entirely up to the individual secrets engines involved.

Any recycle bin concept would need to be specific to individual secrets engines.

I can kind of see how this might work for KV v2, but I don't think the recycle bin concept is meaningful for the database secrets engine, or most others.

**Comment by VioletHynes** [comment]
Yeah, I think a generic 'recycle bin' doesn't fit with Vault's model. While it might be possible to create some kind of concept for KV secrets that have been `delete`d but not `destroy`ed, I might be missing what kind of problem we'd be solving, since `undelete` already exists. Is there something more that you'd like for APIs like KVV2 `undelete` today?

Ultimately, if you want high levels of reliability, a strategy like in the guide you posted is the best option.

**Comment by patrickdung** [comment]
@VioletHynes

OK, a generic' recycle bin' does not fit all types of secrets. Maybe create recycle bin or undelete feature for other types of secrets.

If an admin/user performed a permanently delete on a wrong item, it would be gone.
![image](https://github.com/hashicorp/vault/assets/38665827/58f85fa9-e2ee-425e-8afc-040626503996)
So I would like KVV2 to have a recycle bin to stored it temporary instead of delete it permanently.

**Comment by VioletHynes** [comment]
Hey there,

We don't think it makes sense to add a second way for Vault to undelete ('undestroy'?) KV secrets. Given that we already have delete protection (delete vs destroy), it would be redundant to add a third delete protection (delete, destroy, and actually destroy?), not to mention, where does this stop. What if something is permanently deleted from the 'recycle bin'?

Undelete doesn't make sense for many kinds of secrets (un-revoking a lease is dangerous territory), which is why I'd scoped the conversation to KV.

Thanks for the issue, but after some discussion we're going to close this one. If you're looking for more data resilience, then the guide you linked in the original post should offer some tips. That's the best 'one size fits all' there is.

**Comment by maxb** [comment]
Hi @VioletHynes - I'd like to share an idea I have about why people may be using the "metadata delete" operation (immediate permanent deletion of all versions) more than they should be:

It's the only way to remove an entry so that it no longer shows up in list operations.

Hence, if your objective is to clean up the tree being browsed by human users, you are forced to bypass all the existing delete protections.

A possible way to mitigate this would be to add an additional kind of list operation to KVv2 - list, but only show entries where the highest data version is not deleted.

Handily, the current list operation is implemented only on the `metadata` path... This new list operation I have proposed would be a good logical fit, for list operations on the `data` path.

Once implemented, this new list operation should probably become the default one shown in the UI and via `vault kv list`, with the existing one that includes deleted and destroyed data becoming "opt in".

@patrickdung What do you think? Would this address your issue?

**Comment by patrickdung** [comment]
@maxb Your last comment is too technical for me (starters). 😃 

For me or my organization, we are going to start using Vault (OSS). Some of the users may just use the Web UI.

From the administrative perspective, I afraid users would perform delete operations accidentally. Like the my previous comment https://github.com/hashicorp/vault/issues/22211#issuecomment-1671181661 and delete operation like these:
![image](https://github.com/hashicorp/vault/assets/38665827/d187b0f1-5670-489d-97f3-98701709914f)

**Comment by maxb** [comment]
If you can't trust the users not to delete bits of configuration they don't understand, they probably shouldn't have access to configure Vault at all...
