### ISSUE TITLE
vault.exe not working on windows

### ISSUE THREAD

**Issue by kamalchoudharyindia** [hashicorp/vault#2222]
Hello Sir ,

I am trying to setup vault on windows 10 but it is not working.

I have run command : vault server -dev
that is working fine and show detail about vault server.

Can you please explain this 3 steps how to perform : 

https://www.vaultproject.io/intro/getting-started/dev-server.html

With the dev server running, do the following three things before anything else:

Launch a new terminal session.

Copy and run the export VAULT_ADDR ... command from the terminal output. This will configure the Vault client to talk to our dev server.

Save the unseal key somewhere. Don't worry about how to save this securely. For now, just save it anywhere.

Do the same as step 3, but with the root token. We'll use this later.

https://www.vaultproject.io/downloads.html

**Comment by jefferai** [comment]
Hi @kamalchoudharyindia 

Can you please post questions on the mailing list (https://groups.google.com/forum/m/#!forum/vault-tool) rather than in GitHub issues? This gets a lot more eyes on any particular question or idea.

It also prevents problematic issue workflows for questions where either the issue is closed immediately but then discussion continues on a closed issue; or, the issue is not closed, discussion dies down, and the issue remains open indefinitely waiting for further potential replies.

Thanks!
