### ISSUE TITLE
Can Vault HTTP API work with Basic Auth, like providing username and password?

### ISSUE THREAD

**Issue by nsehgal** [hashicorp/vault#2287]

**Comment by jefferai** [comment]
Hi @nsehgal ,

Can you please post questions on the mailing list (https://groups.google.com/forum/m/#!forum/vault-tool) rather than in GitHub issues? This gets a lot more eyes on any particular question or idea.

It also prevents problematic issue workflows for questions where either the issue is closed immediately but then discussion continues on a closed issue; or, the issue is not closed, discussion dies down, and the issue remains open indefinitely waiting for further potential replies.

Thanks!
