### ISSUE TITLE
feature request: X509v3 Subject Alternative Names additional types

### ISSUE THREAD

**Issue by s-maj** [hashicorp/vault#2289]
In PKI secret backend only two types of "name" are supported: email or dns. According to RFC 5280 there are other types that can be put in this field, like IP address or OID. Currently, all strings with "@" character are being classified as email and rest of them as dns. IMHO this field could be a parameter without any logic so users can put there whatever they want.

Use case: 
Elasticsearch search-guard-ssl plugin requires OID field in certificate to evaluate if connection comes from trusted host or not.

**Comment by jefferai** [comment]
IP addresses are already supported via the `ip_sans` parameter; this is distinct from `alt_names` to make it more clear whether a value is supposed to be explicitly marked as an IP address or DNS. If you put an IP address in `alt_names` it will be treated as an opaque string blob. You can do the same with OIDs.

**Comment by s-maj** [comment]
I've tried and outcome is like this:
X509v3 Subject Alternative Name:
                DNS:ip-172.16.1.1.internal, DNS:localhost, DNS: oid:1.2.3.4.5.5, IP Address:172.16.1.1
instead of OID type I have DNS type with oid:1.2.3.4.5.5 value. What I would to achieve is OID field with value 1.2.3.4.5.5.

**Comment by jefferai** [comment]
Oh, I thought you just wanted the OID value.

There are no plans to implement this internally, but I'd maybe consider a PR if it wasn't intrusive. However, I didn't find any mention of an OID requirement in the search-guard-ssl repo and I didn't catch anything in a skim of their showing how to configure openssl either. Are you sure this isn't some optional extra requirement? There's really no need to use a specific OID when you can match on anything in the subject (including DNS names or OU values, which will be in 0.6.5), so if search-guard-ssl is requiring this it feels fundamentally broken.

**Comment by jefferai** [comment]
`otherName` -- how you get OID SANs into certs via openssl -- isn't in the docs repo (https://github.com/floragunncom/search-guard-ssl-docs/search?utf8=%E2%9C%93&q=othername) or code repo (https://github.com/floragunncom/search-guard-ssl/search?utf8=%E2%9C%93&q=othername).

**Comment by s-maj** [comment]
I wouldn't call it broken, they're just using some unpopular x509 features. Anyway OID are mentioned here: https://goo.gl/wAwPvG, "Server certificate OID" This is a ticket where are some examples how to generate proper certs in java keytool: https://goo.gl/QdSi8M. More about OIDs: https://goo.gl/0fysqG.  Here is how to generate cert with them using openssl: https://goo.gl/ivvtzh. I'm not going to pretend that I fully understand purpose of OIDs but they seem to be used in enterprise related stuff. 
Anyway, I understand if I want this feature, this is totally up to me to implement this :)

**Comment by jefferai** [comment]
I don't click on shortened links, but regardless, the fact that you can technically use OID SANs doesn't mean it's a broadly compatible feature -- and as I pointed out, there is nothing in the docs or code repo of search-guard-ssl that indicates that this is a requirement.

If this *is* a requirement, you should suggest that they remove it in favor of/supplant it with something more configurable and more broadly compatible -- or at the very least, document it as a requirement with a description of why it is required and no other solution suffices.

**Comment by hex2a** [comment]
it is documented in the `search-guard-docs` repo, the oid value is used to verify if the incoming request is from a trusted node in the cluster or not, to prevent an attacker joining the cluster with a client certificate from the same CA.
https://github.com/floragunncom/search-guard-docs/blob/master/installation.md#server-certificate-oid

**Comment by jefferai** [comment]
That is some weird pseudo-security. It's just a shared secret, which could be put elsewhere on the certificate that has more compatibility. But it doesn't actually buy anything, just causes hassle. If you trust the CA and you trust the path that the issued certs and associated keys take to get to the search nodes, which you must do in this case anyways, you don't need to be checking this shared value, you can just use the DNS name or common name; just give each trusted node a specific DNS SAN.

A much better approach would be to have the administrator feed in the serial numbers of trusted certificates to a whitelist.

> Plus, the oid is also checked whenever a node wants to join the cluster. This prohibits that a malicious attacker can join the cluster by using a client certificate.

There is no evidence in the rest of the description to back up this claim. An attacker with a stolen client certificate will have the correct OID in it. However, doing this also means that there is no way to apply privilege checks simply based on the attributes of the certificate itself because the OID is required, even if the value is set to something totally nonsensical.

I still suggest you contact the search-guard author and ask them for a way to disable this at a minimum and a better design ideally.

**Comment by hex2a** [comment]
the OID field is only set for trusted ES nodes in the cluster, for which all actions are allowed.

A client certificate does not have the OID field set, so an attacker can only impersonate the client from which the certificate was stolen, but can not join the cluster as a fully trusted node.
In the case of a client certificate, ACLs apply.

**Comment by jefferai** [comment]
What you just said doesn't match the docs, which say that the OID field is set for all nodes in order to control access at all, but that any node that has a field *value* that does not match the trusted value has ACL permissions apply.

If the docs are wrong, and the OID field is actually not required, then you can simply make appropriate ACLs to give the nodes whatever permissions you need, right?

**Comment by hex2a** [comment]
as I unterstand this,
the OID field is needed to verify, whether a connection is from a trusted node (must be set to `1.2.3.4.5.5`) or client (not set, or other value):

(trusted) cluster **nodes**  will be issued certificates **with** the OID field set to `1.2.3.4.5.5`

**clients** will be issued certificates either **without** OID field, or another value.

> All certificates used by the nodes on transport level need to have the oid field set to a specific value. By default, this is 1.2.3.4.5.5

**transport level** is referring to cluster-internal communication between trusted **nodes**, whose certificates have the OID field set to `1.2.3.4.5.5`. (replication, etc)

the **HTTP**(S) **API** exposes elasticsearch APIs to **clients** (with ACLs), this API may use client certificates for authentication


> This oid value is checked by Search Guard to identify if an incoming request comes from a trusted node in the cluster or not. In the former case, all actions are allowed, in the latter case, privilege checks apply. Plus, the oid is also checked whenever a node wants to join the cluster. This prohibits that a malicious attacker can join the cluster by using a client certificate.

as both kinds of certificates (cluster node / client) are issued from the same CA, its not enough to just verify the certificate, (as an attacker with a valid client certificate could just connect to the transport API and join the cluster as trusted node), but rather also verify the OID field, which is set to `1.2.3.4.5.5` only for cluster nodes, not clients.

**Comment by jefferai** [comment]
Oh, the passage in the docs doesn't really make it clear that there are two kinds of certs (cluster/client), at least for someone not steeped in its workings.

Comments are the same though: plenty of other very easily parseable and widespread cert attributes could be used for the same purpose, and they really should be whitelisting anyways for an ultimate-trust scenario.

As I said before, I'd consider a PR if it isn't too intrusive, but given that this is a single plugin to a single piece of software I can't promise anything. This is super special-case/special-purpose, so I think it'd depend on what the code looks like.

**Comment by mattupstate** [comment]
@jefferai can you explain why the focus here has been on SearchGuard's implementation? What difference does it make to you what SearchGuard does? The main idea here is to afford end users additional SANs through the Vault APIs, is it not?

**Comment by jefferai** [comment]
@mattupstate Sure, affording end users additional SANs through the API is fine, but there is currently no support within Vault for working with OID SANs. That's not to say they couldn't be added, but they aren't supported right now.

The reason that I suggested asking SearchGuard to revise their implementation is that OID SANs (which really are just custom OID values) are very uncommon ways to check authorization. Apparently they didn't want to do DNS SANs because names can change (ignoring that a DNS SAN does not need to be a resolvable host name), but then they also ignored O/OU values in the certificate's subject, which are *far* more common ways of doing "ensure particular value is in a cert" workflows.

Adding this feature would literally be for a single use case, which is for a single plugin for a single database. If they picked a different value it'd be easier for *ALL* other CAs to generate certs that they can handle. IMHO, they got it wrong and should fix it, rather than requiring everyone else to change their software to accommodate them.

**Comment by jefferai** [comment]
Randomly thought of this ticket so figured I'd point out that this has been supported for a while now.

**Comment by AdrianAbraham** [comment]
I found this ticket while trying to convince Vault to generate Searchguard certificates ... what's the right syntax for other_sans? No matter what I try, OpenSSL tells me the SAN is "othername:<unsupported>". For reference, with EasyRSA I use "--subject-alt-name=RID:1.2.3.4.5.5", which produces a SAN of "Registered ID:1.2.3.4.5.5".
