### ISSUE TITLE
Vault is not operation after restart.

### ISSUE THREAD

**Issue by slivabox** [hashicorp/vault#2312]
Hi,

We have a vault server with DynamoDB backend which has been running for a while without any issues.
Today it hanged (EC2 instance was not available over ssh) so we had to restart it.
After restart we tried to unseal it but it stuck in some weird limbo state:

vault process uses a lot of CPU and RAM any requests through vault client cli end up with:
` net/http: request canceled (Client.Timeout exceeded while awaiting headers)
`
on another hand when I do request with curl to /v1/sys/health the server answers with valid json:
`{"initialized":true,"sealed":false,"standby":false,"server_time_utc":1485846633,"version":"0.6.4","cluster_name":"vault-cluster-7d4356f3","cluster_id":"b1581e99-f016-20dd-f47f-6d526037a528"}
`

We have ~30k keys which are considered to expired and there's a huge traffic between vault and dynamodb.
We've increased Throughput limits (both read and write).

There are no obvious/clear symptoms what might be wrong.

Could anyone suggest what might be wrong or how to debug this issue?

Kind regards,
Ievgen.

**Comment by jefferai** [comment]
Hi @slivabox ,

Vault stores its lease information in memory -- it has to in order to track expiration in a timely manner. When Vault starts it must load all lease information into memory and then process any revocations, which also involve writes back to storage.

If there are 30k items that are expired since Vault went down, it sounds like you must have a *huge* number of leases. Which also suggests a reason why your EC2 instance hung in the first place: I would guess that you ran out of memory.

Usually this kind of behavior can be avoided by determining why you had so many leases in the first place and modifying client behavior. In many cases it's due to lack of re-use of resources; for instance, rather than re-use tokens clients fetch a new token for every request, and the token lifetimes are long (for instance the default 32 days); or a similar pattern for database credentials.

Outside of manually munging Vault's data store, which can have its own dangers, the safest way to resolve this would be to simply increase iops between Vault and Dynamo, possibly increase memory on the Vault server (or at least, monitor it to ensure that you don't run out as its loads leases), and wait; eventually it will load all of your leases and expire the ones that need to be expired.

**Comment by slivabox** [comment]
Hi @jefferai,

Apparently, we had a broken logic - we created new item rather than re-using existing one.
This ended up with this issue which we haven't noticed until it happened.

As I said in the original message we've tried to increase throughput between vault and dynamodb without any outcome.

We ended up with manual deletion of expired items from dynamodb (I know that it might lead to unpredictable behaviour, but we didn't have any other option).


Kind regards,
Ievgen.

**Comment by jefferai** [comment]
Unfortunately increasing throughput might help but won't solve it if the problem is swapping due to OOM or not waiting long enough for all operations to complete. As long as operations were still ongoing between Vault and Dynamo you probably didn't give it enough time, unfortunately.
