### ISSUE TITLE
feature request: make AWS IAM user prefix configurable

### ISSUE THREAD

**Issue by blalor** [hashicorp/vault#2318]
When creating an IAM user, the `vault-` prefix is [hardcoded](https://github.com/hashicorp/vault/blob/c44f1c9817955d4c7cd5822a19fb492e1c2d0c54/builtin/logical/aws/secret_access_keys.go#L63).  I'd like to be able to configure this when mounting the secret backend.  This would allow for multiple user management scopes within a single AWS account.  

The IAM user provided to Vault to manage dynamic credentials has [a policy](https://github.com/hashicorp/vault/blob/v0.6.4/website/source/docs/secrets/aws/index.html.md#root-credentials-for-dynamic-iam-users) with a resource restriction like `arn:aws:iam::ACCOUNT-ID-WITHOUT-HYPHENS:user/vault-*`.  I'd like to be able to create two Vault users in this account, dev and test, with restrictions like `arn:aws:iam::…:user/vault-dev-*` and `arn:aws:iam::…:user/vault-test-*`.  This is currently not possible.

**Comment by jefferai** [comment]
@joelthompson Putting this on your radar

**Comment by joelthompson** [comment]
@blalor -- what about configuring the Path that IAM users get created at? So one role would create a user at `arn:aws:iam::123456789012:user/dev/vault-...` and the other would be at `arn:aws:iam::123456789012:user/test/vault-...` That feels more natural to your use case, and it also means that configuring a longer prefix wouldn't run into username length restrictions. (The user names should still be configured to begin with the `vault-` prefix to prevent name collision -- IAM usernames must be unique within an AWS account, not just within a specific path.)

**Comment by povils** [comment]
What is the state of this?

**Comment by joelthompson** [comment]
Hi there @povils -- speaking personally (i.e., as somebody not an employee of HashiCorp but as a community member who contributes to AWS integrations with Vault), I wanted to get a little more information on the use case before just writing some code. As I mentioned above, I think specifying the Path parameter would actually be a bit cleaner and provide a better user experience. For example, IAM usernames are limited to 64 characters; the ability to specify an arbitrary prefix would have to limit the length of that prefix to ensure Vault could still generate unique usernames. However, the Path parameter has an independent limit (512 characters) and I think would provide a better user experience.

What are your thoughts on this? Would being able to specify the path, rather than the username prefix, solve your usecase? If not, can you give some more details about what you're trying to do and why the ability to choose a Path wouldn't help?

**Comment by povils** [comment]
Hey @joelthompson , thanks for response.
The use case is basically the same as OP has - the need to distinguish users in order to give right permissions. Specially when username is created using token display name and sometimes this display name is uid(like nomad allocation id). I think user paths would definitely solve this problem as you mentioned :) To be honest I would be interested even to implement it

**Comment by joelthompson** [comment]
Hey @povils -- just wondering if you were planning on submitting a PR? If not, I'll probably pick this up in the next couple of weeks, just didn't want to duplicate efforts.

**Comment by povils** [comment]
Hi @joelthompson. Yes, I am planning :)

**Comment by deenar** [comment]
Hi @joelthompson . I have a similar requirement, but I would like the AWS IAM user suffix configurable when generating STS tokens, currently this  "arn:aws:sts::867407613858:federated-user/vault-1550629889-9348", which is a arn:aws:sts::867407613858:federated-user/vault-$timestamp-$uuid, where $timestamp and $uuid are vault generated. These cant be correlated to the application user generating this call. The user name is propogated by AWS in many logs, including s3 access logs. 

I am not sure if you change will cover the sts case in the func genUsername(displayName, policyName, userType string) (ret string, warning string)  function too.
