### ISSUE TITLE
Incorrect display

### ISSUE THREAD

**Issue by stryder123451** [hashicorp/vault#23629]
**Describe the bug**
![image](https://github.com/hashicorp/vault/assets/77195946/1d73573f-16a1-4981-a3ec-94c56aab9462)

**Expected behavior**
Correct display

Environment:

Vault Server Version: 1.7.2
Vault CLI Version: 1.7.2

**Comment by divyaac** [comment]
Hi @stryder123451 would you mind providing a larger image for context on what page you are expecting to see the version? 
Also what you clicked on to get that page?

**Comment by stryder123451** [comment]
@divyaac  
Hi, page "secrets", this is  happens, even without clicking on the secret view button

![image](https://github.com/hashicorp/vault/assets/77195946/df8b3c41-b2bf-45ca-bd17-b7caaba2450f)

**Comment by stryder123451** [comment]
@divyaac , Hi, page "secrets", this is  happens, even without clicking on the secret view button
![image](https://github.com/hashicorp/vault/assets/77195946/035f455c-79dc-4aea-93ff-f0373dda5e1f)

**Comment by Monkeychip** [comment]
@stryder123451 this has been fixed in the most recent supported versions. I checked out the 1.13.x release branch and this is not an issue there, though it may have been fixed on an even earlier version as well. 
![image](https://github.com/hashicorp/vault/assets/6618863/45c2ceba-de74-4862-9598-b6ae85110ccd)
