### ISSUE TITLE
1.15 web-ui kv2 -- issue adding new lines to secret in json view

### ISSUE THREAD

**Issue by NetzWerkPlanDeveloper** [hashicorp/vault#23940]
**Describe the bug**
When editing a secret via web interface in the kv2 engine, trying to add a new line to the secret in json view results in the cursor jumping to the first line of the file.

If you add a `,` or `{` at the end of a line before trying to add a new line with the enter key, it works. 
I'm not sure if this is intended and supposed to be some kind of json validation while the secret is being edited, or if it's just a bug.

Either way, it makes it impossible to insert something from the clipboard.

The behavior in kv1 hasn't changed, so I assume it's related to [22559](https://github.com/hashicorp/vault/pull/22559).

**To Reproduce**
1. Create secret in kv2
2. Create new secret version
3. Switch to json view
4. Attempt to add new line by pressing enter

**Environment:**
* Vault Server Version: 1.15.1

**Comment by timonych** [comment]
I have already open topic. but have no responce on it: https://discuss.hashicorp.com/t/strange-behaviour-in-json-editor-in-vault-1-15-0-kv2/59259

Btw, I have found that it will as previous if You are using previous link.
E.g.

**Comment by hashishaw** [comment]
Thank you for the report! We are working on getting a fix in. 

As far as the URL slashes, there is not a way to disable those. We changed to encoded paths for KV v2 so that we can make fewer API calls while managing KV secret data within the UI. We determined that having "ugly" URLs was a reasonable tradeoff for the value we get from minimizing the calls, as well as other organizational benefits. We welcome feedback around how folks are using the UI and other improvements we can make, so please keep those coming along with reports of broken behavior like this one. Thanks!
