### ISSUE TITLE
Root Token: Expiration and Renew

### ISSUE THREAD

**Issue by tboussar** [hashicorp/vault#2395]
Hello,

we got root token on our platform
for security reason we would like to create root token with a TTL (if a token is mislaid he  will be invalidated after some time)

1. Is it possible to renew root token regularly (example every 3 months renew half of root tokens)?
2. Give to all root token a TTL / expiration date?
(in doc this sentence "a root token with an expiration cannot create a root token that never expires" indicate that it's possible)

Thanks

**Comment by jefferai** [comment]
Hi @tboussar ,

Can you please post questions on the mailing list (https://groups.google.com/forum/m/#!forum/vault-tool) rather than in GitHub issues? This gets a lot more eyes on any particular question or idea.

It also prevents problematic issue workflows for questions where either the issue is closed immediately but then discussion continues on a closed issue; or, the issue is not closed, discussion dies down, and the issue remains open indefinitely waiting for further potential replies.

Thanks!
