### ISSUE TITLE
-field option for HTTP API?

### ISSUE THREAD

**Issue by jcrowthe** [hashicorp/vault#2421]
In the CLI, we have the ability to run 
`vault read -field=test secret/something` and retrieve only the value of that one field, `test`. However, I have been unable to find what the equivalent is when using the HTTP API.

I have tried the following and a few other variations:
`curl -X GET -H "X-Vault-Token:$VAULT_TOKEN" https://example.com/v1/secret/something?field=test`

Am I missing something?

**Comment by vishalnayak** [comment]
`-field` is a CLI magic. The API always returns a full response.

**Comment by ksupriyasingh** [comment]
so is there any way which can be used to get the specific field using api?

**Comment by itssudhirhere** [comment]
@jefferai , @ksupriyasingh 
Yes you can access specific field by using following CURL command

curl -X GET -H "X-Vault-Token:$VAULT_TOKEN" https://example.com/v1/secret/something **| jq -r ".data.data.test"**
instead of below command.
curl -X GET -H "X-Vault-Token:$VAULT_TOKEN" https://example.com/v1/secret/something?field=test

**Comment by ira-gordin-sap** [comment]
Is it still not fixed? Not always you have jq.
