### ISSUE TITLE
TLS connection issue

### ISSUE THREAD

**Issue by raffaelespazzoli** [hashicorp/vault#2474]
Hi I'm developing a Vault client using the Vault client go package and I'm getting an error establishing a TLS connections.
This is my client error message:
```
time="2017-03-12T15:25:37Z" level=info msg="error creating wrapped token for pod (vault-example-4-pt6gw), error: Post https://vault.vault-controller.svc.cluster.local:8200/v1/auth/token/create: x509: certificate signed by unknown authority" 
```

This is vault's error message (log_level=debug)
`2017-03-12 15:30:32.144129 I | http: TLS handshake error from 10.1.2.1:57468: EOF`

Vault is configured with certificates and the Vault client is configured with a VAULT_CACERT that verifies the certificate, in fact curling behaves correctly:
```
sh-4.2# curl --cacert /var/run/secrets/kubernetes.io/serviceaccount/service-ca.crt https://vault.vault-controller.svc.cluster.local:8200/v1/auth/token/create
{"errors":["missing client token"]}
```

Also adding `VAULT_SKIP_VERIFY=true` to the client environment variables doesn't change the outcome.

My hypothesis is that I'm not initializing the client correctly, I need to some guidance in diagnosing this problem.

Here is how the vault client is initialized:

```
	//creates the vault config
	log.Debugln("creating default vault config")
	vConfig := api.DefaultConfig()
	log.Debugln("created default vault config")

	//creates the vault client
	log.Debugln("creating vault client")
	vaultClient, err = api.NewClient(vConfig)
	if err != nil {
		log.Fatalln(err)
	}
	log.Debugln("created vault client")
```

Thanks
Raffaele

**Comment by vishalnayak** [comment]
Setting the CA cert via the environment variable `VAULT_CACERT` should do it.

Please post questions on the mailing list (https://groups.google.com/forum/m/#!forum/vault-tool) rather than in GitHub issues. This gets a lot more eyes on any particular question or idea.

It also prevents problematic issue workflows for questions where either the issue is closed immediately but then discussion continues on a closed issue; or, the issue is not closed, discussion dies down, and the issue remains open indefinitely waiting for further potential replies.
