### ISSUE TITLE
S3 storage backend and LDAP auth

### ISSUE THREAD

**Issue by codybuell** [hashicorp/vault#2477]
Running Vault 0.6.5 with an S3 bucket for the backend and authenticating users through LDAP.  Unsealing the vault and doing any number of reads or writes with the root token works properly.  As soon as a user authenticates with LDAP all users get:

```
Error checking seal status: Error making API request.

URL: GET https://xxxxxxxxxxxx:8200/v1/sys/seal-status
Code: 500. Errors:

* RequestError: send request failed
caused by: Get https://xxxxxxxxxxxxxxxxxx.s3.amazonaws.com/core/cluster/local/info: read tcp xxx.xxx.xxx.xxx:49784->xxx.xxx.xxx.xxx:443: read: connection reset by peer
```

Enabled logging on the S3 bucket but not getting anything other than AWS console activities.  Vault's AWS credentials have a policy with full control of the bucket in question. Any ideas?

**Comment by vishalnayak** [comment]
@codybuell This is strange. Not getting any ideas to suggest but since `seal-status` does not need a Vault token to operate, it might not have anything to do with LDAP auth though.

The client to interact with S3 is not refreshed between Vault token authentications. If it worked before authentication, it should work after as well. Were there any other actions you took in between?

**Comment by jefferai** [comment]
@codybuell Also, two questions:

1) Can you try with 0.7 beta in case this is an issue in the aws-sdk library that has been fixed? (They tend to make assumptions about using global variables and this has caused problems in the past)

2) If it doesn't, would you be okay building your own version of Vault for testing?

**Comment by codybuell** [comment]
@vishalnayak Between the ldap auth and error listed no.  It's immediate for both users.  @jefferai I'll give the 0.7 beta a go and report back.  Don't mind building a custom version.

**Comment by jefferai** [comment]
Hi @codybuell ,

First up would be to try the beta version, but if that doesn't work, next would be to try going into `physical/s3.go` in current `master` and adding a line between lines 78 and 79 with the following:

`HTTPClient: cleanhttp.DefaultPooledClient(),`

so that the block looks like:
```go
	s3conn := s3.New(session.New(&aws.Config{
		Credentials: creds,
		HTTPClient: cleanhttp.DefaultPooledClient(),
		Endpoint:    aws.String(endpoint),
		Region:      aws.String(region),
	}))
```
I'm not sure that will help, but it can't hurt, and we've seen problems in the past with AWS stomping around on (or being stomped on by) global vars set in other packages.

@vishalnayak BTW, see any reason not to just make ^ the default?

**Comment by vishalnayak** [comment]
I don't see any reason not to use a pooled client.

**Comment by codybuell** [comment]
0.7 beta has the same result.  Trying with suggested changes next.

**Comment by codybuell** [comment]
...Sigh...  Looks like its a VPC routing issue.  Traffic is filtering through a firewall that is misbehaving and blocking connections once a user has authenticated.  Solution is to add a resource endpoint to S3 in the VPC.  Bypasses the fw and resolves the issue.  Thanks for the help and apologies for the wild goose chase.

**Comment by jefferai** [comment]
Glad it's working!
