### ISSUE TITLE
PKI backend doesn't enforce cert CN uniqueness

### ISSUE THREAD

**Issue by FransUrbo** [hashicorp/vault#2487]
I've successfully been able to create three identical host certs using a command line like:

```
vault write -format=json pki/issue/example-dot-com common_name=blah.example.com alt_names=whatever.example.com
```

This without the previous cert being revoked.

Using OpenSSL as a CA "in the shell" won't allow this, it will reject the new cert before it's signed.

So I don't think Vault should allow this either. PREFERABLY, the old cert should be automatically revoked, before the new one is issued.

Because there's no easy way to list the certs CN, only their serial number, it makes things more difficult (or at least time consuming) to programatically check ALL certs for their CN before creating a new. Which I don't think should be up to the client. It's up to the CA...

**Comment by jefferai** [comment]
OpenSSL absolutely allows it. What you mean to say is easy-rsa doesn't allow it. Plenty of other CA software and commercial CAs do.

 Regardless, this behavior is very much by design and will not be changed. There are many use cases for this, from fetching a new cert before your old one expires to using certs with the same CNs across many instances of a microservice. If you are authorized to fetch a cert with a particular CN, there's not much reason to artificially limit this.
