### ISSUE TITLE
500s During Mass Token Revoke

### ISSUE THREAD

**Issue by cpgravlee** [hashicorp/vault#2515]
The issue we are having is that while Vault is revoking a large amount of tokens it is unable to process additional requests and responds with a 500 error.  The TTL on all of our tokens is the default (32 days).  Our tokens are not created in batches, but are created when necessary by certain microservices.  My question is do token revokes occur immediately after the TTL has expired, or do they group up and occur during one single garbage collection event?

The following image shows a timeline of the telemetry output for our Vault cluster.  As you can see in the image revoke-tree is called tens of thousands of times during a short period.
![Vault Telemetry](https://cloud.githubusercontent.com/assets/15351119/24156293/8cc4307e-0e2c-11e7-9b31-0e486edaebbf.png)

Vault Version:
`Vault v0.6.3 ('27aff4397f6fe6cf741fbc967adf863347c0beaf+CHANGES')`

Backend:
```
"backend": {
    "consul": {
      "address": "consul.url:8500",
      "path": "vault",
      "disable_registration": "true",
      "advertise_addr": "https://vault.url:8200"
    }
  }
```

**Comment by jefferai** [comment]
Vault attempts to revoke tokens immediately upon expiration. From your chart it seems like the uptick in revoke calls also correlates strongly with an uptick in requests made to Vault, which suggests that the revocation calls might be the work of some external actor.

**Comment by adkhare** [comment]
@jefferai we are not calling revokes externally. we rely on vault to make it expire. the gets spike might be retries on our application connecting to vault.

**Comment by jefferai** [comment]
The likely cause in this case is that those tokens are generating large numbers of leases. When a token is revoked all of its leases must be revoked as well, so if you have 1000 leases generated by each token, each token revoke call will be very expensive.

**Comment by adkhare** [comment]
@jefferai we use userpass authentication to authenticate and never renew leases. But we use the same token to transact with vault for various amounts of reads and writes which i guess are different leases for every read/write. 

What is the recommendation on reducing leases and maybe potentially reduce auth calls?

What is the industry-wide practice for this?

**Comment by jefferai** [comment]
> But we use the same token to transact with vault for various amounts of reads and writes which i guess are different leases for every read/write.

What reads/writes? Whether it generates leases depends on what it is...which backend (and also which version of Vault).

**Comment by adkhare** [comment]
@jefferai it reads and write to generic backend.

we are on vault 0.6.3

**Comment by jefferai** [comment]
Generic backends don't issue leases. So if that's all that's happening it seems likely it's purely down to tokens. Do you have access to the underlying Consul cluster? Can you get some metrics around the number of keys under sys/expire/id in various folders, e.g. sys/expire/id/ at the top level and sys/expire/id/auth/userpass?

**Comment by adkhare** [comment]
@jefferai 
v1/kv/vault/sys/expire/id
328946

v1/kv/vault/sys/expire/id/auth/userpass
328938

v1/kv/vault/sys/expire/token
15

v1/kv/vault/sys/expire/id/pki
15 

v1/kv/vault/sys/expire/id/auth/token
10

**Comment by jefferai** [comment]
Hi @adkhare ,

That suggests that something is creating huge numbers of tokens via userpass, and large chunks of them are expiring at once (so they're probably also being created in a quick loop). Generally speaking when we see this it's because of people or processes grabbing new tokens for every operation in Vault rather than reusing existing tokens. Each of those tokens generates storage entries, leases that must be tracked in Vault's memory and loaded on startup, and so on.

**Comment by adkhare** [comment]
@jefferai we use microservices architecture and every instance of microservice authenticates itself with vault which then generates these amount of tokens.

We dont have any way of knowledge about how we can reuse tokens across different instances of the same microservice. Any help on this or the overall industry-wide usage of vault in this specific usecase would be greatly appreciated.

**Comment by jefferai** [comment]
You don't need to reuse tokens across instances, but this usage suggests that you have a lot of churn with your instances but long token lifetimes. You would probably be well served by reducing your token lifetimes from 32 days to however long your microservices are actually expected to last.

Generally speaking as far as how people are doing this in industry, they're not using userpass, because that has a problem of getting the user/password to instances. Instead they're using an orchestration system (Nomad, Mesos, etc.) and using either built-in or add-on capabilities to get Vault tokens to instances in secure ways by having the orchestration agents act as the sources of truth. Additionally, rather than use token lifetimes, we usually recommend (and some of these orchestration capabilities require) using periodic tokens for services, so that the tokens are tied pretty heavily to the lifetime of that particular service.

**Comment by adkhare** [comment]
We are using mesos for our containers and would like to know how vault is integrated with Mesos.

**Comment by jefferai** [comment]
There is nothing first party but there are some third party integrations such as https://github.com/ChannelMeter/vault-gatekeeper-mesos
