### ISSUE TITLE
Vault Enterprise

### ISSUE THREAD

**Issue by sbatchu0108** [hashicorp/vault#2541]
I was going through vault enterprise documentations, came across this feature saying primary cluster and secondary cluster. Is it an active-active setup ? I see the documentation saying secondary performs operations that are done by primary cluster but if user trying to modify the state it will redirect to primary cluster. I was confused if it an active-active setup or active-standby setup, just to clarify things i was posting this question.

The other question was in vault opensource, i have 3 vault nodes where node 1 is active and node2,3 are standby. If i plan to use vault enterprise then assume 3 nodes are in east region and 3 nodes are in west region, so is there active node per each region or just one active node in east and all other are standy nodes ? I am trying to get a bigger picture in general so that we can start looking at our existing enterprise license.

**Comment by jefferai** [comment]
Hi @sbatchu0108 ,

It's not active-active but it's also not active-standby. It's more like a read replica model where many requests can be handled by the local secondary cluster but anything changing underlying state/configuration gets transparently handled by the primary. (Details are at https://www.vaultproject.io/docs/internals/replication.html.)

I can't really answer your other question because I'm not sure if you mean "primary" or if you mean "active" as it applies to Vault's HA. Generally the answer is "you can set it up any way that you want", though...for HA active/standbys need to share a data store; for replication they don't (but each cluster participating in replication can itself be an HA cluster with active/standbys).

**Comment by sbatchu0108** [comment]
@jefferai In 0.7 version we have primary and secondary clusters defined, so what i was asking is in primary cluster lets assume we have 3 nodes, so how are these nodes defined like all these are in active mode or just one node is in active mode within the cluster.

**Comment by jefferai** [comment]
Hi,

In the primary cluster there is one active node given a set of nodes participating in HA. The same can be true of secondaries. That's why you have a primary/secondary _cluster_ rather than _node_; we mean a given HA cluster.
