### ISSUE TITLE
Error listing ksm/records: Error making API request.

### ISSUE THREAD

**Issue by naveen1583** [hashicorp/vault#25525]
I was able to enable a ksm plugin as per the keeper documentation listed [https://docs.keeper.io/secrets-manager/secrets-manager/integrations/hashicorp-vault](url) and configured a Secrets Manager Connection as well. But when I try to list secrets `vault list ksm/records` I get this error

vault list ksm/records
Error listing ksm/records: Error making API request.

URL: GET http://<vault-ip>:8200/v1/ksm/records?list=true
Code: 500. Errors:

* 1 error occurred:
	* error during POST request: Post "https://keepersecurity.com/api/rest/sm/v1/get_secret": read tcp <vault-ip>:34496->100.25.27.45:443: read: connection reset by peer

**Plugin Information**
Name as it would appear listed: ksm
Plugin type (secrets/auth/database): secrets
Repository link: https://github.com/Keeper-Security/secrets-manager/releases

**Comment by austingebauer** [comment]
Hi @naveen1583. I'm not seeing the keeper secrets manager plugin as a supported Vault integration or one that's endorsed as a [community integration](https://developer.hashicorp.com/vault/integrations). I'm also not seeing enough details here to be able to help out. I suggest you ask the folks that maintain that plugin on their GH repo. It does appear that the 500 is coming from the POST to the keeper security URL.

I'm going to close this issue. If you think there is a Vault bug, please reopen with reproduction steps. Otherwise questions can be directed to [Vault discuss](https://discuss.hashicorp.com/c/vault/30) forum.

**Comment by naveen1583** [comment]
Thank you, @austingebauer We were able to find the issue, and it is the firewall blocking the egress reaching the keeper security API.
