### ISSUE TITLE
The Vault browser cli can't read the plugin secrets

### ISSUE THREAD

**Issue by naveen1583** [hashicorp/vault#25620]
Hello, I've integrated the hashicorp-vault server with Keeper security, I can list the passwords from the vault server cli but not from the browser cli. 

From the server: 
![image](https://github.com/hashicorp/vault/assets/98860391/01b735bb-8646-4479-9174-7b4b0f502875)

browser cli:
![image](https://github.com/hashicorp/vault/assets/98860391/5aae08ce-1df8-449a-9d05-c8f9d9b44045)

**Comment by ram-parameswaran** [comment]
has this worked before? Have you recently moved to 1.15.4?

**Comment by naveen1583** [comment]
I have never tired, it's the first time. It's been a while since I started using 1.15.4 but I didn't use any other versions.

**Comment by hashishaw** [comment]
Hi @naveen1583, thank you for the report. I think this is an issue with the record uid being passed as an attribute rather than in the path. If the plugin supports path-based access, I would try that instead (eg. `read ksm/record/my-uid`). 

The Web REPL is really just a convenience tool for accessing the API, so if the suggestion above doesn't work the next step would be to provide the API URL that is the equivalent for that command, and I can look at how we may be able to support this use case.
