### ISSUE TITLE
PGP encrypted key shares stored by vault

### ISSUE THREAD

**Issue by OursDesCavernes** [hashicorp/vault#2579]
# Context
We are setting up a vault cluster (Consul backend) to be used by several different entities (let's say 5) and we are writing a foolproof procedure for a distributed and remote rekey ceremony using GnuPG.
Everybody agreed on 3 key shares to unseal the vault.
We have one operator team with a key share and root token, and 4 security officers from other entities with one key share each. 

# Flaw in the process
The operator initiates the rekey process with all the GPG identities and his key share then asks other key holders to do the same. Every one can check the provided GPG identities so its fine until here.

The flaw is when the 3rd security officer is providing his key share. We don't know which officer will be the 3rd and the new keys could be easily lost (power fail or BSOD before the keys are securely stored, manipulation error, ...)

# Possible solutions

1. Add an option to the rekey command that stores in the vault the encrypted key shares so that they can be pulled out by anyone with a matching policy. (prefered) 
2. Snapshot Consul before rekey to reload the previous master key => We loose RTO 0 and RPO 0 during the rekey process and need to manage that.
We will also snapshot consul in solution 1.

What do you think ?

**Comment by jefferai** [comment]
When you rekey (not init) you can have the PGP keys be backed up by Vault so that in case the keys are lost by the operator they can be retrieved.

Someone was going to implement this for init but dropped off radar. We don't consider this a big problem for initing though, since there's by definition nothing in Vault at that point. If the keys are lost right after init, simply wipe and start over.
