### ISSUE TITLE
[Please release a new api tag which fixed CVE-2024-2048 vulnerability]

### ISSUE THREAD

**Issue by kevin-zhang-dev** [hashicorp/vault#25902]
**Describe the bug**

The [CVE-2024-2048](https://nvd.nist.gov/vuln/detail/CVE-2024-2048) security vulnerability was discovered during a virus scan.

So I want to check two questions:

1. Which version of Vault does the vault/api version 1.12.0 use?
2. Does the vault/api package with 1.12.0 version have the CVE-2024-2048 security vulnerability?

**To Reproduce**
1. go.mod in the service has the dependency of github.com/hashicorp/vault/api v1.12.0
3. Run virus scan.
4. Found the [CVE-2024-2048](https://nvd.nist.gov/vuln/detail/CVE-2024-2048) security vulnerability

**Expected behavior**
Please release a new api tag which fixed CVE-2024-2048 vulnerability.

**Environment:**
* Vault API Version (1.12.0): github.com/hashicorp/vault/api v1.12.0

Vault server configuration file(s):

```hcl
# github.com/hashicorp/vault/api v1.12.0
```

**Additional context**

**Comment by mickael-hc** [comment]
Hi Kevin, thanks for opening this issue.

Vault's API version (`vault/api`) follows versioning that is distinct from Vault (the binary). The API package is not vulnerable to CVE-2024-2048, and may be a false positive from your scanning tool.

I'll be closing this issue, but feel free to reach out to security@hashicorp.com to report any security issues in the future.

**Comment by echo-qin** [comment]
@mickael-hc thanks for the response. I'm in the same team with Kevin. We think it's a false positive as well.

We'll communicate with the scanner team but is there any chance you know which version of vault the vault api 1.12.0 uses? We understand that they are in different release series but our scanner team would require us to provide the vault version. Thanks.

**Comment by mickael-hc** [comment]
Yesterday we pushed a new tag https://github.com/hashicorp/vault/tree/api/v1.12.1. Perhaps you can try using it to see if it resolves the issue you are observing with your scanner(let us know if it does).

Vault depends (on a specific revision/version/tag) vault/api, not the other way around. In the case of Vault 1.15.6 (the most recent release), it uses Vault API 1.10.0 https://github.com/hashicorp/vault/blob/v1.15.6/go.mod#L156

**Comment by hessamalipour** [comment]
@mickael-hc We pushed a new Vault tag, 1.19.5, and AWS Inspector scanned it. Strangely, some vulnerabilities showed up again (many vuks) —even though these issues were resolved last year! Might some changes are reverted?

<html><head></head><body>
CVE-2024-2048 | github.com/hashicorp/vault | HIGH | Vault  and Vault Enterprise (“Vault”) TLS certificate auth method did not  correctly validate client certificates when configured with a non-CA  certificate as trusted certificate. In this configuration, an attacker  may be able to craft a malicious certificate that could be used to  bypass authentication. Fixed in Vault 1.15.5 and 1.14.10.


CVE-2024-9180 | github.com/hashicorp/vault | HIGH | A  privileged Vault operator with write permissions to the root  namespace’s identity endpoint could escalate their own or another user’s  privileges to Vault’s root policy. Fixed in Vault Community Edition  1.18.0 and Vault Enterprise 1.18.0, 1.17.7, 1.16.11, and 1.15.16.

CVE-2023-5954 | github.com/hashicorp/vault | HIGH | HashiCorp  Vault and Vault Enterprise inbound client requests triggering a policy  check can lead to an unbounded consumption of memory. A large number of  these requests may lead to denial-of-service. Fixed in Vault 1.15.2,  1.14.6, and 1.13.10.

CVE-2023-24999 | github.com/hashicorp/vault | HIGH | HashiCorp  Vault and Vault Enterprise’s approle auth method allowed any  authenticated user with access to an approle destroy endpoint to destroy  the secret ID of any other role by providing the secret ID accessor.  This vulnerability is fixed in Vault 1.13.0, 1.12.4, 1.11.8, 1.10.11 and  above.

CVE-2023-5077 | github.com/hashicorp/vault | HIGH | The  Vault and Vault Enterprise ("Vault") Google Cloud secrets engine did  not preserve existing Google Cloud IAM Conditions upon creating or  updating rolesets. Fixed in Vault 1.13.0.

CVE-2020-8911 | github.com/aws/aws-sdk-go | MEDIUM | A  padding oracle vulnerability exists in the AWS S3 Crypto SDK for GoLang  versions prior to V2. The SDK allows users to encrypt files with  AES-CBC without computing a Message Authentication Code (MAC), which  then allows an attacker who has write access to the target's S3 bucket  and can observe whether or not an endpoint with access to the key can  decrypt a file, they can reconstruct the plaintext with (on average)  128*length (plaintext) queries to the endpoint, by exploiting CBC's  ability to manipulate the bytes of the next block and PKCS5 padding  errors. It is recommended to update your SDK to V2 or later, and  re-encrypt your files.

CVE-2024-2660 | github.com/hashicorp/vault | MEDIUM | Vault  and Vault Enterprise TLS certificates auth method did not correctly  validate OCSP responses when one or more OCSP sources were configured.  This vulnerability, CVE-2024-2660, affects Vault and Vault Enterprise  1.14.0 and above, and is fixed in Vault 1.16.0 and Vault Enterprise  1.16.1, 1.15.7, and 1.14.11. 

CVE-2021-38554 | github.com/hashicorp/vault | MEDIUM | HashiCorp  Vault and Vault Enterprise’s UI erroneously cached and exposed  user-viewed secrets between sessions in a single shared browser. Fixed  in 1.8.0 and pending 1.7.4 / 1.6.6 releases. 

CVE-2023-0665 | github.com/hashicorp/vault | MEDIUM | HashiCorp  Vault's PKI mount issuer endpoints did not correctly authorize access  to remove an issuer or modify issuer metadata, potentially resulting in  denial of service of the PKI mount. This bug did not affect public or  private key material, trust chains or certificate issuance. Fixed in  Vault 1.13.1, 1.12.5, and 1.11.9. 

CVE-2023-2121 | github.com/hashicorp/vault | MEDIUM | Vault  and Vault Enterprise's (Vault) key-value v2 (kv-v2) diff viewer allowed  HTML injection into the Vault web UI through key values. This  vulnerability, CVE-2023-2121, is fixed in Vault 1.14.0, 1.13.3, 1.12.7,  and 1.11.11.

**Comment by mickael-hc** [comment]
Hello @hessamalipour these fixes were not reverted, they are false positives due to a change in Golang 1.24 described in https://tip.golang.org/doc/go1.24 

> The go build command now sets the [main module's version](https://tip.golang.org/pkg/runtime/debug#BuildInfo.Main) in the compiled binary based on the version control system tag and/or commit.

This may result in some scanners not being able to detect the version of the package used and reporting incorrect vulnerabilities. We'll look into making changes to the build commands for the upcoming release

**Comment by hessamalipour** [comment]
@mickael-hc Thank you for clarification!
