### ISSUE TITLE
Feature Request - AWS Secret Backend: Add RoleSessionName support to STS

### ISSUE THREAD

**Issue by yakireliyahu87** [hashicorp/vault#2615]
Hey,
Looking at the documentation of ["Generating IAM with STS"](https://www.vaultproject.io/api/secret/aws/index.html#generate-iam-with-sts), which is intended to assume roles (whether local/cross-account), I noticed that there's no way to assign this assumed role a custom "Session Name".

This is possible when using the [AWS API directly](http://docs.aws.amazon.com/STS/latest/APIReference/API_AssumeRole.html) using the RoleSessionName Identifier.

Will it be possible to add a parameter "session_name" to the payload of the API request to Vault, so the assume-role operation will include it?

This would be very helpful when the same role is assumed multiple times by different users in our system, and will allow to inspect user actions via CloudTrail.

In my case, my system will need to assume a role in another AWS account multiple time (one time per user in my system), and i would like to know which user performed a certain operation on the target AWS account (using CloudTrail).

Thanks,
Yakir.

**Comment by mdgreenfield** [comment]
While this issue is to support a `session-name` parameter when retrieving STS credentials should be ok from an authenticated Vault request I'd actually like to see something implemented more along the lines of the SSH plugin where an identity template can be passed into the role configuration (see https://github.com/hashicorp/vault/pull/7548).

The problem I have with the current `RoleSessionName` format is that it is pseudo-random. https://github.com/hashicorp/vault/blob/d9ee6252bfe3476adef79886a1108d41353505bb/builtin/logical/aws/secret_access_keys.go#L64

And because searching CloudTrail logs by username does not allow for globs or partial matching it means that the CloudTrail logs must be downloaded and post-processed.

One suggestion to help improve tracing between Vault audit logs and CloudTrail logs would be to include the `role_session_name` in the `/aws/sts/:name` response. Vault admins would be required to configure [`audit_non_hmac_response_keys`](https://www.vaultproject.io/api-docs/system/mounts#audit_non_hmac_response_keys-1) but short of making the `RoleSessionName` deterministic I think this could be a fine approach.

**Comment by mechastorm** [comment]
I think the original request for this feature could be resolved by this PR ? https://github.com/hashicorp/vault/pull/11345

**Comment by vishalnayak** [comment]
Fixed by #11345
