### ISSUE TITLE
The term physical backend is confusing, Can Storage backend be used instead.

### ISSUE THREAD

**Issue by gautamk** [hashicorp/vault#262]
The term physical backend feels quite confusing in terms of its function. 
Using Storage backend would make it clear that data is actually stored on this backend.

**Comment by certifiedloud** [comment]
When I first started reading the docs and the code I thought the same thing. It might be worth changing for new comers.

**Comment by armon** [comment]
The docs should only refer to things as "Secret" and "Storage" backends, so please let us know where that is missing. At this point, I don't think it's worth changing in the code itself. Few people dive in there, and it should be fairly clear after a few minutes. Of course, I have the bias of staring at it for a few months :)

**Comment by certifiedloud** [comment]
[Here's one](https://github.com/hashicorp/vault/blob/1e7bdad06c7ab82de300fe6c686e954e22cb8e37/website/source/docs/concepts/ha.html.markdown)
[Another](https://github.com/hashicorp/vault/blob/0ede02a08c3b1a616b302384a4a34b6dca79ecc4/website/source/docs/commands/help.html.md)

[And one more](https://github.com/hashicorp/vault/blob/4ea6acffecdd1de45ed42159c83c27745d727d0d/website/source/docs/config/index.html.md)

I can do a pull request for these later if you'd like. 
NOTE: I skipped phrases that said "physical storage" since that makes perfect sense.

**Comment by armon** [comment]
@certifiedloud Could you please create a PR? Thanks!

**Comment by armon** [comment]
Fixed by #265

**Comment by gautamk** [comment]
Thanks, 
That was fast :+1:
