### ISSUE TITLE
Vault will skip root CA check when -ca-cert is intermediate CA

### ISSUE THREAD

**Issue by lcgkm** [hashicorp/vault#2634]
```
% vault version
Vault v0.6.4 ('f4adc7fa960ed8e828f94bc6785bcdbae8d1b263')
```
When -ca-cert is intermediate CA
Vault CLI is OK.  
```
$ vault auth -method=cert \
    -ca-cert=ca.pem -client-cert=cert.pem -client-key=key.pem
```
Curl will return error. **SSL certificate problem: unable to get issuer certificate**
```
$ curl --cacert ca.pem --cert cert.pem --key key.pem \
    $VAULT_ADDR/v1/auth/cert/login -XPOST
* SSL certificate problem: unable to get issuer certificate

  0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0
* Closing connection 0
curl: (60) SSL certificate problem: unable to get issuer certificate
```

**Comment by jefferai** [comment]
There's not enough context here to fully understand what is happening, however, the error message you are seeing from `curl` is from `curl`, not Vault. If you've put the appropriate root CA into Vault's cert auth backend and you are using the intermediate to auth *and* you have the intermediate's key, which you do, Vault will grant login because the root issued the intermediate.

What's likely happening is that curl is trying to look up the root CA on the system and unable to do so, but since Vault has the root submitted directly to it it can correctly validate the check.

**Comment by lcgkm** [comment]
We try to enable the Vault Server TLS support.
The Vault Server TLS certificate like this:
TLS Root CA -> TLS Intermediate CA -> Vault Server TLS Certificate
And we use  -ca-cert to indicate the TLS intermediate CA only, not (Root CA + Intermediate CA):
```
-ca-cert=path           Path to a PEM encoded CA cert file to use to
                          verify the Vault server SSL certificate.
                          Overrides the VAULT_CACERT environment variable if set.
```

We found that we can access our vault server via CLI:
```
$ vault auth -method=cert \
    -ca-cert=ca.pem -client-cert=cert.pem -client-key=key.pem
```
Note: The client certificate issued by another Client Root CA, not TLS Root CA.

>What's likely happening is that curl is trying to look up the root CA on the system and unable to do so, but since Vault has the root submitted directly to it it can correctly validate the check.

In our case, the root certificate has not submitted to Vault. So we guess the vault client (CLI) will not check the whole certificate chain.

**Comment by jefferai** [comment]
It's still not clear to me what you think the issue is. Is it that authentication succeeds and you get a client token...in which case what CAs/certs are you putting into the cert auth backend? Or is it that the CLI command succeeds even though the given CA cert only contains the intermediate, which isn't a problem if the Vault server is providing a root that is trusted on your system?

**Comment by lcgkm** [comment]
Just forget auth backend...
Please compare following commands:
```
$vault read -ca-cert=ca.pem pki/cert/ca
```
```
$curl --cacert ca.pem $VAULT_ADDR/v1/pki/cert/ca
```
And please make sure:
* -ca-cert/--cacert indicate the TLS intermediate CA only, not "bundle" CAs (Root CA + Intermediate CA)
*  System don't contain the Root CA

**Comment by jefferai** [comment]
If you give Vault's CLI a specific CA cert and tell it to use that for validation, if the server has a cert issued by that CA it matches. Vault looks at system certificates by default, but you're overriding this behavior. It appears that curl (or really, some library it uses) is enforcing that the CA cert be self-signed, but Go's libraries don't work like that (and personally I don't think they should).

Generally the behavior is to provide the client with root CAs and let the other side present a leaf cert and potentially intermediates, which are then checked against the root CAs the client is configured to use. But there's really no reason not to match against any valid CA cert that you are explicitly telling it to validate against.

**Comment by lcgkm** [comment]
>Generally the behavior is to provide the client with root CAs and let the other side present a leaf cert and potentially intermediates, which are then checked against the root CAs the client is configured to use. 

Got it. Thanks!

**Comment by benbendemo** [comment]
Could you please tell me which value should I assign to `VAULT_CACERT`, `VAULT_CLIENT_CERT`, `VAULT_CLIENT_KEY` on my macOS? I have Vault macOS version installed, can't found out how to setup these parameters.
