### ISSUE TITLE
Ability to see resources list that use policy

### ISSUE THREAD

**Issue by StyleT** [hashicorp/vault#2642]
It would be useful to see all resources that use policy to prevent accidental deletion. For example in AWS if you want to delete any resource that has dependents you will be warned about this & provided with the list of these deps.

Currently I can delete policy thinking that it's not in use anymore & break some application.

**Comment by vishalnayak** [comment]
Issues that are not reproducible and/or not had any interaction for a long time are stale issues. Sometimes even the valid issues remain stale lacking traction either by the maintainers or the community. In order to provide faster responses and better engagement with the community, we strive to keep the issue tracker clean and the issue count low. In this regard, our current policy is to close stale issues after 30 days. Closed issues will still be indexed and available for future viewers. If users feel that the issue is still relevant but is wrongly closed, we encourage reopening them.
   
Please refer to our [contributing guidelines](https://github.com/hashicorp/vault/blob/main/CONTRIBUTING.md) for details on issue lifecycle.
