### ISSUE TITLE
Rekey fails with openpgp error

### ISSUE THREAD

**Issue by horsehay** [hashicorp/vault#2651]
After upgrading (now on 0.7.0) I can't get rekey to work:

```{"errors":["Error setting up encryption for PGP message: openpgp: invalid argument: cannot encrypt a message to key id 24db4cc9a3b88931 because it has no encryption keys"]}```

Checked other issues, and I know there have been some changes here, but this method worked prior to the upgrade. I'm not even sure where it's getting that key id because pgp key ids are 8 digits and that doesn't match any of the ones I'm using.

Here's the command I'm using to start the rekey (public keys are stored in a directory on the server):
`vault rekey -init -key-shares=$(ls | wc -l) -key-threshold=3 -backup=true -pgp-keys="$(ls | tr [:space:] ',' | sed 's/,$//')"`

**Comment by horsehay** [comment]
I just tested this in an environment running 0.6.2 and had the same issue.

**Comment by callafeucht** [comment]
We are experiencing this same issue on v0.6.4.

**Comment by jefferai** [comment]
What is the key ID you are using? Is it 24db4cc9 or a3b88931?

**Comment by bgupta** [comment]
@jefferai I made this comment on another ticket, but I'm fairly certain, it's the same issue. 

After digging in I think this is the cause and resolution. https://github.com/keybase/go-crypto/pull/50

Looks like you pulled in the new fixed dependency on Mar 30: https://github.com/hashicorp/vault/commit/790261277397502e1565cac64abaea3ab6cbec0a#diff-851cdaf90f5ed1eb0c57d1e2fa2ac379

Guessing this will be resolved when you cut v0.7.1. I'd be willing to test and see if it resolves my issue, if you can point me to a nightly build.

**Comment by jefferai** [comment]
0.7.1 will be out very soon and there won't be any traction on this if the upgraded libraries *don't* work, so rather than build a nightly I'll defer to 0.7.1 :-)

**Comment by horsehay** [comment]
@jefferai Sorry for the slow reply. The valid key id is a3b88931. I didn't recognize thet there were two smushed together there.

**Comment by horsehay** [comment]
@jefferai Just upgraded to 0.7.2 and having the same issue. 😿

**Comment by jefferai** [comment]
Probably a duplicate of #2372

**Comment by GastroGee** [comment]
Did anyone figure out a solution to this?

I am having the same problem running vault 0.6.5

A rekey operation generates exactly same error message

**Comment by horsehay** [comment]
@jefferai Still having this issue in 0.8.0 and it's becoming a problem as I need to rekey vault with new keyholders as old ones are gone. I'm not using sub-keys, and I know there were several changes made to the pgp stuffs, so I was hoping that would fix it. Is this something that is still being figured out?

**Comment by jefferai** [comment]
@horsehay It's not actively being investigated on our end.

**Comment by jefferai** [comment]
@horsehay btw I just had to run out but will provide some more color later.

**Comment by jefferai** [comment]
@horsehay OK, so here's the state of things:

* We don't really know what the problem is...we don't know what's causing it or how to repeat it.
* It isn't happening for everyone, and only started for you at some point well after the feature was implemented and I don't think it's changed much
* This suggests something about the underlying libraries, but it's not clear what has changed; we did switch to the Keybase version of the openpgp library and it seems like that solved other issues, but I don't think the timing of that matches with when you say the problem started
* OpenPGP support on Go is, generally, kind of a mess. So this may be something we're doing wrong or may not. But especially with you not using subkeys we really aren't steeped into the internals enough to have much of an idea.
* If you were willing to send us the affected public/private key pair that might help, but also may not if it's some issue deep in the weeds

OK, so that's to explain the state of things with OpenPGP. But there's another reason for the lack of traction and this has to do with something that happened internally a while back. We were thinking about the init process and how to lock down its security more, because there are actually quite a few procedural holes that can be exploited by a sysadmin if people aren't being very, very careful about every step of the init and rekey process -- this includes when using PGP keys. When we were walking through what this ideal process would be to figure out the steps for a guide, we started to realize that we could use Vault's own features (based around response wrapping) to actually provide essentially the exact same security guarantees during an ideal init/rekey workflow as PGP keys. And, one of the pros in the pros/cons analysis is that it makes better init/rekey security more accessible to all users (including those not using PGP at all) and isn't encumbered by PGP problems like what you're seeing that we don't really have good ideas about how to fix. (BTW, I say "ideal" init/rekey workflow not as something that is specific to this method; there are definitely ideal workflows when using PGP as well, and we think most aren't actually using them, and some of it would require some enhancements to Vault.)

So currently you're sort of caught between a rock and a hard place, where we don't really know what's going on with some people's keys and lack the time to really dig in, and at the same time would rather spend time we can dedicate to this working towards implementation of this new method (which is actually designed and partially implemented but needs to be finished), because we think overall it will be a much better solution for most people.

In the mean time, if the keys are working for you in some other language, you could write a script that would make the last call to rekey using the non-PGP-keyed rekey method, parse the JSON, and encrypt the key shares using your public keys and spit those out -- essentially what Vault is doing internally but in a language that's working for you. You could have multiple people watch the process to ensure that the plaintext keys are never divulged.

**Comment by horsehay** [comment]
@jefferai Thank you so much for the in depth explanation. It's very helpful to know for making a decision on how to go forward.

**Comment by horsehay** [comment]
Looks like I did have an issue with a pgp key that was causing this problem. Nothing to see here; move along.

**Comment by jefferai** [comment]
@horsehay oh boy, hah! Glad it's resolved, although our opinion around a different method going forward hasn't changed (which isn't to say we're going to rip PGP out, just that we'd generally encourage using the new method) so hopefully that will show up with 0.9 if we can fit it in.
