### ISSUE TITLE
Option to Hide Vault Version in UI for Enhanced Security

### ISSUE THREAD

**Issue by marioasabella** [hashicorp/vault#26599]
**Is your feature request related to a problem? Please describe.**

Currently, the HashiCorp Vault UI prominently displays the Vault version in the footer. While this is helpful for troubleshooting and support, it can pose a security concern in environments where exposing software versions is considered a risk. This issue requests the addition of a feature to optionally hide the Vault version number from the UI. In many security-sensitive environments, revealing software versions is discouraged as it can provide attackers with useful information for crafting targeted attacks.

**Describe the solution you'd like**
I propose adding a configuration option in the Vault server's configuration file that controls the display of the Vault version in the UI. This option could be a simple boolean flag:

```hcl
ui_hide_version = true
```

**Describe alternatives you've considered**

Using a Reverse Proxy: Setting up rewrite rules in a reverse proxy to remove the version number from the HTML. But this adds network complexity and can be error-prone.

**Additional context**

The addition of this feature would greatly benefit organizations that are bound by strict security and compliance regulations. It would allow them to use Vault without compromising on their security policies regarding information disclosure.

**Comment by divyaac** [comment]
Hello @marioasabella , thank you so much for bring this to our attention! We currently have an option called https://developer.hashicorp.com/vault/docs/configuration/listener/tcp#redact_version that should redact the version from any response. We will test this to make sure that if this toggle is set to true, the UI will also redact the version.

**Comment by noelledaley** [comment]
Hi @marioasabella, I've tested whether setting `redact_version: false` in the vault config as Divya pointed out successfully hides the version from the UI entirely and unfortunately it's not hidden. I'm investigating a potential fix -- stay tuned! Thanks again for bringing this up. 🙌

**Comment by marioasabella** [comment]
Hello @divyaac and @noelledaley, 

Thank you both for your prompt responses and for looking into this feature!

@divyaac I appreciate you pointing out the redact_version configuration option. I wasn’t aware of this setting, and it sounds like exactly what we need. 

@noelledaley thank you for testing and coming up with a [fix](https://github.com/hashicorp/vault/pull/26614) so quickly.

**Comment by noelledaley** [comment]
Hi again @marioasabella, I spoke with our product team to clarify the intention behind the `redact_version: true` configuration option and learned that it will only redact the Vault version from the API response when a user is unauthenticated. In other words, the Vault version will be hidden from the app footer in the UI when a user is not logged in, but once they're logged in they _will_ see the version. This functionality is described in a more detail in https://github.com/hashicorp/vault/pull/24262, and is available as of Vault 1.16.0.

The idea of completely removing the version from the UI was considered but ultimately decided against because of the frequency with which users use the Vault version as a reference when troubleshooting.

Given this, I'm going to close this issue. I hope using the `redact_version` setting helps your use case, and if it doesn't meet your needs feel free to add more context here. Thanks!

**Comment by marioasabella** [comment]
Hi @noelledaley,

Thank you for clarifying how the `redact_version: true` configuration works and for discussing this with the product team. I understand the reasoning behind the decision to show the version number to authenticated users, especially given its utility in troubleshooting.

The current functionality, where the version is hidden from unauthenticated users, actually aligns well with security requirements. I appreciate the team taking the time to consider the full removal of the version number from the UI and for providing a detailed explanation.

Thanks again for your support and for addressing this issue promptly.
