### ISSUE TITLE
unable to import exported transit key

### ISSUE THREAD

**Issue by stampycode** [hashicorp/vault#2667]
[Transit Read Key](https://www.vaultproject.io/api/secret/transit/index.html#read-key-1) allows Transit endpoint to output the encryption/hmac/signing key used, but there seems to be no equivalent endpoint where these keys can be imported/restored into a Vault instance.

From [Transit Docs](https://www.vaultproject.io/docs/secrets/transit/index.html):
> The primary use case for transit is to encrypt data from applications while still storing that encrypted data in some primary data store.

So if my data is transit-encrypted and stored permanently in a data store, and I lose my Vault instance, and have exported my keys using the above method, then I will have to find a third-party library to decrypt my data using the keys... ?

**Comment by jefferai** [comment]
You could actually use a library from Vault (https://github.com/hashicorp/vault/tree/master/helper/keysutil), but yes, currently there is no way to import (and in fact, it's never come up before as a request).

Part of the "contract" of `transit` is that the key is never exposed outside of Vault. We added the ability to export keys because some enterprises have key escrow requirements, but it leaves a permanent mark in the key metadata. I suppose we could at some point allow importing a key and also leave such a mark.

**Comment by stampycode** [comment]
The ability to do this also make sense if you wanted to have multiple unconnected Vaults (such as for sharing encrypted data between separate companies).
This way, keys would need to be shared between Vaults just once (probably by PKI), reducing costs for sharing data.

My particular scenario is using Vault in a dev capacity, where I want to spin up and tear down local dev instances of Vault for testing, but I need an easy way of using the same key across different instances of Vault, to save on scripting key-fetch commands and re-encrypting bunches of data between tests.

**Comment by stampycode** [comment]
for example, if my app only has permission to `transit/decrypt` data, currently I have to encrypt that data for each test-run in order to check that my decrypt process works.

**Comment by jefferai** [comment]
Adding to 0.7.4 milestone but want to be up front that this may well slip.

**Comment by jefferai** [comment]
One thing that I haven't sorted out yet is *how* this should work. Let's say that you have ciphertext from v3 of a key. If the key is imported as version 1, Vault will attempt to decrypt with the wrong key version.

I also don't think it's a good idea to allow importing on top of an existing key. Too easy to do something stupid.

What I'm thinking right now is that importing would simply add a new key version using the imported key. So if you imported to a key that didn't exist it would be version 1; otherwise if the key is at version 1 and you import a key it would become version 2. That way you can never overwrite a valid key but you can affect the ordering of versions as needed.

**Comment by zero-below** [comment]
I've just run into this as well. We were about to try switching an internal application over to the transit backend; in our case, we already have some keys that we need to use to sign some data, but were hoping to use vault to simplify the storage of these keys. Our signing algo was already supported by vault, but inability to import the existing keys in may be a blocker for us.

**Comment by jefferai** [comment]
@zero-below Feel free to suggest/comment on the UX proposed above. It's not an issue of not wanting to do it, just trying to do it right.

**Comment by zero-below** [comment]
I think it's perfect to only allow importing to an empty slot. If we wanted to replace it, we could separately delete the unwanted key as a separate action first.

Alternatively, a UX may be that the imported key will, by default, become the latest. However, a user can specify a version to use instead. If the user specifies a version, then that slot must be empty. If they want to overwrite a key, then they would need to delete it manually, first.

**Comment by jefferai** [comment]
Unfortunately that doesn't work as we don't allow gaps. You can't simply delete a key version and then import into that version.

**Comment by zero-below** [comment]
For my own purpose, especially if we are able to import, for all I care, it could require going into slot 0 of an empty transport key list. Any further import options that let me append to a list, are perfectly fine with me.

**Comment by zero-below** [comment]
My current intention for use, is to keep the keys offline in other storage, then to load them into a new vault, at setup time, with the configuration setting to make them un-exportable. We likely only have one key in the chain at a time, except perhaps for short durations where we add a second one.

**Comment by jhmartin** [comment]
The ability to import is important.  The case I'm looking at is where two vaults are using transit encryption to generate data keys. The vaults are in different AWS regions, but requests relying on these keys can arrive in either.  The data needs to be de-cryptable in both locations.

**Comment by yiwawang2017** [comment]
Transit: backup/restore #3637: Do we allow import of our own key? Similar to AWS KMS. We are currently using our own key management service, but considering switch to vault. Our encrypted data is stored in DB. It would make the transition easier if we can import our existing key so that we do not need to decrypt the data using the old key and re-encrypt it using the vault - at least allow us to phase this out.

**Comment by jefferai** [comment]
@yiwawang2017 No, the backup/restore functionality is for direct backup and restore. It won't solve your use-case, although it will solve most of the others in this thread (and some of them already have solutions anyways).
