### ISSUE TITLE
Vault returns no error information when it can't write to etcd backend.

### ISSUE THREAD

**Issue by stephanh** [hashicorp/vault#2670]
We had an issue with Vault where the certificates expired on the leader and it couldn't talk to the etcd backend.

Vault seemed to have entered a read only mode where we could still read data but not write. When trying to write data it would return an empty error response:

```
$ vault write secret/foobar test=true
Error writing data to secret/foobar: Error making API request.

URL: PUT https://vault.sop.ai.cba/v1/secret/foobar
Code: 400. Errors:

* internal error
```

However, if I do a delete operation I get a meaningful error with the actual problem:

```
$ curl  -XDELETE -H"X-Vault-Token:<token>" https://vault/v1/auth/approle/role/foo
{"errors":["1 error(s) occurred:\n\n* failed to invalidate the secrets belonging to role 'foo': client: etcd cluster is unavailable or misconfigured; error #0: net/http: TLS handshake timeout\n; error #1: remote error: tls: bad certificate\n; error #2: remote error: tls: bad certificate\n"]}
```

**Comment by jefferai** [comment]
You don't give any information about what version of Vault you're using, so it's likely that it's a version that accidentally put 400 with an internal error instead of 500. When 500s get thrown, the Vault log should have information about what the error is. We intentionally don't give 500 error information to clients in case it's something sensitive.

**Comment by stephanh** [comment]
The Vault version was `0.6.2`. 

In this case you are returning error information on a delete operation but not on the put operation. So if there is concern around sensitive information being leaked then the delete operation could be leaking info.

**Comment by jefferai** [comment]
At the storage level we don't really care if an error is shown, as values are encrypted anyways.

It looks in this case like the etcd backend in 0.6.2 doesn't throw an error when this happens. I do recommend upgrading, for many reasons (including security fixes), but also because more recent versions of Vault have an etcd backend maintained by the etcd team and has been entirely rewritten.
