### ISSUE TITLE
Redirect from sealed node in HA

### ISSUE THREAD

**Issue by oillio** [hashicorp/vault#2684]
In HA mode, are sealed vaults supposed to redirect requests if there is an active master in the cluster?

When I restart a vault node, I expected it to be able to serve requests and redirect to the active master in the cluster.  What I am seeing is the node will return an error, until it is unsealed.  At that point, it will be in standby mode and properly redirect requests.  I know a sealed node cannot become a master, but it still should be able to redirect to the master, if one exists.
Is this expected behavior?

I am using consul as the backend.

`VAULT_ADDR=http://servA:8200 vault status `
```
Sealed: false
Key Shares: 1
Key Threshold: 1
Unseal Progress: 0
Unseal Nonce: 
Version: 0.7.0
Cluster Name: vault-dev
Cluster ID: 702df08e-1cd3-0664-48df-a3fe78d11b58

High-Availability Enabled: true
	Mode: active
	Leader: http://servA:8200
```

`VAULT_ADDR=http://servB:8200 vault status `
```
Sealed: true
Key Shares: 1
Key Threshold: 1
Unseal Progress: 0
Unseal Nonce: 
Version: 0.7.0

High-Availability Enabled: true
	Mode: sealed
```

`VAULT_ADDR=http://servA:8200 vault read secret/test `
```
Key             	Value
---             	-----
refresh_interval	768h0m0s
value           	aval
```

`VAULT_ADDR=http://servB:8200 vault read secret/test `
```
Error reading secret/test: Error making API request.

URL: GET http://servB:8200/v1/secret/test
Code: 503. Errors:

* Vault is sealed
```

`VAULT_ADDR=http://servB:8200 vault unseal `

`VAULT_ADDR=http://servB:8200 vault status `
```
Sealed: false
Key Shares: 1
Key Threshold: 1
Unseal Progress: 0
Unseal Nonce: 
Version: 0.7.0
Cluster Name: vault-dev
Cluster ID: 702df08e-1cd3-0664-48df-a3fe78d11b58

High-Availability Enabled: true
	Mode: standby
	Leader: http://servA:8200
```

`VAULT_ADDR=http://10.0.61.83:8200 vault read secret/test`
```
Key             	Value
---             	-----
refresh_interval	768h0m0s
value           	aval
```

**Comment by jefferai** [comment]
No, they are not. Sealed vaults can do nothing except be unsealed. This is for security reasons; the active node advertisement is in the encrypted storage, otherwise it would be trivial to hijack Vault clients by simply overwriting this with a plaintext entry that they would blindly forward clients to.

**Comment by oillio** [comment]
Well, I would disagree that this would open up a vector for attack.  You don't need a shared secret to protect against that sort of hijacking.  We are already distributing TLS certs to the hosts...

Thanks for the quick response though.

**Comment by jefferai** [comment]
The point though is that the root of trust is protected by the split secret mechanism. Any mechanism that works around that being the root of trust is problematic.

Potentially a certificate generated by Vault and stored internally (protected by the keyring) could do the signing, so maybe in the future that would be an avenue, but it doesn't exist now.

**Comment by oillio** [comment]
This is overly pedantic, but I can't resist mentioning that you are already violating that rule.  Unless I am missing something, the private key used for TLS is not protected by the split secret root of trust.

I'd rate a compromised TLS key as at least as bad as as a hijacked redirect.
I suppose a compromised TLS key AND a hijacked redirect would be considerably worse than just one or the other though...

**Comment by jefferai** [comment]
Hi Dan,

You're totally right, but it's an exception we can't really work around, due to, for instance, being a networked service :-)

There's a key difference though -- in most cases Vault is running with networked storage. Overriding a cert on a given host is one compromise, writing a value to networked storage is another. But by writing such a value you can essentially compromise all Vault servers in this way, rather than just a single most. Also, in many cases security around that storage tends to be more lax than for TLS keys, either because the ability to lock things down is less or people aren't as careful (after all, if everything else is encrypted...).

Finally, having Vault be unavailable until unsealing does give an opportunity for unseal key holders to verify and validate the Vault node they're about to unseal. In theory this would include things like running a hash against the binary, verifying machine access since startup, and so on. Most users aren't going to be concerned enough to do this, but we know some that do. This gives another opportunity to detect this kind of malfeasance that you don't get if Vault blindly forwards based on an unencrypted value.

Hope that helps explain things!
