### ISSUE TITLE
Dealing with losing nonce upon deploy

### ISSUE THREAD

**Issue by aizotov-aspiration** [hashicorp/vault#2691]
I am setting up aws-ec2 auth, but don't quite understand how to deal with losing the nonce upon redeploy of application code.

One idea is to clear the whitelist with every deploy as part of the build step. This would require keeping a vault token that authorizes such an action somewhere outside of vault. Not ideal but certainly possible.

Another idea that comes to mind is that items in the whitelist should live for such a short time that in the instance of code deploy the whitelist entry just expires. I've tried to configure this by setting the max_lease on the auth backend to a low value
`vault mount-tune -default-lease-ttl=2m -max-lease-ttl=2m auth/aws-ec2`
but this had the undesired side-effect of disallowing my application to renew the token via `renew-self` endpoint after 2 minutes have expired, also the entry wasn't even wiped from the whitelist (presumably due to the safety_buffer of 72h)

Another option is of course to persist the nonce to the disk, but the docs seems to say that it is a bad idea.

What is the recommended solution for surviving code deploys and reboots?

**Comment by jefferai** [comment]
Code deploys is relatively easy; simply persist the nonce to ramdisk. It won't survive a reboot but will be there after the application restarts.

Reboots are harder. If you are constrained by needing to reboot instances (instead of, say, tearing down an instance and using a new one instead), you may want to look at using IAM for auth with the extra EC2 bindings, just released in 0.7.2.

**Comment by aizotov-aspiration** [comment]
Ok thank you for the suggestion!
