### ISSUE TITLE
Multi-get for secrets?

### ISSUE THREAD

**Issue by nbrownus** [hashicorp/vault#272]
I do not see a way to `GET` multiple secrets with a single http request. It would be a nice performance improvement to have, certainly if someone has to fetch 10s or 100s of secrets at a given time.

**Comment by skyzyx** [comment]
:+1:

**Comment by jefferai** [comment]
Just to chime in here,  while I think this is an interesting enhancement idea, I do think we also need to ensure we can implement this in a way that prevents someone causing horrendous performance problems due to requesting 10k secrets at once. Maybe an arbitrary (or operator-tunable) hard limit would suffice.

**Comment by mp911de** [comment]
This would be useful for applications that request multiple secret details. In general, I see two patterns when using the `generic` secrets:

1. Storing multiple secrets in one path
2. Storing multiple secrets using multiple paths

This is however only a scenario for `generic` and does not take other secret backends into account. 

Obtaining multiple secrets (password for MySQL, Cassandra, AWS) in one shot would help with batching and request synchronization since it's usually a difficult exercise for a client. I'm currently triggering multiple async requests and synchronize them at the end. This is especially useful when vault needs to perform work that is related to remote services. Not sure how vault handles concurrency internally but parallel requests help to reduce the total time the client has to wait for secrets.

**Comment by jefferai** [comment]
> Not sure how vault handles concurrency internally but parallel requests help to reduce the total time the client has to wait for secrets.

All requests are handled concurrently!

**Comment by jaxley** [comment]
Currently, Vault does not have any PATCH API for updating single fields when storing multiple fields at a given URI path.  A common use case is to just update a single value.  To do this, it means that every consumer of the API for updating values has to do one of several possible things that are each problematic in their own right to avoid corrupting pre-existing values:

* correctly implement logic to fetch all existing fields at the URI path; merge locally; submit back (requires 2 API calls for every update)
* Require the end-user to re-store all stored secrets at a URI path even when only needing to update a single value
* Expose all existing stored secrets to the user

Therefore, it is currently far safer to store only a single field=value pair at a given URI path and avoid this whole issue.  However, that means that without a batch/bulk API for GETs, you cannot retrieve multiple values at once anymore so read performance suffers.  HTTP/2 will eventually help with this whenever it is ubiquitous, but in the meantime, would be beneficial to have native support for batching.

**Comment by jcrowthe** [comment]
Any update on this issue?

**Comment by jefferai** [comment]
None currently.

**Comment by rkrzr** [comment]
It would indeed be useful to have this. Any bigger application will usually require a whole number of secrets to run (databases, API keys, other credentials). So I think this is a quite common use case.

Is this on the roadmap?

**Comment by jefferai** [comment]
Not at this time.

**Comment by CSharpRU** [comment]
Hi guys,

I've ended up with something that allowed to us request multiple secrets at one time, but it introduces a new custom HTTP method - MULTIPLE.

I don't think that is a good way to do it, maybe you have some ideas about that and we can implement them with community?

**Comment by CSharpRU** [comment]
@jefferai ?

**Comment by jefferai** [comment]
Yes?

**Comment by CSharpRU** [comment]
@jefferai 
> Hi guys,
>
> I've ended up with something that allowed to us request multiple secrets at one time, but it introduces a new custom HTTP method - MULTIPLE.
>
> I don't think that is a good way to do it, maybe you have some ideas about that and we can implement them with community?

**Comment by jacob-salassi** [comment]
Can you consider extending the LIST method on /v1/secret/:path to also return values? That could be further extended with a filter option in a query params?

If its unplanned for the roadmap, is it because the feature is not compelling? Should we be thinking about fetching multiple secrets in a different way? 

This is particularly painful in the jenkins integration because the LIST methods arent even exposed there, you need to now maintain a separate list, and keep it in sync with the actual committed secrets.

**Comment by jefferai** [comment]
Having LIST also return values would mean that every list command would have to then read every key it returns, which could result in huge load on the Vault server.

There are a number of reasons we haven't supported this so far, but for each get request you'd have to check the token (so that you'd decrement the use count if it's use-limited), run an ACL check, and handle that request separately. It may well be more efficient to just make multiple requests over an existing connection (e.g. using HTTP/2), especially if those requests are run in parallel; the OP's claim that it would be a performance improvement is merely a supposition and depends strongly on whether you're considering clock time or overall processing time within Vault.

**Comment by jefferai** [comment]
> so maybe an issue/pr on the plugin is a better way to go.

It does seem like that plugin has some specific challenges that might best be solved by the plugin itself.

> My bootstrapping container making 100+ http requests could be characterized as bad performance, my time to availability is now constrained by the round trip of each secret fetch.

Parallelize them! Vault deals with parallel requests very well. In addition, sending serial requests over a single HTTP connection will net you huge performance gains (10-50x improvement is totally possible vs. opening a new connection per).

**Comment by jacob-salassi** [comment]
> Parallelize them! 

Certainly, dont want to belabor the point too much just wanted to point out there are performance considerations on both sides I guess. On its face sending 1 request is better than 100, but opening 100 sockets and sending 100 requests is also not exactly a mammoth task.

**Comment by rkrzr** [comment]
> Parallelize them!

@jacob-salassi we wrote a small tool called [vaultenv](https://github.com/channable/vaultenv) which fetches secrets from Vault in parallel and puts them into the environment as environment variables.
It's a stand-alone executable without further dependencies. Perhaps it's useful to you here.

**Comment by jefferai** [comment]
> About serialization though, do you mean pipelining where I just blast out requests on a single socket without waiting on any responses between requests?

Basically you have two options. One is to use a single HTTP session but send requests serially over the same session (re-use), where you save the (significant) overhead of HTTP and TLS session establishment between them.

The other is to use HTTP/2 which allows mutliple streams to be opened within the same session, each carrying their own request. So you can parallelize natively.

@rkrzr that's cool! Feel free to send a PR to get it added to https://www.vaultproject.io/api/relatedtools.html ...you can do it right from that page via the "Edit this page" link at the bottom!

**Comment by rkrzr** [comment]
> @rkrzr that's cool! Feel free to send a PR to get it added to https://www.vaultproject.io/api/relatedtools.html 

Thanks for pointing that out! I opened a PR here: https://github.com/hashicorp/vault/pull/3945

**Comment by jacob-salassi** [comment]
@rkrzr I built the same tool in go, however getting the vault client to function inside a goroutine has proven impossible for me so far.

@jefferai did quite a bit of googling here, are there any examples anywhere for the vault go API calling Read() in a goroutine?

Even this ugly thing doesnt work when called as a goroutine, it never returns from the call to Read():

`func get_secret(key interface{}) {
        var err error
        fmt.Println(key.(string))
        token := os.Args[1]
        path := "secret/" + os.Args[2]

        cfg := api.DefaultConfig()
        cfg.Address = "https://127.0.0.1"

        client, err := api.NewClient(cfg)
        if err != nil {
                log.Fatal(err)
        }

        client.SetToken(token)
        vault := client.Logical()

        secret, err := vault.Read(path + "/" + key.(string))
        if err != nil {
                log.Fatal(err)
        }

        value := secret.Data["value"]

        fmt.Println("%s=%s", key.(string), value.(string))   
}`

This is called in a for loop:

`
...
     keys := secret.Data["keys"]
        for _, key := range keys.([]interface{}) {
                go get_secret(key)
...
`

Anyway, looking for a minimal example for how to use the vault client in goroutines to parallelize the fetching of bulk secrets.

**Comment by jacob-salassi** [comment]
Thanks, you are right. Totally my mistake :).

**Comment by jefferai** [comment]
Closing this for now as there are no plans currently to implement this, in favor of e.g. HTTP pipelining and concurrency.

**Comment by hoylemd** [comment]
Given that requesting secrets is now rate-limited, can this please be reopened?
