### ISSUE TITLE
minor: sending non-javascript-object in request body causes Go error

### ISSUE THREAD

**Issue by stampycode** [hashicorp/vault#2730]
Specifying non-object body content in the POST data to any non-GET endpoint:
```
POST /secret/foo
```

Such as these values:
```
[], "", 123, 0, false
```

Causes:
```
400: {"errors":["failed to parse JSON input: json: cannot unmarshal array into Go value of type map[string]interface {}"]}
```

Think it would be better to handle this differently.

Specifying an empty object `{}` or the keyword `null` works fine when no body is expected.

I only hit this error because in PHP `json_encode([])` returns `[]` because there are no keys in the array to cause it to output an object `{}`.

_Note: The body is always parsed, regardless of whether the endpoint expects a valid request body._

**Comment by vishalnayak** [comment]
@stampycode Even though `[]`, `""`, `123`, `0`, `false` are all valid JSON inputs, as far as I can recall, Vault CLI only accepts `key`/`value` pair(s) at the top level. The `value` can be one of the inputs you mentioned. Its not straightforward to distinguish between other decoding errors vs the Go specific error message we are noticing here. So, I am not how we can (or if we should) address this.

Regarding the body always getting parsed regardless of the endpoint expecting the request body. It seems fine to me since the HTTP spec does not prohibit body to be sent along GET requests. It only specifies that the server should not consider values sent in the body during GET requests, which Vault is in full compliance with.

**Comment by stampycode** [comment]
@vishalnayak I agree with you completely - my request is only that this bug is a direct error message as reported by Go is too verbose and should instead be something such as `This endpoint only accepts a JSON-formatted object in the request body`.

Also the fact that Go is the language used by Vault is not relevant to the error itself, and should not be mentioned in the error message. Telling the user that Go raised the error can be used for app version fingerprinting, narrowing attack surfaces for exploitation, and generally feels like it's an error 
 in the Go code that Vault just wasn't able to handle.

I would strongly suggest that no Vault endpoint accepts any non-object value as input, as although that would be valid JSON, it's not in-keeping with the API JSON patterns used throughout the API.

It's only really an issue when my app accidentally submits '[]' instead of '{}' to the API endpoint, and I get back a Go error from Vault that takes a while to understand if you haven't seen it before.

**Comment by jefferai** [comment]
@stampycode The problem is that if we assume any JSON error is due to this and swallow the actual response from the decoder, if the actual issue decoding is for some totally different reason, that will get clobbered.

**Comment by jefferai** [comment]
Closing for now; if someone is interested in changing this feel free to reopen and address.
