### ISSUE TITLE
Not clear how to change the cluster name and what the repercussions would be

### ISSUE THREAD

**Issue by palmobar** [hashicorp/vault#27526]
Hi,
the cluster_name is very useful when discovering metrics/dashboards however the auto generated names don't say much. Right now it is very unclear what would happen if `cluster_name` is set in config after the cluster is already established (e.g. the name and id were auto generated). Unfortunately the description there is very terse: https://developer.hashicorp.com/vault/docs/configuration#cluster_name

From what I've found here the originally generated cluster name is stored in the physical storage: https://github.com/hashicorp/vault/blob/main/vault/cluster.go#L307
A few lines below that it seems like it is possible to clear up that name however I'm not entirely sure what exact scenario would put me in that execution path: https://github.com/hashicorp/vault/blob/main/vault/cluster.go#L317 How can we be both modified and not generated (the cluster id is persisted as well).

I found the following issues that might be somewhat related to this one:
* https://github.com/hashicorp/vault/pull/20591
* https://github.com/hashicorp/vault/issues/11988

**Comment by miagilepner** [comment]
The cluster name can be set in the config and this will override the cluster name that is set in storage: https://github.com/hashicorp/vault/blob/main/vault/cluster.go#L94. Metrics will then report the cluster name that is in the config. However, you will need to set this in the configuration of **each node** in the cluster. This is because of your correct assessment that the cluster name and cluster info in storage will not be rewritten.

**Comment by palmobar** [comment]
@miagilepner thank you for confirmation. What I'm unsure about if it's okay to just change the name of the cluster, the documentation doesn't clearly specify what it is used for and if it's allowed. Would it be possible to document it better?
