### ISSUE TITLE
Invalidate TOTP code after verification

### ISSUE THREAD

**Issue by mp911de** [hashicorp/vault#2775]
The newly introduced TOTP backend should allow TOTP code invalidation so the time-based **one-time-password** is guaranteed to be used only once. 

Invalidation should include the time-based aspect of locking out codes generated at an earlier time. If a user generates two codes and uses the later code first with a successful verification, the earlier generated code should not verify sucessfully (even if it would validate because of clock skew).

**Comment by jefferai** [comment]
My inclination here when reviewing the backend was to allow this so that if a machine was given a TOTP code to use to run multiple commands (remember Vault being machine oriented as much as human oriented) it would work. But, upon reviewing the RFC, it's actually forbidden. So I'll have a PR in a moment to fix this.

**Comment by jefferai** [comment]
@mp911de Why shouldn't you be able to use an earlier generated code if the period/skew allow it, so long as it's strictly once?

**Comment by mp911de** [comment]
If an earlier token gets divulged (MITM or similar) which is still valid, an unintended party might use the token. Given that you limit clock skew to 0 or 1, you limit that probability. Still, a user could enter a token for the first time, that gets scraped, the user receives an error (which isn't uncommon because of clock skew), the user enters another token which then passes. The MITM possesses a valid token for the next 30...60 seconds.

In that case, the second token is no longer permitted to use (according to your fix) but there is an earlier, valid token that could be used by an unintended party. By locking out earlier tokens, you eliminate the possibility of token usage and the earlier token gets worthless.

**Comment by jefferai** [comment]
If the first token is scraped but invalid because the server is too far behind, the MITM can simply keep retrying the command using the scraped token. When the server catches up, they'll be able to use that well before the next token is valid.

This seems like something that can make things not work correctly for an average user but doesn't really help protect against an attack.

**Comment by mp911de** [comment]
So let's keep it that way and I think the main issue is solved with #2908.

**Comment by jefferai** [comment]
:-D
