### ISSUE TITLE
1 error occurred: failed to store SecretID: zk: node already exists

### ISSUE THREAD

**Issue by matthewmrichter** [hashicorp/vault#2791]
I wrote a small middleware to authenticate AppRole requests for approleid and secretid against our Mesos cluster. It takes post requests at two paths, one for approleid and one for secretid.

This was working nicely against a test approle in my local dev environment, so I deleted the test approle and then rolled it up to our staging cluster. Now, it will retrieve the approle, but I am getting the below error when I request a secretid:

'1 error occurred: failed to store SecretID: zk: node already exists'

I'm guessing that when I deleted the approle, vault did not properly delete the storage backend data related to it. I poked around inside the zkCLI, but I was unable to find anything human readable in there.. 

Any way to overcome this?

**Comment by jefferai** [comment]
Are you requesting a specific secret ID, or a randomly generated one?

Also, what version of Vault?

**Comment by matthewmrichter** [comment]
Vault v0.7.0. I'm trying to generate and issue a new secretid onto an existing approle. 
Making the following request via javascript:

{
      url: process.env.VAULT_ADDR + '/v1/auth/approle/role/' + approle + '/secret-id',
      method: 'POST',
      headers: { 'X-Vault-Token': client_token }
}

**Comment by jefferai** [comment]
@michaelansel Any ideas? OP found a workaround but maybe this is something you've seen.

**Comment by matthewmrichter** [comment]
Yup - workaround was to disable/reenable the AppRole auth backend.

**Comment by michaelansel** [comment]
I recalled seeing this in the past, but not a resolution, so I dug through our logs, and it looks this still happens reasonably regularly (1-2 times per day across multiple clusters and multiple approles within each cluster). It doesn't seem to be be consistent (a retry seems to work and the distribution across all the different fields in the audit log just matches the overall request distribution), so that feels like a race condition to me.

**Comment by michaelansel** [comment]
Actually... looking at the logs, I see something interesting: I've been investigating a strange behavior in our cluster last week where it seemed to be climbing in latency and getting overall "unhappy" up until last Friday when (for some unknown reason) failover was triggered automatically (without restarting the old leader). Now, what is interesting and relevant is that the rate of "node already exists" was also climbing during that window and dropped after failover. So, my conclusion is that the rate of incidence is somehow related to the health of the Go process.

**Comment by jefferai** [comment]
That does sound suspicious. It does seem to be ZK specific though (quite possibly via the underlying library) as I've never heard of that behavior before.

**Comment by ulmwe** [comment]
If anyone is still wondering about this, it's happening when all secret_id values have been consumed or expired.  At that point the parent znodes are also removed:
[zk: localhost:2181(CONNECTED) 30] ls /vault/auth/12345678-abcd-1234-1234-abc123abc123
[role, role_id, _salt]

The next time a secret_id is generated the parent znodes will be recreated.  But if two clients are trying to create a secret_id, and depending on timing (high chance with low write performance in the ZK quorum), the two requests might result in colliding creations of the parent znode and one will fail.

So one Vault client's request results in the znode named literally "secret_id" which serves as a parent for its newly generated secret_id leaf znode (the one that starts with underscore):
[zk: localhost:2181(CONNECTED) 31] ls /vault/auth/12345678-abcd-1234-1234-abc123abc123
[accessor, secret_id, role, role_id, _salt]
[zk: localhost:2181(CONNECTED) 32] ls /vault/auth/12345678-abcd-1234-1234-abc123abc123/secret_id/176ee112a32ad12677f977ba6808b777f4406a2368e2a4a577e9eeccbac64f87
[_b065c7441bfef79b3aba91211685910138925e6e9f41faa5519d8182919ee2db]

And the other Vault client gets a 500 error due to the name collision on one of the two parent znodes:
  failed to store secret_id: zk: node already exists

My organization's Vault client side workaround is to just retry the secret_id creation.  A Vault server side fix might be to have the ZK backend retry.  I'm unsure about how much interest there is in this backend though.

**Comment by matthewmrichter** [comment]
Now that I am 3 years and several Vault and ZK clusters past when I entered this issue (lol at 'near term' tag), I would absolutely not recommend ZK as a backend. Our best results have been with DynamoDB.

**Comment by vishalnayak** [comment]
> Now that I am 3 years and several Vault and ZK clusters past when I entered this issue (lol at 'near term' tag), I would absolutely not recommend ZK as a backend for vault. (or really anything if you can avoid it) Our best results have been with DynamoDB.

👍
