### ISSUE TITLE
Is it possible to setup vault server in HA with S3 back-end? Here is my complete use-case ... I have one ELB with 2 Ec2 instance on AWS with S3 as the backend  

### ISSUE THREAD

**Issue by ankitkl** [hashicorp/vault#2800]

**Comment by ankitkl** [comment]
As we want to achieve the vault server in HA so plan to setup vault server on 2 EC2 instance and then put ELB on top of these 2 EC2 to route the traffic. S3 is my back-end server which is already in HA.

I have doubt if we create the keys on the vault then the vault servers running on the 2 EC2 instance able to read the data of each other created on S3.

**Comment by ankitkl** [comment]
@ekristen  @armon  any suggestions

**Comment by jefferai** [comment]
Hi @ankitkl ,

Can you please post questions on the mailing list (https://groups.google.com/forum/m/#!forum/vault-tool) rather than in GitHub issues? This gets a lot more eyes on any particular question or idea.

It also prevents problematic issue workflows for questions where either the issue is closed immediately but then discussion continues on a closed issue; or, the issue is not closed, discussion dies down, and the issue remains open indefinitely waiting for further potential replies.

Thanks!
