### ISSUE TITLE
[ERROR] core: failed to audit response: request_path=sys/auth error="event not processed by enough 'sink' nodes

### ISSUE THREAD

**Issue by laszloszetey** [hashicorp/vault#28136]
Hi there. This has been raised a few times and a fixes have been reported to have been released, but I have not been able to find a release (non-enterprise) since 1.14.10 that doesn't exhibit this error.

Believed to be related to this issue:
https://github.com/hashicorp/vault/issues/27692

When using vault commands:
**vault auth list
vault secrets list**

we are getting the following error:
Versions: 1.15.1 - 1.17.0
[ERROR] core: failed to audit response: request_path=sys/mounts
  error=
  | 2 errors occurred:
  | \t* event not processed by enough 'sink' nodes
  | \t* event.(SyslogSink).Process: error writing to syslog: write unixgram ->/private//var/run/syslog: write: message too long
  |
Versions: 1.17.3
[ERROR] core: failed to audit response: request_path=sys/mounts error="event not processed by enough 'sink' nodes: error writing to syslog: write unixgram ->/private//var/run/syslog: write: message too long"

**To Reproduce**
run vault in dev mode:
vault server -dev
vault login token=<root-token>

run these commands:
vault auth list
vault secrets list

**Expected behavior**
We should see a list of secret engines, or auth mounts

**Environment:**
1.15.1
1.15.2
1.15.6
1.16.3
1.17.0
1.17.3

**Additional context**
We ran 1.11.11 and had upgraded to 1.16.3 when we noticed the issue.
Testing of the different versions after that has been done using vault in dev mode.

Thanks for any assistance

**Comment by divyaac** [comment]
Hi @laszloszetey thank you for raising this issue! The issue fix was made for for 1.16.5+ on enterprise only, and 1.17+ on the community edition. Would you mind noting which type of edition you're using here for each version here?

**Comment by Krishnakanth-Kolan** [comment]
Hi @divyaac laszlo is my colleague. We tried with v1.17.3 after your suggestion and the issue is still there. We are getting the following error when we try to list the secrets:

`vault secrets list
Error listing secrets engines: Error making API request.

URL: GET https://OUR-ORG-URL:8200/v1/sys/mounts
Code: 500. Errors:

* internal error`

**Comment by Krishnakanth-Kolan** [comment]
@divyaac Here is the error log from the vault server when we try to list the secrets on v.1.17.3 Community edition:

`[ERROR] core: failed to audit response: request_path=sys/mounts error="event not processed by enough 'sink' nodes: error writing to syslog: write unixgram @->/run/systemd/journal/dev-log: write: message too long"`

**Comment by divyaac** [comment]
HI @Krishnakanth-Kolan do you have any audit log configurations + server logs + audit logs you could provide us with? 
Also, do you know how many secret engines/auth engines you have configured on the cluster?

**Comment by divyaac** [comment]
Hi all! Thank you for your responses. The likely cause of the issue is that the log item that was attempted to be written to the syslog audit device is larger than the syslog host's configured maximum socket send buffer. 

We can see that in the following error from above:
`[ERROR] core: failed to audit response: request_path=sys/mounts error="event not processed by enough 'sink' nodes: error writing to syslog: write unixgram ->/private//var/run/syslog: write: message too long"
`

This is documented here: https://developer.hashicorp.com/vault/tutorials/monitoring/blocked-audit-devices#example-log-messages, and a fix can be configured by the operator. More information on kernel tunables are here: https://man7.org/linux/man-pages/man7/socket.7.html

If this still doesn't fix your issue, feel free to open this issue!

**Comment by divyaac** [comment]
Reproduction steps:
```
vault server -dev  -dev-root-token-id=$VAULT_TOKEN -log-file=/var/tmp/$(date +%F)-vault-server-logs-dev.log
```

```
DEVICE_NAME=slogaudit ; vault audit enable syslog elide_list_responses=true                            
Success! Enabled the syslog audit device at: syslog/
```

```
➜ vault auth list        
Error listing enabled authentications: Error making API request.

URL: GET http://127.0.0.1:8200/v1/sys/auth
Code: 500. Errors:

* internal error
```

**Comment by Krishnakanth-Kolan** [comment]
@divyaac Thanks for the reply. We increased the default send buffer size and it resolved the issue. We are no longer getting the following error:

[ERROR] core: failed to audit response: request_path=sys/mounts error="event not processed by enough 'sink' nodes: error writing to syslog: write unixgram ->/private//var/run/syslog: write: message too long"
