### ISSUE TITLE
After delete the policy A, the binding of entity and policy A still exists

### ISSUE THREAD

**Issue by JumpWill** [hashicorp/vault#28252]
**Describe the bug**
I am using the sdk of Vault。
I have policy A， and create an entity with policy A.
After I delete policy A,  the binding of entity and policy A still exists.

**To Reproduce**
1. Create an policy named  A
2. set policy A for an entity named B 
3. delete policy A 
4. show the policy of entity B

**Expected behavior**

**Environment:**
version  1.15.2/1.17.5

**Comment by JumpWill** [comment]
@heatherezell   I am sorry , my description may  be not  proper .This is not SDK issue but system issue . If you reproduce above  behavior，you will find this issue.

**Comment by VioletHynes** [comment]
Hi there -- this is expected behaviour, not a bug.

This decision is made intentionally, so that policies can be deleted and remade without needing to remember and then modify all of the affected entities. It would also be confusing if doing a CRUD operation on one resource would affect another resource.
