### ISSUE TITLE
The auth/aws/config/sts endpoint doesn't validate the role to assume

### ISSUE THREAD

**Issue by joelthompson** [hashicorp/vault#2829]
Currently, the endpoint just blindly accepts any `sts_role` parameter. It should probably add the following validations:

1. The `sts_role` actually looks like an IAM Role ARN
1. The account ID embedded in the ARN matches the account ID requested.
1. Vault, using its credentials, can successfully call `sts:AssumeRole` to assume the given role

**Comment by joelthompson** [comment]
Note that #3790 might make 3 above something we shouldn't do

**Comment by vishalnayak** [comment]
Issues that are not reproducible and/or not had any interaction for a long time are stale issues. Sometimes even the valid issues remain stale lacking traction either by the maintainers or the community. In order to provide faster responses and better engagement with the community, we strive to keep the issue tracker clean and the issue count low. In this regard, our current policy is to close stale issues after 30 days. Closed issues will still be indexed and available for future viewers. If users feel that the issue is still relevant but is wrongly closed, we encourage reopening them.
   
Please refer to our [contributing guidelines](https://github.com/hashicorp/vault/blob/main/CONTRIBUTING.md) for details on issue lifecycle.
