### ISSUE TITLE
AESGCMBarrier decrypt & decryptKeyring over allocate 

### ISSUE THREAD

**Issue by JaredWilliams** [hashicorp/vault#2845]
Minor issue, but the decryption output buffer allocated in these two functions doesn't take into account the size of the tag. Allocating gcm.Overhead() more than necessary.

https://github.com/hashicorp/vault/blob/master/vault/barrier_aes_gcm.go#L800
https://github.com/hashicorp/vault/blob/master/vault/barrier_aes_gcm.go#L831

**Comment by jefferai** [comment]
So you're suggesting it should be e.g.

`out := make([]byte, 0, len(raw)-gcm.NonceSize()-len([]byte(path)))`?

**Comment by joelthompson** [comment]
I think he's suggesting it should be:

`out := make([]byte, 0, len(raw)-gcm.NonceSize()-gcm.Overhead())`

Looking closer, I think this, what you suggested, and what's in the code are all wrong. While the code doesn't take into account the size of the GCM tag, it does erroneously take into account the size of the GCM nonce, when that's already pulled out of raw (i.e., `raw := cipher[5+gcm.NonceSize():]` -- so, why are you subtracting out the nonce size from the length of a byte slice when you've already excluded the nonce from that slice?). What would be closer to right would be:

`out := make([]byte, 0, len(raw)-gcm.Overhead())`

Except that, pedantically speaking, I don't think that's 100% right either. The docs for `AEAD.Overhead()` specifies it's "the **maximum** difference between the lengths of a plaintext and its ciphertext" (emphasis added). If the difference in size between the ciphertext and plaintext is less than `AEAD.Overhead()`, then subtracting out `gcm.Overhead()` could underallocate the buffer as opposed to overallocate the buffer.

[According to NIST](https://nvlpubs.nist.gov/nistpubs/Legacy/SP/nistspecialpublication800-38d.pdf) (see section 5.2.1.2, Output Data), "The bit length of the tag, denoted t, is a security parameter, as discussed in Appendix B. In general, t may be any one of the following five values: 128, 120, 112, 104, or 96. For certain applications, t may be 64 or 32."

Of course, this is all very theoretical. In practice, it looks like golang always uses a 128-bit tag and a 96-bit nonce, and so the end result is that you end up over-allocating 4 bytes more than needed (`gcm.Overhead() - gcm.NonceSize()`), rather than the 16 (`gcm.Overhead()`) as OP suggested. And it's probably safe to just use `gcm.Overhead()` as I'd guess the chance of golang suddenly introducing a smaller tag length in a backwards-incompatible way is pretty small.

**Comment by jefferai** [comment]
@joelthompson Won't this underallocate? If Overhead is always 128 bits, and the actual nonce is 96 bits, doesn't this mean we could end up underallocating by 4 bytes?

Usually you'd use Overhead when creating an encrypt buffer, e.g. you'd size it the size of plaintext + Overhead.

TBH, given that Go is GC'd it's also not clear to me that it's even worth nickel and diming a few bytes here and there. The buffer as a whole will be allocated together and the GC will free it together. If we're unsure about the exact sizing it's likely safer to keep as-is.

**Comment by joelthompson** [comment]
Pretty certain it won't underallocate -- if it did, then I'd expect that to cause tests to fail in #4183 due to underallocation (I think the tests that did fail were unrelated to my change). I think you're mixing up the GCM nonce (length `gcm.NonceSize()`) and the GCM authentication tag (length `gcm.Overhead()`). The ciphertext (`raw` in this case) contains the encrypted plaintext and the 128-bit tag, not the encrypted plaintext and the 96-bit nonce. That's why the nonce length is irrelevant and we really want to subtract out the length of the tag.

> Usually you'd use Overhead when creating an encrypt buffer, e.g. you'd size it the size of plaintext + Overhead.

Yep. So, if `len(ciphertext)=len(plaintext)+gcm.Overhead()` then it logically follows that `len(plaintext)=len(ciphertext)-gcm.Overhead())`

> TBH, given that Go is GC'd it's also not clear to me that it's even worth nickel and diming a few bytes here and there. The buffer as a whole will be allocated together and the GC will free it together. If we're unsure about the exact sizing it's likely safer to keep as-is.

Totally agree. I just saw this and was like, "Ooh, interesting low-level crypto stuff, this looks like fun!" and couldn't help myself from jumping in :)

**Comment by jefferai** [comment]
> I think you're mixing up the GCM nonce (length gcm.NonceSize()) and the GCM authentication tag (length gcm.Overhead())

The sizes, yeah, I brainfumbled.

> Yep. So, if len(ciphertext)=len(plaintext)+gcm.Overhead() then it logically follows that len(plaintext)=len(ciphertext)-gcm.Overhead())

Except that it's not guaranteed that the GCM overhead will always be 128 bits as that's the max. If for some reason ciphertext was written with 112 bits of tag instead you'll be two bytes off. So with 100 bytes of plaintext you'd get
`len(ciphertext)=len(plaintext)+gcm.Overhead() === 114 = 100 + 14`
but allocate at  decryption time
`len(plaintext)=len(ciphertext)-gcm.Overhead()) === 100 = 114 - 16`
This also actually means that using NonceSize() is technically not correct either since for certain applications it may be 32 or 64 per the NIST specs you quoted above.

So the safest thing to do seems to be to assume that the tag is 32 bits, although keep in mind "safe" is totally relative because this isn't C; this is pre-allocating slice capacity, but the slice still grows if it's too small, it's just another allocation, and the slice size still starts at 0.

At this point I wonder if the right thing to do is to simply not even subtract anything at all, let the garbage collector do its job, and be done with it.

**Comment by joelthompson** [comment]
Right, that's what I was trying to get at.

I doubt that golang would change the tag length size in a way that a: is backwards incompatible (the decrypt needs to be binary compatible with the output of the current encrypt) and b: has less security. So it should be safe.

golang/go#19594 actually allows changing the tag size, and in that, Overhead is still the tag size. So it should be safe to just use Overhead.

But yeah, probably not worth discussing much more.

**Comment by chrishoffman** [comment]
Closing based on discussion above. Closes #4183.
