### ISSUE TITLE
Key names are in plain text in Consul backend

### ISSUE THREAD

**Issue by mrtati** [hashicorp/vault#2873]
Hi,

we started to experiment with Vault, which seems to be a great product.

However, we noticed that key names are stored in plain text in the Consul backend, which is rather disturbing.
If an attacker gains access to Consul, then he can selectively corrupt or delete secrets and thus selectively influence the applications that rely on Vault. These kind of changes might be hard to trace back to an attack on Consul compared to the scenario when the attacker blindly corrupts or deletes all entries in Consul.

Would it be possible to change the implementation of Vault to support encrypted key names?
Or is there any specific reason why the key names should be in plain text? 

Thanks!

**Comment by jefferai** [comment]
The keys are in plaintext for a variety of reasons but mostly for practicality when developing, debugging, and running Vault.

If Vault were to encrypt keys using a different key everywhere, it would be impossible for us to give support advice like "please delete `core/lock`" because the actual path to `core/lock` would be different on every system. If such a problem is preventing the user from running Vault, then there is no possibility of using Vault APIs to perform this translation.

If a user is having an issue where we need to figure out where a runaway number of leases are being generated from, if we cannot examine the path we cannot know where the leases are being generated from that are causing Vault to (for example) be very slow to start up so cannot know if simply deleting certain values are a safe way to recover.

Both of those are real scenarios that have happened multiple times, and there are many more.

Similarly, such a scenario would make developing and debugging code significantly harder because we could not examine the data store for expected keys (or the lack thereof).

Anywhere that Vault internally puts sensitive values in paths we hmac the paths to obfuscate them, but in those cases we have context by knowing the path leading up to those values.

We won't be changing this, but hopefully it's understandable why. You can of course SHA or HMAC any key names you add to Vault, and you can use Consul ACLs to control access to the underlying data.

One last note: because of using GCM mode with AES, corrupting a secret via the database will result in immediate errors, so in practice there would be no difference for an attacker deleting vs. bit swapping.

**Comment by mrtati** [comment]
Except for the `core/lock` scenario, when Vault does not start, debugging could fetch key names from Vault and not directly from Consul. Or you could make key name encryption configurable, and so for development and debugging it could be turned off.
Please consider this for implementation.

With an analogy, it is like the money vault in a bank is made from transparent material so that you can see what is inside it when you walk into the building. :smile:

**Comment by jefferai** [comment]
I don't see the issue with seeing the money in the vault. You still can't get to it.

The keys are sensitive, not secret, and encrypting them makes it impossible to support both open source and commercial customers.

We will not be changing this.
