### ISSUE TITLE
Key rotate gives false sense of security

### ISSUE THREAD

**Issue by bh9** [hashicorp/vault#2893]
The [documentation](https://www.vaultproject.io/docs/internals/rotation.html) suggests that rotate is useful in the event of a compromised key. This is true in *most* cases. Should your encryption key be compromised, then rotating it while the compromiser is still in the system would give them the new key (since they have the old encryption key so can decrypt the same way the backups would)
This is a difficult thing to solve but a good first step would be to push the encrypted key to a known list of followers rather than getting them to pull. Also, the documentation should make this issue clear so people don't see rotate as a panacea.

**Comment by jefferai** [comment]
Can you link to where you are referencing?

**Comment by jefferai** [comment]
I don't see what's wrong with it. In case of an unseal key compromise, rotating the master key is indeed a useful step to take.

**Comment by bh9** [comment]
It's not useful in the case of an *encryption key* compromise and the difference should be made clear

**Comment by bh9** [comment]
It's not useful in the case of an *encryption key* compromise and the difference should be made clear. My point is that in the event of an encryption key compromise, sending out the new encryption key encrypted with the old encryption key is going to directly result in whoever compromised the old key also having access to the new key

**Comment by bh9** [comment]
@jefferai you seem to have missed the point when you closed this, please have another look (encryption key != unseal key)

**Comment by jefferai** [comment]
I didn't miss the point, I simply disagree with your assertion, because the encryption keys are not encrypted with themselves, they are encrypted with the master key. Someone that has managed to compromise a single encryption key version in the keyring -- or even all existing key versions in the keyring -- will still be able to decrypt values within Vault encrypted with that key version(s) -- can't really help that -- but not values written with new key versions, hence rotate being a useful thing to do to start writing values with a new key. And they wouldn't be able to access the new key version without compromising the master key, and if they *did* compromise the master key, rotating the master key re-encrypts the encryption key keyring, which also then makes it inaccessible to the attacker.

**Comment by bh9** [comment]
The documentation states " If the current encryption key is N and a rotation installs N+1, Vault creates a special "upgrade" key, which provides the N+1 encryption key protected by the N key" which to me says `encryption key N+1 is shared encrypted with encryption key N` therefore giving anyone with access to encryption key N access to encryption key N+1.

**Comment by bh9** [comment]
The cluster share an encryption key and a master key. The only way to send a new encryption or master key to the standby nodes is encrypted with either the master key or encryption key or both. If I have both the current master key and the current encryption key then any combination will result in me being able to decrypt the new key.

**Comment by jefferai** [comment]
I forgot about the upgrade mechanism, although note that it is cleaned up after about a minute or so, so the key for N+1 is not lying around forever for someone that has key N to decrypt. (In the future we'd actually like to do away with that mechanism, and we're relatively close to being able to do so, but not yet.)

Regardless, in your last comment you're now increasing the scope of compromise from one type of key to both. Yes, if you have both, one combination or the other will allow decryption of the new encryption key (again, for a short period of time, and until we change the mechanism).
