### ISSUE TITLE
Display_name parameter support for SecretID

### ISSUE THREAD

**Issue by timp87** [hashicorp/vault#2897]
Please, consider _display_name_ parameter support for **SecretID**.
https://www.vaultproject.io/docs/auth/approle.html

**Comment by jefferai** [comment]
What is it you are wanting to do with it?

**Comment by timp87** [comment]
@jefferai I'd like to see this parameter among others when reading out the properties of a SecretID.
Also it would be great if SecretID display_name attached to tokens issued by this particular SecretID

**Comment by timp87** [comment]
I know there is metadata for SecretID, but display_name looks more appropriate to describe what for I create this SecretID, for example

**Comment by vishalnayak** [comment]
Issues that are not reproducible and/or not had any interaction for a long time are stale issues. Sometimes even the valid issues remain stale lacking traction either by the maintainers or the community. In order to provide faster responses and better engagement with the community, we strive to keep the issue tracker clean and the issue count low. In this regard, our current policy is to close stale issues after 30 days. Closed issues will still be indexed and available for future viewers. If users feel that the issue is still relevant but is wrongly closed, we encourage reopening them.
   
Please refer to our [contributing guidelines](https://github.com/hashicorp/vault/blob/main/CONTRIBUTING.md) for details on issue lifecycle.
