### ISSUE TITLE
VAULT login Method OIDC : default path

### ISSUE THREAD

**Issue by raydenz** [hashicorp/vault#28993]
**Is your feature request related to a problem? Please describe.**
When someone login with the method OIDC, you enter you role here:
![image](https://github.com/user-attachments/assets/bd9c8c75-8971-4a2d-bc28-e7f7d62f6051)

you have here to enter the name of the paths you want to view, which is annoying because if the policty give you access to 20 paths, how to remember it?
![image](https://github.com/user-attachments/assets/eb18a406-467a-41ca-8f8c-2a7ca986facb)

**Describe the solution you'd like**
Is it possible, based on the role to be directly in a default path or to list all paths i have access in "secrets/"
Because you have to remember the name of the path everytime you login with OIDC
![image](https://github.com/user-attachments/assets/68f461f0-60c4-44b0-8417-3b501823ec4f)

**Comment by bosouza** [comment]
Hi, the behaviour you're seeing is likely caused by missing `list` permissions for these secrets, any login method that uses the same policy would result in the same. When opening a kv-v2 mount the Vault UI will do an initial [List Secrets](https://developer.hashicorp.com/vault/api-docs/secret/kv/kv-v2#list-secrets) call and if that fails it shows the `View secret` prompt. To show the full list of secrets in the mount you can try to add this to the policy applied to the OIDC auth method:
```hcl
path "secret/metadata/*" {
  capabilities = ["list"]
}
```

**Comment by raydenz** [comment]
> Hi, the behaviour you're seeing is likely caused by missing `list` permissions for these secrets, any login method that uses the same policy would result in the same. When opening a kv-v2 mount the Vault UI will do an initial [List Secrets](https://developer.hashicorp.com/vault/api-docs/secret/kv/kv-v2#list-secrets) call and if that fails it shows the `View secret` prompt. To show the full list of secrets in the mount you can try to add this to the policy applied to the OIDC auth method:
> 
> ```hcl
> path "secret/metadata/*" {
>   capabilities = ["list"]
> }
> ```

Hello,

thank you for the response
There are 50 users and every use has a policy
if i add in their policy the capability to list the secret/metadata/* they will see all the paths

i want them to see only the paths they are authorized to see

for example i tried this but it does not work, you have to enter your path manually


```hcl
path "secrets/metadata/mypath" {
  capabilities = ["list"]
}
and 
path "secrets/metadata/mypath/*" {
  capabilities = ["list"]
}

```
regards

**Comment by bosouza** [comment]
I see, you seem to want a way of filtering the results of the list operations based on user permissions. That is not supported by the list API, as per the [docs](https://developer.hashicorp.com/vault/api-docs/secret/kv/kv-v2#list-secrets):
```
Note that no policy-based filtering is performed on keys; do not encode sensitive information in key names.
```
and
```
To list secrets for KV v2, a user must have a policy granting them the list capability on this /metadata/ path - even if all the rest of their interactions with the KV v2 are via the /data/ APIs. Access to at least list the /metadata/ path should typically also be granted.
```

The guidance here is to not include sensitive information on the keys, exactly so that such list rights can be widely granted. This filter-less list behavior seems to be consistent across all secret engine list APIs so it's not something we'd consider changing without good reason.

Something that might help you with restricting list access is to use prefixes for different levels of access then restrict list rights based on those prefixes. Users would still have to remember their prefix to see the list of certificates though.
