### ISSUE TITLE
Provide strongly-typed clients for builtin backends

### ISSUE THREAD

**Issue by bmoylan** [hashicorp/vault#2920]
Most of the backends have complex APIs, and using the generic logical interface is error prone for all but the generic secret backend. I've had to write internal libraries that wrap an `*api.Client` and provide strongly typed methods and structs for the  `aws` auth, `pki`, and `ssh` backends. Integrating with the vault backends would be much easier if there were officially supported go APIs for these that incorporated new features as they're added. 

I understand that right now the API is implicit based on the `framework` objects. Keeping these in sync is a pain (though still worth it in my opinion), so as a long-term goal auto-generated clients (and docs!) would be really cool :)

**Comment by vishalnayak** [comment]
Issues that are not reproducible and/or not had any interaction for a long time are stale issues. Sometimes even the valid issues remain stale lacking traction either by the maintainers or the community. In order to provide faster responses and better engagement with the community, we strive to keep the issue tracker clean and the issue count low. In this regard, our current policy is to close stale issues after 30 days. Closed issues will still be indexed and available for future viewers. If users feel that the issue is still relevant but is wrongly closed, we encourage reopening them.
   
Please refer to our [contributing guidelines](https://github.com/hashicorp/vault/blob/main/CONTRIBUTING.md) for details on issue lifecycle.
