### ISSUE TITLE
Thousands of entries under vaultca/sys/expire/id/auth/mount/login

### ISSUE THREAD

**Issue by mskeefe** [hashicorp/vault#2927]
We are seeing thousands of entries piling up under vaultca/sys/expire/id/auth/mount/login

We aren't entirely sure where these are coming from or what is the correct way to clean these out and/or reduce their number in the first place.  From the key, we expect this has something to do with logins into Vault.

A review of the documentation didn't turn up anything regarding the sys/expire endpoint.  At the very least, maybe the documentation could be enhanced around this implementation detail.  Either that or maybe we just need to be pointed in the right direction.  

Thanks.

**Comment by jefferai** [comment]
sys/expire isn't an endpoint, it's a path in your storage.

As your surmised, this is due to logins via whatever backend you have mounted at auth/mount/login.

The most common cause is a combination of fetching new tokens instead of reusing tokens that exist and too-long token lifetimes for your usage pattern.

**Comment by mskeefe** [comment]
Thanks @jefferai.  Does Vault periodically clean this storage area?  Given our volume we wouldn't expect to have seen quite so many entries.  We can check to make sure that there isn't something broken on our end that is causing this.  Thanks again.

**Comment by jefferai** [comment]
Those will be removed when the tokens expire. You could do a revoke-prefix if you want to remove those ahead of time.

**Comment by mskeefe** [comment]
Thanks.
