### ISSUE TITLE
Tunable Consul High Availability Lock Timeout Value

### ISSUE THREAD

**Issue by brianshumate** [hashicorp/vault#2949]
When using Vault with Consul for HA, there is a 30 second timeout that must elapse before a completely failed (i.e. system power off, SIGKILL on PID, etc.) Vault instance's lock in Consul is released. This was observed to occur with Vault 0.7.3 and Consul 0.8.4.

To reproduce the issue:

1. Spin up a Consul cluster of 3 server agents
2. Spin up 3 Consul agents in client mode which join the 3 servers
3. Spin up 3 Vault servers on the same systems as the Consul agents from step 2 and configure them to use Consul for HA and communicate to the local Consul agents
4. Initialize and unseal all Vault servers and observe that there is HA mode with a current leader
5. Monitor the output of `vault status` (e.g., `watch -n 1 vault status`) on one of the standby Vault instances
6. Power off the machine corresponding to the current **active** Vault server
7. Observe the status in step 5 and measure the time between power off in step 6 and failover to promoting one of the standby instances to active; this will typically be between 32 and 33 seconds.

It would be handy to expose the underlying timeout value as a user-tunable configuration setting to allow for less time between failing over and promotion of a standby instance to active.

**Comment by slackpad** [comment]
Consul internally doubles the TTL, which Vault isn't supplying so that defaults to 15 seconds, which explains the 30 second timeout. On top of that there's the lock delay which also defaults to 15 seconds, which is kind of a fudge factor that's imposed (see the [sessions internals guide](https://www.consul.io/docs/internals/sessions.htmlhttps://www.consul.io/docs/internals/sessions.html)).

Tuning the lock delay depends on how long you want to wait to make sure a Vault instance that has lost leadership might need to perceive that it has lost leadership and safely stop what it's doing. Tuning the TTL lower would require more Vault resources to service the timer. It seems like these could both be exposed as tuneables for folks who want a faster failover, or we could let folks tune the TTL and maybe lower the lock delay?
