### ISSUE TITLE
AWS IAM issued token fails to renew with "unable to fetch client for account ID"

### ISSUE THREAD

**Issue by shayangz** [hashicorp/vault#2990]
When using vault 0.7.3 to issue AWS IAM tokens, we are getting the follow error on token renewals (using `auth/token/lookup-self` endpoint):

```
{
  "errors": [
    "1 error occurred:\n\n* failed to renew entry: failed to verify instance ID \"<instance-id>\": unable to fetch client for account ID  -- default client is for account <aws-account-id>"
  ]
}
```

We are able to do a self-lookup on the token fine

```
{
  "request_id": "327e1f5e-96e4-3c09-31d0-4d3c36b14a85",
  "lease_id": "",
  "renewable": false,
  "lease_duration": 0,
  "data": {
    "accessor": "d176a585-96a8-fed4-26f7-54039d46ab66",
    "creation_time": 1499670281,
    "creation_ttl": 21600,
    "display_name": "aws-<name>",
    "expire_time": "2017-07-11T07:04:41.922043061Z",
    "explicit_max_ttl": 0,
    "id": "<token>",
    "issue_time": "2017-07-10T07:04:41.922034023Z",
    "last_renewal": "2017-07-10T07:06:28.491560584Z",
    "last_renewal_time": 1499670388,
    "meta": {
      "account_id": "<aws-account-id>",
      "auth_type": "iam",
      "canonical_arn": "arn:aws:iam::<aws-account-id>:role/<role-name>",
      "client_arn": "arn:aws:sts::<aws-account-id>:assumed-role/<role-name>/<instance-id>",
      "client_user_id": "XXX",
      "inferred_aws_region": "us-west-2",
      "inferred_entity_id": "<instance-id>",
      "inferred_entity_type": "ec2_instance"
    },
    "num_uses": 0,
    "orphan": true,
    "path": "auth/aws/login",
    "policies": [
      "default"
    ],
    "renewable": true,
    "ttl": 44115
  },
  "wrap_info": null,
  "warnings": null,
  "auth": null
}
```

The first renewal attempt works fine but subsequent ones fail.

Here is the role used to create the token:

```
vault write auth/aws/role/<role-name> auth_type=iam inferred_entity_type=ec2_instance inferred_aws_region=us-west-2 bound_iam_instance_profile_arn=arn:aws:iam::<aws-account-id>:instance-profile/<instance-profile-name> bound_vpc_id=<vpc-id> period=6h
```

any pointers on how to work around this issue would be much appreciated.

**Comment by joelthompson** [comment]
Taking a quick look at this, I think it's a typo [here](https://github.com/hashicorp/vault/blob/48ab9c54f009fd1d9ceed0766c7d9eb320e929bc/builtin/credential/aws/path_login.go#L921) -- it should be `req.Auth.Metadata["account_id"]` instead of `req.Auth.Metadata["accountID"]`. I'll run some tests to confirm in a bit.

In the mean time, turning off inferencing is probably the only way to go for the renewals.

**Comment by joelthompson** [comment]
Hi @shayangz -- I've tracked it down, and it's definitely because I made that typo :man_facepalming: 

The reason it was only occurred on the second time is because Vault was caching the result of a lookup and so that bug didn't really matter. You must have done something that cleared Vault's cache between the renew attempts -- either a failover/restart of a vault server or writing to/deleting the `auth/aws/config/client` path. (There's also an `Invalidate` method on the struct that would clear the cache, but a quick grep through the code doesn't tell me what might call that; @jefferai / @vishalnayak -- can you shed light on what events might call `framework.Backend.Invalidate`?).

As a work around until we fix this bug, if you do run into this situation, I think any vault authentication using either the ec2 auth method or the iam auth method with the `inferred_entity_type=ec2_instance` and having the machine in the same account should restore the cache. For example, on the same machine, you could do something like:

```bash
# backup the old token
$ mv ~/.vault-token ~/.vault-token-2
# Generate a new token to populate the cache
$ vault auth -method=aws -role=<role-name>
# Revoke the new token so it doesn't pollute the storage backend
$ vault token-revoke -self
# Restore the backed up token
$ mv ~/.vault-token-2 
# And now you can renew
$ vault token-renew
```

Separately, while testing, I discovered that #2729 isn't fully fixed either -- those tokens cannot be renewed.

I'll try to get a PR for both of these fixes in the next couple days.

**Comment by jefferai** [comment]
@joelthompson The invalidate method is used during replication. Generally speaking you won't need to deal with it, the Vault team will keep it maintained. Basically, it allows the underlying replication system to tell a backend that a storage path has changed, and allow the backend to the do the right thing. In this case, if the underlying path is the client configuration, invalidation will cause the secondaries to then create new clients with the new configuration.

**Comment by shayangz** [comment]
Thanks for the quick turnaround, @joelthompson. Looking forward to the `0.7.4` drop.

**Comment by joelthompson** [comment]
Thank you @shayangz for the quality bug report :)
