### ISSUE TITLE
Vault -> Vault backend

### ISSUE THREAD

**Issue by freman** [hashicorp/vault#3003]
Hi.

I'd be super interested in getting a vault to vault upstream backend

The concept would be something along the lines of a dev users localhost vault would be able to execute commands on the production vault with production policies in place.

The reasoning behind it is we have (for the moment) super open dev vaults that aren't sealed and rebuilt as needed with all their credentials exposed for fun and games in an effort to get early adoption going, but we're finally hooking up aws and would like to generate aws credentials without putting root credentials in the dev vault.

**Comment by jefferai** [comment]
Hi @freman ,

To be honest this makes me pretty nervous as an idea, but more importantly I don't think it actually solves your problem. If a developer received a token for your real Vault, they would need to make calls outside their localhost environment to make use of it. In the case that this token lives inside their localhost Vault, their localhost Vault still has to make calls outside the localhost environment, and if they have full admin access to their localhost Vault they can pretty easily extract the token if they like. So it ends up seeming like the exact same scenario either way.

I'd suggest simply giving your developers tokens for your real server limited to generating AWS users, and/or allowing them to log in and get tokens with those policies. In addition you may want to think about AWS consolidated billing and simply setting up a test account to limit any damage caused by developers run amok. :-D

**Comment by freman** [comment]
I could easily resolve my issue by writing code to just call the two vaults, but that becomes a pita managing leases in two vaults.
