### ISSUE TITLE
allowed_users in ssh CA role not behaving as expected

### ISSUE THREAD

**Issue by NickGBT** [hashicorp/vault#3019]
the allowed users parameter for the ssh-client-signer/roles/${rolename} policies does not add a list of allowed users to the ssh cert principals when a comma delimited list is supplied, it instead seems to use the default_user parameter to do this.

vault version: Vault v0.7.3 ('0b20ae0b9b7a748d607082b1add3663a28e31b68')

Example policy document:

`{
  "allow_user_certificates": true,
  "allowed_users": "user1,user2,user3",
  "default_extensions": [
    {
      "permit-pty": ""
    }
  ],
  "key_type": "ca",
  "default_user": "user1",
  "ttl": "20m0s"
}`

expected outcome: user1,user2 and user3 are listed in the cert principals and can ssh in to the instance

actual outcome: only user1 is listed in the cert principal, user2 & user3 cannot use the cert to ssh in to the instance.

**Comment by jefferai** [comment]
`allowed_users` is a whitelist but each certificate only encodes a single user, specified at generation time (https://www.vaultproject.io/api/secret/ssh/index.html#generate-ssh-credentials) via the `username` value.

If you don't specify that username it will use the configured default user, otherwise you can specify any of those three.

**Comment by NickGBT** [comment]
So is the expected behaviour that specifying allowed_users by itself & not specifying default_user that the whitelist works? or can multiple users not be specified outright?

**Comment by jefferai** [comment]
Specifying users in a role is specifying the list of users that certificates can be generated for. Specifying the default user is specifying the user that will be used if the client does not select one explicitly. At credential generation time, the client can only get a certificate with a single name -- one of the whitelisted users in `allowed_users` by explicitly choosing it via the `username` parameter, or the `default_user` value otherwise.

**Comment by NickGBT** [comment]
Ah, I think I understand now, so when the cert is generated via vault write ssh-client-signer/sign/clientrole you can pass a username in at that stage that's specified in the allowed_users whitelist?

**Comment by jefferai** [comment]
Sorry, I was looking at the wrong endpoint. https://www.vaultproject.io/api/secret/ssh/index.html#sign-ssh-key is the correct one.

**Comment by moolshankar** [comment]
@jefferai 
Hi Jeff,
Hope you are doing good,

Well my issue has nothing to do with this bug but I am stuck and need your help.
Actually I am trying to implement ssh using CA Key Type but stuck at one step.

https://www.vaultproject.io/docs/secrets/ssh/index.html
Sign the client key 

(I am bit confused here actually, where it has to be done on client machine or on host), I tried doing it on client machine and doing ssh as explained but getting error " Permission denied (publickey) ".
I don't know what I am doing wrong. IF you can simply the below part for me it would be so nice of you.

"
Save the signed key in a file (make sure you set the permissions to only be writeable by the owner); if you're saving it along with your public/private key (e.g. ~/.ssh/id_rsa(.pub)), saving it with -cert.pub (e.g. ~/.ssh/id_rsa-cert.pub) allows SSH to automatically discover it. Otherwise, you can tell the SSH client where to find it (and the associated private key) by using -i such as ssh -i ~/.ssh/id_rsa -i my-signed-cert.pub localhost.

If you want to see the configured extensions, principals, etc., you can use the -L flag to ssh-keygen, e.g. ssh-keygen -Lf ~/.ssh/id_rsa-cert.pub.
" 
Thanks a lot in advance :)

**Comment by NickGBT** [comment]
@moolshankar It'd probably help if you told us what steps you have done, this is rather vague.

Have you followed the earlier instructions on the page up to that point? 

It should be as simple as running the command here on the client machine, provided you followed the earlier steps: 

`cat id_rsa.pub | vault write ssh-client-signer/sign/clientrole public_key=-`

replacing id_rsa.pub with the path to your public key, and pasting the value of the signed_key part of the response from vault into id_rsa-cert.pub in the same directory that your private key resides in.

**Comment by moolshankar** [comment]
@NickGBT , Hey Thanks Nick for your response.

Okay let me tell you what exactly I have done. I have three machines on my network

vault-machine : I have installed vault on this machine.
host-machine : Which our application is deployed and I want to connect using ssh.
client-machine: Now this is my machine, from where I'd do ssh to different hosts.
(Please let me know if I am confusing in Client and Host)

I have followed all the steps exactly as mention on the page
https://www.vaultproject.io/docs/secrets/ssh/index.html

But stuck at "Sign the client key".

Now as you said 
"_It should be as simple as running the command here on the client machine, provided you followed the earlier steps:

cat id_rsa.pub | vault write ssh-client-signer/sign/clientrole public_key=-_"

command can't be run on client machine as vault is installed on different not on client.

"_replacing id_rsa.pub with the path to your public key, and pasting the value of the signed_key part of the response from vault into id_rsa-cert.pub in the same directory that your private key resides in._"

I did that in client machine /.ssh directory.

Please let me know what you suspect I am doing wrong.

Thanks Again

**Comment by NickGBT** [comment]
@moolshankar the vault binary will need to be available on the client machine to do that, you'll need to be authenticated as well by running vault auth and authenticating with credentials that have the permission to sign the client key.

If you don't want to use the binary, you can make a http request to vault and do it that way, which is better from an automation standpoint. Though you'll still need to authenticate and get a token beforehand. The docs for the ssh secret backend api are here: https://www.vaultproject.io/api/secret/ssh/index.html and you'll probably want to look at the auth backends as well: https://www.vaultproject.io/docs/auth/index.html
