### ISSUE TITLE
Unsealing the vault at boot time?

### ISSUE THREAD

**Issue by dswhite42** [hashicorp/vault#3038]
We have a small team using our Vault instance, which is stored on a server that only a couple of us have access to + IT sysadmins.  (everyone else on the team accesses Vault via the API or with Goldfish).  Everyone logs into Vault via LDAP, and access is controlled via LDAP group lookups.

I had thought I could make Vault startup easy while maintaining security by generating just one unseal key:

    vault init -key-shares=1 -key-threshold=1 

which I did not think I had to protect.  I could then write a simple startup script to unseal the vault using that key at boot time (the machine may be booted unexpectedly by sysadmins), and the secrets would still be protected, accessible only by users when they login via LDAP.

I'm now realizing my mistake, in that anyone who has the single unseal key can generate a new root token, and then get full access to Vault.  So, that's no good.

But what's the alternative?  I want my team to be able to access Vault without worrying about the unsealing process, so that's why I thought a single key and a startup script to unseal vault would make life easy for them.  But if that's not safe, the only alternatives I can think of are:

- for me to always do the unsealing after a reboot (**but** what if I'm not available?)

- to give everyone the unseal key so any of them can unseal the vault manually when the server reboots (**but** then everyone would have full root access to the vault)

- for me to use the traditional method of making several shared keys with a threshold minimum and distributing them among the team (**but** what if a single member of the team needs to work on a weekend when there is no one else to provide the minimum unseal key threshold?)

Are these the only options?  Is there a way to accomplish easy unsealing while still protecting the secrets and not granting everyone full root access to the vault?

**Comment by joelthompson** [comment]
Hi @dswhite42,

In general, the Vault team likes to keep the GitHub issue tracker for feature requests and bug reports, and to have general discussions on the Vault mailing list: https://groups.google.com/forum/#!forum/vault-tool

But the simplest solution is probably to run Vault in an HA mode with some sort of load balancer and/or service discovery in front of the Vault servers, so that if one server gets rebooted, another one will take over and there's less urgency to needing to unseal the server.

If you have other questions, you should take this to the mailing list as you'll get more community involvement that way.
