### ISSUE TITLE
Comparison to CyberArk?

### ISSUE THREAD

**Issue by klauern** [hashicorp/vault#3045]
Our corporate network is using CyberArk for user logins.  I think this tool is very similar to Vault, but I don't know what about it would make it easier or better or different.

I looked at your Comparisons tool and didn't see anything mentioning CyberArk/Conjur https://www.vaultproject.io/intro/vs/index.html

CyberArk: https://www.cyberark.com/

**Comment by jefferai** [comment]
Hi @klauern ,

CyberArk has all of its documentation behind a customer-only login, which makes it hard to do any meaningful direct comparison since we cannot accurately assess its capabilities, security, or anything else. In contrast, all of our documentation, including for our Enterprise version, is out in the open. That in itself is likely an instructive bit of information, right?  :-D
