### ISSUE TITLE
Detect an HTTP request when TLS enabled and provide a better error message

### ISSUE THREAD

**Issue by armon** [hashicorp/vault#309]
Currently if the client connects expecting HTTP when the server is used HTTPS (TLS enabled) they get a horrible error message, usually from OpenSSL. We should instead automatically downgrade to HTTP and return an error message that is more informative.

**Comment by eliasgrander** [comment]
Token credentials and the rest of secrets must be kept confidential in transit and storage, and only shared among the Vault server and the client to whom the token is issued. These secrets must only be transmitted using TLS with server authentication as defined by RFC 2818 because Vault does not provide any methods for the protected resource to ensure that an token presented to Vault by a given client was issued to that client by the Vault server.

That's why if the downgrade to HTTP is done, a malicious client could do a mitm attack, impersonate another client and obtain access to protected resource. So, I think Vault should not instead automatically downgrade to HTTP ever, so this issue should not be a bug.

**Comment by jefferai** [comment]
@eliasgrander The idea wasn't to satisfy the request by downgrading, but rather to handle it as an HTTP connection so that we could return "sorry, Vault requires a TLS connection, please check your address" or so instead of simply seeing "tls handshake failed". Regardless, I'm going to close this for now as it's not likely something we'll get to soon and may have decent technical hurdles.
