### ISSUE TITLE
/sys/auth/:path endpoint requires reading the parent endpoint for read operations

### ISSUE THREAD

**Issue by CVTJNII** [hashicorp/vault#3148]
Please create a read operation for /sys/auth/:path.  Currently to read the settings of an auth backend a library must read /sys/auth and select the :path/ key in the returned hash.  Implementing a data model where all CRUD operations are on the same path will make client implementations more consistent and easier to maintain.

**Comment by vishalnayak** [comment]
Issues that are not reproducible and/or not had any interaction for a long time are stale issues. Sometimes even the valid issues remain stale lacking traction either by the maintainers or the community. In order to provide faster responses and better engagement with the community, we strive to keep the issue tracker clean and the issue count low. In this regard, our current policy is to close stale issues after 30 days. Closed issues will still be indexed and available for future viewers. If users feel that the issue is still relevant but is wrongly closed, we encourage reopening them.
   
Please refer to our [contributing guidelines](https://github.com/hashicorp/vault/blob/main/CONTRIBUTING.md) for details on issue lifecycle.
