### ISSUE TITLE
Please implement update operation for /sys/audit/:path

### ISSUE THREAD

**Issue by CVTJNII** [hashicorp/vault#3151]
Please create a update operation for /sys/audit/:path. Currently to update the settings of an audit backend a library must delete and recreate the backend. Implementing an update method on the same path will allow client libraries which implement the CRUD model against different backends to be consistent between the different backends. Thanks.

**Comment by jefferai** [comment]
We don't currently have plans to allow changing audit parameters on the fly. This is for several reasons but mostly because it's not user facing and incorrect parameters can wedge Vault, including for the response for this command. It's much safer to set up a second audit backend with new parameters and then remove the original once it's verified the new one is working.
