### ISSUE TITLE
Consul HTTPS backend

### ISSUE THREAD

**Issue by kolis** [hashicorp/vault#321]
I'm trying to use vault together with an https-only consul backend, eg
```
backend "consul" {
  address = "https://my.consul.server:8500"
  ...
}
```
this does not work however, because vault assumes plain http

```
2015/06/05 09:29:01 [ERR] core: failed to read seal configuration: Get http://https://my.consul.server:8500/v1/kv/vault/core/seal-config: dial tcp: too many colons in address https://my.consul.server:8500
```

is it not a good idea to use https for communication between vault and consul?

**Comment by bscott** [comment]
@kolis I believe it's erroring out due to the https:// protocol being there, but yes it does seem to be assuming http connections instead of allowing the option for https.

Vault is using the Consul API package and using the default api.Client config which assumes HTTP, setting a ENV variable seems to set the HTTPS mode.

https://github.com/hashicorp/consul/blob/master/api/api.go#L121

Simple solution would be to update Vault's consul backend package to pass in a custom Config struct that allowed you to set the scheme string.

https://github.com/hashicorp/consul/blob/master/api/api.go#L96

I'll see if I can get a PR created, unless I'm missing something and the feature is already implemented :)

**Comment by jszwedko** [comment]
You should specify the `Scheme` field in the Vault configuration, see https://vaultproject.io/docs/config/index.html#scheme

**Comment by armon** [comment]
Closing this, as specifying `scheme` is the way to do this.
