### ISSUE TITLE
A mounted non-existing plugin cannot be unmounted

### ISSUE THREAD

**Issue by kirilmonzo** [hashicorp/vault#3266]
**Environment:**
* Operating System/Architecture:
Ubuntu 14.04 - `Linux host 3.13.0-74-generic #118-Ubuntu SMP Thu Dec 17 22:52:10 UTC 2015 x86_64 x86_64 x86_64 GNU/Linux`

* Vault Version:  Vault v0.8.1 ('d54258253906596d22975a2174189913d1610cb9+CHANGES')

**Vault Config File:**
```
backend "cassandra" {
  hosts = "cassandra-ZZZ"
  protocol_version = 3
  connection_timeout = 600
}

ha_storage "etcd" {
  address = "http://XXX:2379"
  ha_enabled = 1
  etcd_api = "v3"
  redirect_addr = "http://YYY:8200"
}

listener "tcp" {
  address     = "0.0.0.0:8200"
  tls_disable = 1
}

plugin_directory = "/opt/vault/plugins"
```

**Startup Log Output:**
```
==> Vault server configuration:

              HA Storage: etcd
                     Cgo: disabled
         Cluster Address: https://vault-cluster:8201
              Listener 1: tcp (addr: "0.0.0.0:8200", cluster address: "0.0.0.0:8201", tls: "disabled")
               Log Level: info
                   Mlock: supported: true, enabled: true
        Redirect Address: http://vault-host:8200
                 Storage: cassandra
                 Version: Vault v0.8.1
             Version Sha: d54258253906596d22975a2174189913d1610cb9+CHANGES
```

**Expected Behavior:**
It should not be possible to mount plugins that are not present in the plugin catalog.

**Actual Behavior:**
`mount` returned successful result when mounting the non existing plugin and it is impossible to unmount afterwards.

**Steps to Reproduce:**
Attempt to mount a plugin, which does not exist in the plugin catalog.

Command output:
```
# vault mount -path=plugin-1 -plugin-name=notexistingplugin  plugin
Successfully mounted plugin 'notexistingplugin' at 'plugin-1'!
# vault unmount plugin-1
Unmount error: Error making API request.

URL: DELETE http://127.0.0.1:8200/v1/sys/mounts/plugin-1
Code: 400. Errors:

* no plugin found with name: notexistingplugin
# vault mounts
Path            Type       Accessor            Plugin                           Default TTL  Max TTL  Force No Cache  Replication Behavior  Description
...
plugin-1/       plugin     plugin_c941fc4e     notexistingplugin                system       system   false           replicated
```

Logs:
```
[INFO ] core: successful mount: path=plugin-1/ type=plugin
[TRACE] rollback: attempting rollback: path=plugin-1/
[ERROR] rollback: error rolling back: path=plugin-1/ error=no plugin found with name: notexistingplugin
[TRACE] rollback: attempting rollback: path=plugin-1/
[ERROR] rollback: error rolling back: path=plugin-1/ error=no plugin found with name: notexistingplugin
[ERROR] sys: unmount failed: path=plugin-1/ error=no plugin found with name: notexistingplugin
[TRACE] rollback: attempting rollback: path=plugin-1/
[ERROR] rollback: error rolling back: path=plugin-1/ error=no plugin found with name: notexistingplugin
```

**Comment by calvn** [comment]
I cannot seem to reproduce. Can you build from a clean branch?

**Comment by jefferai** [comment]
I literally was doing the same thing as @calvn at the same time and also cannot reproduce :-)

I note that the output above has CHANGES in addition to the git SHA. Are you sure your changes didn't cause the problem?

@calvn: It would be good to ensure that if a plugin is mounted that *does* exist, but is then removed from the plugin catalog, that:

* It doesn't keep Vault from starting up (because if it does you can't re-add the plugin)
* It can be unmounted successfully

Maybe those two things are already happening (the first probably will due to lazy loading?)

**Comment by calvn** [comment]
> It doesn't keep Vault from starting up (because if it does you can't re-add the plugin)

There is an error in this case, which prevents vault from starting up. If we write to the catalog, mount, remove from the catalog, seal, and then try to unseal, we would get an error in this case and stop the unseal process.

```
...
2017/08/31 10:40:39.495746 [INFO ] core: vault is unsealed
2017/08/31 10:40:39.495793 [INFO ] core: post-unseal setup starting
2017/08/31 10:40:39.495802 [TRACE] core: clearing forwarding clients
2017/08/31 10:40:39.495822 [TRACE] core: done clearing forwarding clients
2017/08/31 10:40:39.495909 [INFO ] core: loaded wrapping token key
2017/08/31 10:40:39.495921 [INFO ] core: successfully setup plugin catalog: plugin-directory=/tmp/vault_plugins
2017/08/31 10:40:39.496180 [INFO ] core: successfully mounted backend: type=generic path=secret/
2017/08/31 10:40:39.496299 [INFO ] core: successfully mounted backend: type=system path=sys/
2017/08/31 10:40:39.496325 [ERROR] core: failed to create mount entry: path=mock/ error=no plugin found with name: mock-plugin
2017/08/31 10:40:39.496338 [INFO ] core: pre-seal teardown starting
2017/08/31 10:40:39.496344 [INFO ] core: cluster listeners not running
2017/08/31 10:40:39.496380 [INFO ] core: pre-seal teardown complete
2017/08/31 10:40:39.496388 [ERROR] core: post-unseal setup failed: error=failed to setup mount table
2017/08/31 10:40:39.496400 [WARN ] core: vault is sealed
```

> It can be unmounted successfully

This occurs successfully

**Comment by jefferai** [comment]
If it keeps Vault from starting up you basically have no way to fix the problem. Given that plugins are going to be lazy loaded, does this now just turn into "the dummy metadata plugin succeeds, then on lazy loading we fail"? Or no, because it validates that the underlying plugin exists?

One way to help prevent this might be to disallow removing a plugin from the catalog if any mount is using it, although for databases it might be tricky to actually check this.

**Comment by calvn** [comment]
The problem is that loading the dummy metadata plugin fails because that requires a legit call to the plugin, which is not in the catalog any more.

> Or no, because it validates that the underlying plugin exists?

Yes, there is validation performed to make sure that the underlying plugin exists. There is an eventual call to `LookupPlugin` whether on loading the metadata plugin or lazy loading the plugin.

**Comment by jefferai** [comment]
Ah, right, right.

It's a weird situation because for builtins we know that the backend will never go away, but we don't really want people to get totally hosed by removing a plugin.

Maybe for plugins we should simply not fail, but not mount that backend, if the underlying plugin no longer exists. This should cause all sort of errors that a sysadmin will get alerted to, but at least then they will be able to fix such a mistake.
