### ISSUE TITLE
Update to Comparison Site

### ISSUE THREAD

**Issue by calphool** [hashicorp/vault#3326]
I am requesting an update to the Vault comparison site (https://www.vaultproject.io/intro/vs/index.html) to include BeyondTrust Powerbroker.  It *seems* like there's a pretty significant overlap.

Gartner apparently reached out to Hashicorp to ask essentially this same question, and you apparently didn't respond (see Gartner's 2017 Market Guide for Privileged Access Management).

It *appears* that these are Vault's competitors:  Applecross, Arcon, Avecto, BeyondTrust, CA, Centrify, CyberArk, Fox Technologies, HelpSystems, MasterSAM, MicroFocus, One Identity, Raz-Lee Security, Thycotic, Vision Solutions, Balabit, Devolutions, NRI, ObserveIT, RedHat idM, Securelink, SSH Communications, and Venafi.  It would be nice to have a comparison of the products of as many of those as is reasonable.

**Comment by jefferai** [comment]
Hi @calphool ,

We don't have experience with most of those technologies, and wouldn't want to write comparison pages based on speculation. If you feel like submitting PRs and can link to documentation that we can verify then I'm happy to add such pages, or we can add them over time as/when we gain significant insight into any of them. We certainly don't claim that list to be exhaustive.

I know that we have been in discussions with Gartner both in the past and very recently, so I can't comment on the veracity of your information about Gartner reaching out and us not responding, and you don't mention a source. If the source is the market guide, I can't verify any such claims since it's behind a paywall.

**Comment by calphool** [comment]
The source is the "Gartner's 2017 Market Guide for Privileged Access Management" document.  It asserts that they reached out to you and you didn't respond.

**Comment by jefferai** [comment]
I've asked around internally, and nobody knows the answer yet, but I hear some related grumbles having to do with our previous PR firm. It's possible that however it is they reached out, the communication never made its way to us. We have talked with them more recently than the publication of that report, though, so whatever communication issues there were appear to have been ironed out.

Closing this; feel free to send PRs as desired and we'll update with information as we know more.
