### ISSUE TITLE
Miss command LIST in /database/creds/:name

### ISSUE THREAD

**Issue by renanberto** [hashicorp/vault#3353]
Hello Guys, I started using vault for two days, I ended up making an app to consume the API and work with the data. However, I noticed the lack of a much needed command to verify the current passwords and quantity.

Today there is this command to create a new credential:
`curl -s -H "$ROOT_KEY" $VAULT_ADDR/v1/database/creds/$PATH_NAME`
where PATH_NAME is the name of my role.

But it is necessary to list all the credentials that already exist, something similar to:
`curl -s -X LIST -H "$ROOT_KEY" $VAULT_ADDR/v1/database/creds/$PATH_NAME`

There is already this API or command?

https://www.vaultproject.io/api/secret/databases/index.html#generate-credentials

**Comment by chrishoffman** [comment]
By design, there is no way to query for the passwords that exist after they are created.  You can however lookup the associated leases that exist for a dynamic secret path.  

It would look something like this:
`curl -s -X LIST -H "$ROOT_KEY" $VAULT_ADDR/v1/sys/leases/lookup/database/creds/$PATH_NAME`

https://www.vaultproject.io/api/system/leases.html#list-leases
