### ISSUE TITLE
Vault UI - Unauthorized secret backends 

### ISSUE THREAD

**Issue by censored** [hashicorp/vault#3366]
**Environment:**
* Vault Version: Vault v0.8.2+pro ('f6153a5487af04f3e05f4f2f4f00ea1f4e564412+CHANGES')
* Operating System/Architecture: Ubuntu Xenial 16.04.1 LST x86_64

**Vault Config File:**
N/A

**Startup Log Output:**
N/A

**Expected Behavior:**
Attempting to view a secret backend you don't have permissions to tells you "You don't have permissions" and allows you to navigate back to the root.

**Actual Behavior:**
Viewing a secret backend you are not authorized to view displays
```
You don't have access to linux/undefined. If you think you've reached this page in error, please contact your administrator.
```
The '```navigate back to the root```' link or '```back to secrets```' button redirects back to https://vault.dev.xx.com/ui/vault/secrets/linux/list rather than say, https://vault.dev.bigfishgames.com/ui/vault/secrets and keeps you on the Not authorized error screen.

**Steps to Reproduce:**
* Create a secret backend
* Generate and apply a policy to your user which denies access (or in my case, does not grant access) to the particular backend
* Attempt to view the backend in the UI

**Comment by meirish** [comment]
Unfortunately, that _is_ the "you don't have permissions" message (though there's an issue in the display with the root level there it should just be `linux/`. We currently don't have a way to know if your token doesn't have access to the whole backend. As an example: if you have a policy that sets `deny` on `secret/*` but then later one that has `update` for `secret/foo`, you would still be able to take action on `secret/foo`.  The UI doesn't have a good way to show you the parts you do have access to if you can't navigate there from the root because there's no good way to glean that from the API. I do agree that the link back should be to the secret backends list if you get that error at the root of a backend though - I'll change that so we can get it out in a future release.

**Comment by censored** [comment]
That sounds just fine, thanks!

**Comment by beoSheep** [comment]
Hi, are you planning to somehow workaround this insane "feature"?

Currently the UI is unusable if you create multiple policies for different teams. You must grant secret/* **list** permissions for users to be able to browse to their secrets and use UI to create secrets.

**Comment by jefferai** [comment]
If you don't want to give list permission, you can manually modify URLs, just as if you were manually typing paths in the CLI.

There isn't really a way around it. If people can't list, the UI can't know what's there. Plain and simple.

**Comment by meirish** [comment]
Closing for now as I don't believe this is still an issue. We are working on something to help with the listing of secrets, but likely won't make the cutoff for 1.1.
