### ISSUE TITLE
Feature Request: Transit - hierarchical keys in 

### ISSUE THREAD

**Issue by shatl** [hashicorp/vault#3380]
**Feature Request:**

Add ability to use hierarchical key names in Transit storage. E.g.
`transit/userProfiles/foo`

**Environment:**

* Vault Version:
Vault v0.8.3 ('6b29fb2b7f70ed538ee2b3c057335d706b6d4e36')

**Expected Behavior:**
`Success! Data written to: transit/keys/foo/bar`

**Actual Behavior:**
```
Error writing data to transit/keys/foo/bar: Error making API request.

URL: PUT http://127.0.0.1:8200/v1/transit/keys/foo/bar
Code: 404. Errors:

* 1 error occurred:

* unsupported path
```

**Steps to Reproduce:**
`vault write -f transit/keys/foo/bar`

**Important Factoids:**

**References:**

**Comment by vishalnayak** [comment]
Issues that are not reproducible and/or not had any interaction for a long time are stale issues. Sometimes even the valid issues remain stale lacking traction either by the maintainers or the community. In order to provide faster responses and better engagement with the community, we strive to keep the issue tracker clean and the issue count low. In this regard, our current policy is to close stale issues after 30 days. Closed issues will still be indexed and available for future viewers. If users feel that the issue is still relevant but is wrongly closed, we encourage reopening them.
   
Please refer to our [contributing guidelines](https://github.com/hashicorp/vault/blob/main/CONTRIBUTING.md) for details on issue lifecycle.
