### ISSUE TITLE
Vault server -dev windows not working

### ISSUE THREAD

**Issue by Lechucico** [hashicorp/vault#3405]
Hello,

I'm using Windows 10 home edition x64 with vault version 0.8.3.

When I execute vault server -dev everything goes ok with the desired output.

Next step I use the following command: set VAULT_ADDR=http://127.0.0.1:8200

After that I try `vault status` and this error appears: 
**Error checking seal status: Get https://127.0.0.1:8200/v1/sys/seal-status: http: server gave HTTP response to HTTPS client**

**Comment by jefferai** [comment]
Are you performing the `set` command in the same terminal window where you are running `vault status`?

**Comment by Lechucico** [comment]
Yes. 

I've solved it going to system variables and adding vault variable manually.

**Comment by jfgossage** [comment]
I am experiencing the same problem on Ubuntu 18.04 desktop. I have UFW running and have enabled `127.0.0.1 to 127.0.0.1 8200/tcp`. I am attempting to follow the instructions in https://www.vaultproject.io/intro/getting-started/dev-server.html. Can you make any suggestions as to what I should do to work around this?

**Comment by chrishoffman** [comment]
@jfgossage Your issue seems to be unrelated to the issue above.  Can you please open a new issue so we can try and help out?

**Comment by pablonautic** [comment]
Hi guys,

I've just hit the very same problem mentioned @Lechucico .

After spending a bit of time investigating, it turned out that the problem is indeed Windows specific, and precisely, it depends on which shell are you using :)

So the output written by Vault 

`set VAULT_ADDR=http://127.0.0.1:8200` 

works perfectly fine when run using `cmd.exe` but does not work at all when using `Powershell`.

Is `PS` you have run something like `$env:VAULT_ADDR="http://127.0.0.1:8200"` and then `vault status` works like a charm :)
