### ISSUE TITLE
DR site step-down fails

### ISSUE THREAD

**Issue by censored** [hashicorp/vault#3460]
**Environment:**
* Vault Version: Vault v0.8.3+pro ('a0ce18244b6ef266f7b967d5fa204dcaff675c0d+CHANGES')
* Operating System/Architecture: Ubuntu Xenial 16.04

**Vault Config File:**
```
ui = true

default_lease_ttl = "4h"
max_lease_ttl = "8h"

listener "tcp" {
  "address" = "0.0.0.0:8443",
  "cluster_address" = "0.0.0.0:8444",
  "tls_cert_file" = "/etc/certs/com.combined.crt",
  "tls_key_file" = "/etc/certs/com.key",
}

storage "consul" {
    ha_enabled = "true",
    address = "unix:///tmp/.consul.sock",
    path = "vault",
    consistency = "stale",
    scheme = "http",
    service = "vault",
    tls_cert_file = "/etc/certs/com.crt",
    tls_key_file = "/etc/certs/com.key",
    tls_ca_file = "/etc/certs/geotrust_wildcard_intermediate_CA-G3.crt",
    cluster_addr = "http://vault.xx.com:8444/",
    redirect_addr = "https://vault.xx.com:443"
}

telemetry {
    statsd_address = "graphite-relay.xx.xx.com:8125",
    disable_hostname = true
}
```

**Expected Behavior:**
DR is enabled between 2 sites. The DR site has an active and standby node. When needing to fail over to a secondary host in the DR site, a step-down should succeed

**Actual Behavior:**
```
steph@purgatory:~$ VAULT_ADDR=https://vault01.ash.xx.com:8443 vault step-down
Error stepping down: Error making API request.

URL: PUT https://vault01.ash.xx.com:8443/v1/sys/step-down
Code: 400. Errors:

* Path disabled in replication DR secondary mode
```

**Steps to Reproduce:**
* Set up a DR site with 2 nodes
* Attempt to step down the primary so maintenance can be performed

**Important Factoids:**
As I need to do maintenance on the primary node in the DR site, I am unable to step it down. Even though the secondary node is online, functioning and unsealed, shutting down the primary node doesn't allow it to properly fail over and thus consul gets stuck in an election attempt loop.

I suppose spinning up a 3rd node will help me avoid this election problem, however being able to cleanly step down the active DR node would be ideal to avoid this situation.

**Comment by jefferai** [comment]
Step-down is disabled on secondaries because we don't authenticate tokens. We are working on other ways to authenticate this call. Note that sealing has the same behavior.

For now, simply gracefully terminate the vault instance (e.g. via SIGHUP or SIGINT). This performs the same workflow internally and will cause a standby node to take over for the active cluster.

**Comment by censored** [comment]
The standby node did not take over as I expected it to. If I restart vault in my primary site with 2 hosts, fail over works fine. If I restart vault on the dr site, fail over does not work.

**Comment by jefferai** [comment]
What are your logs from those instances? From before you said "consul gets stuck in an election attempt loop". If Consul is having some kind of election issue, Vault is not going to be able to behave properly since Consul will not be available.

**Comment by censored** [comment]
I'll run a restart and let you know tomorrow. I just found it odd since doing it in the primary site worked, but then the secondary hated me. We'll see!

**Comment by jefferai** [comment]
If things are unhappy in Consul you should definitely be seeing errors in both logs, so that would be good to check. Outside of not supporting the actual step-down/seal commands, There is nothing specific to replication of either type or either type of host with respect to local cluster HA, so it is much more likely there is some other local cause within that cluster.
