### ISSUE TITLE
Add ability to revoke all leases by role_id

### ISSUE THREAD

**Issue by chrishoffman** [hashicorp/vault#3478]
Currently, there is no easy mechanism to revoke all logins under a specific AppRole role_id. 

Original mail list request https://groups.google.com/forum/#!topic/vault-tool/3mNT54sNUkA.

**Comment by christophetd** [comment]
Thanks for opening this! If you're willing to accept a PR and to give me a pointer for where to start, I'd be glad to send one out.

**Comment by chrishoffman** [comment]
After some internal discussions, we will probably not add role_id to the login path due to the security implications of the change.  Some Vault users treat role_id as a secret value instead of just a sensitive value.  Adding role_id to the login path would allow it to show up in other places, such as audit logs, lease lookups, etc. 

Right now the suggestion would be to lookup the accessors and loop over the accessors to revoke.  I am keeping this open since this isn't ideal and updated the title and description to better reflect the problem we need to solve.

**Comment by christophetd** [comment]
Thank you for the update. 

For this use case, I wrote a script using Vault's Go API client that does the following.

- Revoke any authentication token created for a specific AppRole
- Revoke any secret ID bound to a specific AppRole

In a model where you'd use one AppRole per application, this script could be used as a "break-glass" procedure in case an application (along with its role-id and secret-id and potentially its authentication tokens) gets compromised.

Does this approach make sense to you @chrishoffman?

**Comment by chrishoffman** [comment]
The secrets should get revoked when you revoke the authentication token created by the AppRole.  Other than that, the procedure looks sound.

**Comment by christophetd** [comment]
Unless I'm mistaken, secret-ids won't be revoked when the corresponding authentication tokens are.

```
$ vault write -f auth/approle/role/myservice_role/secret-id
Key               	Value
---               	-----
secret_id         	f0a3d58d-79d9-22e6-e715-144fa86c7108
secret_id_accessor	32e49655-53d5-3053-31ab-4bf323d87cdc

$ vault read auth/approle/role/myservice_role/role-id
Key    	Value
---    	-----
role_id	aa5e5dbb-ee6a-75ae-7824-fe13ebe7cfe3

$ vault write auth/approle/login role_id=aa5e5dbb-ee6a-75ae-7824-fe13ebe7cfe3 secret_id=f0a3d58d-79d9-22e6-e715-144fa86c7108
Key                 	Value
---                 	-----
token               	c24f2659-bd40-1295-8d55-f64e9e115644
token_accessor      	8dfe2889-eac4-5150-2821-bd750c7dea2e
token_duration      	768h0m0s
token_renewable     	true
token_policies      	[default myservice-policy]
token_meta_role_name	"myservice_role"

$ vault write -f auth/token/revoke-accessor accessor=8dfe2889-eac4-5150-2821-bd750c7dea2e
Success! Data written to: auth/token/revoke-accessor

$ vault write auth/approle/login role_id=aa5e5dbb-ee6a-75ae-7824-fe13ebe7cfe3 secret_id=f0a3d58d-79d9-22e6-e715-144fa86c7108
Key                 	Value
---                 	-----
token               	55435449-3a44-87b8-d35a-424cd0abb44e
token_accessor      	715f4e70-f9d3-8e1c-7f04-bda6266ac7b7
token_duration      	768h0m0s
token_renewable     	true
token_policies      	[default myservice-policy]
token_meta_role_name	"myservice_role"
```

Here I revoked one of the tokens generated using a secret ID, but the secret ID itself wasn't revoked - which makes sense to me.

The converse of what you said doesn't seem to apply either, since revoking a secret ID doesn't revoke the authentication tokens that were generated using this secret ID. Example:

```
$ vault write -f auth/approle/role/myservice_role/secret-id
Key               	Value
---               	-----
secret_id         	0fd60dd1-1fef-7faf-8697-170c2700e9f2
secret_id_accessor	63df5e4f-1ae6-1498-cdc7-443931b5d740

$ vault read auth/approle/role/myservice_role/role-id
Key    	Value
---    	-----
role_id	aa5e5dbb-ee6a-75ae-7824-fe13ebe7cfe3

$ vault write auth/approle/login role_id=aa5e5dbb-ee6a-75ae-7824-fe13ebe7cfe3 secret_id=0fd60dd1-1fef-7faf-8697-170c2700e9f2
Key                 	Value
---                 	-----
token               	c4fea0d5-c9af-781d-c999-1f8b959b95f0
token_accessor      	761ec9a1-8e85-1585-9ad5-be9511045444
token_duration      	768h0m0s
token_renewable     	true
token_policies      	[default myservice-policy]
token_meta_role_name	"myservice_role"

$ vault write auth/approle/role/myservice_role/secret-id-accessor/destroy secret_id_accessor=63df5e4f-1ae6-1498-cdc7-443931b5d740
Success! Data written to: auth/approle/role/myservice_role/secret-id-accessor/destroy
```

Here I revoked the secret ID, and indeed I can't generate auth tokens from this secret anymore:

```
$ vault write auth/approle/login role_id=aa5e5dbb-ee6a-75ae-7824-fe13ebe7cfe3 secret_id=0fd60dd1-1fef-7faf-8697-170c2700e9f2
Error writing data to auth/approle/login: Error making API request.

URL: PUT http://localhost:1234/v1/auth/approle/login
Code: 400. Errors:

* failed to validate SecretID: invalid secret_id "0fd60dd1-1fef-7faf-8697-170c2700e9f2"
```

**But** I can still use the authorization token generated earlier by this secret ID to authenticate to Vault.

``` 
$ vault auth c4fea0d5-c9af-781d-c999-1f8b959b95f0
Successfully authenticated! You are now logged in.
token: c4fea0d5-c9af-781d-c999-1f8b959b95f0
token_duration: 2764652
token_policies: [default myservice-policy]
```

Did I miss something, or is there something wrong?

**Comment by chrishoffman** [comment]
Sorry, I misunderstood. I thought you meant secrets created by your AppRoles (dynamic secrets) not secret ids for your AppRole.  Looks good!

**Comment by coxd** [comment]
Hi - came across this issue because I was looking for the same functionality - to be able to revoke tokens when deleting an AppRole. Forgive my potential ignorance - couldn't you use the approle name in the login path rather than the role ID? This is not considered as sensitive (you don't auth with it) and it is also stable/immutable. The role id for an approle can actually be changed via the older push model/update.

**Comment by jefferai** [comment]
@coxd It's mutable both ways. You can delete an approle, then create a new role with the same name.

Note that sudo is _per path_ just like all other capability grants. You can give someone access to the token accessors listing call without giving them access to anything else. Sudo also still requires appropriate read/write/delete capabilities to go with it -- it's additive. The point of sudo is just a way for us to hint to operators that this is a potentially dangerous operation.

**Comment by coxd** [comment]
@jefferai good point around delete/recreate making it mutable :). Thank you for the hints on sudo - didn't realize this. Using the information available from token accessors still requires some hoops that don't really solve the mutable nature of the approle name (or role id). Given the initial objection above around adding role id to the login path was around it being considered secret (and we do consider it a secret) is there an objection to adding the role name to the login path?

**Comment by jefferai** [comment]
The path is set by the request path; you can't just modify the path contained in the token without special-casing that I don't want to do.

Normally the way you'd handle this is by putting the role name in the metadata that is returned by the backend, which is written into the token, so when listing accessors you can see the metadata. The problem with approle is that it allows the user to specify metadata, and potentially overwriting user-specified metadata is never ideal.

One possibility might be to add the role name to the metadata if the user has not specified any custom metadata (leaving it up to the user to add the role name on their own if they write custom metadata). We could also just unilaterally write the role name into it, as it seems like it should never be _unsafe_ behavior even if some users might find it _undesired_. I just foresee some user complaining that this breaks something because they don't want the role name in metadata for some internal security reason, and then we're in a situation where we have to add another flag just to opt-out.

Which brings up a third possibility, which is just to have a flag that defaults to true that causes the role name to be written into metadata, regardless of whether custom metadata has been set or not. Probably the best option.

**Comment by vishalnayak** [comment]
Issues that are not reproducible and/or not had any interaction for a long time are stale issues. Sometimes even the valid issues remain stale lacking traction either by the maintainers or the community. In order to provide faster responses and better engagement with the community, we strive to keep the issue tracker clean and the issue count low. In this regard, our current policy is to close stale issues after 30 days. Closed issues will still be indexed and available for future viewers. If users feel that the issue is still relevant but is wrongly closed, we encourage reopening them.
   
Please refer to our [contributing guidelines](https://github.com/hashicorp/vault/blob/main/CONTRIBUTING.md) for details on issue lifecycle.
