### ISSUE TITLE
Use vault as authorization server for external services

### ISSUE THREAD

**Issue by nwwells** [hashicorp/vault#3480]
**Feature Request:** Policies are a powerful RBAC implementation. Also, they seem relatively well abstracted away from the rest of the vault implementation. My suggestion is to provide a mechanism to use policies for resources defined in other services. This means exposing possibly 2 paths: 

1. take a token and return all the paths + capabilities in JSON or HCL
2. take a token, path and operation (`read`, `write`, etc.) and return 200 if authorized or 403 if not.

**Comment by vishalnayak** [comment]
Issues that are not reproducible and/or not had any interaction for a long time are stale issues. Sometimes even the valid issues remain stale lacking traction either by the maintainers or the community. In order to provide faster responses and better engagement with the community, we strive to keep the issue tracker clean and the issue count low. In this regard, our current policy is to close stale issues after 30 days. Closed issues will still be indexed and available for future viewers. If users feel that the issue is still relevant but is wrongly closed, we encourage reopening them.
   
Please refer to our [contributing guidelines](https://github.com/hashicorp/vault/blob/main/CONTRIBUTING.md) for details on issue lifecycle.
