### ISSUE TITLE
Composable policies

### ISSUE THREAD

**Issue by sethvargo** [hashicorp/vault#350]
This came up as a result of a conversation @mitchellh and I had. It would be great if policies could "inherit" from each other, for example:

``` javascript
// base.hcl
path "sys/renew/" {
    policy = "write"
}

path "auth/token/renew/" {
    policy = "write"
}
```

``` javascript
// app-transit.hcl
inherit "base"

path "transit/encrypt/app_" {
    policy = "write"
}

path "transit/decrypt/app_" {
    policy = "write"
}
```

Vault would need to check for circular dependencies, but I think it would be really helpful to compose policies like this.

**Comment by armon** [comment]
This is a great idea! It would definitely make management less challenging. Not actually that hard for us to implement either, if we only support a strictly linear chain.

**Comment by sethvargo** [comment]
I agree, and I think we need to be strict about it. If we allowed versioned policies, next thing you know you'll be writing a dependency solver :stuck_out_tongue_closed_eyes:

**Comment by jefferai** [comment]
If we do this we definitely need a way to get the full set of applicable rules written out on request.

**Comment by coderanger** [comment]
Was this closed for an actual reason?

**Comment by vishalnayak** [comment]
@coderanger 

Some of the Vault issues were closed by mistake from a syncing software. We apologize for the confusion caused. We have reopened the issues that were closed and are investigating the problem that caused this. Again, we are very sorry for the inconvenience.

**Comment by rfelsburg** [comment]
Any further word on this, It kind of dropped off. I'm also looking for the same policy inheritance capabilities.

**Comment by StyleT** [comment]
Really helpful feature when you want to manage ACLs for big organization (10+ teams).

**Comment by Gabology** [comment]
Yeah, this would be hugely useful for us. Right now updating policies usually involves changing a few policies, if we had some form of inheritance we would have to do less modifications.

**Comment by jefferai** [comment]
I'm going to close this at this point as there are currently no plans to implement composable policies in the manner suggested here.

Given that separate ACL policies already combine rules from individual policies, it's already pretty simple to manage this -- instead of the "base.hcl" import in the OP's example, simply put such rules into a "base" policy and attach that into tokens along with the "app-transit" policy. Each of these can be modified at any time since policies are evaluated on request.

Adding an import layer makes reasoning about resultant states more complicated and doesn't really provide additional functionality, just a different method of doing so.

**Comment by yakhyadabo** [comment]
Is there any progress regarding composable policies?
