### ISSUE TITLE
Limit number of policies a token issued against a role can obtain.

### ISSUE THREAD

**Issue by wrouesnel** [hashicorp/vault#3674]
**Feature Request:**

We would like to be able to limit the number of policies a role with a list of "allowed_policies" will grant to a token issued against it. A sample payload would be:
```json
{
"allowed_policies": [
    "dev"
  ],
  "max_token_policies": 1,
  "name": "nomad",
  "orphan": false,
  "renewable": true
}
```
The intent being to ensure applications operating as this role do not (through error) gain the ability to operate with more policy scope then they might otherwise want to.

The specific application is we have a "deployer" which needs to access multiple secrets in order to move them into the the deployment environment. Each application it deploys specifies a manifest of paths it would like access to, which in turn become app-specific policies. For simplicity (and audit log clarity) the deployer operates as an unprivileged token which then issues sub-tokens containing just the app policy (partly to validate a specific app should have access to those paths). It would be of great help if the issued tokens could be enforced by Vault to have a certain maximum number of policies at any one time (specifically, 1).

EDIT: Prototyping an implementation on https://github.com/wrouesnel/vault/tree/role_count_limited_tokens

**Comment by jefferai** [comment]
There are no plans to implement something like this anytime soon. This is already possible using Sentinel policies though.

**Comment by vishalnayak** [comment]
Issues that are not reproducible and/or not had any interaction for a long time are stale issues. Sometimes even the valid issues remain stale lacking traction either by the maintainers or the community. In order to provide faster responses and better engagement with the community, we strive to keep the issue tracker clean and the issue count low. In this regard, our current policy is to close stale issues after 30 days. Closed issues will still be indexed and available for future viewers. If users feel that the issue is still relevant but is wrongly closed, we encourage reopening them.
   
Please refer to our [contributing guidelines](https://github.com/hashicorp/vault/blob/main/CONTRIBUTING.md) for details on issue lifecycle.
