### ISSUE TITLE
vault crashes during start up if its unable to communicate with telemetry server

### ISSUE THREAD

**Issue by jaloren** [hashicorp/vault#3742]
I have vault configured to send dogstatsd metrics to prometheus statsd exporter. If the exporter is not yet addressable, then vault crashes with the following error.

```
Error initializing telemetry: failed to start DogStatsD sink. Got: lookup statsd.test.com on 127.0.0.11:53: no such host
```

**Environment:**
Vault v0.9.0 ('bdac1854478538052ba5b7ec9a9ec688d35a3335')
CentOS 7.3

**Vault Config File:**

```
{
  "telemetry": {
    "dogstatsd_addr": "statsd.test.com:9125",
    "dogstatsd_tags": [""]
  }
}
```

**Expected Behavior:**
Vault should be resilient failures from network service that it happens to be sending some data to. If vault is unable to resolve telemetry DNS or talk to the server, it should log this failure and then periodically retry.  

**Actual Behavior:**
Vault crashes during start up instead of automatically recovering and logging the failure.

**Comment by calvn** [comment]
@jaloren the current behavior is the expected behavior. From a behavioral perspective, having metrics defined but not firing up properly when Vault is started is not ideal, since people who rely on these metrics use them to determine Vault's health and if the metrics are not going through it means that Vault is either in an undefined or an assumed unhealthy (false-positive) state.

**Comment by jaloren** [comment]
@calvn It depends on how someone sets up their metric and alerting. 

If I am not receiving data from an application that itself should raise alert IMHO. But more importantly, vault is a critical piece of someones infrastructure. If that goes down, then many other systems will go down as well (because it cannot get secrets it needs to run). Moreover, the availability of the metric server now becomes a SPOF for high availability vault (every single vault instance will now fail to start up because it can't talk to the metric server). 

So in a situation where the metric server is down, instead of just having my metric server be unavailable (a problem but not service interrupting) I could have a potentially catastrophic site outage. As an operator who would like to avoid site outages, what about providing an option that allows someone to tell vault to simply log an error about this and continue to start up. This is btw exactly how the statsd telemetry option work. 

PS This seems like a really important detail to cover in the  documentation regardless of whether anything is done here.

**Comment by jefferai** [comment]
Based on your comment it seems like the issue isn't with go-statsd (since you said the statsd telemetry option works this way) but rather with the sink that DataDog has created. We are using their official sink from github.com/DataDog/datadog-go/statsd

As a result I think that is the right place for an enhancement/change request.

**Comment by jaloren** [comment]
@jefferai I think there might be a misunderstanding here. I am not sure what this has to do with dogstatsd library.

My understanding is that during vault start up, it invokes setupTelemetry function. If this returns an error when communicating with a  dogstatsd server, then this causes vault to os exit with code of 1. I am going off what I see here:

https://github.com/hashicorp/vault/blob/master/command/server.go#L221

So if my understanding is correct, then the issue i am raising is how vault handles a situation when it encounters an error while setting up telemetry. The consequence of the current behavior is that an issue with an external service becomes a SPOF for an HA vault and turns a problem with a metric server into a site outage.

If this behaving as designed, then I am making the following feature request: can we have an option that tells vault to recover from telemetry set up errors, finish start up, log the problem, and periodically retry telemetry setup?

**Comment by jefferai** [comment]
@jaloren The dogstatsd library maintains the network connection to the telemetry server, not Vault. So my suggestion was that such periodic retries might be something that they should be implementing.

I'm of mixed minds about whether Vault should simply fail or should continue. A lot of people consider telemetry information to be critical, and we generally don't like having Vault silently drop critical information.

**Comment by krish7919** [comment]
I would +1 for Vault to startup as it is a critical infra piece. If the metrics are missing, it is up to the alerting infra to alert on missing data.

Our infra is such that all our components depend on Vault, _even Datadog_, and now since Vault is down, nothing would come up as there is a cyclical dependency between Vault and Datadog.

Are there any plans to handle this?

**Comment by krish7919** [comment]
Opened https://github.com/hashicorp/vault/issues/8463 as this is closed.
