### ISSUE TITLE
Vault does not detect deletion of audit file.

### ISSUE THREAD

**Issue by seanjfellows** [hashicorp/vault#3935]
**Environment:**
* Vault Version: `vault version` shows `Vault v0.8.3 ('6b29fb2b7f70ed538ee2b3c057335d706b6d4e36')` but `vault status` shows `Version: 0.9.3+pro`.
* Operating System/Architecture: Ubuntu 14.04

**Expected Behavior:**
The documentation at https://www.vaultproject.io/docs/audit/index.html#blocked-audit-devices claims Vault will stop serving requests if it is failing to audit.

**Actual Behavior:**
Vault continues to write to the fd it has open even though the file is deleted from the file system. When Vault restarts, the audit log will be permanently lost. `lsof` shows vault writing into the deleted file, and indeed new entries are visible by opening the file from /proc/.../fd.

**Steps to Reproduce:**
Enable audit to file.
Rm the file after Vault opens it.

**Comment by jefferai** [comment]
The documentation is correct. The audit write succeeds, because the OS doesn't report to Vault that it has been deleted since the fd is valid, which you've confirmed by viewing it via `proc`. This is normal Unix-y behavior (technically it's not deleted/reclaimed by the OS until the last file handle is unlinked from the file). An important point is that from a Vault perspective, there's no difference between the file being "deleted" and moved to another location.

One obvious question (and a reason we haven't implemented anything so far) is what Vault should do if it detects that the file is no longer where it was. Stop working entirely? Alert? Often the reason for the file to be gone is because a log rotation program has moved it away (Vault will still successfully write to the file in the new location), and the rotation program then sends a SIGHUP to have Vault close and re-open the file so that the rotator can compress/ship/etc. At the Vault level, we have no insight into _why_ a file is no longer there, but that's a very, very common reason. If Vault were to fail audit logs between when the file moved from its original place and Vault was HUP'd you'd have unnecessary downtime for however long the process took.

Without some way to ensure that failing the log is the right thing to do, we leave it up to the operator to deal with these normal Unix file handling semantics. If you're uncomfortable with them, consider using the syslog audit mechanism or the socket mechanism to ship logs as soon as they are created.

**Comment by seanjfellows** [comment]
Thanks @jefferai for the quick and detailed reply.

I think everything you wrote makes sense, but I worry that the overall logic is circular. The documentation says:

> The device does not currently assist with any log rotation. There are very stable and feature-filled log rotation tools already, so we recommend using existing tools.

Taking this combined with your reply, it seems like the situation could be summarized as:
* Vault does not do log rotation because other tools can do it just fine.
* Vault cannot react to log file being moved because it does not do its own log rotation.

It seems to me it would be better if Vault insisted on doing its own log rotation and then would seal itself if it detects that the open fd does not correspond to the filesystem file. Unless there is some other scenario outside of rotation where the file and fd might not align?

**Comment by jefferai** [comment]
There's a third point though:

* Vault does not do log rotation because other tools can do it just fine. [I'd argue -- can do it _way better_]
* Vault cannot [automatically] react to log file being moved because it does not do its own log rotation.
* Vault can be HUP'd by a rotation tool to react to the log file being moved.

**Comment by seanjfellows** [comment]
I agree that other tools can do log rotation better from the perspective of rotation related features, but I guess the feature I am most after here is Vault's audit-failure-self-sealing mechanism. It would be a tradeoff between fancy log rotation features and guarantees around auditing.
