### ISSUE TITLE
Please update documentation for setting up TCP listener in Hashicorp vault docs.

### ISSUE THREAD

**Issue by frameworkdartboard** [hashicorp/vault#3978]
**Environment:**
$ vault -version
Vault v0.9.3 ('5acd6a21d5a69ab49d0f7c0bf540123a9b2c696d')

* Vault Version: 0.93
* Operating System/Architecture: Ubuntu 14.04 amd64

**Vault Config File:**
# https://www.vaultproject.io/docs/configuration/index.html
  
storage "file" {
  # https://www.vaultproject.io/docs/configuration/storage/filesystem.html
  path = "/opt/vault/storage"
}
  
listener "tcp" {
  # https://www.vaultproject.io/docs/configuration/listener/tcp.html
  address         = "0.0.0.0:8200"
  tls_cert_file   = "/opt/vault/config/vault.crt"
  tls_key_file    = "/opt/vault/config/vault.key"
}

**Startup Log Output:**

**Expected Behavior:**
The documentation at Hashicorp's website should explain how to set up the listener TCP configuration in full detail including the requirements to add an IP SAN that includes the address 127.0.0.1.

**Actual Behavior:**
The documentation did not explain anything about setting up the IP SAN.  It just says "put TLS cert here."

**Steps to Reproduce:**
Visit https://www.vaultproject.io/docs/configuration/listener/tcp.html .  Read documentation. Remain uninformed as to the IP SAN requirement.

**Important Factoids:**

**References:**

**Comment by jefferai** [comment]
IP SANs aren't a requirement; only if you are accessing via IP. This is nothing specific to Vault, it's a normal part of using X509 certs. If you think something could be more clear, feel free to submit a PR for us to look at.

**Comment by frameworkdartboard** [comment]
IP SANs may not be a requirement but since your documentation uses the
example "vault operator init" it is something that is going to come up
again and again.

When I google "hashicorp vault ip sans error" I find Google Groups entries
and github issue threads where you and other hashicorp team members have to
explain what is happening.

I can't imagine that it is in any way pleasurable to have to explain that
to person after person.

Please put something better in this section of the manual (
https://www.vaultproject.io/docs/configuration/listener/tcp.html ) than
what is there right now:


   -

   tls_cert_file
   <https://www.vaultproject.io/docs/configuration/listener/tcp.html#tls_cert_file>
    (string: <required-if-enabled>, reloads-on-SIGHUP) – Specifies the path
   to the certificate for TLS. To configure the listener to use a CA
   certificate, concatenate the primary certificate and the CA certificate
   together. The primary certificate should appear first in the combined file.
   -

   tls_key_file
   <https://www.vaultproject.io/docs/configuration/listener/tcp.html#tls_key_file>
    (string: <required-if-enabled>, reloads-on-SIGHUP) – Specifies the path
   to the private key for the certificate. If the key file is encrypted, you
   will be prompted to enter the passphrase on server startup. The passphrase
   must stay the same between key files when reloading your configuration
   using SIGHUP.

There is nothing in those 2 paragraphs which says how to create the
certificate in a way that will not result in this error:

$ sudo vault operator init
Error initializing: Put https://127.0.0.1:8200/v1/sys/init: x509: cannot
validate certificate for 127.0.0.1 because it doesn't contain any IP SANs

Help me to help you to not have to hear from me or people like me.

-Eric

**Comment by joelthompson** [comment]
My $0.02: I'm mostly sympathetic to @jefferai here.

First, not only do you need a TLS cert that has an IP SAN of 127.0.0.1, it **also** needs to be trusted. Should Vault explain how to get a TLS cert with an IP SAN of 127.0.0.1? It's unlikely you'll get such a TLS cert from a public CA (see section 3.2.2.5, "Authentication for an IP Address," of the [Baseline Requirements](https://cabforum.org/wp-content/uploads/CA-Browser-Forum-BR-1.5.4.pdf) -- I don't see how an applicant could demonstrate control over 127.0.0.1). So should Vault document how to generate your own CA, issue your own certificate with an IP SAN of 127.0.0.1, and then how to ensure that the custom CA is trusted? These are all very subtle things. And the exact same applies with using the DNS name of localhost. In these instances, I imagine that most people will just turn off TLS certificate verification (probably OK if you're talking to localhost/127.0.0.1, though might not be if you have untrusted users who can login to the system and try to attack other clients).

Second, the Vault team is in the business of providing a secret management tool, not educating people about TLS. These are very different problems that require very different skillsets to do well. And, speaking selfishly, I would want the Vault team to focus on what they do best, which is deliver an awesome secrets management tool and leave user education up to people who know how to do that well.

The reason I said mostly sympathetic is because it doesn't seem to be a great user experience to have the default (vault address being `https://127.0.0.1:8200` and verifying TLS certs) be something that is pretty much guaranteed not to work, but I'm not sure what the better UX would be. Maybe not have a default Vault server address? Maybe have the CLI print a big warning if you have a Vault server address of `'https://127.0.0.1:*` or `https://localhost:*` and are not setting `TLS_SKIP_VERIFY`? Maybe update the docs (e.g., [here](https://www.vaultproject.io/docs/commands/index.html#vault_addr)) with a note about the default value and how it's pretty much guaranteed not to work, and that users should set a vault server address using the same hostname clients will connect with? As Jeff said, if you think any of these would help you, feel free to submit a PR.

**Comment by noph** [comment]
I would like to see the default vault address be changed to either a non tls default endpoint ( http://127.0.0.1:8200 ) or an endpoint that is relatively common to have a trusted cert for like the hostname ( https://<hostname>:8200 )

Either one of those will work well out of the box and make the default ux much smoother.
