### ISSUE TITLE
PGP encrypting secrets bound for Vault to a Vault-held key

### ISSUE THREAD

**Issue by jgiles** [hashicorp/vault#3984]
**Feature Request:**
Enable writing secret fields to Vault encrypted to a PGP key generated and held within Vault.

The best-kept secrets are born in Vault and never leave (e.g. the `/pki/root/generate` route). However, some critically important secrets have to be created outside of Vault (e.g. the `secret_key` field of `/aws/config/root`). We consider these secrets safe once they are in Vault, but it's hard to be confident that copies of these secrets are not floating around elsewhere.

If Vault generated its own PGP key pair at init time, never returned the private key to clients, and made the public key available, then clients could encrypt secrets before sending them to Vault and Vault could decrypt the secrets internally. Secret creators could be confident that only Vault would be able to read the encrypted secret values.

This arrangement has a number of useful applications:
- Automation implementing the "give me your PGP key and I'll encrypt created secrets to you" pattern could be given the Vault's public key to approximate a "born in Vault" security model. For example, we could create our Vault root IAM credentials using Terraform [aws_iam_access_key's pgp_key parameter](https://www.terraform.io/docs/providers/aws/r/iam_access_key.html#pgp_key), and be fairly confident that only Vault would be able to use those near-root-authority credentials.
- We can better separate the role of Vault administrators/user from owners of other systems. For example, I help manage Vault at my organization but I am not the Duo admin. The Duo admin is not a Vault user. If I want to add Duo API creds to Vault, our Duo admin needs to create those credentials and send them to me so I can put them in Vault. I would rather not have a copy of those credentials that I can personally read. But the Duo admin can use GPG, and could encrypt the credentials to Vault.
- The [Vault Terraform provider](https://www.terraform.io/docs/providers/vault/index.html) is by far the best way I've found to manage Vault configuration as code. However, its [storage of secret information in Terraform state](https://www.terraform.io/docs/state/sensitive-data.html) is a critical flaw. We have an [icky workaround](https://github.com/terraform-providers/terraform-provider-vault/issues/65#issuecomment-361775092), but if we could specify secret fields encrypted to Vault we wouldn't have to worry about the state storage problem.

**API Ideas**

The public key could be available unauthenticated at some `/sys` endpoint (like the [CA Cert endpoints](https://www.vaultproject.io/api/secret/pki/index.html#read-ca-certificate)).

Encryption would be most useful if applied to individual field values (e.g. the `secret_key` field in the AWS root config).

We could go around adding extra `encrypted_blah` fields to all the various API requests, but that approach would be prone to missing some fields. It also would not work very well for the generic secret backend, where clients control the set of keys.

The best approach might be to add a new header like `X-Vault-Encrypted-Fields` to list the encrypted fields, and have a middleware layer around the logical handlers which would perform the needed decryption before passing the request along for processing. This would implement support across the board.

**Open Questions/Issues**

   - The [database plugin connection configs](https://www.vaultproject.io/api/secret/databases/index.html#read-connection) do not play very nicely with this scheme:
       - They permit reading back the configuration, which reduces confidence that only Vault has the credentials
       -  They mash password values in with non-secret configuration in one field

**Comment by jefferai** [comment]
Hi @jgiles ,

Thanks for submitting this!

I'll mostly put comments in line, but one thing I'll put up front: _These days_, I'm not a super huge fan of PGP. Not because of the underlying technology, but because it ends up being something that is very hard to get things to properly interoperate. I've used it with enough clients and services over the years to not be a huge fan of continuing to deal with it. Keybase is a notable exception that I really do love, but a lot of why they've been able to be successful here is because, internally, they are very standardized, so they don't need to worry as much about interoperation and all of the complexities involved. (They actually use their own serialization for encryption, for instance.) So it might be one thing to say "you can use this with keybase encryption and only keybase encryption" but I guarantee that immediately people that want to use gpg will be up in arms.

I say all that specifically to put out there up front that an immediate concern, outside of any of my other comments, is key management, key interoperability, encryption format/serialization interoperability, and all of the other things PGP brings with it.

> If Vault generated its own PGP key pair at init time, never returned the private key to clients, and made the public key available, then clients could encrypt secrets before sending them to Vault and Vault could decrypt the secrets internally. Secret creators could be confident that only Vault would be able to read the encrypted secret values.

You address this later, but my immediate response first reading this was -- but if clients are sending secrets to Vault, and that's over TLS, they don't need to encrypt it first. I'll get to the application you mention, but outside of those specific applications I think this is not really a widespread problem.

> Automation implementing the "give me your PGP key and I'll encrypt created secrets to you" pattern could be given the Vault's public key to approximate a "born in Vault" security model. For example, we could create our Vault root IAM credentials using Terraform aws_iam_access_key's pgp_key parameter, and be fairly confident that only Vault would be able to use those near-root-authority credentials.

I don't know anything about the provider or the pgp_key parameter, but if the idea is that terraform generates an IAM key and populates it into Vault, this should be running fully in-memory, right? In which case you don't buy much by having a separate step to encrypt the value that is then being sent to Vault...the plaintext value is still in memory.

> We can better separate the role of Vault administrators/user from owners of other systems. For example, I help manage Vault at my organization but I am not the Duo admin. The Duo admin is not a Vault user. If I want to add Duo API creds to Vault, our Duo admin needs to create those credentials and send them to me so I can put them in Vault. I would rather not have a copy of those credentials that I can personally read. But the Duo admin can use GPG, and could encrypt the credentials to Vault.

Sure, what you propose could solve this problem, but -- and I'm sure you can guess what I'm about to say here -- why not just give the Duo admin a Vault token? :-)  It's a very simple, authenticated/authorized, audited mechanism to get what you want done.

> The Vault Terraform provider is by far the best way I've found to manage Vault configuration as code. However, its storage of secret information in Terraform state is a critical flaw. We have an icky workaround, but if we could specify secret fields encrypted to Vault we wouldn't have to worry about the state storage problem.

I don't know enough about Terraform's internals to know why they don't support encrypting their state file with Vault (update: I just asked, and it's simply that it hasn't been done yet, but is a long term wishlist item of the team -- see https://github.com/hashicorp/terraform/issues/9556) -- but they certainly could, and that seems like a way better way to deal with this problem because you wouldn't have to specify which fields are sensitive, they would simply *all* be encrypted. I really do think that's the more ideal solution.

Overall my feeling is that this is a fine idea that doesn't map well to a specific problem space, because the cases in which this would be useful that you have outlayed are either more simply or better solved with other solutions.

**Comment by jgiles** [comment]
Thank you for the thorough response! Some replies inline.

> So it might be one thing to say "you can use this with keybase encryption and only keybase encryption" but I guarantee that immediately people that want to use gpg will be up in arms.

I'd be happy with using keybase :-). But in all seriousness, I think it would be reasonable to constrain the set of accepted inputs. The PGP suggestion was mostly because Vault already does a bit of that.

> You address this later, but my immediate response first reading this was -- but if clients are sending secrets to Vault, and that's over TLS, they don't need to encrypt it first. I'll get to the application you mention, but outside of those specific applications I think this is not really a widespread problem.

I agree that probably only a small set of secrets sent to Vault merit this treatment. But, those secrets are *very important*. Mostly, I'm interested in:

- effectively-root production AWS IAM access keys
- root production AWS RDS database passwords

For context, we are setting up a system where non-Vault-mediated access to our AWS resources triggers a pager alert (via CloudTrail). Vault's exclusive ownership of these credentials is a linchpin of the arrangement.

We could implement something like this for just the fields we consider "extremely sensitive", but different clients might have different ideas about what fields qualify.

> I don't know anything about the provider or the pgp_key parameter, but if the idea is that terraform generates an IAM key and populates it into Vault, this should be running fully in-memory, right? In which case you don't buy much by having a separate step to encrypt the value that is then being sent to Vault...the plaintext value is still in memory.

It's not always possible for the same `terraform apply` operation to both create the IAM keys and send them to Vault - these operations might be performed at separate times, by separate people, with different credentials. In any case, if you don't provide a PGP key to the `aws_iam_access_key`, it puts the secret value in plaintext in an attribute stored in the Terraform state (see below on Terraform state).

> Sure, what you propose could solve this problem, but -- and I'm sure you can guess what I'm about to say here -- why not just give the Duo admin a Vault token? :-) It's a very simple, authenticated/authorized, audited mechanism to get what you want done.

That's not always as simple as it sounds. For instance, we would need to provision our Duo admin with production VPN access in order for them to talk to Vault.

> I don't know enough about Terraform's internals to know why they don't support encrypting their state file with Vault (update: I just asked, and it's simply that it hasn't been done yet, but is a long term wishlist item of the team -- see hashicorp/terraform#9556) -- but they certainly could, and that seems like a way better way to deal with this problem because you wouldn't have to specify which fields are sensitive, they would simply all be encrypted. I really do think that's the more ideal solution.

I actually do not like the "encrypt the whole Terraform state" approach here. If the whole Terraform state is encrypted, then you have to decrypt the whole Terraform state any time you want to use any of its output values or update some mundane piece of configuration, which means all the admins who use or reference the Terraform module will be able to read all the contained secret values, including those that were meant to only ever be held by Vault. I don't want *anyone* short of a very determined quorum of Vault unseal token handlers able to read the root IAM credentials we give to Vault.

**Comment by jefferai** [comment]
> The PGP suggestion was mostly because Vault already does a bit of that.

.................yeah.

More seriously, the way I'm looking at your problem is very TF-focused because it's really something we should look at improving for TF. I realize not all workflows where you may want to address this kind of issue is in TF (your Duo admin example, which I'm sensitive to, I promise), but putting some system into Vault would _still_ entail putting such a system into TF to take advantage of it (or even worse, coding in support to hundreds of providers) so holistically/from high enough up it looks like making TF behave better is a win for both products without doing anything super special purpose that entails major architectural changes to Vault in ways that I haven't figured out yet. So this isn't to say that a system in Vault couldn't/wouldn't be welcomed at some point, just that I think there are better wins that can be achieved by trying to look at where TF can improve its security globally.

I had a long discussion with some of the TF devs last night about this; encrypting a state file is one thing...keep in mind, if you can mark in Terraform that a value is sensitive and should be encrypted, nothing says that you can't have Terraform spit out a decrypted version of the state file with any such-marked fields redacted, leading to the same effective behavior. The other thing I asked about is ephemeral values. Essentially, it seems from your examples above that there are cases where you want Terraform to act as the _transport_ for values but have no reason to keep them in Terraform state, encrypted or otherwise.

The obvious problem is "if Terraform doesn't have it in its state file how can it know whether something needs to be run". I think the answer could be relatively simple; something as simple as state protected by env vars such that the state is only considered if an env var is non-empty. I know that in many cases automated processes run TF based on state file changes, but it strikes me as something that you _generally don't want running_ and where a bit of manual interaction to force this particular process to run is not necessarily a bad idea.

Finally: dealing with PGP and identity and keyrings and subkeys -- none of which are actually needed for this ask -- is something I'm not feeling happy about. On the other hand, standard mechanisms of encrypting with the types of keys used in PGP are simpler, albeit not necessarily on the command line. One of the downsides of using RSA is that you can't encrypt large values, but you *can* encrypt a data key which itself is used to encrypt the value. What I'm getting at is that if there is sufficient demand for this (I can't tell you what "sufficient" might be since this would be a big enough lift to have to officially be on a roadmap, I suspect, and that's controlled by more than just me) I may be more amenable to having a sort of "vault encrypt" CLI command that just uses a standard RSA public key, generates a data key, uses AES or ChaCha to encrypt the actual value, and bundles it all up. Less unneeded PGP magic.

**Comment by jgiles** [comment]
re: Terraform changes to take advantage of a Vault PGP encryption feature, the immediate thing I had in mind was a `vault_pgp_key` data source in the Terraform provider that just read the unauthenticated `/sys` endpoint mentioned above. That value would then be fed into the `pgp_key` field of the `aws_iam_access_key` resource or similar.

My hope here was that this would not actually involve a major Vault architectural changes - rather, the simplest possible PGP scheme (no subkeys), applied as a thin layer over the logical API interactions. Of course, I don't really have the familiarity with Vault internals (or PGP schemes really) to say whether that is the case.

I certainly would welcome general TF improvements in this area. On the other hand, https://github.com/hashicorp/terraform/issues/516 dates to 2014, so I'm less than optimistic that a Terraform-wide solution will be forthcoming soon. It's a very hard problem - if your resource produces a secret, how do you guarantee that it never ends up in an "insecure" field anywhere in the Terraform graph? Encryption at creation time is a fairly reasonable approach.

https://github.com/terraform-providers/terraform-provider-vault/issues/65 is a separate request to approximate your "terraform as transit" solution for just the Vault resources. However, that doesn't really give an end-to-end story for values produced by other resources (like `aws_iam_access_key`).

**Comment by jefferai** [comment]
> My hope here was that this would not actually involve a major Vault architectural changes - rather, the simplest possible PGP scheme (no subkeys), applied as a thin layer over the logical API interactions

In a theoretical sense it sounds like a thin layer, but I promise it's not as simple as it sounds :-)

>  It's a very hard problem - if your resource produces a secret, how do you guarantee that it never ends up in an "insecure" field anywhere in the Terraform graph?

Sure, but how do you know if something produces a secret? And, if you want to produce it in one place and have it encrypted in another in TF, you need pgp_keys-style parameters decorated around. Or, you can pass that value singly to Vault through transit to encrypt. Once you've identified things that are sensitive there are multiple possible ways to deal with them, but you have to get there first...

**Comment by vishalnayak** [comment]
Issues that are not reproducible and/or not had any interaction for a long time are stale issues. Sometimes even the valid issues remain stale lacking traction either by the maintainers or the community. In order to provide faster responses and better engagement with the community, we strive to keep the issue tracker clean and the issue count low. In this regard, our current policy is to close stale issues after 30 days. Closed issues will still be indexed and available for future viewers. If users feel that the issue is still relevant but is wrongly closed, we encourage reopening them.
   
Please refer to our [contributing guidelines](https://github.com/hashicorp/vault/blob/main/CONTRIBUTING.md) for details on issue lifecycle.
