### ISSUE TITLE
Improvement: Support for PKI certificate submission to Certificate Transparency logs

### ISSUE THREAD

**Issue by robison** [hashicorp/vault#4006]
**Feature Request:**
I've gone back and read quite a few other issues in the project asking after CRLs, OCSP, or support for some other certificate revocation/audit process, but could not immediately find anything about supporting Certificate Transparency logs. Is this something that would be considered, or is currently worked on internally? Happy to submit a PR in the near term, for review.

**Comment by jefferai** [comment]
Generally we would prefer that this kind of operation be handled independently outside of Vault so that Vault doesn't have to deal with soft failures, which is something we try to avoid with Vault. Given that logs are not required to be submitted to by CAs this is a valid workflow. There's also the question of how widely useful this is, given that most users of Vault PKI are issuing large numbers of very short-lived certificates, and this is the general workflow we recommend (thus obviating the need for CRLs/OCSP). Additionally, Vault already supports audit logs (although they're not currently cryptographically verifiable) so the issuance of certificates can be watched by monitoring agents in real-time.

**Comment by robison** [comment]
> Additionally, Vault already supports audit logs (although they're not currently cryptographically verifiable) so the issuance of certificates can be watched by monitoring agents in real-time.

I think that this is the most salient point, especially for PKI roles that may be considered higher-security. I think that this may be able to be implemented as an optional feature as a role flag, that would return a bool in the response from `/pki/issue/:name` if the CT-log in question either accepted the submission or not.

**Comment by catsby** [comment]
Hello - thank you for submitting this feature request. At this point this issue is almost 2 years old with no movement, so I'm going to go ahead and close this. We may consider a pull request that implements this feature, however as mentioned above, it's not something the Vault team will be implementing at this time. Thanks again!
