### ISSUE TITLE
Identity Secrets Engine + PGP/GPG = ♥️

### ISSUE THREAD

**Issue by StyleT** [hashicorp/vault#4025]
It would be great to have ability to give ability for the organization employees to upload/generate PGP/GPG & attach them to their Entity in Identity Secrets Engine. Together with Cubbyhole secret backend it gives ability to implement something like https://keybase.io/encrypt  
So organization employees will receive ability to sent encrypted messages to each other.

**Comment by jboero** [comment]
See this thread:
https://github.com/hashicorp/vault/issues/1347

**Comment by vishalnayak** [comment]
Issues that are not reproducible and/or not had any interaction for a long time are stale issues. Sometimes even the valid issues remain stale lacking traction either by the maintainers or the community. In order to provide faster responses and better engagement with the community, we strive to keep the issue tracker clean and the issue count low. In this regard, our current policy is to close stale issues after 30 days. Closed issues will still be indexed and available for future viewers. If users feel that the issue is still relevant but is wrongly closed, we encourage reopening them.
   
Please refer to our [contributing guidelines](https://github.com/hashicorp/vault/blob/main/CONTRIBUTING.md) for details on issue lifecycle.
