### ISSUE TITLE
Cannot get help after enabling auth approle or gcp

### ISSUE THREAD

**Issue by janbols** [hashicorp/vault#4056]
**Environment:**

* Vault Version: Vault v0.9.5 ('36edb4d42380d89a897e7f633046423240b710d9')
* Operating System/Architecture: Ubuntu 17.10 - x86_64

**Vault Config File:**

**Startup Log Output:**

```
 vault server -dev
==> Vault server configuration:

                     Cgo: disabled
         Cluster Address: https://127.0.0.1:8201
              Listener 1: tcp (addr: "127.0.0.1:8200", cluster address: "127.0.0.1:8201", tls: "disabled")
               Log Level: info
                   Mlock: supported: true, enabled: false
        Redirect Address: http://127.0.0.1:8200
                 Storage: inmem
                 Version: Vault v0.9.5
             Version Sha: 36edb4d42380d89a897e7f633046423240b710d9
```

**Expected Behavior:**

After enabling gcp auth, I should be able to get help information.

**Actual Behavior:**

Following error is shown:
```
vault auth help gcp   
INTERNAL ERROR! Found an auth method enabled at gcp/, but its type "gcp" is
not registered in Vault. This is a bug and should be reported. Please open an
issue at github.com/hashicorp/vault.
```

**Steps to Reproduce:**

1. vault auth enable gcp
2. vault auth enable gcp

The same applies when substituting gcp with approle

**Important Factoids:**

**Comment by jefferai** [comment]
This is a super confusing error message, including the fact that despite what it says it's not a bug, nor an internal error.

The problem is that some auth methods have CLI helpers that make it easier for people on the CLI to use them. `gcp` does not, so it's detecting that you have an auth method at `gcp/` but when it says that its type is not registered in Vault, it doesn't mean the Vault server, it means the CLI's set of method-specific helpers.

In the linked PR I updated those error messages to be more clear.
