### ISSUE TITLE
Error creating encryption keys using vault write -f

### ISSUE THREAD

**Issue by RohanKurane** [hashicorp/vault#4068]
@chrishoffman

Hey Chris,
Thanks for that.
I opened a new issue because I wasnt sure if you would get notified on a closed one (made a similar comment there)

Here is the latest (I want to use 12357 for the tcp port)

VAULT_ADDR="http://127.0.0.1:12357"
VAULT_TOKEN="c5b8be1c-30d2-e5ce-cced-0a0eeb59cf5f" --> from cat $HOME/.vault_token

cat config.hcl
storage "file" {
path = "/home/ubuntu/vaultdata"
}

disable_mlock=true

listener "tcp" {
address = "127.0.0.1:12357"
tls_disable = 1
}

ubuntu@penguin:~$ vault write -f secret/hello
Error writing data to secret/hello: Error making API request.

URL: PUT http://127.0.0.1:12357/v1/secret/hello
Code: 400. Errors:

** missing data fields**

Then when I try the same with sudo, I get a different error for port 8200 instead of 12357.
sudo vault write -f secret/hello
Error writing data to secret/hello: Put https://127.0.0.1:8200/v1/secret/hello: dial tcp 127.0.0.1:8200: getsockopt: connection refused
@RohanKurane

Attach files by dragging & dropping,

, or pasting from the clipboard.
Styling with Markdown is supported

**Comment by RohanKurane** [comment]
perhaps 'vault write -f" is not supported for the kv secrets engine ?

**Comment by joelthompson** [comment]
When you write to secret/hello, Vault is expecting input data to encrypted and then stored there. That's why vault write -f doesn't work -- you're not passing any data to be encrypted.

The transit engine operates differently. When you write to transit/keys/my-key, you're telling Vault to generate a brand new encryption key called my-key. You can then encrypt information by writing it to transit/encrypt/my-key -- that's analogous to writing to secret/hello, except that in the transit engine, Vault doesn't store it and instead just returns the encrypted data back to you.

Vault won't return the actual key material when reading from transit/keys/my-key, and it sounds like that's what you're expecting. If you want the actual key material, you'll need to flag the key as exportable/backup-able when [creating the key](https://www.vaultproject.io/api/secret/transit/index.html#exportable) or [updating the key](https://www.vaultproject.io/api/secret/transit/index.html#exportable-1) then use the [export](https://www.vaultproject.io/api/secret/transit/index.html#export-key) or [backup](https://www.vaultproject.io/api/secret/transit/index.html#backup-key) method -- however, I strongly advise against doing this unless you _really_ need to. There's a lot of security benefit in knowing that the key material has never left Vault -- it forces any decryptions to go through Vault, which is logged and auditable, and access can be controlled and revoked.

**Comment by joelthompson** [comment]
Also, RE:

> Then when I try the same with sudo, I get a different error for port 8200 instead of 12357.
sudo vault write -f secret/hello
Error writing data to secret/hello: Put https://127.0.0.1:8200/v1/secret/hello: dial tcp 127.0.0.1:8200: getsockopt: connection refused

That's because sudo drops a bunch of environment variables by default, and so it's dropping your VAULT_ADDR environment variable, causing the Vault client to default to https://12.0.0.1:8200

However, there's virtually no reason why running under sudo would make a difference in this case -- the Vault CLI essentially just does a bunch of HTTP commands for you to the Vault API, and running under sudo wouldn't really change anything in what Vault sees.

**Comment by RohanKurane** [comment]
@joelthompson 
Thanks Joel. 

So, if I understand you -

1. The 'kv' secrets engine needs data (key=value) on the write command. This will encrypt the data and store encrypted data in the storage backend. What encryption key is it using here ? 
The 'transit' secrets engine generates a new encryption key (using -f flag). Then when you do a vault write <data> to it, the transit engine encrypts the data using the encryption key generated and returns the encrypted data back to user. It does not store the encrypted data. 

2. No need to run under sudo.  Without sudo my port 12357 should be honored as in the config.hcl file.

I have some absolute basic questions regarding how Vault works with its secret engine and storage backend.  Can you please help clarify ?

Secrets engine are the ones that create, update, delete secrets. There are a bunch of secrets engine currently supported by Vault including kv, transit, AWS etc).  

Storage backend is where the secrets, encrypted data etc are stored. There are a bunch of built-in storage backends supported by Vault including filesystem, AWS, Database etc. 

I am trying to integrate Vault with my application which provides a storage backend. The storage backend is a directory on disk. I assume I can use storage: "file"  as my backend so all secrets and encrypted data gets written to the directory created by my application. Is that a correct assumption ? Or do I need to look into the 'plugin storage backend' section ?

**Comment by jefferai** [comment]
Closing this; it's both old and the vast majority of the questions are already answered by simply reading documentation.
