### ISSUE TITLE
bring your own key 

### ISSUE THREAD

**Issue by daniyalsuri** [hashicorp/vault#4092]
HI

I have been working on a project for my organization and one particular aspect of that project is i could use a tool for encryption as a service.
the challenge here is that can i provide my own self generated key and the data to be encrypted to vault and vault can perform encryption service?
i have seen the transit engine of vault but so far i have seen is that it uses the keys that are generated from vault, what if i want to bring my own key?
any help will be greatly appreciated!

Thanks in advance!

Daniyal

**Comment by vishalnayak** [comment]
Please post questions on the mailing list (https://groups.google.com/forum/m/#!forum/vault-tool) rather than in GitHub issues. This gets a lot more eyes on any particular question or idea.

It also prevents problematic issue workflows for questions where either the issue is closed immediately but then discussion continues on a closed issue; or, the issue is not closed, discussion dies down, and the issue remains open indefinitely waiting for further potential replies.

Thanks!

**Comment by jefferai** [comment]
@daniyalsuri Vishal is correct, please do use the ML, but I saw that you commented on another issue about exporting -- take a look at the backup endpoint. You can simply create restore blob with your key in the expected format and populate via the restore endpoint.

**Comment by daniyalsuri** [comment]
Thanks @jefferai but can you please explain your answer. I have listed this query on the mailing list now, you can check and we can commute about this more over there.
