### ISSUE TITLE
Kubernetes authentication: is it more secure than Kubernetes secrets?

### ISSUE THREAD

**Issue by raffaelespazzoli** [hashicorp/vault#4095]
My understanding of the kubernetes authentication is the the service account token presented by the requesting container is authenticated by the master via the token review request.

Some organizations look at Vault as a way to secure secrets in a more secure way than with kubernetes secrets.

Because the kubernetes authentication relies on a kubernetes secret (service account token), this mechanism is not more secure than using kubernetes secrets. In other words if I am able to steal a kubernetes secret, I can also steal the Vault secrets. To make things worse in kubernetes, service account token are never rotated.

Do I understand that right?

Could Vault use more information in this authentication? for example verify that the IP from which the request is coming is assigned to a pod with that IP?

**Comment by james-atwill-hs** [comment]
FWIW, Vault 0.10.2 now supports enforcing cidrs when authenticating to a Kubernetes auth point.

**Comment by ianferguson** [comment]
[Service Account Token Projection](https://kubernetes.io/docs/tasks/configure-pod-container/configure-service-account/#service-account-token-volume-projection) in Kubernetes v1.20+ may help with this as well

**Comment by vishalnayak** [comment]
Issues that are not reproducible and/or not had any interaction for a long time are stale issues. Sometimes even the valid issues remain stale lacking traction either by the maintainers or the community. In order to provide faster responses and better engagement with the community, we strive to keep the issue tracker clean and the issue count low. In this regard, our current policy is to close stale issues after 30 days. Closed issues will still be indexed and available for future viewers. If users feel that the issue is still relevant but is wrongly closed, we encourage reopening them.
   
Please refer to our [contributing guidelines](https://github.com/hashicorp/vault/blob/main/CONTRIBUTING.md) for details on issue lifecycle.
