### ISSUE TITLE
Vault DynamoDB read spikes

### ISSUE THREAD

**Issue by mohsinkerai** [hashicorp/vault#4114]
Vault is showing spiky behavior (after every 1 hour)
Vault Version (0.9.1)

We've deployed Vault in HA mode with DynamoDB, any leads why it is happening and how to solve it?

Attached Screenshot

![image](https://user-images.githubusercontent.com/9077390/37197643-58bfb78a-239d-11e8-8f1b-f29ca80f60cc.png) 

For reference
Spikes Times
14:45
15:46
16:47 and So on

**Comment by jefferai** [comment]
Without having any information about what paths are being accessed I can't say much, but I would image that it's because you have a lot of clients that are fetching and/or renewing and/or creating new secrets all at the same time. This can be the case if you e.g. boot up 100 nodes at the same time.

**Comment by mohsinkerai** [comment]
Going through Audit Logs / ELB Access Logs, there is no such activity along this time. 

We have `renew-self` token calls, secret get calls, but that spreads throughout hour and doesn't correlate with spikes.

Is there anything scheduled/maintenance task within vault? for example refreshing cache every hour or anything else which happens every hour?

**Comment by jefferai** [comment]
Vault doesn't have many automated tasks that it runs; really only for AppRole and AWS credential backends and these are invoked once a minute, not once an hour. Getting trace logs may prove illuminating; not much else I can think of at this point.

**Comment by brianshumate** [comment]
Hey there,

Given Jeff has explained that Vault doesn't have automated tasks at the observed frequency, have you considered that some other automated processes are accessing the DynamoDB instance outside of Vault?

The spikes are on intervals that certainly feel like an automation set to run at every 45 minutes; is there some kind of automated backup of DynamoDB or similar read intensive process occurring on a schedule for example?

**Comment by mohsinkerai** [comment]
Hello,

I'll paste TRACE logs in couple of days.

For backup, it is done daily (24 Hours), so I think it is out of question. Adding more light to it, we see Network out of our primary instance that co-relate with DynamoDB Write IOPS, similarly network in of primary instance with Dynamo Read IOPS.

Additionally at same time, we see read spike and write spike together at same time.

Time between spikes is 61 minutes.

Let me know if we need to monitor something else in-between.

**Comment by mohsinkerai** [comment]
Guys, Any Insights about following logs?

```
2018/03/23 03:57:32.861121 [INFO ] core: loaded wrapping token key
2018/03/23 03:57:32.861140 [INFO ] core: successfully setup plugin catalog: plugin-directory=
2018/03/23 03:57:32.868931 [INFO ] core: successfully mounted backend: type=kv path=secret/
2018/03/23 03:57:32.869066 [INFO ] core: successfully mounted backend: type=system path=sys/
2018/03/23 03:57:32.869238 [INFO ] core: successfully mounted backend: type=identity path=identity/
2018/03/23 03:57:32.869280 [INFO ] core: successfully mounted backend: type=aws path=aws-ec2/
2018/03/23 03:57:32.869307 [INFO ] core: successfully mounted backend: type=cubbyhole path=cubbyhole/
2018/03/23 03:57:32.899942 [INFO ] expiration: restoring leases
2018/03/23 03:57:32.900039 [INFO ] rollback: starting rollback manager
2018/03/23 03:57:33.232207 [INFO ] core: pre-seal teardown starting
2018/03/23 03:57:33.232297 [INFO ] core: cluster listeners not running
2018/03/23 03:57:33.387286 [INFO ] rollback: stopping rollback manager
2018/03/23 03:57:33.387443 [INFO ] core: pre-seal teardown complete
2018/03/23 03:57:33.387484 [ERROR] core: post-unseal setup failed: error=failed to update entity in MemDB: alias "24a08e8c-eb17-53a0-f13c-52caeabe60cd" in already tied to a different entity "1ae52fc3-b21c-a7be-57ec-8f445a2d7af8"
2018/03/23 03:57:34.403633 [INFO ] core: acquired lock, enabling active operation
2018/03/23 03:57:34.452615 [INFO ] core: post-unseal setup starting
2018/03/23 03:57:53.404863 [ERROR] core: error during forwarded RPC request: error=rpc error: code = Unavailable desc = all SubConns are in TransientFailure
```

A Brief summary of what happend
1. Suddenly Spike in Read was observed (Much Much Much Larger then presented in this Ticket)
2. Read Requests were throttled for 5 minutes
3. We lost Primary Instance, and no instance became primary again.

There are some logs that we were able to trace.

**Comment by ncorrare** [comment]
Hi @mohsinkerai
After discussing this with the team this seems to be aligned to the token creation and revocation process (the timeline fits with a big revocation process). The lack of lock acquisition might be attributed to an issue with eventual consistency in DynamoDB.

**Comment by aiwaniuk** [comment]
Hi,

I have the same issue (and it is still present after upgrade to 0.10.1):
- there are huge DynamoDB spikes every 1 hour.
- I have two server instances (HA Mode)
- There is no any special activity with the server when spike occurs
- There is noting interesting in TRACE log level
- This one hour period starts from server restart (So I guess this is prof that: it is not performed by any external thing operating on DynamoDB. And this is not caused by anything which speaks with vault server and its' likle that vault server is performing some sync every hour).
- This spikes grows over time +5% every two weeks (It is possible (but I'm n ot sure) that number of secrets/leases in vault also grows with the same value and is it ok, this just info that number of reads could correlate with number of items).

**Comment by calvn** [comment]
Do you have any tokens whose TTL (either directly or indirectly through policies) is set to expire after 1 hour, especially tokens that might derive a large number of child leases/tokens?

**Comment by aiwaniuk** [comment]
I'm using AWS secret engine (STS) with default settings and these creds by default are 3600 seconds.
I'm issuing large number of these creds.

**Comment by calvn** [comment]
That sounds like it's what might be causing the increased hourly spikes. If a large number of these creds are created all at once, their expiration will also happen at the same time. During revocation, Vault will make a number of calls to the underlying storage related to these leases.

**Comment by aiwaniuk** [comment]
I'm creating a lot of them at once, but this happens every 4 hours so this two things doesn't match. I will change this default time to something, else and perform some test to confirm if this things are related.

**Comment by aiwaniuk** [comment]
I can confirm that this was not caused by revocation of these secrets.
But I think I found something that could be the reason.
To access DynamoDB storage backed I'm using instance profile.
And I see in CloudTrail logs that vault server is refreshing creds every hour (I see AssumeRole calls).
So it is maybe something like this:
Vault server when obtaining new creds to access storage backend it is loading everything from dynamodb again?

**Comment by aiwaniuk** [comment]
Nope, leader is still the same and there is no single line in logs (TRACE level) in the time when issue occurs.

**Comment by aiwaniuk** [comment]
I have changed auth method from instance profile to access_key/secret_key in config file and disabled second standby instance and I still see that issue.

**Comment by MattSurabian** [comment]
As for the regularity of the spikes it's hard to say, are you using these settings in your config (obviously you may have them set to different values)?
```
        max_parallel = "25"
        read_capacity = 50
        write_capacity = 75
```

We found that unless we tuned the `max_parallel` to play nice with the read/write values Vault itself would not make an effort to throttle requests and instead just send them to dynamodb immediately as soon as they were received. 

Because DynamoDB's capacity units aren't a 1:1 map with requests (depends on request size and operation) this can get a bit tricky. My guess is that you'll have to tune things as we did in order to prevent Vault from spiking your DynamoDB provisioned capacity.

**Comment by aiwaniuk** [comment]
I guess read_capacity/write_capacity is only used for creating table, I didn't see any other usage of them in the vault source code. I have not set these vaules in config and provisioned table manually to 100/100. I was also trying to play with max_parallel, but I don't see any difference.

In my case I have consumed about:
- 5 units/second almost all the time
- 80 units/second during spikes

**Comment by MattSurabian** [comment]
Yes the `read_capacity` and `write_capacity` are only used at table creation time, but `max_parallel` is used at runtime. I'd expect if you set `max_parallel` to a low value during the spikes they would level out in some way. Unfortunately it's hard for me to say exactly how it should be set, I'm surprised if it's having no effect at all.

**Comment by aiwaniuk** [comment]
after setting disable_periodic_tidy=true on AWS EC2 backend this issue is not visible anymore

**Comment by mitchelldavis** [comment]
From what I can tell, this has to do with the amount of entries in the identity whitelist cache.  Whenever I would run [this](https://www.vaultproject.io/api/auth/aws/index.html#list-identity-whitelist-entries), the spike would show up at that time.  (Outside the hour interval everyone else was seeing.)  I wrote this script to cleanup ec2 instances that were no longer active:

```
#! /bin/bash

WHITELIST=$(vault list -format=json auth/aws-ec2/identity-whitelist | jq -r '.[]')

INSTANCES=$(aws ec2 describe-instances)
INSTANCE_LIST=$(echo $INSTANCES | jq -r '.Reservations[].Instances[] | .InstanceId')

for item in $WHITELIST; do
	if echo $INSTANCE_LIST | grep -w $item > /dev/null; then
		echo "Skipping..."
	else
		echo "Delete $item"
		curl -X DELETE -H "X-VAULT-TOKEN: $VAULT_TOKEN" $VAULT_ADDR/v1/auth/aws-ec2/identity-whitelist/$item
	fi
done
```

to clean up old entries for instances that weren't around anymore.  Now, the spike is back at a manageable level.

This just happened a few hours ago, so I haven't been able to observe for an extended period of time and this doesn't explain why we had so many entries that were not being cleaned from the cache so the investigation continues, but I do have another clue:

> For us, it's not just the read capacity that spikes, the write does as well.  

Does this mean that the `expiration_time` is being updated every hour as well?  That's a hint on why we had 2000+ entries still in the whitelist cache, but I can't say for sure yet.

**Comment by jefferai** [comment]
You may want to consider switching to the IAM authentication type, as it doesn't require whitelists or complicated reauthentication logic.

**Comment by vishalnayak** [comment]
Issues that are not reproducible and/or not had any interaction for a long time are stale issues. Sometimes even the valid issues remain stale lacking traction either by the maintainers or the community. In order to provide faster responses and better engagement with the community, we strive to keep the issue tracker clean and the issue count low. In this regard, our current policy is to close stale issues after 30 days. Closed issues will still be indexed and available for future viewers. If users feel that the issue is still relevant but is wrongly closed, we encourage reopening them.
   
Please refer to our [contributing guidelines](https://github.com/hashicorp/vault/blob/main/CONTRIBUTING.md) for details on issue lifecycle.
