### ISSUE TITLE
Feature Request: Vagrantfile

### ISSUE THREAD

**Issue by rurounijones** [hashicorp/vault#4130]
**Feature Request:**

Add a Vagrantfile for Vault so that people can easily get started with it.

I have recently started playing with the Hashistack and the Vagrantfile for Nomad made getting up and running with nomad  for experimentation SO easy. I now want to experiment with Vault.

**Expected Behavior:**
I should be able to download an official Vagrant file then ```vagrant up``` and have a sealed Vault installation ready for me to play with.

**Actual Behavior:**
There is no vagrant file.

**Steps to Reproduce:**

1, Go to Website and Repo
2, Search in vain for a Vagrantfile.
3. Cry and raise a Github issue since I now actually have to spend setting up a VM with vault on it. 

(Note, I know that vault is a LOT less work to setup but when every other hashistack component I have tried so far has a simple "vagrant up" getting started step not having one here is jarring)

**References:**

* Nomad has a Vagrantfile: https://github.com/hashicorp/nomad/tree/master/demo/vagrant 
* Consul has a Vagrantfile: https://github.com/hashicorp/consul/tree/master/demo/vagrant-cluster
* Vault has No Vagrantfile: :sob:

**Comment by sidewinder12s** [comment]
If you want to play with Vault, you literally download the exe for the platform your on and run `vault server -dev` and your ready to go.

While that won't help if you want to test HA, you need an HA backend anyways to play with HA Vault.

**Comment by rurounijones** [comment]
It works for messing around on your local desktop with an ephemeral vault installation. But if you are, for example, testing out your application on Nomad+Vault using https://github.com/hashicorp/nomad/blob/master/demo/vagrant/Vagrantfile then having a non-ephemeral auto-starting vault available as another VagrantFile makes it easier to test the two together.

**Comment by vishalnayak** [comment]
Issues that are not reproducible and/or not had any interaction for a long time are stale issues. Sometimes even the valid issues remain stale lacking traction either by the maintainers or the community. In order to provide faster responses and better engagement with the community, we strive to keep the issue tracker clean and the issue count low. In this regard, our current policy is to close stale issues after 30 days. Closed issues will still be indexed and available for future viewers. If users feel that the issue is still relevant but is wrongly closed, we encourage reopening them.
   
Please refer to our [contributing guidelines](https://github.com/hashicorp/vault/blob/main/CONTRIBUTING.md) for details on issue lifecycle.
