### ISSUE TITLE
Documentation issue: AWS Handling lost client nonces

### ISSUE THREAD

**Issue by danieljamesscott** [hashicorp/vault#4133]
There is a bug in the documentation for AWS Handling lost client nonces:

https://www.vaultproject.io/docs/auth/aws.html#handling-lost-client-nonces

It states that to allow an instance to re-obtain its nonce, I need to delete the instance ID 

    This can be done via the auth/aws/identity-whitelist/<instance_id> endpoint.

But the path is actually

    auth/aws-ec2/identity-whitelist/<instance_id>

**aws-ec2**

**Comment by joelthompson** [comment]
Hi @danieljamesscott -- it's not actually a bug. All auth backends can be mounted at alternate paths, with a default path of `auth/<backend_type>`, and the docs all, by convention, show the default path. If users have a backend mounted at a different location they will need to modify the paths shown in the documentation to match the actual mount paths.

The aws auth backend is a bit unique. It used to be called `aws-ec2` and so by default was mounted at `auth/aws-ec2`. It was renamed last year to just `aws` and by default now gets mounted to `auth/aws`; however, existing mounts will stay mounted at `auth/aws-ec2` (and the old mount type name of `aws-ec2` was also preserved and will still mount at `auth/aws-ec2` by default for backwards compatibility).

The docs always correspond to the latest version of the code, which is why they show the mount path as `auth/aws` by default, but it just depends on where you have it mounted.

**Comment by vishalnayak** [comment]
Joel is right! Closing.

**Comment by james-lawrence** [comment]
documentation is still incorrect, a cursory reading doesn't make it clear that the endpoints are variable. leading to the confusion that generated this issue.

**Comment by joelthompson** [comment]
Hey @james-lawrence, could you suggest changes to the documentation that you think would help make it clearer that the mount point can be varied?
