### ISSUE TITLE
hardening: use PR_SET_DUMPABLE on Linux?

### ISSUE THREAD

**Issue by slingamn** [hashicorp/vault#4150]
**Feature Request:**

On Linux, `prctl(PR_SET_DUMPABLE, 0)` can be used to prevent the creation of core dumps under certain circumstances. I believe that it doesn't change the overall threat model, in which an attacker with root privileges (more precisely, `CAP_SYS_PTRACE`) can override this restriction. But it may at least obviate the current recommendation in the [production hardening guide](https://www.vaultproject.io/guides/operations/production.html) to disallow dumps via `RLIMIT_CORE`.

**References:**

* https://linux.die.net/man/2/prctl
* https://linux.die.net/man/2/ptrace
* https://linux.die.net/man/2/process_vm_readv

**Comment by vishalnayak** [comment]
Issues that are not reproducible and/or not had any interaction for a long time are stale issues. Sometimes even the valid issues remain stale lacking traction either by the maintainers or the community. In order to provide faster responses and better engagement with the community, we strive to keep the issue tracker clean and the issue count low. In this regard, our current policy is to close stale issues after 30 days. Closed issues will still be indexed and available for future viewers. If users feel that the issue is still relevant but is wrongly closed, we encourage reopening them.
   
Please refer to our [contributing guidelines](https://github.com/hashicorp/vault/blob/main/CONTRIBUTING.md) for details on issue lifecycle.
