### ISSUE TITLE
Make zookeeper storage more robust in containerized environments (2/2)

### ISSUE THREAD

**Issue by scoof** [hashicorp/vault#4161]
Make zookeeper storage more robust in containerized environments (1/2)

**Feature Request:**

**Environment:**

* Vault Version: Vault v0.9.1 ('87b6919dea55da61d7cd444b2442cabb8ede8ab1')
* Operating System/Architecture: Alpine Linux 3.6

**Vault Config File:**
{"storage": {"zookeeper": {"path": "vault/", "address": "zookeeper-0:2181,zookeeper-1:2181,zookeeper-2:2181"}}, "default_lease_ttl": "168h", "max_lease_ttl": "720h", "disable_mlock": true, "api_addr": "https://vault:8200", "listener": {"tcp": {"address": "0.0.0.0:8200", "tls_disable": 1}}, "telemetry": { "statsd_address": "127.0.0.1:8125", "disable_hostname": true }}

**Expected Behavior:**
Vault should discover when zk backends change their IP. I.e. do a new DNS lookup on reconnect.

**Actual Behavior:**
If the full zk ensemble restarts and is assigned new IP addresses by OpenShift, vault goes down, since it can't connect to the old IPs.

**Steps to Reproduce:**
Configure vault with at least one zk backend. Restart that zk backend with a new IP and change DNS record to reflect this.

**Important Factoids:**
Since this is running in OpenShift with a stateful set of zookeeper storage, IP addresses of the zk backends are not known until the containers are running. The nodes may change IP after being restarted.
This seems to require changes in vendor/samuel/go-zookeeper, since the current implementation of DNSHostProvider caches first DNS lookup.

**Comment by scoof** [comment]
Related issue: https://github.com/samuel/go-zookeeper/issues/157

**Comment by ajay-aggarwal** [comment]
We are seeing the same issue.

**Comment by sholavanalli** [comment]
Please fix this. We're seeing this as well. Work arounds until its fixed?

**Comment by jefferai** [comment]
I suggest you contact the original author or the go-zookeeper maintainers. We do not support this storage type.

**Comment by scoof** [comment]
One (platform specific) workaround for OpenShift is to create each zk node in the ensemble as a service, and point to the service IP, which is fixed across restarts.

**Comment by vishalnayak** [comment]
Issues that are not reproducible and/or not had any interaction for a long time are stale issues. Sometimes even the valid issues remain stale lacking traction either by the maintainers or the community. In order to provide faster responses and better engagement with the community, we strive to keep the issue tracker clean and the issue count low. In this regard, our current policy is to close stale issues after 30 days. Closed issues will still be indexed and available for future viewers. If users feel that the issue is still relevant but is wrongly closed, we encourage reopening them.
   
Please refer to our [contributing guidelines](https://github.com/hashicorp/vault/blob/main/CONTRIBUTING.md) for details on issue lifecycle.
