### ISSUE TITLE
Create backup pgp-encrypted unseal keys at init

### ISSUE THREAD

**Issue by jhmartin** [hashicorp/vault#4166]
**Feature Request:**
`/sys/init` should have the same `backup` capability for PGP-encrypted unseal keys as `/sys/rekey/init`.  This way both newly initialized and subsequently rekeyed Vault's can store a backup copy of their PGP encrypted unseal keys at `core/unseal-keys-backup` on their storage backend.

**References:**
https://www.vaultproject.io/api/system/init.html
https://www.vaultproject.io/api/system/rekey.html#backup

**Comment by lenaing** [comment]
Just got bitten by this :)
It would be nice indeed to have a backup on init and not only on the subsequent rekeking.

**Comment by vishalnayak** [comment]
Issues that are not reproducible and/or not had any interaction for a long time are stale issues. Sometimes even the valid issues remain stale lacking traction either by the maintainers or the community. In order to provide faster responses and better engagement with the community, we strive to keep the issue tracker clean and the issue count low. In this regard, our current policy is to close stale issues after 30 days. Closed issues will still be indexed and available for future viewers. If users feel that the issue is still relevant but is wrongly closed, we encourage reopening them.
   
Please refer to our [contributing guidelines](https://github.com/hashicorp/vault/blob/main/CONTRIBUTING.md) for details on issue lifecycle.
