### ISSUE TITLE
scp passthrough/helper command for ssh otp

### ISSUE THREAD

**Issue by heretogo** [hashicorp/vault#4217]
**Feature Request:**

A vault scp command would be useful in addition to vault ssh. Regular scp requires manually generating a OTP.

**Comment by kwakiutlCS** [comment]
not exactly what you ask, but one can workaround to copy files without manually generating the OTP
tar czf - folder | vault ssh -role role_name -mode otp user@host tar xzf -

**Comment by vishalnayak** [comment]
Issues that are not reproducible and/or not had any interaction for a long time are stale issues. Sometimes even the valid issues remain stale lacking traction either by the maintainers or the community. In order to provide faster responses and better engagement with the community, we strive to keep the issue tracker clean and the issue count low. In this regard, our current policy is to close stale issues after 30 days. Closed issues will still be indexed and available for future viewers. If users feel that the issue is still relevant but is wrongly closed, we encourage reopening them.
   
Please refer to our [contributing guidelines](https://github.com/hashicorp/vault/blob/main/CONTRIBUTING.md) for details on issue lifecycle.
