### ISSUE TITLE
Shared File Backend(NFS) -Clarification

### ISSUE THREAD

**Issue by nandhusriram** [hashicorp/vault#4236]
I am running multiple vault  instances on OpenShift with filebackend shared(NFS like concept) across those vault instances , is that a good option/alternate for HA . I do understand documentation says filebackend does need consul for HA. I am looking for any input/advice  whether  running shared file storage across vault instances is something an acceptable option?

Thanks

**Comment by joelthompson** [comment]
That's not supported nor would it be a good idea. The reason is that the Vault servers need to ensure only single node is the leader, and the file system storage backend doesn't have leader election logic (which is why using something like Consul for HA is necessary). Shared storage is necessary but not sufficient.

**Comment by jefferai** [comment]
As Joel said, NFS can satisfy the shared storage part but you must then specify separate ha storage for the locking; NFS locking is not sufficient/compatible.
