### ISSUE TITLE
Feature Request: OpenPGP HTTP keyserver secret backend

### ISSUE THREAD

**Issue by viralpoetry** [hashicorp/vault#4280]
**Feature Request:**

Hi, it would be big enhancement if Vault could provide OpenPGP HTTP keyserver backend. Vault authn mechanism could be leveraged for key authenticity.

Is something like this planned in the near future?

Thank you for great work!

**References:**
[https://tools.ietf.org/html/draft-shaw-openpgp-hkp-00](https://tools.ietf.org/html/draft-shaw-openpgp-hkp-00)
[https://github.com/hockeypuck/hkp](https://github.com/hockeypuck/hkp)

**Comment by vishalnayak** [comment]
Issues that are not reproducible and/or not had any interaction for a long time are stale issues. Sometimes even the valid issues remain stale lacking traction either by the maintainers or the community. In order to provide faster responses and better engagement with the community, we strive to keep the issue tracker clean and the issue count low. In this regard, our current policy is to close stale issues after 30 days. Closed issues will still be indexed and available for future viewers. If users feel that the issue is still relevant but is wrongly closed, we encourage reopening them.
   
Please refer to our [contributing guidelines](https://github.com/hashicorp/vault/blob/main/CONTRIBUTING.md) for details on issue lifecycle.
