### ISSUE TITLE
Unable to view raw telemetry on Windows

### ISSUE THREAD

**Issue by ofek** [hashicorp/vault#4311]
On Windows when viewing raw telemetry data, sending the required `BREAK` signal kills the Vault process (and doesn't output any telemetry).

```
vault server -dev
...
==> Vault shutdown triggered
2018/04/08 23:01:56.233952 [INFO ] core: pre-seal teardown starting
2018/04/08 23:01:56.237952 [INFO ] core: cluster listeners not running
2018/04/08 23:01:56.241953 [INFO ] rollback: stopping rollback manager
2018/04/08 23:01:56.245953 [INFO ] core: pre-seal teardown complete
2018/04/08 23:01:56.249454 [INFO ] core: vault is sealed
```

Is the signal improperly handled? Otherwise if this is expected, is there another way to view the raw data?

**Comment by ofek** [comment]
@jefferai @vishalnayak Can you please take a look at this?

**Comment by ofek** [comment]
Any update?

**Comment by vishalnayak** [comment]
Let us know if this is still an issue.

**Comment by vishalnayak** [comment]
Issues that are not reproducible and/or not had any interaction for a long time are stale issues. Sometimes even the valid issues remain stale lacking traction either by the maintainers or the community. In order to provide faster responses and better engagement with the community, we strive to keep the issue tracker clean and the issue count low. In this regard, our current policy is to close stale issues after 30 days. Closed issues will still be indexed and available for future viewers. If users feel that the issue is still relevant but is wrongly closed, we encourage reopening them.
   
Please refer to our [contributing guidelines](https://github.com/hashicorp/vault/blob/main/CONTRIBUTING.md) for details on issue lifecycle.
