### ISSUE TITLE
Build Fails on RHEL 6

### ISSUE THREAD

**Issue by swsnider** [hashicorp/vault#432]
When building using the distro's golang (go version go1.4.2 linux/amd64), the build fails with message:

```
# github.com/hashicorp/vault/builtin/logical/pki
builtin/logical/pki/cert_util.go:188: undefined: elliptic.P224
```

This is because RHEL/Fedora remove certain curves from crypto packages because of patent encumbrances (see https://github.com/coreos/etcd-ca/issues/22, for example). Please consider removing this curve (p256 is still available).

**Comment by armon** [comment]
Tagged as a bug/enhancement. What a world when mathematical curves are patent encumbered.

**Comment by mr-savari** [comment]
i have the same issue !!

**Comment by jefferai** [comment]
The referenced etcd bug states that they don't think it should be on them to remove functionality useful to many because one distribution chooses to patch it out. I agree with this stance; we build against official released Go. You can either build Go yourself on RHEL and then build Vault with it, or you can use our signed binary releases which are built against official Go releases.
