### ISSUE TITLE
vault github repo does not post source code zips

### ISSUE THREAD

**Issue by migs** [hashicorp/vault#4342]
Hi,

Would it be possible for the vault github repo to start using release tags? For example, https://github.com/hashicorp/terraform/releases uses release tags which is great for our concourse driven automation.

**Comment by jefferai** [comment]
Does something about https://github.com/hashicorp/vault/releases not work for you? I'm not really following the issue.

**Comment by migs** [comment]
I'm using this to pick up github releases in Concourse: https://github.com/concourse/github-release-resource. This will automatically scan for new tagged releases in a given github repository. Once it finds a new version, it can trigger other elements of our concourse pipelines.

This works fine for every other github release I've thrown at it from other organisations, but unfortunately the only hashicorp project that uses releases is terraform.

Some other examples of github repos that use releases instead of just tags:

https://github.com/cloudfoundry/bosh-bootloader/releases
https://github.com/starkandwayne/safe/releases

etc

**Comment by jefferai** [comment]
So your actual ask is not for release tags, which we already have, but for us to...post source code zips? I still don't understand what you actually need here.

**Comment by migs** [comment]
I apologise, I'm probably confusing github terminology. I'm referring to the differences between releases and tags. It looks like that hashicorp is just applying tags, not releases (with the exception of the terraform repo, which uses full releases in addition to tags)

This might help? https://blog.github.com/2013-07-02-release-your-software/

**Comment by jefferai** [comment]
We don't currently have plans to start using those. It also seems from the docs like the software you're referencing ought to be able to handle tags. Given that GitHub will happily produce a zip file of any tag or branch you ask it to, if that software doesn't currently support normal tags it seems like a worthwhile enhancement.

**Comment by patrick-motard** [comment]
@jefferai It would be nice if there were compiled binaries. I needed the vault binary on a server. I wanted provisioning the server to be automatic. I wrote a [silly script](https://github.com/patrick-motard/greenscripts/blob/master/lib/hashicorp) that can download a given hashicorp product of a given version. It pulls the zip from your main website. Works pretty well. Only downside is that there's no way to search for valid versions. Pretty much have to navigate to the website and view the version in the link anyways. 

So i thought it'd be pretty neat if instead of using the website, I just listed the releases on your repos via the [github api](https://developer.github.com/v3/repos/releases/). And since you don't do releases, nothing is returned from the call. I suppose I could try to figure out if the Github API supports getting a repos tags and listing/validating in the scrip that way. 

Either way, it would be nice if:

1. OS specific package managers had packaged releases of hashicorp projects. I'm thinking specifically of `apt`, `pacman`, `yum`, `choco`, etc.

2. Releases were published in github so that the above "ask" could be a bit easier to do.


Just my 2 cents.

**Comment by sethvargo** [comment]
The releases service (releases.hashicorp.com) has an API which you can query for versions (discouraged, but available). https://github.com/hashicorp/terraform/issues/9803#issuecomment-257903082

**Comment by jefferai** [comment]
You can get tags: https://developer.github.com/v3/git/tags/

These can be parsed in the same way as releases, as they would have the same values.

**Comment by catsby** [comment]
Hello - I'm going to close this issue for now; we tag and push source to GitHub and provide release binaries on https://releases.hashicorp.com

Cheers!
