### ISSUE TITLE
Audit log issue

### ISSUE THREAD

**Issue by aprousas** [hashicorp/vault#4406]
**Environment:**

* Vault Version: 0.9.5 and 0.10.0
* Operating System/Architecture: Mac OS X

**Vault Config File:**

```hcl
backend "file" {
  path = "storage"
}

listener "tcp" {
  address = "127.0.0.1:8200"
  tls_disable = "true"
}

disable_mlock = true
```

**Expected Behavior:**
According to the official documentation (https://www.vaultproject.io/docs/audit/index.html) the audit log contains every interaction with Vault.

**Actual Behavior:**
There are several interactions with Vault that are not included in audit log (neither file nor syslog).

For example, **unsealing** Vault (by command line or by using the HTTP API) is not included in audit log. The same happens when I check Vault's **status**. However, when I seal the Vault the action is included in the audit log.

Has anyone ever faced the same issue? Is there a workaround/fix for that? 

Thanks in advance.

**Comment by jefferai** [comment]
Unsealing can't be included in the audit log because Vault doesn't have access to the audit log information until it's unsealed. It's kinda chicken-and-egg.

Status is not included because it's an unauthenticated action.

I'll update the text to make it clear that every _authenticated_ action is audited.

**Comment by aprousas** [comment]
Thanks @jefferai !
