### ISSUE TITLE
High Availability Questions

### ISSUE THREAD

**Issue by ekristen** [hashicorp/vault#444]
I have 3 consul servers using a single DNS entry for "round robin" support consul.private.io

I have 3 vault servers using a single DNS entry for "round robin" support vault.private.io.

What should `Advertise Address` be? When the first vault server comes online the first server's IP address seems to get picked as the Advertise Address, when I startup the second 2, they sometimes get their own ip addresses as the Advertise Address, sometimes they get the first server's ip. Usually a subsequent restart gets the the "leaders" IP. 

When should vault re-elect a leader and shouldn't it replicate the new advertise address to the other standbys? 

What ACLs on Consul does Vault need? I thought perhaps that maybe Consul ACLs are causing problems. 

Also as it stands right now, if I restart the leader, the vault seals which doesn't make sense either.

Thanks.

**Comment by ekristen** [comment]
@armon if you have a chance to answer these, it would be great.

**Comment by dkaffee92** [comment]
@ekristen 
From looking at the code if you don't supply an advertise address it should default to `0.0.0.0`, 
https://github.com/hashicorp/vault/blob/27728075478ec48070fb9b0f1670b6e108cbeedb/command/server.go#L287-L350

regarding ACLs for Consul, what I use and it works is 
```
key "vault/" {
    policy = "write"
}
```

**Comment by ekristen** [comment]
@dkaffee92 are you using a high availability setup?

**Comment by ekristen** [comment]
I found one problem, I wasn't using the local consul agent, that has been fixed. However if I take down the leader all I get is a `dial tcp connection refused` error message.

**Comment by ekristen** [comment]
AFAIK HA leader election is completely broken, but I'd like to hear from the main project owners first before I try and figure out why.

**Comment by armon** [comment]
@ekristen We run our Vaults in an HA configuration on Consul serving production traffic, so I assure you its not "completely broken".

The advertise address is a heuristic at best, it tries to guess the an addressable IP or hostname for that node. With Consul, it asks the agent for its advertise address and uses that. This would explain why you were getting strange IPs, since you were not using a local agent.

Vault needs at least write level permission to whatever path you use. It defaults to the `vault/` prefix, but you can change that to whatever you'd like.

If you restart a Vault it always seals, with or without HA mode. This is because it no longer has the encryption keys in memory. The unseal process is required so that it can restore the encryption keys. Again, this is by design, so that those keys are not persisted or transmitted over the network.

**Comment by ekristen** [comment]
@armon that makes sense. However, I have 3 servers, all of which have an ACL with full write access to `vault/` when I shutdown 1 of the 3 servers, the other 2 continue to forward to the original server. The other two never elect a new leader ...

I've manually set the advertise_addr on all 3 to each local IP and port. 

How is a leader suppose to be selected?

**Comment by armon** [comment]
@ekristen They probably are doing a leader election, but the "advertise_addr" on each node must be for themselves. You have
[{Node 1, Advertise Addr1}, {Node 2, Addr 2}, ...]

Currently you have Addr1 = Addr2 = AddrN, such that no matter which node is the leader they forward to the same address. The addresses must be corresponding to the node itself, such that when the leader election happens it forwards to that node.

**Comment by ekristen** [comment]
I have 3 servers, they all pull their own IP from the local running consul agent (which happens to be in server mode) All three have the advertise address as their own IP. 

Server1
```
backend "consul" {
  address = "10.10.xxxx.30:8500"
  datacenter = "west"
  path = "occultare"
  token = "c592370c-xxxx-xxxx-xxxx-81ca054exxxx"
}

listener "tcp" {
  address = "10.10.xxx.30:8200"
  tls_cert_file = "/config/server.pem"
  tls_key_file = "/config/server-key.pem"
}
```
```
         Log Level: info
             Mlock: supported: true, enabled: true
           Backend: consul (HA available)
 Advertise Address: https://10.10.xxx.30:8200
        Listener 1: tcp (addr: "10.10.xxx.30:8200", tls: "enabled")
```

Server2
```
backend "consul" {
  address = "10.10.xxxx.40:8500"
  datacenter = "west"
  path = "occultare"
  token = "c592370c-xxxx-xxxx-xxxx-81ca054exxxx"
}

listener "tcp" {
  address = "10.10.xxx.40:8200"
  tls_cert_file = "/config/server.pem"
  tls_key_file = "/config/server-key.pem"
}
```
```
         Log Level: info
             Mlock: supported: true, enabled: true
           Backend: consul (HA available)
 Advertise Address: https://10.10.xxx.40:8200
        Listener 1: tcp (addr: "10.10.xxx.40:8200", tls: "enabled")
```

Server3
```
backend "consul" {
  address = "10.10.xxxx.50:8500"
  datacenter = "west"
  path = "occultare"
  token = "c592370c-xxxx-xxxx-xxxx-81ca054exxxx"
}

listener "tcp" {
  address = "10.10.xxx.50:8200"
  tls_cert_file = "/config/server.pem"
  tls_key_file = "/config/server-key.pem"
}
```
```
         Log Level: info
             Mlock: supported: true, enabled: true
           Backend: consul (HA available)
 Advertise Address: https://10.10.xxx.50:8200
        Listener 1: tcp (addr: "10.10.xxx.50:8200", tls: "enabled")
```

**Comment by armon** [comment]
Can you run `vault status`? This all looks good, things should be working.

**Comment by ekristen** [comment]
Question: Do the vault instances need to be able to communicate with each other over port 8200 or do they do all election via consul k/v storage?

Here is the requested output.

```
> VAULT_ADDR="https://10.10.xxx.32:8200" vault status
Sealed: false
Key Shares: 5
Key Threshold: 3
Unseal Progress: 0

High-Availability Enabled: true
	Mode: active
	Leader: https://10.10.xxx.32:8200

> VAULT_ADDR="https://10.10.xxx.97:8200" vault status -tls-skip-verify                                       
Sealed: true
Key Shares: 5
Key Threshold: 3
Unseal Progress: 0

High-Availability Enabled: true
	Mode: sealed

> VAULT_ADDR="https://10.10.xxx.156:8200" vault status -tls-skip-verify
Sealed: true
Key Shares: 5
Key Threshold: 3
Unseal Progress: 0

High-Availability Enabled: true
	Mode: sealed
```

**Comment by armon** [comment]
@ekristen It looks like the issue is that the other instances are sealed. The instances must be unsealed to act as a standby. Otherwise, should they get elected leader, they would not have the encryption keys to be able to service any requests.

The interaction is all over Consul K/V so there is no need for them to communicate over 8200, but of course clients must be able to reach them.

**Comment by ekristen** [comment]
@armon thanks! It works now. I think the problem is the documentation isn't very clear.

Under `Basic Concepts` https://www.vaultproject.io/docs/concepts/ha.html It basically states that HA is available automatically when using a backend that supports it. 

I just re-read the documentation and under `Internals` the last paragraph is the only place it mentions needing the other servers to be unsealed to act as standbys, https://www.vaultproject.io/docs/internals/high-availability.html

Thanks for helping me solve this problem! Looking at writing my own backends for some internal uses! Glad to finally have this working. Thank you!

**Comment by armon** [comment]
Our pleasure. Glad its working.

**Comment by gvenka008c** [comment]
@armon Sorry for posting it in the closed issue, but got an quick query

I have Vault + Consul installed on the same VM's on all the 3 machines. I have given the IP address in backend configuration (address = "xx.xxx.xxx.xx:8500"). Should this just be "127.0.0.1:8500" instead of the IP address? Also do we need to specify advertise_addr?

```
backend "consul" {
  address = "xx.xxx.xxx.xx:8500"
  path = "vault"
  advertise_addr = "http://xx.xxx.xxx.xx:8200"
}
```

Today one of the Consul server went down and Vault was not able to talk to Consul. Any suggested workaround? Please suggest. Thanks

Thanks,
Govind

**Comment by narayan8291** [comment]
@gvenka008c : I am using zookeeper as the backend and my config files looks similar to yours,
backend "zookeeper" {
  address = "a.b.c.d:xxxx"
  path = "vault"
  advertise_addr = "https://127.0.0.1:8200"
}
I am using the loopback address.
