### ISSUE TITLE
Telemetry tags

### ISSUE THREAD

**Issue by ofek** [hashicorp/vault#4461]
In the example output here https://www.vaultproject.io/docs/internals/telemetry.html there are things like `vault.7f320e57f9fe.runtime.sys_bytes` where `7f320e57f9fe` I assume is the cluster name.

For parsing purposes, does every `vault.` metric root have the possibility to be followed by a tag? The only documentation of this is for `database.` names here https://www.vaultproject.io/docs/internals/telemetry.html#secrets-engines-metrics.

**Comment by vishalnayak** [comment]
Issues that are not reproducible and/or not had any interaction for a long time are stale issues. Sometimes even the valid issues remain stale lacking traction either by the maintainers or the community. In order to provide faster responses and better engagement with the community, we strive to keep the issue tracker clean and the issue count low. In this regard, our current policy is to close stale issues after 30 days. Closed issues will still be indexed and available for future viewers. If users feel that the issue is still relevant but is wrongly closed, we encourage reopening them.
   
Please refer to our [contributing guidelines](https://github.com/hashicorp/vault/blob/main/CONTRIBUTING.md) for details on issue lifecycle.

**Comment by hsimon-hashicorp** [comment]
Hi folks! Is this still an issue in newer versions of Vault? Please let me know so I can bubble it up accordingly. Thanks!

**Comment by raskchanky** [comment]
Since it's been awhile with no response, I'm going to close this issue. Please reopen if there's more to add here.
