### ISSUE TITLE
Does api_addr and cluster_addr configuration options exist?

### ISSUE THREAD

**Issue by balupton** [hashicorp/vault#4482]
**Environment:**

* Vault Version: `Vault v0.10.1 ('756fdc4587350daf1c65b93647b2cc31a6f119cd')`
* Operating System/Architecture: `Linux par1_origin_0 4.14.33-mainline-rev1 #1 SMP Sun Apr 8 12:40:59 UTC 2018 aarch64 aarch64 aarch64 GNU/Linux`
 
**Vault Config File:**

```json
{
	"api_address": "10.10.36.185:8200",
	"cluster_address": "10.10.36.185:8201",
	"ui": true,
	"listener": {
		"tcp": {
			"address": "10.10.36.185:8200",
			"cluster_address": "10.10.36.185:8201",
			"tls_disable": 1
		}
	},
	"storage": {
		"consul": {}
	}
}
```

**Startup Log Output:**

```
Error loading configuration from /etc/systemd/system/vault.d: error loading "/etc/systemd/system/vault.d/vault.json": 2 errors occurred:

* invalid key "api_address" on line 2
* invalid key "cluster_address" on line 3
```

**Expected Behavior:**

This error should not have occurred, as the documentation says these keys exist https://www.vaultproject.io/docs/configuration/index.html#api_addr

**Actual Behavior:**

It seems those keys do not exist.

**Steps to Reproduce:**

1. Put the earlier json at `/etc/systemd/system/vault.d/vault.json`
2. Run: `vault server -config=/etc/systemd/system/vault.d`

**Comment by calvn** [comment]
Note that it should be `api_addr` and `cluster_addr` as specified in the docs instead.

**Comment by jefferai** [comment]
What do you mean?

**Comment by balupton** [comment]
The issue was mistake. I then provided some thoughts on what could have made my experience better. Of course, that is not to excuse my user error.

**Comment by jefferai** [comment]
I was looking on my phone before and only saw the text from the email. I didn't realize you'd modified the post.

> Why is there no consistency with the naming conventions? At root it is addr inside listener.tcp it is address.

They're different values that do very different things. They are different _on purpose_ to prevent confusion, as otherwise if they were the same and someone said `cluster_address` we wouldn't know which directive they're talking about.

> https://www.vaultproject.io/docs/configuration/listener/tcp.html uses /etc/certs with key and crt, and is the only one to use tls_cert_file, tls_key_file, tls_ca_file instead of cert_file, key_file, ca_file,

It could read both, but nobody has ever asked for this. It'd be an easy PR for someone motivated.

> Why are the root fields necessary when the listener.tcp fields exist? What is the interaction between these two?

The listener fields control the address(es) and port(s) that Vault listens on and is a TCP address. The ones outside control the values that Vault advertises to other nodes and/or clients, which is often the same as the listener address/port (but as a full URI) but in many cases isn't, e.g. to avoid the need for IP SANs or to direct traffic through a LB.
