### ISSUE TITLE
Allow global read on ssh/config/ca

### ISSUE THREAD

**Issue by bluecmd** [hashicorp/vault#4517]
* Vault Version: `Vault v0.10.1 ('756fdc4587350daf1c65b93647b2cc31a6f119cd')`
* Operating System/Architecture: `x86_64 Linux`

```text
$ vault read ssh/config/ca
Error reading ssh/config/ca: Error making API request.

URL: GET https://xxxx/v1/ssh/config/ca
Code: 403. Errors:

* permission denied

$ vault read ca-pki/cert/ca
Key                Value
---                -----
certificate        -----BEGIN CERTIFICATE-----
....
-----END CERTIFICATE-----
revocation_time    0
```

**Expected Behavior:**
SSH and PKI should behave similarly.

**Actual Behavior:**
Even though I have no explicit `read` grants I'm allowed to read out certificates from the PKI backend, but not the SSH backend.

**Steps to Reproduce:**
* Create a PKI backend
* Create a SSH backend
* Try to read the PKI's CA, it will succeed
* Try to read the SSH's public key, it will fail

It was late at night when I did this so I might have missed something, but I thought it would be worth doing a bug report on.

**Comment by jefferai** [comment]
IIRC the difference is that X509 certs can have the address to fetch the signing CA cert encoded in the certificate so there is an expectation of availability from any given verifier, Meanwhile since SSH certs use a different format there is no provision for the certificate itself to point to the signing CA, so you already need to distribute the CAs around.

**Comment by vishalnayak** [comment]
@bluecmd As mentioned by @rvandegrift the public key of the CA key pair can be accessed by https://www.vaultproject.io/api/secret/ssh/index.html#read-public-key-unauthenticated-.

**Comment by bluecmd** [comment]
Cool! Thanks, I must have missed that one!
