### ISSUE TITLE
[Api Request] Add a cache purging endpoint

### ISSUE THREAD

**Issue by uepoch** [hashicorp/vault#4577]
**Feature Request:**
It would be nice to have a simple endpoint in /sys/ to purge existent backend/policy cache without having to forcefully step-down a leader which cause brief interruption of service.

This can be expanded in maybe a with a list operation if that's ok to wrap function like Peek and Keys from the lru object in the Cache struct

**Comment by uepoch** [comment]
I've made a not that good attempt here https://github.com/criteo-forks/vault/pull/1 if you want to take a look and tell me what you think

**Comment by uepoch** [comment]
Sure !

It was not motivated by a particular bug in cache layer, we have two concerns:

Having the cluster down when a node dies is ok but we prefer to avoid it for small operations like ones that could require cache purge (i.e rollback of data)

Reading/Purging/Listing cache can be useful for troubleshooting purposes since it's not storable in a remote redis/memcache/... 

For 1) maybe it can/should be an improvement of the forced step-down and the election after it (have ideas on this, can it be discussed on the ML ?)

2) Is mostly motivated by operational safety, as a more specialized raw endpoint

**Comment by jefferai** [comment]
> Having the cluster down when a node dies is ok but we prefer to avoid it for small operations like ones that could require cache purge (i.e rollback of data)

Why would the cluster be down when a node dies? In an HA setup a standby should take over active duty.

Vault is a stateful application, you *cannot* just roll back the underlying storage on a live instance. It has nothing to do with the cache -- your patch is nowhere near sufficient in this regard because there is state all over. If you want to roll back data, you should really stop Vault, rollback, start Vault.

**Comment by uepoch** [comment]
This issue was biased by incomplete comprehension of in memory caching, closing it as it makes little sense as described now
