### ISSUE TITLE
Support nested LDAP groups that is not Active Directory

### ISSUE THREAD

**Issue by bluecmd** [hashicorp/vault#4597]
**Is your feature request related to a problem? Please describe.**
I have nested LDAP groups, i.e. the "member" attribute in a group points to either a user or another group (full DN).

**Describe the solution you'd like**
While the current documentation suggests using LDAP_MATCHING_RULE_IN_CHAIN (1.2.840.113556.1.4.1941) that is limited to Active Directory. I would like the equivalent of what [Apache](https://httpd.apache.org/docs/2.4/mod/mod_authnz_ldap.html#authldapgroupattributeisdn) does.

**Describe alternatives you've considered**
Right now I added the 10 or so groups manually, but ideally I would use the group they have in common.

**Explain any additional use-cases**
Have a clear directory structure is a security feature. Instead of adding the user to many many groups, adding them to a team group and having access policies derived from that is clearer and I would even claim it's industry best practice.

**Comment by uepoch** [comment]
Not on vault side, but if you need to do something like this with OpenLDAP family, you can use an overlay like dynlist http://www.zytrax.com/books/ldap/ch6/dynlist.html to create them server side

**Comment by bluecmd** [comment]
@uepoch I've been looking for something like that, that's excellent! I'll give it a try.

Still, to emphasize, this should probably still be supported by Vault as not everybody will be willing to patch their OpenLDAP :-).

**Comment by vishalnayak** [comment]
Issues that are not reproducible and/or not had any interaction for a long time are stale issues. Sometimes even the valid issues remain stale lacking traction either by the maintainers or the community. In order to provide faster responses and better engagement with the community, we strive to keep the issue tracker clean and the issue count low. In this regard, our current policy is to close stale issues after 30 days. Closed issues will still be indexed and available for future viewers. If users feel that the issue is still relevant but is wrongly closed, we encourage reopening them.
   
Please refer to our [contributing guidelines](https://github.com/hashicorp/vault/blob/main/CONTRIBUTING.md) for details on issue lifecycle.
