### ISSUE TITLE
MySQL Backend HA Support

### ISSUE THREAD

**Issue by michaeljs1990** [hashicorp/vault#4665]
**Use Case**: I want to use Vault in an environment that doesn't have a lot of resources available for instance I only have the ability to have a MySQL backend which already exists and have the room to run a few docker containers. However over time I would like to expand out this environment and make vault more resilient by adding HA and scaling out the MySQL backends to support failures.

**Solution**: MySQL has a built in GET_LOCK function that I believe can be used to implement the MySQL HA Backend. I would like to add support for this since I know MySQL is a community driven backend. This will likely be code that can be copy pasted between several other SQL servers as well.

**Alternatives**: I could start with MySQL and as I grow switch out to use Zookeeper for the backend however I don't think this is necessary as I have much more operational experience around MySQL and would like to continue using it as a backend.
 
I will do the work for this and have something I am working on locally right now but wanted to add this to ensure upstream would accept such a change and also find out if I have anything else I should consider when implementing this.

**Comment by jefferai** [comment]
Sure, we'd accept it, providing it is a reasonably sure locking solution (I just looked at the docs and it seems so). Also note that you can use separate storage and HA storage, where only the lock would then go into the HA storage, which doesn't remove the need for operationalizing another system but makes it much simpler (e.g. if something goes wrong with it, you can wipe its storage and start again because all that's there is the lock).

I'm going to close this as you said you're interested in implementing and it's not something on our roadmap...will watch for a PR!
