### ISSUE TITLE
Simple way to initialize Vault client, including token helper support

### ISSUE THREAD

**Issue by jgiles** [hashicorp/vault#4688]
**Is your feature request related to a problem? Please describe.**
Tools incorporating the Vault API client library don't have a clear, easy way to emulate the CLI's configuration setup - in particular, for getting the token to use, especially when a token-helper is configured.

This leads to issues like https://github.com/terraform-providers/terraform-provider-vault/issues/98 - the Terraform provider duplicates logic in the CLI for getting the token, but neglects to do the work for supporting token-helper:

https://github.com/terraform-providers/terraform-provider-vault/blob/93a146bf1e0cf065c8c1ce8061ecdcb25e168820/vault/provider.go#L154

The logic handling this in the CLI is here:
https://github.com/hashicorp/vault/blob/deb2904f46f951bd04505376238af6d5b3e25e63/command/base.go#L55

**Describe the solution you'd like**
A one-line, standard, documented call for creating an API client configured with all the environment variables, `~/.vault-token`, and `~/.vault`-configured token helper taken into account.

**Describe alternatives you've considered**
While non-obvious, this would seem to do the trick:

```
client, err := new(command.BaseCommand).Client()
```

But, the `command` package imports the world: https://github.com/hashicorp/vault/blob/deb2904f46f951bd04505376238af6d5b3e25e63/command/commands.go#L4
including packages that also import Vault (e.g. [the Azure plugin](https://github.com/hashicorp/vault-plugin-auth-azure/blob/4a00ec473112ccb88b2df03c56ebd0074313db3d/Gopkg.toml#L40) ), which wreaks havoc when you depend on `command` and try to use `dep`.

**Explain any additional use-cases**
Everyone writing a CLI tool based on the Vault client library should get all the standard client setup stuff "for free".

**Additional context**
A standard configure + create call would also allow clients to pick up support for Vault profiles if that were ever implemented (see https://github.com/hashicorp/vault/issues/2092#issuecomment-290554501)

**Comment by karysto** [comment]
Agreed, I'm having a similar issue where I am able to automate nearly the entire Vault setup within Go, and then I run into an error related to the `token-helper` isn't part of the client API... there should be a way to initialize a client with all necessary components out of the box

**Comment by jefferai** [comment]
While I'm amenable to the ask, I do want to point out that you're getting all the "standard client setup stuff for free"... token-helper is not a part of the Go API and has always been specific to the CLI.

But, it's also easily available and is in its own package: https://github.com/hashicorp/vault/tree/master/command/token

You shouldn't need all of the dependencies of command/

**Comment by sethvargo** [comment]
The API client and the CLI are functionally different things. The API client implements the various API methods in Go and manages TLS, etc. The CLI _consumes_ the API client and adds additional sugar, including token helpers. 

If you want those same sugars, you should either shell out to the Vault CLI or [call the token helper yourself](https://github.com/hashicorp/vault/blob/bd650812bcb91947ea202ace1c459009afb75513/command/base.go#L126-L142). 

I wouldn't want the Go API client library to use a token helper in most cases. I think Terraform is a bit of a special case, since it also behaves as a local CLI tool like Vault's CLI, so users might expect that behavior. However, for the vast majority of users, their "token helper" is the default "~/.vault-token". Thus, my recommendations would be (in order):

1. Pull the 30ish lines of code you need to instantiate a helper and parse a helper config from the command base I linked above

1. Just `ioutil.ReadFile("~/.vault-token")` instead of using an actual helper; yes, this will break for power users, but it solves the UX for 99.99% of users

1. Just document that Terraform consumes the API client library, thus it doesn't support token helpers.

**Comment by vishalnayak** [comment]
Issues that are not reproducible and/or not had any interaction for a long time are stale issues. Sometimes even the valid issues remain stale lacking traction either by the maintainers or the community. In order to provide faster responses and better engagement with the community, we strive to keep the issue tracker clean and the issue count low. In this regard, our current policy is to close stale issues after 30 days. Closed issues will still be indexed and available for future viewers. If users feel that the issue is still relevant but is wrongly closed, we encourage reopening them.
   
Please refer to our [contributing guidelines](https://github.com/hashicorp/vault/blob/main/CONTRIBUTING.md) for details on issue lifecycle.
