### ISSUE TITLE
PKI Backend does not allow certificates to live longer than the MaxLeaseDuration

### ISSUE THREAD

**Issue by armon** [hashicorp/vault#470]
This is to separate a few discussions happening in #451. The heart of the issue is that the PKI backend may generate a certificate that lives longer than the MaxLeaseDuration (30d). Unfortunately this means that the system will revoke that certificate after that time period, and add it to a CRL. This makes it difficult to use for long lived certificates.

One option is to increase the global MaxLeaseDuration, but it feels like a hack. The second option is that a "lease" is somewhat strange for a TLS certificate anyways since it cannot be renewed only revoked. The lease concept is already built into x509 in the form of expirations.

So another option may be to support certificate generate in a way that does not return a lease. The downside here is that automatic revocation can no longer be done.

A third option, and this starts getting strange, is to have a configurable MaxLeaseDuration per backend. This allows you to keep the leasing in tact, and just increase the PKI backend lease duration to say 90 days or a year. The risk here is that if there is a high rate of issue, Vault may start to manage a ton of leases which could overwhelm storage subsystems.

**Comment by jefferai** [comment]
I think the third option is overall the best (have the Vault core allow different max lease durations per backend). I wonder if some sort of user-displayed caution/warning when someone toggles this per-backend would be enough.

I feel like suggesting a whitelist of backends allowed to have this behavior is also very hacky, but may help in this situation to curb abuse so that people don't accidentally cause problems with their own installs.

**Comment by kgutwin** [comment]
I could imagine that, if the third option wasn't available, then smart admins would use the first option (which is easy to implement) but have separate Vault instances for different functions - for example, have a PKI vault separated from their AWS vault. 

@armon, you've mentioned the risk of overwhelming storage systems - can you comment on at what scale you would expect this to start being a problem? Are we talking about millions of leases or thousands? Have you seen this happen before?

**Comment by jefferai** [comment]
@armon Also FWIW it's so easy to build Go software and it's such an easy patch to remove the 30-day limit that I can easily imagine people simply going in and changing that one line. And then not telling anyone when asking for support.  :-)

Maybe better to get ahead of that?

**Comment by armon** [comment]
I think we want some combo of the first and third approach. The global default should be configurable with an enormous warning that it should not be done. The third approach lets you just modify the PKI backends or any others that may need it, which is more sane.

@kgutwin It depends a lot on the storage system. Consul stores keys in memory, so really depends on the deployment of that system. Still, it's not designed for handling millions of keys, so hundreds of thousands start to push things. MySQL can probably handle low millions comfortably. Then the issue is our lease GC isn't optimized for that many keys, so you will get Vault pressure.

Our initial design target was for a cluster of several thousand machines reading their secrets on start and renewing as necessary. This mean't that the total number of leases was in the low tens of thousands in the worst case.

Of course, over time we will improve Vault so that it can support ever more demanding work loads.

**Comment by theonewolf** [comment]
@armon 100k level of leases should be OK for my use cases for a long time.  Even your quoted tens of thousands is good enough for now.

I really like having the third option of configuring `maxLeaseDuration` per-backend, at least definitely tunable for PKI.

However, I'd accept a global tunable for short term progress :laughing: as in PR #470.

**Comment by theonewolf** [comment]
Oh and what you said is true @jefferai, except unsealing the Vault is non-trivial (not like building Go software!) :laughing: so I don't want to keep hacking on the codebase to get customized configuration.

**Comment by jefferai** [comment]
The merge in #469 seems to override the agreed-upon approach here, or am I missing something?

**Comment by theonewolf** [comment]
It's not per backend if that's what you mean?

I am happy with the global tunable though :smiley:

**Comment by jefferai** [comment]
There are two parts to this problem: the PKI backend, and Vault generally.

For now, the PKI backend ought to limit the max certificate lifetime to the global configured max lease lifetime for Vault. This requires exposing that information to the backends, so that's one task.

Eventually, all backends should be able to have a local configured max lease time. Either they should be able to be shorter than the global max lease time, or they should be able to be both shorter and longer but potentially require a token with sudo privs to allow a longer local lease time.

**Comment by theonewolf** [comment]
I'm fine with the simpler everyone adheres to the global maximum---but now in our new world the global maximum is tunable.  I think the weird exception for the sudo power is just that---a weird exception.  I'd like less of those to be able to reason about things more easily.

This is exactly the direction I wanted anyways basically.

**Comment by jefferai** [comment]
@theonewolf I'm glad that this fits your needs, however, I do think that per-backend capabilities are useful, especially for delegation: The superadmin in an organization can set the backend policies, but allow delegates to configure roles with lease duration default/max within what's allowed to that particular backend.

It's possible that you will only be able to reduce the maximum for a particular backend, not increase it, but it's not good UX if you make the global maximum high for one backend but then must go into every other backend and reduce it.

There is also still a need, even with the global value, of exposing this value to backends so that they can reason about it. This is part of the issue with the PKI backend now where it can create leases longer than what Vault allows, because there is no way for it to know what that allowed value is.

**Comment by jefferai** [comment]
A quick note: per-backend configurable TTLs are still on the radar, but this fix solves the immediate problem in this issue of being able to issue certificates longer than the maximum global lease time.
