### ISSUE TITLE
Policy LIST endpoints must end in slash

### ISSUE THREAD

**Issue by stampycode** [hashicorp/vault#4765]
This policy:

    "path "auth/approle/role" { capabilities = ["read", "list"] }"

Doesn't grant any permissions, but is accepted as valid policy.

    "path "auth/approle/role/" { capabilities = ["read", "list"] }"

Adding a trailing slash is required to allow LIST on the endpoint, even though adding the trailing slash on the actual request to the resource is optional.

e.g. I can request `LIST /v1/auth/approle/role` with or without the trailing slash, and both will fail with the first policy, but both will succeed with the second policy.

**Expected Resolution**
The first policy should be rejected for specifying LIST without a trailing slash or asterisk in the path.
OR
The first policy should allow LIST calls without a trailing slash, so there is no ambiguity.

_(It's also an edge case whether granting "auth/approle/role/" should even allow a request to "auto/approle/role" because the paths don't strictly match.)_

**Environment:**
* Vault Server Version: 0.10.1+prem
* Vault CLI Version : using HTTP API.

Thanks!

**Comment by calvn** [comment]
That's correct, adding a trailing slash on the ACL policy for list endpoint is required even though the actual request may or may not have the trailing slash. The reason for this behavior is that during request handling, if the operation is a LIST, then Vault will append a trailing slash (if missing) to the request path before the ACL gets parsed. The actual path for list operations will always contain a trailing slash as far as Vault is concerned which is why a trailing slash is required for ACLs.

**Comment by stampycode** [comment]
@jefferai forgive me, I had a read through that document before posting the ticket - there's no usage of the word "trailing" or "slash", and the only paragraph that vaguely looks relevant is this:

> When providing list capability, it is important to note that since listing always operates on a prefix, policies must operate on a prefix because Vault will sanitize request paths to be prefixes

Can we make this a bit easier to read?

Also I think a code change is still required to resolve the issue - the first policy is accepted, but is invalid.

Thanks!

**Comment by jefferai** [comment]
It's not invalid, it grants `read` on `auth/approle/role`.

The docs have been updatd to be more clear.
