### ISSUE TITLE
Cert Auth Backend determine which token to revoke

### ISSUE THREAD

**Issue by kaelumania** [hashicorp/vault#477]
When I change assigned policies for a certificate, then the user still has a valid token with the old assigned policies? How to force a renew of the token for the certificate?

**Comment by sethvargo** [comment]
Hi @kaelumania 

I think you will be able to determine this information from the audit log.

**Comment by kaelumania** [comment]
@sethvargo but from the audit log I have to manually find the entry, right? Further, when the user has a valid token and renews it every now and then. The token keeps its policies and is still allowed to renew itself even when I change the policies for a certificate. e.g.:
```ruby
certificate user_a policies: admin
token user_a policies: admin
...
change certificate user_a to policies: normal_user
...
token user_a policies: admin

> user is able to renew the token with the obsolete policy :(
```

**Comment by jefferai** [comment]
Hi @kaelumania ,

Starting with 0.5.2, tokens that are issued also issue acccessors, which by default are clear-text in audit logs. These accessors can be used to revoke tokens, in combination with the cleartext metadata written at token issue time to know which accessor belongs to which token (at least, roughly, although there may be more than one if a user has authenticated repeatedly).

Some of the credential backends will not allow renewals if the policies have changed since the token was revoked. The `cert` backend doesn't do that now, but I'll add that in for 0.6.

**Comment by kaelumania** [comment]
@jefferai that sounds awesome. I think it is the only reasonable behaviour to reject renewals when the policies of an certificate have changed.

**Comment by jefferai** [comment]
@kaelumania Yep. I should have that in today, if you want to build from `master`. Note that this won't *revoke* the token, it will just refuse to renew. If the token still has lifetime left it will still be valid.

**Comment by jefferai** [comment]
Also as of 0.5.2, if you don't disable binding in the cert backend, you could revoke the client certificate and upload the CRL to the cert backend, since the renew method (unless disabled) verifies that the subject key ID and authority key ID match the original requester of the token.

**Comment by kaelumania** [comment]
@jefferai that's exactly my expectation, we choose pretty low ttls to ensure that a token won't be valid much longer.
