### ISSUE TITLE
Inconsistency around authentication method behavior for users with no assigned policies

### ISSUE THREAD

**Issue by broamski** [hashicorp/vault#4775]
I'm curious if there is a stance on the expected behavior for all of the built-in authentication mechanisms when an authenticating user does not have any policies attached; either via the 3rd party identity provider or internal to vault. For example, the Okta and LDAP Auth Methods fail user authentication (even when presented with valid credentials) when no policies are presented during login as the result of querying external and internal group/policy mappings.

e.g. https://github.com/hashicorp/vault/blob/master/builtin/credential/okta/backend.go#L286-L294

Unlike the Okta or LDAP Auth Methods, the Userpass backend yields a successful login with the default policy attached when no policy mappings are attached to an authenticated user.

I would like some guidance from the Vault team around consistency with this behavior. Is an acceptable approach for me to add a configuration option to the Okta Auth Method allowing successful logins when no policy mappings are present? Or does this warrant further discussion?

My current use case is that my default policy gives my global user base a basic set of capabilities and they require no further policy mappings at this point and the remaining enforcement is accomplished via Sentinel.

Thanks!

**Comment by calvn** [comment]
That's correct, the userpass auth method adds the default policy when no policy mapping is attached to the user which is why not providing a policy mapping in that case is valid. For other auth methods such as Okta and LDAP, it does not perform this automatically. However, you can attach the default policy to the user/group so that a valid credential login results in a successful vault authentication.

**Comment by broamski** [comment]
Thanks @jefferai and @calvn!
