### ISSUE TITLE
Navigation in UI not working when list view is refreshed

### ISSUE THREAD

**Issue by feenst** [hashicorp/vault#4786]
**Describe the bug**
When navigating directly via pasting a URL into the address bar to a list view of a secret path in the Vault UI or refreshing the browser while in the list view, any folder names become mangled and can't be navigated.

**To Reproduce**
1. Open Vault UI in browser
2. Navigate to a listing of a secret path and refresh the browser or navigate directly to that path by pasting the URL into the address bar

**Expected behavior**
The folders should be navigable just as if I had navigated to that path from the root secret path.

**Environment:**
* Vault Server Version (retrieve with `vault status`): 0.10.1
* Vault CLI Version (retrieve with `vault version`): 0.8.1
* Server Operating System/Architecture:

Vault server configuration file(s):

**Additional context**

![navigation-lost-path](https://user-images.githubusercontent.com/997971/41558356-66a350da-72f5-11e8-932f-52ac5229efdb.gif)

**Comment by meirish** [comment]
Thanks for reporting this! I believe stripping the trailing slash was fixed in 0.10.2 via https://github.com/hashicorp/vault/pull/4668 - there is currently still an issue if you input a url that needs the trailing slash incorrectly. That will be fixed in https://github.com/hashicorp/vault/pull/4828 and is tracked in https://github.com/hashicorp/vault/issues/4819 so I'm going to close this one.
