### ISSUE TITLE
Feature Request: Reload local CA store on SIGHUP

### ISSUE THREAD

**Issue by stampycode** [hashicorp/vault#4928]
When I call NOHUP on the Vault service, it reloads the local TLS cert keyfile, so I can update the cert without restarting the service. Fantastic.
Unfortunately, if I modify the list of trusted CAs in the trusted OS CA cert store, I have to completely restart all Vault nodes for the changes to take effect.

In the event that a CA is breached or becomes untrusted (á la DigiNotar) we want to remove that CA trust from the store as soon as possible, so Vault reloading these trusted certs should happen on a NOHUP, just like when we update the local cert.
If the NOHUP can trigger this reload, updating the CA list can be an automated process, but if we have to restart the Vault nodes, we have to unseal each node manually, and raise maintenance alerts in advance.

It's also helpful for when we add a local CA for consul usage to the OS trusted CAs store, we have to restart all Vault nodes for the Consul CA to become trusted - we feel this should be doable just with a NOHUP.

Thanks!

**Comment by stampycode** [comment]
_nudge_

**Comment by SoMuchToGrok** [comment]
Are you sure it's not reloading the CA store on a SIGHUP? I've gone through hundreds of root CA rotations to date and haven't run into this problem.

What does your config file look like?

**Comment by stampycode** [comment]
@SoMuchToGrok - Sure no worries. So we're using Consul for service discovery, and for that to work the Vault has to trust the root CA cert our Consul service uses, which is a non-public cert; it's an internal CA. This means the CA cert isn't in the default operating system trusted CA list on the Vault servers - so we needed to add it.

The situation I outlined above about CA revocations also requires updates to the CA list.
The problem is that the operating system CA list updates are only ingested by Vault when you restart the Vault service - but if they were ingested on a NOHUP signal (like the private TLS key/cert files) then we would have a much easier time managing our list of trusted CAs.

Check out `/usr/local/share/ca-certificates` and `/usr/sbin/update-ca-certificates` for more info.

**Comment by vishalnayak** [comment]
Issues that are not reproducible and/or have not had any interaction for a long time are stale issues. Sometimes even the valid issues remain stale lacking traction either by the maintainers or the community. In order to provide faster responses and better engagement with the community, we strive to keep the issue tracker clean and the issue count low. In this regard, our current policy is to close stale issues after 30 days. If a feature request is being closed, it means that it is not on the product roadmap. Closed issues will still be indexed and available for future viewers. If users feel that the issue is still relevant but is wrongly closed, we encourage reopening them.

Please refer to our [contributing guidelines](https://github.com/hashicorp/vault/blob/main/CONTRIBUTING.md) for details on issue lifecycle.
