### ISSUE TITLE
UI - listing_visibility="unauth" not working for ldap method

### ISSUE THREAD

**Issue by FraaJad** [hashicorp/vault#5051]
**Describe the bug**
After setting listing_visibility="unauth" for the ldap method, the user cannot log in using the new lowercase ldap method via the UI.  Selecting Other and then LDAP still works.

**To Reproduce**
1. Have existing ldap auth method.
2. Set listing_visibility="unauth" on the ldap method using the UI.
3. Start new session to UI and see the new lowercase ldap method.
4. Try to log in as ldap user but fail.

**Expected behavior**
UI login should work in new lowercase "favorited" ldap.

**Environment:**
* Vault Server Version (retrieve with `vault status`): 0.10.4
* Vault CLI Version (retrieve with `vault version`):
* Server Operating System/Architecture: Ubuntu 16

Vault server configuration file(s):

```hcl
listener "tcp" {
  address         = "0.0.0.0:8200"
  cluster_address = "0.0.0.0:8201"
  tls_cert_file   = "/opt/vault/tls/vault.crt.pem"
  tls_key_file    = "/opt/vault/tls/vault.key.pem"
}

storage "consul" {
  address = "127.0.0.1:8500"
  path    = "vault/"
  scheme  = "http"
  service = "vault"

  # HA settings
  cluster_addr  = "https://10.64.92.15:8201"
  api_addr      = "https://10.64.92.15:8201"
}

ui = true
```

**Additional context**
The response to the POST is the same for both ldap and LDAP logins.

**Comment by meirish** [comment]
Hi! Sorry for the late response here - could you provide some more details about the failure? Could you open the browser's dev tools and look to see if there's an error in the networking pane? Is there any error shown in the UI?

The difference between the display is that the lowercase one is the path where the backend is mounted (since you could have more than one LDAP auth method mounted), but if the path is `ldap` that _should_ be an identical request (and sounds like that's the case from your comment about the POST being the same).

I'll dig more into this and try to recreate it over the next few days.

**Comment by FraaJad** [comment]
Hi, no worries!  I just got back from a trip myself.  

There aren't any errors in the networking pane or an error shown in the UI.  In the networking pane, I see that it does the POST and it receives a valid response.  I checked it against the POST using the old LDAP tab and the request and response are identical.  It seems that the UI just doesn't respond to the response of the POST.

**Comment by meirish** [comment]
We tracked it down, and embarrassingly, it _was_ due to capitalization, just not in the way I initially thought. This will be in our next release - thanks for reporting the issue!
