### ISSUE TITLE
[LDAP] Anyone can login

### ISSUE THREAD

**Issue by cireCloud** [hashicorp/vault#5065]
Currently in our production Vault (0.6.1) no one apart from desired group can login (one we created policies for). With the same configuration (we configure it with Terraform) on latest Vault in test environment - any member of LDAP directory can login to the Vault and have default policy. At the moment we made a following permissions for default policy, but we would like previous behavior. Thank you.

Default policy:
path "*" {
 capabilities = ["deny"]
}

**Comment by cireCloud** [comment]
We also tried to limit the LDAP search to specific groups in auth/ldap/config, but still anyone can login, just showing for them that groups were not found and using local permissions.

**Comment by jefferai** [comment]
This change was made to have the different auth methods behave the same when valid credentials are supplied but no particular policy is configured.

You can simply remove all grants from the default policy if you like, or you can further modify your search query so that only the users you want to allow are ever found, but we have no plans to change this behavior back.
