### ISSUE TITLE
Documentation contradiction - root token vs cubbyhole

### ISSUE THREAD

**Issue by kcrouch** [hashicorp/vault#5142]
# The contradiction

The "Tokens Concepts" page states that a root token can do anything.  However the Cubbyhole page contradicts this.  

https://www.vaultproject.io/docs/concepts/tokens.html

### Root Tokens

"Root tokens are tokens that have the root policy attached to them. Root tokens can do anything in Vault. Anything."

https://www.vaultproject.io/guides/secret-mgmt/cubbyhole.html

### Cubbyhole

"It is not possible to reach into another token's cubbyhole even as the root user."
 
### Additional Discussion

The cubbyhole secret engine provides your own private secret storage space where no one else can read (including root).
 
### CLI command (Example:)

"Now, try to access the secret using the root token. It should NOT return the secret."

### API call using cURL (Example:)

"Now, try to access the secret using the root token. It should NOT return the secret."

# One possible solution

I would humbly suggest that the line on the Tokens Concepts page be amended to read something closer to 

"Root tokens can do almost anything in Vault (except reach another token's [cubbyhole](https://www.vaultproject.io/guides/secret-mgmt/cubbyhole.html))."

**Comment by jefferai** [comment]
Technically a root token could reach into another user's Cubbyhole -- but they'd have to know the actual token ID to do so, so that sort of obviates needing the root token in the first place :-)

Also, a root token could use `sys/raw`, if that endpoint is enabled, to reach in, but they'd be more or less stabbing in the dark when trying to read a *particular* cubbyhole. But they could read all cubbyholes that way.

**Comment by vishalnayak** [comment]
Issues that are not reproducible and/or have not had any interaction for a long time are stale issues. Sometimes even the valid issues remain stale lacking traction either by the maintainers or the community. In order to provide faster responses and better engagement with the community, we strive to keep the issue tracker clean and the issue count low. In this regard, our current policy is to close stale issues after 30 days. If a feature request is being closed, it means that it is not on the product roadmap. Closed issues will still be indexed and available for future viewers. If users feel that the issue is still relevant but is wrongly closed, we encourage reopening them.

Please refer to our [contributing guidelines](https://github.com/hashicorp/vault/blob/main/CONTRIBUTING.md) for details on issue lifecycle.
