### ISSUE TITLE
what does the "sudo" do in policy

### ISSUE THREAD

**Issue by lindalovemusic** [hashicorp/vault#5173]
Hi Everyone! Here is a part of policy for admin that provided in official guide. However, I have some questions about the "sudo".
---------------------------------------------------------------------------------------------------
# Manage and manage secret engines broadly across Vault.
path "sys/mounts/*"
{
  capabilities = ["create", "read", "update", "delete", "list", "sudo"]
}
----------------------------------------------------------------------------------------------------
I don't understand that why in this example, we already have "create", "read", " update"," delete", " list" , and we also need "sudo"? Does "create"+"read"+" update"+" delete"+" list" = "sudo"?

**Comment by jefferai** [comment]
Please post questions on the mailing list (https://groups.google.com/forum/m/#!forum/vault-tool) rather than in GitHub issues.

With over 1700 subscribers, the mailing list gets a _lot_ more eyes on any particular question. You'll get an answer faster, not slower, by taking advantage of the suggestions and answers provided by the wealth of experience that long-time users and devs bring to the list.

It also prevents problematic issue workflows for questions where either the issue is closed immediately but then discussion continues on a closed issue; or, the issue is not closed, discussion dies down, and the issue remains open indefinitely waiting for further potential replies.

Thanks!
