### ISSUE TITLE
Policy on attribute level

### ISSUE THREAD

**Issue by joek** [hashicorp/vault#518]
Hi, 
I like to extend the policy system to work on attribute level as well. We need this, to enable users to change their password, without changing their policy. 

At the moment it seems to be an tricky task, since vault seems to overwrite the whole object instead of updating it. So just blocking the user form not changing specific attribute might not work. 

Another solution could be to define default values, which can not be overwritten by the user. 

What do you think, how can we solve the issue?

Cheers
Johannes

**Comment by armon** [comment]
@joek The simplest way is probably to create special paths that have different behavior, for example an `auth/userpass/passwd/<user>` path may be used to change the password given the current one.

Otherwise, you start getting into the world where the semantics of the underlying API have to be exposed to the policy layer. This creates a coupling between the two layers that makes it hard to reason about.

**Comment by jefferai** [comment]
This will hopefully automatically be solved with features planned for 0.11, but there is otherwise no specific action planned for this.
