### ISSUE TITLE
Lease duration for other auth methods

### ISSUE THREAD

**Issue by dominykas** [hashicorp/vault#521]
Basically, what I want, is to specify a duration and/or number of uses for a token that was created by logging in with, say, `userpass`.

Docs say:
> When any other auth backend returns an identity, Vault core invokes the token backend to create a new unique token for that identity.

`/auth/token/create` also has `lease` and `num_uses` params, but I can't seem to find a way to pass these params into other auth methods?

I guess I could try work around this with some bash fu to login, get a new token with a duration, revoke old token, use new token, but it's a bit of a hassle :)

**Comment by kstruis** [comment]
Hi there,

I have somewhat the same question. 

When i authenticate via the auth/app-id/login backend I get back a token with a lease_duration:0 and no limit on the number of uses either. This means on every reauthentication via auth/app-id/login a new token is created which will remain available for eternity and is never revoked?

**Comment by maticmeznar** [comment]
@kstruis Yes. You have to remove tokens manually (you can revoke all app-id tokens with a single command though). I was just stress testing Vault with app-id logins and after about 14000 rounds, Vault DB grew to 100 MB and consumed about 80 MB RAM.

**Comment by jplabit** [comment]
+1 - My monitoring system (using app-id) creates a ton of tokens (1 per run, per node, every 30s) as a part of functionality testing. I will be changing the duration later, but my consul directory is already 1 GB, and that is all tokens (with maybe 10 secrets). Having over 15 million tokens waiting to expire for 30 days (I think?), when I could just set it to 5 or 10 minutes (all I need it for)... seems like a waste of resources.

**Comment by jefferai** [comment]
Some of this is really backend-specific, and we'd welcome enhancements. But, there is some good news -- as of 0.3 (or current master) you will be able to set both a global default/max lease TTL and a per-backend default/max lease TTL. So you could have the default be 7 days and max 30 days globally, but for app-id you could set that to 3 minutes and 6 hours, if you like. Since it's per-backend, this also means that copies of a backend mounted in different locations have separate defaults/max leases.

Again -- if any specific backend is trying to set values rather than use configured defaults, this may not fully solve your problem -- however, the configured maximum for the backend/system will override anything else, which will help a lot.

**Comment by jveiga** [comment]
On the same topic can I set in vault set a ttl per app-id on creation?

**Comment by tomwganem** [comment]
Any plans to address this?

**Comment by jodem** [comment]
Until then, the best solution is to revoke token once finished updating configuration of the app.
/auth/token/revoke-self/

**Comment by jefferai** [comment]
Most of the auth backends support setting values internally, and mount tuning can be used to set values per-mount, so I'm going to close this. If there are specific enhancement asks, please open a new ticket.
