### ISSUE TITLE
Instructions for PaaS-hosting?

### ISSUE THREAD

**Issue by kevinSuttle** [hashicorp/vault#524]
Something like CloudFoundry? 
https://docs.cloudfoundry.org/

**Comment by sethvargo** [comment]
Hi @kevinSuttle 

Thank you for opening an issue. What kind of documentation are you looking for exactly? Do you want docs like CloudFoundry because those are available at vaultproject.io. If you are looking for ways to integrate with CloudFoundy, there are a number of client libraries in Go, Ruby, nodejs, and more to connect to Vault.

**Comment by kevinSuttle** [comment]
I was looking for docs explaining how to deploy Vault to a cloud environment, because I didn't see the clients mentioned in the getting started guides. I've found them now. Thanks! 

https://vaultproject.io/docs/http/libraries.html

**Comment by kevinSuttle** [comment]
Maybe you can help here? https://github.com/kr1sp1n/node-vault/issues/6
