### ISSUE TITLE
Add SELinux enforcement

### ISSUE THREAD

**Issue by davidpoalim** [hashicorp/vault#5267]
**Describe the solution you'd like**
I think that set of custom SELinux labels + custom SELinux policy will be useful for hardening this product.

**Describe alternatives you've considered**
Maybe adding a specific flag to the binary file/configuration file which add SELinux labels to Vault context and setting up SELinux policy.

**Explain any additional use-cases**
I think this kind of feature will add additional layer of security for this product

**Comment by vishalnayak** [comment]
Issues that are not reproducible and/or have not had any interaction for a long time are stale issues. Sometimes even the valid issues remain stale lacking traction either by the maintainers or the community. In order to provide faster responses and better engagement with the community, we strive to keep the issue tracker clean and the issue count low. In this regard, our current policy is to close stale issues after 30 days. If a feature request is being closed, it means that it is not on the product roadmap. Closed issues will still be indexed and available for future viewers. If users feel that the issue is still relevant but is wrongly closed, we encourage reopening them.

Please refer to our [contributing guidelines](https://github.com/hashicorp/vault/blob/main/CONTRIBUTING.md) for details on issue lifecycle.

**Comment by cipherboy** [comment]
For anyone stumbling across this, [this has existed since 2020](https://github.com/hashicorp/vault-selinux-policies) in a separate Hashicorp GH repository. As this policy attempts to be a general starting point, but may need customization depending on specific environments, (feel free to open PRs if the functionality is generally relevant!), we're unlikely to ship this within the main Vault repository. 

Feel free to contribute there if interested!
