### ISSUE TITLE
Confusing lease behaviour for TLS authentication backend

### ISSUE THREAD

**Issue by AndrewKlopper** [hashicorp/vault#527]
I am using Vault 0.2.0 together with the TLS authentication backend.

It seems to be impossible to find out the lease duration for a certificate that has been added to the TLS backend, and lease information returned by Vault CLI and HTTP commands is either non-existent, incorrect or confusing.

I have added a certificate to the TLS authentication backend using the following command:
```
vault write auth/cert/certs/deployment certificate=@ca-deployment.cert.pem policies=demo,dev,prod,staging,basic lease=300
```
Tokens created by logging in using the TLS backend to seem to have the correct lease time based on when they expire, but there doesn't seem to be a way to view the lease time for an existing certificate, either through the CLI:
```
vault read auth/cert/certs/deployment

	Key             Value
	certificate     -----BEGIN CERTIFICATE-----
	...
	-----END CERTIFICATE-----
	display_name    deployment
	policies        demo,dev,prod,staging,basic
```
or the HTTP API:
```
GET /v1/auth/cert/certs/deployment

	{
		"lease_id":"",
		"renewable":false,
		"lease_duration":0,
		"data":{
			"certificate":"-----BEGIN CERTIFICATE-----\n...\n-----END CERTIFICATE-----\n",
			"display_name":"deployment",
			"policies":"demo,dev,prod,staging,basic"
		},
		"auth":null
	}
```
The CLI does not display any lease information, while the information displayed by the HTTP API is just plain wrong.

On a client machine, logging in via the CLI does not display lease information:
```
vault auth -method=cert -ca-cert=$VAULT_CACERT -client-cert=deployment.cert.pem -client-key=deployment.key.pem

	Successfully authenticated! The policies that are associated
	with this token are listed below:

	demo, dev, prod, staging, basic
```
Nor does a token lookup via the CLI:
```
vault read auth/token/lookup-self

	Key             Value
	path            auth/cert/login
	policies        [demo dev prod staging basic]
	display_name    cert-deployment
	id              ...
	meta            map[cert_name:deployment common_name:test.node.consul]
	num_uses        0
```
Once again, a token lookup via the HTTP API appears to indicate that the lease never expires, which is incorrect:
```
curl --cacert $VAULT_CACERT --cert deployment.cert.pem --key deployment.key.pem -H "X-Vault-Token: $VAULT_TOKEN" -H "Content-type: application/json" $VAULT_ADDR/v1/auth/token/lookup-self

	{
		"lease_id":"",
		"renewable":false,
		"lease_duration":0,
		"data":{
			"display_name":"cert-deployment",
			"id":"...",
			"meta":{
				"cert_name":"deployment",
				"common_name":"test.node.consul"
			},
			"num_uses":0,
			"path":"auth/cert/login",
			"policies":["demo","dev","prod","staging","basic"]
		},
		"auth":null
	}
```
It is possible to see the lease duration when logging in using the HTTP API, but here two lease durations are returned:
```
curl --cacert $VAULT_CACERT --cert deployment.cert.pem --key deployment.key.pem $VAULT_ADDR/v1/auth/cert/login -XPOST       

	{
		"lease_id":"",
		"renewable":false,
		"lease_duration":0,
		"data":null,
		"auth":{
			"client_token":"...",
			"policies":["demo","dev","prod","staging","basic"],
			"metadata":{
				"cert_name":"deployment",
				"common_name":"test.node.consul"
			},
			"lease_duration":300,
			"renewable":true
		}
	}
```
Renewing a token via the CLI also returns the lease duration:
```
vault token-renew $VAULT_TOKEN

	Key                     Value
	token                   ...
	token_duration          300
	token_renewable         true
	token_policies          [demo dev prod staging basic]
	token_meta_cert_name    "deployment"
	token_meta_common_name  "test.node.consul"
```
as does the HTTP API, although once again two values are returned:
```
curl --cacert $VAULT_CACERT --cert deployment.cert.pem --key deployment.key.pem -H "X-Vault-Token: $VAULT_TOKEN" -H "Content-type: application/json" $VAULT_ADDR/v1/auth/token/renew/$VAULT_TOKEN -XPUT

	{
		"lease_id":"",
		"renewable":false,
		"lease_duration":0,
		"data":null,
		"auth":{
			"client_token":"...",
			"policies":["demo","dev","prod","staging","basic"],
			"metadata":{
				"cert_name":"deployment",
				"common_name":"test.node.consul"
			},
			"lease_duration":300,
			"renewable":true
		}
	}
```
Most of the above behaviour can be worked around, although it does seem to be unnecessarily confusing. It would be really useful to be able to view the lease duration associated with a certificate, however.

**Comment by sethvargo** [comment]
Ping @jefferai :smile:

**Comment by jefferai** [comment]
@sethvargo You're free to ping me on this, but he's talking about TLS authentication, not the PKI backend  :smile:

**Comment by jefferai** [comment]
A note about the places where "two lease durations" are returned: what you're actually seeing is a lease structure which optionally contains authentication information. "0" is simply the zero value for the duration type; it is shown because in some cases this literally means "using the default" whereas in other cases it just means "not set", and it's a bit context-specific. In all cases, if the lease ID is empty, the other lease values are not meaningful and are simply showing the defaults.

Lease structures may contain just lease information, or they may include authentication information, or both. In this case, it is not containing a lease (hence the lack of the lease ID) but is containing authentication information -- a token. That's what the duration seen in that structure corresponds to -- the TTL for the token.

I'm doing some work on this now to expose the TTL (set by the write, or if not set, the backend/system default) in read calls, which will solve some of your issues. Not displaying the token duration information when logging in is a CLI issue; I'll see if I can fix that now, but regardless, I will work on getting duration information into lookup-self, which will provide at least a useful workaround.
