### ISSUE TITLE
Vault audit log can be used to reduce complexity of guessing AppID/UserID pairs

### ISSUE THREAD

**Issue by armon** [hashicorp/vault#530]
The audit log does store the access paths used to configure the AppID backend and reduces the complexity of guessing the appropriate pairs since the domain of values is now known.

Context: https://groups.google.com/forum/?utm_medium=email&utm_source=footer#!msg/vault-tool/rV_2uGTkh2I/M8lvPgofAAAJ

**Comment by 0xdabbad00** [comment]
Any updates on this?

**Comment by jefferai** [comment]
We definitely want to log the paths hit in the audit log...they're an important part of auditing.

My general recommendation is to not use the App-ID backend for authentication.

**Comment by drmdrew** [comment]
@jefferai I was considering working on a change that could log an associated `display_name` instead of the user-id value when the request path is logged in an audit... so in the audit log, instead of logging:
```
    "path": "auth/app-id/map/user-id/bar"
```
... something like:
```
    "path": "auth/app-id/map/user-id/display-name:name-for-bar"
```

This could help prevent disclosing user-id values in audit logs when there are clients that are using the app-id auth backend that haven't migrated to something better like cubbyhole.

I thought I'd ask here before working on such a PR just to find out if there are objections to such an approach.

**Comment by jefferai** [comment]
I would hold off. We're going to announce something soonish (probably in the next month) that will obviate the need for this. Thank you for asking!

**Comment by drmdrew** [comment]
Ok, no problem. I'll look at some logstash rules to work around user-id values in audit logs in the meantime.

**Comment by jefferai** [comment]
Closing this old bug given that AppID is deprecated in favor of AppRole (which does not have this problem).
