### ISSUE TITLE
Best way to export or set Root Token in dev mode?

### ISSUE THREAD

**Issue by romanlehnert** [hashicorp/vault#532]
Hey, 

since vault in dev mode currently regenerates the root token everytime, i also need to put that newly generated token in the config of consuming apps, everytime, i work on them. 

Do you have any suggestions, how to automate that?

**Comment by BRMatt** [comment]
If you're using vault locally for anything other than integration tests/playing around then you may want to set up a local instance which isn't in dev mode. Reason being that when vault is in dev mode it'll lose the  encryption keys/secrets that your app is using every time it restarts. 

This is [the part of our internal chef recipe](https://gist.github.com/BRMatt/4e47d7a880c841f170f8) that intializes vault and stores the unseal key/root token in `/etc/vault` so that upstart can unseal vault when it starts the service. It works really well for us, and it's the way I'd recommend. After initializing vault chef runs some commands to create the policies/auth tokens we need and assigns them appropriately.

**Comment by sethvargo** [comment]
@romanlehnert 

I would recommend exporting the environment variable VAULT_TOKEN and having the apps read that token instead. Alternatively, your apps can read the contents of the file at `$HOME/.vault-token`. 

I also agree with @BRMatt that you should not run in dev mode if you need re-use.

Please let me know if you have any other questions.

**Comment by romanlehnert** [comment]
@sethvargo this is awesome. The hint for `$HOME/.vault-token` was exactly what i was looking for. 

During development and when running specs, i want to have a vault server up and running that i can use. And until your hint, setting the environment variable was always a manual step of copy & paste. To be honest, doing this manually sucks, and thus i came up with 
```zsh
sed -i "d/^VAULT_TOKEN=\(.*\)/" ../.env; vault server -dev | tee >(grep --line-buffered Root | sed -u -e "s/^Root Token: \(.*\)$/VAULT_TOKEN='\1'/g" >> ../.env)
```
wich sucks even more... basically it fetches the root token from the output of `vault server -dev` and creates an entry for it in a `.env` file. But your hint makes this much more easy. Thanks!

**Comment by sethvargo** [comment]
@romanlehnert here's how I do that in specs: https://github.com/hashicorp/vault-ruby/blob/master/spec/support/vault_server.rb
