### ISSUE TITLE
Improve metrics naming by using labels

### ISSUE THREAD

**Issue by uepoch** [hashicorp/vault#5326]
**Is your feature request related to a problem? Please describe.**
metrics naming in vault could be cleaner and easier to ingest in systems that supports labels
At the moment, vault create a new name for each metric, you would have to write a rule for each specialized metric (like, syslog audit log metrics)

**Describe the solution you'd like**
go-metrics supports labeling (and label filtering) which are a useful and clean way to differentiate metrics with others that share the same functional interest (e.g. latency summary for each http call of the API, audit related statistics per backend type, ..)

**Describe alternatives you've considered**
Go-metrics seems to be the de-facto solution for hashicorp products, overall it's a fine library and could be used

**Explain any additional use-cases**
This would ease aggregation and alerting for people with observability system that support labeling
This would also allow more human friendly name, as most of the time metric name follow a strict convention (like no hyphens, no slash, .. ) and you can end with metrics named `something_api_GET_v1_self_register___count` for something that could be named `something_api_count` with a label set of  path="v1/self/register/" and method="GET"

**Additional context**
It will break client relying on older metrics names, so maybe should be triggered by a flag in configuration
Although vault is not 1.0 yet, it seems risky to break all clients

**Comment by vishalnayak** [comment]
Issues that are not reproducible and/or have not had any interaction for a long time are stale issues. Sometimes even the valid issues remain stale lacking traction either by the maintainers or the community. In order to provide faster responses and better engagement with the community, we strive to keep the issue tracker clean and the issue count low. In this regard, our current policy is to close stale issues after 30 days. If a feature request is being closed, it means that it is not on the product roadmap. Closed issues will still be indexed and available for future viewers. If users feel that the issue is still relevant but is wrongly closed, we encourage reopening them.

Please refer to our [contributing guidelines](https://github.com/hashicorp/vault/blob/main/CONTRIBUTING.md) for details on issue lifecycle.
