### ISSUE TITLE
PKI backend sign-data endpoint similar to transits

### ISSUE THREAD

**Issue by kjord1** [hashicorp/vault#5333]
I would like the ability to sign arbitrary data though the PKI backend, similar to the transit/sign-data endpoint. The basic case for this would be signing JWT tokens without the private key ever leaving vault. Clients need to be able to verify the signature using the x509 cert. For example IoT devices issued cert/keys from a vault issuing CA could communicate directly using JWT tokens as they can both rely on a trusted third party, the issuing CA.

**Comment by sigmunau** [comment]
I'd rather have this as a dedicated secrets backend. JWT tokens doesn't neccessarily require a CA certificate to sign. e.g some apis use authentication based on signing a JWT with a client certificate. 

Such a secrets backend would allow you to upload a certificate and private key, and then create some roles which dictates allowed/forced claims in the created JWTs and then signed JWTs could be generated by a separate endpoint per role with standard vault authentication mechanisms. This way users/clients could be entitled to generate certain JWTs without ever getting access to the private key, and without freely getting to sign whatever data they want.

**Comment by jefferai** [comment]
You can already sign JWTs via `transit`. We just don't export X509 certs from there.

**Comment by sigmunau** [comment]
I specifically looked for this in the `transit` backend, without finding it in the documentation. Looking again through the api documentation I did find something related to this this time around, however there is no way to use an existing certificate for this (except possibly abusing the restore function). And there is no control over what can be signed if the key is in there.

**Comment by pr4th4m** [comment]
@jefferai can you please point me to an example to sign JWT's via transit?
Is it the `marshaling_algorithm=jws` when signing with `ECDSA` keys only?

**Comment by vishalnayak** [comment]
Issues that are not reproducible and/or have not had any interaction for a long time are stale issues. Sometimes even the valid issues remain stale lacking traction either by the maintainers or the community. In order to provide faster responses and better engagement with the community, we strive to keep the issue tracker clean and the issue count low. In this regard, our current policy is to close stale issues after 30 days. If a feature request is being closed, it means that it is not on the product roadmap. Closed issues will still be indexed and available for future viewers. If users feel that the issue is still relevant but is wrongly closed, we encourage reopening them.

Please refer to our [contributing guidelines](https://github.com/hashicorp/vault/blob/main/CONTRIBUTING.md) for details on issue lifecycle.
