### ISSUE TITLE
FreeIPA Secrets Engine feature

### ISSUE THREAD

**Issue by Badrmoh** [hashicorp/vault#5418]
**Is your feature request related to a problem? Please describe.**
I have been trying to use the feature of AD secret engine in my environment. The environment I have uses FreeIPA server ldap server, and naturally is used to manage passwords of users and applications. I tried to adapt the AD secret engine plugin with FreeIPA server by using an openldap proxy to map attributes, however, I hit the wall while trying to map the `pwdLastSet` attribute to FreeIPA's `krbLastPwdChange` attribute. Then problem is that `pwdLastSet` uses UTC standard and is stored as Int in AD, meanwhile, `krbLastPwdChange` uses a different standard (More on this : https://tools.ietf.org/html/rfc4517). Moving to an AD from FreeIPA is a big hassle for me especially the setup is pretty stable and I wouldn't like to mess it up.

**Describe the solution you'd like**
Similar to AD secret engine, it would be very nice to have something for FreeIPA.

**Describe alternatives you've considered**
I considered using openldap proxy but it didn't solve the problem totally, just was able to map few parameters that are formatted the same in both Ad and FreeIPA, while others were basically not using the same format and couldn't be mapped.

**Explain any additional use-cases**
FreeIPA is widely used and is a powerful tool that has being used by us for a while. I am sure that this feature of Vault (AD secret engine) is invaluable for many from security perspective. 

Thanks.

**Comment by jefferai** [comment]
The main reason the existing plugin is AD only (at least, for now), is a) demand and b) it has a standardized access pattern and schema. Different LDAP servers and setups tend to vary widely, making it very difficult to write such an engine that takes into account every possible difference. (Even simply authing against LDAP while supporting various servers is challenging.)

Just some context.

**Comment by 3nprob** [comment]
FreeIPA has been gaining increasing momentum and adoption, and seems like the default choice over OpenLDAP for new deployments in the past couple of years. May be worth revisiting considering this.

**Comment by vishalnayak** [comment]
Issues that are not reproducible and/or have not had any interaction for a long time are stale issues. Sometimes even the valid issues remain stale lacking traction either by the maintainers or the community. In order to provide faster responses and better engagement with the community, we strive to keep the issue tracker clean and the issue count low. In this regard, our current policy is to close stale issues after 30 days. If a feature request is being closed, it means that it is not on the product roadmap. Closed issues will still be indexed and available for future viewers. If users feel that the issue is still relevant but is wrongly closed, we encourage reopening them.

Please refer to our [contributing guidelines](https://github.com/hashicorp/vault/blob/main/CONTRIBUTING.md) for details on issue lifecycle.

**Comment by kalafut** [comment]
See also https://github.com/hashicorp/vault-plugin-secrets-openldap which has the ability to support multiple schemas.
