### ISSUE TITLE
Print server URL

### ISSUE THREAD

**Issue by dol** [hashicorp/vault#547]
It would be nice having a possibility to print the URL of the webserver depending on the config or run mode.
`$vault server -dev -print-url`
Output:
`http://127.0.0.1:8200`
or
`$vault server -print-url -config=/path/to/vault.hcl`
Output depending on the config:
`https://127.0.0.1:8200`

This would help to get the URL in a scriptable way. E.g.:
.bashrc
`export VAULT_ADDR='$(vault server -print-url -config=/path/to/vault.hcl)'`

It's also possible to add a separate command for this feature instead of an additional flag of the 'server' command.

**Comment by jefferai** [comment]
If running in dev mode, it's printed in the output -- a simple grep/sed should be sufficient. If it's being configured via a config file, presumably you could pull the address from that file. Or is there some use-case I'm not seeing?

**Comment by dol** [comment]
>If running in dev mode, it's printed in the output -- a simple grep/sed should be sufficient.

This only works in the terminal in which vault was started.

To properly extract the correct URL from the config file a HCL parser is needed. The URL is a combination of the address and tls_disable config parameters.
Due to possible changes of the configuration params in the future a centralized 'get me the URL command' would be nice.

**Comment by jefferai** [comment]
If running in dev mode, it's printed in the output -- a simple grep/sed should be sufficient. If it's being configured via a config file, presumably you could pull the address from that file. Or is there some use-case I'm not seeing?

**Comment by naunga** [comment]
Wouldn't this command only work on the Vault server? If you're wanting to use this method to set the VAULT_ADDR variable on a client machine then you'd need to distribute the configuration file out. 

It kind of seems like you're looking for Vault to broadcast its service address. Using Consul (or something) to allow clients to discover the Vault server address would be a good way to do that though.

I wrote up a quick bash script that will get the URL for you when you feed it the vault config. You can take a look here: https://gist.github.com/naunga/8ad873dbf760e69884e2. Hopefully that will be useful for you, while awaiting this feature.

**Comment by jefferai** [comment]
What the OP is asking for will in fact only work on the Vault server, but there are a number of things that make it difficult to implement -- for instance, what if one person actually wants the DNS name that Vault is behind vs. the IP address (since the address may be 127.0.0.1 and being reverse-proxied to).

There are a number of good workarounds for this, including Consul (as you suggested), using the same config management system that is writing the Vault config file to also distribute that value out to any clients needing it, or simply parsing it from the output of `netstat` by looking at the address listening on port `8200` (or whatever Vault is configured to listen on).

**Comment by jefferai** [comment]
`vault status` in 0.9.4ish+ will show the url of the active node.
