### ISSUE TITLE
What is the naming convention for secret, policy, role?

### ISSUE THREAD

**Issue by nightfury1204** [hashicorp/vault#5474]
Is there any set of characters that is not allowed to use in the name? Or any regular expression vault use for validation of name?

When I was trying to create role in kubernetes auth for the name `default:demo`, i got following error:
```
vault write auth/kubernetes/role/default:demo \
                       bound_service_account_names=vault-auth \
                       bound_service_account_namespaces=default \
                       policies=default \
                       ttl=1h

Error writing data to auth/kubernetes/role/default:demo: Error making API request.
URL: PUT http://127.0.0.1:8200/v1/auth/kubernetes/role/default:demo
Code: 404. Errors:
* 1 error occurred:
* unsupported path
```

**Comment by catsby** [comment]
Hey @nightfury1204 thanks for reporting. It looks like we don't do any query escaping when constructing the URL here:

- https://github.com/hashicorp/vault/blob/54b0ee9d96fd9411cd9c9b85193445ef580f881b/api/logical.go#L131

I imagine using [url.QueryEscape](https://golang.org/pkg/net/url/#QueryEscape) would probably be sufficient, but we'd also need to update all auth plugins to Unescape as well, or otherwise try to support both.

**Comment by chrishoffman** [comment]
Each backend has a different set of values that are accepted for paths depending on the path definition in the backend.  In the case described above, it uses our GenericNameRegex helper which is
`(?P<%s>\\w(([\\w-.]+)?\\w)?)`.  Each backend defines the allowed values for each path and parameter.

See:
https://github.com/hashicorp/vault-plugin-auth-kubernetes/blob/master/path_role.go#L29
https://github.com/hashicorp/vault/blob/master/logical/framework/path.go#L16-L18
