### ISSUE TITLE
Postgresql backend does not close connections on failure

### ISSUE THREAD

**Issue by joshuata** [hashicorp/vault#554]
Yesterday we tried to revoke user credentials, however the users had permissions that caused the drop to fail. This caused vault to try again, starting a new connection. However, it never closed the existing connections which caused it to fill up the connection pool of the database.

**Comment by jefferai** [comment]
Looking at the code, I can't help but wonder if this is actually a Go bug in the `sql` package. We are using the built-in connection pool and setting a hard limit of open connections to 2.

**Comment by jefferai** [comment]
@joshuata I've looked at the revoke code and it is properly closing the prepared statement. However, I did notice that the number of max connections is set to 2. I can see a possibility where the connection pool isn't immediately closing the connections, so in the case of a retry by Vault of an operation, which may happen rapidly, it can overwhelm that limit.

Any chance you're comfortable building Vault on your own? I can tell you what to change and you can see if you are able to replicate the problem.

Thanks!

**Comment by joshuata** [comment]
We are actually building it from scratch already. I'm currently setting up a database to try and replicate the bug.

**Comment by jefferai** [comment]
OK -- try increasing the value in `builtin/logical/postgresql/backend.go` line 82. If this is indeed the problem there should be some value beyond which you can no longer trigger this issue, because Vault won't open more connections than are being reaped by the connection pool's goroutine(s). Probably making this tunable is a good long-term task.

**Comment by lassizci** [comment]
I have a test setup with pre-built 0.2.0 and I don't see vault closing the connections even on successful creations/deletions. If I create e.g 10 dynamic credentials quickly in a for loop, connections seem to increase by 2. If I create 10 slowly, the connections increase by 20.

**Comment by lassizci** [comment]
The connections apparently aren't closed either when the leader status is lost..

**Comment by jefferai** [comment]
The backend uses the normal Go SQL library, which implements a connection pool. Most connection pools don't close connections unless they meet the conditions of the pool (length of time idle, configured limits, etc.). So it's not completely abnormal that you're seeing connections sit open, because the connection pool will keep open idle connections unless it's told not to.

The behavior reported by @lassizci seems more problematic -- if you haven't changed the max open connections within the Vault code, it shouldn't get beyond 2. I do wonder if this is an issue in the Go SQL library. If you have the opportunity it would be useful to see if you could replicate this behavior with a simple program that opens a connection to the Postgres DB (you could see the code in backend.go in the Vault Postgres backend for an easy template) and runs the loops you mentioned, slowly and then quickly. This would help narrow down whether it's a Vault issue or something in the Go SQL library.

BTW, I've created https://github.com/hashicorp/vault/issues/602 to track the ability to adjust max/idle connections instead of using hardcoded values.

**Comment by lassizci** [comment]
This might be related to another issue we've been facing with etcd backend. It turned out, it's not actually about how slowly or quickly I create the credentials. I'ts about whether the next creation happens before or after the vault has lost it's leader status (with etcd it currently seems to change master every 15 seconds).

As the vault loses its' leader status, it calls unloadMounts() in preSeal and then when it gets the status back, it loads the mounts again, creating a new instance of the backend(?). So after that when I create credentials, it will add 2 (or whatever the pool size is) connections and use those two until the next leader lost.

**Comment by jefferai** [comment]
Ah. Yes, that does make sense. Probably something is keeping around one connection pool, and then a new one is being created. I'm not familiar in my head about whether there are hooks in the backends on unloading, but this should certainly be fixed.

Regarding etcd, we had a report on the Google Group just today or yesterday about someone having a similar issue. In their case they fixed it by switching to Consul; not sure if that's possible for you.

**Comment by joshuata** [comment]
I have been trying to get a replica of the problematic environment up and running, but I'm a student and school has started to take over my life again. I hadn't set it up with the etcd backend, which may have been why I couldn't reproduce the problem earlier.

**Comment by jefferai** [comment]
@joshuata I think the pull request from @lassizci will fix this problem nicely.

**Comment by jefferai** [comment]
Closing due to #608 landing. Props to @lassizci !
