### ISSUE TITLE
Add maintenance code to /v1/sys/health

### ISSUE THREAD

**Issue by adongy** [hashicorp/vault#5550]
**Is your feature request related to a problem? Please describe.**
When performing updates to a Vault cluster, we sometimes have to restart the Vault server (e.g. version upgrades).

Consider the architecture from the [Vault Reference Architecture](https://www.vaultproject.io/guides/operations/reference-architecture.html#load-balancing-using-external-load-balancer) with a load balancer redirecting requests to the active Vault server.

To perform a zero-downtime restart (for the Vault cluster) on the active Vault server, we need to make it step down. However, depending on the load balancer settings, there may be a few moments where the whole custer is unavailable (due to the checks not being performed in time to detect the new active node).

A first solution is to use the `/v1/sys/health` `standbyok` feature, adding every Vault node in the load balancer active pool and relying on Vault forwarding the requests internally to the correct active node.
In that case, stepping down is a zero-downtime operation.

However, restarting a standby node suffers from the same initial issue: there may be a few moments where load balancer requests are redirected to a node that is shutting down.

**Describe the solution you'd like**
Add a new status code for maintenance operations on `/v1/sys/health` to indicate that the node is currently accepting requests, but does not want to receive any if possible.

It will allow the load balancer to detect at its own rate that the maintenance node should have its requests drained, and it can then be restarted at will (from the point of view of the load balancer, nodes in maintenance mode and unresponsive are both unhealthy).

It could be set from the HTTP API (+ added as a command in the CLI) with the same rules as `operator step-down`. Whether you could set it when the node is the active node is questionable.

Example usage:

```
vault operator maintenance -on
vault operator maintenance -off
```

**Describe alternatives you've considered**
At the moment, we've thought of multiple solutions:

Add a reverse proxy between the load balancer and the Vault nodes, where we can set a flag to indicate the node can receive requests properly, but should not receive requests anymore. It adds another block to the infrastructure to maintain.

Remove the node to be restarted from the load balancer pool, then readding it after the node restarted: if possible, we'd like to avoid doing this, as we're touching two different blocks and is more error-prone.

**Comment by vishalnayak** [comment]
Issues that are not reproducible and/or have not had any interaction for a long time are stale issues. Sometimes even the valid issues remain stale lacking traction either by the maintainers or the community. In order to provide faster responses and better engagement with the community, we strive to keep the issue tracker clean and the issue count low. In this regard, our current policy is to close stale issues after 30 days. If a feature request is being closed, it means that it is not on the product roadmap. Closed issues will still be indexed and available for future viewers. If users feel that the issue is still relevant but is wrongly closed, we encourage reopening them.

Please refer to our [contributing guidelines](https://github.com/hashicorp/vault/blob/main/CONTRIBUTING.md) for details on issue lifecycle.
