### ISSUE TITLE
Display the commands to set up the environment variables

### ISSUE THREAD

**Issue by sudarkoff** [hashicorp/vault#556]
This is inspired by the `docker-machine env` feature. Don't know if it's a crazy idea or even if vault is the right tool for this, BUT:

Add a sub-command (e.g. `vault env`) that would display the commands to set up the environment variables out of key/value pairs stored at a particular path. It could be useful to do something like this:

```
$ eval $(vault env secret/my_app/prod/secrets) my_app
```

**Comment by jefferai** [comment]
My initial take on this is that it belongs in a separate command a la https://github.com/hashicorp/envconsul -- I would imagine that by the time everyone would be happy with all of the various ways that this could be used, it will have grown into an eight headed monster.

**Comment by jefferai** [comment]
Still thinking about it, having thought about this more, I see a lot of issues with Vault itself trying to do this. For instance, Vault is configured to listen on addresses, but is probably going to be accessed via a DNS name most of the time, and Vault doesn't know (and generally shouldn't care) what that address is. Even reading it from its TLS cert would be problematic if there are multiple SANs.

At the moment, I'd recommend manually putting the correct value into Consul, and using https://github.com/hashicorp/envconsul rather than building similar information into Vault.

**Comment by sethvargo** [comment]
@jefferai @armon and I have talked about this a few times and we want to add support for this to envconsul. There is an open issue somewhere on the project.

**Comment by sudarkoff** [comment]
I found that envconsul issue. And that solution definitely would be satisfactory for us since we're using consul as a backend for our vault. Closing this issue.
