### ISSUE TITLE
Website ordered lists look like footnotes

### ISSUE THREAD

**Issue by sethvargo** [hashicorp/vault#5571]
In the new website, ordered lists are super small and have a high baseline. This makes them look like footnote references more than an ordered list.

<img width="91" alt="screen shot 2018-10-19 at 9 56 13 pm" src="https://user-images.githubusercontent.com/408570/47250073-f8cfaa80-d3e9-11e8-93c0-1dab9cb02957.png">

/cc @jescalan

**Comment by jescalan** [comment]
Hey there @sethvargo! We have made an adjustment to make sure the numbers are centered a little better since this issue was filed thanks to your feedback. However, the design team wants to keep the smaller size and lighter colors as-is, as their rationale was to make the numbering less visually intrusive. Thanks again for noticing and filing these tickets.
