### ISSUE TITLE
Cannot create child token with identity policy

### ISSUE THREAD

**Issue by solmonk** [hashicorp/vault#5668]
I am trying to move to JWT auth backend and working on utilizing identity groups and their policies, but experiencing issues because of this behavior. 

For example, I have a token with an associated token policy `default` and identity policies `a`, and `b`. But I can only create child token with my token policy `default`. Trying to create a token with policy `a` or `b` results in an error: `child policies must be subset of parent`.

 Although all of my identity policies are inherited to child token, but I can never create a token only having `a` or `b`. This might be an intended behavior because identity policies are not technically token policies, but it is kind of weird and inconvenient that I should only inherit the whole set of policies, not a subset of them.

Is there any plan to support this, or any other alternatives? Thanks!

**Comment by thiloplanz** [comment]
I have the same problem.

My scenario is that I am trying to create an orphan token with only a subset of my own policies. I want this to be an orphan, because I want to immediately after creating the token log out (invalidate the stronger original token). 

What is the best way to achieve this?

**Comment by derBroBro** [comment]
Same here. Even if I have several identiy_policies, they are not considered on creating a token with one of these (error `child policies must be subset of parent`). Any hint if this is the expected behavior?

**Comment by derBroBro** [comment]
As I got a answer from @jefferai on the forums, just a short update here as well:

> This is in fact on purpose!

> When you create a token and put a policy on the token it is bound to that token for the token’s full lifetime. Identity policies are bound to your identity and can come or go at any time relative to the token’s lifetime. As a result, allowing binding of non-token policies to a child token could result in a privilege escalation, where even if the policy is removed from the identity, it would still be bound to the token. So it’s not allowed.

**Comment by vishalnayak** [comment]
Issues that are not reproducible and/or have not had any interaction for a long time are stale issues. Sometimes even the valid issues remain stale lacking traction either by the maintainers or the community. In order to provide faster responses and better engagement with the community, we strive to keep the issue tracker clean and the issue count low. In this regard, our current policy is to close stale issues after 30 days. If a feature request is being closed, it means that it is not on the product roadmap. Closed issues will still be indexed and available for future viewers. If users feel that the issue is still relevant but is wrongly closed, we encourage reopening them.

Please refer to our [contributing guidelines](https://github.com/hashicorp/vault/blob/main/CONTRIBUTING.md) for details on issue lifecycle.
