### ISSUE TITLE
Dynamic User Creation on SSH Backend

### ISSUE THREAD

**Issue by ekristen** [hashicorp/vault#571]
What do you think about giving the SSH backend with the dynamic key the ability to create the user as well and set a dynamic password for the session? It could be implemented as a dynamic_user instead of dynamic_key option.

Thoughts?

**Comment by armon** [comment]
Seems like an interesting possible enhancement. Not sure how people feel about creating/deleting users dynamically though. Adds a lot more edges to the system.

**Comment by ekristen** [comment]
You are correct it does add more edges to the system. One possible avenue would be to change how the install script works, add more logic to the install script and less to the backend, so the script can be more dynamic. This would remove the edges from the system.

**Comment by jefferai** [comment]
@ekristen Any chance you can describe your use-case a bit better? In particular since (when using the OTP method with the ssh backend) Vault enables auditing of which users have accessed a system, what is the benefit you see by having Vault control users vs. using a flexible configuration management engine to manage users and using Vault to manage _access_ to those users?

**Comment by ekristen** [comment]
Well I like the dynamic key system better than the OTP because it forces short lived secrets, whereas OTP does not, that means old possibly compromised passwords and ssh keys could be on the server still. OTP should enforce only valid users with valid access to vault can access but I have audit logs with vault already so I know what users are calling all endpoints. I also have auditing on all servers auth logs too. 

I think there is a nice use case whereby I grant someone access to use a specific role that allows them access to a certain set of servers without first having to have my configuration management server create an account on a linux box, especially for accounts that rarely get used. 

Like I mentioned earlier if we slightly change the install_script to provide the username, and move the authorized key path to the install_script then we can allow for any behavior and not limit it to just that of modifying the authorized_keys file.

**Comment by jefferai** [comment]
OTP does in fact force short-lived secrets -- it has the same TTL property as the dynamic keys, except that the login credentials can only be used once instead of many times during that TTL period. I don't follow how using OTP allows "old possibly compromised passwords and ssh keys" to sit on the server whereas the dynamic key method does not -- neither affects user account passwords or pre-existing SSH keys.

Vault audit logs are not sufficient to prove access when using dynamic keys. OTPs are tied to particular Vault tokens and this is reflected in the audit log; since dynamically generated keys are used for direct logins, they do not trip the actual login through the audit log. So, suppose two users request access to a system and are given a dynamically generated key for the same user. Then, three minutes later one of them logs in; one more minute later another one logs in. Which one logged in when?

There's also a potential security issue with the dynamic key backend in that it doesn't prevent users from simply adding their own private SSH key as a valid key, skipping Vault for future logins.

**Comment by vishalnayak** [comment]
Adding to what Jeff said. 
Dynamic keys can be renewed unlike OTPs and hence can be misused.
OTPs are cryptographically secure (golang claims) UUIDs and are hard to guess.
OTPs expire in 10 minutes and so there is no way old compromised passwords reside in server.

**Comment by ketzacoatl** [comment]
While I too am on the fence about whether vault should be creating users like this, I think it's reasonable to solve this by making Vault's use of the install script a little more flexible: eg - and maybe Vault already does this.. I am not sure - when setting up this backend, Vault could let the admin specify the install script to use. Or maybe a command/script to run if the user is not yet present.

Said another way, I don't like the idea that Vault would create users directly, but I think it's reasonable to allow that possibility by giving the admin the ability to specify the script to use.

**Comment by therc** [comment]
Even if you created an user, what UID/GID would you give to it? The question is important, because

a) the UID chosen has ramifications past the lifetime of the SSH session, if e.g. the user starts creating files
b) it then leads to the question of whether UIDs are ever returned or recycled
c) if there's any kind of shared storage, you need two SSH daemons on two separate hosts to generate a consistent UID across both. Even if you used a predictable hashing function, you still have to deal with potential collisions, which can manifest themselves in different order on each of the hosts.

If only you could look up a central, authoritative source of UIDs... something like a directory ;-)

**Comment by jefferai** [comment]
We have no plans to implement this, so closing.
