### ISSUE TITLE
Zookeeper Connection getting closed while saving new key in HA setup using ZooKeeper

### ISSUE THREAD

**Issue by abhijith-vr** [hashicorp/vault#5830]
**Describe the bug**
For storing secret information , we have setup vault in HA mode with Zookeeper as back end .Will work fine for less number of requests , but when increases the number of requests suddenly vault gives 500 server error.When checked logs following logs are printed 

"
Nov 21 08:40:35   vault: 2018-11-21T08:40:35.639Z [ERROR] core: failed to run existence check: error="existence check failed: zk: connection closed"
Nov 21 08:40:35   vault: 2018-11-21T08:40:35.639Z [ERROR] core: failed to run existence check: error="existence check failed: zk: connection closed"
Nov 21 08:40:35   vault: 2018-11-21T08:40:35.639Z [ERROR] core: failed to run existence check: error="existence check failed: zk: connection closed"
Nov 21 08:40:35   vault: 2018-11-21T08:40:35.639Z [ERROR] core: failed to run existence check: error="existence check failed: zk: connection closed""

1. Run  vault server in HA mode with zoo keeper as back end
2.Zoo keeper cluster is setup in Multiple Availability Zones in Amazon Cloud
3. Start multiple requests of  Save Secret API POST "/v1/secret/keyname#"  to save multiple secrets

**Expected behavior**
All save should be successful

**Environment:**
* Vault Server Version (retrieve with `vault status`):Vault v0.10.4 ('e21712a687889de1125e0a12a980420b1a4f72d3')
*Zookeeper - zookeeper-3.4.13
* Vault CLI Version (retrieve with `vault version`):
* Server Operating System/Architecture:AWS - EC2 Cloud ,3 vault instances and 3 node Zookeeper cluster

Vault server configuration file(s):
 
storage "zookeeper" {
  address = "10.20.151.147:2181,10.20.152.64:2181,10.20.153.106:2181"
  path = "vault/"
  redirect_addr = "10.20.151.15:8200"
}

listener "tcp" {
  address = "10.20.151.15:8200"
  cluster_address = "10.20.151.15:8201"
  tls_disable = "true"
}

ui = true
disable_mlock = false
default_lease_ttl = "63600h"
max_lease_ttl = "127200h"
api_addr = "http://10.20.151.15:8200"
cluster_addr = "https://10.20.151.15:8201"
disable_clustering = "false"
-------------------------

 Zoo keeper logs
Nov 21 09:19:46  Vault_HA systemd: zookeeper.service failed.
Nov 21 09:19:46  Vault_HA systemd: zookeeper.service holdoff time over, scheduling restart.
Nov 21 09:19:46  _HA systemd: Starting Zookeeper CN1 To Hashicorp_Vault_HA...
Nov 21 09:19:46  Vault_HA zookeeper: ZooKeeper JMX enabled by default

**Comment by vishalnayak** [comment]
Issues that are not reproducible and/or have not had any interaction for a long time are stale issues. Sometimes even the valid issues remain stale lacking traction either by the maintainers or the community. In order to provide faster responses and better engagement with the community, we strive to keep the issue tracker clean and the issue count low. In this regard, our current policy is to close stale issues after 30 days. If a feature request is being closed, it means that it is not on the product roadmap. Closed issues will still be indexed and available for future viewers. If users feel that the issue is still relevant but is wrongly closed, we encourage reopening them.

Please refer to our [contributing guidelines](https://github.com/hashicorp/vault/blob/main/CONTRIBUTING.md) for details on issue lifecycle.
