### ISSUE TITLE
KV path mismatch

### ISSUE THREAD

**Issue by Narayanan170** [hashicorp/vault#5871]
I'm really confused by the recent changes in the KV API. The HTTP API and the CLI  have different paths to access my KV store, and that would be OK if I could prepend/append something to a path and that would be it, but the current implementation seems weird.

Ex.
mount_a - KV mount

We do a `vault kv put mount_a/first/second test=bla`

When we want to get it via CLI, we need that path we have just written to...
`vault kv get mount_a/first/second`
But when we use the API, we need to construct a path that is mount_name/data/path without mount name, which is just weird and frustrating
So getting the same secret via the API would look like:
`curl --header "X-Vault-Token: $(cat ~/.vault-token)" https://vault.example.com:8200/v1/mount_a/data/first/second`

The path should be the same for those two methods of accessing the secret

Since vault has a versioned API, maybe that can be done with /v2/ version prefix

**Comment by meirish** [comment]
Hi @Narayanan170 - thanks for filing an issue. The differences you're seeing are because the paths for kv v1 and kv v2 are different (see here for a description of the kv API paths: https://www.vaultproject.io/docs/secrets/kv/kv-v2.html#acl-rules ) - in order for the `vault kv` subcommand to be compatible for both versions, the command does some data transforms.

If you'd like to operate on the same paths, you can use the lower-level `vault write` command.
