### ISSUE TITLE
KV Secrets Engine - Version 2 (API) - parameter / max_versions defaults to 10 document bug

### ISSUE THREAD

**Issue by hassanrt** [hashicorp/vault#5907]
Description:   The following test enviably shows that (max_version 0) means 10.  Other documentation possibly say DEFAULT instead of 0 in the CLI. 

Test:

for i in {1..1000}; do vault kv put teams/linux/test value=secret-$i; done

$ vault kv get teams/linux/test
====== Metadata ======
Key              Value
---              -----
created_time     2018-12-05T15:43:09.728994322Z
deletion_time    n/a
destroyed        false
version          1001

==== Data ====
Key      Value
---      -----
value    secret-1000

$ vault kv get -version=$((1001 - 9)) teams/linux/test
====== Metadata ======
Key              Value
---              -----
created_time     2018-12-05T15:43:08.811930186Z
deletion_time    n/a
destroyed        false
version          992

==== Data ====
Key      Value
---      -----
value    secret-991

$ vault kv get -version=$((1001 - 10)) teams/linux/test
No value found at teams/linux/data/test

--The default is 10

$ vault read teams/linux/config
Key             Value
---             -----
cas_required    false
max_versions    0
--So 0 is a misnomer??

**Comment by jcrowthe** [comment]
Coincidentally, 10 is also an integer. Shouldn't the API report the accurate value instead of showing 0 and silently enforcing 10?

**Comment by aphorise** [comment]
I think this has since been resolved and is no longer applicable?

Using 1.5.0 - I was not able to spot any issues. @hassanrt maybe you can confirm?

```bash
for i in {1..1000}; do vault kv put -format=json kv/test value=secret-$i | jq -r '.data.version' ; done
  # 1
  # ...
  # 1000

vault kv get kv/test ;
  # ====== Metadata ======
  # Key              Value
  # ---              -----
  # created_time     2020-08-09T21:36:46.330074777Z
  # deletion_time    n/a
  # destroyed        false
  # version          1000
  # 
  # ===== Data =====
  # Key        Value
  # ---        -----
  # value      secret-1000

vault kv get -version=$((1001 - 10)) kv/test ;
  # ====== Metadata ======
  # Key              Value
  # ---              -----
  # created_time     2020-08-09T21:36:45.585728934Z
  # deletion_time    n/a
  # destroyed        false
  # version          991
  # 
  # ===== Data =====
  # Key        Value
  # ---        -----
  # value      secret-991
```

**Comment by vishalnayak** [comment]
Issues that are not reproducible and/or have not had any interaction for a long time are stale issues. Sometimes even the valid issues remain stale lacking traction either by the maintainers or the community. In order to provide faster responses and better engagement with the community, we strive to keep the issue tracker clean and the issue count low. In this regard, our current policy is to close stale issues after 30 days. If a feature request is being closed, it means that it is not on the product roadmap. Closed issues will still be indexed and available for future viewers. If users feel that the issue is still relevant but is wrongly closed, we encourage reopening them.

Please refer to our [contributing guidelines](https://github.com/hashicorp/vault/blob/main/CONTRIBUTING.md) for details on issue lifecycle.
