### ISSUE TITLE
Vault cannot revoke RDS+MSSQL when user logged in

### ISSUE THREAD

**Issue by jhmartin** [hashicorp/vault#5914]
**Describe the bug**
https://www.vaultproject.io/docs/secrets/databases/mssql.html#amazon-rds describes a sample custom revocation statement for RDS MSSQL as the built-in default is not compatible. The sample script fails if the user is logged in:

`* failed to revoke entry: resp: (*logical.Response)(nil) err: mssql: Could not drop login 'v-root-my-role-4Hd5tHL0dpI8sjMcDPtC-1544115511' as the user is currently logged in.`

Since the entire custom revocation script is run in a single transaction, the failure of the `DROP LOGIN` also rolls back the `DROP USER`, plus any attempts to add `ALTER USER ... DISABLE`. 

Adding logic to kill any outstanding user sessions fails as the custom revocation statements are run in a transaction, and `KILL` results in

`* failed to revoke entry: resp: (*logical.Response)(nil) err: mssql: KILL command cannot be used inside user transactions.`

There's no mechanism in the plugin to skip transactions for the custom revocation script.  Note that the built-in mechanism skips transactions in order to revoke as much access as possible, so perhaps that should be used in this scenario as well.

**To Reproduce**
1. Create a RDS MSSQL instance, configuring Vault with the master login and password.
2. Configure Vault MSSQL w/the sample custom revocation script
3. Log in with the vault provided credentials
4. Attempt to revoke the lease
5. Observe user retains login and query permissions.

**Expected behavior**
Connected RDS MSSQL users who have their lease expired/revoked have their access revoked and are disconnected from the database.

**Environment:**
* Vault Server Version (retrieve with `vault status`): 1.0.0
* Vault CLI Version (retrieve with `vault version`): Vault v1.0.0 ('c19cef14891751a23eaa9b41fd456d1f99e7e856')
* Server Operating System/Architecture: AWS RDS SqlServer SE 10.50

**Comment by tyrannosaurus-becks** [comment]
To help make this easier to develop against, I tried to switch this over to using docker to create a test environment [like the one for Mongo](https://github.com/hashicorp/vault/blob/master/plugins/database/mongodb/mongodb_test.go#L22). I found a container should be available [here](https://hub.docker.com/r/microsoft/mssql-server) but when I actually tried to use it pointed at `msint.azurecr.io/mssql/server` as described in their docs, I got a `API error (500): Get https://msint.azurecr.io/v2/mssql/server/manifests/latest: unauthorized: authentication required` response. 

I believe it's because [we would need to pay for an account](https://azure.microsoft.com/en-gb/pricing/details/container-registry/).

Just wanted to share that here to prevent others from beating down the same path, and to see if anyone has any other suggestions.
