### ISSUE TITLE
New Templating Parameters for approle/ldap Auth Methods

### ISSUE THREAD

**Issue by lcgkm** [hashicorp/vault#5916]
How to write the templated ACL policies for AppRole?
Current Available Templating Parameters don't have role_name... 
https://www.vaultproject.io/guides/identity/policy-templating.html

For approle token, we can find following info:
token_meta_role_name=\<\<approle name\>\>

For ldap token, we can find following info:
token_meta_username=\<\<ldap username\>\>

So, can we use token meta data as policy templating parameter? For example:
token.metadata.\<\<metadata key\>\>

Reference:
https://learn.hashicorp.com/vault/identity-access-management/policy-templating#available-templating-parameters

**Comment by chrishoffman** [comment]
Token metadata will likely not be added to the available template parameters.  For both of the use cases above, you can leverage the identity system.  Each AppRole will create an entity in the identity system with a mapping to the role id.  LDAP has a mapping to the username.

Check out these guides for more information:
https://learn.hashicorp.com/vault/identity-access-management/iam-identity
https://learn.hashicorp.com/vault/identity-access-management/policy-templating

**Comment by lcgkm** [comment]
Hi @chrishoffman ,

Sorry for bother you.

> Each AppRole will create an entity in the identity system with a mapping to the role id. 
Could you provide more details about this? How about the entity lifecycle?
And I can find that AppRole will create an entity and entity alias in identity system, the entity alias as same as the AppRole's role id.
But how about AppRole's role name?
Can we add AppRole's role name to entity alias meta?

Best Regards,
CG Li

**Comment by chrishoffman** [comment]
@sielaq Yes, that is true but these have to be encoded into each backend and do not provide centralized management available to all backends.  We have seen requests in the past to extend token metadata to additional backends but have decided not to pursue it because it has to be customized per backend.  The identity system provides the same functionality but centralizes all the functionality and makes it available to all auth methods.

**Comment by sielaq** [comment]
@chrishoffman thanks for clarification. 
The only problem I have (probably different from @lcgkm, but still around this issue)
 is: that we use very cool project
https://github.com/nemosupremo/vault-gatekeeper
to let application accessing properties/secrets...

Using vault-gatekeeper you can match the app name (that runs in mesos) with AppRole (role_name),
and you get temporal token back for accessing own secrets.  In that moment app, that want to access own-namebased-secret, require a policy per application. I cannot create a simple one policy like:
```
path "secrets/{{identity.entity.name}}" {
    capabilities = ["read"]
}
```
because `identity.entity.name` is not the same like `role_name` and I have no `role_name` in templating :( (or might be I have overseen something ? )

**Comment by lcgkm** [comment]
https://github.com/hashicorp/vault/pull/9529
