### ISSUE TITLE
Identity engine should support managing entity-alias by name

### ISSUE THREAD

**Issue by viralpoetry** [hashicorp/vault#5943]
Hi,
In the Identity Secret Engine, it is possible to get information about the entity  using the `entity` name, but I really miss the same functionality for the `entity-alias`.

I would like to remove `entity-alias` by script, but currently there is no way on how to find the alias by using username from some other authentication backend. It is possible to find out alias ID by reading entity ID first, but it's not the most straightforward way.

I can list entities like this:
```
$ vault list identity/entity/name
Keys
----
entity_808505f9
entity_87c1d724
```

it would be nice to have the same functionality for the `identity/entity-alias/name` path.

Thank you for your time,
Peter

**Comment by meirish** [comment]
Hi! This isn't currently possible because unlike entity name, entity alias name is not unique across aliases on a single entity, as there may be several aliases across different auth methods (think using the same email to log in at different mounts). 

If you add a mount_accessor, you can the lookup api to look up an entity given an alias name and an auth_mount_accessor though - see the endpoint docs here: https://www.vaultproject.io/api/secret/identity/lookup.html#lookup-an-entity

**Comment by MaroonedMind** [comment]
Hello, @meirish ! Is it possible to lookup an entity by alias-name and mount-accessor via CLI (in UI)?

**Comment by loewenstein** [comment]
@meirish I would be interested in an answer as well. I would like to manage access to a namespace via a group of entities in a parent namespaces and the things I know and can ask people for is the username of their login, i.e. the entity alias name.

Now how do I do that without iterating over 1000s of entity aliases one by one, filtering by their name? At least for me, all the list commands only returned the ids...

**Comment by grembo** [comment]
> Hello, @meirish ! Is it possible to lookup an entity by alias-name and mount-accessor via CLI (in UI)?

@MaroonedMind that's

    vault write -field id identity/lookup/entity \
      alias_name=<alias> \
      alias_mount_accessor=<mountaccessor>
