### ISSUE TITLE
MongoDB Atlas API Plugin

### ISSUE THREAD

**Issue by ahartma1** [hashicorp/vault#5962]
**Is your feature request related to a problem? Please describe.**
Atlas is the cloud-based enterprise DaaS solution. If you have an enterprise subscription, you are most likely using the Atlas product. The problem is, all DB users are managed via the web GUI or via the HTTP API. Thus, any user created by the MongoDB driver will be immediately erased by Atlas, invalidating the usefulness of the mongodb driver for anything but a community edition of the database. This is insufficient for any organization that intends on seriously leveraging Vault and MongoDB together

**Describe the solution you'd like**
Please create a MongoDB Atlas Database Secrets plugin. The plugin would interact not with the database directly, but rather with the HTTP API. 

**Describe alternatives you've considered**
I suspect other coming DaaS solutions may benefit from a generic HTTP API Secrets Engine. This would also fit our needs potentially

**Explain any additional use-cases**
Any use case related to Enterprise MongoDB falls within the purview of this request

**Additional context**
A Go library for interacting with Atlas does already exist, so this might be pretty simple to implement at least as a Custom Database Secrets Engine.
https://github.com/akshaykarle/go-mongodbatlas

**Comment by erickufrin** [comment]
We are also in critical-need of this as a native secret plugin. Thank you!

**Comment by ahartma1** [comment]
I got a tentative yes-ish from Nicolas on mIRC who works at hashicorp.

**Comment by ahartma1** [comment]
but that was awhile ago

**Comment by brianjo1** [comment]
really need this dynamic secret functionality!!

**Comment by tmackness** [comment]
I agree this would be good to see

**Comment by gordonbondon** [comment]
Third party plugin is available https://github.com/mealal/vault-atlas-plugin . We tested it at our environments and it works.

**Comment by JnMik** [comment]
@gordonbondon  I'm having trouble installing the plugin on my vault instances, mind sharing your install script ?

**Comment by ahartma1** [comment]
I never saw that this was implemented, but thank you guys for all your work! 

@jnmik 

https://www.vaultproject.io/docs/plugin/

**Comment by JnMik** [comment]
Thanks @ahartma1, it will serve me well to install the plugin. Seems pretty straight forward.
I just need to manage to build it first -_- 
lol

**Comment by gordonbondon** [comment]
Ther's now an official plugin https://github.com/mongodb/vault-plugin-secrets-mongodbatlas

**Comment by Throckmortra** [comment]
Hope this gets added to core plugins :)

**Comment by vishalnayak** [comment]
Issues that are not reproducible and/or have not had any interaction for a long time are stale issues. Sometimes even the valid issues remain stale lacking traction either by the maintainers or the community. In order to provide faster responses and better engagement with the community, we strive to keep the issue tracker clean and the issue count low. In this regard, our current policy is to close stale issues after 30 days. If a feature request is being closed, it means that it is not on the product roadmap. Closed issues will still be indexed and available for future viewers. If users feel that the issue is still relevant but is wrongly closed, we encourage reopening them.

Please refer to our [contributing guidelines](https://github.com/hashicorp/vault/blob/main/CONTRIBUTING.md) for details on issue lifecycle.

**Comment by kalafut** [comment]
Note: MongoDB Atlas support was added in Vault 1.4.0.
