### ISSUE TITLE
Error writing data to auth/kubernetes/login

### ISSUE THREAD

**Issue by tak2siva** [hashicorp/vault#5985]
I have two GKE clusters one for vault and other running applications. 

When I try to authenticate using kubernetes backend

```
vault write auth/kubernetes/login role=app-role jwt="{JWT}"
```

I'm getting this error
```
Error writing data to auth/kubernetes/login: Error making API request.

URL: PUT http://127.0.0.1:8200/v1/auth/kubernetes/login
Code: 500. Errors:

* Post https://APP_GKE_IP:8443/apis/authentication.k8s.io/v1/tokenreviews: dial tcp APP_GKE_IP:8443: i/o timeout
```

I tried adding ingress/egress firewall rule between GKE but that didn't help. Not sure what I am doing wrong. 

FYI: I used this [blog](https://coreos.com/tectonic/docs/latest/vault-operator/user/kubernetes-auth-backend.html) as reference for setting up

**Comment by tak2siva** [comment]
@catsby I replaced actual IP with `APP_GKE_IP` for the sake of posting here. Maybe I should've been explained better.

Anyway I figured out the problem. This is how the [documentation](https://www.vaultproject.io/docs/auth/kubernetes.html#configuration) says to setup Kubernetes auth
```
vault write auth/kubernetes/config \
    token_reviewer_jwt="reviewer_service_account_jwt" \
    kubernetes_host=https://192.168.99.100:8443 \
    kubernetes_ca_cert=@ca.crt
```

It works if I remove port number from kubernetes_host

**Comment by catsby** [comment]
Hey @tak2siva - thanks for following up and closing your issue. 

> It works if I remove port number from kubernetes_host

That's a curious thing though, the documentation says it supports including the port:

```
kubernetes_host (string: <required>) - Host must be a host string, a host:port pair, or a URL to the base of the Kubernetes API server.
```

(from https://www.vaultproject.io/api/auth/kubernetes/index.html#configure-method)

From looking at the code, I don't yet see any indication that we modify or parse that url either, we just use it directly 🤔

Please let me know if you hit anything else, or find more information, otherwise thanks again for following up 😄
