### ISSUE TITLE
Using vault to store hmac key

### ISSUE THREAD

**Issue by pokey** [hashicorp/vault#600]
I use an hmac algorithm to sign cookies that I send to my users.  I have one hmac key that needs to be shared between all my application servers to sign and verify cookies.  I was thinking of putting the hmac key in vault.  Questions:

* Is this a standard use case for vault?
* Should I just put the hmac key in the generic secrets backend?
* What should I do with the hmac key once the application server process receives it?  I noticed that vault uses mlock to ensure that nothing important is swapped to disk.  Should I do the same thing with the hmac key in my application server?  Or should I just delete it as quickly as possible and ask for it again from vault whenever I need it?
* My application servers don't currently support upstream https requests (I'm using the [h2o server library](https://h2o.examp1e.net/)).  Is there any other safe way to get the hmac key from the vault server?

**Comment by jefferai** [comment]
FYI, in the future please use https://groups.google.com/forum/#!topic/vault-tool/ for this kind of question -- that gets a lot of community eyes on the question, and a lot of people have great advice about their usage patterns.

This is indeed a pretty standard use-case for Vault, especially for the generic secrets backend. You may also be interested in the `transit` backend, which will be gaining some additional capabilities for key rotation and generation soon.

Generally speaking you shouldn't keep querying Vault for the same value over and over. Vault doesn't remove values from the `generic` backend when they expire, but it does generate leases (for now; in the future it may not generate leases for backends that don't actually remove or revoke anything). So reading values over and over and over will eventually clog up your physical storage, depending on how often you are doing it and what the lease time is.

As for mlock, I'd worry much less about that (especially since you could set up encrypted swap as a workaround) and much more about the upstream HTTPS problem. There isn't really any safe way to get any sort of secret from a network server without some kind of encryption/cover.

What you may want to do is have a separate process (maybe that runs before application startup, in a script) fetch the value from Vault and put it somewhere accessible to the application from the local machine -- either in a temporary file (perhaps on a ramdisk), or injected into the application's environment on startup.

**Comment by jefferai** [comment]
I'm going to close this for the moment -- the transit improvements will be in 0.3. Please reopen after then if you think your use cases can't be met and we can discuss further.

Thanks!

**Comment by pokey** [comment]
Yes, that was quite helpful. I think I'll go with your suggestion of
injecting the key into the application's environment on startup. Thanks!

**Comment by jefferai** [comment]
@pokey A few more comments:

* If you are reading over and over, for the moment, I suggest not setting a "ttl" (previously "lease") value when you set the item in the `generic` backend, as this prevents a lease being generated on read, which is currently expensive.

* Very shortly in master (and in the upcoming 0.3) you can use the `transit` backend to generate a data key, which is just a 128-bit or 256-bit high-entropy opaque value that arrives in ciphertext (and optionally plaintext). You can give this encrypted key to your servers via the environment, then they can use their access privileges to Vault (controlled by their Vault token, which must also be received securely) to decrypt this into the plaintext value that can then be used for HMAC and other duties.
