### ISSUE TITLE
Support for importing client keys protected by passphrases

### ISSUE THREAD

**Issue by alansill** [hashicorp/vault#603]
I'm having trouble understanding the use case for allowing import of client TLS certificate and key pairs. Why would one have a client key that is not protected by a passphrase laying around on disk? What openssl functions are being called here?

In any case, can support be added for allowing the vault auth -method=cert CLI command to be used when the client key is protected by a passphrase?

**Comment by vishalnayak** [comment]
Issues that are not reproducible and/or not gotten responses for a long time are stale issues. In order to provide faster responses and better engagement with the community, we strive to keep the issue tracker clean and the issue count low. In this regard, our current policy is to close stale issues after 30 days. Closed issues will still be indexed and available for future viewers. If users feel that the issue is still relevant, we encourage reopening them.
   
Please refer to our [contributing guidelines](https://github.com/hashicorp/vault/blob/main/CONTRIBUTING.md) for details on issue lifecycle.
