### ISSUE TITLE
enable auth response from authenticated endpoints in Vault plugins

### ISSUE THREAD

**Issue by dustin-decker** [hashicorp/vault#6074]
**Is your feature request related to a problem? Please describe.**
I am making an auth plugin, and I'd like to issue an auth response from an authenticated endpoint.
When doing this, I get an error:

```[ERROR] core: unexpected Auth response for non-token backend: request_path=auth/controller/issue```

This is due to authenticated requests with an auth response tripping this logic: https://github.com/hashicorp/vault/blob/master/vault/request_handling.go#L782

Unauthenticated requests are allowed to send an auth response.

**Describe the solution you'd like**
I would like to be able to send an auth response for an authenticated request.

**Describe alternatives you've considered**
I could make the `issue` endpoint unauthenticated, have a separate authenticated endpoint return a token to a consumer, and expect that token from the consumer as a request param on the unauthenticated `issue` endpoint.

Here's what the flow would look like with the alternative work around:
```
# authenticated endpoint
BACKEND_TOKEN=$(vault read auth/controller/config -field=backend_token)

# unauthenticated endpoint
vault write auth/controller/issue role="github.com/some/repo" token="$BACKEND_TOKEN"
```

**Comment by jefferai** [comment]
Could you explain the use case so that we can think this through? Why do you need to issue a Vault token to an already authenticated Vault client?

**Comment by jefferai** [comment]
Why not use token store roles? Or, use approles and inject roleids/secretids instead and let those jobs then authenticate with those.

**Comment by dustin-decker** [comment]
There are a few issues I've identified with using token or AppRoles for the controller use case:

1. We cannot namespace the paths for different types of resource roles, or resource roles better represented with a structure:
    ```
    $ vault write auth/approle/role/github.com/some/repo policies="some-policy"

    Error writing data to auth/approle/role/github.com/some/repo: Error making API request.

    URL: PUT http://127.0.0.1:8200/v1/auth/approle/role/github.com/some/repo
    Code: 404. Errors:

    * 1 error occurred:
        * unsupported path
    ```
1. There is a privilege escalation vector due to the controller policy requiring path globbing which allows both policy creation and token issuance.

    Required controller policy for issuing tokens:
    ```
    path "auth/approle/role/github.com*" {
    capabilities = ["create"]
    }
    ```

    Privilege-escalating policy write:
    ```
    $ vault write auth/approle/role/github.com-some-repo policies="root_equivalent"
    ```

    Issue token for privilege-escalated policy:
    ```
    $ vault write -f auth/approle/role/github.com-some-repo/secret-id
    Key                   Value
    ---                   -----
    secret_id             7ebc8b56-c933-9bf4-ad3d-f1a214f10cf6
    secret_id_accessor    4552ce70-d413-caa8-4b68-9b8c5e9e2398
    ```

**Comment by jefferai** [comment]
Addressing your second question first:
> Required controller policy for issuing tokens:
```
path "auth/approle/role/github.com*" {
capabilities = ["create"]
}
```
Why are you using that as your policy? Keep privileges separate -- give the person configuring the role that you trust access to `/policies` and give the service issuing IDs access to `/secret-id` and neither can do both.

Fundamentally anyone that can configure an auth method can choose the policies that are allowed, which is why it's a good idea to keep such configuration to minimum sets of people and make use of things like Control Groups to have multiple authorizations required to update them, and watches on your audit logs to alert when these endpoints are called.

But in this particular case, nearly everything you can do with approle has a separate endpoint that can be used instead for this exact reason, to make it easier to ACL.

> Privilege-escalating policy write:
```
$ vault write auth/approle/role/github.com-some-repo policies="root_equivalent"
```
I strongly suggest you don't put `root_equivalent` style policies in approles.

First question:

> We cannot namespace the paths for different types of resource roles, or resource roles better represented with a structure:

You have some options here:
1. Fork the existing approle plugin to allow these patterns
2. Make a transformation to your strings to remove `/` from them, so that everything simply works as-is (such as a simple character replacement, or at an extreme, a urlsafe base64ing)
3. File a feature request asking us to consider relaxing the regex here to allow slashes, if there is a specific use-case that can't be solved by simply transforming the strings

**Comment by dustin-decker** [comment]
The write path for creating a role is a subset of the write path for accessing `/secret-id`, and only trailing globs in paths are properly supported. This means we would need to explicitly grant write access in the controller policy to the full `secret-id` path for each resource role in the mount (potentially hundreds, or thousands) in order to prevent it from being able to create new roles. New roles created could reference policies known to Vault that were never intended for that use case.

Our policies and roles are maintained via a gitops workflow, so `auth/$MOUNT/role/github.com/some/repo` actually represents a path to a role file in a git repository. To keep both the file tree and the Vault key space manageable we'd like to preserve the `/`.

If I made PR to relax the regex and support globs within a path, we could make AppRole work for this use case.

**Comment by dustin-decker** [comment]
These are the best four options i've identified to move my project forward:

1. keep the existing custom auth plugin with the workaround
2. enable auth response from authenticated plugin endpoints (upstream Vault change)
3. fork approle plugin and modify the paths (possibly upstream it as AppRole V2?)
4. relax AppRole regex to allow `/` and modify vault globbing to support non-trailing globs (upstream Vault change)

**Comment by dustin-decker** [comment]
For clarification, in (3) I meant changing the AppRole plugin paths so I can safely glob the roles in the backend mount (for obtaining secret-id) without granting permission to create new role.

Thanks for looking into this. I'll continue on with option (1) or (3).
