### ISSUE TITLE
Display auth method description on Vault UI Login Page

### ISSUE THREAD

**Issue by sidewinder12s** [hashicorp/vault#6120]
**Is your feature request related to a problem? Please describe.**
Our end users may not know what different authentication methods are in Vault. 

**Describe the solution you'd like**
Display the auth method description as a tool tip or something similar on the Vault login screen.

**Describe alternatives you've considered**
Easiest for end users is to just disable other auth methods that might be confusing but that is pretty heavy handed. 

Sorta related to #4307, #6067, #5292

**Comment by aphorise** [comment]
In the current (1.12.x) versions it does display description on the secrets listing view of the UI as per the screenshot below.

![image](https://user-images.githubusercontent.com/974854/199501472-c8fe8127-9afd-48a4-bb13-8a3454756db1.png)

hey @sidewinder12s - I'm curious if you've revisited this request since raising it or are you ok to close?

**Comment by sidewinder12s** [comment]
Sounds good to me, I haven't upgraded/used the UI in a while.

**Comment by aphorise** [comment]
> Sounds good to me, I haven't upgraded/used the UI in a while.

Me too 😃 I almost never use the UI - although it's worth checking once a while as there are on-going improvements with each minor release.
