### ISSUE TITLE
one time token is unable to create credentials to postgresql backend, but returns credentials

### ISSUE THREAD

**Issue by lassizci** [hashicorp/vault#615]
This issue is probably the same with some other backends as well:

```
$ vault token-create -use-limit=1 
Key            	Value
token          	bed62997-8834-b458-cebe-e738e2b92aff
token_duration 	0
token_renewable	false
token_policies 	[root]

$ vault auth -no-verify bed62997-8834-b458-cebe-e738e2b92aff
Authenticated - no token verification has been performed.

$ vault read postgresql/creds/test
Key            	Value
lease_id       	postgresql/creds/test/63dadd66-81db-2478-5e2b-b62a5a598507
lease_duration 	3600
lease_renewable	true
password       	45a6ffcb-4b3c-13a8-9f0b-8cbd89d176a2
username       	token-c3a7bf3e-b21a-dde7-5a9d-3107693e398f
```
However, the user hasn't been created in postgresql backend, so error should be returned instead. But when I create token with ```-use-limit=2``` the database user is created.

**Comment by jefferai** [comment]
Authentication is a use of the token, so this is correct behavior.

You don't need to be authenticating there... you already have the token you want to use.

**Comment by lassizci** [comment]
If authentication is supposed to use the token, shouldn't I get permission denied on ```vault read postgresql/creds/test```

**Comment by jefferai** [comment]
I actually don't understand what the issue you're having is. Can you explain further?

**Comment by jefferai** [comment]
What version of Vault are you using? If master, does this happen in 0.2?

**Comment by lassizci** [comment]
This was with master, so I got confused as the behavior is different with 0.2. With 0.2 one could create a token that has use-limit of 1 and then use it to create dynamic secret (i.e postgresql user).

With master the database user was actually created but since the token gets revoked when it's used, it also removes the user instantly which led me thinking it just returns generated username and password without creating the user. So yeah, it kind of works as expected, just very different from 0.2.

**Comment by jefferai** [comment]
There was a change since 0.2 that fixed a lot of real problems, but seems to have caused this -- which seems like more of a UX issue than a real technical one (but still a definite issue).

In 0.2, tokens uses were decremented before an operation happened. While for many purposes this didn't matter all that much, it meant that for one-time-use tokens you could often end up being able to actually use the token for its intended use before it was revoked.

In master, token actions are carried out and then the uses left value is decremented, with possible revocation as a result. This is more correct behavior, but as you saw, this now leads to a user experience issue.

The right way to fix this might be to check whether the response from the backend contains a Secret, and if so, check the existing uses; if it is at 1, return an error message instead. This would allow other backend operations (changes to a role, for instance) to proceed normally.

**Comment by lassizci** [comment]
I'm not sure if there's anything to fix after all, but sure the ux could be improved. This pretty much works now as documented in https://vaultproject.io/docs/concepts/tokens.html while earlier it didn't.

**Comment by jefferai** [comment]
@lassizci I'm working on a fix right now; I will ping you when it's done if you would like to test.

**Comment by lassizci** [comment]
Sure, I will help testing. But this was pretty much my own mistake of relying on undocumented behavior :)

**Comment by jefferai** [comment]
Should be fixed in 112a419...let me know!

**Comment by lassizci** [comment]
That gives a nice input, and probably helps avoiding confusion. Cheers!

**Comment by jefferai** [comment]
Great!

**Comment by sirlatrom** [comment]
I'm sorry for bumping this old issue, but from my simple perspective, it appears that specifying `-use-limit=1` is now not useful at all with the UX in 0.3.1, contrary to how one would think about a 'one-use token'.

Example:

    $ vault version
    Vault v0.3.1
    
    $ export VAULT_ADDR=http://127.0.0.1:8200
    $ export VAULT_TOKEN=<root-token>
    $ vault write secret/foo bar=baz
    Success! Data written to: secret/foo

    $ vault token-create -use-limit 1
    Key             Value
    token           d087764d-4da2-3c12-40a6-3ea15adc6b81
    token_duration  0
    token_renewable false
    token_policies  [root]

    $ export VAULT_TOKEN=d087764d-4da2-3c12-40a6-3ea15adc6b81
    $ vault read secret/foo
    Error reading secret/foo: Error making API request.

    URL: GET http://127.0.0.1:8200/v1/secret/foo
    Code: 400. Errors:

    * Secret cannot be returned; token had one use left, so generated credentials were immediately revoked.

Maybe I haven't read the docs thoroughly enough, but is there then any use case for a single-use token (in the sense of setting `-use-limit=1`)?

**Comment by jefferai** [comment]
Going to reopen this for 0.4. We need to special-case the `generic` backend since it doesn't generate credentials, and make sure `transit` is good too.

@sirlatrom In most cases specifying a count of 2 or more makes sense (like for `cubbyhole` authentication), but `generic` and `transit` are still use-cases for single-use tokens -- this needs to be fixed though  :-)

**Comment by lassizci** [comment]
for at least generic use-limit=2 results actually in a one time token: on first use the token is able to read the secret and on the second time it returns an error. But I agree that this is a bit confusing when both dynamic and generic secrets are used since it's easy to think that one time token would work the same way.

**Comment by jefferai** [comment]
Yeah, it's a hard problem. When a token is revoked, it revokes credentials, so use-limit=1 doesn't make sense for most credential-gathering use-cases. But there are definitely useful use-cases for transit and generic, so those should work.

**Comment by jefferai** [comment]
@lassizci Regarding your previous comment about use-limit=2, check out the "no-verify" flag to token-create. Generally when using a use-limited token you'll want to set that.
