### ISSUE TITLE
Allow policy template interpolation in path body

### ISSUE THREAD

**Issue by jlindsey** [hashicorp/vault#6202]
**Is your feature request related to a problem? Please describe.**
I have several gRPC services that use client certs for authentication, and use the Vault PKI provider to issue these certs. I have an intermediary service that brokers this login flow to ensure that users can't issue themselves certs for names other than their own. This service would be obviated if there were a way to craft a policy such that users can only generate certs with `common_name` set to their own identity name.

**Describe the solution you'd like**
The ability to use policy templates within the body of the `path` block instead of just in the key:

```hcl
path "test_auth/issue/example_role" {
    capabilities = ["update"]
    allowed_parameters = {
        "common_name" = ["{{identity.entity.name}}"]
    }
}
```

**Describe alternatives you've considered**
I have considered using some orchestration tool to automatically generate policies per-user and per-service that has the allowed `common_name` hardcoded, but this is even more cumbersome than a broker service.

**Comment by jefferai** [comment]
This is actually quite complicated to do it outside keys, and we don't really encourage use of allowed/denied parameters since they are rather fragile.

We do allow plugins access to the request identity so really the way to solve this is to add the support directly into pki. Just waiting for us to get time, or someone interested.

Closing as we have no plans to fulfill the request this way.
