### ISSUE TITLE
Support custom STS region selection in Vault CLI call

### ISSUE THREAD

**Issue by krish7919** [hashicorp/vault#6234]
**Is your feature request related to a problem? Please describe.**
I have configured Vault to use the `config.STSEndpoint` of `https://sts.eu-central-1.amazonaws.com`, reference: https://github.com/hashicorp/vault/blob/fb89af7cfa66b033951fa4c44ff31718537f094f/builtin/credential/aws/path_login.go#L1185

However, when trying to test my AWS Auth configuration using the Vault CLI, I get the error message `Credential should be scoped to a valid region, not 'us-east-1'.`

This seems to be the result of using a default STS config in the `GenerateLoginData` method, which defaults to `us-east-1`.

There is no option in the CLI to add a region or a custom STS URL when using it to authenticate to AWS, reference: https://github.com/hashicorp/vault/blob/master/builtin/credential/aws/cli.go#L27

**Describe the solution you'd like**

Add a CLI option that a user can provide while executing the command.

**Describe alternatives you've considered**
I have set the `AWS_REGION` and the `AWS_DEFAULT_REGION` env vars, but they don't seem to be used at all by the Vault CLI.

**Comment by tyrannosaurus-becks** [comment]
@krish7919 hi! Can you post the CLI command you're using to test it? Of course redacting any values that are secret.

**Comment by tyrannosaurus-becks** [comment]
Nevermind! I think I figured it out. Check out the linked PR and comment if you get a chance.

**Comment by jhnlsn** [comment]
Could the PR also be extended to the code here?  https://github.com/hashicorp/vault/blob/master/builtin/credential/aws/backend.go#L276

When creating a role using the following command:
`vault write auth/aws/role/auth_test auth_type=iam policies=auth_test bound_iam_principal_arn=`

we will sometimes get a `RegionDisabledException` due to the fact that not all regions have STS enabled in our accounts.  it would be nice to be able to control the region here:
https://github.com/hashicorp/vault/blob/451f2a6f36f7d14b14a218b63e90d2f2c603a9fe/builtin/credential/aws/backend.go#L236

We also get the same error mentioned in this ticket when configuring the STSEndpoint and trying to create a role.
