### ISSUE TITLE
Vault default policy overrides entity policies

### ISSUE THREAD

**Issue by megakoresh** [hashicorp/vault#6299]
If I have some rules in default policy and then expand them in another, the other policy will be overridden with whatever's in default.

**To Reproduce**

Default policy with the following content:

```hcl
path "sys/leases/renew" {
  capabilities = ["update"]
}

# Allow looking up lease properties. This requires knowing the lease ID ahead
# of time and does not divulge any sensitive information.
path "sys/leases/lookup" {
  capabilities = ["update"]
}
```

Provisioner policy with the following content:

```hcl
# Manage leases across Vault
path "sys/leases/*" {
  capabilities = ["create", "read", "update", "delete", "list", "sudo"]
}
```

Assign provisioner policy to a user that logs in from some other backend via an external group:

```shell
vault write identity/group name=provisioner policies=provisioner type=external
vault write identity/group-alias name=provisioner-ldap mount_accessor="$(vault auth list |grep ldap |awk '{print $3}')" canonical_id="$(vault read -field=id identity/group/name/provisioner)"
vault write auth/ldap/users/megakoresh@memes.co groups=provisioner-ldap
```

**Expected behavior**

Once `megakoresh@memes.co` logs in, they should have full access to `/sys/leases`.

**What actually happens**

```
megakoresh@dankmemes:~$ vault token capabilities /sys/leases/lookup
deny
```

This prevents UI from being able to visually preview various leases as well as performing administrative tasks.

**Environment:**
* Vault Server Version (retrieve with `vault status`): 1.0.2
* Vault CLI Version (retrieve with `vault version`): 1.0.2
* Server Operating System/Architecture: Centos 7.5

**Comment by jefferai** [comment]
You can simply remove the statements from the default policy, or you can add the explicit paths (rather than using a prefix) to your provisioner policy.

**Comment by megakoresh** [comment]
> You can simply remove the statements from the default policy, or you can add the explicit paths (rather than using a prefix) to your provisioner policy.

Excuse me, but how is that a solution? I need the ability to give everyone more restricted access, but administrators should have more broad privileges. I can't image this is an uncommon use-case. And in every situation I would have to replicate the whole default policy in addition to permissions specific to admins? @jefferai

**Comment by jefferai** [comment]
The problem isn't what you want, it's how you're doing it. Specific path rules take precedence over wildcard rules, and policies' paths are combined together. If you don't want to remove that path from default, just split out your wildcard path into the few specific API endpoints and the paths will compose their grants.

**Comment by megakoresh** [comment]
> The problem isn't what you want, it's how you're doing it. Specific path rules take precedence over wildcard rules, and policies' paths are combined together. If you don't want to remove that path from default, just split out your wildcard path into the few specific API endpoints and the paths will compose their grants.

Yes I understand that, it's just a giant pain and doesn't scale at all, which is why I assumed there would be a better way (vault has otherwise been fantastic in all aspects so far).

As vault grows to have many different policies and rules, having to split wildcard rules to match specificity of the most detailed path on any policy that a user may have, either assigned automatically or manually, makes policies unmaintainable. It is good to be aware that this limitation is by design though.

**Comment by jefferai** [comment]
The reason it's this way is it's pretty hard to go the other way. Imagine that you have a path statement granting access on `sys/*` with `read` and `list` capability and you want to exclude a path -- let's say you want people to be able to list policies but not read them, so you create a path statement at `sys/policies/acl` with only `read`. If we were to compose both the longest prefix match and the wildcard match, since capabilities are access grants there's no obvious way to communicate that a privilege should be dropped. Would it be to use `deny, read` as the capabilities? That might be doable but seems pretty odd. What if multiple different prefix-based policies attempt to do the same thing, e.g. you also have a path statement at `sys/policies/*` that does a `deny, create`? What's an understandable way to reconcile this? We could maybe work forwards from least specific to most and honor `deny` calls as we go, but it seems very hard to reason about.

Whereas if we use strict longest prefix matching, it can make writing policies more onerous but the path to resolution is extremely clear.

**Comment by megakoresh** [comment]
Classic code maintenance vs user convenience scenario. I understand. Usually systems solve this problem using an index or weight system attached to policies that determine their precedence.

If vault can't have that for one reason or another, then we'll just have to work around the issue by keeping deployments small-scale, where every team would have to deploy their own vault.

That's fine for open-source version, though I am not sure how it would play with vault enterprise (you have one license, so technically you have one vault?). I am not sure if vault is supposed to be used at large scales, but I personally do not see any way to run it at scale with this kind of limitation. Maybe I am missing something, or maybe it's worth opening a feature request for policy precedence. Not sure what the code owner's stance is on this issue.

**Comment by jefferai** [comment]
Usually large enterprises handle this by not using wildcard statements, since they _want_ to have very tight control over exactly what privileges are given to specific users. Or, if they use a wildcard and are overriding it for a set group of people, they simply enumerate the paths involved. This is not a common pain point we hear from our large customers.

**Comment by megakoresh** [comment]
> Usually large enterprises handle this by not using wildcard statements, since they _want_ to have very tight control over exactly what privileges are given to specific users. Or, if they use a wildcard and are overriding it for a set group of people, they simply enumerate the paths involved. This is not a common pain point we hear from our large customers.

Then they orchestrate policy creation, without doing it manually (well if they live in 2019 anyway, I can't imagine building anything that would involve a ticket que and some person manually typing in commands for every use-case). I think this could be a good addition to the documentation and/or learning tracks on the main website. I am supposed to present Vault as a secret managemnet solution in our company and the questions of maintainability and operational scalability are inevitable.

So the takeaway is to either use one large-scale deployment with orchestration, or some kind of "Vault as a service" thing, where each team uses own standardized vault deployment. Both options seem viable.
