### ISSUE TITLE
Vault servers are stateful regarding seal/unseal

### ISSUE THREAD

**Issue by bkeroackdsc** [hashicorp/vault#634]
Using the S3 backend with three vault servers behind a load balancer for HA, the servers appear to have independent state during the unsealing process.

For example, if the master key is split into three shards and the unseal PUT requests happen to hit different servers, you can end up with some servers returning ``sealed: true`` and some ``sealed: false``.

Vault should store all state in some persistent backend so load balancing works as expected.

**Comment by bkeroackdsc** [comment]
Turns out they are stateful regarding basically all config...

**Comment by jefferai** [comment]
From the documentation:

`s3 - Store data within an S3 bucket S3. This backend does not support HA.`

You are not running a HA cluster; you are running three totally separate Vault servers.

**Comment by bkeroackdsc** [comment]
@jefferai And yet they all can share the S3 backend fine, which begs the question why they can't also have the same configuration/auth backend. IOW, why can't S3 work for HA? Or perhaps put another way, why can't the configuration/auth datastore be independent from the secrets datastore? (to allow stateless servers)

**Comment by jefferai** [comment]
HA either can't work for S3 because S3 doesn't provide the necessary atomic locking capabilities on keys, nobody has coded in the necessary support using S3's atomic locking capabilities (if they exist), or both. I'm not sure which it is, but I do know that it is not currently an HA-supporting backend. Attempting to use it as if it does support HA will result in undefined, probably very bad, behavior.

There isn't any such thing as a "configuration/auth" datastore. There is a single datastore. It is possible that in the future logic could be abstracted such that the datastore and the cluster coordination happen over separate mechanisms, but this is not the current situation.

I don't really follow your comment about stateless servers. Like most daemons, Vault is not a stateless server, and never will be. it is not a simple application providing CRUD semantics to named resources on disk to anonymous clients.
