### ISSUE TITLE
Add Jose secret backend that replaces JWT backend

### ISSUE THREAD

**Issue by dol** [hashicorp/vault#644]
The recently added JWT backend (#460) was removed due to a lot of work (@6c21b3b69343b17e716dc64b9312bfd2024bb33a) fixing up the backend.

I agree on the removal of the backend. The backend has some flaws and is incomplete:
- The possibility to verify the integrity of a token is missing. Sign and verify are the two building blocks of JWT
- The 'claims' parameter in `/jwt/issue/<role>` is called 'payload' [1] in the JOSE world. See jwt.io or RFC 7519 [1]
- Backend is limited to JWT only. In the JOSE [2] ecosystem JWS [3] and JWE [4] are the building blocks of JWT. A JWT/JWE endpoint is IMHO necessary.
- Missing possibility to change the hashing algorithm assigned to a key. Once a key is added to the backend there is no option to change the hashing algorithm

I don't wont to discourage @ekristen for his work. I think a ~~JWT~~JOSE backend is very usefull.

It would be very much appreciated if a revised version ot the JWT backend brought back to life.
### Minor excursion on the JOSE ecosystem
- JWE (E = encryption) is used to encrypt/decrypt JSON Objects
- JWS (S = signing) is used to sign/verify JSON Objects
- JWT (T = token)
  - representation of claims
  - protected by JWS or JWE
    - types: plain, signed and encrypted

I can recommend this blog post: https://securityblog.redhat.com/2015/04/01/jose-json-object-signing-and-encryption/
### A proposal for a possible future API
- Rename jwt to jose
- Rename claims parameter in `/jwt/issue/<role>` to 'payload'
- Add new endpoint to verify JWS/JWT
  - `/jwt/verify/<role>`
- Add new endpoint to decrypt a JWT/JWE
  - `/jwt/decrypt/<role>`
- Add possibility to change signature algorithm
  - Rename 'algorithm' parameter in `/jwt/roles/` to 'default_sign_algorithm'
  - Add new optional parameter 'sign_algorithm' to `/jwt/issue/<role>`
- Add new optional parameter 'jwt=<boolean> (default: true)' to `/jwt/issue/<role>`, `/jwt/decrypt/<role>` and `/jwt/verify/<role>`
  - `/jwt/issue/<role>` will add the default parameter used in JWT
  - `/jwt/decrypt/<role>` and `/jwt/verify/<role>` will perform a claims validation
- Add new endpoint that returns the public key as JWK
  - `/jwt/role/<name>/publickey`
- Add new optional parameter 'mode=<plain|sign|encrypt> (default: sign)' to `/jwt/issue/<role>`
  - This is only possible with the parameter 'jwt=true'
  - In some rare cases encrypting a JWT is used
- Support 'Nested JWT' (rare usage)
  - From the RFC 7519: A JWT in which nested signing and/or encryption are employed. In
    Nested JWTs, a JWT is used as the payload or plaintext value of an
    enclosing JWS or JWE structure, respectively.

For proper JOSE support I recommend using https://github.com/square/go-jose .

[1] https://tools.ietf.org/html/rfc7519
[2] https://tools.ietf.org/html/rfc7165
[3] https://tools.ietf.org/html/rfc7515
[4] https://tools.ietf.org/html/rfc7516

**Comment by jefferai** [comment]
We'll revive something for 0.4. The big overarching problem with the JWT backend as-is (which I pushed up to a branch for keeping for the moment) is that it allows the caller to set any claim values they like, including issuer and issued_at. An issuer that simply signs whatever a client tells it to is not an issuer you can trust, making it functionally useless for Vault's purposes.

I don't have time to fix it before 0.3 so we took it out for the moment, but plan to put something back. Thanks for these suggestions on the API and the link to go-jose, they'll be very useful!

**Comment by dol** [comment]
I you need any second opinion on the topic ring me. I'm happy to help.

As always: We currently have a use case where this backend would have been very beneficial. ;-) But with the requirement of generating JWS instead of JWT.

**Comment by ekristen** [comment]
@jefferai why not just open a ticket and ask me to fix, since I originally submitted this? I need JWT in Vault. 

> The big overarching problem with the JWT backend as-is (which I pushed up to a branch for keeping for the moment) is that it allows the caller to set any claim values they like, including issuer and issued_at. 

It is not useless in its current state. You the admin of vault controls who and what has access to vault. I see the point you are making however and if that is a requirement then let me fix it. Lets not just yank it out. As for setting other claims, you do have to be able to support dynamic claims but we can blacklist some.

To the point that there is no verification method, that can be fixed too! That was an oversight on my part as I was thinking purely about the RS and EC algorithms and how there is a public key to be able to be used **outside** of vault to verify and in my use cases I was going to be verifying outside of Vault. I wanted vault for the secure storage of the private key and to prevent needing to give it to my developers. Where as with the HS signing algorithms its a shared key, so I see the need for verification.

I disagree on being able to change a signing algorithm for a role. The signing algorithm is set at role creation time because the key has to be verified as usable by the algorithm.

@jefferai what do you need for this to be added back in for 0.3?

**Comment by jefferai** [comment]
> why not just open a ticket and ask me to fix, since I originally submitted this? I need JWT in Vault.

There isn't time to fix it, vet it, and test it before the release.

>  I need JWT in Vault.

You are welcome to continue using your code in your own build, but the code as-is will not be an upstream Vault feature.

> It is not useless in its current state. You the admin of vault controls who and what has access to vault.

Access in Vault is done by prefix matching. That's why backends have roles with administratively-configured values, and then tokens are given policies allowing access to credentials identified, in the URL path, with a role.

There is no way for an administrator to blacklist certain options or fields for specific client tokens, because there isn't a way to know anything about the token other than if it can call a function, it has access. That means that as-is, the backend allows any caller to generate a JWT with absolutely anything they want for the values. That may fit your use-case but it doesn't at all align with Vault's architecture or goals.

There is no quick fix, and there is unfortunately no time go through a rewrite, review, and test cycle before 0.3.

**Comment by ekristen** [comment]
I don't believe I'm the only one looking for the feature.

You said there is no quick fix. Could you please list out the things that were wrong with the current iteration that caused it to be yanked out? I would like to work on the fixes.

> There is no way for an administrator to blacklist certain options or fields for specific client tokens, because there isn't a way to know anything about the token other than if it can call a function, it has access

I was not suggesting blacklisting as an option. You mentioned that being able to set `issuer` and `issued_at` and I agree, removing the ability to set those other than at the role creation time is an easy fix. If setting all the "default" claims that are configurable by the role is a problem an issue time, that's an easy fix too.

However the ability to set custom claims is a must, but the overriding the defaults can be prevented.

**Comment by ekristen** [comment]
I apologize if I came off as defensive.  @dol thanks for your suggestions.

**Comment by adamlc** [comment]
Its a shame this got yanked, but I do agree it probably needs some more thought. Would be great to see this back in :+1: 

JWTs are great and it would definitely be awesome to have them in vault!

**Comment by ekristen** [comment]
Agreed, needs some work, just bummed that this wasn't brought up before so it could be fixed for 0.3. @jefferai whenever you can provide a list, that would be great. Thanks!

**Comment by jefferai** [comment]
Vault's model is zero-trust. An administrator needs to be able to completely define what a client can do, because the point is that there is no human in the loop. Once a token is signed or a cert issued, other entities must trust it at face value. This is simply not possible when a client holds all of the power.

If a CA allowed any requestor to get a certificate for google.com or facebook.com, nobody would trust anything that CA issued, ever. You can't. That's the root of when I said that as-is it was "functionally useless", and I apologize if that was harsh wording; I simply meant it literally, as in "if Vault issues these tokens you can't trust Vault".

(Also, I apologize for not reaching out to you prior to this -- I was definitely going to, but between readying the release and gearing up for HashiConf I ran out of time yesterday.)

I want to be clear that I think that having JWTs in Vault is a great use case and I'm fully supportive of the idea, we just need to go back to the drawing board a bit and figure out how to make it work within the Vault model. I'd start with figuring out a decent API...a lot of the code is there, and can be repurposed (or maybe as @dol suggested go-jose could be used). I'm happy to work on this with you, and I think @dol  and @adamlc would probably both be happy to as well.

I would suggest taking a look at the API for the PKI backend (https://vaultproject.io/docs/secrets/pki/index.html). There are a lot of similarities in terms of the types of things promised by signed JWTs and signed TLS certificates, and so there might be some good ideas in there as to how to lock things down, specifically if you look at which types of things are relegated to role definitions and which are client-set options at issuance time.

**Comment by jefferai** [comment]
> Agreed, needs some work, just bummed that this wasn't brought up before so it could be fixed for 0.3.

Yeah, I know that kind of sucks. I'm sorry about that. This was merged prior to me working on Vault full-time, and there's been so much other stuff going into 0.3 that I didn't go back and take a look at it. Here's a lesson for you, though: I started to take a good look at it because the acceptance tests were failing  :-)

(Just to be clear, this was not my sole decision to defer it to 0.4; I simply had cause to look at the code and realized that there were discrepancies between how it worked and how Vault is intended to operate. The larger team discussed and decided to defer.)

**Comment by ekristen** [comment]
> I started to take a good look at it because the acceptance tests were failing.

As in these tests? https://github.com/hashicorp/vault/blob/jwt-on-ice/builtin/logical/jwt/backend_test.go

**Comment by ekristen** [comment]
> I simply meant it literally, as in "if Vault issues these tokens you can't trust Vault". 

My basic reasoning for this was a secure place to store the key, I figured if I was giving my developer access to it, I trusted what he was asking him to sign. I wasn't looking at this as Vault is the approval authority or even the place to guarantee accuracy at the time. I just didn't want to have to give 10 different devs access to the private key.

I understand the reasoning around **trusting** vault and we can easily make the claims defined by the RFC set in the role and unable to be changed, however we still need the ability to add user defined claims, otherwise its mostly useless. Most JWT have some additional claims that need to be added the define scopes of access or something that the receiving service will use along with verification of the token to provide access.

**Comment by jefferai** [comment]
Yes, although that contains some fixes already. Here's the file before my changes: https://github.com/hashicorp/vault/blob/b2da14c3e88b65fe878d255d5f64b4f54d396e7a/builtin/logical/jwt/backend_test.go

**Comment by ekristen** [comment]
RE: tests -- interesting they were all work when I submitted the code originally AFAIK.

**Comment by jefferai** [comment]
> I understand the reasoning around trusting vault and we can easily make the claims defined by the RFC set in the role and unable to be changed, however we still need the ability to add user defined claims, otherwise its mostly useless. Most JWT have some additional claims that need to be added the define scopes of access or something that the receiving service will use along with verification of the token to provide access.

Sure...but we need to figure out how to properly control those. For instance, maybe roles contain lists of which claims are allowed to be set by a client, so different clients can be given access to different roles based on what claims they might need to set.

I'm going to need to mostly jump off of this for now, but post HashiConf I'll be happy to spend more time working with you to figure out the right way to restructure this. This is set as a 0.4 milestone, it will stay on my radar  :-D

**Comment by jippi** [comment]
:+1:

**Comment by adamlc** [comment]
Any updates on this? :smiley_cat:

**Comment by drawks** [comment]
6 Months later... Would love to see this implemented in some sort of sane way. Being able to use vault to auth against ldap and get a jwt issued with role memberships populated into the claims would be awesome!

**Comment by ekristen** [comment]
+1 to getting this implemented.

**Comment by gilgoodridge** [comment]
+1 for getting this implemented.

**Comment by ekristen** [comment]
At the request of @jefferai I've put together an RFC for a JOSE backend that is more complete. I've borrowed from the original suggestions of this post along with the work I did originally on the JWT module.

Please see https://github.com/hashicorp/vault/issues/1986 and provide and feedback specific to the proposal. Thanks!

**Comment by jefferai** [comment]
Closing in favor of 1986.
