### ISSUE TITLE
$VAULT_TOKEN not processed when using vault login command

### ISSUE THREAD

**Issue by identitymonk** [hashicorp/vault#6501]
**Describe the bug**
On V1.1.0, when using _vault login_ command in an environment set with $VAULT_TOKEN, the vault instance still asks for a token to be provided inline. If the value provided is different from the one set in $VAULT_TOKEN, the vault instance opens a session with the identify of the token provided inline despite warning of:

```
WARNING! The VAULT_TOKEN environment variable is set! This takes precedence
over the value set by this command. To use the value set by this command,
unset the VAULT_TOKEN environment variable or set it to the token displayed
below.
```

**To Reproduce**
1. Set $VAULT_TOKEN environment variable to root token value
2. Execute _vault login_ command
3. System asks for token value despite the fact the $VAULT_TOKEN is set:

```
Token (will be hidden):
```
4. Provide a non root token value
5. Vault instance open session as non root context with warning of expected behavior that does not reflect reality

```
WARNING! The VAULT_TOKEN environment variable is set! This takes precedence
over the value set by this command. To use the value set by this command,
unset the VAULT_TOKEN environment variable or set it to the token displayed
below.

Success! You are now authenticated. The token information displayed below
is already stored in the token helper. You do NOT need to run "vault login"
again. Future Vault requests will automatically use this token.

Key                  Value
---                  -----
token                s.wxPIoXXXXXXXXXXXXXXXXXXXXf9LJhH
token_accessor       BLYTSo4zqul1laTNh90IRcUr
token_duration       264h24m48s
token_renewable      true
token_policies       ["default" "pki_services"]
identity_policies    []
policies             ["default" "pki_services"]
```
This can be reproduced by setting a non root token in $VAULT_TOKEN and executing _vault login_ command providing the root token inline. The session is open in the root context  with warning of expected behavior that does not reflect reality.

Only way to use $VAULT_TOKEN is to execute the command as  _vault login token=$VAULT_TOKEN_. If this is the official way, then the warning message should be removed and the documentation updated. Otherwise, there is a bug.

**Expected behavior**
Being connected within the session of the token provided through the $VAULT_TOKEN environment variable when I execute  _vault login_ or  _vault login token=<different value than $VAULT_TOKEN>_ as described in warning message and documentation.

**Environment:**
* Vault Server Version (retrieve with `vault status`): 1.1.0
* Vault CLI Version (retrieve with `vault version`): Vault v1.1.0 ('36aa8c8dd1936e10ebd7a4c1d412ae0e6f7900bd')
* Server Operating System/Architecture: CentOS Linux release 7.6.1810 (Core) / AMD64

Vault server configuration file(s):

```
ui = true

storage "consul" {
  address = "127.0.0.1:8500"
  path    = "vault/"
}

listener "tcp" {
 address     = "192.168.56.102:80"
 tls_disable = 1
}

```

**Additional context**
I found this when using the docker image of vault to test some vault scripts

**Comment by kalafut** [comment]
Hi. The warning is accurate, and your stated expected behavior is the current behavior. The CLI login process will have written your new token out to ~/.vault, and it will be used if $VAULT_TOKEN isn't set. The description of the token is for the one that was just created/stored. But as long as $VAULT_TOKEN is set, it will take precedence. For example, after step 5 in your process, subsequent CLI commands will still have root capabilities as long as $VAULT_TOKEN is set to root. You can verify this by attempting a command that requires root and having it succeed.

**Comment by identitymonk** [comment]
Hi,

Thanks for the explanation. So I understand that this is less critical than I feared.

Now what is the purpose of login in if it has a different behavior than all the others command in an $VAULT_TOKEN set environment? Just checking the credentials?

I keep scratching my head to the purpose of such a different behavior and the Warning is not so clear"

Thanks

**Comment by kalafut** [comment]
`vault login` is going to facilitate authenticating via some method. In the case of "token" auth (the default), the operation is very simple, because you already have the token so the CLI will just lookup the token and display information about it, and write it out to ~/.vault-token. But if you did something like `vault login -method=github`, it will use the GitHub auth process to actually creates a new token, which will be returned and saved to file. Many auth backends have an interface like this.

The warning is useful because, for example, I rarely have $VAULT_TOKEN set when doing a lot of CLI operations. I'm using `vault login` to change my authentication. If I did happen to have $VAULT_TOKEN set, those changes would be having no effect... hence the warning.
