### ISSUE TITLE
no overwrite secret kv2 api

### ISSUE THREAD

**Issue by FritschAuctores** [hashicorp/vault#6510]
**Describe the solution you'd like**
Just insert a new password via api

**Describe alternatives you've considered**
Read all passwords and write all back

**Explain any additional use-cases**
Insert a new password to a user without delete all exist vaules

There is no update discribed:
https://www.vaultproject.io/api/secret/kv/kv-v2.html#create-update-secret

**Comment by catsby** [comment]
Hello - the update call is the same as the create call, meaning they are both `POST` calls to the endpoint `/secret/data/:path`, where `:path` is the key path. The options are identical for both calls.

Please let us know if there's anything else we can clarify here.

**Comment by FritschAuctores** [comment]
Thanks for answer, what ist the Sample Payload for update only one value?

With
```
{
  "data": {
      "foo": "bar"
    }
}
```
I create a new Version of the Secret, if there another value in the same path, it will archived.

**Comment by catsby** [comment]
Hello - 

I believe you're talking about the contents of the `data` map in the payload? The API itself does not support `PATCH`, however the command line does (albeit undocumented). If the command line is an option, this should work:

    $ vault kv patch secret/data/<path> key=<new value>

The CLI client will handle merging and updating the data, and then attempt to `PUT` those values using the [cas](https://www.vaultproject.io/api/secret/kv/kv-v2.html#options) options.  

Unfortunately the API itself does not support `PATCH`, so in order to update a single key in the Secret's data users must read the current values and construct an updated data map, and then call the `PUT` endpoint for that secret. It is recommended you use the `cas` option as well, to prevent updating data that may have changed since reading. 

I'm going to close this issue for now, but please let me know if you have any other questions.

**Comment by FritschAuctores** [comment]
Too bad that this does not work. Thanks for answer.

**Comment by dataviruset** [comment]
It would be great if Vault could support patching of some key values. It feels insecure that I need to grant read+update permissions to do a patch operation.
