### ISSUE TITLE
pgpkeys binary or base64?

### ISSUE THREAD

**Issue by mattstep** [hashicorp/vault#653]
The new -pgpkeys parameter for rekeying and initializing is advertised as being for base64 encoded keys on https://www.hashicorp.com/blog/vault-0.3.html and appears to be for binary format keys in the help for the rekey/init commands in vault. Base64 is probably easier than binary since most keys seem to be shared in base64.

**Comment by jefferai** [comment]
It's base64. From the docs for init/rekey:

"The keys must be base64-encoded from their original binary representation."

Perhaps the CLI output help is confusing...I'll take a look.

**Comment by mattstep** [comment]
Actually, to get the CLI working, I had to have them in binary. It wouldn't work correctly with base64.

**Comment by jefferai** [comment]
Yes, was just going to mention that. The CLI reads in the binary key files. But it's passed B64 to the API.

**Comment by mattstep** [comment]
Yeah, any reasons to do binary with the CLI? I think it makes alot more sense to just use B64 everywhere...

**Comment by jefferai** [comment]
Yes, to avoid users having to convert their binary keys into B64 just to pass them into Vault. For most users, this will save a step. But you can't pass binary data around in JSON APIs, so it gets encoded.

A future enhancement could be to attempt reading the file, and if it's not a valid key, attempt B64-decoding and try again.

**Comment by mattstep** [comment]
It's way easier to get a B64 encoded public key via a keyserver or with keybase.io these days...

**Comment by mattstep** [comment]
I havent had someone send me a binary public key in a while actually.

**Comment by cornfeedhobo** [comment]
I can not recall the last time I passed around a binary key.
FWIW, I would lean towards base64 public keys. Or maybe an additional flag to support it?

**Comment by jefferai** [comment]
It's not a question of passing around binary keys. If you already have the public keys on your keychain, regardless of how you got them, gpg generally exports as binary. That was the logic behind this.

Please open a new issue with a feature request if you want support for base64-encoded keys.

**Comment by mattstep** [comment]
I'll probably just use curl since the api supports base64, and it's just one commandline switch for gpg to export, and most of the examples people use online will include that switch.

**Comment by cornfeedhobo** [comment]
@jefferai I will make a PR when I find time, but I was looking for a small discussion on a preferred approach. The logic that an additional step to reach base64 is fairly weak, and doesn't suit common use. Even the GPG page on key exportation says that binary keys are not the norm when sharing. Further, the workflow of keys being local and in a keyring already, assumes that the operator has done the work of importing those keys and then exporting them; which then begs the question of why not just interface with GPG directly instead of binary keys.

So you see, I can not submit a feature request yet as I would like some consensus. Let me know what you (and everyone else) thinks on this topic. I can also be reached on Freenode if you would like to keep the clutter on this issue down.

**Comment by jefferai** [comment]
>  I will make a PR when I find time

It was already done two days ago.

>  The logic that an additional step to reach base64 is fairly weak, and doesn't suit common use. 

No, this doesn't fit *your* use-case. Again, this was designed for when you already have a keychain of public keys -- acquired via importing or keyservers, for instance -- and are exporting the ones that are desired. That is not the same as e.g. sending someone your public key through email. 

>  Further, the workflow of keys being local and in a keyring already, assumes that the operator has done the work of importing those keys and then exporting them; which then begs the question of why not just interface with GPG directly instead of binary keys.

Because not all PGP programs are GPG, because I don't want GPG to be a compile-time or run-time dependency, because existing Go libraries to interface with GPG either don't (and just reimplement functionality) or shell out to the binary which is far from ideal, and because there are no CGO dependencies right now and I don't want to add that for interfacing with GPG as a library.

**Comment by cornfeedhobo** [comment]
@jefferai thanks
