### ISSUE TITLE
auth/aws: support disallow_reauthentication for IAM role-based authentication

### ISSUE THREAD

**Issue by patcable** [hashicorp/vault#6547]
**Is your feature request related to a problem? Please describe.**
One of the things I like about EC2 Role Tag auth is that it only allows one authentication per host. With our workflow, hosts should receive a token on boot (we handle this via chef) and renew it for the life of the machine, or let it age out.

However, when using `auth_type=iam` this behavior does not happen, which means anyone who isn't root on the machine can receive a token and read secrets. 

**Describe the solution you'd like**
For `disallow_authentication=true` to work with `auth_type=iam` as well as `auth_type=EC2`

**Describe alternatives you've considered**
For many of our applications, I can see moving away from a host-based approach where chef puts the key on a ramfs mount, and integrating vault directly into the application. However, there are a handful of apps that we _dont_ write that we rely on chef to query vault and write out config for

**Explain any additional use-cases**
None that I can think of.

**Comment by joelthompson** [comment]
Hi @patcable -- this unfortunately won't be that simple. For starters, there's not really a "right" way to do this, only an approximation. With the `ec2` auth method, you have an EC2 instance ID, and that is guaranteed to be unique. With the `iam` auth method, you have an IAM principal, and what it means to disallow reauthentication isn't well defined. For one, what happens if you delete an IAM user or role and recreate it? Should the old reauthentication blacklist carry over to the recreated IAM users and roles? Second, for IAM roles, should the blacklist be at the level of the role or at the level of the role session name? When you have EC2 instances in IAM instance profiles, the role session name is the EC2 instance ID, but the role session name can be chosen arbitrarily by anybody who can call AssumeRole on the role. So it creates a path to get around the reauthentication blacklist. It doesn't make the feature useless, of course, but I do worry about doing things that can provide users with a false sense of security.

The biggest issue, though, is how to handle legitimate cases where reauthentication is in fact needed (such as an instance being rebooted). There's a bit of complexity in the `ec2` auth method to try to handle the various use cases -- you have `disallow_reauthentication`, `allow_instance_migration`, and nonces associated with a given token. IMHO, one of the bigger advantages of the `iam` auth method is that it doesn't have all this complexity. While it may not be able to handle the use case you have, its relative simplicity makes it much easier to reason about, which makes it easier and more likely for people to implement correctly and securely, and that has a non-trivial benefit associated with it.

Don't get me wrong, I understand your concern about EC2 instances and the general accessibility of the credentials via the instance metadata service. Personally, I'd recommend ensuring your EC2 instances are single tenant, that is, the only users on the machine are authorized to get the credentials via the instance metadata service, and also using the [iptables owner](http://ipset.netfilter.org/iptables-extensions.man.html#lbBP) plugin to block any user that's not root (or any other authorized local user) from being able to access the instance metadata service.

**Comment by patcable** [comment]
Hey, thanks so much for getting back to me here. I was under the impression that the EC2 instance ID was immutable in that auth path, but given that it isn't - the design decision makes perfect sense :+1:. Indeed, our machines are single tenant, but just trying to defend-in-depth. Thanks for the pointer to iptables owner though - I will definitely take a look at that. Cheers!
