### ISSUE TITLE
"Tile" overflow with more than 2 lines on Firefox

### ISSUE THREAD

**Issue by mterron** [hashicorp/vault#6562]
When a "tile" text is over 2 lines, the radio button overflows the frame. It works fine on Chrome.
![image](https://user-images.githubusercontent.com/4434907/55914580-9b4f4480-5c3b-11e9-89d0-504555b2f791.png)

Another example:
![image](https://user-images.githubusercontent.com/4434907/55914536-82469380-5c3b-11e9-8d98-293eda6756b9.png)

**To Reproduce**
1. Click `Enable new engine`
2. See error

**Environment:**
* Vault Server Version (retrieve with `vault status`): 1.1.0
* Browser: Firefox 66

**Comment by Monkeychip** [comment]
Hi @mterron,  

This issue appears to have been fixed in the more recent versions of Firefox.  However, we are also adding a `min-height` css property to help prevent it from happening in the case where the items in the box get bigger, due to things like a longer title name.  That fix will be released in version 1.3.2.

Thank you for the ticket!
