### ISSUE TITLE
Add API call to directly run AWS auth tidy methods, and debug output

### ISSUE THREAD

**Issue by tyrannosaurus-becks** [hashicorp/vault#6617]
This would help with debugging whether and when it's running, and with running ad-hoc tidies.

**Comment by alexandernst** [comment]
Just to add more context, this issue comes from here: https://groups.google.com/forum/?utm_medium=email&utm_source=footer#!msg/vault-tool/xlukrGX0buE/svQMtQwqBQAJ

I have setup AWS auth via EC2. My EC2 instances are able to get a token correctly, but Vault doesn't seem to be deleting the tokes once they are expired. My tokens' TTL is 10s and my safety buffer is 10s. According to @tyrannosaurus-becks the tidy process kicks once every hour, which means that the maximum amount of time between one of my EC2 instances requesting a token and the ID of that instance being removed from Vault's AWS whitelist should be 1h 20s, but that is not the case as I reviewed the IDs that are currently showed as whitelisted, and there are IDs of instances that have been completely gone for almost a day.

**Comment by jefferai** [comment]
Already exists: https://www.vaultproject.io/api/auth/aws/index.html#tidy-identity-whitelist-entries

**Comment by alexandernst** [comment]
@jefferai Please, stop closing issues without actually understanding the purpose of each one. I'm OK with you closing this one, as it's already implemented, but then please reopen #6619 , as that one is completely different.

**Comment by jefferai** [comment]
From 6619:

> A simple alternative would be implementing #6617 and letting the Vault operator to run that command in a cron as often as he/she wants.

It sounded like this solution was acceptable for you.

**Comment by alexandernst** [comment]
@jefferai There is still a bug, as described in #6619 . This (#6617) would be a workaround while the bug gets fixed.
