### ISSUE TITLE
Unable to initialize vault on AWS

### ISSUE THREAD

**Issue by jdevilla20** [hashicorp/vault#6618]
I am trying to install vault by using these instructions:

https://aws-quickstart.s3.amazonaws.com/quickstart-hashicorp-vault/doc/hashicorp-vault-on-the-aws-cloud.pdf

I noticed 2 issues:

1) This deployment is supposed to create 2 ec2 instances, but when running consul members, only one node appears

2) I am unable to run vault init, getting an error code:

ubuntu@ip-10-84-3-27:~$ vault init
WARNING! The "vault init" command is deprecated. Please use "vault operator
init" instead. This command will be removed in Vault 0.11 (or later).

Error initializing: Error making API request.

URL: PUT http://127.0.0.1:8200/v1/sys/init
Code: 400. Errors:

* failed to check for initialization: Unexpected response code: 500

Even when setting my CIDR to 0.0.0.0/0, I still get this issue.

**Comment by michelvocks** [comment]
Hi @jdevilla20,

as far as I know, the AWS quickstart tutorials are maintained by AWS.
You might want to check the AWS support or the AWS forums. If both channels are not helpful, you could also try to ask via our Vault Google group: https://groups.google.com/forum/#!forum/vault-tool

I will close now this issue since this is not a bug but feel free to reopen the issue if you have any further questions. 

Cheers,
Michel
