### ISSUE TITLE
Add ability to move or rename a folder in VaultUI

### ISSUE THREAD

**Issue by andrewsav-bt** [hashicorp/vault#6628]
There is a summarily closed feature request for rename here: https://github.com/hashicorp/vault/issues/2414

This current request is for supporting this feature in **Vault Web UI**. This operation is something that users want to do regardless of atomicity support on the server, therefore the UI should make it easy instead of asking people to write scripts.

Thank you for considering this!

**Comment by aphorise** [comment]
@andrewsav-bt - are you after secrets or authentication mount renmaing? - I'm trying to understand what `folder` is in refernce to here. Can you provide a screen shot?

**Comment by AndrewSav** [comment]
@aphorise not authentication mount, no. let's assume I have some secretes under /path/to/secrets1. Under this path there are several secretes. I want to be able to move all of these to /anotherPath/to/secrets2. Currently this is not possible.

Additionally, a subset of this request is renaming /path/to/secrets1 to /path/to/correctName in place.

![2022-08-31_11-55-15](https://user-images.githubusercontent.com/658865/187563730-c32ef2f3-4e07-4df9-a7e0-0eed2f96a8fa.png)

The highlighted are folders. packer-template/ is also a folder.

This needs to work both for v1 and v2 engines.

**Comment by aphorise** [comment]
@andrewsav-bt oh I see what you are getting at.

However I actually dont think this would be reasonably possible due to the likely recursion as well as the fact that folders / paths here are not like a file system.

Simply put all entries in any path are made in whole and paths are not created separated or managed as such.

It may be a valid ask for some risky `vault secrets rename` operator that's something similar to the script you were referring to. The risk is in the recursion which nonetheless can not be avoided and there's not shortcut single `rename` possible; all the docs in each path and nested path would need traversing and have to some rewrite. You can appreciate on some mounts with millions of records this could take way to long.

**Comment by AndrewSav** [comment]
> However I actually dont think this would be reasonably possible due to the likely recursion as well as the fact that folders / paths here are not like a file system.

IMO this is an implementation details. We are talking about the UI now that present a well known to user folder hierarchy paradigm. It is not unreasonable to expect to be able to rename folders, and this is something that is often requested and needed.

> Simply put all entries in any path are made in whole and paths are not created separated or managed as such.

Yeah it was made clear in the closed issue the OP links to.

> The risk is in the recursion which nonetheless can not be avoided and there's no shortcut single rename possible; all the docs in each path and nested path would need traversing and have to have some rewrite.

Sure, it looks like this is what needs to be implemented then.

>  You can appreciate on some mounts with millions of records this could take way too long.

So are we saying that because on some hypothetical mounts with millions of records it would take longer, we would not implement this for very practical and wide spread cases which do not have this problem?

In UI design long running operations is not new and well understood, there are ways of representing them in UI that have been around for decades. (Progress bar, work queue view, etc). Which one is appropriate is up to you, but this is not some kind of unsolved or unsolvable problem, that's for sure.

Thank you for looking into this.

**Comment by AndrewSav** [comment]
I understand that atomicity cannot be guaranteed, again, this was explained in the linked issue. This is not what this request is for. We do not require atomicity if it cannot be provided.

**Comment by aphorise** [comment]
> So are we saying that because on some hypothetical mounts with millions of records it would take longer, we would not implement this for very practical and wide spread cases which do not have this problem?

Not hypothetical - there are actual operators which would not seriously read or consider the ramification of doing what may a seemingly harmless rename if for example compared to what we're commonly use to with your OS file system.

What's more at a root level of say `B` in `A/B/C/D/E/F/G/H/I/J/something1` the issue is  determining that at `C` there's no further `C1`, `C2` before proceeding to `D` sub-paths and so-fourth. Naturally a traversal is still required which can only be complete once the entire tree is done starting from `something1` which is the only obvious lead in this example and nothing else is known even if you truncate the tree down to an assumed length of 4 depths only (`A/B/C/D`).

> In UI design long running operations are not new and they are well understood, there are ways of representing them in UI that have been around for decades. (Progress bar, work queue view, etc). Which one is appropriate is up to you, but this is not some kind of unsolved or unsolvable problem, that's for sure.

Sure I agree - I'm not saying it's not possible. But there is more merit to doing this programmatically as any failure or issue can be continued by the operator even in cases where Vault may for example have a change in leadership (would break the ongoing renaming).

In any case - there's presently no `rename` let alone a recursive rename in the context of KV1 & KV2 which is what would be needed first before considering any UI.

The UI would also be unable to show any progress given the limitations of recursions and so it would be just like an API request where additional polling / status check on a move would need to be subscripted to (cant determine end).

I personally would only envisage this in the UI with huge warning and triple confirmation modals before allowing you to rename anything on any level thats further than one (+1) 😄

Anyway just sharing my thoughts.

**Comment by AndrewSav** [comment]
> In any case - there's presently no rename let alone a recursive rename in the context of KV1 & KV2 which is what would be needed first before considering any UI.

Jeff made it clear that there will not be any when he closed that issue. The fact that it is not feasible in the engine for design reason, IMO should have no bearing on the UI and convenience

> The UI would also be unable to show any progress given the limitations of recursions

Can you explain that in more details? I admit, that as with many progress estimations you won't be able to provide perfect and accurate information, that's why we have terms like "Microsoft second", etc. But I'm sure you will be able to show _some_ progress.

**Comment by aphorise** [comment]
Hey @andrewsav-bt do you have any [knolwedge of itteration](https://en.wikipedia.org/wiki/Recursion_%28computer_science%29) versus [recursion in computer science](https://en.wikipedia.org/wiki/Recursion_%28computer_science%29)?

Imagine - there is a tree or a partocular branch on a tree that you are dropped on, where you cant even see the entire tree beyond the limited view of the branch immediatly in front of you and someone then asks you how many leaves are there on the tree or the branch you are on? - you get the idea? - progress will not be possible and anything else will just be a fake estimation and without any meaning or accuracy.

What you are asking for - has all the issues and ills that I'd highlighted to which there are no solutions (literally) - including
 - potential failure
 - lack of logical and definitive decisions in the case of failure (leadership change, etc.) - what should it do retry? - if so why or when would it stop if it keeps failing?
 - can end up with an indeterminate amount of time to complete - is it acceptable that a KV secrets path would be non-accessible and needing to take 2+ hours to complete several million entries?
 - how much of the Vault process should focus on this single task? - Vault cant soloy focus on the rename request and not handle end user request - it needs to balance both right? - this would make it a background operation and even more reason to take longer.

I do not see this request materialising any time soon (or perhaps never) due to some of these reasons. Also the effort required in comparison to the limited conveniece it would provide in the UI are not functionality justified particularly as there is room for uncertianties and failures which would yeild the feature useless if operator intervetion is required regardless (like a script); all these things (rate, failure, reporting, etc) can be more easily initiated and control by opreators than somehow expecting the UI to do what's neither feasible nor capable of consistent application for most users in most cases.

**Comment by AndrewSav** [comment]
Thank you for looking into this!

> progress will not be possible and anything else will just be a fake estimation and without any meaning or accuracy.

If you saying that you cannot know how deep a tree is without walking, that's true. You can still report on how many top level (or of there is very few top level, then also second level) "folders" you have processed. No doubt that it won't be accurate, but that's ok, as I mentioned it happens everywhere with progress indication, in many cases it is just not possible to calculate it accurately, but it does not mean you have nothing to display. You still can display how many top level folders you have walked so far and how many left.

> potential failure

you can report it as any failure

> lack of logical and definitive decisions in the case of failure 

inform the user of what happened and why so they could retry if they want. As you test your implementation, you will become more aware on how it behaves and what types of failure you can encounter. With this newly gained insight you will have a better understanding how to support it. Software development is an iterative process, and there are often unknown unknowns upfront. 

> is it acceptable that a KV secrets path would be non-accessible and needing to take 2+ hours to complete several million entries

you know the answer to that, in practice, it is not likely to be acceptable. but your design could account for that and make sure that it does not happen

> how much of the Vault process should focus on this single task? how much of the Vault process should focus on this single task? - Vault cant solely focus on the rename request and not handle end user request - it needs to balance both right? - this would make it a background operation and even more reason to take longer

In all likelihood, it does have to be a background operation, that's fine. 

> I do not see this request materialising any time soon (or perhaps never) due to some of these reasons.

Do me a favour, please discuss this with your senior developer, or, if you are the most senior, with your peer. I do not hold any hopes here, but I'd like to ask that nonetheless, two pairs of eyes are better than one. If your sentiment that the implementation is not straight forward, I totally agree it is not. But it should be possible with careful design and implementation.

I also would like to acknowledge, that software companies decide not to implement something because in their view effort outweighs the benefits, it happens all the time. It also looks that this is what's going to happen here. However I find "the limited convenience" dismissive, in my view it's a basic usability feature. Can you figure out how to make it work? ;)

**Comment by aphorise** [comment]
> you know the answer to that, in practice, it is not likely to be acceptable. but your design could account for that and make sure that it does not happen

Ok but why? all this effort and guestimations just for your convenience? - isnt this just an illusion? 😃 - your hoping that in most cases or rather in your cases it would work - which it could - however there are more general consideration for cases where it will not work for some of these reasons I've highlighted (that are just some immedate thoughts and not everything).

> Do me a favour, please discuss this with your senior developer, 

@AndrewSav sure I will ask a UI team member to take a look - but given the amount of backloged items they have I can assure you even if this was partially possible they will not be keen on doing something that's a partial solution with so many caveates (if fails warn, estimate, bla bla bla) as well as the fact that this would fall way lower on their priority list.

I will ask nonetheless.

**Comment by hashishaw** [comment]
Hello all,

While we certainly understand the pain point here, it is not being considered for the UI to address at this time. I will note that as of 1.10 Vault can accomplish [mount migrations](https://www.vaultproject.io/docs/v1.10.x/concepts/mount-migration) (via CLI) so it is more feasible as a future backend task than the UI.
