### ISSUE TITLE
Tokens Issued with Non-Existent Policies

### ISSUE THREAD

**Issue by theonewolf** [hashicorp/vault#676]
This bug just hit me (and @mallikarjun26) where it is possible to generate tokens with non-existent policies.

I think this should be considered an error for the `token-create` sub-command?

For example, this CLI will happily return to me a token which has no real meaning to my Vault deployment:

```bash
./vault token-create -policy IDONOTEXIST -orphan -lease "48h"
Key            	Value
token          	**Scrubbed token UUID**
token_duration 	172800
token_renewable	true
token_policies 	[IDONOTEXIST]
```

@mallikarjun26 first reported this issue and I helped track it down.  It particularly rears its head if you have capitalization mistakes.  For example, accidentally issuing a token associated with policy 'test' when you really meant 'Test'.

**Comment by jefferai** [comment]
I will have to look into the history of this; it may actually be on purpose, so that you can distribute tokens now to systems but define policies later. The reason I think this may be the case is because you can later change the contents of those policies without needing to reissue tokens; looking at it from one perspective, a non-existent policy is just an empty policy.

**Comment by theonewolf** [comment]
@jefferai I was also thinking that.  I wonder how most people are using it?

I hate the problem with capitalization though :disappointed: (Test vs test).

**Comment by jefferai** [comment]
I'm going to mark this as a `thinking` bug and find a time to bring it up internally. I think this may indeed have been on purpose, so I can't promise a behavior change coming down the line.

**Comment by jefferai** [comment]
We just had an internal discussion. It seems like one of the other reasons for the current behavior is not just to allow defining a policy later, but to allow reasoning about tokens that have policies associated that have since been deleted.

I think the way forward will be the following:

1. Normalize policy names to lowercase
2. Add a Warnings field into responses. This can be parsed from the JSON API, and the CLI can be taught to display them. That way we can return a warning indicating that the policy doesn't exist, while still allowing it to be associated with a token.

**Comment by theonewolf** [comment]
Warnings would be great, and definitely catch this from a UI-perspective.

Not having the warning led to a small headache :smile:.
