### ISSUE TITLE
Expose status code from API errors

### ISSUE THREAD

**Issue by alexodle** [hashicorp/vault#6779]
Similar to: https://github.com/hashicorp/vault/issues/2140, but specifically, an http status code should be exposed via the error object returned by the vault API. Right now, the only way to get the status code is to parse it out from the error string "Code: <status_code>" returned by the API.

*For reference*:
* Error is created here: https://github.com/hashicorp/vault/blob/master/api/response.go#L60

**Comment by jefferai** [comment]
It's actually very complicated to do this because of API breakages. In most cases it would require introducing copies of existing functions to return response structures instead of base underlying data + error, and at that point we might as well v2-rev the Go API. Which it'd be nice to do at some point but is a significantly more burdensome task -- likely this would come from the OpenAPI plus a lot of manual code, but all of that generation and the design of it have to be done.

If you figure out a way to do this without duplicating API calls and without breaking the existing API, feel free to PR something; otherwise if you need the status code you'll have to do your own request handling.
