### ISSUE TITLE
Vault rights for auth methods 

### ISSUE THREAD

**Issue by luuka100** [hashicorp/vault#6876]
Hello,
I’m trying to grant LDAP user rights to list, create, update, and delete auth methods by adding following line to the ACL Policy in Vault:

# List, create, update, and delete auth backends
path "/sys/auth/*"
{
  capabilities = ["create", "read", "update", "delete", "list", "sudo"]
}

When I’m trying to list the auth methods using UI I’m getting following error:

Not authorized
Ember Data Request GET /v1/sys/auth returned a 403 Payload (Empty Content-Type) [object Object]

1 error occurred: * permission denied

Can anyone help to troubleshoot this further?

**Comment by michelvocks** [comment]
Hi @luuka100,

`/sys/auth/*` does not include `/sys/auth`. This should work:
```
path "/sys/auth*" {
    capabilities = ["create", "read", "update", "delete", "list", "sudo"]
}
```

I will close this issue now since it doesn't seem to be a bug. Please use for further questions the mailing list (https://groups.google.com/forum/#!forum/vault-tool) or the new discussion forum (https://discuss.hashicorp.com/c/vault).

Cheers,
Michel
