### ISSUE TITLE
Vault Lease timeout Increase

### ISSUE THREAD

**Issue by venkat1981** [hashicorp/vault#6923]
The Vault Token that is getting generated lease expires by default 2 days  by Default . Is there a possibility to increase the lease time to 6 Months for non root token 

Thanks 
Venkat

**Comment by michelvocks** [comment]
Hi @venkat1981!

Yes. This is possible. Please have a look at our token documentation page which describes how to do that: https://www.vaultproject.io/docs/concepts/tokens.html#token-time-to-live-periodic-tokens-and-explicit-max-ttls

I will close this issue for now since it seems that this is not an issue related to Vault itself. Please feel free to ask further questions via our [Discussion forum.](https://discuss.hashicorp.com/c/vault)

Cheers,
Michel
