### ISSUE TITLE
math: MaxInt64 overflows int on ARM

### ISSUE THREAD

**Issue by nexus166** [hashicorp/vault#6946]
**Describe the bug**

![image](https://user-images.githubusercontent.com/9354925/59917245-c2877680-9421-11e9-812c-014959181565.png)

**Environment:**
* Vault Server Version (retrieve with `vault status`): origin/master
* Vault CLI Version (retrieve with `vault version`): origin/master
* Server Operating System/Architecture: linux/arm
---
See https://github.com/golang/go/issues/23086#issuecomment-371017565

**Comment by jefferai** [comment]
@briankassouf I think this comes down to what you need from NewDelimitedReader. Underneath it all it uses a bufio.NewReader which takes in an int arg, so that's going to be defined as 32 bits on 32-bit platforms as well.

If you think you need more than 32 bits (I wasn't sure if this was during snapshot restore, which I imagine could be more than 4G, or generally reading streaming events, in which case it's likely small) then it probably means forking or writing your own delimited reader that takes in 64 bits and possibly doesn't use bufio.NewReader either. If not, it's easy -- switch to math.MaxInt32.

**Comment by briankassouf** [comment]
I believe the size in enforced per k/v entry not for the full snapshot, so MaxInt32 should be sufficiently large for our needs
