### ISSUE TITLE
Secret storage not that secret with consul backend

### ISSUE THREAD

**Issue by frntn** [hashicorp/vault#697]
:warning: *This is much more a discussion than a real issue as I am pretty sure you already know about this behaviour, but I think it needs some explanation/documentation/...* :warning:

### What I do

Storing some arbitary data to vault using default mounted secret store with consul storage backend

```bash
$ vault write secret/topsecret/service/proxychain servers="socks.somewhere.com|socks.foo.bar"
Success! Data written to: secret/topsecret/service/proxychain
```

Then reading it using vault

```bash
$ vault read -format json secret/topsecret/service/proxychain | jq '.data'
{
  "servers": "socks.somewhere.com|socks.foo.bar"
}
```

### What I get

Checking what has been stored to consul I see that the path is **not encrypted**
```
$ curl -s http://localhost:8500/v1/kv/?recurse | jq '.'  | grep -A4 -B3 proxychain
  {
    "Value": "AAAAAwIaD63dUNymIzOXGXL9PHSnH1xxQO8+JADv+gqlo8kZ7I0A2weoeQBhfxLtlDD9bqMuTiNBQ12BQOb5HFNB+/l/msSukrUrlmVmhA==",
    "Flags": 0,
    "Key": "vault/logical/9e55ac8e-6701-8574-b0c9-339a3a1cc0f1/topsecret/service/proxychain",
    "LockIndex": 0,
    "ModifyIndex": 1312,
    "CreateIndex": 1308
  },
```

### What I expected

Using the `?recurse` and a simple API call, an attacker could easily gather **a lot of information** about the whole system (if everything secrets rely on vault for example) using the paths stored in plain text.

**I would have liked the path to be encrypted in consul too.**

If it's a technical limitation, i.e. we'll have to deal with this behavior, I think we need to add something in the documentation to warn the users that paths should not expose information about the system in this case.  (As for the `Do not run the dev server in production` we cannot miss in the doc)

---
versions: Vault v0.3.1 + Consul v0.5.2
platform: linux 64bits (ubuntu 14.04.3 LTS)

**Comment by armon** [comment]
@frntn We probably do need better documentation around this, but the paths to a secret should not contain sensitive information.

In many cases we obfuscate the path where possible in Vault, but in many cases we need to preserve the hierarchical structure of keys and directories. This is most obvious in the `list` case, as doing a list of a path needs to map deterministically to a path in a backend.

If we encrypted paths, certain operations become vastly more expensive, such as list, since we should need to decrypt all the paths and then filter to the relevant subset, which quickly becomes impractical.

All this is meant to provide some context as to our decision making and how we got to the current situation. I don't mean to suggest things can't be improved, and we are certainly open to ideas as to how this can be approved.

**Comment by frntn** [comment]
Thanks @armon for the context.

I do agree on your statement that *"path to a secret should not contain contain sensitive information"* and I do understand it is a design constraint. I can live with that **as soon as I am aware of it** and most of the implementations should. But still, I think **it should be up to the operator to choose** between *usability / acceptable security* (cleartext paths) and *total security* (obfuscated paths).

Paths are here to set some logic and contains, if not sensitive, at least *relevant information* by design. And any relevant information for the op can be useful for an attacker...

I have a real life use case where the number of secrets are about 10 and where we actually don't want cleartext paths. Today we are obfuscating the paths with naming conventions (`secret/d/p`, `secret/d/c`,...) which is not an ideal solution.

I think more user comments on their real life use cases and more discussion will be necessary, but to start with an (incomplete) improvement proposal I would suggest the following :
* configurable generic secret backend 
```bash
backend "consul" {
  address = "127.0.0.1:8500"
  path = "vault"
  obfuscate_paths = 1                # <-- new optional parameter in backend config
}
``` 
* use obfuscated paths
```bash
$ vault write secret/hello value=world excited=yes
Success! Data written to: xyzxyzxyz  # <-- output obfuscated path
```

Then accept only obfuscated path (accepting cleartext paths too ? may be impractical as you said...)

* show clear text path when read (and similar ouput for the API)
```bash
$ vault read xyzxyzxyz               # <-- use obfuscated path
Key           	Value
_path               secret/hello     # <-- show cleartext path
lease_duration	2592000
excited       	yes
value         	world
```

**Comment by daveadams** [comment]
Another alternative would be to use Consul ACLs to lock down the `vault/` path to only management tokens and the vault servers' token(s), and disallow agent-local or anonymous tokens from reading the `vault/` tree.

**Comment by jefferai** [comment]
@frntn You are definitely correct in that we need better documentation around the fact that keys are not obfuscated; I've marked this as a 0.4 milestone to make sure that happens before the next release.

As @armon indicated, there are a number of scalability and functionality considerations that come with obfuscating paths. Perhaps some day down the line this will be a feature added to the `generic` backend, but in the meantime there are a number of ways that you can gain this functionality with a little work on the client side, as I'll describe below. I also want to echo what @daveadams said: backend physical ACLs or access control can help too.

Here are some ways you can get obfuscated paths:

1) If clients never need to list keys (listing is not supported yet, but will be), because they know exactly which keys they require, you could have clients use a SHA or HMAC hashing algorithm on each key before performing an operation on it.

2) You could round-trip keys through the `transit` backend. You'd have to do a simple string replacement on the returned text (since `:` isn't an allowed character in paths), but you could then use the encrypted value as the key. The benefit to this approach is that since the encryption is symmetric, this would still allow clients with appropriate permissions to decrypt the values and examine the plaintext keys, e.g. after performing a list operation.

**Comment by frntn** [comment]
I do like what you and @daveadams are suggesting.
I'll give it a try asap.

Thanks

**Comment by jefferai** [comment]
@frntn If you try option (2) above, you may want to look into the `datakey` support added to the `transit` backend in 0.3. This is basically a key wrapped by a key. You can then safely distribute the encrypted data key to your services at rest; at run time, they can then load this encrypted value and make a call to Vault to get the unencrypted value of the key (which they store only in memory, and do not persist to disk). Then reading and writing key values is a simple matter of performing an encryption or decryption operation with this unencrypted datakey value.
