### ISSUE TITLE
Postgres should revoke permissions upon revocation

### ISSUE THREAD

**Issue by jefferai** [hashicorp/vault#699]
The Postgres backend drops the created role during revocation, but open sessions are still able to perform queries.

The MySQL backend explicitly revokes permissions first, then drops the user. Open sessions are unable to perform further queries.

The Postgres backend should behave the same way, to ensure that a session that remains open past expiration (for instance, due to a long-running query) is functionally useless.

**Comment by jefferai** [comment]
Fixed by #736

**Comment by J-Walling** [comment]
Excellent! Thank you for the prompt response to this!

**Comment by jefferai** [comment]
No problem :-)

**Comment by jefferai** [comment]
It seems that Postgres does some caching; @J-Walling reports that after revoking privileges users are still able to use PG with their original permissions. This may be some kind of caching, or it may be a bug; my tests were with 9.4.

We should add the ability to:

* Specify a drop/delete SQL statement
* Force terminate connections

It would also be good, when thinking about adding these, to think about rolling the current SQL backends to the role framework when it's out and combine the various SQL backends into one (basically, anything using `database/sql`). There is probably enough code that can be shared to make it worthwhile, and the type-specific stuff can be farmed out to libraries.

**Comment by mwielgoszewski** [comment]
I'm noticing similar problems with roles created by Vault being left behind. My pg.log shows entries along the lines of:

~~~
STATEMENT:  DROP ROLE IF EXISTS "xxx";
ERROR:  role "xxx" cannot be dropped because some objects depend on it
DETAIL:  privileges for database abc
        3 objects in database abc
~~~

I am using the following SQL template to create roles. Additional `GRANT SELECT`'s for tables/columns specific to our schema are appended depending on the access requested.

~~~
CREATE ROLE "{{name}}"
    WITH
    LOGIN
    PASSWORD '{{password}}'
    CONNECTION LIMIT 1
    VALID UNTIL '{{expiration}}';

GRANT USAGE ON SCHEMA public TO "{{name}}";
GRANT CONNECT ON DATABASE %(database)s TO "{{name}}";
~~~

To successfully drop these roles, I have to manually execute the following statements for each role created by Vault:

1. `REVOKE ALL PRIVILEGES ON ALL TABLES IN SCHEMA public FROM "{{name}}";`
2. `REVOKE USAGE ON SCHEMA public FROM "{{name}}";`
3. `REVOKE CONNECT ON DATABASE %(database)s FROM "{{name}}";`
4. `DROP ROLE IF EXISTS "{{name}}";`

Note, 1 and 2 can probably be combined into one statement, i.e., `REVOKE ALL ON SCHEMA public FROM "{{name}}";`

I understand these statements can get pretty hairy for Vault to handle depending on the access you're granting. For that reason, it would also be a nice feature if Vault allowed configuring a template to run for revocation purposes if we so choose to.

**Comment by jefferai** [comment]
Yeah, there are a few issues... the plan eventually is to convince SQL backends and allow both creation and revocation SQL.

**Comment by mwielgoszewski** [comment]
And we just ran into the following:

~~~
2016/01/05 02:45:43 [INFO] core: pre-seal teardown complete
panic: runtime error: invalid memory address or nil pointer dereference
[signal 0xb code=0x1 addr=0x0 pc=0x8033a0]

goroutine 261549 [running]:
database/sql.(*DB).prepare(0xc8203f1a40, 0xc82135d200, 0x8a, 0xc821355c01, 0x8a, 0x0, 0x0)
        /usr/local/go/src/database/sql/sql.go:871 +0x470
database/sql.(*DB).Prepare(0xc8203f1a40, 0xc82135d200, 0x8a, 0x1, 0x0, 0x0)
        /usr/local/go/src/database/sql/sql.go:849 +0x76
github.com/hashicorp/vault/builtin/logical/postgresql.(*backend).secretCredsRevoke(0xc8206b0480, 0xc8216aea80, 0xc82033a230, 0x0, 0x0, 0x0)
        /gopath/src/github.com/hashicorp/vault/builtin/logical/postgresql/secret_creds.go:110 +0x37b
github.com/hashicorp/vault/builtin/logical/postgresql.(*backend).(github.com/hashicorp/vault/builtin/logical/postgresql.secretCredsRevoke)-fm(0xc8216aea80, 0xc82033a230, 0x5, 0x0, 0x0)
        /gopath/src/github.com/hashicorp/vault/builtin/logical/postgresql/secret_creds.go:33 +0x42
github.com/hashicorp/vault/logical/framework.(*Secret).HandleRevoke(0xc820469f00, 0xc8216aea80, 0x1210e98, 0x0, 0x0)
        /gopath/src/github.com/hashicorp/vault/logical/framework/secret.go:87 +0xac
github.com/hashicorp/vault/logical/framework.(*Backend).handleRevokeRenew(0xc82029cbb0, 0xc8216aea80, 0x1210e98, 0x0, 0x0)
        /gopath/src/github.com/hashicorp/vault/logical/framework/backend.go:333 +0x45c
github.com/hashicorp/vault/logical/framework.(*Backend).HandleRequest(0xc82029cbb0, 0xc8216aea80, 0xc8216aea80, 0x0, 0x0)
        /gopath/src/github.com/hashicorp/vault/logical/framework/backend.go:88 +0x113
github.com/hashicorp/vault/vault.(*Router).Route(0xc822051350, 0xc8216aea80, 0x0, 0x0, 0x0)
        /gopath/src/github.com/hashicorp/vault/vault/router.go:256 +0xb0e
github.com/hashicorp/vault/vault.(*ExpirationManager).revokeEntry(0xc8203a6f00, 0xc8216aea00, 0x0, 0x0)
        /gopath/src/github.com/hashicorp/vault/vault/expiration.go:490 +0x29f
github.com/hashicorp/vault/vault.(*ExpirationManager).Revoke(0xc8203a6f00, 0xc82030f490, 0x63, 0x0, 0x0)
        /gopath/src/github.com/hashicorp/vault/vault/expiration.go:188 +0x1bf
github.com/hashicorp/vault/vault.(*ExpirationManager).expireID(0xc8203a6f00, 0xc82030f490, 0x63)
        /gopath/src/github.com/hashicorp/vault/vault/expiration.go:465 +0x104
github.com/hashicorp/vault/vault.(*ExpirationManager).Restore.func1()
        /gopath/src/github.com/hashicorp/vault/vault/expiration.go:151 +0x37
created by time.goFunc
        /usr/local/go/src/time/sleep.go:129 +0x3a
~~~
