### ISSUE TITLE
KV Secret limit of vault

### ISSUE THREAD

**Issue by tsahoo** [hashicorp/vault#7012]
Hi All,
Greetings...
We need  information regarding vault kv secret.
Is there any soft limit of kv secret count ? like 1000,2000 kv secrets.
And is there any documented step for vault version up gradation from v0.10.4 tov 0.11.0.(Currently our vault cluster is running on aws )

Thanks and Regards,
Trupti R Sahoo

**Comment by tsahoo** [comment]
Any update on this??

**Comment by michelvocks** [comment]
Hi @tsahoo,

Vault has no direct KV secret limit. However, all secrets are stored encrypted in the storage backend. Dependent on your used storage backend, there can be some kind of limitations.

> And is there any documented step for vault version up gradation from v0.10.4 tov 0.11.0.(Currently our vault cluster is running on aws )

You should have a look at the upgrade guides: https://www.vaultproject.io/docs/upgrading/index.html

I will close this issue for now since it doesn't appear to be a bug. If you have further questions, please try to ask them via the [Mailinglist](https://groups.google.com/forum/#!forum/vault-tool) or the [Discussion Forum](https://discuss.hashicorp.com/c/vault).

Cheers,
Michel
