### ISSUE TITLE
Any go code example with Vault k8s authentication?

### ISSUE THREAD

**Issue by goplusgo** [hashicorp/vault#7017]
I've searched this online by it turns out that not many code samples available. The one I saw is this: https://github.com/sethvargo/vault-kubernetes-authenticator/blob/master/main.go

However, it does read the k8s service account jwt token manually and then call the `login` endpoint to retrieve the client token. And then it sets the token to the go client. 

This involves a lot of manual work and also we might need to handle the token renew (by using the `renewer`). 

Can I know is there any other easier ways to communicate with `Vault` (say, I only provide the k8s sa token path and Vault endpoint. The sdk will take care of everything else including the token renewer for me )?

Thanks.

**Comment by aphorise** [comment]
Hey @goplusgo - there have been a number of K8S specific learn guides that have been made available on the learn portal since you'd post your request. Like for example:

 - [Integrate a Kubernetes Cluster with an External Vault](https://learn.hashicorp.com/tutorials/vault/kubernetes-external-vault#configure-kubernetes-authentication)

Anyway I'd advise reviewing them and if there' something more specific that you feel is still missing from any of the learn guides or the [other documentation areas](https://www.vaultproject.io/docs/platform/k8s) and [API docs](https://www.vaultproject.io/api-docs/auth/kubernetes) then please raise another issue.
