### ISSUE TITLE
Create tool to report who has access to a path

### ISSUE THREAD

**Issue by tyrannosaurus-becks** [hashicorp/vault#7110]
Just dropping an idea here.

I wonder if it would be useful for us to create a tool that analyzes **who has access** to a particular path in Vault. The path could be a directory level, or an individual secret. The tool would walk all the policies looking for ones that grant access, and then all places where the policy is in use.

This could be helpful at large organizations with lots of policies. Suppose someone new wants to figure out who can read this or that valuable secret. They would run this tool and get a report that it's used by X roles, and possibly also that X users have access to X roles (but that's more of an implementation detail).

**Comment by tyrannosaurus-becks** [comment]
To be clear, I'm thinking of a report that would say _everyone_ who has access to the given secret, not just whether the user performing the query does.

**Comment by chrishoffman** [comment]
This is very much something that is in the purview of the Vault Advisor tool under development.  Since not everything can be tracked to users, it ends up being more closing understood through access patterns, policies, and policy complexity.  See https://www.hashicorp.com/resources/introducing-vault-advisor.
