### ISSUE TITLE
Logical API client broken with paths containing leading '/'

### ISSUE THREAD

**Issue by bkeroackdsc** [hashicorp/vault#720]
[Logical API client](https://github.com/hashicorp/vault/blob/master/api/logical.go#L13)

```go
import (
   "github.com/hashicorp/vault/api"
   "log"
)

func main() {
   vc, _ := api.NewClient(&api.Config{Address: config.vaultServer})
   vc.SetToken(token)
   lc := vc.Logical()
   s, err := lc.Read("/secret/development/testing/test_value")
   if err != nil {
       log.Fatalf("Error reading secret from Vault: %v: %v", path, err)
   }
   log.Printf("Secret value: %v", s.Data["value"].(string))
}
```

Result:
```
2015/10/26 15:31:18 Error reading secret from Vault: /secret/development/testing/test_value: http: read on closed response body
```

Fixed by removing leading slash:

```go
// [...]
s, err := lc.Read("secret/development/testing/test_value")
// [...]
```

Fixed result:

```
2015/10/26 15:36:07 Secret value: omg, success
```

**Comment by jefferai** [comment]
Hi there,

This is actually correct behavior...mounts do not start with a slash. You can see this in the examples in the documentation as well as the output of the `vault mounts` command.

**Comment by bkeroackdsc** [comment]
Seems like a pretty arbitrary limitation. Also the error message is not helpful.

Is there any way to make this a bit more developer-friendly?

**Comment by jefferai** [comment]
In `master` you can already start paths with a slash, just not in any released version, so in the released version you need to use the proper mount path.

The problem with handling them wasn't really a Vault issue, it was unwanted behavior of the Go HTTP server when encountering a `//` in a URL; rather than pass it in to the handler, it would by fiat generate a specific redirect code that was different from the redirect code used by Vault, causing the Vault client to not follow it. So some clients worked, but the Vault API client did not.

**Comment by josh-padnick** [comment]
So, this just bit me in a subtle way. I'm writing a Go-based tool using the golang vault api library. I'm using HA Vault with 3 nodes total.  Here's the inconsistency I discovered with the the compiled vault client:

```
# Run this with a vault client whose requests go to the master.

$ vault read /secret/apps/my-app
Key           	Value
lease_duration	2592000
name          	josh
```

But when you do this exact command directed to a vault standby which forwards to a vault master, you get this:

```
$ vault read /secrets/apps/my-app
No value found at secrets/apps/my-app
```

When using the API to do this exact operation, the `vaultClient.Logical().Read()` returns an unhelpful `EOF` for the error message instead of the nice message returned by the client. 

It looks like the Vault client uses the [same error-handling logic](https://github.com/hashicorp/vault/blob/master/command/read.go#L50-L60) I have in my code, but somehow I get the `EOF` error?

Anyway, I had a bug where I included a leading `/` when I shouldn't have, but because of this bug, it showed up intermittently and it caused a lot more grief than it should have.

**Comment by jefferai** [comment]
@josh-padnick Vault (actually the underlying Go library) handles leading `/` by returning a `301` redirect to the version without the double `//` in the URL. Probably what you're seeing with the `EOF` is that the response body is blank, but you're not checking for and following a redirect.
