### ISSUE TITLE
Vault is not running behind nginx 

### ISSUE THREAD

**Issue by vishnuidp** [hashicorp/vault#7225]
Hi,

I am trying to run vault behind nginx and getting following error 
ui/assets/vendor-9d467c17a27c64929a6f89cfcf0970ea.js' with computed SHA-256 integrity '7e0Vir+Z1UWl7+bG0cr3KXYXliKg0psBs4giaj4237g='. The resource has been blocked.

Nginx configuration are below
 location /vault {
        proxy_pass http://vault:8200/ui;
        proxy_http_version 1.1;
                proxy_set_header    Host               $host;
                proxy_set_header    X-Real-IP          $remote_addr;
                proxy_set_header    X-Forwarded-For    $proxy_add_x_forwarded_for;
                proxy_set_header    X-Forwarded-Host   $host;
                proxy_set_header    X-Forwarded-Server $host;
                proxy_set_header    X-Forwarded-Port   $server_port;
                proxy_set_header    X-Forwarded-Proto  $scheme;
                }
i tried giving http://vault:8200 also, not working.

**Comment by PumpkinSeed** [comment]
What happens if you try `location / {}`, because the Vault's path won't handle the /vault prefix.

**Comment by vishnuidp** [comment]
We have other services running on nginx and base path is being used for some other purpose. Is there any other way?

**Comment by chrishoffman** [comment]
Please post questions on the mailing list (https://groups.google.com/forum/#!forum/vault-tool) rather than in GitHub issues.

With over 1700 subscribers, the mailing list gets a lot more eyes on any particular question. You'll get an answer faster, not slower, by taking advantage of the suggestions and answers provided by the wealth of experience that long-time users and devs bring to the list.

It also prevents problematic issue workflows for questions where either the issue is closed immediately but then discussion continues on a closed issue; or, the issue is not closed, discussion dies down, and the issue remains open indefinitely waiting for further potential replies.
