### ISSUE TITLE
allow user to control vault CLI choice to store auth token in ENV VAULT_TOKEN instead of $HOME/.vault-token

### ISSUE THREAD

**Issue by careyblack** [hashicorp/vault#723]
I was surprised that a second ssh session (as an already authenticated user to vault) would inherit the existing "vault token".

It looks like the default way that the CLI stores a users session is through the $HOME/.vault-token file. (Which is easily read from other new, or existing, ssh sessions.)

I think the existing behavior could be desired by some. However, I can also see a desire for it to use the environment variable VAULT_TOKEN  and not the file cache to avoid the described behavior.

Maybe add another value to the server config file (I assume it is also used by the CLI (but maybe it would need to use a user local config file $HOME/.vault ??) with a setting like:   token_storage=[user_file | environment_variable ]  So that the host/user can choose how they what the command line to operate for them.

NOTE" As a temp workaround a user can can do this after they authenticate in any session.... ( However, it seems fairly trivial to avoid if the user could control how the CLI works by default.)

``` bash
export VAULT_TOKEN=`cat $HOME/.vault-token`;rm $HOME/.vault-token
```

**Comment by jefferai** [comment]
If both exist, the `VAULT_TOKEN` environment variable will be preferred over the file cache; this is described at `https://vaultproject.io/docs/commands/environment.html`.

The reason it's done this way is that CLI users are generally humans who appreciate having an automatically cached token to avoid having to manually set environment variables in each shell session, whereas API users tend to be automated systems.

The CLI by default does not read any config (and not the server config, since most users won't be running the Vault CLI on the same machine as the Vault server). If this were implemented, probably the right way to go would simply be to add a flag that spits out the token to stdout rather than saving it in a file. Then the user can do as they wish with it.

**Comment by careyblack** [comment]
>If both exist, the VAULT_TOKEN environment variable will be preferred over the file cache;

Yep. and that makes the default behaviors of the CLI a bit more strange to me.
* The command `vault auth ...`  defaults to storing token in file cache. (And does not currently support storing it in VAULT_TOKEN environment variable. Without the user doing something on their own.)
* The command `vault read ...` defaults to VAULT_TOKEN environment variable then falls back to file cache.

If the command line tool is being used, (and in all of the above cases it is) then I would expect all of the CLI's "preferences" to be consistent.

I am also surprised that the default way that the token is stored would persist for much longer than the user's current session. So if the user "forgets" to revoke the token, then any other session could use the token (file cache) "by default" until it's TTL expires. ( Which does not seem very secure to me. ) My expectations are that when my session ends, so should any "tokens" that I might have authenticated to use.

BTW: What it the "default TTL" for a Token? 
By my read...
  http://vaultproject.io/docs/auth/token.html
> ttl optional The TTL period of the token, provided as "1h", where hour is the largest suffix. If not provided, the token is valid for the default lease TTL(http://vaultproject.io/docs/config/), or indefinitely if the root policy is used.

>>default_lease_ttl (optional) - Configures the default lease duration for tokens and secrets, specified in hours. Default value is 30 days. This value cannot be larger than max_lease_ttl.
>>
>>max_lease_ttl (optional) - Configures the maximum possible lease duration for tokens and secrets, specified in hours. Default value is 30 days.

So that file would be usable for 30 days. ( Which seems far later than what I think a reasonable expectation would be from any user.)


IMHO, using the VAULT_TOKEN environment variable as the default place to store the token makes much more sense from a security perspective. ( It does not propagate across sessions. Unless the user propagates it via manually setting the environment variable in the second session. Or saving the token to a file with an explicit flag/action. ) 


Not to mention that this is also a bit concerning:

If the root token is used, then that TTL is actually **Indefinite**.  (<-- WT?) And that gets stuffed into a file in the users home directory.!?  

An aside: (maybe should be it's own enhancement request)
> I understand that the root token is special. However, maybe the vault keys could be used in a different way to "recreate" the root token instead of making it live forever?  ( Or at least make any child tokens of root, have a forced TTL.)


About the config file, I did say:
> Maybe add another value to the server config file (I assume it is also used by the CLI (but maybe it would need to use a user local config file $HOME/.vault ??) 

The vault is the server and the CLI. All wrapped up in one executable. So it makes sense ( to me ) that the executable would expect to have a config file(s) in standard locations on the environment. ( /etc/..., $HOME/.vault , $HOME/.vault_cli , etc...)  

Bash man page snip (Just to illustrate the idea)
>When bash is invoked as an interactive login shell, or as a non-interactive shell with the --login option, it first reads and executes commands from the file /etc/profile, if that file exists.  After reading that  file, it  looks  for ~/.bash_profile, ~/.bash_login, and ~/.profile, in that order, and reads and executes commands from the first one that exists and is readable.  The --noprofile option may be used when the shell is started to inhibit this behavior.

If the project direction thinks that some settings should only live in file "/etc/..." and not in file "$HOME/.vault_cli" (or visa versa) then ok. But I would suggest that reading the files in a standard shell like fashion would make the most sense. And let any configfile match one definition instead of trying to segregate where the settings can live. I think that would likely be what users would expect from a CLI tool. ( And obviously if there are settings that the server should assert over the CLI config settings, then so be it, at run time, too.)

**Comment by jefferai** [comment]
> The command vault auth ... defaults to storing token in file cache. (And does not currently support storing it in VAULT_TOKEN environment variable. Without the user doing something on their own.)
> The command vault read ... defaults to VAULT_TOKEN environment variable then falls back to file cache.

Unlike other Vault CLI commands, `vault auth` does not consume a token, it retrieves a token. It is consistent for it to store the retrieved token in the location that token-consuming functions expect to read it.

>  So if the user "forgets" to revoke the token, then any other session could use the token (file cache) "by default" until it's TTL expires. ( Which does not seem very secure to me. ) My expectations are that when my session ends, so should any "tokens" that I might have authenticated to use.

Using the Vault CLI is not a requirement; it is a simple wrapper around the HTTP API. If you do not like its behavior of caching a token for you, you can currently easily work around it by using `curl` or `httpie` to fetch a token and populate it into your environment. The way it works now is a convenience for most command-line users.

> BTW: What it the "default TTL" for a Token? 

It defaults to 30 days, and is easily changeable via config file parameters or (in 0.4+) using the `mount-tune` command on the `auth/token` mount.

> IMHO, using the VAULT_TOKEN environment variable as the default place to store the token makes much more sense from a security perspective.

In your environment this may well be the case, and nothing prevents you from doing so; it is simply not currently built-in. We have found that most users end up wrapping the API to meet their own needs, and this is reasonable and expected, as all organizations and users have their own set of security needs and trade-offs.

> If the root token is used, then that TTL is actually Indefinite. (<-- WT?) And that gets stuffed into a file in the users home directory.!?

Root tokens do not expire. There has to be some non-expiring method of accessing Vault's system functionality to prevent lock-out. However, such a root token is only populated into a file in your home directory if you place it there; by default the only root token is returned from the HTTP API at `init` time, and only a root token can create other root tokens, which does not happen via `vault auth`.

> An aside: (maybe should be it's own enhancement request)
> I understand that the root token is special. However, maybe the vault keys could be used in a different way to "recreate" the root token instead of making it live forever? ( Or at least make any child tokens of root, have a forced TTL.)

At first glance, it seems sensible to me that if a quorum of unseal keys are provided and wish to create a new root token, they should be able to. Feel free to file an enhancement request for it.

>  But I would suggest that reading the files in a standard shell like fashion would make the most sense.

One issue with doing this is compatibility with Windows or any other platform that may not have a traditional shell.

**Comment by norganna** [comment]
I realise this is a 6 month necro-bump, but when searching for this topic, I came across this post and thought I'd post to help anyone else searching.

There's a major problem with the suggested enhancement.

# The problem

An application (running in a subprocess) cannot set an environment variable in the parent (shell) process.

# A solution

The only way to do this is to have a new option implemented in vault to output a series of commands which would then be evaluated by the shell (a là `ssh-agent`)

For example, you would need to do something complicated like this:

~~~
eval $(vault auth --env=bash)
~~~

The command `vault auth --env=bash` would output something similar to `export VAULT_TOKEN=6731916b-c59d-4f11-8a65-dbe4714ad034`, which then gets evaluated by the calling shell process.

The vault process still needs to output prompts and read user input, so this would be tricky, as standard output is being captured by the shell, the vault process would have to acquire the TTY directly.

# Yuk, too complicated!

Yeah. The good news is that there's an alternative; to do the work yourself via a shell function!

You could do something like:

~~~
function env-vault-auth {
  vault auth "$@" && \
  if [ -f ~/.vault-token ]; then
    token=$(cat ~/.vault-token)
    if [ ! -z $token ]; then
      export VAULT_TOKEN=$token
    fi
    rm ~/.vault-token
  fi
}
~~~

Then you would execute it like:

~~~
testuser@testhost:~$ env-vault-auth -method=ldap username=testuser
Password (will be hidden):
Successfully authenticated! You are now logged in.
The token below is already saved in the session. You do not
need to "vault auth" again with the token.
token: 6731916b-c59d-4f11-8a65-dbe4714ad034
token_duration: 2764800
token_policies: [admin default]
testuser@testhost:~$ ls -la ~/.vault-token
ls: cannot access '/home/testuser/.vault-token': No such file or directory
testuser@testhost:~$ echo $VAULT_TOKEN
6731916b-c59d-4f11-8a65-dbe4714ad034
~~~

Because this is a shell function, the process executing the commands is the process you're trying to set the environment in, so it works perfectly.

You can even declare the shell function in your `.bashrc` or similar to load it every time.

**Comment by kiich** [comment]
Post by norganna worked really well for my use case where I have multiple vault backend for different environment and I was frustrated with the constant vault-token remove/recreate process. Awesome job, thanks!

**Comment by th3xer0** [comment]
Was this functionality ever added?

**Comment by jefferai** [comment]
No, because it's not at all necessary. You can simply do:

```
$ env | grep VAULT_TOKEN

$ export VAULT_TOKEN=$(vault login -token-only root)
The token was not stored in token helper. Set the VAULT_TOKEN environment
variable or pass the token below with each request to Vault.

$ env | grep VAULT_TOKEN
VAULT_TOKEN=root
```

In fact, now that I realize this is open, I'm just going to close it :-)

**Comment by tomdottom** [comment]
If anyone wishes to control the vault token location with a `VAULT_TOKEN_PATH` env var then an example solution using the token helper can be found at https://github.com/hashicorp/vault/issues/1492#issuecomment-453527482
