### ISSUE TITLE
Define the Raft backend cluster nodes in the config file similar to Consul

### ISSUE THREAD

**Issue by SK360** [hashicorp/vault#7242]
**Is your feature request related to a problem? Please describe.**
Loving the Raft backend however needing to run the join via CLI or API to the leader is a bit of a pain to make idempotent.

**Describe the solution you'd like**
I would like to be able to define the other nodes in the cluster like I can with Consul in the config via retry_join or something similar so that I can dynamically control the nodes via an Ansible template.  Ideally leader election could also dynamically occur once the bootstrap expect value is met like Consul.

**Comment by chrishoffman** [comment]
I don't think this will end up being possible.  I believe part of the raft join is doing a secure handshake between the node and another node in the cluster.  @briankassouf has more of the details around this.

**Comment by hixichen** [comment]
This is also useful when you use statefulset in k8s which each vault node(pod) can resolve by pod name (it is fixed in statefulset.)

**Comment by nathanhruby** [comment]
Hi Folks! 

This is also needed for running vault in a auto scaling group.  

In my case I already have Consul and cloud auto-unseal setup.  The cluster "works" in that new members come up, register as standbys in Consul but fail health checks because they have no data.  My expectation was that if there is a `service_registration` stanza in the config, it would have mimic'ed the current behavior and formed a cluster.

Assuming all the node and cluster_addr's were unique in the server configs, could one do a `vault operator raft join https://active.vault.consul:8200` and have it resolve things correctly during the join?  I could easily add this to cloud-init and maybe this is an easy workaround?

In my case, vault nodes present valid ssl certs for themselves created through `vault agent` with aws auto-login, so I have a reasonable level of confidence that nodes are who they say they are and therefore am fine with the limited risk involved in auto joining (also limited via security group on the 8201 cluster port).

**Comment by briankassouf** [comment]
Hi @nathanhruby,

you should be able to use the consul address to join the cluster. Also the original ask from this issue of supporting retry_join in the config file is done. You could also set the consul address in the config file so the nodes auto join when they startup. 

docs for retry_join are here: https://www.vaultproject.io/docs/configuration/storage/raft#retry_join

Hope this helps, and since the original ask here is complete I'm also going to close this issue. Feel free to open a new one if there are additional feature asks here.

**Comment by nathanhruby** [comment]
Just tried this and it works great, thank you Brian and Vault Team, as usual!
