### ISSUE TITLE
Can't get website UI in vault Production environment when everything else is working perfectly

### ISSUE THREAD

**Issue by RCAgT** [hashicorp/vault#7249]
As the title states, everything with Vault in a production environment is going perfect O'perfect and every terminal run seems to work flawlessly on its purpose.

However I can't seem to work with the web UI when it also worked perfectly in the development enviroment with `vault -dev`

Here is my config.json file:

```
{
	"listener": [{
		"tcp": {
			"address": "127.0.0.1:8200",
			"tls_cert_file":"/ssl/certs/MY-SELF-SIGNED-CA.crt",
			"tls_key_file":"/ssl/certs/MY-SELF-SIGNED-CA.key"
		}
	}],
	"max_lease_ttl": "3h",
	"default_lease_ttl": "2h",
	"ui":true,
	"plugin_directory":"/plugins",
	"raw_storage_endpoint":true,
    "disable_sealwrap":true,
    "backend": 
        {
            "file": 
                {
                    "path": "/vault/file"
                }
        }
}
```

So, and again, **the vault UI website worked perfectly in a development environment.** However, when I access localhost:8200 I get "ERR_EMPTY_RESPONSE" through HTTP protocol and "ERR_CONNECTION_CLOSED" on HTTPS.

Just to reiterate: everything else on vault seems to be working as it should be unless for this UI issue.

Why would that be though? Thank you! :)

**Comment by chrishoffman** [comment]
Are you running through a proxy?  Are you seeing anything in your vault server logs?  

Also, this is a great question for the mailing list (https://groups.google.com/forum/#!forum/vault-tool) rather than in GitHub issues.

With over 1700 subscribers, the mailing list gets a lot more eyes on any particular question. You'll get an answer faster, not slower, by taking advantage of the suggestions and answers provided by the wealth of experience that long-time users and devs bring to the list.

It also prevents problematic issue workflows for questions where either the issue is closed immediately but then discussion continues on a closed issue; or, the issue is not closed, discussion dies down, and the issue remains open indefinitely waiting for further potential replies.
