### ISSUE TITLE
Does Server Configuration support establishing audit backends?

### ISSUE THREAD

**Issue by careyblack** [hashicorp/vault#726]
ref(http://vaultproject.io/docs/config/index.html)

If I am reading that correctly then it appears to not allow the server config file to specify an audit backend.

Why was not not added to the config file format? (And can it be added?)

**Comment by jefferai** [comment]
It cannot be added. Mount information is stored in the physical backend; it must be, so that it is consistent and accessible during a high-availability failover.

If you aren't on it already, the best place for this kind of question is the mailing list (https://groups.google.com/forum/#!forum/vault-tool) as other people can provide answers and helpful information.
