### ISSUE TITLE
The UI Secrets page should display the mount description

### ISSUE THREAD

**Issue by nickwales** [hashicorp/vault#7304]
It would provide useful information to customers if the secrets page that shows all the current mounts could also display the description. 

**Describe the solution you'd like**
Displaying the description `/ui/vault/secrets` page could have the configured mount description displayed to the right of the mount name + ID 

**Describe alternatives you've considered**
The description is available when looking at the mount settings but customers are unlikely to go and investigate there.

**Additional context**
Here's a very high quality mockup of how it _could_ look.
![Screen Shot 2019-08-13 at 10 26 29 AM](https://user-images.githubusercontent.com/588472/62954824-a8c93680-bdb5-11e9-82d9-b46d4ebd23f7.png)

**Comment by lpar** [comment]
I'd really like to be able to have a displayed description at secret level as well. My current kv secrets store has one, and I've found it very useful when I can't remember which remote database system is associated with which business process, etc.

Failing that, is there a performance implication to having a separate kv2 store mounted for every application, so that at least each application can have a description?

**Comment by aphorise** [comment]
Above PR should address built-in secret engines with a description detail where none are set by the user.

![Screenshot 2020-08-25 at 00 41 30](https://user-images.githubusercontent.com/974854/91103769-917d8400-e66c-11ea-9365-550a93401457.png)

**Comment by aphorise** [comment]
@nickwales - have you tried the latest 1.8.0 release? - please consider closing this ticket if it fits the bill.

<img width="1072" alt="Screenshot 2021-08-05 at 00 16 58" src="https://user-images.githubusercontent.com/974854/128262730-5e180707-a6bd-4e9a-9401-6575f47ae3e3.png">

**Comment by aphorise** [comment]
Closing as there's been no follow-up & original request made is already in place.
