### ISSUE TITLE
Kubernetes Secrets Syncing

### ISSUE THREAD

**Issue by jweissig** [hashicorp/vault#7364]
We are exploring the use case of integrating Vault with the Kubernetes Secrets mechanism via a syncer process. This syncer could be used to periodically sync a subset of Vault secrets with Kubernetes so that secrets are always up-to-date for users without directly interacting with Vault.

We are seeking community feedback on this thread.

**Comment by jogy** [comment]
Please have a look at https://github.com/postfinance/vault-kubernetes and https://itnext.io/effective-secrets-with-vault-and-kubernetes-9af5f5c04d06.

Seth Vargo thinks it is a terrible idea to sync from Vault to K8s secrets as they are inherently insecure. A standardized API like CSI (container storage interface) or CNI (container networking interface) for secrets would be a great way to plug Vault into K8s.

**Comment by cypherfox** [comment]
I would second the route of a CSI for a number of reasons:
* copying secrets to K8s will always increase the  surface of attack massively . I do not trust K8s! The copying will create the need to protect the data at rest, in such a way that it hard to misconfigure and secure by default. Vault does this (as a raison d'etre!)
* can provide a mechanism of component authentication that does not rely on K8s configuration / integrity, like SPIFEE. This is possible without the CSI, but everybody is reinventing the wheel.
* Creates a more limited scope than all of K8s for a security audit.

For applications that are not Vault aware, a sidecar can provide the authentication to the CSI and populate secrets in the filesystem. IMHO, passing secrets in an environment variable is a dubious idea (`kubectl describe pod`?)

**Comment by daneharrigan** [comment]
@jingweno and I have been looking at scenarios where secrets will need to be shared across multiple kubernetes namespaces. In the case of two deployments, unique namespaces for each, and a shared secret (basic auth for example), vault would need to sync to a k8s secret in each namespace.

I’m on board with leveraging k8s secrets since it’s a simple interface and it allows the community to develop against now and add a vault syncer later down the road.

**Comment by tstoermer** [comment]
Currently, we are using [Vault Agent](https://www.vaultproject.io/docs/agent) and [Consul Template](https://github.com/hashicorp/consul-template) in various scenarios as the standard tooling. Also in k8s as sidecar containers to provide the required secrets and performing renew of leases. 

It would be great to have a managed injection of these as init containers (enable clean startup of applications) and then as sidecar (for managing renew of token & leases). 
That would reuse the existing tooling and strengthen their maintenance.

**Comment by thefirstofthe300** [comment]
Funny, I am just hitting this problem for the first time and am trying to decide how best to solve this particular issue. Here's my usecase:

1. We are running applications that have zero knowledge of vault but can read secrets in from env vars or from the filesystem with no issues.
2. These applications cannot be guaranteed to not read credentials from disk each time an authenticated call is made to an API; consequently, updating the secret should result in a new deployment.
3. The end user should be capable of providing a fully fleshed out configuration to a cluster administrator to audit and then apply to synchronize the requested secrets into the user's namespace.

My preferred solution (which I was looking to write over the next month or two) would be to create a controller with two CRDs to implement the syncing solution.

The first CRD would be cluster scoped and provide the configuration to access Vault.
The second CRD would be namespace scoped and used to tell the controller which secret to fetch from Vault and load into the cluster. It would also configure all of the secret specific rotation information.

At this point, the secrets would all be synchronized to the cluster, but they still would not trigger a new deployment rollout to ensure that the application had the correct set of credentials cached.

Consequently, I envision using an annotation to tell the application which secret to pull from the namespace. The secret would need to have a unique identifier that changes each time the secret is rotated. The controller would then update all deployments/statefulset/etc that reference the secret specified in the annotation with the new secret name, thus triggering a rollout.

Again, this is how I'd go about solving the problem. I am not sold on the idea of using a CSI plugin as it requires the application to be aware of changes to the file mounted into the pod (at least, that's my understanding of how the CSI works). I'm not going to say it's not something that should be investigated or even implemented; I'm just saying I don't foresee it solving my usecase.

I'm more a fan of the k8s syncer method for those of us who are running legacy applications that are fairly dumb and don't really pay attention to whether or not the secrets are changed after their initial boot.

**Comment by olemarkus** [comment]
https://github.com/DaspawnW/vault-crd can already do this, but there are some key features missing. For example that anyone that can provision the Vault resource can access all secrets that Vault-CRD has access to. It would be nice if this was namespace-aware or that one can provision different CRD controllers with specific access to Vault. It also doesn't support dynamic secrets.

**Comment by fcgravalos** [comment]
We implemented https://github.com/tuenti/secrets-manager at Tuenti, which is basically a custom controller, which reconciles a CRD, called `SecretDefinition`.

secrets-manager uses vault-approle authtentication to connect to Vault and currently supports kv1 and kv2 engines. I'm looking into the possibility of implementing other vault backends and match them as `classes` which is kind of the `Ingress Controller` approach.

**Comment by james-atwill-hs** [comment]
Tools that have cluster-wide access to Vault secrets (like https://github.com/tuenti/secrets-manager) are a non-starter for us. Also, the further we go down the road of dynamic credentials (databases, aws, etc), it becomes more important that tooling only cycles to new credentials when the lease is about to expire - comparing dynamic credentials to the ones kept inside of Kubernetes will just cause new credentials to be constantly created which isn't really appropriate.

**Comment by fcgravalos** [comment]
Hi @james-atwill-hs! 

As I said, secrets-manager uses AppRole, and we use policies to control which paths are allowed to be read by secrets-manager.

About dynamic secrets, It is not implementes, neither designed. But I think it's feasible to implement the logic to read when the secret ttll is close to expire, as we do with token renewal

**Comment by thefirstofthe300** [comment]
@fcgravalos I believe James's point is not that secrets-manager has to have permssions on Vault but that secrets-manager needs cluster-wide access to secrets to be able to install them in all the required namespaces. 

I'm assuming that secrets-manager is able to install secrets in multiple namespaces. If it's not, I'd totally be willing to help get support for both namespacing and dynamic credential backends implemented. I've been wanting to dig into writing operators for a while now anyway, and I'm at a point where I need it.

I'd also suggest adding support for configuring secrets-manager using a namespaced CRD so that each namespace could have it's own isolated identity to allow for more granular control over secrets synchronization into namespaces.

**Comment by tstoermer** [comment]
Same requirement for us, each application must have its own vault access ensuring it can only access secrets it is allowed to. This is also very important for the vault auditing identifying secret usage of each application.

Regarding dynamic credentials, I think leasing is the important part, e.g. databases:
As many applications have problems with changing db users during runtime, we make use of the leasing mechanism. A db user gets dynamically created on pod startup and is valid as long as it leases are renewed. When the application is shutdown, the vault token is revoked and will clean up the db user. In that way we have
- automated rotation of db credentials for each restart/deployment
- auditing on usage of db users (including renew of lease in context of the application)
- each pod has its own database user, if one gets leaked it can be easily cleaned up (delete pod to create new one with new secrets)

Of course, pki secrets will unfortunately not work that way.

**Comment by fcgravalos** [comment]
Hey @thefirstofthe300! Glad to see you are open to contribute!

We could check if there's a way a controller can reconcile objects in a given namespace but I am not sure if that would be possible tbh.

**Comment by dannyk81** [comment]
@thefirstofthe300 unfortunately CRDs are not namespace-local objects, an option to support namespace-local CRDs was discussed here https://github.com/kubernetes/kubernetes/issues/65551 and although there was interest, it was not implemented (perhaps in the future :pray:)

So, although you could install multiple secrets-managers, the CRD objects are still going to be cluster-wide.

@tstoermer, the kind of requirement you are suggesting sounds like a sidecar approach, perhaps something like https://github.com/uswitch/vault-creds will work for you.

similar approach discussed here https://www.hashicorp.com/blog/whats-next-for-vault-and-kubernetes _"Injecting Vault secrets into Pods via a sidecar"_

---

secrets-manager was designed to reconcile secrets in a more centralized way, dynamic credentials is indeed interesting capability to add.

**Comment by james-atwill-hs** [comment]
I'd much rather something that injects init/sidecars into pods like ( https://github.com/uswitch/vault-creds / https://github.com/hootsuite/vault-ctrl-tool ) than one central controller that has more access than it needs; regardless of namespace scoping.

To be honest, I'd rather investigate a Secrets Provider and Secrets Provider Controller (ala Ingress / Ingress Controller); that's a huge undertaking though.

**Comment by olemarkus** [comment]
If you install multiple secrets-managers, you can specify per secrets-manager in which namespace to look for SecretDefinition objects. And this can be enforced through RBAC. RBAC would also control in which namespaces a controller could read/write Secret objects.

**Comment by dannyk81** [comment]
@james-atwill-hs a sidecar approach is appealing, together with an admission controller to inject the sidecar to the pods (much like Istio does with proxy sidecar), however you still need to define which secrets your applications (pods) need and where to store them/etc.. so this will need to be a logic in the admission controller I suppose.

>To be honest, I'd rather investigate a Secrets Provider and Secrets Provider Controller (ala Ingress / Ingress Controller); that's a huge undertaking though.

Here, I'm confused :smile: since what you are describing is what secrets-manager does, the SecretDefinitions are equivalent to Ingress objects (and are namespaced, etc..) and secrets-manager is the controller that watches these objects and updates the secrets accordingly.

Ingress Controller has a concept of an ingress `class` and can also be limited to watch Ingresses in specific namespaces, combined with RBAC as @olemarkus describes can provide the same kind of isloation. But a controller is still a controller - it's scoped for more than just a single Pod.

**Comment by james-atwill-hs** [comment]
> Here, I'm confused 😄 since what you are describing is what secrets-manager does,

Sort of; my understanding is that secrets-manager has enough access to Vault to provide secrets for multiple pods. If there are different Vault policies in place for service1 vs service2, secrets-manager would need to have access to the superset. This means having a second set of policies in place in secrets-manager to prevent service2 from requesting paths that are only supposed to be accessible to service1. It also means trusting secrets-manager with all the secrets for both service1 and service2.

Right now with init/sidecar, secrets from Vault come in straight from Vault over TLS and are only materialized within the cgroup of the pod. The pod authenticates as itself and the policies Vault gives it are managed inside Vault. ServiceAccount tokens are the defacto way for services to identify themselves in Kubernetes, and once we have bound serviceaccounts it becomes even less perilous to send a serviceaccount jwt to Vault too.

So, we use admission controllers and injecting containers because that's all we have.  What I'm saying as a Secrets Provider / Secrets Provider Controller is something that would limit the exposure of secrets available in Vault to all the surrounding infrastructure. 

Maybe it's something that visits pods and does the heavy lifting, maybe it's a Vault plugin that pushes encrypted Secrets into Kubernetes when a Kubernetes service authenticates and only that service has the decryption key. Dunno. 

What it's not (for us), is another single point of risk that has a superset of access to Vault.

**Comment by fcgravalos** [comment]
Well, if you use a sidecar, there are two options:

1) inject the secret directly from vault to the pod fs directly. Policies for the sidecars would be really hard to maintain, though

2) creating a secret with k8s API. This does not fix the issue since even when a pod can get compromised and you can only get secrets from that path in Vault, you could probably read from k8s api other secrets in the same namespace. And in any case It is still a real PITA maintaining all those vault policies.

**Comment by thefirstofthe300** [comment]
> @thefirstofthe300 unfortunately CRDs are not namespace-local objects, an option to support namespace-local CRDs was discussed here [kubernetes/kubernetes#65551](https://github.com/kubernetes/kubernetes/issues/65551) and although there was interest, it was not implemented (perhaps in the future)

Right, I may have phrased what I was saying poorly. I understand that the CRD itself can't be namespaced. It's an extension of the API server and consequently isn't easy to isolate the object definition to a namespace since that's not how the API server is designed.

I was referring to namespacing the vault configuration that the controller would use. This would allow the controller to pull secrets from Vault into a namespace using an identity that has an isolated set of permissions. Users who can create secrets configurations in the namespace would only be able to use the identity associated with the namespace they are located in.

> Sort of; my understanding is that secrets-manager has enough access to Vault to provide secrets for multiple pods. If there are different Vault policies in place for service1 vs service2, secrets-manager would need to have access to the superset. This means having a second set of policies in place in secrets-manager to prevent service2 from requesting paths that are only supposed to be accessible to service1. It also means trusting secrets-manager with all the secrets for both service1 and service2.

@james-atwill-hs But services never actually ask secrets-manager for their secrests; they pull them from the secrets objects that secrets-manager creates.

> Right now with init/sidecar, secrets from Vault come in straight from Vault over TLS and are only materialized within the cgroup of the pod. The pod authenticates as itself and the policies Vault gives it are managed inside Vault. ServiceAccount tokens are the defacto way for services to identify themselves in Kubernetes, and once we have bound serviceaccounts it becomes even less perilous to send a serviceaccount jwt to Vault too.

I would argue that this is no more secure than using software using an identity with a combination of all permissions granted to the service accounts inside that namespace. If I'm wrong about any of the below, feel free to correct me. There's a lot of pieces here and I could be very easily be missing something.

1) If a person has the ability to get secrets in a namespace, they have access to service account tokens
2) If a person has the ability to deploy a pod to a namespace, they have the ability to attach any service account to the pod and transitively have access to get any service account token in the namespace. However, they can't read all the secrets in the namespace.
3) Given 1 and 2, anybody with the ability to deploy a pod into a namespace effectively has the accumulation of all permissions to Vault granted to the namespace's SAs.
4) If someone has compromised a node or has exploited the API server, they effectively have full access to Vault since they can get the token of any service account.

If instead of granting access to Vault to each service account in the namespace, why not instead have a series of identities that a controller can use to synchronize Vault secrets to k8s secrets. Each identity will be specific to the superset of needed permissions for that namespace and only used when synchronizing the secrets for the secrets definitions in that namespace. This provides a good UX for friendly users who just want to be able to fetch the secrets that they already have access to anyway while keeping the effective attack surface essentially the same.

**Comment by fcgravalos** [comment]
@thefirstofthe300 regarding Vault configuration, I think this is exactly what we do when we deploy secrets-manager. We use a role whose policy rules allow a particular path in Vault.

We have 10+ clusters and every secrets-manager vault's permissions are scoped to its cluster path in Vault.

We can do the same with namespaces we just need to make sure that if múltiple secrets-manager are deployed pero cluster we will need to find a way for them to watch these secretsDefinitions in its namespace.

Ingress controller seems to be able to do It:

https://kubernetes.github.io/ingress-nginx/user-guide/cli-arguments/


There's a `--watch-namespace` flag for it

**Comment by daneharrigan** [comment]
I was thinking along the same lines as @jogy with SMI (secret management interface). Could Kubernetes Secrets be rewritten with a pluggable store? It defaults to etcd, but optionally with Vault through the SMI.

**Comment by james-atwill-hs** [comment]
@fcgravalos writes:

> Well, if you use a sidecar, there are two options: inject the secret directly from vault to the pod fs directly. Policies for the sidecars would be really hard to maintain, though

Containers running in a pod can share the same temporary filesystem. This is how the init container and sidecar interact with whatever service container you have. For vault-ctrl-tool, you can specify how you want your secrets outputted: everything from "just write out the vault token and i'll do the rest" to regularly writing ~/.aws/credentials and filling in templated configuration files. The risk is that the secrets are "on disk" in the pod, the win is that, as a developer, if you can read a file, you can be using Vault.

@thefirstofthe300 writes:

> If a person has the ability to get secrets in a namespace, they have access to service account tokens

With RBAC turned on, no one person should have that much power.

> If a person has the ability to deploy a pod to a namespace, they have the ability to attach any service account to the pod and transitively have access to get any service account token in the namespace. However, they can't read all the secrets in the namespace.

We believe that a Service Account is the way to identify a Service. So, this is where admission controllers come into place. We enforce a naming convention for service accounts and services so that service "A" cannot impersonate service "B" by including a service account token for "B".

> If someone has compromised a node or has exploited the API server, they effectively have full access to Vault since they can get the token of any service account.

If someone gains access to the material used to authenticate to Vault, they gain the ability to authenticate to Vault and therefore also gain access to the secrets that service has. This is true of any authentication process. If you are using dynamic credentials (which is what you should be striving for), then once the breach is detected, you can quickly revoke any of the credentials and create new ones. If you're using static credentials then you have a lot of manual work as well.

And yes, if you gain access to a node and can become root, you may gain the ability to dump memory and sift through it to find secrets. Again, if your secrets are short lived then your exposure is limited.

@daneharrigan writes:

> I was thinking along the same lines as @jogy with SMI (secret management interface). Could Kubernetes Secrets be rewritten with a pluggable store? It defaults to etcd, but optionally with Vault through the SMI.

Agree _something_ like this is where we should be going. Currently Vault supports using Service Account Tokens to authenticate, so the scope of policies is per-service account. I strongly think that's the right scope to be aiming for. Operators that have the access of multiple services (and are pulling a wide scope of secrets from Vault into Kubernetes) seem suboptimal to me.

**Comment by afirth** [comment]
This proposal would be extremely helpful in the "cluster per service" model which is becoming common now that it's easy to provision clusters on the various cloud providers. Bootstrapping the secrets is currently the most painful part of that process, in my opinion. Of course, there are security tradeoffs for other use cases which might make this approach not viable for them. They can use the other mechanisms instead. Thanks for all the links to tooling that already does this. I think the fact that the tooling exists in several forms shows the vault team the use cases exist. :+1:

**Comment by fcgravalos** [comment]
Just in case if it sounds interesting for someone, we added a `watch-namespaces` functionality into `secrets-manager`

https://github.com/tuenti/secrets-manager/pull/39

**Comment by asaintsever** [comment]
[Talend Vault Sidecar Injector](https://github.com/Talend/vault-sidecar-injector) supports this use case (disclaimer: I am the author of this component).
We inject both vault agent+consul template as sidecars (not init containers) thus vault token is continuously refreshed for you underneath.

**Comment by asaintsever** [comment]
Oh great. Thanks for pointing that. Will then be able to only inject one sidecar to do all the work!

**Comment by fcgravalos** [comment]
`secrets-manager` v1.0.2 stable release. Nampesace restriction is included in this release.

https://github.com/tuenti/secrets-manager/releases/tag/v1.0.2

**Comment by blakepettersson** [comment]
How about the approach of a [mutating webhook](https://github.com/banzaicloud/bank-vaults/tree/master/docs/mutating-webhook)? It seems to allow for specifying the K8S secrets as Vault keys, while it defers the fetching of the actual secret until deployment time. I'm probably missing something here so feel free to let me know what that could be...

**Comment by joemiller** [comment]
First, I think this is a good and clever approach. One downside is rotation
of secrets. The mutating webhook only runs when the pod is created. Dynamic
credentials like TLS certs with short expiration would need an additional
mechanism to handle refresh/renewal.

**Comment by estahn** [comment]
@blakepettersson @joehillen 

> How about the approach of a [mutating webhook](https://github.com/banzaicloud/bank-vaults/tree/master/docs/mutating-webhook)?

We had a fair amount of negative experience and drama with the mutating webhook. Just a reminder, the mutating webhook will mutate any created pod. While in theory, it's great to have every pod with its own credentials it wasn't scalable for us, because:

1. The different secret backends need to be able to provide the throughput, e.g. AWS Aurora and AWS Redshift failed on this for us, e.g. replica lags due to blocking.
2. You have to handle different failure scenarios like crash loops which will create massive amounts of users.
3. If you use multiple secret backends per app (which I assume is normal) then 2. will increase exponentially.

Imo syncing to Kubernetes secrets sounds good (even if not most optimal) and using some strategy like https://github.com/stakater/Reloader should solve the pod rotation issue.

**Comment by joehillen** [comment]
@estahn wrong joe

**Comment by jweissig** [comment]
FYI - We just announce a new Vault + Kubernetes integration that enables applications with no native HashiCorp Vault logic built-in to leverage static and dynamic secrets sourced from Vault. Suspect this will be of interest to folks in here since there was chat about init, sidecar, service accounts, etc.

Blog: https://hashicorp.com/blog/injecting-vault-secrets-into-kubernetes-pods-via-a-sidecar
Docs: https://www.vaultproject.io/docs/platform/k8s/injector/index.html
Video: https://www.youtube.com/watch?v=xUuJhgDbUJQ

**Comment by bonifaido** [comment]
@estahn 

> Just a reminder, the mutating webhook will mutate any created pod.

This is just not true. MutatingWebhookConfiguration offers a very fine-grained control over which pods to mutate.

**Comment by estahn** [comment]
@bonifaido 

> This is just not true.

I don’t recall the exact mechanism, but my primary point was about secret backends not being resistent to pod churn and especially situations with crash-looping pods which create thousands of users.

We have used bank-vaults and contributed the mutating webhook to the project. Unfortunately we had to remove it due to the impact on our workload.

**Comment by patpicos** [comment]
I think both injection. and replication are needed capabilities. Not every secrets get loaded into a pod/deployment.

Here's another use case. Anthos CM for example has a CRD listening for RootSync objects. the configuration requires a references to the git credentials stored as a k8s secret. Therefore, the injector does not work.

Yes I could do an imperative step of 
- vault kv get
- k creat secret
- create the rootsync.
...but a direct integration w/o having to deploy yet another secret solution (SOPs, external secrets, your flavor of tool) would be ideal.

**Comment by ncabatoff** [comment]
We reserve github issues for bug reports and feature requests, which this doesn't appear to be.  As such, I'm going to close this and suggest that you continue the discussion at https://discuss.hashicorp.com/c/vault/30.
