### ISSUE TITLE
Can I set One-Time Passwords in MySQL database secret engine like (SSH OTP) One-Time SSH?

### ISSUE THREAD

**Issue by 2994186010** [hashicorp/vault#7407]

**Comment by michelvocks** [comment]
Hi @2994186010!

This seems to be a question instead of an issue of Vault itself. Questions should be asked via the [Discussion forum](https://discuss.hashicorp.com/c/vault) or the [mailing list](https://groups.google.com/forum/#!forum/vault-tool). I will close this issue for now but feel free to ask this question again via the mentioned community channels.

Cheers,
Michel
