### ISSUE TITLE
Individual kv size limit

### ISSUE THREAD

**Issue by ivijaykarani** [hashicorp/vault#7442]
The vault kv can accept inputs in the form of json file. 
Is there a soft or hard limit on individual kv size? If so what is the size is bytes ?
Are there any data to show the get/put access times from vault when the size of the kv is 1MB or 10MB or 1GB ? Are those sizes reasonable for a single kv entry?

**Comment by ncabatoff** [comment]
We reserve github issues for bug reports and feature requests, which this doesn't appear to be.  As such, I'm going to close this and suggest that you ask about this at https://discuss.hashicorp.com/c/vault/30.

Since I can answer some of your questions very quickly:
* Limits are typically storage-engine specific, some are documented here: https://www.vaultproject.io/docs/internals/limits
* Access times can be seen in metrics: https://www.vaultproject.io/docs/internals/telemetry
