### ISSUE TITLE
Improve Vault audit log documentation

### ISSUE THREAD

**Issue by vzabawski** [hashicorp/vault#7488]
It would be really nice to have some guidelines for audit logs. Here's my notes:
1. `syslog` and `socket` audit devices' doc pages contain warnings, so it seems like the most stable and preferable for inexperienced users is `file` audit devise. It would be useful to have a note about the most popular/reliable approach for people who've just started using Vault.
2. `file` audit device has some tips about log rotation but it would be really nice to have some "best practices" section dedicated to log rotation, maybe example config and some advice for better logs handling. For example, docs for Consul backend contain some examples of default ACL policies for Consul and it's really useful when you're just starting with Consul ACL and dont' want to break Vault functioning. So, it would be really nice to have something like that for `file` audit device and maybe other audit devices.

**Comment by aphorise** [comment]
I believe the documentation that's sought after has since been added and is available at:
- Docs: [vaultproject.io/docs/audit](https://www.vaultproject.io/docs/audit)
- Learn guide: [Blocked Audit Devices](https://learn.hashicorp.com/tutorials/vault/blocked-audit-devices)

@vzabawski  please confirm.
