### ISSUE TITLE
Docs: Go version in the README.md.

### ISSUE THREAD

**Issue by aivinog1** [hashicorp/vault#7525]
**Describe the bug**
In the README.md:
https://github.com/hashicorp/vault/blob/9b05bfd882134f16890f55ac2f50c0c03e679c58/README.md#L63
minimal go version is 1.12.1. But in the build scripts, minimal go version is 1.12.7. Consider #7475 let's create a maximum version of <1.13.

**To Reproduce**
1. Use go version of 1.12.1+, but before 1.12.7
2. Run make
3. See an error about the minimum version of 1.12.7

**Expected behavior**
Expecting that README.md points to the right version of go and that a build script has a constraint about version >=1.13.

**Comment by kalafut** [comment]
Thanks for highlighting this, and I've updated the version numbers in the README (thanks for highlighting that).

Adding a max version to the build process is something that would need some further review. Hard breaks due to using the latest version of Go have been rare, there are usually workarounds, and we get useful feedback from those running with very recent versions.
