### ISSUE TITLE
Add ability to set PSS salt length for transit/sign endpoint

### ISSUE THREAD

**Issue by mbreban** [hashicorp/vault#7531]
By default, the salt length in a PSS signature is computed according to the _PSSSaltLengthAuto_ method.

> PSSSaltLengthAuto causes the salt in a PSS signature to be as large as possible when signing

An other method is available _PSSSaltLengthEqualsHash_ in _pss.go_.

> PSSSaltLengthEqualsHash causes the salt length to equal the length of the hash used in the signature.

For some reasons, I have no other choice but to use this second method.
The API does not allow user to set the method to be used for the salt length.

What I would like is a new parameter in the transit/sign endpoint to define the method to use.

**Comment by iamktm** [comment]
Instead of having a parameter to allow the caller to specify the PSSSaltLengthEqualsHash method, it would be nice to allow the caller to specify the salt length in the request. Doing this will satisfy the PSSSaltLengthEqualsHash use case as well as any other salt value (between 0 and emLen - hLen - 2). This would make it fully compatible with other APIs like OpenSSL, JCE, etc.

**Comment by stevendpclark** [comment]
Closing issue as it was implemented by @trishankatdatadog within #16549
