### ISSUE TITLE
Docs for storage backends.

### ISSUE THREAD

**Issue by odigity** [hashicorp/vault#755]
I've gone through ~~all~~ most of the docs, and while there are dedicated sections for the Audit, Auth, and Secret Backends, there doesn't seem to be one for Storage Backends.

I want to set up Vault with etcd, but I'm not sure how.

Related: Would also be nice to see some comments about the possibility of migrating from one store to another, in case I, for example, want to upgrade to Consul later.

Other potential awesome topics to cover:
1. Using Vault + Let's Encrypt to automatically generate and store single-host certs.  (Public launch Nov 16!  So excited...)
2. Setting up some kind of FUSE solution to serve certs to nginx from Vault.  (I haven't checked to see if there's a non-FS way to feed a cert to nginx, but I'm currently using the jwilder/nginx-proxy docker image which probably wouldn't support it anyway.)

Disclaimer: I hope you take these as suggestions, not stressors.  :)

**Comment by odigity** [comment]
I just found the etcd docs here, on one of the few pages I hadn't finished reading yet:

https://vaultproject.io/docs/config/index.html

So sorry...

**Comment by jefferai** [comment]
> Using Vault + Let's Encrypt to automatically generate and store single-host certs. (Public launch Nov 16! So excited...)

Did you see the PKI backend (https://vaultproject.io/docs/secrets/pki/index.html)? This can be used as an API-driven way to generate certs. In 0.4 its capabilities are hugely expanded (I can point you to a branch if you like, although the documentation for it isn't complete).

Let's Encrypt is also API driven but it's solving a different problem -- authentication and authorization in the public Internet. Vault has separate authn/authz capabilities.

**Comment by odigity** [comment]
I did read that section of the docs, and also read through this convo:

https://github.com/hashicorp/vault/issues/388

Disclaimer: I'm not much of a PKI buff, and know little beyond the basic concepts of asymmetric crypto, CA-rooted cert chains tied to DNS, and that certs are necessary for TLS. In other words, I know enough to build apps. :)

If I understand Vault's PKI feature correctly, it's purpose is primarily to generate child certs using a parent cert (CA cert) you store in Vault, which are then used within your infrastructure (such as Vault client/server communication).

That's different from the purpose of Let's Encrypt, which is to make it free/easy/automatable to get a cert for particular host (foo.example.com) issued from a CA that's already accepted by all browsers, for the purpose of enabling TLS on public-facing web apps and services (and other protocols, of course).

It could be that there's nothing to be done in terms of integrating Let's Encrypt with Vault beyond:
1. Setting up Let's Encrypt to use normally.
2. When you do get a cert, stick in Vault's generic secrets backend for retrieval later.

**Comment by jefferai** [comment]
Yes -- as I said, LE is solving a totally different problem than Vault's PKI backend, which is targeted not at public-facing CAs (although it could certainly serve as the backend for that), but rather for backend/datacenter usage, where you need TLS certificates between each set of hosts (often for client/server auth rather than purely for stream security). There are solutions for this already, but the Vault backend lets you piggyback on the authn/authz you already have set up for your applications, and simply tack on certificate generation and fetching.

That's one of the things that people that think Vault has backend-itis don't really quite understand. Vault is really a unified authn/authz platform. The backends are mostly, at this point, written by third parties, and the quality varies, but the point is that you figure out how to securely get a Vault token to a machine once, and then you can use it for a wide array of additional security needs.

**Comment by odigity** [comment]
I agree that it's a very useful feature, and I intend to check it for internal TLS when I can get around to it.

Speaking of which, the docs for the etcd storage backend say it defaults to http://localhost:4001, which obviously doesn't use TLS.  Is enabling TLS as simple as specifying an https URI?  (And configuring it on etcd's side, obviously.)  Or is there additional configuration necessary?

**Comment by jefferai** [comment]
In master it actually now defaults to the IANA assigned etcd client port. I'm not actually sure with respect to enabling TLS, but being dependent on the URI is often a good first guess.

**Comment by raoofm** [comment]
@jefferai just wondering why was this issue reopened. I'm planning to use etcd v3 or v2 as the backend for vault.

**Comment by jefferai** [comment]
Because it was closed accidentally, along with hundreds of other issues. That said, the original request is kind of moot at this point, so I'll re-close it.

**Comment by raoofm** [comment]
@jefferai how confident should I be using etcd as the backend?

**Comment by jefferai** [comment]
From our docs:

> Please note: The only physical backends actively maintained by HashiCorp are consul, inmem, and file. The other backends are community-derived and community-supported. We include them in the hope that they will be useful to those users that wish to utilize them, but they receive minimal validation and testing from HashiCorp, and HashiCorp staff may not be knowledgeable about the data store being utilized. If you encounter problems with them, we will attempt to help you, but may refer you to the backend author.

**Comment by raoofm** [comment]
@xiang90 We use etcdv2 as documented on etcd [production-users](https://github.com/coreos/etcd/blob/master/Documentation/production-users.md#vonage).

We think that it is better to use etcd as backend as we have a 5 machine cluster already in production, rather than using consul (though we have zk as well but we don't wanna use it for other reasons).

Just want your opinion on using etcd(both v2 and v3) as the backend for vault. Is it mature enough or too early to adopt it for vault? Your opinion gives a lot of trust as we have been following etcd for 2 years and it had been a great experience.

**Comment by xiang90** [comment]
@raoofm I start to maintain etcd3 backend for vault. I would suggest you to wait until the 0.6.5 vault release to try out etcd3 backend. If there is any etcd3 issues in vault, we will make sure it get resolved as soon as possible.

**Comment by xiang90** [comment]
@jefferai Do we have a doc listing the maintainers of different backends?

**Comment by jefferai** [comment]
We don't; however, we could put in a note in the etcd backend docs if you want to point to a specific email addy/mailing list/etc.

**Comment by raoofm** [comment]
@xiang90 thanks

**Comment by xiang90** [comment]
@jefferai I can add a readme or owner file in the etcd backend pkg if you do not mind.

**Comment by jefferai** [comment]
Sure, that works.
