### ISSUE TITLE
Socket or RPC communication instead of HTTP API

### ISSUE THREAD

**Issue by PumpkinSeed** [hashicorp/vault#7604]
**Is your feature request related to a problem? Please describe.**
The performance matters for us at my company, and I think the HTTP API is not the best in performance. I looked for it, but this is the only way to communicate with Vault.

**Describe the solution you'd like**
It would be nice to have something like a socket connection or RPC connection next to the HTTP API. It can developed as the part of the core, but wouldn't affect the current system. 

I can help to make it happen if I can have a guide and the designed architecture how to do that.

**Comment by narayan-iyengar** [comment]
@PumpkinSeed What performance enhancements are you trying to get from an RPC based protocol
What areas of the API are you looking to get performance enhancements in?
Trying to figure out if we can make our http api perform better as opposed to implementing a whole new protocol.

**Comment by PumpkinSeed** [comment]
Firstly thanks for the answer and talking about this decision. 
I mean I would like to have something like a gRPC+Protobuf capabilities to talk with Vault instead HTTP+JSON. Since the RPC using a reusable connection of TCP also it's proven [gRPC much faster compared with HTTP](https://dev.to/plutov/benchmarking-grpc-and-rest-in-go-565). Also there is examples there like [Dgraph](https://github.com/dgraph-io/dgraph) using gRPC as the communication with the client. 

I don't want to say to get rid of the HTTP completely. I'm talking about adding an extra functionality to Vault what makes the client able to communicate via gRPC.

Why I came with this idea, because we using Vault with Transit Secret Engine, and I think the gRPC implementation can improve on the performance to talk to Vault. 

I made a quick benchmark test on my Macbook (2015 early). 
What I did in one iteration: 
`client.NewRequest("GET", fmt.Sprintf("/v1/transit/keys/%s", keyname))`
`client.NewRequest("POST", fmt.Sprintf("/v1/transit/sign/%s/%s", keyname, hashAlgorithm`
Benchmark:
```
goos: darwin
goarch: amd64
pkg: bitbucket.org/fluidpay/api/crypto
BenchmarkVaultSign-4   	      60	  39498085 ns/op
```

So it's 39ms, which is basically gives a huge overhead compared what it is actually doing and I think it's not because of the Vault performance. Please correct me if I'm wrong.

**Comment by narayan-iyengar** [comment]
Apologies for the late response. I will definitely take this up internally and see what the Vault engineers have to say. We have discussed this in the past but it's a big task that will have to be planned for and roadmapped. Will keep this issue posted. thanks again for your feedback.

**Comment by PumpkinSeed** [comment]
No worries, not an easy thing what I'm asking for so take your time, also I would be happy to contribute to it.

**Comment by jefferai** [comment]
This is an absolutely enormous lift with a bunch of issues. But I also don't think it's really necessary. That blog post you're looking at is inconsistent with the README in the repo that it links to (https://github.com/plutov/benchmark-grpc-protobuf-vs-http-json#results), which actually shows that HTTP+JSON is faster. One of the comments on the blog post ran the test and got the same result, with HTTP+JSON being faster. There seems to have been something wrong with the setup used for the blog post -- my guess is that it didn't reuse the HTTP connection, resulting in a new connection being created for every operation, but did reuse the connection for gRPC. That will cause a huge amount of slowness regardless of whether it's gRPC or HTTP.

I will say that when reusing the connection we have gotten results encrypting through transit of tens of microseconds. 39ms is a _huge_ amount of time for a single transit call. Of course things like audit logs and the number of configured policies will have an impact as well -- audit logs tend to slow things down quite a lot. But if you're using simple policies and no auditing, it seems like something is off. I don't know the fluidpay library, but I'd guess your test is setting up and tearing down a new connection for every run of the benchmark instead of reusing one.

**Comment by PumpkinSeed** [comment]
Thank you for the detailed answer.
We have an api.Client global variable on top of the package, we are reusing this for our calls toward to Vault. 
Also I hacked an RPC server into the `http/handler.go` which serves the same functionality as the `/v1/sys/health` does. So calling the `getSysHealth(...)` function and wrap up the same response. Just to make sure I'm correct [there is the code](https://pastebin.com/3DLFW1be). I have made the curl first.
```
curl -w "@curl-format.txt" -o /dev/null -s localhost:8200/v1/sys/health
```
with the result of:
```
sh curl.sh 
  time_namelookup:  0.000357s
       time_connect:  0.000543s
    time_appconnect:  0.000000s
   time_pretransfer:  0.000578s
      time_redirect:  0.000000s
 time_starttransfer:  0.000868s
                    ----------
         time_total:  0.000899s
```
Then I run the RPC test: 
```
func main() {
	mes := time.Now()
	client, _ := rpc.Dial("tcp", addr)
	defer client.Close()

	_ = client.Call("Rpchandler.Health", request, response)
	fmt.Println(response)
	fmt.Println(time.Since(mes))
}
```
where the result was (run multiple times where I found this as average):
```
go run rpct.go 
&{200 {"initialized":true,"sealed":false,"standby":false,"performance_standby":false,"replication_performance_mode":"disabled","replication_dr_mode":"disabled","server_time_utc":1574671720,"version":"1.3.0-dev","cluster_name":"vault-cluster-1dc27ac9","cluster_id":"8312b082-6bc1-faf3-1321-5ba6ed1a0d0e"}}
502.247µs
```

Conclusion: It can be faster, but as I dig into the code it's strongly based on HTTP. So doesn't worth the deal with this optimization because it's not a significant improvement.
If you don't mind I close this issue because of the conclusion.
