### ISSUE TITLE
Policy to allow entity name update doesn't work with "*"

### ISSUE THREAD

**Issue by Place1** [hashicorp/vault#7645]
I'm trying to update the name of an entity by id using vault CLI.

Here's the policy i'm using to allow it:

```
path "identity/entity/id/*" {
  capabilities = ["update"]
  allowed_parameters = {
    "name" = []
  }
}
```

Here's the command i'm trying to use to do the update:

```
vault write "identity/entity/id/$the_id" name="$new_name"
```

The above gives me a standard 403 Permission Denied response.

After checking with `vault token capabilities $(cat ~/.vault-token) identity/entity/id/$the_id` vault says that my token only has "read" access

But interestingly if I use the below policy then the capabilities check says I have the permissions I expected and the `write` cli command also works.

```
path "identity/entity/id/$the_id" {
  capabilities = ["update"]
  allowed_parameters = {
    "name" = []
  }
}
```

Additionally, I tried to update the entity name with the below policy and it still didn't work

```
path "*" {
  capabilities = ["create", "read", "update", "delete", "list", "sudo"]
}
```

Does the "*" character not match `:id` segments in API paths?

**Comment by ncabatoff** [comment]
The "*" character does match the `:id` segments in API paths.  The problem you're facing is due to (1) non-wildcard policy paths override wildcard policy paths and (2) everyone gets the `default` policy, which includes this:

```
# Allow a token to look up its own entity by id or name
path "identity/entity/id/{{identity.entity.id}}" {
  capabilities = ["read"]
}
```

So your first rule is being ignored because there's a more specific rule that applies.  Your second rule which uses an explicit id instead of a wildcard works, though I would've expected the capabilities to be merged resulting in `["read","update"]`.

> Additionally, I tried to update the entity name with the below policy and it still didn't work

Again, the more specific rule is winning out.

**Comment by Place1** [comment]
Oh thanks for the explanation. Not sure how I missed this in the docs because some sort of default rule was on my mind.
