### ISSUE TITLE
LDAP Documentation - "Required" Parameters

### ISSUE THREAD

**Issue by llamasoft** [hashicorp/vault#7655]
The documentation for the Active Directory secrets backend says that for the `config` method, the parameters `url`, `binddn`, and `bindpass` are required.  However, the actual validation check is [much less strict](https://github.com/hashicorp/vault/blob/7932afafe2a1c2c5ac9c7fc03c0c7f15c427f9fb/sdk/helper/ldaputil/config.go#L375-L377).  The following commands all report a success, despite violating what the documentation states as required:

```
vault secrets disable ad && vault secrets enable ad && vault write ad/config upndomain="test"
vault secrets disable ad && vault secrets enable ad && vault write ad/config userdn="test"
```

I don't have an AD server to test against so I don't know if the above configurations are even usable, but the endpoint seems to accept them like they are.

**Comment by aphorise** [comment]
This is by design and allows for earlier provisioning prior to the AD or upstream connectivity actually being complete which is only so when you actually attempt a login. It's actually the same with all secret engines and if for example you have [`TRACE` level log enabled](https://www.vaultproject.io/docs/configuration#log_level) then some checked are performed upon a successful `/config`. The [ **required** parameters documented](https://www.vaultproject.io/api-docs/secret/ad#binding-parameters) is with reference to what's needed for valid API call where those parameters must be provided (any value).

@llamasoft - please state if this is clear and if so kindly consider closing your request.

**Comment by llamasoft** [comment]
Works for me.  It's been almost 3 years since I had this issue and have since entirely forgotten about it.
