### ISSUE TITLE
Support for Windows Remoting Certificate Access

### ISSUE THREAD

**Issue by alevy4** [hashicorp/vault#7686]
Hi, it would be great if Vault would support issue of certificates to support certificate authentication on WinRM.

It would mean that cert issue alt_names would need to support OID 1.3.6.1.4.1.311.20.2.3. (UPN), required by Windows to be embedded in the v3 extension.

The only other alternative is to use openssl to generate the certs.

**Comment by powhapki** [comment]
Any Update for this?

**Comment by hsimon-hashicorp** [comment]
Hi @powhapki - does the `allowed_other_sans` option solve your need? https://www.vaultproject.io/api/secret/pki#allowed_other_sans

**Comment by cipherboy** [comment]
As mentioned by @hsimon-hashicorp, Vault has supported the `other_sans` parameter on requests and the `allowed_other_sans` parameter on roles since 2018. This should allow restriction and specification of custom OID SANs during issuance, though some care still needs to be taken due to the globbing of the latter parameter. 

Let us know if that's not sufficient, but I believe it to be so. :-)
