### ISSUE TITLE
Replication/HA Issues beteween datacentres

### ISSUE THREAD

**Issue by mms11** [hashicorp/vault#7697]
I've two vault clusters and I'm using consul storage as a storage for each one enabling High Availabilty beteween then.

Per cluster:
2 Vault Server Version: 1.0.0
3 Consul Server Version: 1.3.0
Configured consul-replicate v0.4.0 to send data from DC1 to DC2.

I'm using token authentication for kubernetes. 

Sometimes users are able to generate a token to authenticate and grab KV secrets and normally works well in DC1 but not in DC2 and then it's necessary stop consul service on both nodes of DC2, delete data folder and start consul service again. Then stop vault service on active node and wait a few seconds till the other node became the active node and after that start the vault service again and unseal vault and do the same steps for this node became the active node again.

This also happens using vault ldap auth.

It's a weird situation and I dont know how and when I can expect it.

Has anyone had the same problem?

**Comment by michelvocks** [comment]
Hi @mms11!

The scenario you described above is not supported by Vault. The problem is that both clusters have an active primary Vault node that writes to the storage and since there is no active locking behavior enabled, unpredictable writes can occur.

I highly recommend having a look at [Vault enterprise](https://www.hashicorp.com/products/vault/enterprise) if you really need Multi-datacenter replication.

Cheers,
Michel

**Comment by mms11** [comment]
Hi @michelvocks. 

I was investigating the issue and the problem is an unpredictable writes as you said.

All the tokens/KV that are write in the DC2 are deleted when the consul-replicator runs.

Cheers,
Marco
