### ISSUE TITLE
How to deploy vault without persistent storage(pv) in openshift

### ISSUE THREAD

**Issue by get2arun** [hashicorp/vault#7726]
Use-case and scenario for setting up the vault server in openshift
In the openshift platform, as a normal user, I am trying to deploy the vault server. Followed the url https://github.com/openlab-red/hashicorp-vault-for-openshift to create vault server in the openshift cluster. In the vault.yaml file, there is persistent volume claim that is not avaialbe in my setup. 

Describe the solution you'd like
How can I deploy the vault without using persistent claim? Is persistent volumes really required for running vault ? what is the alternative solution or workaround for deploying vault?

Describe alternatives you've considered
Is it possible to use the local path on the vault container(pod) instead of pv in the cluster?

I have limited access to DEV cluster but I wanted to perform poc to deploy Hashicorp vault for implementation in the production. I just need the quick (even dirty way) to bring vault server up and running.

**Comment by michelvocks** [comment]
Hi @get2arun!

You don't necessarily need a persistent storage volume for Vault itself. We support multiple storage backends (https://www.vaultproject.io/docs/configuration/storage/index.html) which can be deployed outside of your Openshift cluster. If you want to deploy the storage backend for Vault also inside your Openshift cluster, you probably want to have a persistent storage volume otherwise all data will be lost during a failure/restart. 

Cheers,
Michel

**Comment by catsby** [comment]
Hello - I believe Michel has addressed your questions here, so I'm going to close this for now. For future Vault operation questions, please checkout https://discuss.hashicorp.com/c/vault 

Thanks!
