### ISSUE TITLE
Setting the callbackhost for OIDC is not working in 1.3.0-beta1

### ISSUE THREAD

**Issue by gites** [hashicorp/vault#7771]
**Describe the bug**
I'm trying to test feature introduced in JWT-71 and use different callback host then `localhost` but the `callbackhost` flag is ignored.

**To Reproduce**
1. Use vault `1.3.0-beta1`
2. Run `vault login -method=oidc role=woop callbackhost=callback.example.com`
3. Redirect URI is still set to "`lolcahost` 

`redirect_uri=http%3A%2F%2Flocalhost%3A8250%2Foidc%2Fcallbac` 

**Expected behavior**
Redirect URI should be set to `callback.example.com`

**Environment:**
* Vault Server Version (retrieve with `vault status`):
```
Key             Value
---             -----
Seal Type       shamir
Initialized     true
Sealed          false
Total Shares    6
Threshold       2
Version         1.3.0-beta1
Cluster Name    vault-cluster-3dsada5
Cluster ID      100-200-300
HA Enabled      true
HA Cluster      https://10.10.10.12:8201
HA Mode         active
```
* Vault CLI Version (retrieve with `vault version`):
```
Vault v1.3.0-beta1
```
* Server Operating System/Architecture:
```
x86_64 GNU/Linux
```

**Additional context**

```
# vault plugin info auth oidc
Key        Value
---        -----
args       []
builtin    true
command    n/a
name       oidc
sha256     n/a
```

**Comment by ljagiello** [comment]
It looks like there is a wrong version of plugin in go.mod (https://github.com/hashicorp/vault/blob/master/go.mod#L76) it should be fa5d6cc (next merge).

**Comment by kalafut** [comment]
@ljagiello @gites Thanks for catching this (and thanks for the PR, which I'll accept next). The usual workaround until the next release is to build the plugin from master and register it with Vault. In this case it's a little different, since the issues of interest (JWT-71 and JWT-77) are both in the CLI integration with Vault. This means you need to build Vault (after I merge the PR) to see the change. The good part is that these are both CLI-only changes, so you don't need to update the server to try them out. As long as your local Vault binary is updated you should be good.
