### ISSUE TITLE
Automated PKI Tidying

### ISSUE THREAD

**Issue by ianferguson** [hashicorp/vault#7801]
**Is your feature request related to a problem? Please describe.**

Operating our Vault clusters that utilize PKI backends requires also orchestrating processes to periodically call the [PKI tidy](https://www.vaultproject.io/api/secret/pki/index.html#tidy) endpoint to minimize how many expired certificates we accrue in our storage backends.

**Describe the solution you'd like**

Ideally, expired certificates (past a configurable safety period, if necessary) could be automatically tidied up in a manner similar to how expired tokens/accessors are currently tidied up automatically.

**Describe alternatives you've considered**

No alternatives considered beyond continuing to operate processes that periodically call the tidy endpoint on all PKI mounts.

**Explain any additional use-cases**

None.

**Additional context**

This appears to have been visited around 2.5 years ago in [a post on the mailing list](https://groups.google.com/forum/#!msg/vault-tool/Wh48kq3fEbE/7Datksm6DwAJ), but given the amount of development that has happened with Vault since then, I wanted to see if y'all were open to revisiting that decision.

**Comment by ncabatoff** [comment]
Hi @ianferguson ,

I agree that it would make sense to offer an option to specify that you want Vault to periodically to a tidy with tidy_revoked_certs=true and a particular safety buffer.  If you decide you want to attempt a PR, framework.Backend.PeriodicFunc is probably the hook you want, though note it runs every minute so you might want to have it do nothing some of the time to put less load on storage.

In case you're not already aware, if you're not using CRLs you could set the no_store role option and then you wouldn't need this.

**Comment by ianferguson** [comment]
@ncabatoff thank you for the reply! We've largely moved to not using CRLs and using the no_store option, so this is less pressing for us than it was, and I am unlikely to have time to make a PR for this in the immediate future, but hopefully I will have a chance at some point to do so! Thank you for the pointers on where in the code to look

**Comment by ixe013** [comment]
Hey @ncabatoff , any example of a test using the `PeriodicFunc` ? I was thinking of testing the code with something like this:
 1. Generate the CRL with a validity period slightly larger than the periodic func period. Say **75 seconds** if it triggers every 60s.
 1. Set the CRL renewal interval to **100 seconds** so that on the first `PeriodicFunc` call, the CRL is _not_ regenerated.
 1. Assert that the CRL was not regenerated on the first `PeriodiFunc` call
 1. Wait for the next call to `PeriodicFunc`
 1. Asset that the CRL was re-generated on the second call

**Comment by ncabatoff** [comment]
Hi @ixe013,

I can't think of any that I've written or worked with.  I searched based on name and found TestOIDC_PeriodicFunc, but I haven't dug into it to see if I like how it works or if I like it.  I look at our failing tests quite often and this one doesn't seem flaky, which is a common issue with our time-related tests, so that's something.

The strategy you outline above sounds fine to me.

**Comment by cipherboy** [comment]
@ianferguson and @ixe013 Automatic tidying is now completed in #16900! Give it a try and let us know what you think.

**Comment by ianferguson** [comment]
@cipherboy will do, thanks for working on that!
