### ISSUE TITLE
Vault DB size control options?

### ISSUE THREAD

**Issue by james-masson** [hashicorp/vault#785]
Hi,

We use Vault with both file backend and Consul backends - we have approx 30 mounts, each with 15-20 key-value pairs each. Each of these key-value pairs is just a short password.

We regularly see 350Mb database sizes and larger, perhaps a factor of 100 bigger than the data that is stored.
Much of the database volume seems to be for expired keys - and from looking at the backup sizes over the last 6 months, there seems to be cyclical expansion/contraction over each month - I assume there's some internal pruning going on, or perhaps some journal wrapping.
We don't use explicit key-expiry at the moment. Just the default TTL for all objects.

Any tips on how best to manage this for low memory/disk footprint? What tunables are there to help us achieve this?

**Comment by james-masson** [comment]
This is our Prod instance, so it's running 0.3.1 - could you expand a little, or point me to docs that explain what's new in the unreleased 0.4 that would be helpful?

I guess I'm just looking to understand a little about the mechanics of what's going on.

**Comment by jefferai** [comment]
It's hard for me to say what is actually going on without knowing where in Consul's K/V store you're seeing all of the data come and go. The two improvements that I was referencing are:

1. In 0.3, leases were removed from `generic`, but existing leases aren't properly cleaned up (which should be a constant value of data
2. In < 0.4, leader entries in HA setups would not always be properly cleaned up, so with a lot of leadership changes the number of these values could grow by a decent amount. This is fixed in 0.4, but again, the amount of data should mostly be increasing, not increasing and decreasing.

If you're seeing this in the file backends, it might be useful to get a `du -h` so we can figure out where the data is coming and going -- one of the backends, leader entries, etc.
