### ISSUE TITLE
AWS EC2 Instance Metadata Service V2 support

### ISSUE THREAD

**Issue by lcgkm** [hashicorp/vault#7924]
https://aws.amazon.com/blogs/security/defense-in-depth-open-firewalls-reverse-proxies-ssrf-vulnerabilities-ec2-instance-metadata-service/

**Comment by lcgkm** [comment]
https://github.com/terraform-providers/terraform-provider-aws/issues/10949

**Comment by lcgkm** [comment]
The latest aws-sdk-go use IMDSv2, we can migrate to IMDSv2 by upgrading aws-sdk-go.
https://github.com/aws/aws-sdk-go/blob/master/CHANGELOG.md#release-v12538-2019-11-19
https://github.com/aws/aws-sdk-go/pull/2958/files

**Comment by joelthompson** [comment]
I think this is a good and necessary thing for Vault to do. However beware that this can actually cause breaking changes for clients that are running in Docker containers. See, e.g., https://github.com/boto/botocore/issues/1892#issuecomment-555774288

**Comment by joelthompson** [comment]
I've submitted a PR to update to the latest aws-sdk-go in #7458 though I haven't fully tested that it actually uses the IMDSv2.

**Comment by tyrannosaurus-becks** [comment]
In this PR I've replaced all deprecated instantiations of the AWS client with supported one, including some for the `ec2` service, which ensures the new code will be picked up and used. The code I'm referring to is where the ec2 client gets a token from the instance metadata service v2. That PR's here: https://github.com/hashicorp/vault/pull/8060.

I'm thinking the only other places that need updating are these, where we're calling the instance metadata service directly rather than through a client:

- https://github.com/hashicorp/vault/blob/master/command/agent/auth/aws/aws.go#L193
- https://github.com/hashicorp/vault/blob/master/command/agent/auth/aws/aws.go#L219

Please let me know if I've missed anywhere so we can get those taken care of. Meanwhile I'll tackle those two spots.

**Comment by tyrannosaurus-becks** [comment]
All PRs needed to add support for this have been merged into master and will go out with the 1.4 beta. Thanks everyone!
