### ISSUE TITLE
Web Interface API vs Web inteface CLI list differences

### ISSUE THREAD

**Issue by mitm001** [hashicorp/vault#7970]
The Web Interface has the API activated from the Browser CLI. 
Every List command in the API refuses to work, even for Root token, returns with 
```
{
  "errors": [
    "1 error occurred:\n\t* unsupported operation\n\n"
  ]
}
```
yet entering the exact same command in the Browser CLI works fine.

Is there some trick to using the API command for lists?

There is a entry box that says

```
List - Return a list if `true`
```
but nothing works if entering text.

Maybe I am not using the API correctly but expected behavior would be just hit the Execute button without entering anything for the path since that is already set.

To test, open the 
```
GET​/auth​/approle​/role
Lists all the roles registered with the backend.
```
just hit the execute button. Fails.

Type the same thing into the Browser CLI
```
list /auth/approle/role
```

Works perfectly.

**Comment by FrankLambrette** [comment]
Hi,
I have encountered the same error, is there a solution to this?

**Comment by hashishaw** [comment]
Hi folks, thanks for your patience! From what I gather, the API you're referring to is the API Explorer located at `/ui/vault/tools/api-explorer`, pictured below?

<img width="824" alt="Screenshot 2023-11-15 at 1 29 15 PM" src="https://github.com/hashicorp/vault/assets/82459713/b44f9b29-a673-431b-8ae7-44b98fc0366f">

The interface for that page is completely generated from the OpenAPI spec, and there were some [improvements](https://github.com/hashicorp/vault/pull/21723) made in 1.15.0 specifically to allow better support for listing. I'm going to go ahead and close this out due to those changes, please feel free to open a new ticket if you find more issues!
