### ISSUE TITLE
Feature Request: Telemetry for root token

### ISSUE THREAD

**Issue by iusergii** [hashicorp/vault#7974]
**Is your feature request related to a problem? Please describe.**
As it mentioned in best practice - we revoked root token. And I'd like to have notification  in case it was generated again. 

**Describe the solution you'd like**
Having some metrics for root token would help to set a trigger. 

**Describe alternatives you've considered**
- I went over existing [telemetry](https://www.vaultproject.io/docs/internals/telemetry.html) and didn't find alternatives. Neither each of it has a label for root too. 
- Analysing audit logs.  

**Additional context**
We would like to notify Teams which not have access to Unseal Keys and therefore not including to re-generating process.

**Comment by michelvocks** [comment]
Hi @iusergii!

Thank you for opening this feature-request!

You've mentioned that an alternative solution would be to analyze audit logs. I think that is the best approach to watch for such certain events. Telemetry or metrics, in general, should be used to measure the average time spend to fulfill the specific action. 

I'm not necessarily against this feature-request but I'm wondering if a metric about the root-token creation process is really a good thing to have. Especially since we are already measuring the token creation process in general. 

Cheers,
Michel

**Comment by iusergii** [comment]
Hi @michelvocks,

Agreed, probably metrics wrong way to solve it.  I've proposed this as people already have alarms base on metrics (alarmmanager) and monitoring of audit logs will add additional source.  Which I'd like to avoid. 

I was thinking about counter for amount of root tokens which would also help with observability. 

Thank you,
Sergii

**Comment by michelvocks** [comment]
Hi @iusergii!

Sorry for the late reply.

> Agreed, probably metrics wrong way to solve it. I've proposed this as people already have alarms base on metrics (alarmmanager) and monitoring of audit logs will add additional source. Which I'd like to avoid.

I recommend to always monitor both channels (metrics & audit logs) in production environments. Both channels are similarly important to watch for especially for security reasons.

> I was thinking about counter for amount of root tokens which would also help with observability.

I think that could be helpful, indeed. 

Cheers,
Michel

**Comment by iusergii** [comment]
Got it, thank you for you feedback @michelvocks.
