### ISSUE TITLE
ACL to allow revoking certificates issued by a role

### ISSUE THREAD

**Issue by Lasering** [hashicorp/vault#7990]
**Is your feature request related to a problem? Please describe.**
I have a PKI secret backend with multiple roles configured. I would like to allow a bot/user to revoke certificates issued by the role A but not by the role B.

Currently there are two ways to revoke a certificate:

1. `vault write pki/revoke serial_number=<a serial number>`
2. Or if the role was configured to issue leases and we saved the lease when we generated the certificate: `vault write sys/leases/revoke lease_id=<the lease id>`

Granting delete on the `pki/revoke` would allow the bot/user to revoke every certificate issued by the pki, whether it was issued by role A or role B.

Granting delete on `sys/leases/revoke` with `allowed_parameters` set to something like `"lease_id" = ["pki/issue/roleA/*"]` would work but it is impossible to find the lease_id of a certificate.

**Describe the solution you'd like**
One of:

1. Implement a new ACL `pki/roleA/revoke` which would only accept serials of certificates which were emitted by role A.
2. Allow consulting the lease_id of a certificate. Something akin to [Read Certificate](https://www.vaultproject.io/api/secret/pki/index.html#read-certificate) but an authenticated endpoint which would also return the lease_id.

Ideally both solutions should be implemented. However given the documentation suggestion of not using leases for certificates I would prefer the first option.

**Comment by jefferai** [comment]
The lease id is constructed partially from the path that issued the lease. So you can do this already via the revoke-prefix API call (https://www.vaultproject.io/api/system/leases.html#revoke-prefix)

**Comment by Lasering** [comment]
That works to revoke all the certificates issued by a role. However I'm looking to the capability of revoking a single certificate. Or more explicitly to allow revoking any single certificate issued by a specific role.

**Comment by jsfrerot** [comment]
I would also add that it would be nice to revoke certificate for a specific subjet. We have had some bad configuration which created over 500k certificates for a few servers. And cleanup for those client is painfully slow.

**Comment by cipherboy** [comment]
@Lasering and @jsfrerot -- you'll be happy to know #16566 has merged. While this isn't an ACL role itself, it _is_ a new path which allows certificates to be revoked by proving possession of the private key corresponding to that certificate (and with #16564 which allows revoking `no_store=true` certificates, should solve the underlying use case). Users will take their key (and either serial number or certificate) and can revoke it themselves, assuming operators allow access to the new path, `/revoke-with-key`. Since this is a safe operation (relatively -- verifying the cert and key does impose some performance cost on the cluster and so high load at the endpoint could negatively impact operations), we'd generally recommend all (auth'd) users should have access to this.

Give it a try and let us know what you think!

**Comment by maxb** [comment]
There is substantial difference between the requested and implemented feature. IMO this shouldn't be closed as the provided feature does not answer the request.

It remains impossible to provide delegated authority to a bot or team of operators to handle revocation requests for a subset of certificates defined by a role. Private keys will generally not be available to revocation operators.

**Comment by maxb** [comment]
> I would also add that it would be nice to revoke certificate for a specific subjet. We have had some bad configuration which created over 500k certificates for a few servers. And cleanup for those client is painfully slow.

This use-case is a good illustration of a case when the private keys would not be available - and it has happened to me at work on multiple occasions - however I would also mention that in a case like this, you probably don't want to revoke the certificates at all - since that doesn't actually remove them from Vault's storage, and in fact causes Vault to store an extra copy of them in the revocation metadata - and would also cause the CRL size to grow a lot as well. So it's probably better overall to just ignore and not revoke certificates in this case.

**Comment by Lasering** [comment]
> There is substantial difference between the requested and implemented feature. IMO this shouldn't be closed as the provided feature does not answer the request.
> 
> It remains impossible to provide delegated authority to a bot or team of operators to handle revocation requests for a subset of certificates defined by a role. Private keys will generally not be available to revocation operators.

This exactly!

**Comment by cipherboy** [comment]
@maxb -- the requested functionality is practically infeasible to implement within Vault's present auth system. Hence this is the closest we'll probably get and why I'm comfortable with closing it.


<details>

<summary> For an explanation of why this is difficult... :-) </summary>

---

Within Vault, I don't believe we unambiguously map the same end-user to the same token or long-term identity within Vault. Different auth methods also complicate this for instance. This prohibits explicit delegation (within the realm of PKI) and means we have to rely on the existing ACL path-based policies. At best, we can probably introduce a new path structure (within the PKI plugin) to try to enable this...

This new path structure would end up being forward-applicable only. There's no way to retroactively match issued certs to existing issuance roles (either historically as it wasn't stored or presently as `sign-verbatim` is a thing, the role might've changed, the role might rely on templated user information, &c). So existing certs would have to be detected and probably forbidden from new endpoint use. That's... less than ideal, especially when you take incremental cluster upgrades into account. Plus, even if all the work was done to de-serialize the cert into something comparable with the existing format-- that's a lot of CPU+storage cycles to proactively do the upgrade (unless you do it lazily -- but then revisit the note about roles changing!).

You've also gotta upgrade the existing cert storage (or support both) -- the existing unrevoked cert entry is strictly the DER of the cert without any JSON blob/... extra metadata. This would then need to be handled by all read/... paths &c. Maybe this data could be maintained out of band though (for new certs or explicitly mapped certs...)...

You're now relying on the auth->path-based ACL->cert->role mapping.. How are roles handled when they're deleted? Do you maintain historical issuance roles and delegate auth from those roles to existing legacy paths? What happens when a new role is created with the same name? &c. At this point, maybe it is better to delegate on (new? upgraded?) issuance to a specific _revocation_ role within the PKI mount and let the global ACL take care of auth->revocation-role mapping... But how do you assign existing certs to new revocation-roles? Probably a global operator... in which case, why not just have them do the revocation? ;-)

Fundamentally, within the Vault system, this request technically is very difficult to implement well, with very limited benefits. See below about other approaches that I'd strongly recommend over this approach as requested. 

---

</details>

From a PKIX perspective, delegation of this type _usually_ occurs at the intermediate CA boundary (w.r.t. Vault, split into separate mounts, ACL appropriately -- they remain a trusted entity within the context of the intermediate but lack permissions across other intermediates by default) -- or you push the power all the way to the users (like many public CAs do, w.r.t. revocation via PoP mentioned in their CA operating guidelines or via ACME -- when their own internal operators aren't doing the revocation manually). This is a large part of why the public CA hierarchy includes many subordinate intermediate CAs, and I'd generally _encourage_ internal PKIs to mirror that behavior. Use separate, parallel intermediates to handle delegation to different groups within the larger company/use case, even if a single centralized operator owns running and these groups only control revocation.

Certain systems do have trusted third-party key-recovery capabilities (which can be emulated via K/V and fronting requests to PKI via a K/V stashing interposer) -- so this capability (PoP) would safely allow vault operators/bots (with existing trusted third-party key-recovery capabilities) to do this.

A "semi-trusted" or "trusted-for-a-subset" third party entity on its own doesn't really exist within the standardized CA/RA system. Creating other intermediates should be the preferred approach than a KRA system, IMO. And it is relatively cheap, assuming a finite number of bots/operators and assuming under a common parent, relatively transparent to the end user. :-)

---

Regarding second comment: I fully agree that revoking the certificates is the wrong approach and this is not meant to address that -- nor would the original ask. (It really belongs in a separate issue!) With the BYOC capabilities mentioned earlier, you can set `no_store=true` globally (and safely!) while retaining the ability to revoke certs that you care about (and rely on Vault's audit capabilities for issuance search from a delegated audit-logging search system). This doesn't help the clean up (until these certs expire...) but it does help to prevent this type of mistake.

---

My 2c. but I'm comfortable closing this 3+ year old request knowing that there's very little likelihood of this being implemented by us. Someone else is welcome to try, but it likely requires extensive discussion with the core+cryptosec teams of _how_ before any code is proposed. :-)

**Comment by Lasering** [comment]
1. Certificates are revoked by serial number.
2. I'm assuming serials behave like global ids.
3. When a certificate is issued via a role save the serial of the issued certificate in the storage (this storage must be associated with the role so it can be retrieved later).
4. Create a new path `pki/revoke/:role_name serial_number=<a serial number>`.
5. This path checks the storage associated with the role to see if `<a serial number>` exists. If is exists then certificate revocation is allowed and performed. Otherwise return an 401 Unauthorized (or the equivalent in Vault terms).

All the other scenarios:
> There's no way to retroactively match issued certs to existing issuance roles (either historically as it wasn't stored or presently as sign-verbatim is a thing, the role might've changed, the role might rely on templated user information, &c)

Would behave as they do now, that means, they would require manual intervention using a token with the required permissions to revoke any certificate.

**Comment by maxb** [comment]
Hi @cipherboy,

Here's what I was expecting to be the resolution of this feature request:

* Store the role name used to issue each certificate, with the certificate - we want this anyway to be able to better understand our users' behaviour, and could make this a standalone feature request.
* Provide a new API endpoint e.g. `/revoke-by-role/:role_name` which only revokes if the role name in the path matches the stored  role name.

Yes, this means it won't work for old certificates. I don't care about that - it's simply a necessary cost of creating a new feature. Eventually old certificates will expire and be tidied, so after one full period of maximum TTL (plus a tidy), the migration will be complete in existing clusters.

This seems like a pretty simple technical implemenation to me.

As for roles being deleted - doesn't matter, the new `revoke-by-role` endpoint just needs to be documented that it specifically works by role name only.
