### ISSUE TITLE
Configuring Mongo DB in Vault with kubernetes

### ISSUE THREAD

**Issue by abhi-dwivedi** [hashicorp/vault#8004]
HI All

Can anyone help to configure mongo db application and generate dynamic secrete .

Vault and application deployed on same k8s cluster

**Comment by michelvocks** [comment]
Hi @abhi-dwivedi!

I recommend having a look at our documentation page: https://www.vaultproject.io/docs/secrets/databases/mongodb.html
If you already had a look, it would be great to get more information about the error that you face or what exactly your problem is.

Please remember that the GitHub issue tracker is reserved for bugs/feature-requests only.
I will close this issue for now but feel free to ask this question again at our [Discussion Forum](https://discuss.hashicorp.com/c/vault).

Cheers,
Michel
