### ISSUE TITLE
Implement short lease password for Windows?

### ISSUE THREAD

**Issue by SleeperSmith** [hashicorp/vault#803]
http://blogs.msdn.com/b/davbosch/archive/2006/06/30/651959.aspx

Seems like that will enable implementing what's been done for SSH?

**Comment by jefferai** [comment]
Hi @SleeperSmith ,

Alternative credential providers have been around in Windows for a very long time, but I don't think they will be on the roadmap for Vault in a fashion similar to SSH unless someone takes on the responsibility of implementing it. That said, the OTP style of authentication with the Vault SSH backend doesn't explicitly rely on SSH, so someone could do this without too much in the way of needing Vault changes.

**Comment by ixe013** [comment]
Don't get fooled by the name [Credential Provider](https://msdn.microsoft.com/en-us/library/windows/desktop/mt158211(v=vs.85).aspx):

> It is important to note that credential providers are not enforcement mechanisms. They are simply used to gather and serialize credentials, submitting them for authorization. The local authority and authentication packages will handle and any necessary security enforcement.

Credential Providers are really meant for humans to use. They collect credentials which are sent to the Local Security Authority, which in turn with forward the credentials to an Authentication Package. I don't see what Vault could do here.

If Vault wanted to provide a Credential Provider, it would need to:

1. Create an authentication package that forwards the authentication descision to Vault. It would create a Windows token (nothing to do with Vault tokens). For a number of reason, that Windows token would not be valid on the network.
1. Create a custom Credential provider that collects credentials for the Authentication Package to use
1. Deploy both CP and AP to each machines that needs it.

What if I am logged another computer and want to access a network share? Credential Providers will not help you there.


It might make more sense not to touch any of that, but to have a Vault Secret Engine that creates LDAP accounts on the fly, setting group membership and expiry time on each. That LDAP could be Active Directory. It would allow to use the built-in Windows authentication mechanism instead of duplicating it.

Could you elaborate on the use case you are facing?

**Comment by jefferai** [comment]
@ixe013 thanks for all of the helpful information! If the OP can provide more info and there is interest in picking this up we can reopen.
