### ISSUE TITLE
Vault cannot create a session when configured with Consul and a remote datacenter

### ISSUE THREAD

**Issue by slackpad** [hashicorp/vault#811]
When Vault is configured with a Consul backend and a remote datacenter, but configured to use a local agent in another datacenter, it will not be able to create sessions:

![image](https://cloud.githubusercontent.com/assets/673509/11509027/9e3329a2-9810-11e5-9c0d-9bbe0edafc54.png)

This is because the Consul API client defaults the node name to the name of the local agent, and then forwards the request on to the remote DC, which doesn't have a record of that node.

It's not super clear what the best fix is here. We may want to improve the Consul agent to return an error if the DC is not equal to the agent and a node isn't given in the body (see https://github.com/hashicorp/consul/issues/1459). Given that Consul doesn't support cross-DC sessions, Vault would need to register a node in the remote DC and manage its own session against that, which seems pretty ugly. We could also consider some kind of cross-DC session support in Consul. Alternatively, we could drop the DC configuration option for Vault, since it doesn't really work because of this limitation.

This came up from https://groups.google.com/forum/?utm_medium=email&utm_source=footer#!msg/vault-tool/QJbUFqF3RGU/bBfPleuJBwAJ.

**Comment by jefferai** [comment]
As the Consul expert I'd rather leave it up to you; if you think https://github.com/hashicorp/consul/issues/1459 when fixed will make the datacenter parameter useful, let's keep it; if you don't think it will ever be useful, we'll drop it.

**Comment by slackpad** [comment]
If we do https://github.com/hashicorp/consul/issues/1459 it'll just make the error message better :-) I'll give this some thought and /cc @armon and @ryanuber to see if he they any ideas on this one from a Consul POV as well.

**Comment by vishalnayak** [comment]
Issues that are not reproducible and/or not had any interaction for a long time are stale issues. In order to provide faster responses and better engagement with the community, we strive to keep the issue tracker clean and the issue count low. In this regard, our current policy is to close stale issues after 30 days. Closed issues will still be indexed and available for future viewers. If users feel that the issue is still relevant, we encourage reopening them.
   
Please refer to our [contributing guidelines](https://github.com/hashicorp/vault/blob/main/CONTRIBUTING.md) for details on issue lifecycle.
