### ISSUE TITLE
vault pki Revoke

### ISSUE THREAD

**Issue by wongkafai** [hashicorp/vault#8115]
1. How to setup pki revocation time

1. problem for with Vault write pki / tidy tidy_cert_store = true tidy_revoked_certs = true ??

        WARNING! The following warnings were returned from Vault:
        * Tidy operation successfully started. Any information from the operation
         will be printed to Vault's server logs.

{"time":"2020-01-08T02:31:18.345564346Z",
"type":"response",
"auth":{"client_token":"hmac-sha256:2c745d30c19c1b9960a0dbf26cd5f08bfec5b98808215e1032542189be082cfd",
"accessor":"hmac-sha256:1a553e72c2382a9087f7235e0659e36d1cea4bdbae216fab2a14de9b9efe7a17"
,"display_name":"root","policies":["root"],"token_policies":["root"],"token_type":"service"},
"request":{"id":"545de881-6d2f-6c27-1cbe-e3331161a54d","operation":"update",
"client_token":"hmac-sha256:2c745d30c19c1b9960a0dbf26cd5f08bfec5b98808215e1032542189be082cfd",
"client_token_accessor":"hmac-sha256:1a553e72c2382a9087f7235e0659e36d1cea4bdbae216fab2a14de9b9efe7a17",
"namespace":{"id":"root"},
"path":"pki/tidy",
"data":{"tidy_cert_store":"hmac-sha256:65c2b0766a88922a89fa5505d13e054497d16e3a70accabc16f2805c34c4b26d",
"tidy_revoked_certs":"hmac-sha256:65c2b0766a88922a89fa5505d13e054497d16e3a70accabc16f2805c34c4b26d"},
"remote_address":"172.31.18.141"},
"response":{"data":{"http_content_type":"hmac-sha256:2ad599bc0a2558afccf533447f385cf56bb957a0325b107e4d3d60d3145e80fa",
"http_raw_body":"hmac-sha256:32b0ac8608a86a490099de51abfbede95d96c64bbfafd67c090a7c28efd11049",
"http_status_code":202}}}

3. revoked certificate make it insecure?

e.g.
vault secrets enable pki

vault secrets tune -max-lease-ttl=240h pki

vault write pki/config/urls \
issuing_certificates="http://172.31.18.141:8200/v1/pki/ca" \
crl_distribution_points="http://172.31.18.141:8200/v1/pki/crl"

vault write pki/root/generate/internal \
common_name="test Root CA" \
ttl=240h

vault write pki/roles/allow-all-domains \
allowed_domains=test.com \
allow_subdomains=true \
max_ttl=24h

vault write pki/issue/allow-all-domains common_name="www.test.com"

vault write pki/tidy tidy_cert_store=true tidy_revoked_certs=true

**Comment by catsby** [comment]
Hello - Are you experiencing an issue here or are you looking for guidance? If you're looking for usage, help, or otherwise guidance you may have more success asking in our user forums:

- https://discuss.hashicorp.com/c/vault/30

I'll try to answer the questions I see:

> 1. How to setup pki revocation time

Revocation time is determined by the `TTL`. Typically root and intermediate certs have longer TTLS, and then the certs generated by writing to roles are typically shorter. Our documentation on the PKI secret engine as well as our Learn site have good tutorials that demonstrate this:

- https://www.vaultproject.io/docs/secrets/pki/index.html
- https://learn.hashicorp.com/vault/secrets-management/sm-pki-engine

> 2. problem for with Vault write pki / tidy tidy_cert_store = true tidy_revoked_certs = true ??

I'm not sure I see an issue with the message you posted here. I believe the warning message is normal, and it's intent is to communicate that while the command has returned, the process of running tidy itself may take more time and will run in the background, and has not necessarily completed at the time that the command returned that message. 

> 3. revoked certificate make it insecure?

Revoked and expired certificates will fail to verify when used. 

I'm going to close this for now as I don't believe it represents an issue with Vault.
