### ISSUE TITLE
Connection refused while Configure the AWS Secrets Engine

### ISSUE THREAD

**Issue by manjeetsorout** [hashicorp/vault#8148]
I'm running the following command :
:~$ vault secrets enable -path=aws aws

And I'm getting the following error:

Error enabling: Post http://127.0.0.1:8200/v1/sys/mounts/aws: dial tcp 127.0.0.1:8200: connect: connection refused

Kindly resolve this issue.

**Comment by michelvocks** [comment]
Hi @manjeetsorout!

This error message indicates that the CLI is unable to contact your remote Vault server. 
Please make sure that your Vault instance is listening on http://127.0.0.1:8200.

I also recommend asking these kinds of questions via our [discussion forum](https://discuss.hashicorp.com/c/vault) since the issue tracker is reserved for feature requests and bugs.

Cheers,
Michel

**Comment by michelvocks** [comment]
Hi @manjeetsorout!

I'm going to close this issue due to inactivity. Feel free to open a new issue if you hit the same issue again in the future. 

Cheers,
Michel
