### ISSUE TITLE
LIST method is returning an error in VERSIONED KV secrets engine at /secret path in vault 

### ISSUE THREAD

**Issue by manjeetsorout** [hashicorp/vault#8224]
***I'm running the following command:
curl --header "X-Vault-Token: <token_value>" --request LIST http://127.0.0.1:8200/v1/secret/metadata/my-secret

###ERROR i'm getting : {"errors":[]}

required ouput: 
{
  "data": {
    "keys": ["foo", "foo/"]
  }
}

kindly resolve this issue

**Comment by ncabatoff** [comment]
I think given the output you say you're expecting, you should be using a
GET rather than a LIST.

**Comment by catsby** [comment]
Hello - can you share the kv path values were written to? 

If the paths are is `secret/my-secret/foo` and another kv entry at `secret/my-secret/foo/:something` , then the `LIST` should return as you describe.

If the paths are actually `secret/metadata/foo` and `secret/my-secret/foo/:something` , then the URL would be `http://127.0.0.1:8200/v1/secret/metadata/metadata/my-secret`

Basically, if there are 2 paths and the base of them both is literally `secret/metadata` as the folder containing them, then in order to list the keys you'll need another `metadata` in the url.

**Comment by catsby** [comment]
Hello - we haven't heard back in some time, so we're going to close this issue for now. If you have more information please let us know by opening a new issue, and optionally referencing this one. Thanks!
