### ISSUE TITLE
SSH PKI support

### ISSUE THREAD

**Issue by hashbrowncipher** [hashicorp/vault#823]
SSH keys can be signed, forming SSH certificates.  User certificates authenticate users to hosts, and host certificates authenticate hosts to users.  Vault could be used to store an SSH CA key, and then to sign certificates on behalf of authorized users or hosts.

**Comment by jefferai** [comment]
It is quite unfortunate that the SSH community used similar but just slightly different file formats than standard X509 certificate formats, as otherwise it would be pretty simple to enhance the `pki` backend to do this.

**Comment by olly** [comment]
I also asked about this on the mailing list: https://groups.google.com/d/topic/vault-tool/9AOMgfEn1E0/discussion

**Comment by blalor** [comment]
I think @armon's response in that thread is reasonable for granting a user access to a remote host, but it doesn't solve the problem of authenticating the server to the client.

https://www.digitalocean.com/community/tutorials/how-to-create-an-ssh-ca-to-validate-hosts-and-clients-with-ubuntu

This is something I'd definitely like to see added alongside the PKI backend.

**Comment by gmarkey** [comment]
Is anyone able to provide an estimate of how much work they believe would be required to implement this?

**Comment by gmarkey** [comment]
Posted [$500](https://www.bountysource.com/issues/28972986-ssh-pki-support) bounty for this

**Comment by jefferai** [comment]
@gmarkey We have an implementation internally and as such are unlikely to accept a PR resulting from the bounty.

**Comment by gmarkey** [comment]
@jefferai well that's unfortunate. Do you have an ETA for release?

**Comment by jefferai** [comment]
No, I don't. Someone is welcome to submit a PR; I am specifically discouraging a bounty, since those usually only pay out if the code is merged and it may not be if we decide to use our internal code instead.

If someone is interested in working on this, get in touch.

**Comment by gmarkey** [comment]
@jefferai understood; would you prefer me to take the bounty down? We still see value in this, and remain willing to provide the bounty if this issue can be resolved.

**Comment by jefferai** [comment]
My main issue with the bounty is that most of the time if someone from the community takes on a large task and runs with it without going over design with us the end result is not something we can merge without extensive refactoring. So if someone takes on that task and expects the bounty and doesn't talk to us and it's rejected, it's a sad time all around.

I'd much prefer if someone interested wants to take the code we have internally and fix it so that it's done properly. Right now someone did it for their own uses but, unfortunately, introduced the same problem: they didn't talk to us first about design, and it's not something we'll merge as-is.

**Comment by roidelapluie** [comment]
@jefferai this can be closed

**Comment by vishalnayak** [comment]
Fixed by #2208
