### ISSUE TITLE
documentation vault/website/pages/guides/identity/policies.mdx out of date

### ISSUE THREAD

**Issue by Justin-DynamicD** [hashicorp/vault#8319]
when working with polies in vault 1.3.2, I found the following [info on working with policies](https://www.hashicorp.com/resources/policies-vault) you come up with a rather decent admin defautl template like so:

```
# Manage auth backends broadly across Vault
path "auth/*"
{
  capabilities = ["create", "read", "update", "delete", "list", "sudo"]
}

# List, create, update, and delete auth backends
path "sys/auth/*"
{
  capabilities = ["create", "read", "update", "delete", "sudo"]
}

# To list policies - Step 3
path "sys/policy"
{
  capabilities = ["read"]
}

# Create and manage ACL policies broadly across Vault
path "sys/policy/*"
{
  capabilities = ["create", "read", "update", "delete", "list", "sudo"]
}

# List, create, update, and delete key/value secrets
path "secret/*"
{
  capabilities = ["create", "read", "update", "delete", "list", "sudo"]
}

# Manage and manage secret backends broadly across Vault.
path "sys/mounts/*"
{
  capabilities = ["create", "read", "update", "delete", "list", "sudo"]
}

# Read health checks
path "sys/health"
{
  capabilities = ["read", "sudo"]
}

# To perform Step 4
path "sys/capabilities"
{
  capabilities = ["create", "update"]
}

# To perform Step 4
path "sys/capabilities-self"
{
  capabilities = ["create", "update"]
}
```

The problem is that many of these paths do not appear to work anymore.

For example: `sys/policy` will not control policy access, instead `sys/policies` now seems ot take it's place.

I've been using trial and error to update these paths locally, but it would be ideal to update this page instead. (alternatively, is there a way to browse from /?  I believe its disabled by default, which makes discovery a bit trial and error)

**Comment by adongy** [comment]
To add to this issue, seems like the `sys/policy` and `sys/policies/acl` behave very similarly.

https://github.com/hashicorp/vault/blob/f868e231b249d6c08ec5addaae2eeb65839e7f84/vault/logical_system_paths.go#L1352-L1448

I suppose this is because the Enterprise edition of Vault uses EGP and RGP policies, thus the need for `sys/policies/...`. However documentation seems to vary between the two uses.

Examples:

- `sys/policies/acl` https://learn.hashicorp.com/vault/identity-access-management/iam-policies
- `sys/policy` https://www.vaultproject.io/docs/concepts/policies/#default-policy (linked from the above tutorial)

Is there a deprecation plan for `/sys/policy`, or plans to update all documentation to point to use one endpoint or the other?

Note the vault binary uses `/sys/policies/acl` internally: https://github.com/hashicorp/vault/blob/master/api/sys_policy.go

Thanks!

**Comment by aphorise** [comment]
Hey @Justin-DynamicD have you consulted the more [recent policies documentation](https://www.vaultproject.io/docs/concepts/policies#policy-syntax) and the [learn guides](https://learn.hashicorp.com/tutorials/vault/policies) on this topic?

I'm curious if this request should be closed or if not what may be next.

**Comment by aphorise** [comment]
Closing due to no response. Please re-open if relevant still.

**Comment by Justin-DynamicD** [comment]
2 years later I get an answer ... closed for not responding in 7 days. ;)  That gave me a chuckle.
