### ISSUE TITLE
vault service registration in consul service registry

### ISSUE THREAD

**Issue by szkiba** [hashicorp/vault#833]
A have a single node consul server (for development purpose) and a single node vault server using consul as storage backend (yes I know the vault's dev mode, but I1d like to use real consul backend).

It seem to work. I can use command line vault tool. I see the key/value entries in consul (under /vault/).
But in consule's service registry there is no "vault" entry.
Is it normal or bug ? 
Does vault automatically register itself to consul service registry ? Or I have to write an external script to register vault ? (I didnt found any vault config option to force registration)

**Comment by jefferai** [comment]
Hi @szkiba ,

Vault does not automatically register itself. While in theory it could, it would entail implementing a number of config options that can be in service definitions in order to pass them through, so at the moment it leaves that up to the user to simply configure with Consul directly.

In our internal instance, we have simple `json` service files on the local Consul agent:

```json
{
  "service": {
    "name": "vault",
    "port": 8200
  }
}
```

Hope that helps!
