### ISSUE TITLE
Misplace unseal keys - VAULT

### ISSUE THREAD

**Issue by narayan8291** [hashicorp/vault#835]
I misplace the unseal keys for my vault production deployment. I am not worried about the secrets its holding but need a new vault established on the same machine. I tried doing it by both installing and compiling it from source but no luck as it says * Vault is already initialized. 

What is the best way to get a new vault on the same machine (i am using a VM) ? Also curious how VAULT is designed and is it per machine basis ?

**Comment by jefferai** [comment]
In order to reinitialize vault you will need to remove the backend storage. How you do it depends on which backend you are using. For instance, if it is the `file` backend, remove the entire specified path; if it is `consul`, do a recursive delete on the entire prefix. Alternately, point the path/prefix to a different location.

**Comment by narayan8291** [comment]
Thanks.

**Comment by jefferai** [comment]
Sure.

**Comment by perfecto25** [comment]
deleting the "file" backend worked, I also had to stop and start vault service, then re-init worked
