### ISSUE TITLE
OIDC auth issue

### ISSUE THREAD

**Issue by sri53** [hashicorp/vault#8376]
I am integration vault with azure active directory. While login I received below error, Any idea?

Token verification failed. error validating claims: aud claim does not match any bound audience

**Comment by catsby** [comment]
Hello! Please post questions on the discussion forum (https://discuss.hashicorp.com/c/vault) rather than in GitHub issues.

The discussion forum gets a lot more eyes on any particular question. You'll get an answer faster, not slower, by taking advantage of the suggestions and answers provided by the wealth of experience that long-time users and devs bring to the forum.

It also prevents problematic issue workflows for questions where either the issue is closed immediately but then discussion continues on a closed issue; or, the issue is not closed, discussion dies down, and the issue remains open indefinitely waiting for further potential replies.

Thanks!
