### ISSUE TITLE
VAULT_ADDR should allow sockets

### ISSUE THREAD

**Issue by fuero** [hashicorp/vault#8378]
**Describe the bug**
Vault in agent (auto-auth) mode supports listening on sockets, Vault CLI client doesn't support consuming it (but consul-template does :-) ):

**To Reproduce**
1. Set up vault agent auto-auth, have it listen on a unix socket, e.g. /var/run/vault-agent/vault-agent.sock
2. Run vault cli:
```bash
VAULT_ADDR=unix:/var/run/vault-agent/vault-agent.sock VAULT_TOKEN='' vault list secret/
Error listing secret/: Get unix:///var/run/vault-agent/vault-agent.sock/v1/secret?list=true: unsupported protocol scheme "unix"
```

**Expected behavior**
regular operation as if VAULT_ADDR contained a HTTP URL.

**Environment:**
* Vault CLI Version (retrieve with `vault version`): 1.3.2

**Comment by drawks** [comment]
It really is a puzzling oversight to have the agent present a unix domain socket and not allow the client to connect to it. I would think that this would be a natural way to extend access to vault secrets via auto-auth to userspace limited via user/group membership.

**Comment by drawks** [comment]
I've confirmed that the vault client does indeed accept unix domain sockets using `VAULT_ADDR=unix:///path/to/vault.socket` as @ncabatoff indicated (at least on version 1.3.4).

Technically I think this issue is resolved, however I think there are several places in the documentation that need to be touched up. Currently there are no examples I could find in the online documentation that explicitly show how to use unix domain sockets in the vault client.

For that matter, I also couldn't find anything documenting that you can set a unix domain socket listener in the agent aside from a config block in one of the examples which shows a unix domain socket listener. The bulk of the listener config documentation in the agent points back to the listener config docs for server, but these two components actually appear to use different code under the hood, the vault server AFAICT doesn't support UDS listeners.

**Comment by nomaster** [comment]
Doesn't work for me, either:
```shell
$ VAULT_ADDR=unix:///run/vault-agent.sock vault status
Error checking seal status: Get "http://%2Frun%2Fvault-agent.sock/v1/sys/seal-status": dial unix /run/vault-agent.sock: connect: protocol wrong type for socket
```

**Comment by nomaster** [comment]
Maybe it has to do with https://github.com/hashicorp/vault/pull/11904

**Comment by aphorise** [comment]
@fuero - can you confirm if you've rested following the instructions above https://github.com/hashicorp/vault/issues/8378#issuecomment-982447067 ?

Maybe some documentation updates are required to note avaible unix socket in the case of agents only.

**Comment by fuero** [comment]
Yes, it works fine like @nomaster stated.
