### ISSUE TITLE
Change lease_duration for dynamic secrets created in aws backend

### ISSUE THREAD

**Issue by narayan8291** [hashicorp/vault#841]
I have tuned the aws backend to have a default ttl of 360000 and max ttl of 720000. 

vault mounts
Path        Type       Default TTL  Max TTL   Description
aws/        aws        360000       720000    

I created a policy and created a role called api_roles
vault write aws/roles/api_users policy=@aws_policy.json
Success! Data written to: aws/roles/api_users

I even wrote the lease and max lease for aws/config/lease, 
vault write  aws/config/lease lease=2400h lease_max=4800h

Now, when I create a set of credentials, the lease duration is the default value 3600. 
vault read aws/creds/api_users
Key            	Value
lease_id       	aws/creds/api_users/c240068b-402d-335c-da8a-97bde4e88231
lease_duration 	3600
lease_renewable	true
access_key     	x
secret_key     	y

Can I change the lease duration for these aws tokens.

**Comment by jefferai** [comment]
Currently the AWS backend doesn't support the default value from mount tuning. You can use the `aws/config/lease` endpoint to configure it. See the documentation (https://vaultproject.io/docs/secrets/aws/index.html) for all available config options.

**Comment by Xopherus** [comment]
Is this on the roadmap @jefferai?

**Comment by jefferai** [comment]
@Xopherus It's been supported for a long while :-)

**Comment by Xopherus** [comment]
@jefferai I think I just asked if users would be able to configure the TTLs using mount tuning, not the specific AWS backend operation. I think there's definitely some positives in having consistent configuration mechanisms - especially when you're dealing with a tool that is difficult to automate the setup process (by design). By this I mean you have to be careful using infrastructure as code for Vault because you don't want secrets lying around in terraform files! In the past my team was really just manually running Vault CLI commands when adding new mounts / configuring them, etc. When we were doing that I was really concerned about this issue because it was a pain for us to go to the docs to figure out how to configure a new backend.

Recently I have developed some tooling to automate most of the process so we don't have to start from scratch every time (btw I think automating your vault setup for DR purposes would be super valuable to discuss in another issue if it hasn't already). So it really doesn't actually matter for me how to configure the AWS backend, it just has to match the Vault API. Anyway, just wanted to let you know I've come around to agree with you that this is a non-issue :)

**Comment by jefferai** [comment]
It is not supported via tuning. I'd like for it to be but it isn't high on our priority list, so a PR would be the fastest way to get such support.

**Comment by myoung34** [comment]
Shouldnt this be reopened since its not supported but being requested?
