### ISSUE TITLE
Vault should not crash if telemetry is down

### ISSUE THREAD

**Issue by krish7919** [hashicorp/vault#8463]
**Describe the bug**
Vault is dependent on the `dogstatsd` service in our cluster, and crashes in a loop at startup if that service is unavailable.

**To Reproduce**
Define a `telemetry` configuration in Vault configuration file; but let this service be absent.

**Expected behavior**
Vault should still proceed to start and work if it is unable to send metrics.

**Environment:**
* Vault Server Version (retrieve with `vault status`):
```
# vault status
{
  "type": "shamir",
  "initialized": true,
  "sealed": false,
  "t": 3,
  "n": 5,
  "progress": 0,
  "nonce": "",
  "version": "1.2.2",
  "migration": false,
  "cluster_name": "XXX",
  "cluster_id": "XXX",
  "recovery_seal": false
}
```

* Vault CLI Version (retrieve with `vault version`):

```
# vault --version
Vault v1.2.2
```

* Server Operating System/Architecture:
Running as a pod in K8s.

Vault server configuration file(s):

```json
...
"telemetry": {
    "disable_hostname": true,
    "dogstatsd_addr": "dogstatsd.default.svc.cluster.local:8125",
    "dogstatsd_tags": [
      "'cloud_env:dev'"
    ]
  }
...
```

**Additional context**
Vault is a critical service and in general should not be dependent so tightly on other services being available.

**Comment by krish7919** [comment]
Do we have an update on this?

**Comment by krish7919** [comment]
Is there a way to configure telemetry _after_ Vault is launched?

**Comment by krish7919** [comment]
Any update?

**Comment by krish7919** [comment]
Will this be taken up?

**Comment by supra08** [comment]
@mladlown I'm looking to start contributing to Vault and would like to take this up.

**Comment by radiohead** [comment]
Hey @catsby @mladlow - I've done some preliminary investigation here and it looks like this only happens when using DogStatsD or Stackdriver providers - those fail immediately in `configutil.SetupTelemetry` code [here](https://github.com/hashicorp/vault/blob/master/internalshared/configutil/telemetry.go#L312) and [here](https://github.com/hashicorp/vault/blob/master/internalshared/configutil/telemetry.go#L322) respectively.

The other providers don't fail immediately because they establish the connection asynchronously, which is an even bigger issue, since it may not be obvious to the operator that their telemetry config is wrong (e.g. a misspelled endpoint / firewall blocking connections, etc.).

I'm not quite sure what would be the best approach here. One option is to assume that problems with telemetry sinks are not critical and continue starting Vault even if sinks fail to start, as suggested by @krish7919. Another would be to introduce an extra configuration / command-line flag that would have to be set explicitly to ignore telemetry issues on startup.

I would like to hear your thoughts on that.

**Comment by krish7919** [comment]
I would suggest to log an error on telemetry failure and proceed as usual. We should ideally have all providers establish connection asynchronously.

Vault ideally is the first system to be started/deployed, and we should not have it depend on any other systems to avoid cyclical dependency.

**Comment by raskchanky** [comment]
I agree with @krish7919 on this one. I think it's reasonable to expect Vault to start, even if telemetry is down. The behavior of statsite or statsd in this case seems ideal to me, and it makes sense that the behavior should be consistent across telemetry providers.

I'm interested to hear @mgritter's thoughts as well.

**Comment by mgritter** [comment]
I think it is specific errors that cause this, not just failure to connect to the telemetry server.  For example, I run Telegraf locally to collect stats (using the dogstatsd driver), and when Telegraf is not started, Vault comes up fine anyway.

So I suspect the problem is that the DNS lookup returns an error? That is less clearly "telemetry is not up" and closer to "there's an error in your config file" in a static environment. I'm not as familiar with K8S, but  I can understand that the service address might not resolve until later. I can't think of a good way to clearly distinguish the two cases.

I agree it would be better, on balance, to treat DNS lookup failure as non-fatal; we could probably create a wrapper around the current sink that does that.  Probably it should be fixed in go-metrics so that this capability is available to the other HC products using it.

But, I'm concerned that if the client library treats DNS lookup failures as fatal it might react badly later to DNS failures or DNS changes, so it might be worth validating that the client library is doing the right thing (and maybe even making a ix there.)

Note that StackDriver (aka Google Cloud Operations) is a Google-provided metrics.Sink implementation, not part of go-metrics.

**Comment by radiohead** [comment]
@mgritter good point about the DNS - I haven't traced it that far before, but I've done a quick check now and you were correct - the DNS resolution is indeed the problem.

More specifically for the DogStatsD case it's the `net.ResolveUDPAddr("udp", addr)` that is failing [here](https://github.com/DataDog/datadog-go/blob/v3.2.0/statsd/udp.go#L31).

I also agree that this should be solved in the client library, so the fix should really be done in https://github.com/DataDog/datadog-go and there seems to be some work related to this already (see e.g. https://github.com/DataDog/datadog-go/pull/61).

The downside here is that getting the fix upstream will require fixing it in DD library first, then updating go-metrics and then updating the dependency in Vault. However, if that's not an issue I can start working on that.

**Comment by krish7919** [comment]
If anyone is still looking at this, we can now configure Datadog to connect to Vault and not vice versa by enabling the Datadog Vault integration, which scrapes prometheus metrics from Vault.

I think this is still a valid issue, although this breaks the cyclic dependency for my sepcific use case.

**Comment by aphorise** [comment]
There's been a number of improvements to telemetry since you'd raised this request and I believe that this issue is no longer relevant in the context of recent (1.11.x+) versions of Vault.

Hey @krish7919 - kindly confirm if this issue still relevant for you or if it can be closed?

**Comment by krish7919** [comment]
> Hey @krish7919 - kindly confirm if this issue still relevant for you or if it can be closed?

@aphorise Thanks, although as per https://github.com/hashicorp/vault/issues/8463#issuecomment-737542543 this isn't relevant to me anymore. Thanks!

**Comment by aphorise** [comment]
@krish7919 so do you feel it's okay to close this issue or should some special note or update be made to the [telemetry page](https://www.vaultproject.io/docs/configuration/telemetry)?

**Comment by krish7919** [comment]
We can close this one.
