### ISSUE TITLE
Please make the UI build compatible with NodeJS >= 12

### ISSUE THREAD

**Issue by tsarna** [hashicorp/vault#8504]
The Vault UI cannot be built with NodeJS >= 12, which creates packaging difficulties and results in the UI being disabled on Alpine Linux, and perhaps elsewhere. See:

https://gitlab.alpinelinux.org/alpine/aports/issues/11222

NodeJS 12.x is the current LTS release

**Comment by jefferai** [comment]
Actually Node 10 is still in active mode and flips to maintenance in about two months (https://nodejs.org/en/about/releases/) and is a long way out from being unsupported. Separately from us supporting Node 12, Alpine should really be supporting both releases. This is currently an artificial limitation being imposed by them.

**Comment by Conan-Kudo** [comment]
I'm trying to build Vault for RHEL/CentOS 9, which provides only Nodejs 16. There's basically ***no*** way for me to build this because the asset build breaks. I attempted to try to get Nodejs 10 working, but it requires Python 2, which not available in RHEL 9. And I can't build Python 2 because it's not compatible with OpenSSL 3.0. And that's where I say I'm done, because I'm not getting into crypto libraries.

At this point, I implore that Vault fixes this so that it works with a maintained LTS Nodejs version. Additionally, I would like for Vault to bundle generated assets in the source tarball per #7350 and #7770.

**Comment by hashishaw** [comment]
Hello! We have bumped our required node version to >=14 as of #[12049](https://github.com/hashicorp/vault/pull/12049)
I'm closing this out but please open a new issue if you run into more problems with the build.
