### ISSUE TITLE
Kerberos auth instructions for use on Windows OS which is AD-domain-joined

### ISSUE THREAD

**Issue by erickufrin** [hashicorp/vault#8536]
Kerberos authentication is a new feature for Vault. But the documentation provides zero instructions on how to utilize it on a Windows-domain-joined system. Are we supposed to figure that out on our own?

**Describe the solution you'd like**
A clear and concise description of how to use Vault Kerberos authentication on a Windows-domain-joined OS.

**Describe alternatives you've considered**
We dont have time to figure it out on our. Documentation for how to use this should be provided by Hashicorp!

**Explain any additional use-cases**
We have 10,000+ windows servers in our environment which are domain-joined. We would like to authenticate to Vault using Kerberos from AD as all of these are domain-joined..

**Comment by tyrannosaurus-becks** [comment]
Hi! Thanks for posting this issue. 

We haven't released any docs regarding it yet because the feature is in beta, and the docs go out at GA. That said, you're welcome to look over the docs PRs that have happened so far.

- https://github.com/hashicorp/vault/pull/7993
- https://github.com/hashicorp/vault/pull/8220

You did actually just remind me that I do need to document one last parameter that was added afterwards, [this one](https://github.com/hashicorp/vault-plugin-auth-kerberos/pull/43/files#diff-2a66a49ce9a1ffa85b6805fbf4d82b6aR49), which is needed at the login endpoint. We've found that some Active Directory servers don't support FAST negotiation, and so if that's what you're using for LDAP, you'll need to set that parameter to true when logging in.

I'll add a doc of that last field. Then you'll see the docs when Vault 1.4 GA is released.
