### ISSUE TITLE
http: server gave HTTP response to HTTPS client

### ISSUE THREAD

**Issue by ibsolution-github** [hashicorp/vault#8631]
Hi expert,

i just download Vault and i want to use it.

i start vault server from my config file and disable the tls. when i try to execute command as below  

C:\Development\app\secure>vault operator key-status
Error reading key status: Get https://127.0.0.1:8200/v1/sys/key-status: http: server gave HTTP response to HTTPS client

How to disable the client not send the https traffic ?

regards,

Andy Susanto

**Comment by mocofound** [comment]
Hello!  When learning Vault (for example using `vault server -dev` with TLS disabled/insecure) you can use the following to successfully connect:

Linux:
`export VAULT_ADDR="http://127.0.0.1:8200"`

Windows cmd:
`set VAULT_ADDR="http://127.0.0.1:8200"`

Powershell:
`$env:VAULT_ADDR="http://127.0.0.1:8200"`

**Comment by ibsolution-github** [comment]
I try it before with dev command. 

Now i would like to create empty vault, and use with my apps.

Why when disable tls in vault server doesn't disable tls at vault client ?

Is there any configuration at client side ?

**Comment by tyrannosaurus-becks** [comment]
Hi! Yes, you're right, when you start the Vault server with TLS disabled, the client doesn't know that. That's because normally, the client is running on an entirely separate computer and it's calling remotely to Vault. There's no way for a client to discover where Vault is located because it could be anywhere depending on your set up. That's why you need to `export VAULT_ADDR=http://localhost:8200` (or whatever) on the same machine as where the client is running, to tell the client where to find Vault. 

Here are our full docs on the client! https://www.vaultproject.io/docs/commands/ 

If you have more questions and you're able to user [our forum](https://discuss.hashicorp.com/c/vault/30), that would probably be the best place for them! If for some reason you're not able to follow up there, feel free to continue on here.

Closing this for now. Thank you! :-)
