### ISSUE TITLE
Documentation on setting up haproxy or nginx to redirect to active in HA

### ISSUE THREAD

**Issue by mnikhil-git** [hashicorp/vault#864]
Hi,

Is there a documentation that you can provide that walks through setting up nginx or haproxy to be able to redirect http requests to active/leader vault service in vault HA ?

thanks

**Comment by eyal-lupu** [comment]
+1 however HAProxy configuration should be simple, the interesting thing is how to eliminate the one additional hop required when a stand-by vault server will forward a request to the active one. 

So piggyback on top of the request above I would suggest a new HTTP API in vault:

Technically I guess there is no functional need of HAProxy in-front of vault as vault will do the relay internally. However if one does require HAProxy in front of vault than if vault would have publish a REST api which follows the HAProxy http-check contract we could have saved a hop.

_In 3 lines design:_
* Vault HTTP new API /sys/is-leader (usually OPTIONS method is used for that by HAProxy but it can be configured)
* Leader node returns 200
* Other nodes return 406 (I wouldn’t go with 404 because of the special meaning HAProxy has when using the disable-on-404 directive)

If this was provided HAProxy could easily route directly to the active vault instance without the additional hop (HA -> stand by vault instance -> active vault instance)

**Comment by jefferai** [comment]
Hi there,

Vault already provides this functionality -- see https://vaultproject.io/docs/http/sys-health.html

**Comment by eyal-lupu** [comment]
Yes indeed :-)

Thanks for pointing that out :+1:

**Comment by Venture200** [comment]
Hello guys, @jefferai @eyal-lupu that vault provides /sys/leader endpoint but to determine leader node you have to check json value of its "is_self":true

in haproxy how can I get such check ? in documentation I saw status code, string based but no json value. Maybe I missed something. Any idea how can I do it ?
