### ISSUE TITLE
Cluster node mutual unseal

### ISSUE THREAD

**Issue by delamart** [hashicorp/vault#8655]
If a node in a cluster needs to restart, why can't it unseal by requesting the master key from another running node ?

Nodes in a cluster already have a trust relationship (mTLS) couldn't this be used to share the master key between nodes ?

**Comment by delamart** [comment]
I just realized that the node probably doesn't have access to mTLS secrets if it's sealed.

**Comment by tyrannosaurus-becks** [comment]
Hi! Thanks for your question! Are you aware of our forum located [here](https://discuss.hashicorp.com/c/vault/30)? If possible, it would be great if you could post questions there since we tend to use Github more for bug reports and enhancement requests. However, if that's not possible for you, please do feel free to continue here.

You're correct that when Vault is sealed, it's not making or servicing any requests. You do have some control over its unsealing behavior. By default, it uses the Shamir algorithm for unsealing, but you can instead use a variety of Vault [seals](https://www.vaultproject.io/docs/concepts/seal/). [This guide](https://learn.hashicorp.com/vault/operations/ops-autounseal-aws-kms) adds some color to those concepts.

Closing for now because I don't think there's anything further to do here on our part. Thanks again!
