### ISSUE TITLE
Concept for Token Rotation

### ISSUE THREAD

**Issue by wikiwi** [hashicorp/vault#866]
I'm trying to figure out the most practical way to do Token Rotation.

Currently Vault seems to advocate the use of long living tokens, that are revoked when compromised. This is obvious with the latest addition of `renew-self`, and `revoke-self` to the the default policy. The problem is that a compromise is often unnoticed, and until revocation, an attacker has access to any secret available to that token.

For increased security the tokens should be rotated regularly. This can be done by revoking/expiring a token and issuing a new one using another backend service. I'd like to see first class support integrated into Vault as a form of token self-management.

My idea is to implement a new API path e.g. `/auth/token/rotate-self` that issues a new token with a fresh lease, the same parent and the same policies. At the same time the "old" token should be revoked either immediately, or with a grace period in the form of a short fixed (or configurable?) TTL which gives enough time to deploy the new token. During the grace period another call to `/auth/token/rotate-self` should be prevented otherwise it would be possible to create more than one valid token.

Any thoughts?

**Comment by jefferai** [comment]
Hi there,

Can you please post questions on the mailing list (https://groups.google.com/forum/m/#!forum/vault-tool) rather than in GitHub issues? This gets a lot more eyes on any particular question or idea.

It also prevents problematic issue workflows for questions where either the issue is closed immediately but then discussion continues on a closed issue; or, the issue is not closed, discussion dies down, and the issue remains open indefinitely waiting for further potential replies.

Thanks!

**Comment by wikiwi** [comment]
Sure! No problem.
