### ISSUE TITLE
Kv2 : capabilities = ["deny"] doesn't take precedence.

### ISSUE THREAD

**Issue by korby** [hashicorp/vault#8662]
**Describe the bug**
A policy with deny takes precedence in kv1 but not in kv2

**Policies**
path "test/*" {
  capabilities = ["list", "create", "update", "read", "delete"]
}
path "test/bb" {
  capabilities = ["deny"]
}

**Expected behavior**
vault kv get test/bb should return permission denied;
If "test" is a kv1 engine it's ok, if it'a a kv2 engine it returns the value of the secret. 

**Environment:**
* Vault Server Version (retrieve with `vault status`):1.3.0
* Vault CLI Version (retrieve with `vault version`): 1.3.4
* Server Operating System/Architecture: Ubuntu

**Comment by tyrannosaurus-becks** [comment]
Hi! Thanks for posting this! Please note that if this were the case, it would be a security issue, and we do ask that if you believe you have found a security issue in Vault, please responsibly disclose by contacting us at security@hashicorp.com rather than posting it publicly on Github.

That said, I have attempted to reproduce this locally like so:

- Using Vault's current master branch, run Vault like this: "$ vault server -dev -dev-root-token-id=root"
- In another window, "$ export VAULT_ADDR=http://localhost:8200"
- Note that Vault comes up with a KV V2 engine mounted at `/secret` by running "$ vault read sys/mounts"
- Write a test value: "$ vault kv put secret/fizz foo=bar"
- Verify the path at which the value lives: "$ vault read secret/data/fizz"
- Write and add a policy called "test" ("$ vault policy create test test-policy.hcl") with the following contents:
```
path "secret/data/*" {
    capabilities = ["list", "create", "update", "read", "delete"]
}
path "secret/data/fizz" {
    capabilities = ["deny"]
}
```
- Create a token with that policy: "$ vault token create -policy test"
- Login with that token: "$ vault login <the token>"
- Verify the policies I'm using: "$ vault token lookup"
- Try to read the secret:
```
$ vault read secret/data/fizz
Error reading secret/data/fizz: Error making API request.

URL: GET http://localhost:8200/v1/secret/data/fizz
Code: 403. Errors:

* 1 error occurred:
	* permission denied
```

So, I do get permission denied at that path as expected.

Thanks again for opening this issue! If you do still believe you're seeing it, please do reach out to us at security@hashicorp.com with further steps to reproduce it. Closing here for now as we should not continue the conversation here.

**Comment by jefferai** [comment]
See also https://www.vaultproject.io/docs/secrets/kv/kv-v2/#acl-rules

**Comment by kellyhair** [comment]
Hey @korby - ran into the same issue after spinning up a dev instance. 

It comes down to ensuring your put the right path in the policy. In @tyrannosaurus-becks example, they added `data` to the policy. The examples in HashiCorp's example do not call out the `data` directory.

**Comment by TobyOoO** [comment]
Thanks @kellyhair for calling data/ out ! Have been digging on this for a whole day.
The HashiCrop's documentation is way too misleading.
