### ISSUE TITLE
Vault is getting sealed upon issues with object storage

### ISSUE THREAD

**Issue by andrejbiro** [hashicorp/vault#8677]
Hi,
I do not know if this is bug but we have issues with our vault cluster - vault was sealed on APR-02-2020 around 5pm UTC. We have 3 nodes vault cluster. 

Vault binaries version - vault-1.3.2.linux-amd64
For storage we use Oracle OCI object storage and they confirmed there was object storage outage in our region around time of our issues with vault.

Attached logs for APR-02-2020 for all three vault nodes in cluster.

Could you please check what went wrong that vault get sealed and help to improve vault stability? It is impacting our production customers.

Let me know if you need more info.

Thanks & Regards,
Andrej

[vault_cluster.zip](https://github.com/hashicorp/vault/files/4428859/vault_cluster.zip)

**Comment by tyrannosaurus-becks** [comment]
Hi @andrejbiro ! Thanks for opening this issue. Are you aware of our forum located [here](https://discuss.hashicorp.com/c/vault/30)? If possible, we appreciate it when folks ask questions there because we generally use Github for bugs and enhancement requests.

Regarding those logs, I see "Vault shutdown triggered" in them. There are only three places where that message can originate - they're all in [server.go](https://github.com/hashicorp/vault/blob/master/command/server.go) if you search for that string. The shutdown channel is populated by [this function](https://github.com/hashicorp/vault/blob/f868e231b249d6c08ec5addaae2eeb65839e7f84/command/commands.go#L671). So all it does is listen for shutdown calls from the enclosing environment and respond to them. This is also touched upon [here](https://groups.google.com/forum/#!topic/vault-tool/Y_hYzc89v-w).

If I were in your shoes, I'd check through what may be sending that signal to Vault. You're right, it does appear to correlate with storage, but I doubt it has anything to do with the OCI plugin in Vault. Vault doesn't tend to call SIGINT on itself, or anything like that. You're welcome to look at the code, though, if it would be helpful, it's located [here](https://github.com/hashicorp/vault/tree/master/physical/oci).

Going to close this for now as I don't think anything further is needed on our end! Again, thanks for opening this issue!

**Comment by andrejbiro** [comment]
Hi Becca,
we do not have problem with vault shutdown but with vault sealing.

I think "Vault shutdown triggered" is in logs because I was doing "systemctl restart vault" in attempt to unseal our vaults.  Please have a look at this snippet as I think it is showing the moment when vault got sealed - 
```
Apr 02 17:06:53 vault01 vault[28151]: <head><title>502 Bad Gateway</title></head>
Apr 02 17:06:53 vault01 vault[28151]: <body bgcolor="white">
Apr 02 17:06:53 vault01 vault[28151]: <center><h1>502 Bad Gateway</h1></center>
Apr 02 17:06:53 vault01 vault[28151]: <hr><center></center>
Apr 02 17:06:53 vault01 vault[28151]: </body>
Apr 02 17:06:53 vault01 vault[28151]: </html>
Apr 02 17:06:53 vault01 vault[28151]: .. http status code: 502. Opc request id: "
Apr 02 17:06:53 vault01 vault[28151]: 2020-04-02T17:06:53.615Z [ERROR] core: shutting down
Apr 02 17:06:53 vault01 vault[28151]: 2020-04-02T17:06:53.615Z [INFO]  core: marked as sealed

```

Thanks & Regards,
Andrej

**Comment by tyrannosaurus-becks** [comment]
Hi! It looks like that message originates from [here](https://github.com/hashicorp/vault/blob/master/vendor/github.com/oracle/oci-go-sdk/common/errors.go#L61) and occurs when there's a service failure. If you're seeing Vault seal right after that, that would make sense because Vault needs access to storage to be able to persist changes that arrive from calls being made to it. When Vault seals, it is no longer available to serve traffic, which would be desirable when it's unable to communicate with storage.

**Comment by tyrannosaurus-becks** [comment]
Closing this again as it doesn't seem like an enhancement request or bug report. Thanks again! Our forum is here https://discuss.hashicorp.com/c/vault/30 if you have more questions!
