### ISSUE TITLE
which method does golang use to take request body data in json format in the Post API?

### ISSUE THREAD

**Issue by manjeetsorout** [hashicorp/vault#8774]

**Comment by pcman312** [comment]
Thanks for opening this issue. Are you aware of our forum located here: https://discuss.hashicorp.com/c/vault/30? If possible, we appreciate it when folks ask questions there because we generally use Github for bugs and enhancement requests.

Vault generally uses the POST and PUT methods on endpoints to receive JSON data. Each endpoint is documented in our [API docs](https://www.vaultproject.io/api-docs) with the HTTP method(s) that are supported.

The Vault CLI accepts a flag `-output-curl-string` which can also help create cURL commands to better understand how the HTTP queries are being made. For example:
```shell
$ vault write -output-curl-string kv/foo bar=baz
curl -X PUT -H "X-Vault-Request: true" -H "X-Vault-Token: $(vault print token)" -d '{"bar":"baz"}' http://127.0.0.1:8200/v1/kv/foo
```

**Comment by raskchanky** [comment]
Hi @manjeetsorout 

We haven’t heard back from you on this for a while. I’m going to close this for now, but please feel free to re-open it with additional information!
