### ISSUE TITLE
Vault userpass with password '$' character is failing to authenticate using API

### ISSUE THREAD

**Issue by marimuthuei** [hashicorp/vault#8803]
Vault auth userpass not able to authenticate with API if the password contains '$" character , The same password working fine vault cli command. Attached the screenshot reference.

Vault version : 1.3.2

**Comment by ncabatoff** [comment]
Hi @marimuthuei ,

Thank you for submitting this bug report.

I suspect you're running into issues with quoting and your shell interpreting the `$` as a special character.  You can use the -output-curl-string string on the CLI to see how a given CLI command translates to an API request.  For example:

```
$ vault write auth/userpass/users/nick password='password$'
```

Here I enter `password$` at the prompt:
```
$ vault login -output-curl-string -method=userpass username=nick 
Password (will be hidden): 
curl -X PUT -H "X-Vault-Request: true" -d '{"password":"password$"}' http://localhost:8200/v1/auth/userpass/login/nick
```

When I run the suggested curl command:

```
$ curl -X PUT -H "X-Vault-Request: true" -d '{"password":"password$"}' http://localhost:8200/v1/auth/userpass/login/nick
{"request_id":"3c22853f-159f-38ca-c422-1febd704168f","lease_id":"","renewable":false,"lease_duration":0,"data":null,"wrap_info":null,"warnings":null,"auth":{"client_token":"s.NA0tQfQ7uYrYBAUfEXbJwp7u","accessor":"5puFl77NRuMeBw7sNhqThxxV","policies":["default"],"token_policies":["default"],"metadata":{"username":"nick"},"lease_duration":2764800,"renewable":true,"entity_id":"61b98d77-549e-287d-192d-debf7656090a","token_type":"service","orphan":true}}
```

I'm going to close this because it doesn't look like a bug to me.  Please let us know if you have further questions.
