### ISSUE TITLE
`vault auth -method=github` doesn't prompt for token

### ISSUE THREAD

**Issue by chris-martin** [hashicorp/vault#881]
`vault auth` prompts for a token when `-token` isn't given:

```
$ vault auth
Token (will be hidden): 
```

But when the auth backend is `github`, it just fails.

```
$ vault auth -method=github
'token' var must be set
```

Is this intentional?

```
$ vault --version
Vault v0.4.0
```

**Comment by jefferai** [comment]
Hi @chris-martin ,

It's not that it's intentional, it's that `vault auth` with no backend specified is simply a method of inputting a token and storing it via the token-helper (which currently is only an internal token-helper that places it in `~/.vault-token`. Inputting your token via `vault auth` has no effect if you instead simply place it in that file or if you put it in the `VAULT_TOKEN` env var.

When you specify a method, you are then interacting with that authentication backend. In the case of `github`, the fact that it's looking for a parameter named `token` is just a coincidence (other backends want, say, `username` and `password`).

Hope that helps!

**Comment by chris-martin** [comment]
The explanation of why the two things are not necessarily the same makes sense, but I still feel like this is a useful feature request, in the interest of keeping secrets out of shell history. Maybe there could be a way for auth backends to specify which of its parameters are secrets, so `vault` could prompt for them if missing?

**Comment by jefferai** [comment]
It's something interesting to think about but it's not super simple, and would definitely require an API change, as the CLI is just a wrapper around the JSON API. So there would have to be query endpoints for the CLI to ping the backend and ask what value(s) ought to be kept secret if being entered on the command line.

**Comment by chris-martin** [comment]
Maybe could be done without adding new endpoints? What about specifying a way for failure responses specify which fields were missing from the request. Then the CLI could make an attempt to the API as it does now, read the failure response, prompt for anything that was missing, and then retry.
