### ISSUE TITLE
Clarification on policy priority (deny vs. wildcards)

### ISSUE THREAD

**Issue by chrlwrd** [hashicorp/vault#8813]
**Describe the bug**
When applying two policies to the same secret path, the one with more wildcard segments is treated with lower precedence, even when it includes a `deny` which the [documentation](https://www.vaultproject.io/docs/concepts/policies.html#deny) states takes precedence over all other capabilities.

It's not clear whether this is a bug, and thus the deny policies should take precedence regardless of wildcard use, or whether this is intended behaviour and the suggestion that "deny always takes precedence" is misleading.

**To Reproduce**
Run the server:
```
$ vault server -dev -dev-root-token-id=root

$ export VAULT_ADDR=http://localhost:8200           # Run in each terminal used
```

1. Create test secrets in the default `secret` kv v2 engine (with the root token):
```
$ vault kv put secret/example/foo foo=bar

$ vault kv put secret/example/restricted/bar bar=foo
```

2. Create test policy (with the root token):
```
$ cat > policy1.hcl << EOF
path "secret/data/example/*"
{
  capabilities = ["create", "read", "update", "delete"]
}
path "secret/data/example/restricted/*"
{
  capabilities = ["deny"]
}
EOF

$ vault policy write test policy1.hcl
Success! Uploaded policy: test
```

3. Create token with test policy, then login with it in another terminal and attempt to retrieve `foo` and `bar` secrets. Observe that the "restricted" secret returns permission denied.
```
$ vault token create -policy test

$ vault login <token>

$ vault read secret/data/example/foo
Key         Value
---         -----
data        map[foo:bar]
metadata    map[created_time:2020-04-22T22:42:05.177091646Z deletion_time: destroyed:false version:1]

$ vault read secret/data/example/restricted/bar
Error reading secret/data/example/restricted/bar: Error making API request.

URL: GET http://127.0.0.1:8200/v1/secret/data/example/restricted/bar
Code: 403. Errors:

* 1 error occurred:
	* permission denied
```

4. Create the following wildcard policy (with the root token):
```
$ cat > policy2.hcl << EOF
path "secret/data/example/*"
{
  capabilities = ["create", "read", "update", "delete"]
}
path "secret/data/+/restricted/*"
{
  capabilities = ["deny"]
}
EOF

$ vault policy write test policy2.hcl
Success! Uploaded policy: test
```

5. With the generated token, attempt to read both secrets and observe that the "restricted" secret is now accessible
```
$ vault read secret/data/example/foo           
Key         Value
---         -----
data        map[foo:bar]
metadata    map[created_time:2020-04-22T22:42:05.177091646Z deletion_time: destroyed:false version:1]

$ vault read secret/data/example/restricted/bar
Key         Value
---         -----
data        map[bar:foo]
metadata    map[created_time:2020-04-22T22:42:20.971890857Z deletion_time: destroyed:false version:1]
```

**Expected behavior**
The read on the restricted `bar` secret should (at least according to the documentation) still be denied after `policy2.hcl` has been applied.

**Environment:**
* Vault Server Version: 1.3.4 and 1.4.0
* Vault CLI Version: v1.3.4 and v1.4.0
* Server Operating System/Architecture: Ubuntu 18.04 LTS x86_64 (also tested in the `vault` docker container with the same Vault versions)

**Additional context**
Our use case for this is to allow developers (OIDC auth) and Kubernetes workloads (k8s auth) to access secrets for a given k8s namespace directory (i.e. `secret/<namespace>/foo`) with the same policies, but deny devs access to more sensitive secrets. Ideally we would want to apply a wildcard deny policy at the OIDC layer (i.e. deny at `secret/+/restricted/*`) to prevent having to duplicate policies by separating human/machine access which will get pretty arduous to maintain as we add more and more workloads. We have a lot of policies already!

It's not a huge deal, but if the current behaviour is to be expected then I think it's worth updating the documentation to point out that "deny - Disallows access. This always takes precedence regardless of any other defined capabilities..." is not always the case!

I couldn't find anywhere in the documentation that policy precedence is documented (sorry if I missed something) and only found it by digging into the [code](https://github.com/hashicorp/vault/blob/master/vault/acl.go#L524) which isn't ideal.

Thanks!

**Comment by ncabatoff** [comment]
Hi @chrlwrd,

Figuring out what capability applies to a path is a multi-step process.  The first step is to figure out which matching policies are most specific, by looking at the path matchers they're associated with and determining which are most specific.  Then we look at the set of capabilities provided by that set of most-specific policies, and if any of the capabilities are `deny`, that trumps the others and we return a permission denied.

I think that's implied by the page you linked but I agree it could be made more explicit.  Feel free to submit a PR if you want to give it a try.  Otherwise I'll leave this issue open to track the request and we'll get to it at some point.

**Comment by aphorise** [comment]
Explicit paths with `deny` do indeed take precedence and the [Policy Syntax](https://www.vaultproject.io/docs/concepts/policies#policy-syntax) documentation with the **1 to 5 `P1`+`P2`** rules are helpful to determining overlapping paths and which policy will be applicable in cases of clashes or contentions for the same path(s).

In my experience striving for explicitly path definitions as much as possible without  any overlap or use of multiple `+` or `*` characters is most predicable.

@chrlwrd were the last notes above helpful? - is this issue still applicable for you or are you expecting something further?

**Comment by aphorise** [comment]
Closing due to no follow-up. Please re-open if still relevant.

**Comment by Q-efx** [comment]
Hello everyone, I think I need to reopen (or extent) on this one. 

Lets take a look at this simple policy:

`path "*" {
  capabilities = ["create", "read", "update", "delete", "deny", "sudo"]
}

path "+/data/*" {
    capabilities =["deny"]
}`

You should be allowed to do everything, except reading secrets, but you still can read secrets...

If we add a secret "abc" for example, it works as expected if we edit the policy: 

`path "*" {
  capabilities = ["create", "read", "update", "delete", "deny", "sudo"]
}

path "+/data/abc" {
    capabilities =["deny"]
}`

As far as I understand, the priority is, from non-specific to specific path elements. Since * is super non-specific, it should be behind the data deny policy part. Especially, since deny is above allow...

I just need something to prevent "root admins" reading secrets content...
