### ISSUE TITLE
vault approle read configuration should add commas to token_policies

### ISSUE THREAD

**Issue by juliantaylor** [hashicorp/vault#8836]
vault read  prints the token_policies as a string separated by spaces even if it is a list of objects:

```
# single policy with space
vault write $approle token_policies="a b"
vault read $approle | grep token_policies
token_policies             [a b]
# two policies with comma
vault write $approle token_policies="a,b"
vault read $approle | grep token_policies
token_policies             [a b]
```

these two configurations a very different but one has to use `--format=json` to see the difference

This can confuse users to think policies are space separated for approles (and possibly other auth backends too).

By displaying the data better (e.g. just add a comma) it becomes more clear how a role is to be configured

vault version 1.3.4

**Comment by juliantaylor** [comment]
The issue is about how this is printed by the vault command line tool. There is no way to distinguish between a policy `a b` and two policies `a` and `b`.
This is still the case in vault v1.11.3

**Comment by juliantaylor** [comment]
```
$ vault --version
Vault v1.11.3
$ vault write auth/approle/role/test token_policies="a b"
$ vault read auth/approle/role/test | grep token_policies
token_policies             [a b]
$ vault write auth/approle/role/test token_policies="a,b"
$ vault read auth/approle/role/test | grep token_policies
token_policies             [a b]

```

**Comment by aphorise** [comment]
@juliantaylor - I'm trying to relate to your ask thus my continued questioning. You've mentioned mentioned `-format=json` - there's also `format=yaml`... but in the default `table` view what are you expecting to see if not `[a b]`? can you show an example?

from what I recollect all arrays listed in other table views elsewhere in Vault CLI are the same no?

**Comment by juliantaylor** [comment]
the problem is you allow policy names to contain spaces and delimit them by comma on the command line
but when reading the configuration with out machine readable format a policy with spaces is indistinguishable from two policies

compare the same with json output:

```
$ vault write auth/approle/role/test token_policies="a b"
$ vault read -format=json auth/approle/role/test | jq .data.token_policies
[
  "a b"
]
$ vault write auth/approle/role/test token_policies="a,b"
$ vault read -format=json auth/approle/role/test | jq .data.token_policies
[
  "a",
  "b"
]
```

its a very minor issue, but it does waste some time when people confuse space separation and comma separation.

**Comment by juliantaylor** [comment]
I am expecting following output:

```
$ vault write auth/approle/role/test token_policies="a b"
$ vault read auth/approle/role/test | grep token_policies
token_policies             [a, b]
```
note the comma separating the two policies

**Comment by aphorise** [comment]
I don't think a comma will be possible or compatible with expected behaviour elsewhere that is actually consistent. So in all configs (for role or mount definitions) the policies is a `map` type the same as in other places like for example:

 - [Database Static Roles and Credential Rotation - Step 2: Create a static role](https://learn.hashicorp.com/tutorials/vault/database-creds-rotation#step-2-create-a-static-role)
    > ``` rotation_statements    [ALTER USER "{{name}}" WITH PASSWORD '{{password}}';]```

 - With **`vault read sys/license/status`** - [Control Groups - Lab setup](https://learn.hashicorp.com/tutorials/vault/control-groups#lab-setup)
    > ```
    > autoloaded            map[expiration_time:2022-06-16T21:03:20Z features:...snip...]
    > persisted_autoload    map[expiration_time:2022-06-16T21:03:20Z features:...snip...]
    > ```

In your other case of `policy='a b'` I made a mistake since that would be equivalent to a single policy named 'a b' not `a,b` that's a different string. Simply put these are different polices eg:

```shell
vault policy write 'a b' -<<EOL
path "test" {
  capabilities = ["*"]
}
EOL

# // VS
vault policy write 'b' -<<EOL
path "test" {
  capabilities = ["*"]
}
EOL

vault policy write 'a' -<<EOL
path "test" {
  capabilities = ["*"]
}
EOL

vault token create -policy='a' -policy='b' -policy='a b' | grep policies ;
  # token_policies       ["a" "a b" "b" "default"]
  # policies             ["a" "a b" "b" "default"]
```
 
Hey @juliantaylor why is this an issue for you and why cant the YAML or JSON views suffice for your purposes of distinction? :-)

**Comment by aphorise** [comment]
I dot get where you are coming from and certainly this could still be considered / done irrespective of anything I may be sharing that's just my own.

The only thing I am highlighting is that at present all those map types are rather consistent and perhaps if you made a case of all values being quoted (as opposed to comma) then that could have strong merits as for example you see in some API calls there is SPACE values and in other places "-QUOTE-" SPACE; without that how can you even comma act as a separator - so take or example:

```
# Policies are 'a', b' 'b,a' 'a,b' (4 policies)
# // just comma:
[a, b, b,a, a,b]

# // vs
["a" "b" "b,a" "a,b"]
```

The point being that even the quotes one can make a case against since you can have '"c,a"'as a name of a policy too.

Doing commas only for policies would then leave demands for other places to also be the same - but then this is also not possible in all places and would require selective considerations like in the case `*_statements` as I shared earlier.

The comma in itself in one place and especially via CLI is doable - and I'd bet it would be rather straightforward / easy to achieve this today even with your won build; however matching the same consistent behaviour and output elsewhere is the challenge.

Anyway your issues been open for a couple of year and I thought it could do with some input before it's 3rd anniversary

**Comment by juliantaylor** [comment]
I am not talking about any API's. This issue is purely about the human readable output of the vault command line tool for list values.

the rotation statement you mention is apparently another case of ambiguous output:
as per your documentation rotation statement appears to be a list of strings in the machine readable.
```
# curl output copied from your documentation
{
  # ...snip...
  "data": {
    "db_name": "postgresql",
    "last_vault_rotation": "2019-06-24T10:18:39.766203-07:00",
    "rotation_period": 86400,
    "rotation_statements": [
      "ALTER USER \"{{name}}\" WITH PASSWORD '{{password}}';"
    ],
    "username": "vault-edu"
  },
  # ...snip...
}
# vault read output copied from your documentation
rotation_statements    [ALTER USER "{{name}}" WITH PASSWORD '{{password}}';]
```
so if this is now printed the same as polices are, multiple rotation statements are space separated and thus only separable via the unrelated fact that sql statements end on a semicolon. Though I have not tried m

So this is the exact same issue I have created the issue for.

**Comment by juliantaylor** [comment]
Though fixing may not be worth the effort it is a very minor problem, I just though I'd file it when I ran into it the second time back then, but its not a big deal.
Lets just close this.
