### ISSUE TITLE
Improper Logout Functionality from the Vault UI

### ISSUE THREAD

**Issue by dharavahini** [hashicorp/vault#8839]
I' m using OIDC auth method to authenticate with Vault using a Gmail address .I have noticed the Logout functionality is not properly working from the UI , the session remains active even when the logout function is evoked.Can you please help me how can I resolve the issue ? Thanks 

Version
Vault:1.2.2

**Comment by meirish** [comment]
Hi there! Upon logging out, UI will delete the vault token that it gets when doing the exchange flow with the vault server during OIDC authentication. Clicking "Revoke Token" in the User menu will revoke that token from the Vault server.

What behavior are you seeing? What are you expecting to see?

**Comment by dharavahini** [comment]
@meirish

**Comment by dharavahini** [comment]
@meirish Thanks for the response. We would still be able to use the vault token from the browser cookie even after the logout. Shouldn't the token be revoked/expired on logout ?

**Comment by meirish** [comment]
@dharavahini sorry for the delayed response. The UI deletes the token from the browser storage when logging out. We do have an explicit "revoke token" button that I mentioned above. The suggested way to control session lifetime is tuning the TTL of whatever auth method you want to use. The UI will attempt to renew the token if you are logged in and using the UI (it will check to see if it needs renewal when executing network requests). Revocation isn't the default because depending on how you authenticated, it may not be the desired behavior.

**Comment by hellobontempo** [comment]
Hi @dharavahini - closing out this issue as it looks like your question was answered. Please feel free to reopen if you need further clarification on anything 🙂
