### ISSUE TITLE
Can I encrypt thousands of datas at one eaas api call

### ISSUE THREAD

**Issue by ustccq** [hashicorp/vault#8882]
When I flow the step [here](https://learn.hashicorp.com/vault/developer/eaas-transit#step-2-encrypt-secrets) to encrypt my datas stored in mysql(an ETL process).
Can I just put thousands of plaintext data(like sns of 1000 people's) in the api request' body, and then get seperated ciphertexts back by the order I just sent?
I don't think it's a good idea to request for 1000 times here.
And I don't want call the api mentioned in step6 to get a pair of plaintext and ciphertext of one key back.Because the client need to obey more princples, like destroy the plaintext of key after its use, that will make our chain longer.

Need your advise, that will be much helpful

**Comment by pcman312** [comment]
Thanks for opening this issue. Are you aware of our forum located here: https://discuss.hashicorp.com/c/vault/30? If possible, we appreciate it when folks ask questions there because we generally use Github for bugs and enhancement requests.

Regarding providing multiple plaintext values to be encrypted by the transit engine, you can use the `batch_input` field to provide multiple values: https://www.vaultproject.io/api-docs/secret/transit#batch_input. Hopefully this helps answer your question!
