### ISSUE TITLE
List all key ring present

### ISSUE THREAD

**Issue by rohan2546** [hashicorp/vault#8921]
List all key ring present for a user. I am using Postman for that and also cli, if a ring named my-key exist and again a call is made to create my-key, it creates my-key and doesn't state mny-key already exists.

Is there a workaround for this problem?

**Comment by pcman312** [comment]
Thanks for opening this issue. Are you aware of our forum located here: https://discuss.hashicorp.com/c/vault/30? If possible, we appreciate it when folks ask questions there because we generally use Github for bugs and enhancement requests.

Forgive me but I'm not sure I entirely understand your question. Most of the POST endpoints in Vault are upsert commands. Meaning it doesn't check if a value currently exists prior to saving the new one. There are exceptions to this, but as a general rule this is the case.
