### ISSUE TITLE
[1.3.x] make bootstrap fails due to golint problem

### ISSUE THREAD

**Issue by tonyespy** [hashicorp/vault#8927]
**Describe the bug**
When I try to build vault 1.3.x on an Ubuntu 18.04 LTS system, the make bootstrap step fails with the following error:

```
espy@sumo$ make bootstrap 
Installing/Updating github.com/elazarl/go-bindata-assetfs/...
Installing/Updating github.com/hashicorp/go-bindata/...
Installing/Updating github.com/mitchellh/gox
Installing/Updating golang.org/x/tools/cmd/goimports
Installing/Updating golang.org/x/tools/cmd/goimports
Installing/Updating github.com/client9/misspell/cmd/misspell
Installing/Updating github.com/golangci/golangci-lint/cmd/golangci-lint
# github.com/golangci/golangci-lint/pkg/golinters
../dev/go/src/github.com/golangci/golangci-lint/pkg/golinters/golint.go:21:14: l.LintPkg undefined (type *"github.com/golangci/lint-1".Linter has no field or method LintPkg)
../dev/go/src/github.com/golangci/golangci-lint/pkg/golinters/gomnd.go:13:6: cannot use magic_numbers.Analyzer (type *"github.com/tommy-muehle/go-mnd/vendor/golang.org/x/tools/go/analysis".Analyzer) as type *"golang.org/x/tools/go/analysis".Analyzer in array or slice literal
Makefile:139: recipe for target 'bootstrap' failed
make: *** [bootstrap] Error 2
espy@sumo$ go version
go version go1.12.17 linux/amd64
espy@sumo$ git show HEAD
commit c82e1e69178596b9dddccc9d187a09f25c09ddba (HEAD -> 1.3.5, tag: v1.3.5, origin/rel-1.3.5)
Author: Mike Jarmy <mjarmy@gmail.com>
Date:   Tue Apr 28 17:43:11 2020 -0400

    release: publish v1.3.5

```
**To Reproduce**
1. Clone vault (outside of **GOPATH** as recommended) and checkout a 1.3.x tag
2. Run `make bootstrap`
3. See lint failure

Removing the following line from the **EXTERNAL_TOOLS** variable in the Makefile is a temporary fix for this issue:

`github.com/golangci/golangci-lint/cmd/golangci-lint
`

**Expected behavior**
`make bootstrap` succeeds with no errors

**Environment:**
* Vault Server Version (retrieve with `vault status`): 1.3.x
* Vault CLI Version (retrieve with `vault version`): NA
* Server Operating System/Architecture: Ubuntu 18.04 LTS (amd64)

Vault server configuration file(s): NA

**Comment by pcman312** [comment]
Hi @tonyespy ! Thanks for the issue report. Unfortunately this issue was caused by some changes made in the golangci-lint package. We've fixed this issue in 1.4.x as well as [master](https://github.com/hashicorp/vault/pull/8846), however we don't have any plans to backport it to the 1.3.x series at this time. I recommend utilizing the workaround you described (removing golangci-lint from the `EXTERNAL_TOOLS` variable) when you are building 1.3.x. I'm sorry you have to do this, but we are limiting changes going into the 1.3.x line now that 1.4.x has been released.
