### ISSUE TITLE
Default TTL unit not the one displayed

### ISSUE THREAD

**Issue by baptiste-dauphin** [hashicorp/vault#9043]
**Describe the bug**
When creating a new `role` in a `pki`, under `Options` when I modify the default 30 in unit : `seconds` for `TTL` and `Max TTL` by 31536000, after save, I can see that the actual TTL value recorded by Vault UI is 1892160000.

**To Reproduce**
1. Create Pki role
2. Set TTL value to 31536000 seconds
3. See that the TTL is not 31536000

**Expected behavior**
I expect a `TTL` and `Max TTL` of 31536000 as I filled (and not 1892160000)

**Environment:**
* Vault Server Version (retrieve with `vault status`): 1.3.4
* Vault CLI Version (retrieve with `vault version`): Not Used
* Server Operating System/Architecture: Debian 9 64 bits

**Additional context**
All operations are exclusively done in Vault UI
![vault_role_creation](https://user-images.githubusercontent.com/22060352/82463858-a242ba80-9abd-11ea-86d6-bd776d071bf1.png)
![vault_role_details](https://user-images.githubusercontent.com/22060352/82463860-a2db5100-9abd-11ea-9d7e-84b4268efa2c.png)

**Comment by austingebauer** [comment]
Thanks for opening this bug, @baptiste-dauphin. 

I was able to reproduce this using Vault 1.3.4 up to Vault 1.4.1. It appears the Vault UI is sending `31536000m` instead of `31536000s` for the `ttl` and `max_ttl`. The values come back with a unit of seconds from the api, which is why you're seeing `1892160000` on the role. This is a bug in the UI.

This is fixed in the Vault master branch as a result of work related to https://github.com/hashicorp/vault/pull/8743. As a workaround until that fix is released, toggling the TTL unit select box from seconds->minutes->seconds causes the UI to appropriately send `31536000s` as the value.

**Comment by baptiste-dauphin** [comment]
All right, so I think we can close this issue :)
