### ISSUE TITLE
how to use vault for docker env variables

### ISSUE THREAD

**Issue by prabhinmp** [hashicorp/vault#9067]
how to use vault for docker env variables,
such as db username pass etc

**Comment by austingebauer** [comment]
Thanks for opening this issue. Are you aware of our forum located here: https://discuss.hashicorp.com/c/vault/30? If possible, we appreciate it when folks ask questions there because we generally use Github for bugs and enhancement requests.

You can find instructions on how to run Vault using Docker at https://registry.hub.docker.com/_/vault/.
