### ISSUE TITLE
identity/oidc/introspect fails to work with sdk

### ISSUE THREAD

**Issue by gregkeys** [hashicorp/vault#9080]
**Describe the bug**
https://www.vaultproject.io/api-docs/secret/identity/tokens#introspect-a-signed-id-token seems to only work with when called specifically with a POST request e.g. using curl. the sdk write method fails to return any results.

**To Reproduce**
1. Run `vault read identity/oidc/token/<rolename>`
2. Run `vault write identity/oidc/introspect token=<jwt_response> client_id=<client_id>
`
3. no response

**Expected behavior**
expect to receive 
```json
{
  "active": true
}
```

**Environment:**
* Vault Server Version (retrieve with `vault status`): 1.4.1
* Vault CLI Version (retrieve with `vault version`): 1.4.1
* Server Operating System/Architecture: windows wsl using ubuntu

Using curl directly seems to work as expected
```bash
$ curl \
    --header "X-Vault-Token: ..." \
    --request POST \
    --data @payload.json \
    http://127.0.0.1:8200/v1/identity/oidc/introspect
```

**Comment by austingebauer** [comment]
Thanks for opening this issue, @gregkeys. 

Responses from some of the identity token endpoints are intentionally compliant with OIDC standards so that they can be directly usable by other applications and JWT/OIDC libraries. The Vault CLI expects to parse responses from the Vault API that have a well-defined structure. In this case, the Vault CLI does not output the response from `vault write identity/oidc/introspect ...` because the response doesn't match the structure it expects. This is intentional as the Vault CLI doesn't aim to be a replacement for something like curl.

**Comment by gregkeys** [comment]
ok, thank you for that explanation.

I must have missed that in the documentation

**Comment by austingebauer** [comment]
Absolutely, glad to help.
