### ISSUE TITLE
How to change logic cache vault

### ISSUE THREAD

**Issue by solitarysp** [hashicorp/vault#9084]
The default vault uses local cache.
I want to change the logic to using cache with redis.
How to change logic cache vault ?

**Comment by austingebauer** [comment]
Thanks for opening this issue. Are you aware of our forum located here: https://discuss.hashicorp.com/c/vault/30? If possible, we appreciate it when folks ask questions there because we generally use Github for bugs and enhancement requests.

There is currently not a way to change Vault or Vault Agent to use redis as a cache.
