### ISSUE TITLE
unable to register plugin because lstat not installed on centos7

### ISSUE THREAD

**Issue by Tylerlhess** [hashicorp/vault#9130]
**Describe the bug**
Cannot register a new plugin as lstat not on distro.

**To Reproduce**
1. Be on centos7 install without lstat
2. Run `vault plugin register -sha256=... database oracle-database-plugin`
3. See error

Error registering plugin oracle-database-plugin: Error making API request.

URL: PUT http://127.0.0.1:8210/v1/sys/plugins/catalog/database/oracle-database-plugin
Code: 500. Errors:

* 1 error occurred:
	* error while validating the command path: lstat /etc/vault.d/plugins/oracle-database-plugin: no such file or directory

The plugin is in the correct plugin folder

**Expected behavior**
I expect it to register the plugin.
Having a check to make sure lstat is available and if not fall back to normal stat.

**Environment:**
* Vault Server Version (retrieve with `vault status`): 1.3.1
* Vault CLI Version (retrieve with `vault version`):v1.3.1
* Server Operating System/Architecture:  Centos7

Vault server configuration file(s):

```hcl
# Paste your Vault config here.
# Be sure to scrub any sensitive values
```

**Additional context**

**Comment by Tylerlhess** [comment]
OK after taking the time to cool off and write up the ticket. I was able to reverse engineer that vault was writing to sys/plugins/catalog/database/catalog/<name> and using the arguments of name sha256 and command was able to get the deregistered plugin re-registered without verification using lstat. So this is much less important to me but is still a bug.

**Comment by aphorise** [comment]
@Tylerlhess - is there anyway to get a VM image (vagrant or otherwise) that mimics the issue you were facing? (on the register step) - I've tried recreating this but there's a lot of dependencies specific to Oracle - and I've also not faced any such issues with the other plugins that I've attempted (on Centos7)

Some notes of additional considerations specific to **Centos** maybe a good addition in the documentation section of this plugin - however I do not think this is a bug here or rather it's some quirk specific to Centos that should not be of focus. In my mind there's very little difference between **`stat`** vs **`lstat`** where the former `stat` typically interfaces via `lstat` anyway in most Linux distros.

**Comment by aphorise** [comment]
@calvn any chance this can be given some priority? - technically `stat` is POSIX compliant and can be exepcted to be always present vs `lstat` that's common although not always present.

**Comment by HridoyRoy** [comment]
Hi @Tylerlhess ,
Thanks for submitting this issue!

It seems like `error while validating the command path` is happening because Vault is trying to evaluate a symlink to `/etc/vault.d/plugins/oracle-database-plugin` and using `lstat` to do so. This can be traced down to the code block:

```		
fi, err := os.Lstat(dest)
		if err != nil {
			return "", err
		}
```

Looking into the implementation of os.Lstat, it seems like the error itself is coming from the function `lstatNoLog` [here](https://go.dev/src/os/stat_unix.go), which is a Syscall, not a separate application. According to the man page, this syscall has been around since the same kernel version as stat (version 1.0), so it's unlikely that one exists and the other doesn't. 

Rather, it's more likely that you're seeing this error because the plugin file is missing or the command parameter is incorrect.
