### ISSUE TITLE
Revoking certificates produces high CPU load

### ISSUE THREAD

**Issue by HarryBo112** [hashicorp/vault#9176]
**Describe the bug**
Revoking certificates takes a long time while producing heavy CPU load.
It takes up to 2-3 seconds to revoke a single certificate, and produces > 70% CPU load while revoking.
Our CRL contains 16.9k revoked certs.

**To Reproduce**
* run a vault containing a CRL with ~17k revoked certs
* issue and revoke certs
* "measure" time and CPU usage

**Expected behavior**
I would have expected that a revocation is more like a "cheaper" operation, like adding the Cert to the CRL and signing it again.

**Environment:**
We've originally experienced this issue with vault 1.1.2, and then also checked with vault 1.4.2.
1.4.2 seems to be a little quicker, but still takes up to two seconds per revocation.

The CRL contains 16.9k revoked certs and has a size of ~650k.

Originally, we were using the Postgres Backend, and were suspicious that this issue could be related to the Postgres. 
But the DB has shown max. 10% CPU usage with max. 15 IOPs (both read and write), and it also occured with a stronger DB instance (AWS m5.large)

We've also tested with the filesystem backend, the issue also occurs. 

vault has been running on different Machines, amongst them an AWS m5.large

**Comment by nrdxp** [comment]
We've recently experience this issue in our own infrastructure. Because of an issue during our initial cluster bootstrap that I do not yet fully understand, in one of our clusters we had about 96,000 expired leases. We eventually realized this after the fact because our vault snapshots grew to over 1GB in size.

After issueing the order from the UI to start processing these and cleaning things up we experienced some sluggishness during otherwise unrelated operations due to high CPU usage. Also, about 24 hours later, we are down to about 77,000 expired leases and because of the slow handling it will probably take almost a full week at this pace to process them all.

**Comment by hsimon-hashicorp** [comment]
Hi folks! Revocation is always a much more resource-intensive operation. I recommend reading the [performance tuning](https://learn.hashicorp.com/tutorials/vault/performance-tuning?in=vault/operations) guide for more tips on how to handle this.

**Comment by aphorise** [comment]
There are improvements to the revocation manager - which queues revokes when they are happening on mass or at the same time so that does do revokes dont account for the bulk of the CPU and that user requests can continue to be served. They may take longer to revoke but at least at lower CPU load.

I'm closing issue as there's been no updates in over 2 years from the requester.
