### ISSUE TITLE
Generate SSL certificates for servers

### ISSUE THREAD

**Issue by arthurtsang** [hashicorp/vault#929]
I read the PKI backend documentation and love the concept of short lived certificate/keys.  we have a bunch of servers running nodejs and dropwizard.  what happens when the certificate expires?  we'll have to request a new one and restart the server?  i do not aware how to renew the certificates/keys on a running server instance.  so we'll kill all connections on a server in a short period of time?  

Thanks,
--arthur

**Comment by jefferai** [comment]
Hi @arthurtsang,

Can you please post questions on the mailing list (https://groups.google.com/forum/m/#!forum/vault-tool) rather than in GitHub issues? This gets a lot more eyes on any particular question or idea.

It also prevents problematic issue workflows for questions where either the issue is closed immediately but then discussion continues on a closed issue; or, the issue is not closed, discussion dies down, and the issue remains open indefinitely waiting for further potential replies.

Thanks!
