### ISSUE TITLE
selectable and templatable access control models

### ISSUE THREAD

**Issue by promptio** [hashicorp/vault#934]
I see some chatter about the ACL/Policy models changing in the future? Is it possible to design for interchangeable/multiple models? RBAC /MAC and Custom as authn/z is now?

What about using an existing policy language as well? [https://github.com/joyent/node-aperture] (Joyents Aperture)

**Comment by jefferai** [comment]
This work is already complete; see https://github.com/hashicorp/vault/pull/914

Do you have specific needs that are not addressed by it?

**Comment by promptio** [comment]
nice, you work fast! How about a use case:

Alice requests access to secret file/key, the system checks her LDAP account then checks to see if she is a member of the local security administrators "blue" group. She is granted access if all conditions are met.

**Comment by jefferai** [comment]
Hi there,

We're not going to build in checks against external systems into the policy level, for various reasons. But this kind of use-case is already supported -- not certain about if this exact use case is supported by the actual LDAP backend -- but conceptually it's totally possible. You can have an authentication backend run checks against whatever resource it's using for authentication and assign Vault policies based on this (e.g., the authentication backend is responsible for then deciding authorization). Those Vault policies then control access to resources within Vault.

So rather than an access-time check against an external resource (e.g. LDAP), it's an access-time check against Vault, but where the Vault policies are controlled by the external resource.

**Comment by promptio** [comment]
Thanks Jeff.
