### ISSUE TITLE
cannot unmount pki backend

### ISSUE THREAD

**Issue by mtougeron** [hashicorp/vault#946]
When I try to unmount a pki backend I'm getting the following error.

```
$> vault unmount test-rootpki
Unmount error: Error making API request.

URL: DELETE https://REDACTED:8200/v1/sys/mounts/test-rootpki
Code: 400. Errors:

* failed to revoke 'test-rootpki/root/generate/exported/cef77206-5533-183a-668a-b7bf2c38b0b7' (1 / 1): failed to revoke entry: Error encountered during CRL building: Error fetching CA certificate: stored CA information not able to be parsed
```

Is there a way I can force the unmounting? Our backend is using Consul.

**Comment by jefferai** [comment]
Hi Mike,

I wrote back on the mailing list thread a couple of days ago asking for the CLI commands you used to get to this point. Any chance you can get them to me? Being able to reproduce this would help.

Thanks!

**Comment by mtougeron** [comment]
Sorry, got caught up in a fire-drill. I'm trying to figure out how I got to this state. I can't seem to reproduce it yet. I'm working on it this morning though. I "think" it has to do with how I ran `vault write test-rootpki/config/urls issuing_certificates="$VAULT_ADDR/v1/test-rootpki/ca" crl_distribution_points="$VAULT_ADDR/v1/test-rootpki/crl"` Where `$VAULT_ADDR` is set to the domain name we use.

**Comment by mtougeron** [comment]
@jefferai until I can figure out how to reproduce this, is there a way I can force an unmount of this backend?

**Comment by jefferai** [comment]
@mtougeron The reason I was asking was that knowing how it got into that state would help me give you the correct way to force it. Otherwise I can't think of a way to do it without a code change -- which may be a fine code change anyways, but will require longer to get implemented and send you a binary.

**Comment by jefferai** [comment]
@mtougeron I think I reproduced it. Let me get back to you.

**Comment by jefferai** [comment]
@mtougeron So I think what is happening is that when you use an internally-generated CA certificate it registers a lease. That way when it expires it can write itself to its own CRL, which is generally good practice. I think I may have an out-of-order bit of logic there where it should write the CRL first, then be deleted from storage, but it's instead doing the opposite. I haven't confirmed/verified all of this yet, but it's my working theory.

Let me track this down. I fear that I may have to send you a binary that has a workaround to let you unmount.

**Comment by mtougeron** [comment]
Okay, thanks for looking into it! It isn't a huge priority for the fix, we can wait until the next Vault release if necessary. Thankfully I named it `test-rootpki` :)

**Comment by jefferai** [comment]
@mtougeron OK, so the only way I can reproduce it is if I:

1. Generate a root cert using the `/root/generate` path -- this creates a lease for the root cert
2. Use the `/intermediate/generate` endpoint to generate a CSR, which (as according to documentation) replaces the CA cert in the backend with the new generated private key
3. Never upload a signed cert
4. Attempt to unmount

Does that sound like it might be what you did?

What happens here is that there really is no CA in the backend, so when it tries to load it to build a CRL for the lease created in step 1, building the CRL fails. Since this fails and returns an error, the backend can't be unmounted.

There are a few potential ways to solve this -- one on the preventative side, and one on the palliative side. I still have to think about which is a better idea, or both. On the palliative side, I can put in a way for a backend to check whether they are tainted -- a status that happens only when they're being unmounted. Since unmounting removes the backend storage anyways, there's no need to build a CRL -- it won't be accessible. So the CRL function can, in that instance, simply exit out early with success.

The preventative approach is to consider not allowing CA certificates to be changed once one has been generated for a backend, but that's an idea that we rejected before and I don't think the reasoning has changed.

**Comment by mtougeron** [comment]
Yes, very similar process. I was having trouble getting the signed cert imported. It kept giving me errors because I was doing it wrong so I then tried to unmount it.

**Comment by jefferai** [comment]
Great. That PR fixes it, but I'm waiting internally to see if another approach is preferred.

**Comment by mtougeron** [comment]
Awesome, thanks!

**Comment by jefferai** [comment]
@mtougeron If you can replace your binary with a build from `master` (I can provide one if you need) it should fix your problem.

**Comment by mtougeron** [comment]
Thanks!

**Comment by jefferai** [comment]
Please do let me know if you replace your binary with a master build and it *doesn't* work. Or if you need a 0.4.1 with this cherry-picked on top.

**Comment by mtougeron** [comment]
I'm not sure how to build from master for this. I was planning on just waiting for the 0.5 build to be released.

**Comment by jefferai** [comment]
I can make you a build. Which platform/bits, and do you want it based off of 0.4.1 or master?

**Comment by mtougeron** [comment]
I'm presuming it has to be deployed on the server. If that's the case, I'd rather just wait. It isn't impacting us unless I do a `vault mounts` and my ocd kicks in. :P

If it is for a client build, I'm running OS X 10.11.2 (El Capitan)

**Comment by jefferai** [comment]
Yep, server. No problem waiting then. Hopefully what I was able to replicate (and fix) matched what happened to you.
