### ISSUE TITLE
Add option to secure v1/sys/health and other endpoints

### ISSUE THREAD

**Issue by SledgeHammer01** [hashicorp/vault#9461]
v1/sys/health endpoint is currently unsecured. Would like to see a way to secure it with the client token, etc as the other endpoints. It is a security concern to expose internal information. Also see some of the other rest endpoints are not secured.

**Comment by irbekrm** [comment]
Hi, is there a plan to actually do this @ncabatoff ?

We're thinking to potentially use this endpoint to verify that Vault is running and reachable _before_ calling auth endpoints that would give us the actual token.

Do you think this is not a good idea as in the future calling the endpoint might potentially require auth?

(For the context, this is for a tool that users would install in their Kubernetes cluster that would talk to to their Vault (https://github.com/cert-manager/cert-manager/issues/4620) so we  wouldn't have control or visibility over whether the endpoint gets secured by users or not)

**Comment by marcboudreau** [comment]
@SledgeHammer01 We've addressed this issue in the 1.16.1 release of Vault, but in a slightly different approach. We 
analyzed all endpoints that do not require a valid Vault token and their responses to determine what sensitive information was being disclosed. We were able to categorize this sensitive information in the following categories:
- version/build information
- cluster name (since it is user specified)
- IP/hostname addresses

Here is the list of endpoints the provide some of the above sensitive information:
- `sys/health` (version & cluster name)
- `sys/leader` (addresses)
- `sys/seal-status` (version & cluster name)
- `sys/replication/status` (addresses)
- `sys/replication/dr/status` (addresses)
- `sys/replication/performance/status` (addresses)

The approach used to address this issue with the `sys/health`, `sys/leader`, and `sys/seal-status` is to provide settings that redact each of the sensitive information categories identified above in the TCP listener stanza of the Vault configuration:
- [`redact_addresses`](https://developer.hashicorp.com/vault/docs/configuration/listener/tcp#redact_addresses)
- [`redact_cluster_name`](https://developer.hashicorp.com/vault/docs/configuration/listener/tcp#redact_cluster_name)
- [`redact_version`](https://developer.hashicorp.com/vault/docs/configuration/listener/tcp#redact_version)

By default these settings are `false`, which preserves the legacy behaviour, but if they are set to `true`, the corresponding sensitive information is redacted from the response, **unless a valid Vault token, regardless of its associated policies, is included in the request.**

The approach used to address this issue with the remaining replication related endpoints consists of providing a setting, [`disable_replication_status_endpoints`](https://developer.hashicorp.com/vault/docs/configuration/listener/tcp#disable_replication_status_endpoints), that disables the replication status endpoints. By default, this setting is `false`, which preserves the legacy behaviour, but if it is set to `true`, requests sent to this endpoint will result in an HTTP 404 response with an error message indicating that the path is disabled.

These settings are scoped to the TCP listener under which they are set. So it is possible to define multiple TCP listeners that are configured differently with respect to the above described settings.

**Comment by marcboudreau** [comment]
I am going to go ahead and close the issue.
