### ISSUE TITLE
Use os.Setenv to set environment variables for a more seamless experience

### ISSUE THREAD

**Issue by dvbnrg** [hashicorp/vault#9501]
When starting vault server, environment variables can and should be set automatically with the os package.
something like this:

Note: these variables were taken from the tutorial

os.Setenv(VAULT_ADDR, 'http://127.0.0.1:8200')
os.Setenv(VAULT_DEV_ROOT_TOKEN_ID, "s.XmpNPoi9sRhYtdKHaQhkHP6x")

If someone can elaborate as to when these variables are being generated, I can probably do it myself.

**Comment by ncabatoff** [comment]
Hi @dvbnrg,

I may be misunderstanding what you're proposing, but it sounds like you're suggesting that after running `vault server`, you would like to see some variables populated in your shell's environment.  Unfortunately that's not possible: a process can only modify the environment seen by it and its children.  Since `vault server` is a child of your shell, it's impossible for Vault to modify the shell's environment.

The way I do this when testing things is something like this script:

```
kill `ps axuw |grep 'vault server -dev' |awk '{print $2}'` && sleep 1
vault server -log-level=debug -dev-listen-address=0.0.0.0:8200 -dev -dev-root-token-id=devroot 
while ! nc -w 1 localhost 8200 </dev/null; do sleep 1; done

export VAULT_ADDR=http://localhost:8200
export VAULT_TOKEN=devroot
```

The catch is that you can't *run* this script, you have to use the bash `source` builtin.  So if you put the above into a file named `myvault`, you'd run

```
$ source myvault
```

rather than 

```
./myvault
```

**Comment by dvbnrg** [comment]
Understood. Thank you for the feedback!
