### ISSUE TITLE
Vault:1.4.3 can not start with KMS auto unseal with IAM Role 

### ISSUE THREAD

**Issue by yevgeniyo** [hashicorp/vault#9568]
**Describe the bug**

With version 1.4.3 KMS auto unsealing with IAM Role is not working
Vault service is not starting at all, no output

/vault/logs # vault server -config=/vault/config/
^C

**To Reproduce**

1. Run vault 1.4.3 on docker with config:
    "seal": { 
      "awskms": {
        "region": "your region",
        "kms_key_id": "your key"
      }
    }

2. Check logs

Vault server configuration file(s):

```hcl

{
    "backend": {
      "mysql": {
        "address": "",
        "username": "",
        "password": "",
        "database": "",
        "ha_enabled": "true" 
      }
    },
    "listener": {
      "tcp":{
        "address": "0.0.0.0:8200",
        "tls_cert_file": "/vault/config/ssl/vault.crt",
        "tls_key_file": "/vault/config/ssl/vault.key"
      }
    },
    "ui": true,
    "log_level": "DEBUG",
    "seal": { 
      "awskms": {
        "region": "",
        "kms_key_id": ""
      }
    }
}
```

**Additional context**

Checked the same setup with 1.3.7
All works as expected

**Comment by kalafut** [comment]
Hi. Possibly the same as #8844? Note the comments at the end of that discussion.

**Comment by yevgeniyo** [comment]
Looks like it has the same source

**Comment by danjbh** [comment]
See my recent comment in #9576 re: `ui = false` and logging issues.

**Comment by danjbh** [comment]
I also encountered this issue and wasn't able to figure out what was going on until we set `ui = false` in the config, which then seemed to allow it to log some useful information.

Anyhow, my issue turned out to be a problem w/ the role -- I had it scoped to the wrong namespace.

Although I'd be interested in knowing if anyone else suddenly starts seeing error logs if they set `ui = false`. In the meantime, make sure your roles are setup correctly!

**Comment by kizoojun** [comment]
govo

**Comment by tvoran** [comment]
@yevgeniyo Have you tried setting the environment variable `AWS_ROLE_SESSION_NAME` to something random in your docker container? 

Otherwise you may be running into an issue with docker and IMDSv2: 

- https://github.com/aws/aws-sdk-go/issues/2972#issuecomment-560568989
- https://github.com/aws/aws-sdk-go/issues/2980
- https://github.com/hashicorp/vault/issues/8847#issuecomment-629297745

So you might try increasing the hop count for the underlying ec2 instances if you can.
