### ISSUE TITLE
SSH OTP documentation/behavior inconsistent

### ISSUE THREAD

**Issue by jefferai** [hashicorp/vault#962]
If an OTP isn't found, `nil` is returned as the response, leading to a 204 return code. If one is found, a response is returned. This isn't reflected in the documentation. Additionally, perhaps if an otp isn't found, an error should be thrown (e.g. 404).

**Comment by vishalnayak** [comment]
@jefferai 
The documentation is fixed by https://github.com/hashicorp/vault/commit/61e0e3dd948ffe7b2f739c7c78d641c9831c00e4

Regarding the response code, there was a thought that verify API should not reveal if the OTP was invalid. Hence this behavior. If I rethink now, it doesn't make sense to respond 204 since it is doing just the same. It's better to just say it was a wrong input. 

I will change it to "400: Bad Request" (for now).

**Comment by jefferai** [comment]
Generally I am in agreement about not revealing whether a credential is valid or not. However, in this case, since it is a one-time-use credential, the act of verification itself makes the credential invalid, right? So an attacker that attempts to verify if the OTP is usable has just made it unusable for any further calls. Plus, on a successful response we are already returning data, so you can easily tell a successful OTP from one that wasn't.

Regarding 400 vs. 404, I think 404 is more correct, as it's not technically a bad request per se, but I think either works so long as it's consistent. I'd also be happy with 403 Forbidden, as in, that OTP is not authorized.
