### ISSUE TITLE
Running vault on windows (from mingw or cygwin)

### ISSUE THREAD

**Issue by BSick7** [hashicorp/vault#974]
Yes. I'm weird. I like running bash on windows.
That being said, I get the following error:
```
$ vault policies
Error initializing client: Error: exit status 126

/C: /C: is a directory
```

The following will work:
```
$ export VAULT_ADDR=...
$ export VAULT_TOKEN=...
$ vault policies
```

The big issue is that I don't know what my `VAULT_TOKEN` is until I run
```
$ vault auth -method=github token=...
Error initializing client to auth: Error: exit status 126

/C: /C: is a directory
```

**Comment by BSick7** [comment]
It's probably also important to mention that someone downloading vault and running vault will not get any usage tips.  This is quite an ugly presentation and appears like vault is broken.

**Comment by jefferai** [comment]
@BSick7 I don't really understand what you mean about not getting usage tips. Running `vault` by itself gives help information.

Regardless, I believe your problem is already fixed in `master` (https://github.com/hashicorp/vault/issues/850), so you can either try recompiling it yourself or wait for 0.5 to release in the next couple of weeks. If you're desperate I can send you a build from master.

**Comment by BSick7** [comment]
@jefferai Forgive me. You're right... just running `vault` will give usage.  I got jumpy and try commands immediately.

I will give `master` a try.  Thanks so much!

**Comment by BSick7** [comment]
Works great! Thanks again @jefferai
