### ISSUE TITLE
Storage tradeoffs documentation

### ISSUE THREAD

**Issue by devops-rob** [hashicorp/vault#9866]
With the different storage backend options available for Vault, it would be great if the documentation would detail the tradeoffs to help us make more informed decisions . Currently it is quite difficult to understand the operational costs of a particular choice against an alternative choice.  I guess what i'm asking is, can you please help us make the right choices for ourselves in the documentation
.

**Comment by aphorise** [comment]
I believe this has since been added to the docs:

 - [Integrated Storage vs. Consul as Vault Storage](https://www.vaultproject.io/docs/configuration/storage#integrated-storage-vs-consul-as-vault-storage)

There's also a note on the learn: [Vault with Consul Storage Reference Architecture](https://learn.hashicorp.com/tutorials/vault/reference-architecture):

> For production: [Integrated Storage](https://www.vaultproject.io/docs/internals/integrated-storage) native to Vault is now recommended rather than using Consul for Vault storage. Use Consul for Vault storage only [when there are clear reasons](https://www.vaultproject.io/docs/configuration/storage#integrated-storage-vs-consul-as-vault-storage).

Hey @devops-rob will this suffice to close or were you wishing to add something more?

**Comment by devops-rob** [comment]
Hi @aphorise I believe so. I opened this issue on behalf of a community practitioner but from my perspective as I understood it fro them, this should be good. Thanks 😊
