### ISSUE TITLE
SSL Certs issued with PKI backend don't work with firefox: sec_error_inadequate_cert_type

### ISSUE THREAD

**Issue by doddo** [hashicorp/vault#987]
Certs I used,  issued with vault internal CA does not work with firefox, it throws sec_error_inadequate_cert_type.  Nothing else that I've seen except for firefox (version 42.0) complains about this. (Safari, Chrome, curl, wget, javax.net.ssl.HttpsURLConnection are all happy with the resulting CA and client certs)

First I build vault from master, mount the pki backend,  create a CA, and add the role I call `test`. Finally I issue a test cert for `semester.test`.

```
./vault -version
Vault v0.5.0-dev (b2e172ede807394fadf845466a3371f27086899b)
./vault mount pki
./vault  mount-tune -max-lease-ttl=87600h pki
./vault write pki/root/generate/internal common_name="Test CA" ttl=87600m
./vault write pki/roles/test allowed_domains="test" allow_subdomains="true" max_ttl="17520h"
./vault write pki/issue/test common_name=semester.test ttl=200h
```
Using the cert and key return from the `vault write pki/issue/test common_name=semester.test 
ttl=200h` command, I start a ssl server.

```
gnutls-serv --x509certfile /tmp/semester.test.pem --x509keyfile /tmp/semester.test.key.pem
Set static Diffie-Hellman parameters, consider --dhparams.
HTTP Server listening on IPv4 0.0.0.0 port 5556...done
HTTP Server listening on IPv6 :: port 5556...done
```
If I now go to the page with curl or wide range of different programs, it works.

This works:
```
curl https://semester.test:5556/ --cacert /tmp/test_ca.crt
wget https://semester.test:5556/ --ca-certificate /tmp/test_ca.crt
```
But, when using firefox  (version 42.0), after importing my `rest_ca.crt` Root CA, it says Secure Connection Failed, with the error code: "Error code: sec_error_inadequate_cert_type". 

[This bz on mozilla.com](https://bugzilla.mozilla.org/show_bug.cgi?id=1049176) seems to be relevant

> When a private root CA has an extendedKeyUsage extension set it its certificate, firefox 31 will refuse to talk to servers certified by it, even if the root CA's cert has been explicitly loaded and trusted as an authority for "identifying web sites".  The error is SEC_ERROR_INADEQUATE_CERT_TYPE.

In that bugzilla, an article [supposedly](https://cabforum.org/wp-content/uploads/Baseline_Requirements_V1_1_8.pdf) from the CA / Browser Forum is referenced. In Appendix B it says:

> Root CA Certificate
> Root Certificates MUST be of type X.509 v3.  
> [...]
> extendedKeyUsage 
> This extension MUST NOT be present. 
> 

But, on my CA cert, that I generated from vault, using in the steps above:

```
-----BEGIN CERTIFICATE-----
MIIDQDCCAiigAwIBAgIUDeXwO+kKdepa++bhohll7dBWMc8wDQYJKoZIhvcNAQEL
BQAwEjEQMA4GA1UEAxMHVGVzdCBDQTAeFw0xNjAxMjkxMzI5MzJaFw0xNjAzMzAw
OTI5MzJaMBIxEDAOBgNVBAMTB1Rlc3QgQ0EwggEiMA0GCSqGSIb3DQEBAQUAA4IB
DwAwggEKAoIBAQDAm33l0Cjo1kYDM5bMAPsbuLABBKPfJZCsWdQWTWROA9xdlZBz
M5WN5RtGPtfNobX9qBxeCqn0X9xJL7ee8e9I/IJc4eZSIUTVIpeKpUeE/Yc7nLqx
tQ7GgMavpGv4UcsWV8vhM62G6wQ8whMvWyRXQZ4oREfTcFcX2+lz/d6yVN60AKqB
tvSoIxngO9Frhp4rDrmb0PHQOo95DKaBlW5LhqhxhsL2NNgGSpe7zlmCXmJz0Jsk
Q4049O94DyCx004lbTXjK5HUInG7he3nmTgWrcGMI2kA7s5uOqyBuJnh0+1qqW1Y
JSL5a4RXjFSWzIzwRYR+1RIIeatqdlndh/75AgMBAAGjgY0wgYowDgYDVR0PAQH/
BAQDAgGuMBMGA1UdJQQMMAoGCCsGAQUFBwMJMA8GA1UdEwEB/wQFMAMBAf8wHQYD
VR0OBBYEFNIyv19n5H7Aku+I4LYpmEcvAtQdMB8GA1UdIwQYMBaAFNIyv19n5H7A
ku+I4LYpmEcvAtQdMBIGA1UdEQQLMAmCB1Rlc3QgQ0EwDQYJKoZIhvcNAQELBQAD
ggEBABBgthjazVvG8XexiwrntRRap34yKtueELfO9EQTUlVEdpVwxeITx03xSBpL
8T+v+FiUS1OPp+KnIy4b+k8tR3czUPXZO0c9VN9hz+dAOSyr3xHqSn6ObKvibh+B
Z36yEAX45iGQdQupvKjuadI3uqXm2HHhTNppBTw6BCF3ZpqzQmaxMf+C/aeOSCuu
Ed/0EX9nO+zmFYbSmDG27RQzng2rDDrfiG3NG0/Oisj4CoIdA4Tzrp84uJ+Lgdv4
00//4t0bkndo07ztdPy5PR+SJ32bMSy+2SLQqBvjQnifRJZoxyvGDKu9O25s6HF1
bhi3LZI7zQSWI7ZSJFhmtqmIn4o=
-----END CERTIFICATE-----
```

It does contain this extension.

```
            X509v3 Extended Key Usage:
                OCSP Signing
```

I am no subject-matter expert, and am by no means sure that there could be no use cases where a CA should not have the eKU on it, but I think it would be good if vault could generate Root CA:s withot `X509v3 Extended Key Usage`.

Either way I am happy as long as I can create certificates from vault, which works well with firefox.

**Comment by jefferai** [comment]
Ugh.

This may or may not present a serious problem, because some crypto stacks (Windows, Go) will only accept certificates that are a subset of the CA's extended key usages. For instance, a comment from the Go source code:
```
// An empty list means ExtKeyUsageServerAuth. Key usage is considered a
// constraint down the chain which mirrors Windows CryptoAPI behaviour,
// but not the spec.
```
So in fact, in Vault master right now, if you generate a CA, it basically specifies *all* extended key usages, and this was required to fix earlier reported issues.

So I'm not sure what the right thing here is. Ideally Vault would support issuing certificates from the root CA without requiring an intermediate to be issued, but I'd prefer broad compatibility over minor inconvenience.

I could get rid of the extended key usages on the root, in favor of not having any extended key usage constraints on a self-signed root, but I don't know if the crypto stacks that validate up the chain will be happy if an intermediate specifies a bunch of ext key usages but they're not present on the root. However, I did just look at DigiCert and this what they do, so probably it's fine.

According to the RFC I can put the "any" extended key usage on the root which should satisfy applications that require some kind of extended key usage to be present, which shouldn't be marked critical, but applications are free to ignore this.

I guess I will simply remove any ext key usage if you're generating a self-signed cert but key the long list of key usages if you're signing an intermediate cert. I *think* that will make everything happy.

**Comment by jefferai** [comment]
Sadly, in terms of figuring out the right thing to do, IETF's own site uses a certificate provider whose root certificate specifies no key usages and only some extended key usages.

**Comment by jefferai** [comment]
So looking at GitHub and Google, their CA certs don't specify extended key usages at all. GitHub's normal cert specifies both key usage and extended key usages, but Google's normal cert, interestingly, specifies no normal key usages at all, only specifying extended key usages.
