### ISSUE TITLE
User interface?

### ISSUE THREAD

**Issue by JensRantil** [hashicorp/vault#988]
The [Use Cases](https://www.vaultproject.io/intro/use-cases.html) page claims that Vault is good for "Employee Credential Storage". This is somewhat true if they know how to use `curl` or `wget`. ;)

On a more serious note, Vault is great for this use case but what's missing is a graphical user interface that would allow less technical users to access secrets in Vault. I therefor propose to create a web UI just [like Consul's web UI](https://www.consul.io/intro/getting-started/ui.html).

Workarounds: I'm not sure, are there any web UIs for Vault already? Maybe Vault related community projected could be listed on a community wiki page here on Github?

**Comment by jefferai** [comment]
> This is somewhat true if they know how to use curl or wget. ;)

Or `vault`...

I don't currently know of any UI projects based on Vault, sorry.

**Comment by jantman** [comment]
Since I happened by this in a Google search...

A search of GitHub I did this morning revealed some Vault UI projects, but I can't tell if they're ready to be used, or even functional. At least one of them looked like it didn't even have any real code yet:

* [AMeng/vault-web: A web interface for Hashicorp Vault](https://github.com/AMeng/vault-web)
* [gambtho/vault-portal: UI for interacting with Vault by HashiCorp](https://github.com/gambtho/vault-portal)
* [mclarke47/web-vault: A web ui for hashicorp vault to help me learn vault and angular 2](https://github.com/mclarke47/web-vault)
* [nyxcharon/vault-ui: A webapp for working with Hashicorp's Vault https://github.com/hashicorp/vault](https://github.com/nyxcharon/vault-ui)

We're probably going to be working on an admin API and UI for Vault (i.e. managing policies, associating policies with the various auth elements like app-id and LDAP users, as well as managing some of the [EC2 auth backend](https://www.hashicorp.com/blog/vault-0.6.html#aws-ec2-auth) stuff). I don't know if we'll (1) be able to release it publicly, and (2) write it to be suitably generic for others to use.

**Comment by jefferai** [comment]
@jantman Vault Enterprise will be gaining a UI soon. The set of functionality it will start with will not be all of Vault's capabilities but it will expand over time.

**Comment by djenriquez** [comment]
We've also been working on a Vault UI written in React. It currently supports Github, Token and Username/Password authentication for secrets and policy management. Feel free to check it out: [djenriquez/vault-ui](https://github.com/djenriquez/vault-ui) + [Docker Hub](https://hub.docker.com/r/djenriquez/vault-ui/).

**Comment by svartulv** [comment]
Are there any plans on bringing some official UI to open source version of Vault?

**Comment by Caiyeon** [comment]
I've been working on a vault UI written with VueJS and vault's native Go API here: https://github.com/Caiyeon/goldfish

It contains features beyond what the vault API offers, like being able to submit change requests to policies and having it approved by admins. Check out the repo for a full list!
