### ISSUE TITLE
cannot load github.com/hashicorp/vault/plugins

### ISSUE THREAD

**Issue by Bhuvaneswari94** [hashicorp/vault#9907]
Description 

Trying to implement db2 database plugin for vault.

Vault version 
C:\>vault --version
Vault v1.3.4

My main.go looks like 
package main
import (
	"github.com/hashicorp/vault/plugins"
)
func main() {
	plugins.Serve(New().(*DB2SQL), nil)
}

and the db2.go file is similar to postgres implementation.

When trying to build the code 

C:\go\src\custom-db>go build
build custom-db: cannot load github.com/hashicorp/vault/plugins: module github.com/hashicorp/vault@latest found (v1.3.7), but does not contain package github.com/hashicorp/vault/plugins

**Comment by pcman312** [comment]
Thanks for opening this issue. Are you aware of our forum located here: https://discuss.hashicorp.com/c/vault/30? If possible, we appreciate it when folks ask questions there because we generally use Github for bugs and enhancement requests.

`github.com/hashicorp/vault/plugins` is not a valid import path because there aren't any files within that package. Additionally, only packages within `github.com/hashicorp/sdk` and `github.com/hashicorp/api` are designed for consumption outside of Vault itself.

If you are building a [Database plugin](https://www.vaultproject.io/docs/secrets/databases/custom) you will want to use the `Serve` function from `github.com/hashicorp/vault/sdk/database/dbplugin`.

A [secrets plugin](https://www.vaultproject.io/docs/internals/plugins) is a slightly different process.
