### ISSUE TITLE
Interactive tutorial link appears to be broken

### ISSUE THREAD

**Issue by l8nite** [hashicorp/vault#997]
Chrome Version 47.0.2526.111 (64-bit) on OSX 10.11.3
This is what's in my URL bar after clicking the link: https://www.vaultproject.io/#/demo/0

**Comment by dmclain** [comment]
From the console of a similar setup (Chrome Version 47.0.2526.106 (64-bit) on OSX 10.10.5)

`Refused to execute script from 'https://www.vaultproject.io/assets/javascripts/application-b281ed49.js' because its MIME type ('binary/octet-stream') is not executable, and strict MIME type checking is enabled.`

It works from Safari though.

**Comment by jefferai** [comment]
@captainill Another one for you maybe? Or is this not an issue with the site but rather what's serving it?

**Comment by captainill** [comment]
@jefferai Hrm yea this might have to do with the updated way we are serving the sites? @sethvargo would be the go to for info on that. Any idea Seth?

Jack actually put the interactive demo together so next steps would be to loop him if needed.

**Comment by jefferai** [comment]
This seems to be fine now.
